Repository StarRocks/starrocks, pull requests merged in 2021-12, with the labels that each got.

#1765 Enlarge runtime_join_filter_pushdown_limit for pipeline query engine
  be/src/exec/vectorized/hash_join_node.cpp
Labels: sig/pipeline

#1757 Declare RowsetWriter::global_dict_columns_valid_info() as a const method
  be/src/storage/rowset/rowset_writer.h
Labels: sig/storage

#1754 Refactor MemTable to pass chunk by const reference
  be/src/storage/vectorized/delta_writer.cpp
  be/src/storage/vectorized/memtable.cpp
  be/src/storage/vectorized/memtable.h
  be/test/storage/vectorized/memtable_test.cpp
Labels: sig/storage

#1762 Optimize Profile for pipeline
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline.h
  be/src/exec/pipeline/pipeline_driver_dispatcher.cpp
  be/src/exec/pipeline/pipeline_driver_dispatcher.h
  be/src/exec/pipeline/query_context.h
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: type/enhancement, sig/pipeline

#1815 Remove Remove redundant if judgments
  be/src/http/default_path_handlers.cpp
Labels: Approved

#1726 Fix PreAggregateTurnOnRule miss project rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/PreAggregateTurnOnRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved

#1826 Remove unused code of RowBatch
  be/src/util/arrow/row_batch.cpp
  be/src/util/arrow/row_batch.h
  be/src/util/arrow/row_block.cpp
  be/src/util/arrow/row_block.h
  be/test/CMakeLists.txt
  be/test/util/arrow/arrow_row_batch_test.cpp
  be/test/util/arrow/arrow_row_block_test.cpp
  be/test/util/arrow/arrow_work_flow_test.cpp
Labels: Approved

#1775 fix the bug of oom in high concurrency
  be/src/common/config.h
  be/src/exec/vectorized/chunks_sorter_full_sort.cpp
  be/src/exec/vectorized/chunks_sorter_topn.cpp
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/runtime/exec_env.cpp
  be/src/storage/vectorized/delta_writer.cpp
  bin/common.sh
  bin/start_be.sh
Labels: Approved

#1773 Fix can not choose shuffle bucket join in plan fragment builder
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: sig/optimizer

#1840 Remove some none vectorized code in storage
  be/CMakeLists.txt
  be/src/storage/CMakeLists.txt
  be/src/storage/generic_iterators.cpp
  be/src/storage/generic_iterators.h
  be/src/storage/iterators.cpp
  be/src/storage/iterators.h
  be/src/storage/merger.cpp
  be/src/storage/merger.h
  be/src/storage/reader.cpp
  be/src/storage/reader.h
  be/src/storage/row.h
  be/src/storage/row_cursor.cpp
  be/src/storage/row_cursor.h
  be/src/storage/rowset/CMakeLists.txt
  be/src/storage/rowset/beta_rowset.cpp
  be/src/storage/rowset/beta_rowset.h
  be/src/storage/rowset/beta_rowset_reader.cpp
  be/src/storage/rowset/beta_rowset_reader.h
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/beta_rowset_writer.h
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/rowset_reader.h
  be/src/storage/rowset/rowset_reader_context.h
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/segment_v2/empty_segment_iterator.cpp
  be/src/storage/rowset/segment_v2/empty_segment_iterator.h
  be/src/storage/rowset/segment_v2/segment.cpp
  be/src/storage/rowset/segment_v2/segment.h
  be/src/storage/rowset/segment_v2/segment_iterator.cpp
  be/src/storage/rowset/segment_v2/segment_iterator.h
  be/src/storage/rowset/segment_v2/segment_writer.cpp
  be/src/storage/rowset/segment_v2/segment_writer.h
  be/src/storage/rowset/vectorized/rowset_writer_adapter.cpp
  be/src/storage/rowset/vectorized/rowset_writer_adapter.h
  be/src/storage/rowset/vectorized/segment_iterator.cpp
  be/src/storage/rowset/vectorized/segment_v2_iterator_adapter.cpp
  be/src/storage/rowset/vectorized/segment_v2_iterator_adapter.h
  be/src/storage/storage_engine.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/task/engine_checksum_task.cpp
  be/src/storage/txn_manager.cpp
  be/src/storage/vectorized/convert_helper.cpp
  be/src/storage/vectorized/convert_helper.h
  be/src/storage/vectorized/merge_iterator.cpp
  be/src/storage/vectorized/meta_reader.cpp
  be/src/storage/vectorized/meta_reader.h
  be/src/storage/vectorized/schema_change.cpp
  be/src/storage/vectorized/schema_change.h
  be/src/storage/vectorized/union_iterator.cpp
  be/test/CMakeLists.txt
  be/test/storage/CMakeLists.txt
  be/test/storage/generic_iterators_test.cpp
  be/test/storage/rowset/beta_rowset_test.cpp
  be/test/storage/rowset/segment_v2/segment_test.cpp
  be/test/storage/vectorized/base_compaction_test.cpp
  be/test/storage/vectorized/cumulative_compaction_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
Labels: sig/storage, type/cleanup

#1822 [pipeline] register fragment context after preparing
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
Labels: sig/pipeline

#1825 Fix limit operator use wrong output columns
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalLimitOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalLimitOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/LimitImplementationRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
Labels: Approved, sig/optimizer

#1809 [Vertical compaction] improve the calculation method of aggregated rows in chunk aggregator
  be/src/storage/vectorized/chunk_aggregator.cpp
  be/src/storage/vectorized/chunk_aggregator.h
  be/test/storage/vectorized/chunk_aggregator_test.cpp
Labels: sig/storage

#1695 BugFix : keep storage_medium property consistent when add partition dynamically
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
Labels: metadata

#1740 Support statement digest
  fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ArrayElementExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ArrayExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BetweenPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CaseExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CastExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CompoundPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ExistsPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FromClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/InPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IsNullPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LikePredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LimitElement.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/OrderByElement.java
  fe/fe-core/src/main/java/com/starrocks/analysis/QueryStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SelectListItem.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SelectStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Subquery.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableRef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TimestampArithmeticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/WithClause.java
  fe/fe-core/src/main/java/com/starrocks/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/com/starrocks/plugin/AuditEvent.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DigestTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#1800 Use ExecEnv->tablet_meta_mem_tracker() to collect the memory statistics() of tablet meta
  be/src/http/action/meta_action.cpp
  be/src/http/default_path_handlers.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/mem_tracker.h
  be/src/storage/rowset/beta_rowset.cpp
  be/src/storage/rowset/beta_rowset.h
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_factory.cpp
  be/src/storage/rowset/segment_v2/column_reader.cpp
  be/src/storage/rowset/segment_v2/column_reader.h
  be/src/storage/rowset/segment_v2/page_handle.h
  be/src/storage/rowset/segment_v2/segment.cpp
  be/src/storage/rowset/segment_v2/segment.h
  be/src/storage/rowset/vectorized/segment_iterator.cpp
  be/src/storage/storage_engine.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
  be/src/storage/tablet_schema_map.cpp
  be/src/storage/tablet_schema_map.h
  be/src/storage/task/engine_clone_task.cpp
  be/test/storage/delete_handler_test.cpp
  be/test/storage/rowset/beta_rowset_test.cpp
  be/test/storage/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/storage/rowset/segment_v2/segment_test.cpp
  be/test/storage/tablet_meta_test.cpp
  be/test/storage/tablet_schema_map_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/vectorized/base_compaction_test.cpp
  be/test/storage/vectorized/cumulative_compaction_test.cpp
Labels: Approved, sig/storage

#1819 Add check if normailzed predicate faild
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/NormalizePredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
Labels: Approved

#1902 Add more check point for large mem allocate
  be/src/exec/vectorized/analytic_node.cpp
  be/src/exec/vectorized/chunks_sorter_full_sort.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/topn_node.cpp
  be/src/storage/vectorized/convert_helper.cpp
Labels: Approved

#1922 Try consume before large memory allocate
  be/src/runtime/current_thread.h
  be/src/service/mem_hook.cpp
Labels: Approved

#1710 Support AGG min/max in low cardinality optimize
  be/src/runtime/global_dicts.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecodeRewriteTest.java
Labels: type/enhancement

#1932 Eliminate time-consuming LocalMergeSortSourceOperator and parallelize AnalyticNode with partition_exprs
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/analysis/analytic_sink_operator.h
  be/src/exec/pipeline/analysis/analytic_source_operator.h
  be/src/exec/pipeline/analysis/analytor_factory.cpp
  be/src/exec/pipeline/analysis/analytor_factory.h
  be/src/exec/pipeline/sort/local_merge_sort_source_operator.cpp
  be/src/exec/pipeline/sort/local_merge_sort_source_operator.h
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/pipeline/sort/partition_sort_sink_operator.h
  be/src/exec/pipeline/sort/sort_context.cpp
  be/src/exec/pipeline/sort/sort_context.h
  be/src/exec/vectorized/analytic_node.cpp
  be/src/exec/vectorized/analytor.h
  be/src/exec/vectorized/topn_node.cpp
  be/src/exec/vectorized/topn_node.h
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  gensrc/thrift/PlanNodes.thrift
Labels: sig/pipeline, sig/optimizer

#1973 remove RowBatch
  be/src/exec/es/es_predicate.cpp
  be/src/exec/exchange_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/select_node.cpp
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/vectorized/assert_num_rows_node.cpp
  be/src/exec/vectorized/file_scan_node.cpp
  be/src/exec/vectorized/mysql_scan_node.cpp
  be/src/exec/vectorized/schema_scanner/schema_helper.cpp
  be/src/runtime/CMakeLists.txt
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/export_sink.cpp
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/memory_scratch_sink.cpp
  be/src/runtime/memory_scratch_sink.h
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/mysql_result_writer.h
  be/src/runtime/mysql_table_writer.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_sink.h
  be/src/runtime/result_writer.h
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
  be/src/runtime/vectorized/statistic_result_writer.cpp
  be/src/runtime/vectorized/statistic_result_writer.h
  be/src/runtime/vectorized_row_batch.h
  be/src/util/arrow/row_batch.cpp
  be/test/exec/orc_scanner_test.cpp
  be/test/exec/parquet_scanner_test.cpp
  be/test/exec/tablet_info_test.cpp
  be/test/exec/tablet_sink_test.cpp
  be/test/runtime/fragment_mgr_test.cpp
  be/test/runtime/memory_scratch_sink_test.cpp
  be/test/util/arrow/arrow_work_flow_test.cpp
Labels: type/cleanup

#1967 Fix the bug of large sort can't be cancelled
  be/src/exec/vectorized/chunks_sorter_full_sort.cpp
  be/src/exec/vectorized/chunks_sorter_full_sort.h
  be/src/exec/vectorized/chunks_sorter_topn.cpp
  be/src/exec/vectorized/chunks_sorter_topn.h
  be/src/runtime/runtime_state.h
  be/src/storage/vectorized/memtable.cpp
  be/src/util/orlp/pdqsort.h
  be/test/exec/vectorized/chunks_sorter_test.cpp
Labels: type/enhancement, Approved

#1975 remove VectorizedRowBatch
  be/src/runtime/CMakeLists.txt
  be/src/runtime/vectorized_row_batch.cpp
  be/src/runtime/vectorized_row_batch.h
  be/src/storage/column_predicate.h
  be/src/storage/comparison_predicate.cpp
  be/src/storage/comparison_predicate.h
  be/src/storage/in_list_predicate.cpp
  be/src/storage/in_list_predicate.h
  be/src/storage/null_predicate.cpp
  be/src/storage/null_predicate.h
  be/test/CMakeLists.txt
  be/test/storage/comparison_predicate_test.cpp
  be/test/storage/in_list_predicate_test.cpp
  be/test/storage/null_predicate_test.cpp
Labels: type/cleanup

#1450 [Vertical compaction 5/5] Support duplicate, unique and aggregate key table
  be/src/common/config.h
  be/src/storage/rowset/rowset_factory.cpp
  be/src/storage/rowset/rowset_writer_context.h
  be/src/storage/vectorized/chunk_helper.cpp
  be/src/storage/vectorized/compaction.cpp
  be/src/storage/vectorized/compaction.h
  be/src/storage/vectorized/empty_iterator.cpp
  be/src/storage/vectorized/row_source_mask.cpp
  be/src/storage/vectorized/row_source_mask.h
  be/src/storage/vectorized/tablet_reader.cpp
  be/src/storage/vectorized/tablet_reader.h
  be/test/storage/rowset/beta_rowset_test.cpp
  be/test/storage/vectorized/base_compaction_test.cpp
  be/test/storage/vectorized/cumulative_compaction_test.cpp
  be/test/storage/vectorized/merge_iterator_test.cpp
  be/test/storage/vectorized/row_source_mask_test.cpp
Labels: type/enhancement, sig/storage

#2037 Check mem limit before start execute fragment
  be/src/runtime/fragment_mgr.cpp
Labels: type/bug

#2025 add cancel check in ES Scanner
  be/src/exec/vectorized/es_http_scanner.cpp
Labels: type/enhancement, Approved

#2058 Remove query id string from TLS
  be/src/common/logging.h
  be/src/runtime/current_thread.h
  be/test/exec/tablet_sink_test.cpp
Labels: type/cleanup

#2051 SinkBuffer allow out-of-order transimition
  be/src/common/config.h
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exec/pipeline/exchange/local_exchange.h
  be/src/exec/pipeline/exchange/local_exchange_sink_operator.h
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/pipeline_driver_dispatcher.cpp
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/runtime/data_stream_recvr.cc
  be/src/util/callback_closure.h
  be/src/util/disposable_closure.h
Labels: type/enhancement, sig/pipeline

#2106 [pipeline] check whether driver can short circuit break in poller
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/vectorized/hash_joiner.h
Labels: type/enhancement, sig/pipeline

#2150 Fix group has redundant group expression
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/GroupExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EnumeratePlanTest.java
Labels: sig/optimizer

#1842 [Vertical compaction] Support primary key table
  be/src/storage/tablet_updates.cpp
  be/src/storage/vectorized/rowset_merger.cpp
  be/src/storage/vectorized/rowset_merger.h
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
Labels: sig/storage

#2008 use estimate join column statistics instead of children statistics
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EnumeratePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q15.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q2.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q3.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q8.sql
Labels: sig/optimizer

#1951 Improve statistics estimate for in predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/predicate-extract.sql
Labels: Approved, sig/optimizer

#2202 compute broadcast join costs with pipeline dop
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/join_pipeline_dop.json
Labels: Approved, sig/optimizer

#1782 Reduce overhead of casting type(int->string) when loading json file
  be/CMakeLists.txt
  be/src/exec/vectorized/json_scanner.cpp
  be/src/exec/vectorized/json_scanner.h
  be/src/exprs/vectorized/json_functions.cpp
  be/src/exprs/vectorized/json_functions.h
  be/src/formats/CMakeLists.txt
  be/src/formats/json/binary_column.cpp
  be/src/formats/json/binary_column.h
  be/src/formats/json/nullable_column.cpp
  be/src/formats/json/nullable_column.h
  be/src/formats/json/numeric_column.cpp
  be/src/formats/json/numeric_column.h
  be/test/CMakeLists.txt
  be/test/exec/test_data/json_scanner/test5.json
  be/test/exec/test_data/json_scanner/test6.json
  be/test/exec/test_data/json_scanner/test7.json
  be/test/exec/test_data/json_scanner/test_cast_type.json
  be/test/exec/test_data/json_scanner/test_multi_type.json
  be/test/exec/vectorized/json_scanner_test.cpp
  be/test/exprs/vectorized/json_functions_test.cpp
  be/test/formats/json/binary_column_test.cpp
  be/test/formats/json/nullable_column_test.cpp
  be/test/formats/json/numeric_column_test.cpp
Labels: type/enhancement, sig/storage

#2271 Reduce the number of directory sync on rowset writing
  be/src/storage/fs/file_block_manager.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/test/storage/vectorized/cumulative_compaction_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
Labels: type/enhancement, sig/storage

#1276 Optimize: delete meta instantly when dropping a tablet
  be/src/agent/task_worker_pool.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/update_manager_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/task/DropReplicaTask.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
  gensrc/thrift/AgentService.thrift
Labels: type/enhancement, sig/storage

#2302 Remove OlapTablePartitionParam of non-vectorized execute engine
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/test/exec/tablet_info_test.cpp
Labels: type/cleanup

#2317 Merge multiple duplicate logic
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
Labels: metadata

#2314 remove Tuple
  be/src/exec/es/es_predicate.h
  be/src/exec/parquet_builder.cpp
  be/src/exec/parquet_reader.cpp
  be/src/exec/parquet_reader.h
  be/src/exec/select_node.h
  be/src/exec/tablet_info.h
  be/src/exec/tablet_sink.h
  be/src/exec/vectorized/hdfs_scan_node.h
  be/src/exec/vectorized/mysql_scan_node.h
  be/src/exec/vectorized/parquet_scanner.cpp
  be/src/exprs/expr.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/raw_value.cpp
  be/src/runtime/raw_value.h
  be/src/runtime/tuple.cpp
  be/src/runtime/tuple.h
  be/test/exec/orc_scanner_test.cpp
  be/test/exec/parquet_scanner_test.cpp
  be/test/exec/vectorized/repeat_node_test.cpp
Labels: type/cleanup

#2337 Fix the int overflow bug of DeleteHandler
  fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
Labels: metadata

#2376 remove unused flag: is_vectorized
  be/src/exec/data_sink.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/project_node.cpp
  be/src/exec/vectorized/project_node.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/slot_ref.h
  be/src/exprs/vectorized/arithmetic_expr.cpp
  be/src/exprs/vectorized/binary_predicate.cpp
  be/src/exprs/vectorized/column_ref.h
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/data_stream_sender.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
Labels: type/cleanup

#2371 Optimize local four/three-stages aggregation
  fe/fe-core/src/main/java/com/starrocks/planner/AggregationNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/PruneAggregateNodeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecodeRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: sig/optimizer

#2405 Fix Union flatten miss Qualifier is ALL bug
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/set-operation.sql
Labels: Approved

#2378 Support CTE reuse in subquery
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/ValuesTransformer.java
Labels: Approved

#2423 Print the thread which holding the catalog lock when try_lock timeout
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
Labels: metadata

#2484 Add mutable column visitor
  be/src/column/CMakeLists.txt
  be/src/column/column.h
  be/src/column/column_visitor_mutable.cpp
  be/src/column/column_visitor_mutable.h
Labels: Approved

#2482 SerializedKeyAggHashSet default not use TwoLevelHashSet
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp
  be/src/exec/vectorized/aggregate/agg_hash_variant.h
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp
  be/src/exec/vectorized/aggregator.cpp
  be/src/exec/vectorized/aggregator.h
Labels: type/bug, type/enhancement, Approved

#2499 Remove createSocketAddr in NetUtils
  fe/fe-core/src/main/java/com/starrocks/common/util/NetUtils.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
Labels: Approved

#2057 Reduce lock contentions in TabletsWriter
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/service/brpc_service.cpp
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/storage/vectorized/memtable.h
Labels: type/enhancement, sig/storage

#2540 Bugfix: ChunkPB::is_nulls() is empty
  be/src/runtime/tablets_channel.cpp
Labels: type/bug
