Repository StarRocks/starrocks, pull requests merged in 2021-09, with the labels that each got.

#50 Update Readme.md
  README.md
Labels: Approved

#40 [SR-4404] use _mm_pause and sched_yield instead of sleep
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/exec/pipeline/scan_operator.cpp
Labels: Approved

#49 Revert "[SR-4378] extract common code of aggregate algo in order to r…
  be/src/exec/CMakeLists.txt
  be/src/exec/vectorized/aggregate/aggregate_base.cpp
  be/src/exec/vectorized/aggregate/aggregate_base.h
  be/src/exec/vectorized/aggregate/aggregate_base_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_base_node.h
Labels: Approved

#51 Fix the typo
  README.md
Labels: Approved

#56 remove docker
  docker/README.md
Labels: Approved

#62 [SR-4420] Fix ifnull(float_number, 123) throw exception
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
Labels: Approved

#73 Fix old query engine couldn't find function symbol
  gensrc/script/starrocks_builtins_functions.py
Labels: Approved

#72 fix comment error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
Labels: Approved

#83 [SR-4078] Provide Sort Operator
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/project_operator.h
  be/src/exec/pipeline/scan_operator.cpp
  be/src/exec/pipeline/sort/sort_sink_operator.cpp
  be/src/exec/pipeline/sort/sort_sink_operator.h
  be/src/exec/pipeline/sort/sort_source_operator.cpp
  be/src/exec/pipeline/sort/sort_source_operator.h
  be/src/exec/sort_exec_exprs.h
  be/src/exec/vectorized/chunks_sorter.cpp
  be/src/exec/vectorized/chunks_sorter.h
  be/src/exec/vectorized/chunks_sorter_full_sort.cpp
  be/src/exec/vectorized/chunks_sorter_full_sort.h
  be/src/exec/vectorized/chunks_sorter_topn.cpp
  be/src/exec/vectorized/chunks_sorter_topn.h
  be/src/exec/vectorized/topn_node.cpp
  be/src/exec/vectorized/topn_node.h
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
Labels: Approved

#70 [SR-4421] getPaloPath renamed to getStarRocksPath
  fe/fe-core/src/main/java/com/starrocks/load/DppConfig.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/UserProperty.java
  fe/fe-core/src/test/java/com/starrocks/load/DppConfigTest.java
Labels: Approved

#97 Update BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
Labels: Approved

#94 [SR-4322] Auto statistic don't work if table has not been update
  bin/start_fe.sh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
Labels: Approved, Optimizer

#103 [#102] Fix ASAN crash for scan node use in predicate result
  be/src/exec/vectorized/olap_scan_prepare.h
  be/src/exprs/vectorized/in_const_predicate.hpp
Labels: bug, Approved

#90 Imporve metrics text format for FE
  fe/fe-core/src/main/java/com/starrocks/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/StarRocksMetricRegistry.java
Labels: Approved

#106 Bugfix: should not print error log if status is EndOfFile
  be/src/common/logging.h
  be/src/exec/vectorized/olap_scan_node.cpp
Labels: Approved

#85 [SR-4073] Query making no progress for a long time is expired
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_driver_dispatcher.cpp
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/exec/pipeline/pipeline_fwd.h
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BackendServiceProxy.java
  gensrc/proto/internal_service.proto
  gensrc/thrift/InternalService.thrift
Labels: Approved, Pipeline

#21 [SR-4312] Support multi character column_separator during load
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/vectorized/csv_scanner.cpp
  be/src/exec/vectorized/csv_scanner.h
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: Approved

#64 [SR-3554] Provide hyperscan to instead re2 in like/regexp
  be/CMakeLists.txt
  be/src/exprs/vectorized/like_predicate.cpp
  be/src/exprs/vectorized/like_predicate.h
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: Approved

#109 Rename hadoop_palo_path to hadoop_starrocks_path
  fe/fe-core/src/main/java/com/starrocks/load/DppConfig.java
  fe/fe-core/src/test/java/com/starrocks/load/DppConfigTest.java
Labels: Approved

#121 [SR-4458] Bugfix: DecimalTypeInfo from_string overflow error
  be/src/storage/decimal_type_info.h
Labels: bug, Approved

#135 Bugfix: Remove the skipped tablet from queue
  be/src/storage/tablet_manager.cpp
Labels: Approved

#130 fix variables unused warning
  be/src/exprs/vectorized/in_const_predicate.hpp
Labels: Approved

#28 [SR-4347] support vectorized es_http_scan_node
  .gitignore
  be/src/column/datum.h
  be/src/exec/CMakeLists.txt
  be/src/exec/es/es_predicate.cpp
  be/src/exec/es/es_predicate.h
  be/src/exec/es/es_query_builder.cpp
  be/src/exec/es/es_scan_reader.cpp
  be/src/exec/es/es_scan_reader.h
  be/src/exec/exec_node.cpp
  be/src/exec/vectorized/es_http_components.cpp
  be/src/exec/vectorized/es_http_components.h
  be/src/exec/vectorized/es_http_scan_node.cpp
  be/src/exec/vectorized/es_http_scan_node.h
  be/src/exec/vectorized/es_http_scanner.cpp
  be/src/exec/vectorized/es_http_scanner.h
  be/src/runtime/timestamp_value.cpp
  be/src/runtime/timestamp_value.h
  be/src/util/time_util.hpp
  be/test/exec/es_query_builder_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/EsScanNode.java
Labels: Approved

#138 [BUG] fix const raw string add number
  be/src/exec/vectorized/json_scanner.cpp
  be/src/runtime/data_stream_sender.cpp
Labels: Approved

#118 [SR-3676] Export supports specified columns
  be/src/runtime/export_sink.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/ExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportStmtTest.java
Labels: Approved

#141 Rename class OlapMeta to KVStore
  be/src/storage/CMakeLists.txt
  be/src/storage/data_dir.cpp
  be/src/storage/data_dir.h
  be/src/storage/kv_store.cpp
  be/src/storage/kv_store.h
  be/src/storage/olap_define.h
  be/src/storage/rowset/beta_rowset.cpp
  be/src/storage/rowset/beta_rowset.h
  be/src/storage/rowset/rowset_meta_manager.cpp
  be/src/storage/rowset/rowset_meta_manager.h
  be/src/storage/rowset/vectorized/rowset_options.h
  be/src/storage/rowset/vectorized/segment_options.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/storage/tablet_manager.h
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/txn_manager.cpp
  be/src/storage/txn_manager.h
  be/src/storage/update_manager.cpp
  be/src/storage/update_manager.h
  be/src/tools/meta_tool.cpp
  be/test/CMakeLists.txt
  be/test/storage/delta_writer_test.cpp
  be/test/storage/kv_store_test.cpp
  be/test/storage/tablet_mgr_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/update_manager_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
Labels: Approved

#158 [Compile] Fix hyberscan not found Fix boost found problem
  build.sh
  thirdparty/build-thirdparty.sh
Labels: Approved

#154 [SR-4446] update librdkafka to new version, fix the bug of memory leak in lz4 decompress
  thirdparty/vars.sh
Labels: Approved

#150 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .gitignore
Labels: Approved

#151 [SR-4475] Vectorization engine reuses aggregator components
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp
  be/src/exec/vectorized/aggregate/aggregate_base_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_base_node.h
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.h
  be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_streaming_node.h
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.h
  be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp
  be/src/exec/vectorized/aggregate/distinct_streaming_node.h
  be/src/exec/vectorized/aggregator.cpp
  be/src/exec/vectorized/aggregator.h
Labels: Approved

#164 [Bug][ES-Extern] fix type convert error while get value from es-exter…
  be/src/exec/vectorized/es_http_components.cpp
Labels: Approved

#168 Fix explain verbose plan of HdfsNode
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: Approved, Optimizer

#107 [SR-4370] Support use Min/Max column statistics to estimate && Calculate predicate statistics for cross join
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarRangePredicateExtractor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinOrder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/Constants.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch/q22.sql
  fe/fe-core/src/test/resources/sql/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q10.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q15.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q19.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q2.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q3.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q4.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q6.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q8.sql
Labels: Approved, Optimizer

#68 Support bucket shuffle on multiple partition join
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/HashDistributionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: Approved

#95 [SR-3845] add defense for large binary column in right table of hash join
  be/src/column/array_column.h
  be/src/column/binary_column.h
  be/src/column/chunk.h
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.h
  be/src/column/nullable_column.h
  be/src/column/object_column.h
  be/src/exec/vectorized/hash_join_node.cpp
Labels: Approved

#175 Reduce the number of disk accesses while parsing segment footer
  be/src/storage/rowset/beta_rowset.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/segment_v2/segment.cpp
  be/src/storage/rowset/segment_v2/segment.h
  be/test/storage/rowset/beta_rowset_test.cpp
  be/test/storage/rowset/segment_v2/segment_test.cpp
Labels: type/enhancement

#201 [SR-4416] remove mysql-connector-java
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: Approved

#198 [SR-4489] Fixup IN predicate overflow decimal string convertion failure
  be/src/runtime/decimalv3.h
  be/src/storage/vectorized/column_in_predicate.cpp
  be/src/storage/vectorized/column_not_in_predicate.cpp
  be/src/storage/vectorized/in_predicate_utils.h
  be/test/runtime/decimalv3_test.cpp
Labels: Approved

#197 Avoid loading short key indexes when they are not needed
  be/src/storage/rowset/vectorized/segment_iterator.cpp
Labels: type/enhancement, sig/storage

#210 distrubute system fs.hdfs.impl.disable.cache change to be configurable
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: type/enhancement, Approved

#220 padding hashset serialization data to ensure min size
  be/src/exec/vectorized/aggregator.cpp
  be/src/exprs/agg/distinct.h
Labels: Approved

#204 [#203] Broadcast Join passes the Gather property down
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: Approved, sig/optimizer

#171 [SR-3574] optimizing some object columnp agg-function performance and b…
  be/src/common/config.h
  be/src/exec/es/es_predicate.cpp
  be/src/exprs/agg/bitmap_intersect.h
  be/src/exprs/agg/bitmap_union.h
  be/src/exprs/agg/bitmap_union_count.h
  be/src/exprs/agg/bitmap_union_int.h
  be/src/exprs/agg/hll_union.h
  be/src/exprs/agg/hll_union_count.h
  be/src/exprs/agg/percentile_union.h
  be/src/util/bitmap_value.h
  be/test/util/bitmap_value_test.cpp
Labels: Approved

#236 remove unused dependencies
  be/test/exec/CMakeLists.txt
  build.sh
  run-ut.sh
  thirdparty/LICENSE.txt
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: Approved

#238 [#237] Move tpch mock statistic to UT
  fe/checkstyle.xml
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/EmptyStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/MockTpchStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorageTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
Labels: Approved

#239 [SR-4416] Upgrade zookeeper to more safe version
  fe/fe-core/pom.xml
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: Approved

#247 Adjust the error code to be more consise
  fe/fe-core/src/main/java/com/starrocks/analysis/ClusterName.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
Labels: Approved

#234 Bugfix: fail to capture rowset for version xxx
  be/src/exec/pipeline/olap_chunk_source.cpp
  be/src/exec/pipeline/olap_chunk_source.h
  be/src/exec/vectorized/olap_scan_node.cpp
  be/src/exec/vectorized/olap_scan_node.h
  be/src/exec/vectorized/olap_scanner.cpp
  be/src/exec/vectorized/olap_scanner.h
  be/src/storage/olap_common.h
  be/src/storage/rowset/vectorized/rowset_options.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_meta.h
  be/src/storage/vectorized/compaction.cpp
  be/src/storage/vectorized/reader.cpp
  be/src/storage/vectorized/reader.h
  be/src/storage/vectorized/reader_params.cpp
  be/src/storage/vectorized/reader_params.h
Labels: type/bug, sig/storage

#78 [SR-4368] Disable cast statements when creating materialized views
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/MVColumnOneChildPatternTest.java
Labels: Approved

#249 [SR-4078] Fix for single source
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/vectorized/sorted_chunks_merger.cpp
Labels: Approved

#232 [SR-4535] Fix information_schema.CHARACTER_MAXIMUM_LENGTH & CHARACTER_OCTET_LENGTH
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
Labels: Approved

#202 [#147] Optimize duplicate aggregation nodes
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSetType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeTwoAggRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved, sig/optimizer

#235 [SR-4450] support vectorized schema scanner
  be/src/exec/CMakeLists.txt
  be/src/exec/exec_node.cpp
  be/src/exec/vectorized/schema_scan_node.cpp
  be/src/exec/vectorized/schema_scan_node.h
  be/src/exec/vectorized/schema_scanner.cpp
  be/src/exec/vectorized/schema_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_charsets_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_charsets_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_collations_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_collations_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_columns_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_dummy_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_dummy_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_events_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_events_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_helper.cpp
  be/src/exec/vectorized/schema_scanner/schema_helper.h
  be/src/exec/vectorized/schema_scanner/schema_schema_privileges_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_schema_privileges_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_schemata_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_schemata_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_statistics_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_statistics_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_table_privileges_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_table_privileges_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_tables_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_tables_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_triggers_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_triggers_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_user_privileges_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_user_privileges_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_variables_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_variables_scanner.h
  be/src/exec/vectorized/schema_scanner/schema_views_scanner.cpp
  be/src/exec/vectorized/schema_scanner/schema_views_scanner.h
  be/src/runtime/descriptors.h
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaScanNode.java
Labels: Approved

#268 [minor fix][Bug] make bitmap_to_array sorted
  be/src/util/bitmap_value.h
Labels: Approved

#122 Support replication join's query plan and query schedule
  fe/fe-core/src/main/java/com/starrocks/catalog/Tablet.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/planner/SetOperationNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#260 [SR-4623] Check satisfy local property in olap scan node output properties
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: Approved

#209 [#161] Pushdown equivalence on predicate for outer/semi join
  fe/fe-core/src/main/java/com/starrocks/analysis/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableRef.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinPredicateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinOnClauseRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/predicate-pushdown.sql
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
Labels: Approved

#279 fix select from information_schema tables error
  be/src/exec/vectorized/schema_scan_node.cpp
Labels: Approved

#270 [#269] Fix bug for aggreate require outer join support local property
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved

#297 [SparkConnector] Enable vectorized query plan
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
Labels: Approved

#287 remove unused schema scan code
  be/src/exec/CMakeLists.txt
  be/src/exec/convert_scan_node.cpp
  be/src/exec/convert_scan_node.h
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/schema_scan_node.cpp
  be/src/exec/schema_scan_node.h
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_charsets_scanner.cpp
  be/src/exec/schema_scanner/schema_charsets_scanner.h
  be/src/exec/schema_scanner/schema_collations_scanner.cpp
  be/src/exec/schema_scanner/schema_collations_scanner.h
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.h
  be/src/exec/schema_scanner/schema_dummy_scanner.cpp
  be/src/exec/schema_scanner/schema_dummy_scanner.h
  be/src/exec/schema_scanner/schema_events_scanner.cpp
  be/src/exec/schema_scanner/schema_events_scanner.h
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_schema_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_schema_privileges_scanner.h
  be/src/exec/schema_scanner/schema_schemata_scanner.cpp
  be/src/exec/schema_scanner/schema_schemata_scanner.h
  be/src/exec/schema_scanner/schema_statistics_scanner.cpp
  be/src/exec/schema_scanner/schema_statistics_scanner.h
  be/src/exec/schema_scanner/schema_table_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_table_privileges_scanner.h
  be/src/exec/schema_scanner/schema_tables_scanner.cpp
  be/src/exec/schema_scanner/schema_tables_scanner.h
  be/src/exec/schema_scanner/schema_triggers_scanner.cpp
  be/src/exec/schema_scanner/schema_triggers_scanner.h
  be/src/exec/schema_scanner/schema_user_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_user_privileges_scanner.h
  be/src/exec/schema_scanner/schema_variables_scanner.cpp
  be/src/exec/schema_scanner/schema_variables_scanner.h
  be/src/exec/schema_scanner/schema_views_scanner.cpp
  be/src/exec/schema_scanner/schema_views_scanner.h
  be/src/exec/vectorized/mysql_scan_node.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/runtime/descriptors.h
  be/test/exec/schema_scanner/schema_columns_scanner_test.cpp
  be/test/http/stream_load_test.cpp
Labels: Approved

#304 set minimum parallelism of source operator to 1
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/vectorized/olap_scan_node.cpp
Labels: Approved

#311 remove some unused jar dependencies
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: Approved

#312 [SR-4661] Cbo optimizer introduces wildcard decimal into ArithmeticExpr
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
Labels: type/bug

#246 Improve pre-aggregation for olap scan node with join node
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/PreAggregateTurnOnRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved

#309 support crc/fnv hash in array column
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.cpp
  be/src/column/const_column.h
  be/src/column/decimalv3_column.cpp
  be/src/column/decimalv3_column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exprs/vectorized/runtime_filter.h
  be/src/runtime/data_stream_sender.cpp
  be/test/column/array_column_test.cpp
Labels: Approved

#326 [Bug][SR-4712] fix crash when agg key was decimalv3
  be/src/exec/vectorized/aggregate/agg_hash_map.h
  be/src/exec/vectorized/aggregate/agg_hash_set.h
  be/src/exec/vectorized/aggregate/agg_hash_variant.h
  be/src/exec/vectorized/aggregator.cpp
Labels: Approved

#322 Fix rollup aggregate result has duplicate NULL
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/grouping-sets.sql
Labels: Approved, sig/optimizer

#301 [SR-4685] StarRocksColumn convert to Arrow Array
  be/src/exec/vectorized/arrow_to_starrocks_converter.cpp
  be/src/exec/vectorized/arrow_to_starrocks_converter.h
  be/src/exec/vectorized/arrow_type_traits.h
  be/src/runtime/memory_scratch_sink.cpp
  be/src/runtime/memory_scratch_sink.h
  be/src/runtime/primitive_type.h
  be/src/util/CMakeLists.txt
  be/src/util/arrow/starrocks_column_to_arrow.cpp
  be/src/util/arrow/starrocks_column_to_arrow.h
  be/test/CMakeLists.txt
  be/test/util/arrow/starrocks_column_to_arrow_test.cpp
Labels: Approved, type/feature-request

#320 [#294] Reduce exchange node for query information
  fe/checkstyle.xml
  fe/fe-core/src/main/java/com/starrocks/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/com/starrocks/http/WebUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved

#338 [SR-4737][Bug] fix be crash in debug/asan mode when agg key was boolean
  be/src/exec/vectorized/aggregate/agg_hash_variant.h
  be/src/exec/vectorized/aggregator.cpp
Labels: Approved

#341 Delete the inheritance relationship between Pattern and Operator
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Operator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOperator.java
Labels: Approved

#352 Make code compile with Clang 12.0.1
  be/CMakeLists.txt
  be/src/exprs/agg/distinct.h
  be/src/util/exclusive_ptr.h
  be/test/storage/rowset/segment_v2/plain_page_test.cpp
Labels: Approved

#343 [SR-4075] Refactor report exec status in pipeline
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/exec_state_reporter.h
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver_dispatcher.cpp
  be/src/exec/pipeline/pipeline_driver_dispatcher.h
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
Labels: Approved

#379 Improve cost calculation for multi_distinct_count function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: Approved

#389 Fix performance-inefficient-vector-operation by clang-tidy
  be/src/common/daemon.cpp
  be/src/exec/vectorized/repeat_node.cpp
  be/src/exec/vectorized/table_function_node.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/vectorized/hash_functions.h
  be/src/storage/rowset/beta_rowset_reader.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
  be/src/util/path_util.cpp
Labels: Approved

#324 Expire cached statistics for Fe follower when excute analyze job
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: Approved

#391 Fix performance-move-const-arg by clang-tidy
  be/src/exec/pipeline/exchange/local_exchange_sink_operator.cpp
  be/src/exec/pipeline/limit_operator.cpp
  be/src/exec/pipeline/pipeline.h
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/source_operator.h
  be/src/exec/vectorized/aggregator.cpp
  be/src/exec/vectorized/topn_node.cpp
  be/src/exprs/agg/bitmap_intersect.h
  be/src/exprs/agg/bitmap_union.h
  be/src/exprs/agg/bitmap_union_count.h
  be/src/exprs/agg/hll_union.h
  be/src/exprs/agg/hll_union_count.h
  be/src/exprs/agg/maxmin.h
  be/src/exprs/agg/percentile_union.h
  be/src/gutil/strings/split_internal.h
  be/src/gutil/strings/strcat.h
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/storage/reader.cpp
  be/src/storage/rowset/beta_rowset.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/vectorized/reader.cpp
  be/src/util/arrow/row_batch.cpp
  be/src/util/thread.h
Labels: Approved

#392 fix performance-unnecessary-copy-initialization by clang-tidy
  be/src/http/action/compaction_action.cpp
  be/src/storage/utils.cpp
  be/src/tools/meta_tool.cpp
  be/src/util/arrow/row_batch.cpp
Labels: Approved

#393 Fix performance-type-promotion-in-math-fn by clang-tidy
  be/src/storage/hll.cpp
Labels: Approved

#394 Fix performance-noexcept-move-constructor by clang-tidy
  be/src/column/array_column.h
  be/src/column/binary_column.h
  be/src/column/const_column.h
  be/src/column/hash_set.h
  be/src/column/nullable_column.h
  be/src/common/statusor.h
  be/src/common/statusor_internal.h
  be/src/exprs/vectorized/runtime_filter.cpp
  be/src/exprs/vectorized/runtime_filter.h
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/gutil/ref_counted.h
  be/src/runtime/bufferpool/buffer_pool.cc
  be/src/runtime/bufferpool/buffer_pool.h
  be/src/runtime/runtime_filter_worker.h
  be/src/storage/hll.h
  be/src/util/bitmap_value.h
  be/src/util/exclusive_ptr.h
  be/src/util/phmap/phmap_base.h
Labels: Approved

#339 [SR-4363] Add SM3 Cryptographic Hash Algorithm
  be/src/exprs/vectorized/string_functions.cpp
  be/src/exprs/vectorized/string_functions.h
  be/src/util/CMakeLists.txt
  be/src/util/sm3.cpp
  be/src/util/sm3.h
  be/test/CMakeLists.txt
  be/test/exprs/vectorized/string_fn_sm3_test.cpp
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#405 Modify implicit cast check wildcard decimal
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
Labels: Approved

#419 [SR-4075] add config properties for pipeline engine
  be/src/common/config.h
  be/src/common/status.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/runtime/exec_env.cpp
  be/src/service/internal_service.cpp
  gensrc/thrift/Status.thrift
Labels: Approved

#412 Fix modernize-replace-random-shuffle by clang-tidy
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/storage/storage_engine.cpp
Labels: Approved

#335 Disable one Agg phase when Fe do not get real row count from be
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/resources/sql/tpchcost/q18.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q21.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q22.sql
Labels: Approved, sig/optimizer

#436 Format FE code
  fe/checkstyle.xml
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/common/MarkDownParser.java
  fe/fe-core/src/main/java/com/starrocks/common/Pair.java
  fe/fe-core/src/main/java/com/starrocks/common/io/IOUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/io/OutputBuffer.java
  fe/fe-core/src/main/java/com/starrocks/common/util/SmallFileMgr.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/QueryDetailAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/QueryDumpAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableSchemaAction.java
  fe/fe-core/src/main/java/com/starrocks/load/EtlStatus.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkRepository.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/ScheduleRule.java
  fe/fe-core/src/main/java/com/starrocks/master/MasterImpl.java
  fe/fe-core/src/main/java/com/starrocks/metric/TableMetricsRegistry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlAuthPacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlPacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlPassword.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlChannel.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlServer.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/ReadListener.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendOptions.java
Labels: Approved

#431 fix be crashes when select from information_schema table and fe uses an old version
  be/src/exec/vectorized/schema_scan_node.cpp
  be/src/exec/vectorized/schema_scan_node.h
Labels: Approved

#422 Does not show useless schema hash in logging messages
  be/src/storage/tablet_manager.cpp
  be/test/column/avx_numeric_column.h
  be/test/exprs/vectorized/string_fn_sm3_test.cpp
Labels: type/enhancement, sig/storage

#435 Resolve aggregate shuffle hang problem
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
Labels: Approved, sig/pipeline

#440 [SR-4075] ExchangeMergeSortSourceOperator hangs because of multiple empty input streams.
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/vectorized/sorted_chunks_merger.cpp
Labels: type/bug, Approved, sig/pipeline

#414 pipeline engine support analytic operator
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/analysis/analytic_sink_operator.cpp
  be/src/exec/pipeline/analysis/analytic_sink_operator.h
  be/src/exec/pipeline/analysis/analytic_source_operator.cpp
  be/src/exec/pipeline/analysis/analytic_source_operator.h
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/analytic_node.cpp
  be/src/exec/vectorized/analytic_node.h
  be/src/exec/vectorized/analytor.cpp
  be/src/exec/vectorized/analytor.h
  fe/fe-core/src/main/java/com/starrocks/planner/AnalyticEvalNode.java
Labels: Approved, sig/pipeline

#443 Optimize bitmap_union_count duplicate with count(distinct ) in view
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteBitmapCountDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteDuplicateAggregateFnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved

#449 Fix NPE crash if enable_vectorized_insert=false
  be/src/exec/es/es_predicate.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/tablets_channel.h
Labels: Approved

#434 Fix chose error materialized view when use count() function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: Approved, sig/optimizer

#470 [Bug][QSXQ-602] fix late materialize error in array column
  be/src/storage/rowset/segment_v2/column_writer.cpp
Labels: type/bug, Approved

#366 Fix decimalV3 lost unit bug in view
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ViewPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/resources/sql/optimized-plan/constant-query.sql
Labels: Approved

#398 Add ArithmeticCommutative and EliminateNegations
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ExistsPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/EliminateNegationsRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ArithmeticCommutativeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/FoldConstantsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/NormalizePredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinPredicateUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/resources/sql/logical-plan/aggregate.sql
Labels: Approved

#488 Make MarkedCountDownLatch thread-safe
  fe/fe-core/src/main/java/com/starrocks/common/MarkedCountDownLatch.java
Labels: Approved

#483 [SR-4075] Promote shared exprs across drivers to their pipeline
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.h
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline.h
  be/src/exec/pipeline/project_operator.cpp
  be/src/exec/pipeline/project_operator.h
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/exec/pipeline/result_sink_operator.h
  be/src/exec/pipeline/scan_operator.cpp
  be/src/exec/pipeline/scan_operator.h
  be/src/exec/pipeline/sort/sort_sink_operator.cpp
  be/src/exec/pipeline/sort/sort_sink_operator.h
Labels: Approved

#476 Fix NPE bug in materialize rewrite percentile
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVAggRewrite.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVProjectAggProjectScanRewrite.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
Labels: Approved

#499 FE code format
  fe/checkstyle.xml
  fe/fe-core/src/main/java/com/starrocks/analysis/ExprId.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotId.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TupleId.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/ConfigBase.java
  fe/fe-core/src/main/java/com/starrocks/common/IdGenerator.java
  fe/fe-core/src/main/java/com/starrocks/common/io/DataOutputBuffer.java
  fe/fe-core/src/main/java/com/starrocks/common/io/LimitOutputStream.java
  fe/fe-core/src/main/java/com/starrocks/common/io/Text.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/HivePartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/metric/CounterMetric.java
  fe/fe-core/src/main/java/com/starrocks/metric/TableMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/persist/BackendTabletsInfo.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragmentId.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNodeId.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterId.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/BaseApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: Approved

#500 Remove useless code
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/io/DataInputBuffer.java
  fe/fe-core/src/main/java/com/starrocks/common/io/FastByteArrayOutputStream.java
  fe/fe-core/src/main/java/com/starrocks/common/io/IOUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/io/InputBuffer.java
  fe/fe-core/src/main/java/com/starrocks/common/io/LimitInputStream.java
  fe/fe-core/src/main/java/com/starrocks/common/io/LimitOutputStream.java
  fe/fe-core/src/main/java/com/starrocks/common/io/OutputBuffer.java
  fe/fe-core/src/main/java/com/starrocks/common/io/Text.java
Labels: Approved

#417 Optimize agg hash map by precomputing hash value and prefetch
  be/src/exec/vectorized/aggregate/agg_hash_map.h
Labels: Approved

#508 [SR-4075] LocalExchangeSinkOperator call finish exactly once
  be/src/exec/pipeline/exchange/local_exchange_sink_operator.cpp
  be/src/exec/pipeline/pipeline_driver_dispatcher.cpp
Labels: Approved

#516 Fix broker load throws devide by 0 exception when loading only empty files
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/FileScanNodeTest.java
Labels: Approved

#521 [Compile] Fix Compile Error in gcc9
  be/src/util/phmap/phmap.h
Labels: Approved

#519 [SR-4884] fix: modernize-avoid-bind by clang-tidy and don't capture this in lambda for Counter
  be/src/exec/exec_node.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/scan_node.cpp
  be/src/http/default_path_handlers.cpp
  be/src/runtime/bufferpool/buffer_allocator.cc
  be/src/runtime/bufferpool/buffer_pool.cc
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/disk_io_mgr.cc
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/routine_load/data_consumer.cpp
  be/src/runtime/routine_load/data_consumer_group.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/runtime_filter_worker.cpp
  be/src/storage/memtable_flush_executor.cpp
  be/src/util/mysql_load_error_hub.cpp
  be/src/util/starrocks_metrics.cpp
Labels: Approved

#486 refactor split one loop into two for more clear logic in ChunkAggregator ctor.
  be/src/storage/vectorized/chunk_aggregator.cpp
Labels: Approved
