Repository StarRocks/starrocks, pull requests merged in 2021-10, with the labels that each got.

#544 [SR-3811]Optimize Count Distinct using prefetch technique
  be/src/exec/vectorized/aggregate/agg_hash_set.h
  be/src/exprs/agg/distinct.h
  be/src/util/phmap/phmap.h
Labels: Approved

#531 fix/decimal on arm
  be/src/runtime/decimalv2_value.cpp
  be/src/runtime/decimalv3.h
Labels: Approved

#561 Refactor: replace OLAPStatus with Status in Tablet
  be/src/storage/data_dir.cpp
  be/src/storage/delta_writer.cpp
  be/src/storage/push_handler.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/rowset_factory.cpp
  be/src/storage/rowset/rowset_factory.h
  be/src/storage/rowset/vectorized/rowset_writer_adapter.cpp
  be/src/storage/schema_change.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/task/engine_checksum_task.cpp
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_publish_version_task.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
  be/src/storage/vectorized/compaction.cpp
  be/src/storage/vectorized/delta_writer.cpp
  be/src/storage/vectorized/push_handler.cpp
  be/src/storage/vectorized/tablet_reader.cpp
  be/test/storage/delta_writer_test.cpp
  be/test/storage/rowset/beta_rowset_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/update_manager_test.cpp
  be/test/storage/vectorized/base_compaction_test.cpp
  be/test/storage/vectorized/cumulative_compaction_test.cpp
  be/test/storage/vectorized/memtable_test.cpp
  be/test/storage/vectorized/rowset_merger_test.cpp
Labels: Approved, sig/storage

#461 Refactor Join and Agg Operator to eliminate variability
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVProjectAggProjectScanRewrite.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/BaseApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinCommutativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinPredicateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeTwoAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeTwoProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneAggregateColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneJoinColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteBitmapCountDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteHllCountDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: Approved, sig/optimizer

#584 Bugfix: incorrect segment id after clone
  be/src/storage/snapshot_manager.cpp
  be/src/storage/snapshot_meta.cpp
  be/src/storage/snapshot_meta.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: type/bug, sig/storage

#536 Estimate inner join row count using a middle ground method
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: Approved, sig/optimizer

#606 use lambda instead of std::function
  be/src/util/defer_op.h
Labels: Approved

#615 pipeline engine: analytic operator for unbounded frame and unbounded preceding frame
  be/src/exec/pipeline/analysis/analytic_sink_operator.cpp
  be/src/exec/pipeline/analysis/analytic_sink_operator.h
  be/src/exec/vectorized/analytic_node.cpp
  be/src/exec/vectorized/analytor.cpp
Labels: Approved, sig/pipeline

#630 Remove spill sort node of non-vectorized runtime engine
  be/src/runtime/CMakeLists.txt
  be/src/runtime/spill_sorter.cc
  be/src/runtime/spill_sorter.h
Labels: Approved

#599 Support meta scan in BE
  be/src/exec/CMakeLists.txt
  be/src/exec/exec_node.cpp
  be/src/exec/vectorized/olap_meta_scan_node.cpp
  be/src/exec/vectorized/olap_meta_scan_node.h
  be/src/exec/vectorized/olap_meta_scanner.cpp
  be/src/exec/vectorized/olap_meta_scanner.h
  be/src/runtime/vectorized/statistic_result_writer.cpp
  be/src/runtime/vectorized/statistic_result_writer.h
  be/src/storage/CMakeLists.txt
  be/src/storage/rowset/segment_v2/binary_plain_page.h
  be/src/storage/rowset/segment_v2/column_reader.cpp
  be/src/storage/rowset/segment_v2/column_reader.h
  be/src/storage/vectorized/meta_reader.cpp
  be/src/storage/vectorized/meta_reader.h
Labels: Approved

#647 optimize NullableColumn::serialize_batch for FixedLengthColumnBase
  be/src/column/column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/nullable_column.cpp
Labels: type/enhancement, Approved

#655 remove the logic of set process MemTracker with metric from tc_malloc
  be/src/common/daemon.cpp
  be/src/runtime/mem_tracker.cpp
  be/src/runtime/mem_tracker.h
Labels: Approved

#635 Add cache dict manager for low cardinality string
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalDistributionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved, sig/optimizer

#683 Fix crash in repeat function
  be/src/exprs/vectorized/string_functions.cpp
Labels: Approved

#674 Fixed the problem that dictionary codes lose effectiveness on small t…
  be/src/storage/rowset/segment_v2/column_writer.cpp
Labels: Approved

#676 add comment and reorder fields in Config
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: Approved

#707 Fix query hive empty partition Error
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
Labels: Approved

#698 [SR-4683] Enable decimal divide overflow check
  be/src/exprs/vectorized/arithmetic_expr.cpp
  be/test/exprs/vectorized/decimal_binary_function_test.cpp
Labels: type/bug, Approved

#714 [SR-4683] Add merge_column_with_null_column to support binary_function generating NULL values
  be/src/exprs/vectorized/binary_function.h
  be/src/exprs/vectorized/function_helper.cpp
  be/src/exprs/vectorized/function_helper.h
  be/test/CMakeLists.txt
  be/test/exprs/vectorized/function_helper_test.cpp
Labels: type/bug

#772 bug fix: check binary function result is nan will crash
  be/src/exprs/vectorized/binary_function.h
Labels: Approved

#756 create materialized with count(distinct) should not support at current version #755
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewStmtTest.java
Labels: Approved
