Repository StarRocks/starrocks, pull requests merged in 2022-10, with the labels that each got.

#11886 [Refactor] Fix PriorityThreadPoolExecutorTest unstable UT
  fe/fe-core/src/test/java/com/starrocks/common/PriorityThreadPoolExecutorTest.java
Labels: Approved

#11793 [BugFix] fix uncorrect logical properties when apply LowCardinality optimize
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#11898 [cherry-pick][branch-2.2][BugFix] mysql client automatically reconnect bug(#11668)
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlChannel.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlChannel.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
Labels: automerge

#11904 [Doc] add utility functions and format other date functions--to 2.2
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/convert_tz.md
  docs/sql-reference/sql-functions/date-time-functions/curdate.md
  docs/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/sql-reference/sql-functions/date-time-functions/curtime.md
  docs/sql-reference/sql-functions/date-time-functions/date_format.md
  docs/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/sql-reference/sql-functions/date-time-functions/day.md
  docs/sql-reference/sql-functions/date-time-functions/dayname.md
  docs/sql-reference/sql-functions/date-time-functions/dayofmonth.md
  docs/sql-reference/sql-functions/date-time-functions/dayofweek.md
  docs/sql-reference/sql-functions/date-time-functions/dayofyear.md
  docs/sql-reference/sql-functions/date-time-functions/from_days.md
  docs/sql-reference/sql-functions/date-time-functions/from_unixtime.md
  docs/sql-reference/sql-functions/date-time-functions/hour.md
  docs/sql-reference/sql-functions/date-time-functions/minute.md
  docs/sql-reference/sql-functions/date-time-functions/month.md
  docs/sql-reference/sql-functions/date-time-functions/monthname.md
  docs/sql-reference/sql-functions/date-time-functions/now.md
  docs/sql-reference/sql-functions/date-time-functions/second.md
  docs/sql-reference/sql-functions/date-time-functions/str_to_date.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/timestampadd.md
  docs/sql-reference/sql-functions/date-time-functions/timestampdiff.md
  docs/sql-reference/sql-functions/date-time-functions/to_date.md
  docs/sql-reference/sql-functions/date-time-functions/to_days.md
  docs/sql-reference/sql-functions/date-time-functions/unix_timestamp.md
  docs/sql-reference/sql-functions/date-time-functions/utc_timestamp.md
  docs/sql-reference/sql-functions/date-time-functions/weekofyear.md
  docs/sql-reference/sql-functions/date-time-functions/year.md
  docs/sql-reference/sql-functions/utility-functions/current_version.md
  docs/sql-reference/sql-functions/utility-functions/last_query_id.md
  docs/sql-reference/sql-functions/utility-functions/sleep.md
  docs/sql-reference/sql-functions/utility-functions/version.md
Labels: documentation

#11880 [BugFix] Check the nullable property based on slot instead of parquet field to avoid inconsistency in decoding
  be/src/formats/parquet/column_reader.cpp
  be/test/exec/test_data/parquet_scanner/file_reader_test.parquet6
  be/test/formats/parquet/file_reader_test.cpp
Labels: Approved

#11899 [Cherry-pick][branch-2.4][BugFix] Check the nullable property based on slot instead of parquet field to avoid inconsistency in decoding
  be/src/formats/parquet/column_reader.cpp
  be/test/exec/test_data/parquet_scanner/file_reader_test.parquet6
  be/test/formats/parquet/file_reader_test.cpp
Labels: automerge

#11883 [BugFix] Fix broker load start time
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadJobTest.java
Labels: Approved

#11925 [BugFix] fix build pulsar client with ninja
  thirdparty/build-thirdparty.sh
Labels: Approved

#11805 [Refactor]Support export relative stmt
  fe/fe-core/src/main/java/com/starrocks/analysis/CancelExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExportStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportRelativeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#11932 [Cherry-pick][branch-2.3][BugFix] Check the nullable property based on slot instead of parquet field to avoid inconsistency in decoding
  be/src/formats/parquet/column_reader.cpp
  be/test/exec/test_data/parquet_scanner/file_reader_test.parquet6
  be/test/formats/parquet/file_reader_test.cpp
Labels: automerge

#11884 [BugFix] Fix insert overwrite concurrent with dropping partition bug
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
Labels: Approved

#11927 [Refactor] refactor olap_common
  be/src/exec/olap_common.cpp
  be/src/exec/olap_common.h
  be/src/exec/olap_utils.h
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/dpp_sink_internal.h
  be/src/runtime/raw_value.cpp
  be/src/runtime/raw_value.h
Labels: Approved

#11933 [Doc] modify shortDesc in exportOverview
  docs/unloading/Export.md
Labels: documentation, Approved

#11867 [BugFix] Fix l1 file size keep growing
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  gensrc/proto/persistent_index.proto
Labels: Approved

#11937 Add more test cases
  be/src/exec/stream/aggregate/streaming_aggregate_sink_operator.cpp
  be/src/exec/stream/lookupjoin/lookup_join_context.h
  be/src/exec/stream/lookupjoin/lookup_join_seek_operator.cpp
  be/src/exec/stream/lookupjoin/lookup_join_seek_operator.h
  test_mv.sql
Labels: title needs [type]

#11936 [Doc] modify shortDesc in exportOverview in Branch 2.3
  docs/unloading/Export.md
Labels: documentation

#11935 [Doc] modify shortDesc in exportOverview in Branch 2.4
  docs/unloading/Export.md
Labels: documentation

#11941 [Doc] Add desc on refresh default
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
Labels: documentation, Approved

#11929 [Feature] Add metrics database_num and table_num for database
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: Approved

#11789 [BugFix] update error msg when join cannot be implemented by NLJ
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/NestLoopJoinImplementationRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
Labels: Approved

#11947 fix bugs in DEBUG mode
  be/src/exec/stream/lookupjoin/lookup_join_seek_operator.cpp
Labels: title needs [type]

#11952 fix bugs in memtable
  be/src/storage/memtable.cpp
  be/src/storage/memtable.h
Labels: title needs [type]

#11948 [Enhancement] enable shared scan in connector scan node
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/exec/vectorized/olap_scan_node.cpp
  be/src/exec/vectorized/olap_scan_node.h
Labels: Approved

#11955 fix bugs in lookup join probe operator
  be/src/exec/stream/lookupjoin/lookup_join_probe_operator.h
  be/src/exec/stream/lookupjoin/lookup_join_seek_operator.cpp
Labels: title needs [type]

#11959 fix bugs when flush data into a primary key mv
  fe/fe-core/src/main/java/com/starrocks/planner/stream/OlapTableRouteInfo.java
Labels: title needs [type]

#11844 [Feature] support run StarRocks on mac m1 using docker
  be/src/gutil/cpu.cc
  build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: Approved

#11958 [BugFix] Fix bug of update compaction
  be/src/storage/chunk_iterator.h
  be/src/storage/rowset_merger.cpp
Labels: Approved

#11949 [BugFix] Fix the bug that can't get the variable when connect the Mar…
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
Labels: Approved

#11950 [Refactor] fix the clang-tidy check
  be/src/common/status.h
Labels: Approved

#11216 [Feature] Add paramter(FLOOR | CEIL) and type:DATE for time_slice
  be/src/exprs/vectorized/time_functions.cpp
  be/src/exprs/vectorized/time_functions.h
  be/src/types/timestamp_value.cpp
  be/src/types/timestamp_value.h
  be/test/exprs/vectorized/time_functions_test.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UnitBoundary.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#11856 [BugFix] Fix subquery relation miss limit bug
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SubqueryRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: Approved

#11824 [Cherry-pick-2.2][Enhancement] Change LinkedListMultimap to ArrayListMultimap to better support for getting elements by index
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
Labels: automerge

#11397 [Enhancement] support file sink in pipeline engine
  be/src/common/config.h
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/sink/file_sink_operator.cpp
  be/src/exec/pipeline/sink/file_sink_operator.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_sink.h
  fe/fe-core/src/main/java/com/starrocks/planner/ResultSink.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PipelineParallelismTest.java
Labels: Approved

#11926 Starrocks be debug
  build.sh
Labels: Approved, title needs [type]

#11971 [BugFix] Fix cancel export use error accept function bug
  fe/fe-core/src/main/java/com/starrocks/analysis/CancelExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExportStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportRelativeStmtTest.java
Labels: Approved

#11847 [Feature] New RBAC framework: support basic db & table actions
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeTypes.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/ImpersonateUserPrivTableTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ImpersonatePrivInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#11717 [Feature]update memory size code for docker container
  be/src/util/mem_info.cpp
  bin/common.sh
Labels: Approved

#11641 [Enhancement] Support cumulative compaction on the tablet with missing version
  be/src/common/config.h
  be/src/storage/cumulative_compaction.cpp
  be/src/storage/cumulative_compaction.h
  be/src/storage/storage_engine.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/test/storage/cumulative_compaction_test.cpp
  be/test/test_main.cpp
Labels: Approved

#11871 [BugFix] Support authentication for StarRocks external table
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/http/BasicActionTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceTest.java
  gensrc/thrift/FrontendService.thrift
Labels: Approved

#11855 [Enhancement] optimize binary to decimal converter in parquet
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/formats/parquet/column_converter.cpp
  be/src/formats/parquet/encoding_plain.h
Labels: Approved

#10957 [Enhancement] Take slots in `conjunct_ctxs` as actively load fields in ORC format
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/vectorized/hdfs_scanner.cpp
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
Labels: Approved, sig/DLA

#11942 [BugFix]Fix CTE column prune bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneCTEConsumeColumnsRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: Approved

#11961 [Doc] update supported security measures
  docs/sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
Labels: documentation, Approved

#11323 [Feature] support max_by built-in function (#3288)
  be/src/exec/vectorized/aggregator.cpp
  be/src/exprs/agg/aggregate_factory.cpp
  be/src/exprs/agg/maxmin_by.h
  be/test/exprs/agg/aggregate_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
Labels: Approved

#11976 [Refactor] Fix moving a temporary object prevents copy elision
  be/src/storage/lake/delta_writer.cpp
Labels: Approved

#11776 [Feature] support host_name()
  be/src/exprs/vectorized/utility_functions.cpp
  be/src/exprs/vectorized/utility_functions.h
  be/test/exprs/vectorized/utility_functions_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#11977 [BugFix] fix no-pipeline engine ignore join conjuncts in nested loop join
  be/src/exec/vectorized/cross_join_node.cpp
Labels: Approved

#11974 [BugFix] fix right join on true
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
Labels: Approved

#11728 [Enhancement] Modify Statistics Resource Usage Policy
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved

#11968 [Refactor] Refine error message
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
Labels: Approved

#11662 [Enhancement] Add rate limit macro to limit too much log print
  be/src/storage/tablet.cpp
  be/src/storage/version_graph.cpp
  be/src/storage/version_graph.h
  be/src/util/once.h
  be/src/util/ratelimit.h
  be/test/CMakeLists.txt
  be/test/util/ratelimit_test.cpp
Labels: Approved

#11635 [Enhancement] Optimize log print and error message.
  be/src/agent/agent_task.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/HelpModule.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RangePartitionDesc.java
Labels: Approved

#11983 [BugFix] Fix be report version bug
  be/src/agent/agent_task.cpp
  be/src/agent/task_worker_pool.cpp
Labels: Approved

#11975 [Enhancement] Add more info for Known Backends
  fe/fe-core/src/main/java/com/starrocks/http/action/BackendAction.java
Labels: Approved

#11970 [Refactor][Lake] Remove unused protobuf fields
  be/src/storage/lake/delta_writer.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/exec/vectorized/join_hash_map_test.cpp
  be/test/io/cache_input_stream_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  gensrc/proto/lake_types.proto
Labels: Approved

#11994 [cherry-pick][branch-2.4][Enhancement] Flush wal in parallel (#9940)
  be/src/agent/task_worker_pool.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/txn_manager.cpp
  be/src/storage/txn_manager.h
Labels: automerge

#11997 [Doc] fix broken links
  docs/introduction/StarRocks_intro.md
Labels: documentation

#12003 [Doc] Add Data model supported by MV
  docs/release_notes/release-2.4.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved

#11984 [BugFix] Fix ClassNotFoundException when create UDF
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateFunctionStmt.java
Labels: Approved

#11986 [BugFix] Fix transaction stream load empty label return message
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
Labels: Approved

#11873 [Feature] Support create mv from mv
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: Approved

#12009 [Doc]add privilege description to catalog related docs and a new doc keywords
  docs/TOC.md
  docs/sql-reference/sql-statements/keywords.md
  docs/using_starrocks/catalog/hive_catalog.md
  docs/using_starrocks/catalog/hudi_catalog.md
  docs/using_starrocks/catalog/iceberg_catalog.md
Labels: documentation, Approved

#11991 [Cherry-pick 2.4] [Enhancement] Modify Statistics Resource Usage Policy (#11728)
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: automerge

#12021 [BugFix] Fix NestedLoopJoin crash when having join conjuncts
  be/src/exec/vectorized/cross_join_node.cpp
Labels: Approved

#12020 [Feature] Support snappy data page compression(#12019)
  be/src/storage/metadata_util.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/CompressionUtils.java
Labels: Approved

#12028 [cherry-pick][branch-2.3][Enhancement] Flush wal in parallel
  be/src/storage/storage_engine.cpp
  be/src/storage/txn_manager.cpp
  be/src/storage/txn_manager.h
Labels: automerge

#11993 [cherry-pick][branch-2.3][BugFix] Fix ClassNotFoundException when create UDF (#11984)
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateFunctionStmt.java
Labels: automerge

#12017 [BugFix][Lake] Fix unexpected I/O operation in bthread
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/general_tablet_writer.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/storage/cumulative_compaction_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/tablet_writer_test.cpp
Labels: Approved

#12016 [BugFix] Fix the mixed up function name.
  be/src/storage/persistent_index.cpp
  be/src/storage/primary_index.cpp
Labels: Approved

#11979 [cherry-pick][branch-2.2][BugFix]Support authentication for StarRocks external table (#11871)
  fe/fe-core/src/main/java/com/starrocks/analysis/InsertStmt.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/http/BasicActionTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceTest.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge, title needs [type]

#12039 [Enhancement] Optimize commit quorum wait time
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: Approved

#12032 [cherry-pick][branch-2.2][Enhancement] Flush wal in parallel
  be/src/storage/storage_engine.cpp
  be/src/storage/txn_manager.cpp
  be/src/storage/txn_manager.h
Labels: automerge

#11934 [Enhancement] Ranking window function support pushing down eq predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateRankingWindowRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/window.sql
Labels: Approved

#12045 [Enhancement][Lake] Close DeltaWriter in pthread
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
Labels: Approved

#12048 [Doc] update cancel load
  docs/sql-reference/sql-statements/data-manipulation/CANCEL LOAD.md
Labels: documentation, Approved

#12051 [Doc] Add CANCEL REFRESH MATERIALIZED VIEW
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/CANCEL REFRESH MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved

#12059 [BugFix] Fix the get rowset by version return unexpect result
  be/src/storage/olap_common.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/test/storage/tablet_mgr_test.cpp
Labels: Approved

#12046 [Cherry-pick 2.4] [BugFix]Fix list view parse fail bug (#12023)
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ViewPlanTest.java
Labels: automerge

#11596 [BugFix] Fix PageCache memory tracking inaccurately when adjust size
  be/src/storage/page_cache.cpp
Labels: Approved

#11964 [BugFix] fix the added filter bug when existential subquery to outer join
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinPredicateBase.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/UnsupportedNLJTest.java
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
Labels: Approved

#12074 [BugFix] Fix array_agg may crash in group by limit
  be/src/exprs/agg/nullable_aggregate.h
Labels: Approved

#12066 [BugFix]Fix show create table for external table
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved

#12022 [Enhancement] add some debug check for expression
  be/src/common/logconfig.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exprs/expr_context.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/memory_scratch_sink.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/storage/push_utils.cpp
  be/src/testutil/desc_tbl_builder.cc
  be/src/testutil/desc_tbl_builder.h
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
  be/test/exec/pipeline/table_function_operator_test.cpp
  be/test/exec/vectorized/chunks_sorter_heap_sort_test.cpp
  be/test/exec/vectorized/chunks_sorter_test.cpp
  be/test/exec/vectorized/csv_scanner_test.cpp
  be/test/exec/vectorized/file_scan_node_test.cpp
  be/test/exec/vectorized/hdfs_scan_node_test.cpp
  be/test/exec/vectorized/hdfs_scanner_test.cpp
  be/test/exec/vectorized/join_hash_map_test.cpp
  be/test/exec/vectorized/json_scanner_test.cpp
  be/test/exec/vectorized/parquet_scanner_test.cpp
  be/test/exec/vectorized/repeat_node_test.cpp
  be/test/exec/vectorized/sorting_test.cpp
  be/test/exec/vectorized/table_function_node_test.cpp
  be/test/exprs/vectorized/function_call_expr_test.cpp
  be/test/exprs/vectorized/lambda_function_expr_test.cpp
  be/test/formats/orc/orc_chunk_reader_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/runtime/memory_scratch_sink_test.cpp
  be/test/runtime/memory_scratch_sink_test_issue_8676.cpp
  be/test/runtime/vectorized/sorted_chunks_merger_test.cpp
  be/test/storage/chunk_helper_test.cpp
  be/test/storage/conjunctive_predicates_test.cpp
  be/test/storage/memtable_flush_executor_test.cpp
  be/test/storage/memtable_test.cpp
  be/test/storage/task/engine_storage_migration_task_test.cpp
  bin/start_be.sh
Labels: Approved

#12089 [Doc] update atomicity in brokerLoad
  docs/loading/BrokerLoad.md
Labels: documentation, Approved

#12090 [Doc] update atomicity in brokerLoad in Branch 2.4
  docs/loading/BrokerLoad.md
Labels: documentation

#12091 [Doc] update atomicity in brokerLoad in Branch 2.3
  docs/loading/BrokerLoad.md
Labels: documentation

#12097 [Doc] update persistent pk index
  docs/table_design/Data_model.md
Labels: documentation

#12096 [Doc] update persistent pk index
  docs/table_design/Data_model.md
Labels: documentation, Approved

#11253 [Feature] Support write quorum property for table
  be/src/agent/agent_task.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/delta_writer.h
  be/src/storage/segment_replicate_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/common/util/WriteQuorum.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionChecker.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadingTaskPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/transaction/WriteQuorumTest.java
  gensrc/proto/internal_service.proto
  gensrc/proto/types.proto
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/Types.thrift
Labels: Approved

#12015 [Feature] Multiversion cache
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.h
  be/src/exec/pipeline/chunk_accumulate_operator.cpp
  be/src/exec/pipeline/chunk_accumulate_operator.h
  be/src/exec/pipeline/dict_decode_operator.cpp
  be/src/exec/pipeline/dict_decode_operator.h
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/project_operator.cpp
  be/src/exec/pipeline/project_operator.h
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/query_cache/cache_operator.cpp
  be/src/exec/query_cache/cache_operator.h
  be/src/exec/query_cache/conjugate_operator.cpp
  be/src/exec/query_cache/conjugate_operator.h
  be/src/exec/query_cache/multilane_operator.cpp
  be/src/exec/query_cache/multilane_operator.h
  be/src/exec/query_cache/owner_info.h
  be/src/exec/vectorized/aggregator.cpp
  be/src/exec/vectorized/aggregator.h
  be/src/storage/tablet_manager.cpp
  be/test/exec/query_cache/query_cache_test.cpp
  be/test/exec/query_cache/transform_operator.cpp
  be/test/exec/query_cache/transform_operator.h
Labels: Approved

#12104 [Doc]Update timezone.md
  docs/using_starrocks/timezone.md
Labels: documentation, Approved

#12058 [Refactor][Lake] Change java package name of lake_{types,service}.proto
  be/src/gen_cpp/CMakeLists.txt
  be/src/storage/lake/tablet.h
  be/test/storage/lake/horizontal_compaction_task_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/DeleteLakeTableTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/ShardDeleter.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeBackupJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeRestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/delete/LakeDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/ShardDeleterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/DeleteTest.java
  gensrc/proto/lake_delete.proto
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
  gensrc/proto/olap_file.proto
  gensrc/proto/types.proto
Labels: Approved

#12098 [Enhancement] Enable close update compaction
  be/src/storage/olap_server.cpp
Labels: Approved

#11992 [BugFix] Fix FE restart failed when replaying schema change job
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
Labels: Approved

#12101 [Enhancement] optimize one key nullable group by case
  be/src/exec/vectorized/aggregate/agg_hash_map.h
  be/src/exec/vectorized/aggregate/agg_hash_set.h
Labels: Approved

#12100 [Refactor] Remove unused PlanFragmentExecutor get_next function
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
Labels: Approved

#11996 [Enhancement] Optimize primary replica selection
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
Labels: Approved

#12118 [UT] Fix OlapTableSinkTest UT
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
Labels: Approved

#12115 [BugFix]enable showing tablet for lake table
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
Labels: Approved

#12121 [Doc] update count distinct
  docs/loading/Flink-connector-starrocks.md
  docs/reference/System_limit.md
  docs/release_notes/release-2.4.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
Labels: documentation, Approved

#12125 [Doc] count(distinct),limits,retries for Branch 2.4
  docs/loading/Flink-connector-starrocks.md
  docs/reference/System_limit.md
  docs/release_notes/release-2.4.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
Labels: documentation

#12130 [Doc] sink.max-retries and system limits - Branch 2.3
  docs/loading/Flink-connector-starrocks.md
  docs/reference/System_limit.md
Labels: documentation

#11797 [Feature] Add cast varchar to bitmap
  be/src/exprs/vectorized/cast_expr.cpp
  be/src/types/bitmap_value.cpp
  be/src/types/bitmap_value.h
  be/src/types/bitmap_value_detail.h
  be/test/exprs/vectorized/cast_expr_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: Approved

#11987 [Enhancement] Optimize log print and error message, part two
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/runtime/primitive_type.cpp
  be/src/runtime/primitive_type.h
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: Approved

#12081 [BugFix] Fix error when tablet perform drop and clone at same time
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
  be/src/storage/task/engine_clone_task.cpp
Labels: Approved

#12116 [Enhancement] Disable push down aggregation default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: Approved

#12144 [BugFix] disable use_broker for old FE
  be/src/runtime/snapshot_loader.cpp
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: Approved

#12154 [Doc] Fix FQDN default
  docs/administration/enable_fqdn.md
Labels: documentation, Approved

#12156 [Doc] Add SHOW PROCESSLIST
  docs/TOC.md
  docs/sql-reference/sql-statements/Administration/SHOW PROCESSLIST.md
Labels: documentation, Approved

#12008 [BugFix] Make exception message better when transactions are not done
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#12164 [BugFix] fix null aware anti join in not in subquery (backport #11551)
  be/src/exec/vectorized/join_hash_map.h
  be/src/exec/vectorized/join_hash_map.tpp
Labels: automerge

#12162 [Refactor] Remove some unused codes of hive/hudi
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/EventMessages.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveCommonStats.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HivePartitionName.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/IHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/Partition.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
Labels: Approved

#12035 [Feature] New RBAC privilege framework: complicated GRANT
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ActionSet.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeTypes.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/UserPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantPrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRevokeClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRevokePrivilegeObjects.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/privilege/ActionSetTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeCollectionTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokePrivilegeStmtTest.java
Labels: Approved

#12170 [Cherry-pick 2.2][Enhancement] Pipeline profile refine (#12123)
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/util/runtime_profile.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: automerge

#12151 [Enhancement] update protobuf-java due to CVE-2022-3171
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: Approved

#12174 [cherry-pick][branch-2.4][BugFix] disable use_broker for old FE(#12144)
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: automerge

#12173 [Refactor] Support to resend request of hive thrift api "getPartitionByNames"
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
Labels: Approved

#12067 [Enhancement] Force set output row count minimum to 1
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportHandleTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportRelativeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectConstTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/agg-pushdown.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/join.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/predicate-extract.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/predicate-pushdown.sql
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q7.sql
  fe/fe-core/src/test/resources/sql/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/tpch/q16.sql
  fe/fe-core/src/test/resources/sql/tpch/q17.sql
  fe/fe-core/src/test/resources/sql/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/tpch/q2.sql
  fe/fe-core/src/test/resources/sql/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/tpch/q4.sql
  fe/fe-core/src/test/resources/sql/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/tpch/q9.sql
Labels: Approved

#12157 [BugFix][Lake] Should not run gc if BE not built with --use-staros
  be/src/runtime/exec_env.cpp
  be/src/storage/lake/gc.cpp
Labels: Approved

#12193 [Bugfix] fix BE cpu cores updating (backport #12187)
  fe/fe-core/src/main/java/com/starrocks/system/BackendCoreStat.java
  fe/fe-core/src/test/java/com/starrocks/system/BackendTest.java
Labels: automerge

#12175 [Doc]add CANCEL EXPORT
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/CANCEL EXPORT.md
Labels: documentation, Approved

#12185 [BugFix] aggregate query statistic from all executor nodes (backport #11801)
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
Labels: automerge

#12184 [BugFix] aggregate query statistic from all executor nodes (backport #11801)
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
Labels: automerge

#12197 [Doc]update TOC
  docs/TOC.md
Labels: documentation

#12155 [Refactor] refactor max_routine_load_job_num error msg
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadManager.java
Labels: Approved

#12127 [Cherry-pick-2.2][BugFix] Fix FE restart failed when replaying schema change job
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: automerge

#12211 [Doc]modify incorrect description in External_table.md
  docs/using_starrocks/External_table.md
Labels: documentation, Approved

#12208 [Doc] Add Stream_Load_transaction_interface.md in Branch 2.4
  docs/TOC.md
  docs/loading/Stream_Load_transaction_interface.md
Labels: documentation

#12133 [BugFix] Fix join reorder bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ReplaceColumnRefRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ReplaceColumnRefRewriterTest.java
Labels: Approved

#12137 [BugFix] Fix parser for unitBoundary
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: Approved

#12232 [Doc] add 8 date functions for Branch 2.3
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/hours_diff.md
  docs/sql-reference/sql-functions/date-time-functions/minutes_diff.md
  docs/sql-reference/sql-functions/date-time-functions/months_diff.md
  docs/sql-reference/sql-functions/date-time-functions/quarter.md
  docs/sql-reference/sql-functions/date-time-functions/seconds_diff.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/weeks_diff.md
  docs/sql-reference/sql-functions/date-time-functions/years_diff.md
Labels: documentation

#12229 [Doc] add 8 date functions
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/hours_diff.md
  docs/sql-reference/sql-functions/date-time-functions/minutes_diff.md
  docs/sql-reference/sql-functions/date-time-functions/months_diff.md
  docs/sql-reference/sql-functions/date-time-functions/quarter.md
  docs/sql-reference/sql-functions/date-time-functions/seconds_diff.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/weeks_diff.md
  docs/sql-reference/sql-functions/date-time-functions/years_diff.md
  docs/sql-reference/sql-statements/data-manipulation/CANCEL REFRESH MATERIALIZED VIEW.md
Labels: documentation, Approved

#11810 [Enhancement] Support adjust cachesize automatically
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/storage/olap_server.cpp
  be/src/storage/page_cache.cpp
  be/src/storage/page_cache.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/util/lru_cache.cpp
  be/src/util/lru_cache.h
  be/test/storage/page_cache_test.cpp
Labels: Approved

#12220 [BugFix] Fix wrong logical properties when TopN has a HashJoin Node
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#12245 [cherry-pick] [branch-2.4] [Enhancement] Support adjust cachesize automatically (#11810)
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/storage/olap_server.cpp
  be/src/storage/page_cache.cpp
  be/src/storage/page_cache.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/util/lru_cache.cpp
  be/src/util/lru_cache.h
  be/test/storage/page_cache_test.cpp
Labels: automerge

#11517 [Feature] Unify Load Planner
  be/src/connector/file_connector.cpp
  be/src/exec/vectorized/file_scan_node.cpp
  fe/fe-core/src/main/java/com/starrocks/load/EtlJobType.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
  gensrc/thrift/InternalService.thrift
Labels: Approved

#11985 [Enhancement] support export sink in pipeline engine
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/sink/export_sink_operator.cpp
  be/src/exec/pipeline/sink/export_sink_operator.h
  be/src/exec/pipeline/sink/file_sink_operator.cpp
  be/src/exec/pipeline/sink/file_sink_operator.h
  be/src/exec/pipeline/sink/sink_io_buffer.h
  be/src/runtime/export_sink.h
  fe/fe-core/src/main/java/com/starrocks/planner/ExportSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: Approved

#12171 [Enhancement] Limit the number of direct children of expression
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/TokenNumberListener.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserBench.java
Labels: Approved

#12163 [BugFix] fix null aware anti join in not in subquery (backport #11551)
  be/src/exec/vectorized/join_hash_map.h
  be/src/exec/vectorized/join_hash_map.tpp
  be/test/exec/vectorized/join_hash_map_test.cpp
Labels: automerge

#12262 [Doc]Update GRANT.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation, Approved

#12265 [Doc] update the GRANT statement
  docs/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation

#12061 [Enhancement] Optimize colocate balance on backend restart
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
Labels: Approved

#12267 [Enhancement] Fix udf-extensions security issue
  java-extensions/udf-examples/pom.xml
Labels: Approved

#12273 [Doc] add 2.2.8 release notes-Branch 2.3
  docs/release_notes/release-2.2.md
Labels: documentation

#12271 [Doc] add 2.2.8 release notes
  docs/release_notes/release-2.2.md
Labels: documentation, Approved

#12251 [Feature] Add cost time of hms thrift api to planner profile
  fe/fe-core/src/main/java/com/starrocks/external/CachingRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/external/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetastoreOperations.java
  fe/fe-core/src/main/java/com/starrocks/external/hudi/HudiRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/sql/PlannerProfile.java
Labels: Approved

#11854 [Feature] Support primary key replicated storage
  be/src/exec/tablet_sink.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/memtable.cpp
  be/src/storage/memtable_flush_executor.cpp
  be/src/storage/memtable_rowset_writer_sink.h
  be/src/storage/memtable_sink.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/segment_replicate_executor.cpp
  be/test/storage/rowset_merger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/task/StreamLoadTask.java
  gensrc/proto/data.proto
  gensrc/thrift/FrontendService.thrift
Labels: Approved

#12278 [BugFix] Fix bug MV refresh lose MAXVALUE
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
Labels: Approved

#12274 [BugFix] Fix some query exceptions of hudi table
  be/src/connector/hive_connector.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/external/hudi/HudiRemoteFileIO.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScanner.java
Labels: Approved

#12217 [BugFix] Publish timeout in commitPreparedTransaction should raise error
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
Labels: Approved
