Repository StarRocks/starrocks, pull requests merged in 2022-12, with the labels that each got.

#14272 [BugFix] Avoid using the same host name with another existed fe node
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
Labels: Approved, be-build, 2.5, 2.4

#14414 [BugFix][Cherry-pick 2.3] Fix missing hack NULL_TYPE for field child_type (#14308)
  docs/TOC.md
  docs/sql-reference/sql-functions/cast.md
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: documentation, automerge, be-build

#14198 [BugFix] Fixup reading the ensemble of rowsets instead of delta resets mistakenly
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/query_cache/cache_operator.cpp
  be/src/exec/query_cache/cache_operator.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
Labels: Approved, be-build

#14396 [BugFix] Forbid Async Mv create HLL/BITMAP/PERCENTILE type
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: Approved, title needs [type], be-build, 2.5

#13942 [Enhancement] spark-dpp support spark3
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/IgnoredEvent.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SqlWithIdUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeApplyWithTableFunction.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneTableFunctionColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinOnExpressionToChildProject.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeStatus.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/ExpressionEncoderHelper.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
Labels: Approved, be-build

#14412 [BugFix] serialize starletPort in BackendHbResponse
  fe/fe-core/src/main/java/com/starrocks/system/BackendHbResponse.java
  fe/fe-core/src/test/java/com/starrocks/system/BackendHbResponseTest.java
Labels: Approved, be-build

#14361 [BugFix]get empty table names in drop db
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AccessTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DatabaseTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#14430 [Doc] Add Write Quorum
  docs/loading/Loading_intro.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, Approved, be-build, 2.5

#14409 [Enhancement] Be support customize java opts
  bin/start_be.sh
  conf/be.conf
Labels: be-build

#14145 [BugFix] Fix multi join complex depend column relation
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/MultiJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/ReorderJoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#14343 [Enhancement] Add location message for show create external table
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: Approved, be-build

#14435 [BugFix] optimize single table without predicate mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/OnlyScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build, 2.5

#14460 [Doc] adjust TOC
  docs/TOC.md
  docs/sql-reference/sql-statements/account-management/SHOW AUTHENTICATION.md
Labels: documentation, be-build

#14454 [Doc] Fix MV Config
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved, be-build, 2.5, 2.4

#14461 [Doc] fixed an invalid link
  docs/TOC.md
Labels: documentation, be-build

#14450 [Enhancement] normalize parttion range predicate with min_value
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build

#14466 [BugFix] fix partial partition rewrite bug (#14130)
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#14424 [BugFix] avoid accumulate too many chunks in NLJ
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/test/storage/chunk_helper_test.cpp
Labels: Approved, be-build, 2.5, 2.4

#13619 [Enhancement] Support size tiered compaction strategy
  be/src/common/config.h
  be/src/storage/CMakeLists.txt
  be/src/storage/compaction_candidate.h
  be/src/storage/compaction_context.h
  be/src/storage/compaction_policy.h
  be/src/storage/compaction_task.h
  be/src/storage/default_compaction_policy.cpp
  be/src/storage/default_compaction_policy.h
  be/src/storage/size_tiered_compaction_policy.cpp
  be/src/storage/size_tiered_compaction_policy.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/test/CMakeLists.txt
  be/test/storage/compaction_manager_test.cpp
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: Approved, be-build

#14467 [BugFix] Check whether the database and table exist to prevent NPE in analyze
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeStatus.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticExecutorTest.java
Labels: Approved, be-build

#14074 [Tool]Support delete tablet meta by table id
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/tools/meta_tool.cpp
Labels: Approved, be-build

#14486 [BugFix] backup empty database: error message is not clear (#13382)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
Labels: Approved, be-build, 2.5

#14394 [Enhancement] Infer default storage medium when creating table
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageMediumInfoTest.java
Labels: be-build

#14498 [UT] Fix ut complie error since merge conflict
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: Approved, be-build

#14493 [Docs] add keywords descriptions to 4 load docs in Branch 2.5
  docs/loading/BrokerLoad.md
  docs/loading/StreamLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, title needs [type], be-build

#14494 [Docs] add keywords descriptions to 4 load docs in Branch 2.4
  docs/loading/BrokerLoad.md
  docs/loading/StreamLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, title needs [type], be-build

#14492 [Docs] add keywords descriptions to 4 load docs
  docs/loading/BrokerLoad.md
  docs/loading/StreamLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, Approved, title needs [type], be-build

#14495 [Docs] add keywords descriptions to 4 load docs in Branch 2.3
  docs/loading/BrokerLoad.md
  docs/loading/StreamLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, title needs [type], be-build

#14505 [Doc] Fix MV required
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
Labels: documentation, Approved, be-build, 2.5, 2.4

#13338 [Enhancement] Remove sensitive info from create routine load stmt log
  fe/fe-core/src/main/java/com/starrocks/common/util/PrintableMap.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
Labels: Approved, be-build

#14263 [Enhancement] Remove sensitive info of broker load from audit log (backport #13325) (branch-2.5)
  fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LabelName.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PrintableMap.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ResourceDesc.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExportRelativeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/LoadStmtTest.java
Labels: automerge, be-build

#14261 [Enhancement] Remove access info in broker log (backport #13329) (branch-2.5)
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsService.java
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/HDFSBrokerServiceImpl.java
Labels: automerge, be-build

#14512 [Doc] 2.5 conditional update feature in Branch 2.5
  docs/loading/Load_to_Primary_Key_tables.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, be-build

#14511 [Doc] 2.5 conditional update feature
  docs/loading/Load_to_Primary_Key_tables.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, Approved, be-build

#14515 Branch 2.5
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/Loading_intro.md
Labels: documentation, title needs [type], be-build

#14276 [Refactor] refactor Coordinator and CoordinatorPrepare
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/TPCDSCoordTest.java
Labels: be-build

#14392 [Feature] Support import automatic partition creation syntax
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExpressionPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: Approved, be-build

#14517 [Doc] Fix Quorum
  docs/loading/Loading_intro.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, Approved, be-build, 2.5

#14491 [Feature] support column privilege for xc
  fe/fe-core/src/main/java/com/starrocks/analysis/TablePattern.java
  fe/fe-core/src/main/java/com/starrocks/analysis/UserIdentity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/PrivTable.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/TablePrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/TablePrivTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRevokePrivilegeObjects.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeColumnTest.java
Labels: be-build

#14524 [Doc] Fix Quorum
  docs/loading/Loading_intro.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, be-build

#14225 [Feature] Add a bitmap_to_base64 function
  be/src/exprs/vectorized/bitmap_functions.cpp
  be/src/exprs/vectorized/bitmap_functions.h
  be/test/exprs/vectorized/bitmap_functions_test.cpp
  gensrc/script/vectorized/vectorized_functions.py
Labels: be-build

#14482 [Feature][cherry-pick][branch-2.5] use Array<DecimalV3> for DLA (#12952)
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/runtime/types.h
  be/test/exec/test_data/orc_scanner/dec_orc.orc
  be/test/formats/orc/orc_chunk_reader_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ArrayType.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
Labels: automerge, be-build

#14490 [BugFix] fix union rewrite bug for mv with tll
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build, 2.5

#14476 [BugFix] Fix persistent index upsert with wrong size
  be/src/storage/primary_index.cpp
Labels: Approved, be-build, 2.5

#14413 [BugFix][Cherry-pick 2.4] Fix missing hack NULL_TYPE for field child_type (#14308)
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: automerge, be-build

#14544 [Doc] Add View BE Config Item
  docs/administration/Configuration.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#14484 [Enhancement] Upgrade postgresql due to CVE-2022-41946
  fe/pom.xml
Labels: be-build

#14530 Branch 2.5
  docs/TOC.md
  docs/loading/BrokerLoad.md
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
  docs/unloading/Export.md
  docs/unloading/Flink_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, title needs [type], be-build

#14550 [Doc] 2.5 remove brokers
  docs/TOC.md
  docs/loading/BrokerLoad.md
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
  docs/unloading/Export.md
  docs/unloading/Flink_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, Approved, be-build

#14516 [Enhancement] FE support JDK11 compile
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved, be-build

#14554 [BugFix] align the null flag of evaluating a part of elements
  be/src/column/column_helper.cpp
  be/src/column/column_helper.h
  be/src/exec/vectorized/project_node.cpp
  be/src/exprs/vectorized/array_map_expr.cpp
  be/test/column/column_helper_test.cpp
Labels: Approved, 2.5

#14543 [BugFix] Fix plan connectedness for NlJoin
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved, be-build, 2.5

#14558 [BugFix] fix aggregate checker bug during mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateRewriteChecker.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build, 2.5

#14487 [Enhancement] str_to_date add trim
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: Approved, be-build

#13789 [Enhancement] check max_user_connections must less than qe_max_connection
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/UserPropertyTest.java
Labels: Approved, be-build

#14568 [BugFix] fix clang compile issue
  be/src/util/stack_util.h
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: be-build

#14546 [BugFix] Fix Load throws NPE when force drop BE node
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
Labels: Approved, be-build

#14569 [Feature] Support pathStyleAccess for broker load
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: Approved, be-build

#14570 [Doc] Revise and improve javadoc of class Writeable
  fe/fe-core/src/main/java/com/starrocks/common/io/Writable.java
Labels: be-build

#14566 [UT] fix BE metrics test when staros enabled
  be/test/http/metrics_action_test.cpp
Labels: be-build

#14303 [cherry-pick][branch-2.2][Feature] Support compact rocksdb meta action (#10115)
  be/src/http/CMakeLists.txt
  be/src/http/action/compact_rocksdb_meta_action.cpp
  be/src/http/action/compact_rocksdb_meta_action.h
  be/src/service/http_service.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: automerge, title needs [type], be-build

#14513 [BugFix] Be crash when doing compaction apply
  be/src/storage/tablet_updates.cpp
Labels: Approved, be-build, 2.5

#14567 [BugFix] Fix insert resource group not match database classifier
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
Labels: Approved, be-build, 2.5

#14390 [Enhancement] Support profile for olap table sink & broker load
  be/src/exec/pipeline/olap_table_sink_operator.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/util/reusable_closure.h
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved, be-build

#14432 [Doc] Mask Broker in Doc
  docs/TOC.md
  docs/administration/Configuration.md
  docs/administration/deploy_broker.md
Labels: documentation, Approved, be-build, 2.5

#14437 [Doc] Update Resource Groups
  docs/administration/resource_group.md
Labels: documentation, Approved, be-build, 2.5

#14453 [Doc] Update Backup restore
  docs/administration/Backup_and_restore.md
  docs/sql-reference/sql-statements/data-definition/BACKUP.md
  docs/sql-reference/sql-statements/data-definition/CANCEL BACKUP.md
  docs/sql-reference/sql-statements/data-definition/CANCEL RESTORE.md
  docs/sql-reference/sql-statements/data-definition/CREATE REPOSITORY.md
  docs/sql-reference/sql-statements/data-definition/DROP REPOSITORY.md
  docs/sql-reference/sql-statements/data-definition/RESTORE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW BACKUP.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW REPOSITORIES.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW RESTORE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW SNAPSHOT.md
Labels: documentation, Approved, be-build, 2.5

#14465 [Doc] Add Information Schema
  docs/TOC.md
  docs/administration/information_schema.md
Labels: documentation, Approved, be-build, 2.5

#14594 [Enhancement] filesystem API for dropping local cache
  be/src/fs/fs.h
  be/src/fs/fs_starlet.cpp
Labels: Approved, be-build

#14590 [BugFix] Log statement cannot be serialized
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved, be-build, 2.5

#14596 [Doc]update external catalogs and external tables for 2.5
  docs/data_source/External_table.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, Approved, be-build

#14433 [Enhancement] Print remaining tablets for decommission BE
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
Labels: Approved, be-build

#14614 [Doc] Fix Storage Root Path
  docs/administration/Configuration.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#13693 [Feature] maintenance of materialized view
  be/src/gen_cpp/CMakeLists.txt
  be/src/service/backend_base.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HashDistributionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/rpc/PBackendService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/PMVMaintenanceTaskRequest.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/BinlogConsumeStateVO.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/EpochCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/IMTCreator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVEpoch.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceJob.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceTask.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/KeyInference.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/mv/MVEpochTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/mv/MVMaintenanceJobTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
  gensrc/thrift/BackendService.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/MVMaintenance.thrift
Labels: Approved, be-build

#14556 [BugFix] Fix the Fe Follower's not forward User Variable to the Master bug
  fe/fe-core/src/main/java/com/starrocks/analysis/Subquery.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/DbPrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/GlobalPrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/ImpersonateUserPrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/ResourcePrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/TablePrivEntry.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SqlDigestBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SqlWithIdUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/SubqueryOperator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/LoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowTableStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/analyzer/SimpleExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/analyzer/SimpleSelectAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AST2StringBuilderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeShowTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokePrivilegeStmtTest.java
Labels: be-build

#14592 [BugFix] support structType matchesType() used in function argument type matches
  fe/fe-core/src/main/java/com/starrocks/catalog/StructType.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypeTest.java
Labels: Approved, be-build, 2.5

#14657 [Doc] Change s3-ap-northeast-1 to s3.ap-northeast-1
  docs/loading/BrokerLoad.md
Labels: documentation, be-build, 2.5, 2.4, 2.3, 2.2

#14613 [BugFix] Merge overlap segments of one rowset in lake tablet compaction
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/tablet_reader.cpp
  be/test/storage/lake/horizontal_compaction_task_test.cpp
Labels: Approved, be-build

#14610 [BugFix] Fix compaction scheduler destruct crash
  be/src/storage/storage_engine.h
Labels: Approved, be-build, 2.5

#14607 [Tool][Cherry-pick][Branch-2.2]Support delete tablet meta by table id (#14074)
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/tools/meta_tool.cpp
Labels: automerge, be-build

#14672 [License] Change Elastic License to Apache License 2.0
  gensrc/proto/Makefile
  gensrc/proto/data.proto
  gensrc/proto/descriptors.proto
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
  gensrc/proto/olap_common.proto
  gensrc/proto/olap_file.proto
  gensrc/proto/orc_proto.proto
  gensrc/proto/persistent_index.proto
  gensrc/proto/segment.proto
  gensrc/proto/snapshot.proto
  gensrc/proto/tablet_schema.proto
  gensrc/proto/types.proto
  gensrc/script/Makefile
  gensrc/script/vectorized/gen_vectorized_functions.py
  gensrc/script/vectorized/vectorized_functions.py
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/BackendService.thrift
  gensrc/thrift/Data.thrift
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/Exprs.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/InternalService.thrift
  gensrc/thrift/MVMaintenance.thrift
  gensrc/thrift/Makefile
  gensrc/thrift/MasterService.thrift
  gensrc/thrift/Partitions.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Planner.thrift
  gensrc/thrift/QueryPlanExtra.thrift
  gensrc/thrift/ResourceUsage.thrift
  gensrc/thrift/RuntimeFilter.thrift
  gensrc/thrift/StarrocksExternalService.thrift
  gensrc/thrift/Status.thrift
  gensrc/thrift/StatusCode.thrift
  gensrc/thrift/Types.thrift
  gensrc/thrift/WorkGroup.thrift
Labels: title needs [type]

#14593 [BugFix] Make Struct create all subfield columns to prevent BE crash
  be/src/column/column_helper.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/parquet/column_reader.cpp
  be/src/runtime/types.cpp
  be/test/formats/orc/orc_chunk_reader_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/runtime/type_descriptor_test.cpp
  gensrc/proto/types.proto
Labels: Approved, be-build, 2.5

#14669 [Doc] modify deploy broker link in BrokerLoad in Branch 2.5
  docs/loading/BrokerLoad.md
Labels: documentation, be-build

#14670 [Doc] modify deploy broker link in BrokerLoad in Branch 2.4
  docs/loading/BrokerLoad.md
Labels: documentation, be-build

#14668 [Doc] modify deploy broker link in BrokerLoad
  docs/loading/BrokerLoad.md
Labels: documentation, Approved, be-build

#14671 [Doc] modify deploy broker link in BrokerLoad in Branch 2.3
  docs/loading/BrokerLoad.md
Labels: documentation, be-build

#14231 [Enhancement][Lake] Drop disk cache after GC
  be/src/fs/fs_util.h
  be/src/fs/rapidjson_stream_adapter.h
  be/src/service/staros_worker.cpp
  be/src/storage/lake/filenames.h
  be/src/storage/lake/fixed_location_provider.h
  be/src/storage/lake/gc.cpp
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/starlet_location_provider.cpp
  be/src/storage/lake/starlet_location_provider.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/test/storage/lake/gc_test.cpp
Labels: Approved, be-build

#14678 [BugFix]merge pushdown predicate to cte(backport #14472)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateCTEConsumeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: automerge, be-build

#14620 [BugFix] Fix broker load can not do conditional update and add some pre check for conditional update
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
Labels: Approved, 2.5.0, be-build, 2.5

#13962 [Enhancement] Make new publish mechanism enabled by default
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: Approved, be-build, 2.5

#14685 [Enhancement] Infer default storage medium when creating table (#14394)
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageMediumInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: automerge, be-build

#14642 [BugFix] fix mv rewrite bug with partition prune
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build, 2.5

#14680 [BugFix][Cherry-Pick][Branch-2.5] Make Struct create all subfield columns to prevent BE crash
  be/src/column/column_helper.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/parquet/column_reader.cpp
  be/src/runtime/types.cpp
  be/test/formats/orc/orc_chunk_reader_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/runtime/type_descriptor_test.cpp
  gensrc/proto/types.proto
Labels: automerge, be-build

#14571 [Enhancement] Optimize thrift server pool
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java
Labels: Approved, be-build

#14676 [BugFix]merge pushdown predicate to cte(backport #14472)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateCTEConsumeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: automerge, be-build

#14677 [BugFix]merge pushdown predicate to cte(backport #14472)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateCTEConsumeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: automerge, be-build

#14689 [Doc]Update TOC.md
  docs/TOC.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#14598 [Enhancement] replace str_to_date trim
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: Approved, be-build

#14699 [Doc] updated BrokerLoad & ExportOverview in Branch 2.5
  docs/loading/BrokerLoad.md
  docs/unloading/Export.md
Labels: documentation, be-build

#13968 [Refactor] Refactor build_hash_map and build_set to remove duplicated codes
  be/src/exec/vectorized/aggregate/agg_hash_map.h
  be/src/exec/vectorized/aggregate/agg_hash_set.h
  be/src/exec/vectorized/aggregator.cpp
  be/src/exec/vectorized/aggregator.h
  be/test/exec/vectorized/agg_hash_map_test.cpp
Labels: Approved, be-build

#14636 [BugFix] Fix broker load parallel performance issue since chunk buffer limit to one
  be/src/exec/vectorized/connector_scan_node.cpp
Labels: Approved, be-build, 2.5

#14698 [Doc] updated BrokerLoad & ExportOverview
  docs/loading/BrokerLoad.md
  docs/unloading/Export.md
Labels: documentation, Approved, be-build

#14708 [Doc] Add deploy in Docker
  docs/TOC.md
  docs/administration/deploy_with_docker.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#14714 Update TOC.md
  docs/TOC.md
Labels: documentation, title needs [type], be-build

#14640 [Enhancement] Add toNormalForm to PlanNodes
  fe/fe-core/src/main/java/com/starrocks/planner/AnalyticEvalNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/AssertNumRowsNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/NestLoopJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RepeatNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SetOperationNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/TableFunctionNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/stream/StreamAggNode.java
  gensrc/thrift/Normalization.thrift
Labels: Approved, be-build

#14719 [Refactor] [cherry-pick] Remove some unused code of TabletSink (#7777)
  be/src/exec/data_sink.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/http/action/compaction_action.cpp
Labels: automerge, be-build

#14724 [Doc]iceberg catalog does not support v2 tables in 2.5
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation, Approved, be-build, 2.5

#14731 [Doc] Add MV note to 2.3
  docs/using_starrocks/Materialized_view.md
Labels: documentation, be-build

#14703 [BugFix] fix count(*) with rollup mv rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build, 2.5

#14510 [Enhancement] vectorized runtime filter min/max
  be/src/exprs/vectorized/runtime_filter.h
Labels: Approved, be-build

#14609 [Enhancement] optimize performance of percentile_cont function
  be/src/exprs/agg/percentile_cont.h
Labels: Approved, be-build, 2.5, 2.4

#14635 [BugFix] Fix delete stmt not trigger event to compaction framework
  be/src/storage/push_handler.cpp
Labels: Approved, be-build, 2.5

#14752 [Doc] Add MV note to 2.4
  docs/using_starrocks/Materialized_view.md
Labels: documentation, be-build

#14589 [BugFix] Fix potential race condition of compaction manager
  be/src/storage/compaction_manager.h
Labels: Approved, be-build, 2.5

#14705 [Enhancement] Infer default storage medium when creating table (#14394)
  fe/fe-core/src/main/java/com/starrocks/analysis/ModifyPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageMediumInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: be-build

#14720 [Enhancement] Infer default storage medium when creating table (#14394)
  fe/fe-core/src/main/java/com/starrocks/analysis/ModifyPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageMediumInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: be-build

#14735 [Enhancement] make error msg more readable
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMVStmtTest.java
Labels: Approved, be-build

#14756 [Doc] add-aggregate-key
  docs/table_design/Data_model.md
Labels: documentation, Approved, be-build

#14771 [Doc] Replace StarRocks Download Path in 2.3
  README.md
  docs/administration/deploy_broker.md
  docs/administration/deploy_cn.md
  docs/loading/Flink_cdc_load.md
Labels: documentation, be-build

#14770 [Doc] Replace StarRocks Download Path
  docs/administration/deploy_broker.md
  docs/administration/deploy_cn.md
Labels: documentation, Approved, 2.5, 2.4

#14781 [Doc] Replace SR Download path
  docs/loading/Flink_cdc_load.md
  docs/quick_start/Deploy.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#14786 [Enhancement][Cherry-pick] replace str_to_date trim (#14598)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: automerge, be-build

#14761 [Enhancement] Adapt list partition names when manually refreshing external table
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
Labels: Approved, be-build

#14793 [UT] Fix compaction unstable ut
  be/src/storage/compaction_scheduler.cpp
  be/src/storage/compaction_scheduler.h
  be/src/storage/olap_server.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: Approved, be-build, 2.5

#14603 [Enhancement] Support cancel for TabletReader and SegmentIterator
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  be/test/storage/tablet_updates_test.cpp
Labels: Approved, be-build

#14665 [BugFix] compute memory layout of TupleDescriptor after setting nullable for SlotDescriptor
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: Approved, be-build, 2.5, 2.4, 2.3

#14760 [Refactor] [1/N] Refactor orc chunk reader
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/formats/CMakeLists.txt
  be/src/formats/orc/fill_function.cpp
  be/src/formats/orc/fill_function.h
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
  be/src/formats/orc/utils.cpp
  be/src/formats/orc/utils.h
Labels: Approved, be-build

#14815 [UT] Add checks for errors reported by time_slice
  be/test/exprs/vectorized/time_functions_test.cpp
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
Labels: Approved, be-build

#14840 [BugFix] compute memory layout of TupleDescriptor after setting nullable for SlotDescriptor (backport #14665)
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: automerge, be-build

#14816 [Doc] 2.2 release notes and fe config
  docs/administration/Configuration.md
  docs/administration/timezone.md
  docs/developers/How_to_Contribute.md
  docs/loading/Flink_cdc_load.md
  docs/release_notes/release-2.1.md
  docs/release_notes/release-2.2.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/table_design/Data_model.md
Labels: documentation, Approved, be-build

#14832 [BugFix] fix nested mv rewrite bug
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build, 2.5

#14843 [BugFix] Cherry pick fixes of time_slice and max_by for 2.5
  be/src/exprs/agg/factory/aggregate_resolver_minmaxany.cpp
  be/src/exprs/vectorized/time_functions.cpp
  be/src/exprs/vectorized/time_functions.h
  be/test/exprs/agg/aggregate_test.cpp
  be/test/exprs/vectorized/time_functions_test.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#14819 [BugFix] Be maybe crash if PrimaryKey table using persistent index
  be/src/storage/persistent_index.cpp
  be/test/storage/persistent_index_test.cpp
Labels: Approved, be-build, 2.5, 2.4

#13642 [Feature] Support assign sort key of primary key model by schema change reorder.
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/schema_change.cpp
  be/src/storage/schema_change.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/exprs/vectorized/math_functions_test.cpp
  be/test/storage/tablet_updates_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/OlapTableAlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: Approved, be-build

#14031 [Refactor] Change agg intermedaite state type to varbinary
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeDecimalV3Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q1.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q22.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q1.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q22.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q1.sql
Labels: be-build

#14846 [BugFix] Fix data access for bitmap and hll with lead/lag (#14743)
  be/src/column/object_column.cpp
  be/src/exprs/agg/window.h
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#14802 [BugFix] shouldn't use TreeNode.contains to check the type support join on or not
  fe/fe-core/src/main/java/com/starrocks/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/analyzer/SimpleQueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzePredicateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MetricTypeTest.java
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#14861 [BugFix] Do not do update compaction if no eligible rowset found
  be/src/storage/tablet_updates.cpp
Labels: be-build, 2.5, 2.4

#14850 [Doc]update data loading related docs for 2.5
  docs/sql-reference/sql-statements/data-manipulation/CANCEL LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW LOAD.md
Labels: documentation, Approved, be-build, 2.5

#14852 [BugFix] Fix fe crash when table dropped force before txn visible
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#14877 [BugFix][cherry-pick][branch-2.5] fix use TreeNode.contains to check the type support join on or not (#14802)
  fe/fe-core/src/main/java/com/starrocks/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzePredicateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MetricTypeTest.java
Labels: automerge, be-build

#14884 [Doc] Revise Backup and Compression
  docs/administration/Backup_and_restore.md
  docs/sql-reference/sql-statements/data-definition/BACKUP.md
  docs/sql-reference/sql-statements/data-definition/CREATE REPOSITORY.md
  docs/sql-reference/sql-statements/data-definition/RESTORE.md
  docs/table_design/data_compression.md
Labels: documentation, be-build

#14790 [Enhancement] Add meta incomplete check (#14246)
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/InvalidMetaDirException.java
  fe/fe-core/src/main/java/com/starrocks/leader/MetaHelper.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/StarRocksFETest.java
  fe/fe-core/src/test/java/com/starrocks/leader/MetaHelperTest.java
Labels: be-build

#14885 [Doc] update sr download link
  .github/ISSUE_TEMPLATE/general-question.md
  docs/administration/k8s_operator_cn.md
  docs/faq/Others.md
  docs/release_notes/release-2.2.md
  docs/sql-reference/sql-functions/array-functions/array_sort.md
  docs/sql-reference/sql-statements/data-types/JSON.md
  docs/unloading/Flink_connector.md
  tools/stream_load/README.md
Labels: documentation, Approved, be-build

#14875 [Enhancement] check db priv after found udf(backport#14870)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: automerge, be-build

#14817 [BugFix][Enhancement]Lambda functions reuse sub expressions without lambda arguments
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: be-build, 2.5

#14878 [Doc] add prepared state to BrokerLoad
  docs/loading/BrokerLoad.md
Labels: documentation, Approved, be-build

#13963 [BugFix] Fix key index out of bound in schema of _do_merge_horizontally.
  be/src/column/vectorized_schema.cpp
  be/src/column/vectorized_schema.h
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset_merger.cpp
  be/test/storage/compaction_utils_test.cpp
Labels: Approved, be-build, 2.5

#14896 [Enhancement] Turn on table name restrictions
  fe/fe-core/src/main/java/com/starrocks/common/FeNameFormat.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateTableLikeTest.java
Labels: Approved, be-build

#14799 [Feature] refine MV interface
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/BinlogConsumeStateVO.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVEpoch.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceJob.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceTask.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java
  gensrc/thrift/MVMaintenance.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
Labels: sig/materialized view, be-build
