Repository StarRocks/starrocks, pull requests merged in 2022-11, with the labels that each got.

#12622 [Enhancement] Add a configuration item to control data checksum for block cache
  be/src/block_cache/cache_options.h
  be/src/block_cache/fb_cachelib.cpp
  be/src/common/config.h
  be/src/service/starrocks_main.cpp
Labels: Approved

#12737 [Cherry-pick][Enhancement] Add sample size to session var when getting hive partition statistics
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: automerge

#12340 [Feature][Support Struct] Implement StructType infra in BE.
  be/src/column/CMakeLists.txt
  be/src/column/array_column.h
  be/src/column/column.h
  be/src/column/column_helper.cpp
  be/src/column/column_visitor.cpp
  be/src/column/column_visitor.h
  be/src/column/column_visitor_adapter.h
  be/src/column/column_visitor_mutable.cpp
  be/src/column/column_visitor_mutable.h
  be/src/column/datum.h
  be/src/column/fixed_length_column_base.h
  be/src/column/map_column.cpp
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/column/vectorized_fwd.h
  be/src/exec/vectorized/sorted_streaming_aggregator.cpp
  be/src/exec/vectorized/sorting/compare_column.cpp
  be/src/exec/vectorized/sorting/sort_column.cpp
  be/src/exec/vectorized/sorting/sort_permute.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/expr.cpp
  be/src/exprs/vectorized/subfield_expr.cpp
  be/src/exprs/vectorized/subfield_expr.h
  be/src/runtime/types.cpp
  be/src/runtime/types.h
  be/src/serde/column_array_serde.cpp
  be/src/serde/column_array_serde.h
  be/src/util/mysql_row_buffer.h
  be/test/CMakeLists.txt
  be/test/column/struct_column_test.cpp
  be/test/exprs/vectorized/subfield_expr_test.cpp
  be/test/runtime/type_descriptor_test.cpp
  gensrc/thrift/Exprs.thrift
  gensrc/thrift/Types.thrift
Labels: Approved

#12643 [BugFix] Column mapping may not take effect in Spark load
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
Labels: Approved

#12120 [Enhancement] Fix some implicit conversions
  be/src/storage/chunk_aggregator.h
  be/src/storage/chunk_helper.cpp
  be/src/storage/column_expr_predicate.cpp
  be/src/storage/column_operator_predicate.h
  be/src/storage/column_predicate_rewriter.cpp
  be/src/storage/compaction.cpp
  be/src/storage/conjunctive_predicates.cpp
  be/src/storage/conjunctive_predicates.h
  be/src/storage/convert_helper.cpp
  be/src/storage/disjunctive_predicates.cpp
  be/src/storage/disjunctive_predicates.h
  be/src/storage/push_handler.cpp
Labels: Approved

#12746 [Doc]fix incorrect spelling
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation, Approved

#12627 [BugFix] fix NPE if hostname can't be resolved
  fe/fe-core/src/main/java/com/starrocks/common/proc/FrontendsProcNode.java
  fe/fe-core/src/test/java/com/starrocks/proc/FrontendsProcNodeTest.java
Labels: Approved

#12716 [Feature] Support Materialized view for external table [3/3]
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: Approved, sig/materialized view

#12762 [BugFix] fix topn offset issue (backport #12635)
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/vectorized/chunks_sorter_heap_sort.cpp
Labels: automerge

#12761 [BugFix] fix topn offset issue (backport #12635)
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/vectorized/chunks_sorter_heap_sort.cpp
Labels: automerge

#12708 [BugFix] fix topn offset issue (backport #12635)
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/vectorized/chunk_sorter_heapsorter.cpp
Labels: automerge

#12713 [Cherry-pick] [BugFix] [branch-2.4] HeartbeatResponse add prop aliveStatus(#12481)
  fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatResponse.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BackendTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/FsBrokerTest.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
Labels: automerge

#12655 [Enhancement]Task Framework supported execution progress
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/leader/TaskRunStateSynchronizer.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunPeriodStatusChange.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved, sig/materialized view

#12608 [Feature]Support refresh mv by partition
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionRangeDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RefreshMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: Approved, sig/materialized view

#12566 [Enhancement] add variable `enable_populate_block_cache`
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/vectorized/hdfs_scanner.cpp
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: Approved

#12534 [cherry-pick branch-2.3] Analyze and PlanBuilder should be in the same read lock (#10672)
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: automerge

#12506 [cherry-pick branch-2.2] Analyze and PlanBuilder should be in the same read lock (#10672)
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: automerge

#12778 [BugFix] Materialized view type inference error import failed
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
Labels: Approved, sig/materialized view

#12764 [BugFix] Fix snapshot manager get tablet max version crash
  be/src/storage/snapshot_manager.cpp
Labels: Approved

#12712 [Enhancement] Support materialized view TTL
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/clone/DynamicPartitionSchedulerTest.java
Labels: sig/materialized view

#12799 [Feature] Add api to execute task by sync
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewStatementTest.java
Labels: sig/materialized view

#12752 [BugFix] Fix materialized view refresh error when base table partition value has MAXVALUE
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
Labels: sig/materialized view

#12480 [BugFix] remain agg having filter when remove aggOperator
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RemoveAggregationFromAggTable.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/RemoveAggTest.java
Labels: Approved

#12146 [Tool] add sonar cloud cpp check
  .github/workflows/sonar4be.yml
Labels: be-build

#12759 [Cherry-pick] [BugFix] [branch-2.2] HeartbeatResponse add prop aliveStatus(#12481)
  fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatResponse.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BackendTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/FsBrokerTest.java
Labels: automerge, be-build

#12824 [Tool] update be analyze sonar information
  .github/workflows/sonar4be.yml
Labels: be-build

#12819 [Tool] build with clang13
  be/CMakeLists.txt
  thirdparty/build-thirdparty.sh
Labels: be-build

#12823 [BugFix] intersect_count must use add_aggregate_mapping_variadic to register for nullable arguments
  be/src/exprs/agg/factory/aggregate_resolver_approx.cpp
Labels: be-build

#12649 [BugFix] Fix some broker request using fixed timeout
  be/src/exec/broker_writer.cpp
  be/src/runtime/snapshot_loader.cpp
Labels: Approved

#12840 [Tool] update sonarcloud information
  .github/workflows/sonar4be.yml
Labels: be-build

#12845 [Tool] remove scm provider
  .github/workflows/sonar4be.yml
Labels: be-build

#12839 [Cherry-pick][Branch-2.4][BugFix] Make sync configurable when writing a new tablet (#12624)
  be/src/storage/data_dir.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/tablet_manager.cpp
Labels: be-build

#12848 [Cherry-pick][Branch-2.4][BugFix] Fix materialized view refresh error when base table partition value has MAXVALUE (#12752)
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
Labels: be-build

#12533 [BugFix] Fix collectAllDatabase miss lock query statement db in insert statement
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeUtilTest.java
Labels: Approved

#12792 [Doc]Update dynamic_partitioning.md
  docs/table_design/dynamic_partitioning.md
Labels: documentation

#12808 [Enhancement] refactor hive auto sync
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/CachingRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CacheUpdateProcessor.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadataFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/IHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/AlterPartitionEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/AlterTableEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/DropPartitionEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/DropTableEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/InsertEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/MetastoreEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/MetastoreEventFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/MetastoreEventsProcessor.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
Labels: be-build

#12831 [Feature] Support optimizer time cost trace
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/PlannerProfile.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/StatementBase.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
Labels: be-build

#12864 Cherry-Pick-2.3][Enhancement] Add more safe lock function to Database
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: be-build

#12865 [Doc] Update Data_model.md
  docs/table_design/Data_model.md
Labels: documentation, be-build

#12860 [Cherry-Pick-2.2][Enhancement] Add more safe lock function to Database
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: be-build

#12873 [Enhancement] Add some necessary logs for external table
  fe/fe-core/src/main/java/com/starrocks/connector/CachingRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/AlterPartitionEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/DropPartitionEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/EventFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/InsertEvent.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/MetastoreEventFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/events/MetastoreTableEvent.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
Labels: be-build

#12882 [Refactor] Remove extra semicolon in DeferOp
  be/src/util/defer_op.h
Labels: be-build

#12889 [Refactor] remove boost regex dependency
  be/CMakeLists.txt
  be/src/storage/delete_handler.cpp
  be/src/storage/utils.cpp
  be/src/util/CMakeLists.txt
  be/src/util/symbols_util.cpp
  be/src/util/symbols_util.h
Labels: be-build

#12890 [Refactor] Remove boost filesystem system dependencies
  be/CMakeLists.txt
  be/src/util/runtime_profile.cpp
Labels: be-build

#12744 [Doc] Build StarRocks on Ubuntu
  build.sh
  docs/TOC.md
  docs/developers/build-starrocks/build_starrocks_on_ubuntu.md
Labels: documentation, be-build

#12833 [BugFix] Fix show create materialized view don't have catalog and db name
  fe/fe-core/src/main/java/com/starrocks/analysis/TableName.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewDefBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConnectorPlanTestBase.java
Labels: be-build

#12893 [BugFix] fix money_format when the result only has fractional part (backport #6664)
  be/src/exprs/vectorized/string_functions.h
  be/test/exprs/vectorized/string_fn_money_format_decimal_test.cpp
Labels: be-build

#12891 [BugFix] Use the Unix Make to build brpc/streamvbyte
  be/src/exprs/vectorized/arithmetic_expr.cpp
  thirdparty/build-thirdparty.sh
Labels: be-build

#12876 [Cherry-pick Branch-2.4] [BugFix] Fix collectAllDatabase miss lock query statement db in insert statement (#12533)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeUtilTest.java
Labels: be-build

#12648 [Doc] Added new documentation-Contributing to StarRocks
  docs/developers/How to Contribute.md
Labels: documentation, be-build

#12869 [Doc]Update SHOW LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW LOAD.md
Labels: documentation, be-build

#12855 [Enhancement] make exception message clear while creating external table that does not exist
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/server/TableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
Labels: be-build

#12484 [Feature] Unnest supports multiple parameters of different types
  be/src/exec/pipeline/table_function_operator.cpp
  be/src/exec/vectorized/table_function_node.cpp
  be/src/exprs/table_function/multi_unnest.h
  be/src/exprs/table_function/table_function_factory.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunction.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableFunctionRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeLateralTest.java
Labels: be-build

#12797 [BugFix] Fix primary key table vertical compaction bug
  be/src/storage/rowset_merger.cpp
Labels: be-build

#12899 [Cherry-pick-2.2][BugFix] Fix drop partition log is written behind drop table log bug
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
Labels: be-build

#12750 [Feature] New RBAC privilege framework: basic upgrader
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationManager.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UserProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DomainResolver.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/RoleManager.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/WhiteList.java
  fe/fe-core/src/main/java/com/starrocks/persist/AuthUpgradeInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/RolePrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowGrantsStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationProviderFactoryTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ExecuteAsStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokeRoleStmtTest.java
Labels: be-build

#12382 [Enhancement] Throw error msg when csv parse failed in Hive.
  be/src/column/binary_column.h
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  be/src/formats/csv/binary_converter.cpp
Labels: be-build

#12844 [Enhancement] Add dbId to getRelatedMaterializedViews
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/UseMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
Labels: be-build

#12917 [Doc] toc for contribute and data unloading
  docs/TOC.md
  docs/assets/how to contribute.png
  docs/developers/How to Contribute.md
  docs/sql-reference/sql-functions/crytographic-functions/md5sum.md
Labels: documentation, be-build

#12920 [Doc] adjust toc to Branch 2.3
  docs/TOC.md
  docs/assets/how to contribute.png
  docs/sql-reference/sql-functions/crytographic-functions/md5sum.md
Labels: documentation, be-build

#12918 [Doc] toc adjust to Branch 2.4
  docs/TOC.md
  docs/assets/how to contribute.png
  docs/sql-reference/sql-functions/crytographic-functions/md5sum.md
Labels: documentation, be-build

#12907 [BugFix] Fix the delete predicate bug on new added column
  be/src/storage/rowset/default_value_column_iterator.cpp
  be/src/storage/rowset/default_value_column_iterator.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/default_value_column_iterator_test.cpp
Labels: be-build

#12879 [Enhancement] Make optimizer customizable
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerConfig.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSetType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/OptimizerTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTest.java
Labels: be-build

#12908 [Enhancement] port olap chunk buffer dynamic limiter mechanism
  be/src/common/config.h
  be/src/exec/pipeline/scan/balanced_chunk_buffer.cpp
  be/src/exec/pipeline/scan/balanced_chunk_buffer.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.h
  be/src/exec/vectorized/connector_scan_node.cpp
  be/test/exec/pipeline/pipeline_control_flow_test.cpp
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
  be/test/exec/pipeline/table_function_operator_test.cpp
  be/test/exec/query_cache/transform_operator.cpp
Labels: be-build

#12910 [Enhancement][Cherry-Pick] Throw error msg when CSV parse failed in Hive
  be/src/column/binary_column.h
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  be/src/formats/csv/binary_converter.cpp
Labels: be-build

#12909 [Enhancement][Cherry-Pick] Throw error msg when CSV parse failed in Hive
  be/src/column/binary_column.h
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  be/src/formats/csv/binary_converter.cpp
Labels: be-build

#12895 [cherry-pick][branch-2.3][BugFix] Fix BE crash when RuntimeFilter close without prepared
  be/src/exprs/expr_context.cpp
  be/test/exprs/vectorized/function_call_expr_test.cpp
Labels: be-build

#12912 [Enhancement][Cherry-Pick] Throw error msg when CSV parse failed in Hive
  be/src/column/binary_column.h
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  be/src/formats/csv/binary_converter.cpp
Labels: be-build

#12867 [Enhancement] change return type of md5sum_numeric to LARGEINT
  be/src/exprs/vectorized/encryption_functions.cpp
  be/test/exprs/vectorized/encryption_functions_test.cpp
  gensrc/script/vectorized/vectorized_functions.py
Labels: be-build

#12932 [Doc] Fix MV support
  docs/using_starrocks/Materialized_view.md
Labels: documentation, be-build

#12923 [cherry-pick] [branch-2.3] [BugFix] Fix the delete predicate bug on new added column (#12907)
  be/src/storage/rowset/default_value_column_iterator.cpp
  be/src/storage/rowset/default_value_column_iterator.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/default_value_column_iterator_test.cpp
Labels: be-build

#12927 [Enhancement] change return type of md5sum_numeric to LARGEINT (backport #12867)
  be/src/exprs/vectorized/encryption_functions.cpp
  be/test/exprs/vectorized/encryption_functions_test.cpp
  gensrc/script/vectorized/vectorized_functions.py
Labels: be-build

#12897 [cherry-pick][branch-2.4][BugFix] Fix BE crash when RuntimeFilter close without prepared
  be/src/exprs/expr_context.cpp
  be/test/exprs/vectorized/function_call_expr_test.cpp
Labels: be-build

#12935 [cherry-pick][branch-2.2][BugFix] Fix the delete predicate bug on new added column (#12907)
  be/src/storage/rowset/default_value_column_iterator.cpp
  be/src/storage/rowset/default_value_column_iterator.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/default_value_column_iterator_test.cpp
Labels: be-build

#12854 [cherry-pick][branch-2.4][BugFix] ignore flush pool in txn_manager for CN
  be/src/storage/txn_manager.cpp
Labels: be-build

#12914 [cherry-pick][BugFix][Branch-2.4] Fix primary key table vertical compaction bug (#12797)
  be/src/storage/rowset_merger.cpp
Labels: be-build

#12903 [Doc] Make the IDEA configuration more friendly
  docs/developers/development-environment/IDEA.md
Labels: documentation, be-build

#12924 Update PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: title needs [type], be-build

#12948 [BugFix] Increase default broker_client_timeout.
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: be-build

#12934 [cherry-pick][branch-2.4][BugFix] Fix the delete predicate bug on new added column (#12907)
  be/src/storage/rowset/default_value_column_iterator.cpp
  be/src/storage/rowset/default_value_column_iterator.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/default_value_column_iterator_test.cpp
Labels: be-build

#12928 [Feature] Manage the mapping of name to id by AuthorizationProvider instead of PrivilegeManager
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ActionSet.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeType.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeTypes.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: be-build

#12667 [Enhancement] Add hashJoin execution cost model
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostEstimate.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalDistributionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/three-join.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q10.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q18.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q21.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q5.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q7.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q9.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q16.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q2.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q18.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q5.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q8.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q18.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q8.sql
Labels: be-build

#12936 [cherry-pick][branch-2.1][BugFix] Fix the delete predicate bug on new added column (#12907)
  be/src/exec/vectorized/topn_node.cpp
  be/src/storage/rowset/default_value_column_iterator.cpp
  be/src/storage/rowset/default_value_column_iterator.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/default_value_column_iterator_test.cpp
Labels: be-build

#12953 [Enhancement] update comment format
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
Labels: be-build

#12916 [Enhancement] Add api to get outdated partitions for mv
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: be-build

#12789 [BugFix] Set 'could_local_shuffle' correctly when decompose pipeline
  be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_source_operator.h
  be/src/exec/pipeline/aggregate/sorted_aggregate_streaming_source_operator.h
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.h
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/pipeline/source_operator.h
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/runtime/memory/chunk_allocator.h
  be/src/util/debug/query_trace_impl.h
Labels: be-build

#12938 [Enhancement] Catch unexpected exception when processing column type convert
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
Labels: be-build

#12962 [Doc]add one missing parameter for elasticsearch external table.md
  docs/data_source/External_table.md
Labels: documentation, be-build

#12921 [BugFix] fixbug when keyType in map is char or varchar for parquet
  be/src/formats/parquet/schema.cpp
  be/test/exec/test_data/parquet_scanner/file_reader_test_map_char_key.parquet
  be/test/formats/parquet/file_reader_test.cpp
Labels: be-build

#12887 [Enhancement] Map partition value to partition range using MAX_VALUE instead of Infinity value
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
Labels: be-build

#12954 [Enhancement] Cancel queries when BE is crashed (#11305)
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorMonitor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorMonitorTest.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
Labels: be-build

#12859 [Enhancement] Refactor VariableExpr to support more variable types
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/VariableExpr.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/VariableExprTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/SetExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: be-build

#12955 [Enhancement] Cancel queries when BE is crashed (#11305)
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorMonitor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatResponse.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BackendTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorMonitorTest.java
Labels: be-build

#12958 [Enhancement] Cancel queries when BE is crashed (#11305)
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorMonitor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatResponse.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BackendTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorMonitorTest.java
Labels: be-build

#12976 [Tool] removing deprecated set output
  .github/workflows/add-approve-label.yml
Labels: be-build

#12550 [Enhancement] Support replicated_storage as tablet property & disable insert shuffle when enable replicated_storage
  be/src/agent/agent_task.cpp
  be/src/exec/tablet_sink.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/InternalService.thrift
Labels: Approved, be-build

#12406 [Enhancement][Lake] Add some metrics and logs for compaction jobs
  be/src/fs/fs_starlet.cpp
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/storage/lake/compaction_task.h
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/horizontal_compaction_task.h
  be/test/storage/lake/horizontal_compaction_task_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionManager.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  gensrc/proto/lake_service.proto
Labels: be-build

#12975 [Doc]Update iceberg_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation, be-build

#12965 [BugFix] Fix invalid URL
  fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicasProcNode.java
Labels: be-build

#12883 [Feature][Support Struct] Support read struct type in parquet format
  be/src/formats/parquet/column_chunk_reader.h
  be/src/formats/parquet/column_converter.h
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/test/exec/test_data/parquet_scanner/file_reader_test_struct_null.parquet
  be/test/formats/parquet/file_reader_test.cpp
Labels: be-build

#12806 [Feature] Multiple eos countdown in query cache
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/query_cache/ticket_checker.cpp
  be/src/exec/query_cache/ticket_checker.h
  be/test/exec/query_cache/query_cache_test.cpp
Labels: be-build

#12986 [Enhancement] Set Hive string type to a larger length and set null for parse fails column
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/ColumnTypeConverterTest.java
Labels: be-build

#12988 [BugFix] fix get_json_int throw exceptions
  be/src/exprs/vectorized/json_functions.cpp
  be/test/exprs/vectorized/json_functions_test.cpp
Labels: be-build

#12989 Update External_table.md
  docs/data_source/External_table.md
Labels: documentation, be-build

#12964 [Enhancement] add privilege collection cache
  fe/fe-core/src/main/java/com/starrocks/common/Pair.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/RolePrivilegeCollection.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/RolePrivilegeCollectionTest.java
Labels: be-build

#12993 [BugFix] purge zero-charge cache entry
  be/src/exec/query_cache/cache_manager.h
  be/test/exec/query_cache/query_cache_test.cpp
Labels: be-build

#12385 [Enhancement] generate min/max predicate from runtime filter & support `evaluate_with_filter`
  be/src/common/config.h
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/exec/exec_node.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/expr_context.cpp
  be/src/exprs/expr_context.h
  be/src/exprs/vectorized/in_const_predicate.hpp
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/test/formats/parquet/file_reader_test.cpp
  build.sh
  gensrc/thrift/Exprs.thrift
Labels: be-build

#12941 [Feature] Preprocess mv for rewrite
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTest.java
Labels: be-build

#12999 [Doc] The fields of the two tables are messed up
  docs/loading/BrokerLoad.md
Labels: documentation, be-build

#13006 [BugFix] Fix materialized view rewrite bug of agg with count(1) (#12707)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRuleTest.java
Labels: be-build

#13004 [BugFix] Fix materialized view rewrite bug of agg with count(1) 2.2
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRuleTest.java
Labels: be-build

#12996 [BugFix] fix get_json_int throw exceptions (backport #12988)
  be/src/exprs/vectorized/json_functions.cpp
  be/test/exprs/vectorized/json_functions_test.cpp
Labels: be-build

#12997 [BugFix] fix get_json_int function exception (backport #12988)
  be/src/exprs/vectorized/json_functions.cpp
  be/test/exprs/vectorized/json_functions_test.cpp
Labels: be-build

#12900 [BugFix] simple limit sql may failed when scanrows is lower than bigquery_scan_rows_limit
  be/src/exec/pipeline/fragment_executor.cpp
Labels: be-build

#13022 [Doc] Add SQL references for Resource Group
  docs/TOC.md
  docs/administration/resource_group.md
  docs/sql-reference/sql-statements/Administration/ALTER RESOURCE GROUP.md
  docs/sql-reference/sql-statements/Administration/CREATE RESOURCE GROUP.md
  docs/sql-reference/sql-statements/Administration/DROP RESOURCE GROUP.md
  docs/sql-reference/sql-statements/Administration/SHOW RESOURCE GROUP.md
Labels: documentation, be-build

#13013 [branch-2.3][Enhancement][Cherry-Pick] Set Hive string type to a larger length and set null for parse fails column
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
  fe/fe-core/src/test/java/com/starrocks/external/hive/UtilsTest.java
Labels: be-build

#13008 [branch-2.4][Enhancement][Cherry-Pick] Set Hive string type to a larger length and set null for parse fails column
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
  fe/fe-core/src/test/java/com/starrocks/external/hive/UtilsTest.java
Labels: be-build

#12852 [BugFix] fix some problems when be exits gracefully
  be/CMakeLists.txt
  be/src/agent/agent_server.cpp
  be/src/agent/agent_server.h
  be/src/service/mem_hook.cpp
  be/src/service/starrocks_main.cpp
  be/src/storage/storage_engine.cpp
  bin/start_be.sh
  build.sh
  conf/asan_suppressions.conf
  conf/log4j.properties
Labels: be-build

#12961 [BugFix] Notify CoordinatorMonitor for metadata aliveStatus
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorMonitorTest.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
Labels: be-build

#12376 [Feature] Support append columns in equality delete file
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: be-build

#13011 [Refactor] reduce be test log output
  be/test/exprs/vectorized/decimal_cast_expr_test_helper.h
Labels: be-build

#12940 [BugFix] Add nest subquery check
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: be-build

#13018 [Enhancement] optimize in_const_predicate
  be/src/column/column_builder.h
  be/src/exprs/vectorized/in_const_predicate.hpp
Labels: be-build

#12950 [Feature] support resource statements in new RBAC privilege framework
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeType.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourcePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: be-build

#13016 [BugFix] Fix NPE for array_map when lambda function is null
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
Labels: be-build

#12985 [BugFix] Fix create error when create mv on mv
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: be-build

#13031 [BugFix] fix some problems when be exits gracefully (backport #12852)
  be/CMakeLists.txt
  be/src/agent/agent_server.cpp
  be/src/agent/agent_server.h
  be/src/service/mem_hook.cpp
  be/src/service/starrocks_main.cpp
  be/src/storage/storage_engine.cpp
  bin/start_be.sh
  build.sh
  conf/asan_suppressions.conf
  conf/log4j.properties
Labels: be-build

#13040 [BugFix] fix hive/hudi unpartitioned table statistics row count
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveStatisticsProvider.java
Labels: be-build

#13041 [Doc] Fix Backup Doc
  docs/administration/Backup_and_restore.md
Labels: documentation, be-build

#13014 [branch-2.2][Enhancement][Cherry-Pick] Set Hive string type to a larger length and set null for parse fails column
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
  fe/fe-core/src/test/java/com/starrocks/external/hive/UtilsTest.java
Labels: be-build

#12970 [Enhancement] Support alter materialized view properties
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: sig/materialized view, be-build

#13019 [Feature] implement left semi/anti join for NLJ
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.h
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/simd/simd.h
  fe/fe-core/src/main/java/com/starrocks/planner/NestLoopJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/NestLoopJoinImplementationRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinCommutativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinCommutativityWithOutInnerRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/UnsupportedNLJTest.java
Labels: be-build

#13034 [BugFix] simple limit sql may failed when scanrows is lower than bigquery_scan_rows_limit (#12900)
  be/src/exec/pipeline/fragment_executor.cpp
Labels: be-build

#12638 [Enhancement] optimize aggregate push down factor
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/IntersectAddDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownAggregateCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsEstimateCoefficient.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPushAggTest.java
Labels: type/enhancement, be-build

#13033 [Enhancement] remove not-required manual cache.prune
  be/src/exec/query_cache/cache_manager.cpp
Labels: be-build

#13072 [BugFix] fix apply filter in evaluate conjuncts
  be/src/exec/exec_node.cpp
Labels: be-build

#13052 [BugFix] fix arrayMap without lambda functions error
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
Labels: be-build

#13068 [Doc] update image in contribute
  docs/assets/contribute.png
  docs/developers/How to Contribute.md
  docs/sql-reference/sql-functions/crytographic-functions/md5sum_numeric.md
Labels: documentation, be-build

#13076 [Doc] update md5sum_ numeric to Branch 2.4
  docs/sql-reference/sql-functions/crytographic-functions/md5sum_numeric.md
Labels: documentation, be-build

#12926 [Enhancement] Materialized views support refresh granularity splits
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: sig/materialized view, be-build

#13067 [Cherry-pick][Branch-2.3][BugFix] Fix sync issue (backport #12343) (#12543)
  be/src/fs/fs_posix.cpp
  be/src/fs/fs_util.h
  be/src/storage/data_dir.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/tablet_manager.cpp
Labels: be-build

#13083 [Cherry-pick][Branch-2.3] BugFix] Make sync configurable when writing a new tablet (#12624)
  be/src/storage/data_dir.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/tablet_manager.cpp
Labels: be-build

#13065 [Feature] Support PK for CTAS only used in dbt
  fe/fe-core/src/main/java/com/starrocks/analysis/ColumnDef.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: be-build

#13073 [Feature] Create hourly partitions dynamically
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiRangePartitionDesc.java
Labels: be-build

#13037 [BugFix] Fix wrong logical properties in TopN
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: be-build

#13085 [Doc] Fix community issues
  docs/administration/k8s_operator_cn.md
  docs/introduction/Architecture.md
  docs/sql-reference/sql-functions/How to Write Functions Documentation.md
  docs/sql-reference/sql-functions/aggregate-functions/any_value.md
  docs/sql-reference/sql-functions/aggregate-functions/avg.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_cont.md
  docs/sql-reference/sql-functions/aggregate-functions/retention.md
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  docs/sql-reference/sql-functions/array-functions/array_concat.md
  docs/sql-reference/sql-functions/array-functions/array_contains_all.md
  docs/sql-reference/sql-functions/array-functions/array_distinct.md
  docs/sql-reference/sql-functions/array-functions/array_intersect.md
  docs/sql-reference/sql-functions/array-functions/array_join.md
  docs/sql-reference/sql-functions/array-functions/array_position.md
  docs/sql-reference/sql-functions/array-functions/array_remove.md
  docs/sql-reference/sql-functions/array-functions/array_slice.md
  docs/sql-reference/sql-functions/array-functions/array_sort.md
  docs/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/sql-reference/sql-functions/array-functions/arrays_overlap.md
  docs/sql-reference/sql-functions/array-functions/reverse.md
  docs/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_contains.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_has_any.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_hash.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_intersect.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_max.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_min.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_union_count.md
  docs/sql-reference/sql-functions/date-time-functions/convert_tz.md
  docs/sql-reference/sql-functions/date-time-functions/curtime.md
  docs/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/sql-reference/sql-functions/date-time-functions/day.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/timestampdiff.md
  docs/sql-reference/sql-functions/date-time-functions/week.md
  docs/sql-reference/sql-functions/hash-functions/murmur_hash3_32.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_array.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_object.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/arrow-function.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/cast.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_each.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_exists.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_keys.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_length.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_query.md
  docs/sql-reference/sql-functions/math-functions/square.md
  docs/sql-reference/sql-functions/spatial-functions/st_contains.md
  docs/sql-reference/sql-functions/string-functions/concat.md
  docs/sql-reference/sql-functions/string-functions/concat_ws.md
  docs/sql-reference/sql-functions/string-functions/group_concat.md
  docs/sql-reference/sql-functions/string-functions/locate.md
  docs/sql-reference/sql-functions/string-functions/money_format.md
  docs/sql-reference/sql-functions/utility-functions/uuid_numeric.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation, be-build

#13088 [Doc] cherrypick formatting functions to Branch 2.3
  docs/introduction/Architecture.md
  docs/sql-reference/sql-functions/How to Write Functions Documentation.md
  docs/sql-reference/sql-functions/aggregate-functions/any_value.md
  docs/sql-reference/sql-functions/aggregate-functions/avg.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/sql-reference/sql-functions/aggregate-functions/retention.md
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  docs/sql-reference/sql-functions/array-functions/array_concat.md
  docs/sql-reference/sql-functions/array-functions/array_distinct.md
  docs/sql-reference/sql-functions/array-functions/array_intersect.md
  docs/sql-reference/sql-functions/array-functions/array_join.md
  docs/sql-reference/sql-functions/array-functions/array_position.md
  docs/sql-reference/sql-functions/array-functions/array_remove.md
  docs/sql-reference/sql-functions/array-functions/array_slice.md
  docs/sql-reference/sql-functions/array-functions/array_sort.md
  docs/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/sql-reference/sql-functions/array-functions/arrays_overlap.md
  docs/sql-reference/sql-functions/array-functions/reverse.md
  docs/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_contains.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_has_any.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_hash.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_intersect.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_max.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_min.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_union_count.md
  docs/sql-reference/sql-functions/date-time-functions/convert_tz.md
  docs/sql-reference/sql-functions/date-time-functions/curtime.md
  docs/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/sql-reference/sql-functions/date-time-functions/day.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/timestampdiff.md
  docs/sql-reference/sql-functions/date-time-functions/week.md
  docs/sql-reference/sql-functions/hash-functions/murmur_hash3_32.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_array.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_object.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/arrow-function.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/cast.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_each.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_exists.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_query.md
  docs/sql-reference/sql-functions/math-functions/square.md
  docs/sql-reference/sql-functions/spatial-functions/st_contains.md
  docs/sql-reference/sql-functions/string-functions/concat.md
  docs/sql-reference/sql-functions/string-functions/concat_ws.md
  docs/sql-reference/sql-functions/string-functions/group_concat.md
  docs/sql-reference/sql-functions/string-functions/locate.md
  docs/sql-reference/sql-functions/string-functions/money_format.md
  docs/sql-reference/sql-functions/utility-functions/uuid_numeric.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation, be-build

#13087 [Doc] cherrypick formatting functions to Branch 2.4
  docs/administration/k8s_operator_cn.md
  docs/introduction/Architecture.md
  docs/sql-reference/sql-functions/How to Write Functions Documentation.md
  docs/sql-reference/sql-functions/aggregate-functions/any_value.md
  docs/sql-reference/sql-functions/aggregate-functions/avg.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_cont.md
  docs/sql-reference/sql-functions/aggregate-functions/retention.md
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  docs/sql-reference/sql-functions/array-functions/array_concat.md
  docs/sql-reference/sql-functions/array-functions/array_contains_all.md
  docs/sql-reference/sql-functions/array-functions/array_distinct.md
  docs/sql-reference/sql-functions/array-functions/array_intersect.md
  docs/sql-reference/sql-functions/array-functions/array_join.md
  docs/sql-reference/sql-functions/array-functions/array_position.md
  docs/sql-reference/sql-functions/array-functions/array_remove.md
  docs/sql-reference/sql-functions/array-functions/array_slice.md
  docs/sql-reference/sql-functions/array-functions/array_sort.md
  docs/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/sql-reference/sql-functions/array-functions/arrays_overlap.md
  docs/sql-reference/sql-functions/array-functions/reverse.md
  docs/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_contains.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_has_any.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_hash.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_intersect.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_max.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_min.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_union_count.md
  docs/sql-reference/sql-functions/date-time-functions/convert_tz.md
  docs/sql-reference/sql-functions/date-time-functions/curtime.md
  docs/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/sql-reference/sql-functions/date-time-functions/day.md
  docs/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/sql-reference/sql-functions/date-time-functions/timestampdiff.md
  docs/sql-reference/sql-functions/date-time-functions/week.md
  docs/sql-reference/sql-functions/hash-functions/murmur_hash3_32.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_array.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/json_object.md
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/arrow-function.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/cast.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_each.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_exists.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_keys.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_length.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_query.md
  docs/sql-reference/sql-functions/math-functions/square.md
  docs/sql-reference/sql-functions/spatial-functions/st_contains.md
  docs/sql-reference/sql-functions/string-functions/concat.md
  docs/sql-reference/sql-functions/string-functions/concat_ws.md
  docs/sql-reference/sql-functions/string-functions/group_concat.md
  docs/sql-reference/sql-functions/string-functions/locate.md
  docs/sql-reference/sql-functions/string-functions/money_format.md
  docs/sql-reference/sql-functions/utility-functions/uuid_numeric.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation, be-build

#12979 [BugFix] fix blocking the in-cancelling exchangeSink resulted from OOM
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/sender_queue.cpp
  be/src/service/internal_service.cpp
Labels: be-build

#13061 [BugFix] Validate kafka offset either by custom offset or kafka meta before alter
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
Labels: be-build
