Repository StarRocks/starrocks, pull requests merged in 2022-09, with the labels that each got.

#10674 [BugFix]Fix compile bug
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: Approved

#10652 [BugFix] Add WARNING log when stats collect fail
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved

#10668 [Refactor][Minor] Reduce level of nesting
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#10239 [Enhancement]enable fe to list all file in hdfs recursively
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
Labels: Approved

#10683 [Doc] Fix improper string
  docs/faq/loading/Flink_connector_faq.md
Labels: documentation

#10693 update loading_intro
  docs/assets/4.1-1.png
  docs/assets/4.1-2.png
  docs/assets/4.1.1.png
  docs/loading/Loading_intro.md
Labels: documentation, Approved

#10626 [Bugfix] Fix bug drop/recover db maintain task
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: Approved

#10705 [Cherry-pick] Fix bug drop/recover db maintain task
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: automerge

#10697 [Bugfix] Fix unknown error when rpc query
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved

#10703 update StreamLoad
  docs/assets/4.2-1.png
  docs/assets/4.2-2en.png
  docs/loading/StreamLoad.md
Labels: documentation, Approved

#10533 [Enhancement][Lake]Run abortTxn in a separate thread pool
  be/src/service/service_be/lake_service.cpp
Labels: Approved

#10699 [Bugfix] Fix compile error unused return value
  be/src/common/logconfig.cpp
Labels: Approved

#10644 [bugfix] show storage info when execute 'show create table' of laket table
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved

#10680 [Enhancement] detect JAVA_HOME before call JVM functions
  be/src/exec/vectorized/jdbc_scanner.cpp
  be/src/exprs/agg/java_udaf_function.cpp
  be/src/exprs/agg/java_window_function.cpp
  be/src/exprs/table_function/java_udtf_function.cpp
  be/src/exprs/vectorized/java_function_call_expr.cpp
  be/src/udf/java/java_udf.cpp
  be/src/udf/java/java_udf.h
Labels: Approved

#10711 [Enhance] limit maximum length of JSON string to 16MB (backport #10628)
  be/src/util/json.cpp
  be/src/util/json.h
  be/test/column/json_column_test.cpp
Labels: automerge

#10714 update BrokerLoad
  docs/assets/4.3-1.png
  docs/loading/BrokerLoad.md
Labels: documentation, Approved

#10672 [BugFix] Analyze and PlanBuilder should be in the same read lock
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
Labels: Approved

#10713 [Refactor] Add more log to trace the FSBroker bug
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/HDFSBrokerServiceImpl.java
Labels: Approved

#10679 [BugFix] fix null partition key value pruned by mistake
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/PartitionColPredicateEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/PartitionColPredicateExtractor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/FurtherPartitionPruneTest.java
Labels: Approved

#10710 [Enhance] limit maximum length of JSON string to 16MB (backport #10628)
  be/src/util/json.cpp
  be/src/util/json.h
  be/test/column/json_column_test.cpp
Labels: automerge

#10334 [Lake] Support backup with broker
  be/src/runtime/CMakeLists.txt
  be/src/runtime/lake_snapshot_loader.cpp
  be/src/runtime/lake_snapshot_loader.h
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  fe/fe-core/src/main/java/com/starrocks/analysis/TableName.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableRef.java
  fe/fe-core/src/main/java/com/starrocks/backup/AbstractJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupMeta.java
  fe/fe-core/src/main/java/com/starrocks/backup/SnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeBackupJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  gensrc/proto/lake_service.proto
Labels: Approved

#10112 [BugFix]Fix hive column convert array containing unknown type
  fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/HiveTableTest.java
Labels: Approved

#10678 [BugFix] Ranges may be lost when dynamic partitions are created.
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
Labels: Approved

#10712 [Bugfix] Fix refreshScheme might be NULL
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved

#10719 [Enhancement] Replace std::mutex with bthread::Mutex
  be/src/service/service_be/lake_service.cpp
Labels: Approved

#10695 [Bugfix] Fix ES sync bug.
  fe/fe-core/src/main/java/com/starrocks/external/elasticsearch/EsRepository.java
Labels: Approved

#10744 delete <br/> in BrokerLoad
  docs/loading/BrokerLoad.md
Labels: documentation

#10361 [Bugfix] Use re2 when hyperscan report errors
  be/src/exprs/vectorized/like_predicate.cpp
  be/src/exprs/vectorized/like_predicate.h
  be/test/exprs/vectorized/like_test.cpp
Labels: Approved

#10749 update Etl_in_loading&Load_to_Primary_Key_tabes&Sort_key
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/table_design/Sort_key.md
Labels: documentation, Approved

#10748 [Refactor] remove some unused code of ChunkSorter
  be/src/exec/vectorized/chunks_sorter.cpp
  be/src/exec/vectorized/sorting/compare_column.cpp
Labels: Approved

#10759 add </li> in BrokerLoad
  docs/loading/BrokerLoad.md
Labels: documentation, Approved

#10659 [docs] v2.4 function docs
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/sql-reference/sql-functions/aggregate-functions/count.md
  docs/sql-reference/sql-functions/aggregate-functions/percentile_cont.md
  docs/sql-reference/sql-functions/array-functions/array_contains_all.md
  docs/sql-reference/sql-statements/data-types/Array.md
  docs/sql-reference/sql-statements/data-types/HLL.md
  docs/using_starrocks/Window_function.md
Labels: documentation, Approved

#10763 [Doc] 2.4 OVERWRITE
  docs/loading/InsertInto.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
Labels: documentation, Approved

#10768 [Doc] 2.4 Materialized View
  docs/TOC.md
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/DROP MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/REFRESH MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved

#10753 [cherry-pick] [branch-2.4] [Enhancement] Modify the implementation of the parse root path property (#10450)
  be/src/storage/options.cpp
Labels: automerge

#10751 [cherry-pick] [branch-2.4] [Enhancement] Optimize the mem usage of task worker pool (#10431)
  be/src/agent/agent_common.h
  be/src/agent/publish_version.cpp
  be/src/agent/publish_version.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_clone_task.h
Labels: automerge

#10752 [cherry-pick] [branch-2.4] [Enhancement] limit the number of migration task sent to BE (#10124)
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: automerge

#10613 [Enhancement]Added setting to limit parse large statement
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SqlWithIdUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/OperationNotAllowedException.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/TokenNumberListener.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AdminSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserBench.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/TokenLimitTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#10783 [Doc] Fix format
  docs/sql-reference/sql-statements/data-definition/DROP MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/REFRESH MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW MATERIALIZED VIEW.md
Labels: documentation

#10784 [Doc] Fix Format
  docs/TOC.md
  docs/sql-reference/sql-statements/data-definition/DROP MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/REFRESH MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW MATERIALIZED VIEW.md
Labels: documentation

#10750 [refactor] Remove getIds method from expr
  fe/fe-core/src/main/java/com/starrocks/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/planner/AggregationNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ListPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
Labels: Approved

#10737 [BugFix] fix the bug of import array<json>
  be/src/exec/vectorized/json_scanner.cpp
  be/src/exec/vectorized/json_scanner.h
  be/test/exec/test_data/json_scanner/test9.json
  be/test/exec/vectorized/json_scanner_test.cpp
Labels: Approved

#10727 [Docs]parallel-scan-of-a tablet
  docs/table_design/Data_distribution.md
Labels: documentation, Approved

#10728 [Docs]flink-connector-supports-partial-updates
  docs/loading/Flink-connector-starrocks.md
  docs/loading/Flink_cdc_load.md
Labels: documentation, Approved

#10715 [enhancement] Can build statistics collection SQL across partitions and columns
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved

#10634 change inject error's directories
  be/src/common/config.h
Labels: Approved

#10596 [BugFix] persist grant/revoke role and support grant impersonate to role
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/ImpersonateUserPrivTable.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Role.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/RoleManager.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ImpersonatePrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/PrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ImpersonatePrivInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokeImpersonateStmtTest.java
Labels: Approved

#10792 [cherry-pick] [branch-2.4][BugFix] persist with default_cluster and remove it when read (#10022)
  fe/fe-core/src/main/java/com/starrocks/catalog/AuthorizationInfo.java
  fe/fe-core/src/main/java/com/starrocks/cluster/Cluster.java
Labels: automerge

#10657 [BugFix] Abort insert into txn if filter data in strict mode
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionCommitFailedException.java
Labels: Approved

#10762 [Bugfix] Fix bug check pendingTask in concurrency
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
Labels: Approved

#10606 [enhancement] clear useless txn log
  be/src/storage/lake/gc.cpp
  be/src/storage/lake/gc.h
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/gc_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  gensrc/thrift/HeartbeatService.thrift
Labels: Approved

#10745 [Refactor] use lambda function instead of Runnable class in lake_service.cpp
  be/src/service/service_be/lake_service.cpp
Labels: Approved

#10805 [Cherry-pick 2.3][BugFix] persist grant/revoke role and support grant impersonate to role (#10596)
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/ImpersonateUserPrivTable.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Role.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/RoleManager.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ImpersonatePrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/PrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/ImpersonateUserPrivTableTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ImpersonatePrivInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokeImpersonateStmtTest.java
Labels: automerge

#10802 [Cherry-pick 2.4][BugFix] persist grant/revoke role and support grant impersonate to role (#10596)
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/ImpersonateUserPrivTable.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Role.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/RoleManager.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ImpersonatePrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/PrivInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokeImpersonateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ImpersonatePrivInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokeImpersonateStmtTest.java
Labels: automerge

#10362 [Refactor] Add ExploreGroupTask in memo phase
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ExploreGroupTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/OptimizeExpressionTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/OptimizeGroupTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EnumeratePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSCTERatioTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q9.sql
  fe/fe-core/src/test/resources/sql/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q9.sql
Labels: Approved

#10809 [Bugfix] Fix bug check pendingTask in concurrency (backport #10762)
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
Labels: automerge

#10372 [Enhancement] Allow skip bad journal when replay
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: Approved

#10760 [Bugfix] Fix bug alter materialized view in concurrency
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
Labels: Approved

#10789 [BugFix] Fix bug of broadcast global runtime filter
  be/src/exec/exec_node.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_filter_worker.h
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/test/java/com/starrocks/qe/TPCDSCoordTest.java
Labels: Approved

#10782 [Refactor] Add verbose log for stream load request
  be/src/http/action/stream_load.cpp
Labels: Approved

#10772 [BugFix] SliceMutableIndex's snapshot size is calculated incorrectly
  be/src/storage/persistent_index.cpp
Labels: Approved

#10823 [Cherry-pick 2.4][Enhancement] Allow skip bad journal when replay (#10372)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: automerge

#10813 [Refactor] remove some unused code and add some comment
  be/src/exec/vectorized/json_scanner.cpp
  be/src/exec/vectorized/json_scanner.h
  be/src/formats/json/nullable_column.cpp
Labels: Approved

#10778 [Refactor] refactor the index page reader for easy mem statistics
  be/src/storage/rowset/index_page.cpp
  be/src/storage/rowset/index_page.h
  be/test/storage/rowset/index_page_test.cpp
Labels: Approved

#9806 [Feature] Support Lambda function of array_map()
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/column_helper.h
  be/src/exprs/CMakeLists.txt
  be/src/exprs/expr.cpp
  be/src/exprs/vectorized/array_functions.cpp
  be/src/exprs/vectorized/array_functions.h
  be/src/exprs/vectorized/array_map_expr.cpp
  be/src/exprs/vectorized/array_map_expr.h
  be/src/exprs/vectorized/lambda_function.cpp
  be/src/exprs/vectorized/lambda_function.h
  be/test/CMakeLists.txt
  be/test/column/array_column_test.cpp
  be/test/exprs/vectorized/lambda_function_expr_test.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/PlaceHolderExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableName.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeState.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResolvedField.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/LambdaArgument.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/LambdaFunctionExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/LambdaFunctionOperatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  gensrc/script/vectorized/vectorized_functions.py
  gensrc/thrift/Exprs.thrift
Labels: Approved

#10808 [BugFix] Fix Hive column statistics of decimal type not compute Min/Max value
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveColumnStats.java
Labels: Approved

#10676 [Bugfix][Support Struct]Fixed some expressions not supporting qualified name when creating views.
  fe/fe-core/src/main/java/com/starrocks/analysis/ArrowExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AST2SQL.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Field.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/ExpressionMapping.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
Labels: Approved

#10566 [Bugfix] Add detect for bitmap function
  be/src/common/config.h
  be/src/exprs/vectorized/bitmap_functions.cpp
  be/src/exprs/vectorized/bitmap_functions.h
  be/src/exprs/vectorized/encryption_functions.cpp
Labels: Approved

#10642 [BugFix]Fix colocate state inaccuracy bug
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#10832 [Refactor] Reset all the items if load index failed
  be/src/storage/rowset/bitmap_index_reader.cpp
  be/src/storage/rowset/bitmap_index_reader.h
  be/src/storage/rowset/bloom_filter_index_reader.cpp
  be/src/storage/rowset/bloom_filter_index_reader.h
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
  be/src/storage/rowset/zone_map_index.cpp
  be/src/storage/rowset/zone_map_index.h
  be/test/storage/rowset/column_reader_writer_test.cpp
Labels: Approved

#8808 [SR SQL Planner Summer Camp] New Parser and Analyzer support CreateRoleStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ImpersonatePrivInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: Approved

#10800 [Enhance] use single-quote escape array<json>
  be/src/column/json_column.cpp
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  be/test/util/mysql_row_buffer_test.cpp
Labels: Approved

#10837 [BugFix] Fix semi join with limit reorder error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinOrder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/MultiJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: Approved

#10286 [Enhancement] modify start and stop scripts for cn gracefully exit
  bin/start_cn.sh
  bin/stop_cn.sh
Labels: Approved

#10459 [BugFix] Fix condition will always be true error when check functionset name in mv
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRuleTest.java
Labels: Approved, sig/materialized view

#10844 [Enhancement] Split skip-aggr AGG table physically not logically
  be/src/exec/vectorized/olap_scan_node.cpp
Labels: Approved

#10863 [Docs] New QuickStart Tutorial
  docs/quick_start/Create_table.md
  docs/quick_start/Deploy.md
  docs/quick_start/Import_and_query.md
Labels: documentation, Approved

#10842 [Bugfix] Key columns cannot be pruned in the non-skip-aggr scan stage
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/FilterUnusedColumnTest.java
Labels: Approved

#10859 [Enhancement] add session variable tablet_internal_parallel_mode
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/exec/vectorized/olap_scan_node.cpp
  be/src/exec/vectorized/olap_scan_node.h
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/SetVar.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
  gensrc/thrift/InternalService.thrift
Labels: Approved

#10841 [Enhancement] Remove redundant ES exception handler.
  fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java
  fe/fe-core/src/main/java/com/starrocks/external/elasticsearch/EsRepository.java
Labels: Approved

#10720 [Enhancement] Add consistent hashing for hdfs backend selector
  fe/fe-core/src/main/java/com/starrocks/common/util/ConsistentHashRing.java
  fe/fe-core/src/main/java/com/starrocks/common/util/HashRing.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PlainHashRing.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RendezvousHashRing.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HudiScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/test/java/com/starrocks/common/HashRingTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: Approved

#10880 [Enhancement] switch back to consistent hash ring when node number is large
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
Labels: Approved

#10854 [Enhancement] make push down predicate scan rule more generic
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
Labels: Approved

#10857 [BugFix] ignore flush pool in txn_manager for CN
  be/src/storage/txn_manager.cpp
Labels: Approved

#9634 [BugFix] string_to_float_internal may lose some precision
  be/src/util/string_parser.hpp
  be/test/util/string_parser_test.cpp
  build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: Approved

#10883 [BugFix] BE crash when table use snappy compression (#10883)
  be/src/util/compression/block_compression.cpp
Labels: Approved

#10887 Update BrokerLoad.md
  docs/loading/BrokerLoad.md
Labels: documentation

#10801 [Enhancement]Drop table use new thread pool
  be/src/agent/CMakeLists.txt
  be/src/agent/agent_server.cpp
  be/src/agent/agent_task.cpp
  be/src/agent/agent_task.h
  be/src/agent/drop_tablet_task.cpp
  be/src/agent/drop_tablet_task.h
  be/src/agent/task_singatures_manager.cpp
  be/src/agent/task_singatures_manager.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/runtime/exec_env.cpp
  be/src/service/service_be/lake_service.cpp
  be/src/service/starrocks_main.cpp
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_clone_task.h
  be/test/column/array_column_test.cpp
Labels: Approved

#10323 [Feature]implement Lambda array_filter()
  be/src/exprs/vectorized/array_functions.h
  be/src/exprs/vectorized/array_functions.tpp
  be/test/exprs/vectorized/array_functions_test.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/LambdaFunction.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#10890 Update BrokerLoad.md
  docs/loading/BrokerLoad.md
Labels: documentation

#10892 [Docs] Revise MV and add TOC
  docs/TOC.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
Labels: documentation, Approved

#10896 [branch-2.3]Fix bug cherry-pick pendingTask fix wrong.
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
Labels: automerge

#10516 [Enhancement] Subquery transformation refactor(1)
  fe/fe-core/src/main/java/com/starrocks/catalog/PseudoType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/SubqueryType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CaseWhenOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/SubqueryOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceSubqueryRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceSubqueryTypeRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/ExpressionMapping.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectConstTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
Labels: Approved

#10893 [Docs] update doc format for BrokerLoad & Loading_intro in Branch 2.2
  docs/loading/BrokerLoad.md
  docs/loading/Loading_intro.md
Labels: documentation

#10743 [Enhancement] Refactor rewrite phase by tree rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTreeAnchor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggProjectFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ReorderIntersectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/RewriteTreeTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/SeriallyTaskScheduler.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: Approved

#10888 [BugFix] Fix fs_memory appendv partial success
  be/src/fs/fs_memory.cpp
Labels: Approved

#10921 [Docs] 2.4 cbo
  docs/using_starrocks/Cost_based_optimizer.md
Labels: documentation, Approved

#10913 [BugFix] Add start option host_type in start_fe.sh
  bin/start_fe.sh
Labels: Approved

#10914 [docs] Update SR_table_design&fiveLoading&TOC
  docs/TOC.md
  docs/assets/3.1-1.png
  docs/assets/3.1-2.png
  docs/loading/BrokerLoad.md
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/Loading_intro.md
  docs/loading/StreamLoad.md
  docs/table_design/StarRocks_table_design.md
Labels: documentation, Approved

#10906 Update SR_table_design&fiveLoading&TOC in Branch 2.2
  docs/TOC.md
  docs/assets/3.1-1.png
  docs/assets/3.1-2.png
  docs/loading/BrokerLoad.md
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/Loading_intro.md
  docs/loading/StreamLoad.md
  docs/table_design/StarRocks_table_design.md
Labels: documentation

#10867 [BugFix] Fix zstd single input compress bug
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/tablet_sink.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/util/compression/block_compression.cpp
  be/test/util/block_compression_test.cpp
Labels: Approved

#10922 [docs] Update SR_table_design&fiveLoading&TOC in Branch 2.3
  docs/TOC.md
  docs/assets/3.1-1.png
  docs/assets/3.1-2.png
  docs/loading/BrokerLoad.md
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/Loading_intro.md
  docs/loading/StreamLoad.md
  docs/table_design/StarRocks_table_design.md
Labels: documentation

#10773 [Doc] 2.4 Deploy Compute Node
  docs/administration/Cluster_administration.md
  docs/administration/deploy_cn.md
Labels: documentation

#10912 [Bugfix] Init connector_scan_executor for compute_node
  be/src/runtime/exec_env.cpp
Labels: Approved

#10718 [Enhancement] Add logic to cancel export job when be has crashed before
  fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportFailMsg.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java
  fe/fe-core/src/test/java/com/starrocks/load/ExportCheckerTest.java
Labels: Approved

#10232 [Feature] support report for large dataset
  be/src/common/config.h
  be/src/connector/file_connector.cpp
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/vectorized/file_scan_node.cpp
  be/src/exec/vectorized/tablet_scanner.cpp
  be/src/runtime/CMakeLists.txt
  be/src/runtime/client_cache.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/profile_report_worker.cpp
  be/src/runtime/profile_report_worker.h
  fe/fe-core/src/main/java/com/starrocks/load/EtlStatus.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/InternalService.thrift
Labels: Approved

#10905 [Refactor] Remove unuse code & move path
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Projection.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DefaultPredicateSelectivityEstimator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DictMappingRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ExchangeSortToMergeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PredicateReorderRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneAggregateNodeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneShuffleColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/TreeRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/SeriallyTaskScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TaskContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TaskScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TopDownRewriteIterativeTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TopDownRewriteOnceTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TopDownRewriteTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/DefaultPredicateSelectivityEstimatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/PredicateReorderRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorsReuseTest.java
Labels: Approved

#10754 [Doc] docs for version 2.4
  docs/TOC.md
  docs/assets/3.8.1.png
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  docs/sql-reference/sql-statements/Administration/SHOW COMPUTE NODES.md
  docs/sql-reference/sql-statements/Utility/DESCRIBE.md
  docs/sql-reference/sql-statements/account-management/EXECUTE AS.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
  docs/sql-reference/sql-statements/account-management/REVOKE.md
  docs/sql-reference/sql-statements/data-definition/CREATE EXTERNAL CATALOG.md
  docs/sql-reference/sql-statements/data-definition/DROP CATALOG.md
  docs/sql-reference/sql-statements/data-definition/REFRESH EXTERNAL TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CATALOGS.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW DATABASES.md
  docs/using_starrocks/Manage_data.md
  docs/using_starrocks/catalog/catalog_overview.md
  docs/using_starrocks/catalog/default_catalog.md
  docs/using_starrocks/catalog/hive_catalog.md
  docs/using_starrocks/catalog/hudi_catalog.md
  docs/using_starrocks/catalog/iceberg_catalog.md
  docs/using_starrocks/catalog/query_external_data.md
Labels: documentation, Approved

#10934 [docs] Release Note 2.3.2
  docs/release_notes/release-2.3.md
Labels: documentation, Approved

#10856 [Bugfix] fix star mgr get wrong db name
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJEJournalTest.java
Labels: Approved

#10927 [BugFix] write file repeat close bug
  be/src/fs/fs_broker.cpp
  be/src/fs/fs_hdfs.cpp
  be/src/fs/fs_posix.cpp
Labels: Approved

#10901 [Enhancement] Add more detail mem_tracker for metadata
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/storage/tablet_schema.cpp
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
Labels: Approved

#10935 [docs] Add Release Note 2.3.2 to Branch 2.3
  docs/release_notes/release-2.3.md
Labels: documentation

#10936 [Refactor] remove the nodicard annotation from Column::append_nulls
  be/src/column/column.h
Labels: Approved

#10943 [cherry-pick][branch-2.3][BugFix] Write file repeat close bug (#10927)
  be/src/fs/fs_broker.cpp
  be/src/fs/fs_hdfs.cpp
Labels: automerge

#10138 [Feature] Implement replicated storage engine
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.h
  be/src/runtime/tablets_channel.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/service/service_be/internal_service.cpp
  be/src/service/service_be/internal_service.h
  be/src/storage/CMakeLists.txt
  be/src/storage/async_delta_writer.cpp
  be/src/storage/async_delta_writer.h
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/memtable.cpp
  be/src/storage/memtable.h
  be/src/storage/memtable_flush_executor.cpp
  be/src/storage/memtable_flush_executor.h
  be/src/storage/memtable_rowset_writer_sink.h
  be/src/storage/memtable_sink.h
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/beta_rowset_writer.h
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/rowset/segment_writer.h
  be/src/storage/segment_flush_executor.cpp
  be/src/storage/segment_flush_executor.h
  be/src/storage/segment_replicate_executor.cpp
  be/src/storage/segment_replicate_executor.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/util/reusable_closure.h
  be/test/CMakeLists.txt
  be/test/storage/memtable_flush_executor_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset_merger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/task/StreamLoadTask.java
  gensrc/proto/data.proto
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
  gensrc/proto/olap_common.proto
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/InternalService.thrift
Labels: Approved

#10951 [2.4 docs] Update join in SELECT
  docs/sql-reference/sql-statements/data-manipulation/SELECT.md
Labels: documentation, Approved

#10836 [Feature] analyze statement support async and support show progress in analyze status
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeStatus.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
Labels: Approved

#10908 [Refactor] refactor SortDesc in sort
  be/src/exec/vectorized/chunks_sorter.cpp
  be/src/exec/vectorized/chunks_sorter.h
  be/src/exec/vectorized/chunks_sorter_full_sort.cpp
  be/src/exec/vectorized/chunks_sorter_heap_sort.cpp
  be/src/exec/vectorized/chunks_sorter_heap_sort.h
  be/src/exec/vectorized/chunks_sorter_topn.cpp
  be/src/exec/vectorized/sorting/compare_column.cpp
  be/src/exec/vectorized/sorting/sort_column.cpp
  be/src/exec/vectorized/sorting/sort_helper.h
  be/src/exec/vectorized/sorting/sorting.h
  be/src/storage/memtable.cpp
  be/src/storage/schema_change.cpp
  be/test/column/fixed_length_column_test.cpp
  be/test/column/nullable_column_test.cpp
  be/test/exec/vectorized/chunks_sorter_test.cpp
Labels: Approved

#10955 [cherry-pick] [branch-2.3] [BugFix] fix the bug of import array<json> (#10737)
  be/src/exec/vectorized/json_scanner.cpp
  be/src/exec/vectorized/json_scanner.h
  be/test/exec/test_data/json_scanner/test9.json
  be/test/exec/vectorized/json_scanner_test.cpp
Labels: automerge

#10947 [BugFix] fix zero scan ranges in hdfs backend selector
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
Labels: Approved

#9981 [SR SQL Planner Summer Camp] Support RoutineLoadCreate Statement in new Parser and Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/RoutineLoadDescTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: Approved

#10930 [Enhancement] Fix lazy load fields in conjunct like `(a<1) or (a>7)`
  be/src/connector/hive_connector.cpp
Labels: Approved

#10969 [docs] fix broken link in CREATE TABLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, Approved

#10968 [Docs] 2.4-parallel-scan-of-a tablet
  docs/table_design/Data_distribution.md
Labels: documentation

#10966 [Docs] 2.4-flink-connector-supports-partial-updates
  docs/loading/Flink-connector-starrocks.md
Labels: documentation

#10963 [Feature] Make full partition statistic collect as default statistic mode
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: Approved

#10960 [Cherry-pick][Enhancement] Enable FE to list all file in HDFS recursively.
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
Labels: automerge

#10944 [Enhancement] Add mem statistics for column index
  be/src/storage/rowset/bitmap_index_reader.cpp
  be/src/storage/rowset/bitmap_index_reader.h
  be/src/storage/rowset/bloom_filter_index_reader.cpp
  be/src/storage/rowset/bloom_filter_index_reader.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
  be/src/storage/rowset/zone_map_index.cpp
  be/src/storage/rowset/zone_map_index.h
  be/src/util/system_metrics.cpp
  be/test/storage/rowset/bitmap_index_test.cpp
  be/test/storage/rowset/bloom_filter_index_reader_writer_test.cpp
  be/test/storage/rowset/ordinal_page_index_test.cpp
  be/test/storage/rowset/zone_map_index_test.cpp
Labels: Approved

#10950 [Bugfix] Connector uses different resource group SchedEntity from Olap
  be/src/exec/workgroup/scan_task_queue.cpp
  be/src/exec/workgroup/scan_task_queue.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  be/src/runtime/exec_env.cpp
Labels: Approved

#10940 [BugFix] array_distinct crash when input column is null literal
  be/src/exprs/vectorized/array_functions.tpp
  be/test/exprs/vectorized/array_functions_test.cpp
Labels: Approved

#10982 [BugFix][Lake] Compaciton timeout too short
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
Labels: Approved

#10958 Update deploy_cn.md
  docs/administration/deploy_cn.md
Labels: documentation

#10977 [BugFix][Lake] Forgot to init non-serialized field
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: Approved

#10984 [Enhancement] Add mem statistics for segment for segment metadata
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/storage/lake/tablet.cpp
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/page_handle.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/tablet_updates.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/tablet_writer_test.cpp
  be/test/storage/memtable_flush_executor_test.cpp
  be/test/storage/rowset/column_reader_writer_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset/segment_iterator_test.cpp
  be/test/storage/rowset/segment_rewriter_test.cpp
  be/test/storage/rowset/segment_test.cpp
Labels: Approved

#10985 [Enhancement] put start_be/cn.sh shared part into common.sh
  bin/common.sh
  bin/start_be.sh
  bin/start_cn.sh
Labels: Approved

#10954 [BugFix] simplify expr hashCode calculating
  fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CompoundPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DateLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ExistsPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IntLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LargeIntLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LikePredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/StringLiteral.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ExprHashCodeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: Approved

#10964 [Enhance] introduce fastpath for merge nullable column
  be/src/bench/chunks_sorter_bench.cpp
  be/src/exec/vectorized/sorting/merge_column.cpp
  be/src/util/faststring.h
  be/test/column/bytes_test.cpp
  be/test/exec/vectorized/arrow_converter_test.cpp
Labels: Approved

#10629 [Enhancement] Fold LimitOperator if of no use
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved

#10956 [cherry-pick] [branch-2.4] [BugFix] fix the bug of import array<json> (#10737)
  be/src/exec/vectorized/json_scanner.cpp
  be/src/exec/vectorized/json_scanner.h
  be/test/exec/test_data/json_scanner/test9.json
  be/test/exec/vectorized/json_scanner_test.cpp
Labels: automerge

#10945 [BugFix] subquery operator cast bugfix
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSCTERatioTest.java
Labels: Approved

#10942 [cherry-pick][branch-2.2][BugFix] Write file repeat close bug (#10927)
  be/src/env/env_broker.cpp
Labels: automerge

#9129 [SR SQL Planner Summer Camp] New Parser and Analyzer support ShowGrantsStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowGrantsStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowGrantsStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved, title needs [type]

#10988 [BugFix] fix be may cause a heap-buffer-over in order by limit
  be/src/exec/vectorized/sorting/compare_column.cpp
  be/test/exec/vectorized/chunks_sorter_test.cpp
Labels: Approved

#11000 [Refactor]remove unuse library
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CsvFileStatisticsStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/pom.xml
Labels: Approved

#10055 [Refactor] Support RoutineLoadTaskShow Statement in new Parser and Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadTaskStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadTaskStmtTest.java
Labels: Approved

#11013 [Docs] Add FQDN and other trivial modifications
  docs/TOC.md
  docs/administration/Cluster_administration.md
  docs/administration/deploy_cn.md
  docs/administration/enable_fqdn.md
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved, title needs [type]

#8821 [SR SQL Planner Summer Camp]New Parser and Analyzer support DropRoleStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/DropRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
Labels: Approved, title needs [type]

#11015 [Docs] Add FQDN and other trivial modifications
  docs/TOC.md
  docs/administration/Cluster_administration.md
  docs/administration/deploy_cn.md
  docs/administration/enable_fqdn.md
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation

#10900 [Enhancement] Adjust calculation of OverallThroughput
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
Labels: Approved
