Repository StarRocks/starrocks, pull requests merged in 2022-05, with the labels that each got.

#5859 [Cleanup] Remove file_util.{h,cpp}
  be/src/exec/vectorized/file_scanner.cpp
  be/src/exec/vectorized/parquet_scanner.cpp
  be/src/fs/CMakeLists.txt
  be/src/fs/fs_util.cpp
  be/src/fs/fs_util.h
  be/test/exec/vectorized/parquet_scanner_test.cpp
Labels: type/cleanup

#5867 [Cleanup] Remove lru_cache.hpp and export_task_mgr.{h,cpp}
  be/src/runtime/export_task_mgr.cpp
  be/src/runtime/export_task_mgr.h
  be/src/runtime/routine_load/data_consumer_pool.h
  be/src/service/backend_service.cpp
  be/src/util/lru_cache.hpp
  be/test/CMakeLists.txt
  be/test/util/lru_cache_util_test.cpp
Labels: type/cleanup

#5630 [SR GeekCamp] Distributed execution of count distinct for multiple columns 【Moderate】 #4025
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctOptimizedRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctOptimizedRuleTest.java
Labels: Geek Camp 2022/feature

#6219 [Enhancement] Support 4 phase aggregate for group by constant
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: sig/optimizer

#5133 [Feature] Add materialized view definition
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MetaObject.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
  gensrc/thrift/Types.thrift
Labels: sig/materialized view

#6566 [MaterializedView] add PartitionInfo which have expressions [P0]
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExpressionPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionGsonSerializationTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionRangePartitionInfoTest.java
Labels: sig/materialized view
