Repository StarRocks/starrocks, pull requests merged in 2022-08, with the labels that each got.

#9375 [Refactor] Refactor drop table
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#9408 [bugfix] fix staros integration build break
  be/src/fs/fs.cpp
Labels: Approved

#9160 [BugFix] Fix the incomplete ok semantic in runPendingJob.
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: Approved

#9376 [Enhancement] rename `currentKey` to `nextKey` in `BDBJournalCursor`
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
Labels: Approved

#9410 [BugFix] Shared fs shouldn't set individual FSOptions
  be/src/fs/fs.cpp
  be/src/fs/fs.h
Labels: Approved

#8965 [SR SQL Planner Summer Camp] New Parser and Analyzer support LoadStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/LabelName.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/LoadStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/LoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RestrictOpMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadingTaskPlannerTest.java
Labels: Approved

#9388 [BugFix] Fix set statement miss user define variable and system variable syntax bug
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: Approved

#8931 [Feature] Iceberg connector supports custom catalog
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/external/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/external/iceberg/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/external/iceberg/IcebergUtil.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/external/iceberg/IcebergCustomCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/external/iceberg/IcebergHiveCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogLevelTest.java
Labels: Approved

#9369 [Refactor] Adjust show load print message
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
Labels: Approved

#9413 [Bugfix] ignore partition and columns name case when create mv.#9386
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9365 [Enhancement] Add concurrent load unittest
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoFrontend.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnNewPublishTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/NewPublishTest.java
  fe/pom.xml
Labels: Approved

#9146 [Feature] support integrate starmgr
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/staros/BDBJEJournalSystem.java
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrJournal.java
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJournalCursorTest.java
  fe/fe-core/src/test/java/com/starrocks/staros/BDBJEJournalSystemTest.java
  fe/fe-core/src/test/java/com/starrocks/staros/StarMgrJournalTest.java
  fe/fe-core/src/test/java/com/starrocks/staros/StarMgrServerTest.java
Labels: Approved

#9424 [Bugfix]there is no partition when create mv use trunc_date(week,col1)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9354 [Enhancement] Optimze colocate balance with BE temporarily restart
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: Approved

#9250 [Enhancement] Add throw exception for cast when allow throw exception
  be/src/exprs/vectorized/cast_expr.cpp
Labels: Approved

#9445 [BugFix] Fix LocalTablet Inconsistent bug after deserialization from json string
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/test/java/com/starrocks/catalog/LocalTabletTest.java
Labels: Approved

#6193 [Enhancement][jemalloc] Phase 1: BE supports specifying jemalloc at compile time
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  be/src/http/CMakeLists.txt
  be/src/http/action/pprof_actions.cpp
  be/src/http/default_path_handlers.cpp
  be/src/service/mem_hook.cpp
  be/src/service/starrocks_main.cpp
  be/src/util/metrics.h
  be/src/util/starrocks_metrics.cpp
  be/src/util/starrocks_metrics.h
  be/src/util/system_metrics.cpp
  bin/start_be.sh
  build.sh
Labels: Approved

#9339 [Enhancement] Refine profile merge mechanism
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/com/starrocks/common/util/Counter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: Approved

#9426 [Enhancement] Support pipeline level shuffle for CTE
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/runtime/data_stream_sender.h
  fe/fe-core/src/main/java/com/starrocks/planner/MultiCastPlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: Approved

#9158 [BugFix] Remove broker load unnecessary cast
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
Labels: Approved

#9449 [docs]delete-execute-as-in-release-note
  docs/release_notes/release-2.3.md
Labels: documentation, Approved

#9450 Delete execute as and some jira links in release note
  docs/release_notes/release-2.3.md
Labels: documentation

#9448 [BugFix] Fix error of ScanTime
  be/src/exec/pipeline/scan/scan_operator.cpp
Labels: Approved

#9343 [feature] Add black list for insert
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
Labels: Approved

#9318 [Refactor] Removed not used log upon start and unified drop_tablet_unlock interface
  be/src/agent/task_worker_pool.cpp
  be/src/http/ev_http_server.cpp
  be/src/service/backend_base.cpp
  be/src/service/backend_options.cpp
  be/src/service/starrocks_main.cpp
  be/src/storage/data_dir.cpp
  be/src/storage/olap_server.cpp
  be/src/storage/primary_index.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
  be/src/util/thrift_server.cpp
Labels: Approved

#9401 [Bugfix] fix invalid dictionary in schema change
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: Approved

#9466 [BugFix]Fix exception typos
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
Labels: Approved

#9171 [Feature] Support export without broker
  be/src/fs/fs.h
  be/src/fs/fs_hdfs.cpp
  be/src/fs/fs_s3.cpp
  be/src/runtime/export_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/ExportStmt.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExportSink.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportExportingTask.java
  gensrc/thrift/DataSinks.thrift
Labels: Approved

#9437 [BugFix] Use out exprs column as spark rdd schema
  be/src/runtime/fragment_mgr.cpp
Labels: Approved

#9137 [Enhancement] keep tablet scheduling related config naming consistent
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowConfigStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/BackendLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/ClusterLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ConfigBase.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetDdlStmtAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MetaReplayerCheckAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MigrationAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RowCountAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/SetConfigAction.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/DiskAndTabletLoadReBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/common/ConfigTest.java
  fe/fe-core/src/test/java/com/starrocks/common/PropertyAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/resources/conf/config_test.properties
  fe/fe-core/src/test/resources/conf/config_test2.properties
  fe/fe-core/src/test/resources/conf/config_test3.properties
Labels: Approved

#9457 [Doc]delete content that prepare for 2.4
  docs/TOC.md
  docs/sql-reference/sql-statements/account-management/EXECUTE AS.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
  docs/sql-reference/sql-statements/account-management/REVOKE.md
Labels: documentation, Approved

#9123 [SR SQL Planner Summer Camp] New Parser and Analyzer support schema c…
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/AddColumnClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AddColumnsClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterTableColumnClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ColumnRenameClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DropColumnClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ModifyColumnClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ReorderColumnsClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AddColumnClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AddColumnsClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterTableStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DropColumnClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ModifyColumnClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ReorderColumnsClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/DDLTestBase.java
Labels: Approved

#9352 [Lake][Delete 1/2] support delete from lake table
  be/src/gen_cpp/CMakeLists.txt
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet.h
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/delete/LakeDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/load/OlapDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceAsync.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionAlreadyCommitException.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/DeleteTest.java
  fe/fe-core/src/test/java/com/starrocks/load/DeleteHandlerTest.java
  gensrc/proto/lake_delete.proto
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
Labels: Approved

#9101 Alter lake table drop partition
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
Labels: Approved

#9431 [Feature] Iceberg table supports unknown types
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/external/iceberg/IcebergUtil.java
  fe/fe-core/src/test/java/com/starrocks/external/iceberg/IcebergUtilTest.java
Labels: Approved

#9438 [BugFix] Fix correlated subquery unknown error when equals predicate has expression
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/query_dump/correlated_subquery_with_equals_expression.json
Labels: Approved

#9070 [Enhancement] improve join reorder greedy algorithm
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinOrder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderGreedy.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EnumeratePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q5.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q7.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q9.sql
Labels: Approved

#9458 [BugFix] Fix hang because of empty scan ranges
  be/src/exec/vectorized/connector_scan_node.cpp
  be/test/formats/parquet/file_reader_test.cpp
Labels: Approved

#9397 [Enhancement] No need use write lock for base tablet
  be/src/storage/tablet_manager.cpp
Labels: Approved

#9477 [Enhancement] Refine profile mechanism
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/com/starrocks/common/util/Counter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: Approved

#9226 [StarRocks On ES][Bug-Fix] handle limit operator push-down correctly
  be/src/connector/es_connector.cpp
  be/src/exec/es/es_scroll_parser.cpp
Labels: Approved

#9208 [StarRocks On ES] generate match_all query when all predicates cannot…
  fe/fe-core/src/main/java/com/starrocks/external/elasticsearch/QueryConverter.java
Labels: Approved

#9507 [BugFix] Shouldn't close file system when broker encounters exception
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: Approved

#9444 [Enhancement] Unable to filter NULL data by WHERE to build NOT NULL column
  be/src/exec/vectorized/file_scanner.cpp
Labels: Approved

#9377 [Feature] turn on the enable_column_expr_predicate by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#9509 [cherry-pick][branch-2.3][BugFix] shouldn't close file system when broker encounters excecption(backport #9507)
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: documentation

#8985 [SR SQL Planner Summer Camp] Support RoutineLoadStop Statement in new Parser and Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionalExprProvider.java
  fe/fe-core/src/main/java/com/starrocks/analysis/PauseRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ResumeRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/StopRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PauseRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResumeRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StopRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/PauseRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResumeRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/StopRoutineLoadStmtTest.java
Labels: Approved

#9465 [BugFix] Forbid creating materialized view using week/quarter/year to refresh
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9503 [Enhancement] Disable adding fe with the same host
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTest.java
Labels: Approved

#9510 [Bugfix] Fix error sql generated for jdbc oracle table
  be/src/connector/jdbc_connector.cpp
Labels: Approved

#9201 [Feature] Support select into outfile without broker
  be/src/fs/fs.h
  be/src/fs/fs_hdfs.cpp
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_writer.h
  fe/fe-core/src/main/java/com/starrocks/analysis/OutFileClause.java
  fe/fe-core/src/main/java/com/starrocks/planner/ResultSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  gensrc/thrift/DataSinks.thrift
Labels: Approved

#9075 [BugFix] Vectical rowset writer final flush need writer finalize footer for partial columns.
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/rowset/segment_writer.h
  be/test/storage/rowset/rowset_test.cpp
Labels: Approved

#9152 [Feature] Support correlated scalar non-agg subquery
  be/src/connector/es_connector.cpp
  be/src/connector/hive_connector.cpp
  be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/repeat/repeat_operator.cpp
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/hash_joiner.h
  be/src/exec/vectorized/hdfs_scanner_text.cpp
  be/src/exec/vectorized/repeat_node.cpp
  be/src/exprs/vectorized/utility_functions.cpp
  be/src/exprs/vectorized/utility_functions.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorBuilderFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeTwoProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/logical-plan/subquery.sql
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#9550 [Doc] Add 2.2.4 Release notes
  docs/release_notes/release-2.2.md
Labels: documentation

#9524 [UT] Enable Cte Reuse for UT
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSCTETest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCHPlanTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/grouping-sets.sql
Labels: Approved

#8825 [SR SQL Planner Summer Camp] New Parser and Analyzer support ShowLoadStmt/ShowLoadWarnin…
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/CancelLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowLoadWarningsStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CancelLoadStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowLoadStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowLoadWarningsStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/CancelLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowLoadWarningsStmtTest.java
Labels: Approved

#9501 [Feature] Create history partitions automatically when start is specified for dynamic partition
  fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
Labels: Approved

#9549 [Doc] Add 2.2.4 Release notes
  docs/release_notes/release-2.2.md
Labels: documentation, Approved

#9451 [Refactor] Rename ICEBERG_CATALOG to iceberg.catalog.type
  docs/using_starrocks/External_table.md
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergResource.java
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergResourceTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergTableTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogLevelTest.java
Labels: Approved

#9236 [BugFix] Fix potential bug and refine log printing
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
Labels: Approved

#9420 [BugFix] Fix the failure of querying extenal table that contains struc columns
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/test/exec/test_data/parquet_scanner/file_reader_test.parquet4
  be/test/formats/parquet/file_reader_test.cpp
Labels: Approved

#9398 [Lake][Delete 2/2] Support read and compact lake tablet with delete rowset
  be/src/storage/delete_predicates.h
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/lake/tablet_reader.h
  be/test/storage/lake/horizontal_compaction_task_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
Labels: Approved

#9460 [Lake] Support lake tablet statistic collection
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  fe/fe-core/src/main/java/com/starrocks/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceAsync.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceClient.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
  gensrc/proto/lake_service.proto
Labels: Approved

#9489 [Enhancement] PseudoBackend support report task; add failure injection and write quorum test
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeTabletManager.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeTxnManager.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoFrontend.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoOlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/Rowset.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/Tablet.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnNewPublishTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnWithFailureTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/NewPublishTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TxnWithWriteFailureTest.java
Labels: Approved

#9551 [Doc] Add 2.2.4 Release notes
  docs/release_notes/release-2.2.md
Labels: documentation

#9560 [Bugfix] Fix NPE when refresh mv does not exist
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewStatementTest.java
Labels: Approved, sig/materialized view

#9402 [BugFix] Fix parquet array convert bug
  be/src/exec/vectorized/arrow_to_starrocks_converter.cpp
Labels: Approved

#9546 [BugFix] Fix FileScanNode use not null column
  be/src/column/chunk.cpp
  be/src/column/chunk.h
  be/src/exec/vectorized/parquet_scanner.cpp
  be/src/runtime/plan_fragment_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
Labels: Approved

#9548 [BugFix] Fix Prune Distinct Global Aggregate lose projection
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/PruneAggregateNodeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: Approved

#9567 [Bugfix] There is no data when use cte
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9586 [Bugfix] add system variable 'transaction_isolation'
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: Approved

#9570 [BugFix] record db name of view when query dump
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/DumpInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/MockDumpInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/query_dump/insert_view.json
  fe/fe-core/src/test/resources/sql/query_dump/multi_view_cross_join.json
  fe/fe-core/src/test/resources/sql/query_dump/multi_view_prune_columns.json
  fe/fe-core/src/test/resources/sql/query_dump/multi_view_with_db.json
Labels: Approved

#9572 [BugFix] Show routine load for non-existed job
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: Approved

#9561 [Refactor] Remove the AlterTask in TabletMeta
  be/src/storage/push_handler.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
  be/test/storage/tablet_updates_test.cpp
  gensrc/proto/olap_file.proto
Labels: Approved

#9556 [BugFix] Fix unknown error of profile merge mechanism
  be/src/util/runtime_profile.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: Approved

#9531 [BugFix] Discard expired backup/restore job
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupHandlerTest.java
Labels: Approved

#9578 [BugFix] Remove colocated index from memory
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColocateTableIndexTest.java
Labels: Approved

#9597 [Bugfix] Fix delete throw unknown error when enable query detail
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved

#9590 [Enhancement] Schedule VERSION_INCOMPLETE task imediately
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
Labels: Approved

#9576 [Bugfixi] not support create mv by mv #9543
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9559 [Enhancement] Clear storage after lake table is dropped
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/lake/DeleteLakeTableTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/DeleteTableTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BrpcProxy.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceAsync.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableTest.java
  gensrc/proto/lake_service.proto
Labels: Approved

#8926 [SR SQL Planner Summer Camp] add backup analyzer
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/BackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeBackupTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#9467 [BugFix] Fix multi nest cte inline error
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CTERelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: Approved

#9614 [Enhance] optimize json_query function
  be/src/exprs/vectorized/json_functions.cpp
  be/src/exprs/vectorized/json_functions.h
Labels: Approved

#9505 [Enhancement] Modify the sampling strategy for histogram statistics
  be/src/exprs/agg/histogram.h
  be/test/exprs/agg/aggregate_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/HistogramCacheLoaderTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved

#8815 [SR SQL Planner Summer Camp] New Parser and Analyzer support ModifyBrokerClause
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterSystemStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ModifyBrokerClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ModifyBrokerClauseTest.java
Labels: Approved

#9620 [Bugfix] mv task info not exists after modify async to MANUAL
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
Labels: Approved, sig/materialized view

#9621 [Bugfix] Fix ConcurrentModificationException of concurrently accessing childCounterMap
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
Labels: Approved

#9571 [BugFix] build script supports Python3 and fix file path typos (#9563)
  env.sh
  fe/fe-core/pom.xml
Labels: Approved

#9427 [BugFix] Close invalid environment before bdb setup retry
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBEnvironmentTest.java
Labels: Approved

#9617 [BugFix] Disable txngraph in nonnewpublish
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: Approved

#9629 [BugFix] Fix correlated scalar non-aggregate subquery unknown error when correlated predicate has expression
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: Approved

#9604 [BugFix] Fix `SHOW PROC /colocation_group' after erase db with same name
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColocateTableIndexTest.java
Labels: Approved

#9603 [Enhancement][Lake] Delete segment files on abort txn
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/test/formats/parquet/file_reader_test.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
Labels: Approved

#9606 [Enhancement] Optimize hash join when hash table is empty
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/join_hash_map.cpp
  be/src/exec/vectorized/join_hash_map.h
  be/src/exec/vectorized/join_hash_map.tpp
  be/test/exec/vectorized/join_hash_map_test.cpp
Labels: Approved

#9473 [BugFix] Fix not enough hosts error when BE is decommissioned
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#9650 [Enhancement] add more error info to s3 sdk
  be/src/io/s3_input_stream.cpp
Labels: Approved

#9573 [Enhancement] Avoid VERSION_INCOMPLETE repair task got blocked by REPLICA_MISSING
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: Approved

#9607 [Enhancement] Add clone logic to PseudoCluster and UT for tablet repair and clone
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/clone/CloneTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeTabletManager.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeTxnManager.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoGenericPool.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoOlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/Rowset.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/Tablet.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/TabletTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/ConcurrentTxnTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TxnWithWriteFailureTest.java
Labels: Approved

#9669 [Bugfix] fix crc32 heap-buffer-overflow in aarch64
  be/src/column/column_hash.h
Labels: Approved

#9689 Add v2.0.9 release notes
  docs/release_notes/release-2.0.md
Labels: documentation, Approved

#9690 Branch 2.3
  docs/release_notes/release-2.0.md
Labels: documentation

#9678 [Bugfix] fix coredump when hash table is empty
  be/src/exec/vectorized/join_hash_map.cpp
  be/src/exec/vectorized/join_hash_map.h
Labels: Approved

#9682 [Bugfix] Fix the redundant read request caused by mismatched buffer o…
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/formats/parquet/page_reader.cpp
  be/src/formats/parquet/page_reader.h
  be/src/util/buffered_stream.cpp
  be/src/util/buffered_stream.h
  be/test/util/buffered_stream_test.cpp
Labels: Approved

#9635 [Refactor]Minor: refactor SchemaChangeHandler
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
Labels: Approved

#9668 [Refactor] Remove auto unregister config from MemTracker
  be/src/runtime/mem_tracker.cpp
  be/src/runtime/mem_tracker.h
Labels: Approved

#9686 [Refactor] Remove LakeServiceClient
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/DeleteLakeTableTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/ShardDeleter.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionDispatchDaemon.java
  fe/fe-core/src/main/java/com/starrocks/lake/delete/LakeDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BrpcProxy.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/ShardDeleterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/DeleteTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
Labels: Approved

#9422 [Enhancement] Support load_transmission_compression_type session variable unified load compress config
  be/src/exec/tablet_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/task/StreamLoadTask.java
  gensrc/thrift/InternalService.thrift
Labels: Approved

#9666 [BugFix] Fix recovery for bad replica
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
Labels: Approved

#9598 [BugFix] Null date and datetime value for spark load is not consistent
  be/src/exec/vectorized/arrow_to_starrocks_converter.cpp
  be/src/exec/vectorized/sorting/compare_column.cpp
  be/src/exec/vectorized/sorting/sorting.h
Labels: Approved

#9396 [BugFix] Change the statistics table to non-static to prevent CreateAnalyzer from modifying ColumnDef
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
Labels: Approved

#9699 [Enhancement] Statistics collection focus on truncate and insert overwrite
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
Labels: Approved

#9715 [Feature] Support all-digit user name
  fe/fe-core/src/main/java/com/starrocks/common/FeNameFormat.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
Labels: Approved

#9727 [Enhancement] Add delete query detail Case for StmtExecutor
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/qe/StmtExecutorTest.java
Labels: Approved

#9728 [BugFix] Fix BrokerLoad FailMsg serialization throws NPE
  fe/fe-core/src/main/java/com/starrocks/load/FailMsg.java
  fe/fe-core/src/test/java/com/starrocks/load/FailMsgTest.java
Labels: Approved

#9718 [BugFix] Fix set statement miss user define variable and system variable syntax bug（2/2)
  fe/fe-core/src/main/java/com/starrocks/analysis/SetPassVar.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SetStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/SetPassVarTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/SetExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: Approved

#9520 [Feature] Support load json type from csv format through stream load
  be/src/formats/CMakeLists.txt
  be/src/formats/csv/converter.cpp
  be/src/formats/csv/json_converter.cpp
  be/src/formats/csv/json_converter.h
  be/test/CMakeLists.txt
  be/test/formats/csv/json_converter_test.cpp
Labels: Approved

#9738 [cherry-pick][branch-2.3][enhancement] parquet support coalsece reads across row groups and support late materialization
  be/src/common/config.h
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_chunk_reader.h
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/page_reader.cpp
  be/src/formats/parquet/page_reader.h
  be/src/formats/parquet/stored_column_reader.cpp
  be/src/formats/parquet/stored_column_reader.h
  be/src/util/buffered_stream.cpp
  be/src/util/buffered_stream.h
  be/test/exec/test_data/orc_scanner/orc_zero_size_stream.orc
  be/test/exec/test_data/parquet_scanner/file_reader_test.parquet3
  be/test/exec/test_data/parquet_scanner/small_row_group_data.parquet
  be/test/exec/vectorized/hdfs_scanner_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/group_reader_test.cpp
Labels: automerge

#9622 [Bugfix] Fix the problem of hash distribution
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: Approved

#9711 [Refactor][Enhancement] DataStreamRecvr::SenderQueue phase 1: introduce a lock-free queue
  be/src/util/moodycamel/blockingconcurrentqueue.h
  be/src/util/moodycamel/concurrentqueue.h
  be/src/util/moodycamel/lightweightsemaphore.h
  licenses/LICENSE-concurrentqueue.txt
Labels: Approved

#9632 [Bugfix] fix miss string function in MAX/MIN function when enable dictionary optimization
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalDecodeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#8831 [Feature]Support colocate materialized view index
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved

#9692 Branch 2.0
  docs/release_notes/release-2.0.md
Labels: documentation

#9691 Branch 2.2
  docs/release_notes/release-2.0.md
Labels: documentation

#9714 [Enhancement] Implements vectorized filter in aarch64
  be/src/column/column_helper.h
Labels: Approved

#9712 [Refacor] Cleanup AlterJob series code
  fe/fe-core/src/main/java/com/starrocks/alter/AlterHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/DecommissionBackendJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/DecommissionType.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DecommissionBackendClause.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentBatchTask.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateRollupTask.java
  fe/fe-core/src/main/java/com/starrocks/task/SchemaChangeTask.java
  fe/fe-core/src/test/java/com/starrocks/catalog/FakeEditLog.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
Labels: Approved

#9697 [BugFix] support offset in topn
  be/src/exec/pipeline/sort/sort_context.cpp
  be/src/exec/pipeline/sort/sort_context.h
  be/src/exec/vectorized/sorting/merge.h
  be/src/exec/vectorized/sorting/merge_column.cpp
  be/src/exec/vectorized/topn_node.cpp
Labels: Approved

#9120 [Enhancement] Optimize exchange sink shuffle performance
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exec/pipeline/exchange/local_exchange.h
  be/src/exec/pipeline/exchange/shuffler.h
  be/src/exprs/vectorized/runtime_filter.h
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/util/hash_util.hpp
  be/test/exprs/vectorized/runtime_filter_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: Approved

#9775 [Actions] enable default auto merge
  .github/workflows/add-pr-label.yml
  .github/workflows/automerge.yml
Labels: automerge

#9761 [BugFix]Fix show routine load job from db bug
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
Labels: Approved

#9774 [Cherry-pick 2.3][Bugfix] Fix incorrect partition property (#9622)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: automerge

#9795 [Doc]add release note for 2.1.12
  docs/release_notes/release-2.1.md
Labels: documentation, Approved

#9679 [Refactor] refactor materialized view refresh processor
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedViewPartitionVersionInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/DmlException.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: Approved, sig/materialized view

#9737 [Bugfix] Remove per tablet 'rollback transaction' logging
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/tablet_updates.cpp
Labels: Approved

#9770 [Enhancement] Load transanction state in image in commit order
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: Approved

#9752 [Enhancement] fix aws sdk use
  be/src/common/config.h
  be/src/service/starrocks_main.cpp
  bin/start_be.sh
Labels: Approved

#9693 [StarRocks On ES] Support array format.
  be/src/exec/es/es_scroll_parser.cpp
  be/src/exec/es/es_scroll_parser.h
  be/test/CMakeLists.txt
  be/test/exec/es/es_query_builder_test.cpp
  be/test/exec/es/es_scan_reader_test.cpp
  be/test/exec/es/es_scroll_parser_test.cpp
Labels: Approved

#9767 [Bugfix] no naming rule check when create mv
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: Approved, sig/materialized view

#9779 [BugFix] Fix data not updated after refresh when mv renamed.#9545
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: Approved, sig/materialized view

#9773 [Cherry-pick 2.2] Profile merge mechanism related prs
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/com/starrocks/common/util/Counter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: automerge

#9764 [BugFix]Fix unknown type table count(*)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRuleTest.java
Labels: Approved

#9824 [cherry-pick][branch-2.3][Enhancement] fix aws sdk use (#9752)
  be/src/common/config.h
  be/src/service/starrocks_main.cpp
  bin/start_be.sh
Labels: automerge

#9739 [Enhancement] support runtime filter in parquet scanner
  be/src/column/column_helper.h
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hdfs_scanner.cpp
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/exprs/vectorized/runtime_filter.h
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/test/exec/vectorized/hdfs_scanner_test.cpp
Labels: Approved, sig/DLA

#9829 [Doc] Fix Deploy.md relative links
  docs/quick_start/Deploy.md
Labels: documentation

#9835 [cherry-pick][branch-2.1][BugFix] Fix tablet_meta_mem_tracker inaccurate statistics (#8136)
  be/src/storage/rowset/column_reader.cpp
Labels: automerge

#9836 [cherry-pick][branch-2.2][BugFix] Fix tablet_meta_mem_tracker inaccurate statistics (#8136)
  be/src/storage/rowset/column_reader.cpp
Labels: automerge

#9837 [cherry-pick][branch-2.3][BugFix] Fix tablet_meta_mem_tracker inaccurate statistics (#8136)
  be/src/storage/rowset/column_reader.cpp
Labels: automerge

#8807 [SR SQL Planner Summer Camp] New Parser and Analyzer support DropUserStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/DropUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/DropUserStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#9667 [Enhancement] Compatible with msql use 'truncate' to delete partitions
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterOpType.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterOperations.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TruncatePartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/TruncatePartitionClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AstBuilderTest.java
Labels: Approved

#9853 [BugFix]Fix catalogs dirty read bug
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
Labels: Approved
