Repository StarRocks/starrocks, pull requests merged in 2022-04, with the labels that each got.

#4759 Cleanup: remove some unnecessary inline keywords
  be/src/storage/base_tablet.h
  be/src/storage/tablet.h
Labels: type/cleanup

#4805 Simplify API TabletMetaManager::save
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_meta_manager_test.cpp
Labels: Approved

#4804 remove some unnecessary inline keywords
  be/src/env/compressed_file.h
  be/src/exec/pipeline/sort/sort_context.h
  be/src/exec/vectorized/chunks_sorter.h
  be/src/exec/vectorized/chunks_sorter_topn.h
  be/src/http/http_channel.h
Labels: Approved

#4670 Add Env::create_dir_recursive
  be/src/env/env.h
  be/src/env/env_broker.cpp
  be/src/env/env_broker.h
  be/src/env/env_hdfs.cpp
  be/src/env/env_memory.cpp
  be/src/env/env_memory.h
  be/src/env/env_posix.cpp
  be/src/env/env_s3.cpp
  be/src/util/file_utils.cpp
  be/test/env/env_memory_test.cpp
  be/test/env/env_posix_test.cpp
Labels: sig/storage

#4650 Refactor: get tablet path from tablet meta
  be/src/storage/tablet_manager.cpp
Labels: sig/storage

#4807 Add some functions for constant expression simplification in FE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConstantExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: Geek Camp 2022 Task

#4935 [performance] fix bad performance in aggregator FixedSliceKey
  be/src/exec/vectorized/aggregate/agg_hash_map.h
Labels: Approved

#4965 fix ut compile error
  be/test/storage/task/engine_storage_migration_task_test.cpp
Labels: type/bug

#4983 suppot to handle timezone conversion when decoding min/max in zonemap of ORC file
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/exec/vectorized/orc_scanner_adapter.cpp
  be/src/exec/vectorized/orc_scanner_adapter.h
  be/src/formats/orc/apache-orc/c++/include/orc/sargs/SearchArgument.hh
  be/src/formats/orc/apache-orc/c++/src/Reader.cc
  be/test/exec/test_data/orc_scanner/writer_tz_shanghai.orc
  be/test/exec/test_data/orc_scanner/writer_tz_utc.orc
  be/test/exec/vectorized/hdfs_scanner_test.cpp
  be/test/exec/vectorized/orc_scanner_adapter_test.cpp
Labels: external/hive, sig/DLA

#5281 Fix incorrect result set under concurrent query
  be/src/io/fd_input_stream.cpp
  be/src/io/fd_input_stream.h
Labels: Approved

#5134 [SR GeekCamp]New Parser and Analyzer support ADMIN SET related statement
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminSetConfigStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AdminSetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminSetConfigStmtTest.java
Labels: Geek Camp 2022/feature

#4869 [SR GeekCamp] Reorder predicates based on selectivity【Challenging】
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ConstantOperatorUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/DefaultPredicateSelectivityEstimator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/PredicateReorderRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/ConstantOperatorUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/DefaultPredicateSelectivityEstimatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/PredicateReorderRuleTest.java
Labels: Geek Camp 2022/feature

#5343 [SR GeekCamp] Support fe grammar for GBK charset
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/ColumnDef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SetNamesVar.java
  fe/fe-core/src/main/java/com/starrocks/qe/GlobalVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
Labels: Geek Camp 2022/feature

#4957 [MaterializedView]Drop Materialized vied stmt
  fe/fe-core/src/main/java/com/starrocks/analysis/DropMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/DropMaterializedViewStmtNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: sig/materialized view

#5520 Add BE connector for DLA new framework
  be/CMakeLists.txt
  be/src/connector/CMakeLists.txt
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/test/exprs/vectorized/time_functions_test.cpp
Labels: sig/DLA

#5537 [SR GeekCamp] Support show materialized view in new Parser and new Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowMaterializedViewTest.java
Labels: sig/materialized view

#5566 Add fe config for mv
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: sig/materialized view
