Repository StarRocks/starrocks, pull requests merged in 2022-07, with the labels that each got.

#8041 Mv use insert overwrite
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MvTaskRunProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: sig/materialized view

#7755 [MaterializedView] Partition based on non-existing table throws NPE when creating mv (#7733)
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RangeUtils.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewDefBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ExpressionPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MvTaskRunProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: sig/materialized view

#8101 [Enhancement] Task support kill API
  fe/fe-core/src/main/java/com/starrocks/scheduler/Task.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: sig/materialized view

#8166 [Enhancement] Exchange receiver side add metric 'ClosureBlockTime'
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_recvr.h
Labels: Approved

#8405 [SR SQL Planner Summer Camp] antlr4 for recoverTable
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/RecoverTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/RecoverTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8486 [BugFix] Fix storage cooldown time ut
  fe/fe-core/src/test/java/com/starrocks/catalog/ListPartitionDescTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ListPartitionInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MultiListPartitionDescTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/SingleListPartitionDescTest.java
Labels: Approved

#8491 [fix test] Fix a unstable test case
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8352 [Refactor] Discard unknown transaction status
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStatus.java
Labels: Approved

#8424 [Refactor] Refactor apply node constructor
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggProjectFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
Labels: Approved

#8525 Rename lake::GroupAssigner to lake::LocationProvider
  be/src/fs/fs_util.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/group_assigner.h
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/starlet_location_provider.cpp
  be/src/storage/lake/starlet_location_provider.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/test/CMakeLists.txt
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/horizontal_compaction_task_test.cpp
  be/test/storage/lake/location_provider_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
  be/test/storage/lake/tablet_writer_test.cpp
  be/test/storage/lake/test_location_provider.h
Labels: Approved

#8468 [Enhancement] Do not need check rssid equivalence when compaction.
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
Labels: Approved

#8408 [Enhancement] Support statistics collect immediately when CreateAnalyzeStmt and some code refactoring
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/execution/CreateAnalyzeJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateAnalyzeJobStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeJobStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinOrder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeStatus.java
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/main/java/com/starrocks/statistic/TableCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateAnalyzeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/PredicateReorderRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorageTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved

#8186 [Enhancement] limit buffer capacity instead of scan concurrency
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/fragment_executor.h
  be/src/exec/pipeline/scan/balanced_chunk_buffer.cpp
  be/src/exec/pipeline/scan/balanced_chunk_buffer.h
  be/src/exec/pipeline/scan/chunk_buffer_limiter.cpp
  be/src/exec/pipeline/scan/chunk_buffer_limiter.h
  be/src/exec/pipeline/scan/chunk_source.cpp
  be/src/exec/pipeline/scan/chunk_source.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/olap_scan_context.cpp
  be/src/exec/pipeline/scan/olap_scan_context.h
  be/src/exec/pipeline/scan/olap_scan_operator.cpp
  be/src/exec/pipeline/scan/olap_scan_operator.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/scan_node.h
  be/src/exec/vectorized/connector_scan_node.cpp
  be/src/exec/vectorized/olap_scan_node.cpp
  be/src/exec/vectorized/olap_scan_node.h
  be/src/util/blocking_queue.hpp
  be/src/util/runtime_profile.cpp
Labels: Approved

#8104 [Enhancement] add log configuration for the jars called via JNI in BE
  be/CMakeLists.txt
  build.sh
  conf/log4j.properties
  java-extensions/jdbc-bridge/src/main/java/com/starrocks/jdbcbridge/JDBCBridge.java
Labels: Approved

#8526 [Feature] Change for re-enable minidump
  be/CMakeLists.txt
  thirdparty/minidump/gen_minidump_symbols.sh
  thirdparty/minidump/gen_stack_trace.sh
Labels: Approved

#8459 [SR SQL Planner Summer Camp] Support drop partition in new Parser and Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/DropPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
Labels: Approved

#8356 [Feature]Support hudi connector
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaCache.java
  fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateCatalogStmt.java
  fe/fe-core/src/test/java/com/starrocks/catalog/HudiTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hudi/HudiMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/external/hive/HiveTableTest.java
  fe/fe-core/src/test/java/com/starrocks/external/hive/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogLevelTest.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
Labels: Approved

#8425 rectify wildcard decimal types of multi_distinct_sum converted from sum(distinct) and avg(distinct)
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
Labels: Approved

#8458 [Enhancement] orc format to support coalesce reads
  be/src/common/config.h
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/formats/orc/apache-orc/c++/include/orc/OrcFile.hh
  be/src/formats/orc/apache-orc/c++/src/Reader.cc
  be/src/formats/orc/apache-orc/c++/src/Reader.hh
  be/src/formats/orc/orc_chunk_reader.cpp
Labels: Approved

#8542 [Enhancement] [Refactor] Update compaction do not need rssid file anymore, remove this set of management mechanisms.
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset/beta_rowset_writer.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/rowset_writer_adapter.h
  be/src/storage/rowset_merger.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/update_compaction_state.cpp
  be/src/storage/update_compaction_state.h
  be/test/storage/rowset_merger_test.cpp
Labels: Approved

#8553 [MaterializedView] add cancel refresh for MaterializedView
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java
  fe/fe-core/src/main/java/com/starrocks/execution/DataDefinitionExecutorFactory.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CancelRefreshMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CancelRefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved, sig/materialized view

#8572 [Bugfix] Fix create mv ut unstable
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: Approved

#8421 [BugFix] Notify transaction status visible to caller after write log
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: Approved

#8552 Optimize error message for alter table with materialized view
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterTableStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
Labels: sig/materialized view

#8195 [SR SQL Planner Summer Camp] Support anltr4 for showAlterStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowAlterStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowAlterStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowAlterStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeShowAlterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8586 [BugFix] Fix first_value/last_value of preceding/following window
  be/src/exprs/agg/window.h
Labels: Approved

#8535 [Enhancement] add chunk_accumulate_operator
  be/src/exec/CMakeLists.txt
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/chunk_accumulate_operator.cpp
  be/src/exec/pipeline/chunk_accumulate_operator.h
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp
  be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
Labels: Approved

#8584 [BugFix] return status error when `partition_id` not found in map
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
Labels: Approved

#8594 [BugFix] Fixed StarletLocationProvider::join_path() bug
  be/src/storage/lake/starlet_location_provider.cpp
  be/test/CMakeLists.txt
Labels: Approved

#8548 [MaterializedView] alter async refresh task for alter mv
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
Labels: Approved, sig/materialized view

#8391 [Feature] integrate starlet cache filesystem
  be/src/common/config.h
  be/src/fs/fs_starlet.cpp
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  be/test/fs/fs_starlet_test.cpp
  conf/be.conf
  run-ut.sh
Labels: Approved

#8599 [BugFix] Fix compile
  be/src/storage/lake/starlet_location_provider.cpp
Labels: Approved

#8608 [Lake] Add missing status include
  be/src/service/staros_worker.h
Labels: Approved

#8583 [BugFix] Fix lose cross join predicate when push down join predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinPredicateBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/multi_count_distinct.json
  fe/fe-core/src/test/resources/sql/query_dump/tpcds02.json
  fe/fe-core/src/test/resources/sql/query_dump/tpcds23_1.json
  fe/fe-core/src/test/resources/sql/query_dump/tpcds78.json
Labels: Approved

#8479 [Enhancement] Keep trailing zero if specified
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DecimalLiteralTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeDecimalV3Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTest.java
Labels: Approved

#8274 [BugFix] Fix no push_chunk() before set_finishing() in OlapTableSinkOperator
  be/src/exec/pipeline/olap_table_sink_operator.cpp
  be/src/exec/pipeline/olap_table_sink_operator.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: Approved

#8344 [Refactor] Refactor transaction stream load interface
  be/src/http/action/transaction_stream_load.cpp
  be/src/runtime/stream_load/transaction_mgr.cpp
  be/src/service/service_be/http_service.cpp
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
Labels: Approved

#8481 [Feature] display resource group info in explain verbose
  fe/fe-core/src/main/java/com/starrocks/catalog/WorkGroup.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailTest.java
Labels: Approved

#8607 [Enhancement] Reduce lock: locking once and reference it, not locking twice.
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: Approved

#7939 [Enhancement] Support multi-column global dictionary optimization
  be/src/connector/lake_connector.cpp
  be/src/exec/pipeline/scan/olap_scan_context.cpp
  be/src/exec/vectorized/olap_scan_node.cpp
  be/src/exprs/vectorized/dictmapping_expr.cpp
  be/src/exprs/vectorized/dictmapping_expr.h
  be/src/runtime/global_dict/parser.cpp
  be/src/runtime/global_dict/parser.h
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Projection.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/DictMappingOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/DictMappingRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorsReuse.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#8300 [BugFix] Check invalid window argument
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: Approved

#8603 [Feature] New Parser and Analyzer support SetUserPropertyStmt/ShowUserPropertyStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/SetUserPropertyStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowUserPropertyStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetUserPropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowUserPropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8602 [BugFix] Fix rate limit of tablet deletion
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
Labels: Approved

#8637 fixup avg(distinct non-decimal-type) bugs
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
Labels: Approved

#7877 [Feature] refresh materialized view when base tables are refreshed
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: Approved, sig/materialized view

#8241 [Enhancement] Slide window support removable cumulative algo
  be/src/exec/pipeline/analysis/analytic_sink_operator.cpp
  be/src/exec/vectorized/analytor.cpp
  be/src/exec/vectorized/analytor.h
  be/src/exprs/agg/aggregate.h
  be/src/exprs/agg/aggregate_factory.cpp
  be/src/exprs/agg/aggregate_factory.h
  be/src/exprs/agg/avg.h
  be/src/exprs/agg/count.h
  be/src/exprs/agg/nullable_aggregate.h
  be/src/exprs/agg/sum.h
  be/src/runtime/decimalv2_value.cpp
  be/src/runtime/decimalv2_value.h
  be/test/exprs/agg/aggregate_test.cpp
Labels: Approved

#8640 [enhancement][Materialized View]improve alter task logic of alter mv statement
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
Labels: Approved, sig/materialized view

#8636 [Enhancement] parquet coalsece reads support across row groups
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/util/buffered_stream.cpp
  be/src/util/buffered_stream.h
  be/test/exec/test_data/parquet_scanner/small_row_group_data.parquet
  be/test/exec/vectorized/hdfs_scanner_test.cpp
  be/test/formats/parquet/group_reader_test.cpp
Labels: Approved

#8621 [Feature] New Parser and Analyzer support ShowProcStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowProcStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowProcStmtTest.java
Labels: Approved

#8497 [Feature]Drop lake table
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/catalog/lake/ShardDeleter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/lake/ShardManager.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/ShardInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StarOSAgentTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/lake/ShardDeleterTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/EditLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ShardInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ShardManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  gensrc/proto/lake_service.proto
Labels: Approved

#8662 [BugFix] Fix unknown error when having clause has subquery
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: Approved

#8644 [Enhancment] Add MorselsCount and TabletCount to profile of scan operator
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/pipeline/source_operator.h
  be/src/exec/scan_node.cpp
  be/src/runtime/runtime_state.cpp
  be/src/util/runtime_profile.cpp
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
Labels: Approved

#8488 [Lake] Support lake table storage cache property
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/lake/StorageCacheInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/lake/StorageInfo.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TablesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/lake/LakeTableTest.java
Labels: Approved

#8653 [Feature] Support full statistics as default collect strategy
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AnalyzeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
Labels: Approved

#8596 [Lake] Refactor show command and internal process for lake table
  fe/fe-core/src/main/java/com/starrocks/analysis/AbstractBackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowReplicaDistributionStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowReplicaStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowDataStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowTabletStmt.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletMeta.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndicesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LocalTabletsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TableProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TabletsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AdminStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/lake/LakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/LakeTabletsProcNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/LocalTabletsProcDirTest.java
Labels: Approved

#8693 [Bugfix] use morsel_queue_factory before moving it
  be/src/exec/pipeline/fragment_executor.cpp
Labels: Approved

#8650 [BugFix] Fix bug of rename materialized view
  fe/fe-core/src/main/java/com/starrocks/analysis/TableName.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: sig/materialized view

#8688 [Enhancement] Delete shard and tablet when creating lake table fails
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#8482 [SR SQL Planner Summer Camp] Support create table like in new parser
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateTableLikeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableLikeAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateTableLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8720 Fix cmake errors on macOS
  be/CMakeLists.txt
Labels: Approved

#8495 [Enhancement] Keep dop of clone task handling in sync with fe scheduling
  be/src/agent/agent_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/common/config.h
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_clone_task.h
  be/src/util/threadpool.h
Labels: Approved

#8729 [BugFix] fix the case of dead workgroup
  fe/fe-core/src/main/java/com/starrocks/catalog/WorkGroupMgr.java
Labels: Approved

#8180 [Enhancement] More error logs
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/async_delta_writer.cpp
  be/src/storage/async_delta_writer.h
  be/src/storage/lake/async_delta_writer.cpp
Labels: Approved

#8777 [Doc] Mask Host
  docs/administration/Deployment.md
Labels: Approved

#8508 [SR SQL Planner Summer Camp] Support cancel alter in new parser
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/CancelAlterTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CancelAlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/BatchRollupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCancelAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8589 [Enhancement] Optimize default configuration which may cause balance problem
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/common/PropertyAnalyzerTest.java
Labels: Approved

#8527 [Refactor] rename work group to resource group
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/SetVar.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroup.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupClassifier.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/execution/AlterResourceGroupExecutor.java
  fe/fe-core/src/main/java/com/starrocks/execution/CreateResourceGroupExecutor.java
  fe/fe-core/src/main/java/com/starrocks/execution/DataDefinitionExecutorFactory.java
  fe/fe-core/src/main/java/com/starrocks/execution/DropResourceGroupExecutor.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/metric/ResourceGroupMetricMgr.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/ResourceGroupOpEntry.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetail.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/ResourceGroupMetricTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: Approved

#8728 [BugFix] fix bug in runtime filter plan
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_filter_worker.cpp
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/TPCDSCoordTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTestBase.java
Labels: Approved

#8824 [Refactor] Remove CreateTableStmt in old parser
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateTableStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColocateTableIndexTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateTableTest.java
Labels: Approved

#8823 [BugFix] Optimize 'DataUsedCapacity' display
  fe/fe-core/src/main/java/com/starrocks/common/util/DebugUtil.java
Labels: Approved

#8489 [SR SQL Planner Summer Camp] Support show partitions in new Parser and Analyzer
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowPartitionsStmt.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowPartitionsStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8820 [BugFix] BrokerLoad cann't handle kerberos login with multiple keytab
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: Approved

#8832 [Others] Remove unused test case
  be/test/storage/tablet_updates_test.cpp
Labels: Approved

#8841 [Actions] add documentation label for pr
  .github/workflows/add-pr-label.yml
Labels: Approved

#8833 [docs] Update release-2.3.md
  docs/release_notes/release-2.3.md
Labels: Approved

#8647 [BugFix] potential dead lock in stream_load_pipe
  be/src/runtime/stream_load/stream_load_pipe.cpp
  be/src/runtime/stream_load/stream_load_pipe.h
Labels: Approved

#8783 [Others] Add config for librdkafka debug
  be/src/common/config.h
  be/src/runtime/routine_load/data_consumer.cpp
Labels: Approved

#8771 [Enhancment] Assign tablet ranges for one-phase aggregate without partition and colocate
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: Approved

#8696 [Enhancement] Adjust downgrade strategy of chunks_partitioner
  be/src/exec/pipeline/sort/local_partition_topn_context.cpp
  be/src/exec/pipeline/sort/local_partition_topn_context.h
  be/src/exec/vectorized/partition/chunks_partitioner.cpp
  be/src/exec/vectorized/partition/chunks_partitioner.h
  be/src/exec/vectorized/partition/partition_hash_map.h
Labels: Approved

#8613 [Enhancement] Optimize logic of materialized view when base table is dropped
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/DmlException.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MvTaskRunProcessorTest.java
Labels: Approved, sig/materialized view

#8876 [UT] Fix unstable RollupJobV2Test
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
Labels: Approved

#8856 [Enhancement]mv task definition view
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
Labels: Approved, sig/materialized view

#8874 [docs] Update release-2.3.md
  docs/release_notes/release-2.3.md
Labels: documentation

#8511 [SR SQL Planner Summer Camp] Support ShowDynamicPartitionStmt in new parser
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowDynamicPartitionStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowDynamicPartitionStmtTest.java
Labels: Approved

#8671 [SR SQL Planner Summer Camp] New Parser and Analyzer support ShowProcesslistStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowProcesslistStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowProcesslistStmtTest.java
Labels: Approved

#8864 [docs] add navigation
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/introduction/what_is_starrocks.md
  docs/using_starrocks/Colocate_join.md
Labels: documentation, Approved

#8672 [Refactor] Support BDBJEJournal with prefix
  fe/fe-core/src/main/java/com/starrocks/journal/Journal.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/test/java/com/starrocks/journal/JournalWriterTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBEnvironmentTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJEJournalTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJournalCursorTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: Approved

#8805 [SR SQL Planner Summer Camp][Feature] alter table statement support of add list partition
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/PartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ListPartitionPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/PartitionPersistInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/RangePartitionPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: Approved

#8849 [BugFix] Fix crash during decoding min/max when type mismatch in parquet file
  be/src/connector/hive_connector.cpp
  be/src/exec/vectorized/hdfs_scanner.cpp
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/exec/vectorized/hdfs_scanner_orc.h
  be/src/exec/vectorized/hdfs_scanner_parquet.h
  be/src/exec/vectorized/hdfs_scanner_text.h
  be/src/exprs/expr.cpp
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/test/exec/test_data/parquet_scanner/type_mismatch_decode_min_max.parquet
  be/test/exec/vectorized/hdfs_scanner_test.cpp
Labels: Approved

#8597 [Refactor] Force reorder columns of chunk
  be/src/connector/hive_connector.cpp
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/test/storage/chunk_helper_test.cpp
Labels: Approved

#8884 [Refactor] Refactor hdfs scanner expression usage
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/vectorized/hdfs_scanner.cpp
  be/src/exec/vectorized/hdfs_scanner.h
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/formats/parquet/file_reader.h
  be/test/exec/vectorized/hdfs_scanner_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
Labels: Approved

#8840 [BugFix] Fix runtime filter delivery
  be/src/exec/exec_node.cpp
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/runtime_filter_cache.cpp
  be/src/runtime/runtime_filter_cache.h
  be/src/runtime/runtime_filter_worker.cpp
Labels: Approved

#7649 [Enhancement] introduce query debug trace for BE
  be/CMakeLists.txt
  be/src/common/config.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/util/CMakeLists.txt
  be/src/util/debug/query_trace.h
  be/src/util/debug/query_trace_impl.cpp
  be/src/util/debug/query_trace_impl.h
  build.sh
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: Approved

#8895 [Feature] display data_type in information_schema.columns for hll/bitmap/percentile
  be/src/exec/vectorized/schema_scanner/schema_columns_scanner.cpp
Labels: Approved

#8865 [Enhance] take the fragment prepare time into account of vruntime
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/fragment_executor.h
  be/src/service/internal_service.cpp
Labels: Approved

#8901 [Docs]delete two sql statements
  docs/TOC.md
  docs/sql-reference/sql-statements/Administration/ENTER.md
  docs/sql-reference/sql-statements/Administration/SHOW MIGRATIONS.md
Labels: documentation, Approved

#8893 [BugFix] Fix OlapTableSink close accelerate release resource
  be/src/exec/tablet_sink.cpp
Labels: Approved

#8858 [Bugfix] fix be crash when call DictMappingExpr::evaluate
  be/src/exprs/vectorized/dictmapping_expr.cpp
Labels: Approved

#8896 [BugFix] Fix consistency problem
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/runtime/data_stream_recvr.cc
Labels: Approved

#8872 Remove some old Analyzer codes 4
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BaseTableRef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BaseViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CreateViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FromClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/InPredicate.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IndexDef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LimitElement.java
  fe/fe-core/src/main/java/com/starrocks/analysis/QueryStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SelectStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Subquery.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableRef.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/planner/AnalyticEvalNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/Planner.java
  fe/fe-core/src/main/java/com/starrocks/planner/RollupSelector.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
Labels: Approved

#8862 [Refactor] Renaming constant variable in persistent index to obey our coding style, to improve readability.
  be/src/storage/persistent_index.cpp
Labels: Approved

#8633 [bug fix]fix TaskManager initialDelay not correct
  fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/test/java/com/starrocks/common/util/TimeUtilsTest.java
Labels: Approved, sig/materialized view

#8920 [Enhancement] ThreadPoolToken releasing the tasks outside of lock
  be/src/util/priority_queue.h
  be/src/util/threadpool.cpp
Labels: Approved

#8747 [Refactor] move state listener out of GlobalStateMgr, and rename it to state change executor
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/ha/BDBStateChangeListener.java
  fe/fe-core/src/main/java/com/starrocks/ha/StateChangeExecution.java
  fe/fe-core/src/main/java/com/starrocks/ha/StateChangeExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/ha/StateChangeExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedFrontend.java
Labels: Approved

#8886 [feature]Truncate lake table
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#8885 [Refactor] Use constant to indicate size of IndexValue and add a getter for kv_pair_size, and reduce a parameter.
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
Labels: Approved

#6238 introduce jemalloc into thirdparty
  be/CMakeLists.txt
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/jemalloc_hook.patch
Labels: Approved

#8918 [BugFix] Disable one stage aggregate with one distinct function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: Approved

#8953 [Refactor] [Step 1/2] Change the name from master to leader
  fe/fe-core/src/main/java/com/starrocks/analysis/RedirectStatus.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/ha/BDBHA.java
  fe/fe-core/src/main/java/com/starrocks/ha/HAProtocol.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/ColocateMetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/GlobalDictMetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowProcAction.java
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
  fe/fe-core/src/main/java/com/starrocks/leader/MetaHelper.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatResponse.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportExportingTask.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java
  fe/fe-core/src/main/java/com/starrocks/task/LeaderTask.java
  fe/fe-core/src/main/java/com/starrocks/task/LeaderTaskExecutor.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/task/LeaderTaskExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: Approved

#8937 [Enhancement] Add move constructor and move assignment for Schema
  be/src/column/schema.h
Labels: Approved

#8916 [Feature] histogram statistics support collect top-n data
  be/src/exprs/agg/aggregate_factory.cpp
  be/src/exprs/agg/histogram.h
  be/test/exprs/agg/aggregate_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/main/java/com/starrocks/statistic/TableCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
Labels: Approved

#8265 [BugFix] When the status of HeartBeat is not ok, it also need to be synced to follower
  fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/system/FrontendTest.java
Labels: Approved

#8963 [Refactor] Remove some unused code in old parser for admin stmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminSetReplicaStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowConfigStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowReplicaDistributionStmt.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AdminShowReplicaStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AdminStmtAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminShowReplicaTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/AdminStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AdminSetTest.java
Labels: Approved

#8869 [Bugfix] Fix wrong result when process 'is null' in condition expr in dictionary optimization
  be/src/runtime/global_dict/parser.cpp
  be/src/storage/column_operator_predicate.h
  be/src/storage/column_predicate_dict_conjuct.cpp
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/dictcode_column_iterator.cpp
  be/src/storage/rowset/dictcode_column_iterator.h
Labels: Approved

#8860 [Enhancement] Optimize materialized view refresh task by passing properties to task
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: Approved, sig/materialized view

#8977 [Lake] Create shard with cache property
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved

#8773 [BugFix] fix error of THRIFT_RPC_ERROR with CN
  be/src/service/backend_base.cpp
  be/src/service/backend_base.h
  be/src/service/service_be/backend_service.cpp
  be/src/service/service_be/backend_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/service/service_cn/compute_service.cpp
  be/src/service/service_cn/compute_service.h
  be/src/service/service_cn/starrocks_cn.cpp
Labels: Approved

#8503 [SR SQL Planner Summer Camp]New Parser and Analyzer support AlterUserStmt
  fe/fe-core/src/main/java/com/starrocks/analysis/AlterUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserAuthOption.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterUserStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: Approved

#8957 [Enhancement] Support rewrite window function sort partition by in lowcardinality optimization
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#8978 [BugFix] Fix LocalTabletsChannel head-use-after-free
  be/src/storage/async_delta_writer.cpp
  be/src/storage/async_delta_writer.h
  be/src/storage/delta_writer.cpp
Labels: Approved

#8335 [Enhancement] Remove redundant management on open db
  fe/fe-core/src/main/java/com/starrocks/journal/Journal.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBEnvironmentTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJEJournalTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJournalCursorTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: Approved

#8952 [Refactor] Extract common logics to function success_once
  be/src/storage/rowset/bitmap_index_reader.cpp
  be/src/storage/rowset/bitmap_index_reader.h
  be/src/storage/rowset/bloom_filter_index_reader.cpp
  be/src/storage/rowset/bloom_filter_index_reader.h
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/zone_map_index.cpp
  be/src/storage/rowset/zone_map_index.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
  be/src/util/once.h
Labels: Approved

#8892 [BugFix] check config: use_staros when register service from starMgr
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
Labels: Approved

#8976 [Bugfix] Label BackendExecState initiated for delivery in batch
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: Approved

#9003 Update Spark_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, Approved

#8532 [Enhancement] Bind un-correlate subquery with his predicate table
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSetType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyLeftProjectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyLeftRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TaskContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/TopDownRewriteTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q11.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q15.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch/q15.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q15.sql
Labels: Approved

#8866 [Refactor]Refactor mutable index implementation
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/persistent_index_test.cpp
Labels: Approved

#9004 [Enhancement] use heuristic method to handle left deep join
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinOrder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderLeftDeep.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTestBase.java
Labels: Approved

#8987 [Enhancement] support dynamically change slot per path conf
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
Labels: Approved

#8970 [Bug] fix call JNI function in bthread in UDAF when load class failed
  be/src/udf/java/java_udf.cpp
Labels: Approved

#8850 [Enhancement] Simple compaction scheduler for lake tables
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/ShardDeleter.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionDispatchDaemon.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionManager.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionPicker.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionPickerByCount.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionPickerByTime.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionIdentifier.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatistics.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/lake/ShardDeleterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionPickerByCountTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionPickerByTimeTest.java
Labels: Approved

#8946 [Bugfix] Fix the problem that dictionary optimization cannot get the dictionary after exceeding the cache capacity
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: Approved

#8726 [Feature]add support for be graceful exit
  be/src/agent/heartbeat_server.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/runtime/fragment_mgr.h
  be/src/service/CMakeLists.txt
  be/src/service/internal_service.cpp
  be/src/service/service.cpp
  be/src/service/service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/service/service_cn/starrocks_cn.cpp
  bin/stop_be.sh
Labels: Approved

#8922 [SR SQL Planner Summer Camp] Show char set planner
  fe/fe-core/src/main/java/com/starrocks/analysis/ShowCharsetStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCharsetStmtTest.java
Labels: Approved

#9015 [Feature] turn off the enable_shared_scan by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: Approved

#8925 [Enhancement] Clarify stream load commit rpc error message
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/util/thrift_rpc_helper.cpp
Labels: Approved

#9038 [BugFix] Fix password parse string error bug
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
Labels: Approved

#9019 [SR SQL Planner Summer Camp][Feature] alter table statement support of add list partition
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/PartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ListPartitionPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/PartitionPersistInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/RangePartitionPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: Approved

#9046 [Bugfix] fix "unsupport decode_dict_codes" error in late_materized
  be/src/storage/rowset/dictcode_column_iterator.cpp
  be/src/storage/rowset/dictcode_column_iterator.h
Labels: Approved

#9013 Branch 2.3
  docs/unloading/Spark_connector.md
Labels: documentation

#8950 [Bugfix] Fix DictMappingExpr rewrite multi times
  be/src/exprs/vectorized/dictmapping_expr.h
  be/src/runtime/global_dict/parser.cpp
Labels: Approved

#9057 Update Spark_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation

#9058 Update Spark_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation

#8879 [Bugfix] Persist the maps in mv
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedViewPartitionNameRefInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedViewPartitionVersionInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewGsonSerializationTest.java
Labels: Approved, sig/materialized view

#8999 [Enhancement] Add invisible session variable 'profile_timeout'
  fe/fe-core/src/main/java/com/starrocks/common/MarkedCountDownLatch.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: Approved

#8958 [Enhancement] Optimized statistics scheduling and not collecting empty tables and partitions
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved

#9043 Add compress debug info when disable minidump
  be/CMakeLists.txt
Labels: Approved

#9073 [Enhancement] Use object instead of pointer for HyperLogLog::_hash_set
  be/src/types/hll.cpp
  be/src/types/hll.h
Labels: Approved

#9092 [Doc]Update sql statement
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-definition/DROP TABLE.md
Labels: documentation

#9096 [Doc]update sql statements
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-definition/DROP TABLE.md
Labels: documentation
