Repository StarRocks/starrocks, pull requests merged in 2022-02, with the labels that each got.

#3235 improve TypeInfo::cmp performance
  be/src/storage/rowset/bitshuffle_page.h
  be/src/storage/rowset/plain_page.h
  be/src/storage/types.cpp
  be/src/storage/types.h
Labels: type/enhancement

#3417 Fix insert into outfile memory overflow in float type
  be/src/formats/csv/output_stream.h
  be/src/runtime/file_result_writer.cpp
  be/test/formats/csv/float_converter_test.cpp
Labels: type/bug

#3359 Refactor optimizer property
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/EnumeratePlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/GroupExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/DistributionSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/HashDistributionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/HashDistributionSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/EnforceAndCostTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecodeRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EnumeratePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/three-join.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q10.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q11.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q13.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q14.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q15.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q17.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q22.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q3.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q4.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q5.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q7.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q9.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q10.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q3.sql
Labels: sig/optimizer
