Repository StarRocks/starrocks, pull requests merged in 2022-01, with the labels that each got.

#2476 Move column serialize/deserialize to the outside of Column
  be/CMakeLists.txt
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/chunk.cpp
  be/src/column/chunk.h
  be/src/column/column.h
  be/src/column/const_column.cpp
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/column/vectorized_fwd.h
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/vectorized/join_hash_map.cpp
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/serde/CMakeLists.txt
  be/src/serde/column_array_serde.cpp
  be/src/serde/column_array_serde.h
  be/src/serde/protobuf_serde.cpp
  be/src/serde/protobuf_serde.h
  be/src/storage/rowset/beta_rowset_writer.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/storage/vectorized/row_source_mask.cpp
  be/test/CMakeLists.txt
  be/test/column/array_column_test.cpp
  be/test/column/binary_column_test.cpp
  be/test/column/chunk_test.cpp
  be/test/column/const_column_test.cpp
  be/test/column/fixed_length_column_test.cpp
  be/test/serde/column_array_serde_test.cpp
  be/test/serde/protobuf_serde_test.cpp
Labels: type/enhancement, Approved

#2617 Fix overflow in ColumnRange when extend scan key
  be/src/exec/olap_common.h
  be/test/exec/column_value_range_test.cpp
Labels: type/bug, Approved

#2568 Fix insert with limit miss top limit
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: Approved

#2614 Expression stats default compute return unknown instead of children stats
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: sig/optimizer

#2629 Fix date type distribution prune error with cast function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ColumnFilterConverter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
Labels: sig/optimizer

#2678 Add exec_mem_limit for stream load
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/stream_load/stream_load_context.cpp
  be/src/runtime/stream_load/stream_load_context.h
Labels: type/enhancement

#2692 Add mem restrict for chunk queue of FileScanNode
  be/src/exec/vectorized/file_scan_node.cpp
  be/src/exec/vectorized/file_scan_node.h
Labels: Approved

#2523 Update int = string common type use string
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: type/enhancement, Approved, sig/optimizer

#2744 don't check memory limit of load
  be/src/runtime/current_thread.h
  be/src/storage/memtable_flush_executor.cpp
  be/src/storage/rowset/page_io.cpp
  be/src/storage/vectorized/delta_writer.cpp
Labels: Approved

#2764 Fix: Analytor takes up too much reservation memory
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/analysis/analytic_sink_operator.h
  be/src/exec/pipeline/analysis/analytic_source_operator.h
  be/src/exec/pipeline/analysis/analytor_factory.cpp
  be/src/exec/pipeline/analysis/analytor_factory.h
  be/src/exec/vectorized/analytor.cpp
  be/src/exec/vectorized/analytor.h
Labels: type/enhancement

#2776 Delete duplicate parameters
  thirdparty/build-thirdparty.sh
Labels: Approved

#2600 Consider streaming mode and limit for multi distinct function extra costs compute
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsEstimateCoefficient.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/count_distinct_limit.json
Labels: sig/optimizer

#2834 To align hive plan with native plan
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
Labels: type/enhancement, Approved

#2702 Record required property in physical operator And remove useles code for shuffle bucket join
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/EnumeratePlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: sig/optimizer

#2916 Add more info for schema change reach mem limit
  be/src/runtime/mem_tracker.cpp
  be/src/runtime/mem_tracker.h
  be/src/runtime/runtime_state.h
  be/src/storage/task/engine_alter_tablet_task.cpp
  be/src/storage/vectorized/schema_change.cpp
Labels: Approved

#2900 Refactor primitive type
  fe/fe-core/src/main/java/com/starrocks/analysis/ArrayExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/NullLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TimestampArithmeticExpr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PrimitiveType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java
Labels: type/enhancement

#2936 Improve case when operator simplification
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CaseWhenOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentTest.java
Labels: Approved, sig/optimizer

#3011 Support array_agg
  be/src/exprs/agg/aggregate_factory.cpp
  be/src/exprs/agg/aggregate_factory.h
  be/src/exprs/agg/array_agg.h
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
Labels: Approved

#3058 support array_distinct
  be/src/exprs/agg/array_agg.h
  be/src/exprs/vectorized/array_functions.cpp
  be/src/exprs/vectorized/array_functions.h
  be/src/exprs/vectorized/array_functions.tpp
  gensrc/script/vectorized/vectorized_functions.py
Labels: Approved

#3089 JSON type infra
  be/CMakeLists.txt
  be/src/runtime/primitive_type.cpp
  be/src/storage/tablet_meta.cpp
  gensrc/thrift/Types.thrift
  run-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: Approved
