Repository StarRocks/starrocks, pull requests merged in 2023-09, with the labels that each got.

#29907 [Enhancement] array_agg supports distinct
  be/src/exec/aggregator.cpp
  be/src/exprs/agg/array_agg.h
  be/src/exprs/agg/factory/aggregate_resolver_avg.cpp
  be/test/exprs/agg/aggregate_test.cpp
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_agg_function/R/test_array_agg
  test/sql/test_agg_function/T/test_array_agg
Labels: documentation, 3.1

#30167 [BugFix] Fix decimalv2 to string different as BE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
Labels: 2.5, 3.0, 3.1

#30278 [BugFix] fix persistent index delete flag lost when flush l0 (backport #29997)
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/test/storage/persistent_index_test.cpp
Labels: automerge

#30271 [BugFix] Fix negative audit values
  be/src/runtime/query_statistics.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#30122 [BugFix] Return error if get_stub failed
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/runtime_filter_worker.cpp
  be/src/util/brpc_stub_cache.h
Labels: 2.5, 2.4, 3.0, 3.1, behavior_changed

#30134 [BugFix] fix count rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: sig/materialized view, 2.5, 3.0, 3.1

#30294 [BugFix] fix agg in order by not being analyzed correctly (backport #30108)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: automerge

#30295 [BugFix] fix comments not being discarded when to AST (backport #30210)
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: automerge

#30311 [Doc] Move param config content to BROKER LOAD
  docs/loading/cloud_storage_load.md
  docs/loading/hdfs_load.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#30318 [BugFix] fix unstable tests of array_agg
  test/sql/test_agg_function/R/test_array_agg
  test/sql/test_agg_function/T/test_array_agg
Labels: 3.1

#30284 [Enhancement] array_agg supports distinct (backport #29907)
  be/src/exec/aggregator.cpp
  be/src/exprs/agg/array_agg.h
  be/src/exprs/agg/factory/aggregate_resolver_avg.cpp
  be/test/exprs/agg/aggregate_test.cpp
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_agg_function/R/test_array_agg
  test/sql/test_agg_function/T/test_array_agg
Labels: documentation

#30106 [Feature] no longer support non-pipeline engine
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/DataSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/DecodeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/DeltaLakeScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/EmptySetNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/EsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExceptNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExportSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileTableScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/HudiScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/IntersectNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JDBCScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/MultiCastDataSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/MysqlScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/MysqlTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ProjectNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RepeatNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ResultSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/SelectNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/TableFunctionNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/UnionNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/stream/StreamAggNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/stream/StreamJoinNode.java
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
  test/sql/test_others/R/test_deprecated_non_pipeline_engine
  test/sql/test_others/T/test_deprecated_non_pipeline_engine
Labels: behavior_changed

#30306 [BugFix] fix the scenario of conflicted tasks after restarted
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
Labels: sig/materialized view, 2.5, 3.0, 3.1

#30314 [BugFix] Fix minor bug in asan mode
  be/src/exec/tablet_sink_colocate_sender.cpp
Labels: 3.1

#30293 [Enhancement] turn the MetadataMgr into a cache from map
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
Labels: 3.0, 3.1

#30332 [Doc] Delta lake its not maintained by Apache
  docs/data_source/catalog/deltalake_catalog.md
Labels: documentation

#30310 [BugFix] Fix decimalv2 to string different as BE (backport #30167)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
Labels: automerge

#30344 [Doc] Remove data types limits in Paimon catalog
  docs/data_source/catalog/paimon_catalog.md
Labels: documentation

#30145 [Feature] Support group-level queue with max_cpu_cores
  be/src/agent/CMakeLists.txt
  be/src/agent/resource_group_usage_recorder.cpp
  be/src/agent/resource_group_usage_recorder.h
  be/src/agent/task_worker_pool.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroup.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/qe/ColocatedBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/ResourceUsageMonitor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotRequestQueue.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowResourceGroupUsageStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/SchedulerTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  gensrc/thrift/ResourceUsage.thrift
  gensrc/thrift/WorkGroup.thrift
Labels: behavior_changed

#30347 [BugFix] close before destruct DataStreamRecvr
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/data_stream_recvr.h
Labels: 2.5, 3.0, 3.1

#29643 [Feature] Add new agg/window function 'approx_top_k'
  be/src/exec/analytor.cpp
  be/src/exec/analytor.h
  be/src/exprs/agg/approx_top_k.h
  be/src/exprs/agg/factory/aggregate_factory.hpp
  be/src/exprs/agg/factory/aggregate_resolver_approx.cpp
  be/src/exprs/agg/nullable_aggregate.h
  docs/sql-reference/sql-functions/aggregate-functions/approx_top_k.md
  fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ExprUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  test/common/sql/ssb/create.sql
  test/common/sql/tpcds/create.sql
  test/common/sql/tpch/create.sql
  test/sql/test_agg_function/R/test_approx_top_k
  test/sql/test_agg_function/T/test_approx_top_k
Labels: documentation

#30079 [BugFix] Fix RandomDistributionInfo persist bug
  fe/fe-core/src/main/java/com/starrocks/catalog/RandomDistributionInfo.java
Labels: 2.5, 3.0, 3.1

#30345 [Feature] broker load support parquet datetime in microsecond (backport #29996) (branch-2.5)
  be/src/exec/vectorized/arrow_to_starrocks_converter.cpp
  be/src/runtime/datetime_value.cpp
  be/src/runtime/datetime_value.h
  be/test/exec/test_data/parquet_data/datetime.parquet
  be/test/exec/test_data/parquet_data/generate_datetime.py
  be/test/exec/vectorized/parquet_scanner_test.cpp
Labels: automerge

#30368 [BugFix] close StreamMgr after FragmantMgr::close
  be/src/runtime/exec_env.cpp
Labels: 2.5, 3.0, 3.1

#30366 [BugFix] Modify a column that does not exist get NPE for primary key table (#30365)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: 2.5, 3.0, 3.1

#30387 [Feature] support any/all_match() for arrays (backport #24692)
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/src/exprs/array_functions.tpp
  be/test/exprs/array_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/all_match.md
  docs/sql-reference/sql-functions/array-functions/any_match.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: documentation

#30397 [Doc] Fix code formats in BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#30335 [Enhancement] remove be debuginfo file from the final be/cn/allin1 docker image
  docker/dockerfiles/allin1/allin1-ubi.Dockerfile
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
  docker/dockerfiles/be/be-ubi.Dockerfile
  docker/dockerfiles/be/be-ubuntu.Dockerfile
Labels: 2.5, 3.0, 3.1

#30242 [Enhancement] Enable partial update to be used with condition update
  be/src/storage/delta_writer.cpp
  be/src/storage/rowset_update_state.cpp
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/LoadStmt.java
  test/common/data/stream_load/sr_condition_update_1.csv
  test/common/data/stream_load/sr_condition_update_2.csv
  test/sql/test_condition_update/R/test_condition_update
  test/sql/test_condition_update/T/test_condition_update
Labels: behavior_changed

#30415 [Doc] delete .md in navigation page to avoid 404 in official web
  docs/introduction/StarRocks_intro.md
Labels: documentation, title needs [type]

#29164 [Feature] Support backup/restore for materialized view
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ForeignKeyConstraintTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/UnitTestUtil.java
Labels: sig/materialized view, behavior_changed

#30425 [Doc] add 2.5.12 rn
  docs/release_notes/release-2.5.md
Labels: documentation

#29793 [BugFix] Fix routine load task info null pointer exception
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaTaskInfo.java
Labels: behavior_changed

#29988 [Enhancement] Support convert equal range predicates into equivalence classes
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewMultiJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtilsTest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q12.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q6.sql
Labels: sig/materialized view, 3.1

#30410 [Enhancement] Remove DCHECK in es_predicate.cpp to avoid BE crashed in ASAN mode
  be/src/exec/es/es_predicate.cpp
Labels: 3.1

#30422 [Enhancement] improve cloud native pk table memory use and tracker
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/update_compaction_state.cpp
  be/src/storage/lake/update_compaction_state.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/primary_key_compaction_task_test.cpp
Labels: title needs [type]

#30407 [Feature] support for table-level primary index expire time
  be/src/agent/agent_task.cpp
  be/src/storage/base_tablet.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/update_manager.cpp
  be/src/storage/update_manager.h
  be/test/storage/persistent_index_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/UpdateTabletMetaInfoTask.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/MasterService.thrift
  test/sql/test_primary_index_cache_expire/R/test_primary_index_cache_expire
  test/sql/test_primary_index_cache_expire/T/test_primary_index_cache_expire
Labels: behavior_changed

#30430 [BugFix] fix alter mv's constraints bug
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
Labels: sig/materialized view, 2.5, 3.0, 3.1

#30263 [BugFix] when struct in array append_default real struct row for noexist subfiled
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/test/formats/parquet/test_data/array_struct.parquet
  test/sql/test_external_file/R/test_parquet_struct_in_array
  test/sql/test_external_file/T/test_parquet_struct_in_array
Labels: 3.0, 3.1

#30404 [BugFix] check table existence before heavy creating operation
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
Labels: 3.1

#30442 [Doc] fix linting issue array<bool>
  docs/sql-reference/sql-functions/array-functions/any_match.md
Labels: documentation, 3.1

#30461 [Doc] fix links
  docs/README.md
  docs/TOC.md
  docs/assets/commonMarkdown/insertPrivNote.md
  docs/loading/Spark-connector-starrocks.md
  docs/quick_start/Create_table.md
  docs/release_notes/release-2.1.md
  docs/release_notes/release-3.0.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-statements/generated_columns.md
Labels: documentation, 3.0, 3.1

#30428 [BugFix] Fix null_column handling for 'approx_top_k'
  be/src/exprs/agg/nullable_aggregate.h
Labels: 3.0, 3.1

#28408 [Doc] Runtime profile and text-based profile analysis
  docs/administration/query_profile.md
  docs/assets/profile-16.png
  docs/assets/profile-17.png
  docs/assets/profile-18.png
  docs/assets/profile-19.png
  docs/assets/profile-20.png
  docs/reference/System_variable.md
Labels: documentation, 3.1

#30460 [BugFix] Update the last modification field number to keep consistent with the main branch.
  gensrc/thrift/PlanNodes.thrift
Labels: 2.5

#29706 [Feature]Parallel execution of compaction tasks under one tablet
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/src/storage/compaction_task.cpp
  be/src/storage/compaction_task.h
  be/src/storage/rowset/rowset.h
  be/src/storage/size_tiered_compaction_policy.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/test/CMakeLists.txt
  be/test/storage/compaction_manager_test.cpp
  be/test/storage/compaction_parallelization_test.cpp
Labels: behavior_changed

#30456 [BugFix] Update the last modification field number to keep consistent with the main branch.
  gensrc/thrift/PlanNodes.thrift
Labels: 3.0

#30479 [BugFix] fix uncorrected simplify is null predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/InvertedCaseWhen.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithCaseWhenTest.java
  test/sql/test_case_when/R/test_case_when
  test/sql/test_case_when/T/test_case_when
Labels: 2.5, 3.0, 3.1

#30363 [Enhancement] Support ignoring invalid directories when listing hive directory recursively.
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/test/java/com/starrocks/connector/CachingRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteFileOperationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveStatisticsProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveWriteUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedRemoteFileSystem.java
Labels: 3.0, 3.1

#30457 [BugFix] Some potential bugfix
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/lake_local_persistent_index.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/rowset/page_decoder.h
Labels: 3.1

#30424 [BugFix] Fix BE crash when enable filter_unused_columns and dictionary inconsistent
  be/src/storage/rowset/segment_iterator.cpp
  be/test/storage/rowset/segment_iterator_test.cpp
Labels: 2.5, 3.0, 3.1

#30276 [Enhancement] Enable force_external_table_query_rewrite to support rewrite hive table by default
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteNestedMVTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteSingleTableTest.java
Labels: behavior_changed

#30508 [Doc] fix linting add codeph to array<bool>
  docs/sql-reference/sql-functions/array-functions/any_match.md
Labels: documentation, 3.1

#30502 [BugFix] Fix metatool total kv and bytes not match item sum
  be/src/storage/rowset/rowset_meta_manager.cpp
  be/src/storage/tablet_meta_manager.cpp
  be/src/tools/meta_tool.cpp
Labels: 2.5, 3.0, 3.1

#30382 [BugFix] fix range predicate rewrite by canonicalization
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRangePredicate.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ConstantOperatorDiscreteDomain.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/ConstantOperatorTest.java
Labels: 2.5, 3.0, 3.1

#30367 [BugFix] Remove isAssignedStrLenInColDefinition parameter in ScalarType
  fe/fe-core/src/main/java/com/starrocks/analysis/CastExpr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnDef.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.1

#30524 [BugFix] unify cast decimal to string between FE and BE (backport #30464)
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: automerge

#30463 [Enhancement] Add more case and enhanced metadata partition repair capabilities
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  test/sql/test_insert_empty/R/test_insert_overwrite_partition
  test/sql/test_insert_empty/T/test_insert_overwrite_partition
Labels: 3.0, 3.1

#30529 [BugFix] fix uncorrected simplify is null predicate (backport #30479)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/InvertedCaseWhen.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithCaseWhenTest.java
Labels: automerge

#30341 [Refactor] deprecate enable_pipeline_load
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/planner/DataSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/load/LoadPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/JobSpecTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PipelineParallelismTest.java
Labels: behavior_changed

#30520 [BugFix] sync paimon type nullable logic
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
Labels: 3.1, behavior_changed

#30538 [Enhancement] Support ignoring invalid directories when list hive directory recursively. (#30363)
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/test/java/com/starrocks/connector/CachingRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteFileOperationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveStatisticsProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedRemoteFileSystem.java
Labels: 2.5, 3.0, 3.1

#30537 [Doc] update desc for how to configure memory size for fe
  docs/faq/Others.md
Labels: documentation

#30560 [Doc] Fix typo in cloud storage load doc
  docs/loading/cloud_storage_load.md
Labels: documentation

#30526 [BugFix] Use default priority for publish version tasks to avoid starving abort tasks
  be/src/service/service_be/lake_service.cpp
Labels: 3.1

#30531 [BugFix] Fix primary key alter sort key bug
  be/src/storage/schema_change.cpp
  test/sql/test_ddl/R/alter_table
  test/sql/test_ddl/T/alter_table
Labels: 3.0, 3.1

#30574 [Doc] remove sentence that cause linting error
  docs/sql-reference/sql-functions/array-functions/any_match.md
Labels: documentation, 3.1

#27907 [Feature] improve hash join performance by coroutine-based interleaving
  be/CMakeLists.txt
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/src/exec/pipeline/hashjoin/hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/hash_join_build_operator.h
  be/test/exec/join_hash_map_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: documentation

#30381 [Enhancement] Refine profile to support visualization refactor(2)
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/pipeline_driver_executor.h
  be/src/exec/spill/spiller.cpp
  be/src/exec/spill/spiller.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
  gensrc/thrift/InternalService.thrift
Labels: 3.1

#30488 [refactor] refactor AnalyzeJob to NativeAnalyzeJob
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateAnalyzeJobStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeJobStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/NativeAnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateAnalyzeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/AnalyzeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: title needs [type]

#30593 [Doc] Update Replica.md
  docs/administration/Replica.md
Labels: documentation, 2.5, 2.4, 3.0, 3.1

#30595 [BugFix] ban iceberg eq-delete
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: 3.0, 3.1

#30573 [BugFix] copy partitionInfo to a new map
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/RangePartitionInfoTest.java
Labels: 3.0, 3.1

#30597 [Doc] modify version info or any/all_match and cp to 3.0
  docs/sql-reference/sql-functions/array-functions/all_match.md
  docs/sql-reference/sql-functions/array-functions/any_match.md
Labels: documentation, 3.0, 3.1

#30433 [BugFix] Fix source_scan_bytes compability with 3.0
  gensrc/thrift/FrontendService.thrift
Labels: 3.1

#30623 [Doc] add any/all_match to func list
  docs/sql-reference/sql-functions/array-functions/any_match.md
  docs/sql-reference/sql-functions/function-list.md
Labels: documentation

#29422 [BugFix] fix mv on hive view
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: sig/materialized view, 2.5, 3.0, 3.1

#29906 [Feature] support SecurityManager for UDF
  be/CMakeLists.txt
  be/src/exec/pipeline/exchange/local_exchange.h
  be/src/udf/java/java_udf.cpp
  be/src/udf/java/java_udf.h
  build.sh
  conf/fe.conf
  conf/udf_security.policy
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateFunctionStmt.java
  java-extensions/udf-extensions/pom.xml
  java-extensions/udf-extensions/src/main/java/com/starrocks/udf/UDFClassLoader.java
  java-extensions/udf-extensions/src/main/java/com/starrocks/udf/UDFSecurityManager.java
  java-extensions/udf-extensions/src/test/java/com/starrocks/udf/SecurityTest.java
  java-extensions/udf-extensions/src/test/resources/PermissionCheck.policy
Labels: behavior_changed

#30615 [BugFix] remove varchar length check for jdbc scanner
  be/src/exec/jdbc_scanner.cpp
Labels: 3.0, 3.1

#30491 [Enhancement] Improve backward compatibility of storage volume
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1

#30642 [BugFix][cherry-pick][branch-2.5] orc skip data when rowIndexes empty
  be/src/formats/orc/apache-orc/c++/src/sargs/SargsApplier.cc
Labels: automerge

#30626 [BugFix] Fix lost resource group in audit log for insert
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupClassifier.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupMgrTest.java
Labels: 2.5, 2.4, 3.0, 3.1

#30625 [BugFix] remove orphan rowset meta during BE restart and trash sweep
  be/src/common/config.h
  be/src/storage/data_dir.cpp
  be/src/storage/storage_engine.cpp
Labels: 2.5, 3.0, 3.1

#30658 [Doc] fix typo in Update cloud_storage_load.md
  docs/loading/cloud_storage_load.md
Labels: documentation

#30657 [Doc] fix typo in Update hdfs_load.md
  docs/loading/hdfs_load.md
Labels: documentation

#30499 [Enhancement] Get rid of the database readlock when updateBackendReportVersion
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 2.5, 3.0, 3.1, behavior_changed

#30646 [BugFix] Fix negative audit
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
Labels: 2.5, 3.0, 3.1

#30659 [Enhancement] Remove unneccessary log in batch delete of vacuum
  be/src/storage/lake/vacuum.cpp
Labels: 3.1

#30635 [BugFix] Fix compaction jobs getting stuck when abortCompaction RPC fails
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionTask.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionTaskTest.java
Labels: 3.1

#30685 [Doc] Add short desc to auth to aws doc
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#29283 [Feature] Support unified catalog
  fe/fe-core/src/main/java/com/starrocks/catalog/DeltaLakeTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorType.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/unified/UnifiedConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/unified/UnifiedMetadata.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/com/starrocks/planner/DeltaLakeScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/unified/UnifiedConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/unified/UnifiedMetadataTest.java
Labels: behavior_changed

#30603 [BugFix] Lost replica by mistake on BE if tablet meta checkpoint and restore executed concurrently (#30588)
  be/src/runtime/snapshot_loader.cpp
  be/src/storage/tablet.h
Labels: 2.5, 3.0, 3.1

#30664 [Tool] Add benchmark case for BinaryColumn copy
  be/src/bench/CMakeLists.txt
  be/src/bench/binary_column_copy_bench.cpp
Labels: behavior_changed

#30419 [Enhancement] Support overflow mode for decimal type
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_operation.h
  be/src/exprs/cast_expr.cpp
  be/src/exprs/decimal_binary_function.h
  be/src/exprs/decimal_cast_expr.h
  be/src/exprs/expr_context.cpp
  be/src/exprs/expr_context.h
  be/src/exprs/function_context.cpp
  be/src/exprs/function_context.h
  be/src/exprs/math_functions.h
  be/src/exprs/overflow.h
  be/src/runtime/runtime_state.h
  be/test/exprs/decimal_binary_function_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SqlModeHelper.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_decimal/R/test_decimal_overflow
  test/sql/test_decimal/T/test_decimal_overflow
Labels: 2.5, 3.0, 3.1

#30701 [Doc] Deprecate two params from and add query_timeout to load overview doc
  docs/loading/Loading_intro.md
Labels: documentation

#30705 [BugFix] Fix parquet compile failed in gcc-12
  be/src/formats/parquet/column_read_order_ctx.h
Labels: 3.1

#30532 [Enhancement]support paimon version 0.5
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/PaimonScanNodeTest.java
  java-extensions/paimon-reader/pom.xml
Labels: 3.1, behavior_changed

#30714 Update curdate.md
  docs/sql-reference/sql-functions/date-time-functions/curdate.md
Labels: documentation, title needs [type]

#30739 [BugFix] ensure a valid cast clause for MySQL/JDBC table (backport #23379)
  fe/fe-core/src/main/java/com/starrocks/analysis/CastExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateToExternalTableScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MySQLTableCastTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
Labels: automerge

#30702 [Enhancement] No need to build_slice for get data from BinaryColumn
  be/src/util/arrow/starrocks_column_to_arrow.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#30692 [BugFix] BugFix AccessPath construction
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldAccessPathNormalizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
Labels: 3.0, 3.1

#30727 [BugFix] remove unused partition column from chunk for hudi mor table
  be/src/exec/jni_scanner.cpp
Labels: 3.0, 3.1

#30750 [Doc] Update role desc&name in auth to aws
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#30730 [Doc] Deprecate two params from and add query_timeout to load overview doc
  docs/loading/Loading_intro.md
Labels: documentation

#30582 [Feature]Support get paimon table createtime
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: behavior_changed

#30751 [BugFix] Fix them mem statistics bug of MemoryScratchSink
  be/src/exec/pipeline/sink/memory_scratch_sink_operator.cpp
  be/src/runtime/memory_scratch_sink.cpp
  be/src/util/arrow/starrocks_column_to_arrow.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#30308 [Doc]add new features in spark connector 1.1.1
  docs/loading/Spark-connector-starrocks.md
  docs/unloading/Spark_connector.md
Labels: documentation

#30716 [BugFix]Fix paimon table column can not be nullable
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.1

#30772 [Doc] Remove tablet_writer_rpc_timeout_sec
  docs/faq/loading/Insert_into_faq.md
Labels: documentation, 2.5, 3.0, 3.1

#30446 [Feature] Add compaction grafana metric
  be/src/http/action/compaction_action.cpp
  be/src/storage/base_compaction.cpp
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_task.cpp
  be/src/storage/cumulative_compaction.cpp
  be/src/storage/rowset_merger.cpp
  be/src/storage/storage_engine.cpp
  be/src/util/starrocks_metrics.cpp
  be/src/util/starrocks_metrics.h
Labels: behavior_changed

#30787 [Doc] update data cache, classic mode word usage, and unit
  docs/TOC.md
  docs/administration/Configuration.md
  docs/administration/Monitor_and_Alert.md
  docs/data_source/data_cache.md
  docs/deployment/deploy_manually.md
  docs/deployment/deploy_shared_data.md
  docs/deployment/deployment_overview.md
Labels: documentation, 3.0, 3.1, 3.2

#30803 [BugFix] Fix hive view authorization
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
Labels: 3.2

#30814 [Doc] Add missing docs for the flink version 1.2.8
  docs/loading/Flink-connector-starrocks.md
  docs/unloading/Flink_connector.md
Labels: documentation

#30799 [BugFix] Fix bug column default null convert to \N
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowColumnStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
  test/sql/test_information_schema/R/test_column
  test/sql/test_information_schema/T/test_column
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#30796 [BugFix] check return status of expression
  be/src/exec/aggregate/aggregate_blocking_node.cpp
  be/src/exec/aggregate/distinct_blocking_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exprs/expr.h
  be/src/exprs/expr_context.h
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/formats/csv/json_converter.h
  be/src/util/json_converter.h
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/json_parser_test.cpp
  be/test/exprs/json_functions_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
Labels: 3.2

#30706 [Enhancement] Handle returned status (DLA part)
  be/src/connector/es_connector.cpp
  be/src/connector/jdbc_connector.cpp
  be/src/connector/mysql_connector.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_file_iterator.cpp
  be/src/exec/iceberg/iceberg_delete_file_iterator.h
  be/src/exec/orc_scanner.cpp
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_writer.cpp
  be/src/exec/parquet_writer.h
  be/src/exec/pipeline/sink/hive_table_sink_operator.cpp
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/page_reader.cpp
  be/src/formats/parquet/stored_column_reader.cpp
  be/src/runtime/jdbc_driver_manager.cpp
  be/src/util/arrow/row_batch.cpp
Labels: 3.2

#30589 [Enhancement][BugFix] fix the problem that the spill dir cannot be deleted when the query exits abnormally
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/scan/balanced_chunk_buffer.cpp
  be/src/exec/pipeline/scan/balanced_chunk_buffer.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exec/pipeline/scan/meta_scan_operator.cpp
  be/src/exec/pipeline/scan/meta_scan_operator.h
  be/src/exec/pipeline/scan/olap_meta_scan_operator.cpp
  be/src/exec/pipeline/scan/olap_meta_scan_operator.h
  be/src/exec/pipeline/scan/olap_scan_operator.cpp
  be/src/exec/pipeline/scan/olap_scan_operator.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/pipeline/scan/schema_scan_operator.cpp
  be/src/exec/pipeline/scan/schema_scan_operator.h
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/mem_table.cpp
  be/src/exec/spill/spiller.cpp
  be/src/exec/spill/spiller.h
  be/src/exec/spill/spiller.hpp
  be/src/runtime/local_pass_through_buffer.cpp
  be/src/runtime/local_pass_through_buffer.h
Labels: 3.0, 3.1

#30817 [BugFix]Fix paimon table struct type
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonColumnValue.java
Labels: 3.1, 3.2

#30837 [Enhancement] Use query timeout as information schema rpc timeout
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.h
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  be/src/exec/schema_scanner/schema_schemata_scanner.cpp
  be/src/exec/schema_scanner/schema_tables_scanner.cpp
  be/src/exec/schema_scanner/schema_views_scanner.cpp
  be/src/exec/schema_scanner/schema_views_scanner.h
Labels: 3.2

#30694 [Enhancement]refactor default repliction num calculation rule for statistic tables
  fe/fe-core/src/main/java/com/starrocks/common/util/AutoInferUtil.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoCreator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/test/java/com/starrocks/common/util/AutoInferUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsSQLTest.java
Labels: 3.1

#30592 [Enhancement] add api/feature rest api
  fe/fe-core/src/main/java/com/starrocks/feature/ProductFeature.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/FeatureAction.java
  fe/fe-core/src/test/java/com/starrocks/feature/ProductFeatureTest.java
  fe/fe-core/src/test/java/com/starrocks/http/FeatureActionTest.java
Labels: behavior_changed

#30773 [Doc] add 3.0.6 rn
  docs/release_notes/release-3.0.md
Labels: documentation

#30887 [Doc] replace <> with &lt; and &gt; to avoid failure of synchronzing docs from repo to web
  docs/loading/Flink-connector-starrocks.md
Labels: documentation

#30886 [Doc] fixing linting errors in replica
  docs/administration/Replica.md
Labels: documentation, 3.0, 3.1, 3.2

#30882 [Doc] ] fixing linting errors in connectors
  docs/loading/Flink-connector-starrocks.md
  docs/loading/Spark-connector-starrocks.md
  docs/unloading/Spark_connector.md
Labels: documentation

#30896 [Doc] Correct syntax of Tabular credential
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation, 3.0, 3.1, 3.2

#30775 [Doc] Add support for JDK 11
  docs/deployment/deployment_prerequisites.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#30877 [BugFix][Cherry-Pick] Fix bug column default null convert to \N
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: automerge

#30833 [BugFix] Fix lost resource group in audit log for insert (#30626 #30726)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/qe/LeaderOpExecutorTest.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 2.4, 3.0, 3.1

#30834 [BugFix] Fix lost resource group in audit log for insert (#30626 #30726)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/qe/LeaderOpExecutorTest.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 2.4, 3.0

#30693 [Enhancement] extend configuration and metrics for pipe_prepare_pool
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/util/starrocks_metrics.h
  docs/administration/Monitor_and_Alert.md
Labels: documentation, 3.1, 3.2

#30890 [Enhancement] return more accurate logs when accessing hdfs fails
  be/src/fs/hdfs/fs_hdfs.cpp
Labels: 3.1, 3.2

#30855 [Enhancement] spark/flink connector export data without using column pool
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  gensrc/thrift/InternalService.thrift
Labels: 2.5, 3.0, 3.1, 3.2

#30942 [Doc] fix linting in data cache
  docs/data_source/data_cache.md
  docs/loading/Spark-connector-starrocks.md
Labels: documentation, 3.0, 3.1, 3.2

#27840 [Feature] support prepare statement
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/exec/pipeline/result_sink_operator.h
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/mysql_result_writer.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_sink.h
  be/src/util/mysql_global.h
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  fe/fe-core/src/main/java/com/starrocks/analysis/DateLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IntLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Parameter.java
  fe/fe-core/src/main/java/com/starrocks/analysis/StringLiteral.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/PrepareStmtContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrepareAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DeallocateStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExecuteStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PrepareStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
  gensrc/thrift/DataSinks.thrift
  test/sql/test_preparestatement/R/test_preprare_statement
  test/sql/test_preparestatement/T/test_preprare_statement
Labels: documentation

#30504 [BugFix] refactor cloud native pk table publish & fix local persistent index usage
  be/src/storage/lake/lake_local_persistent_index.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/persistent_index.h
  be/test/storage/lake/condition_update_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/test_util.h
Labels: 3.1, 3.2

#30829 [BugFix] Shutdown update manager & tracer during BE and UT exit
  be/src/common/tracer.cpp
  be/src/common/tracer.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/update_manager.cpp
  be/src/storage/update_manager.h
  be/src/testutil/init_test_env.h
Labels: 3.0, 3.1, 3.2

#30881 [BugFix] Fix complex distinct query use CTE error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#30971 [Doc] Fix linting logic
  docs/.markdownlint.yaml
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#30850 [Doc] Add some profile metrics
  docs/administration/query_profile.md
Labels: documentation, 3.1, 3.2

#31021 [Doc] reformat system variables to help with Algolia indexing
  docs/reference/System_variable.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#31011 [Refactor] Remove old broker load planner
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadingTaskPlannerTest.java
Labels: behavior_changed

#31027 [cherry-pick][branch-3.1][Feature] support lzo block decompression
  be/src/util/compression/block_compression.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/test_data/parquet_scanner/lzo_compression.parquet
  test/sql/test_external_file/R/test_csv_compression_format
  test/sql/test_external_file/R/test_parquet_compression_format
  test/sql/test_external_file/T/test_csv_compression_format
  test/sql/test_external_file/T/test_parquet_compression_format
Labels: title needs [type]

#31014 [BugFix] throw exception when insert into hive table without parquet format
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
  fe/fe-core/src/test/java/com/starrocks/planner/HiveTableSinkTest.java
Labels: 3.2

#30876 [BugFix] fix subquery check in join on predicate
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ParserErrorMsg.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  test/sql/test_join/R/test_apply_to_join
  test/sql/test_join/T/test_apply_to_join
Labels: 2.5, 3.0, 3.1, 3.2

#30959 [Enhancement] update staros components to 3.2-rc1
  be/CMakeLists.txt
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
Labels: 3.2

#30663 [BugFix] Support audit for insert into statement executing from follower
  be/src/exec/pipeline/olap_table_sink_operator.cpp
  be/src/exec/pipeline/olap_table_sink_operator.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/exec/pipeline/result_sink_operator.h
  be/src/exec/pipeline/sink/export_sink_operator.cpp
  be/src/exec/pipeline/sink/export_sink_operator.h
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.h
  be/src/exec/pipeline/sink/memory_scratch_sink_operator.cpp
  be/src/exec/pipeline/sink/memory_scratch_sink_operator.h
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  fe/fe-core/src/main/java/com/starrocks/common/util/AuditStatisticsUtil.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 3.0, 3.1

#30998 [Enhancement] Remove the get schema call in TabletReader.
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/lake/tablet_reader.h
Labels: 3.1, 3.2

#31032 [cherry-pick][branch-3.2][Feature] support snappy stream compression (#30604)
  be/src/exec/hdfs_scanner_text.cpp
  be/src/io/compressed_input_stream.cpp
  be/src/util/coding.h
  be/src/util/compression/stream_compression.cpp
  be/test/exec/test_data/csv_scanner/decompress_test0.csv.snappy
  be/test/exec/test_data/csv_scanner/decompress_test1.csv.snappy
  be/test/io/compressed_input_stream_test.cpp
  test/sql/test_external_file/R/test_csv_compression_format
  test/sql/test_external_file/T/test_csv_compression_format
Labels: title needs [type]

#30936 [Enhancement] extend configuration and metrics for pipe_prepare_pool (#30693)
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/util/starrocks_metrics.h
  docs/administration/Monitor_and_Alert.md
Labels: documentation
