Repository StarRocks/starrocks, pull requests merged in 2023-11, with the labels that each got.

#34094 [BugFix] Revert "[Feature] Arithmetic expression JIT (#28477)"
  be/CMakeLists.txt
  be/src/common/status.h
  be/src/exec/aggregator.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_operation.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/jit/ir_helper.cpp
  be/src/exprs/jit/ir_helper.h
  be/src/exprs/jit/jit_expr.cpp
  be/src/exprs/jit/jit_expr.h
  be/src/exprs/jit/jit_functions.cpp
  be/src/exprs/jit/jit_functions.h
  be/src/exprs/jit/jit_wrapper.cpp
  be/src/exprs/jit/jit_wrapper.h
  be/src/exprs/literal.cpp
  be/src/exprs/literal.h
  be/src/testutil/exprs_test_helper.h
  be/src/types/logical_type.h
  be/test/exprs/arithmetic_expr_test.cpp
  build.sh
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/Exprs.thrift
  gensrc/thrift/InternalService.thrift
  gensrc/thrift/Opcodes.thrift
  gensrc/thrift/StatusCode.thrift
  test/sql/test_jit/R/test_arithmetic
  test/sql/test_jit/T/test_arithmetic
  thirdparty/build-thirdparty.sh
Labels: PROTO-REVIEW

#33789 [BugFix]Fix paimon array NPE exception and deciaml type scale issue
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonColumnValue.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonTypeUtils.java
Labels: 3.2

#33977 [Enhancement] optimize the log when creating table
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 3.0, 3.1, 3.2

#34100 [BugFix] Skip transaction for files sink
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.2

#34109 [Doc] MV docs minor fix
  docs/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#33749 [Enhancement] update distribution info using projection
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q18.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q20.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/agg_with_having3.json
Labels: 3.2

#34033 [Enhancement] Supports modifying the version to take effect without restarting
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminSetConfigStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#34062 [BugFix] exception when migrate empty tablet for primary key table (#34061)
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
Labels: 3.2

#33737 [Enhancement] support statistics for iceberg table and optimize statistics calculation 
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergFileStats.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/DeriveRangeJoinPredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.2

#34140 [BugFix] fix concurrency modify propertyInfo in empty PhysicalPropertySet
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
Labels: 2.5, 3.0, 3.1

#34059 [BugFix] fix format error when create table with invalid sort key
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AlterTableClauseVisitorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CreateTableAnalyzerTest.java
Labels: 3.1, 3.2

#33856 [Enhancement] Add more log info when ingestion failure caused by lost replica
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/LocalTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#34173 [Enhancement][Cherry-Pick] Supports modifying the version to take effect without restarting
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminSetConfigStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 2.5

#34160 [BugFix] fix inverted condition compile
  be/src/storage/storage_engine.cpp
Labels: 3.1, 3.2

#34101 [Enhancement] Instead of throwing an exception, create a log to prevent FE rollback startup failure.
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfoV2.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionRangePartitionInfoTest.java
Labels: 3.0, 3.1, 3.2

#34170 [Doc] sr shared data cluster supports persistent index for pk table
  docs/table_design/table_types/primary_key_table.md
Labels: documentation

#33902 [BugFix] Make unique/foreign key constraints case insensitive
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/common/util/StringUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: 3.1, 3.2

#34186 [Enhancement][Cherry-Pick] Supports modifying the version to take effect without restarting
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminSetConfigStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: automerge

#34172 [BugFix] fix close shared conjuncts in FileDataSource
  be/src/connector/file_connector.cpp
Labels: 3.0, 3.1, behavior_changed, 3.2

#34181 [BugFix] fix FragmentMgr dead lock in close()
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/test/runtime/fragment_mgr_test.cpp
Labels: 3.2

#34195 [Doc] update version info for window func
  docs/sql-reference/sql-functions/Window_function.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#34202 [Refactor] disable column pool by default
  be/src/common/config.h
  docs/administration/Configuration.md
Labels: documentation, behavior_changed

#34207 [Doc] update separator in group_concat and fix mv in grant syntax
  docs/deployment/shared_data/s3.md
  docs/release_notes/release-3.1.md
  docs/sql-reference/sql-functions/string-functions/group_concat.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation, 3.0, 3.1, 3.2

#34149 [BugFix][Enhancement] optimize mv plan cache and fix npe
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.0, 3.1, 3.2

#34185 [Enhancement] Improve aborting transactions in shared data mode
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/service/lake_service_test.cpp
Labels: 3.1, 3.2

#34236 [Doc] Added 3.1.4 release notes
  docs/release_notes/release-3.1.md
Labels: documentation

#30319 [Feature] Support dynamic partition pruning
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/jni_scanner.h
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/formats/parquet/file_reader.cpp
  be/test/exec/hdfs_scanner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#34243 [Doc] Rename other integrations doc.
  docs/integrations/other_integrations/intro.md
Labels: documentation

#33688 [Feature] Add cloud native persistent index type
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  gensrc/proto/lake_types.proto
  gensrc/thrift/AgentService.thrift
Labels: PROTO-REVIEW

#33838 [Enhancement] counting semaphore used in bthread
  be/src/util/bthreads/semaphore.h
  be/src/util/bthreads/util.h
  be/test/CMakeLists.txt
  be/test/util/bthreads/semaphore_test.cpp
Labels: 3.1, 3.2

#33992 [Enhancement] Remove hdfs storage volume params check
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.2

#34204 [BugFix] Fix array expr meet constant-column error
  be/src/exprs/array_expr.cpp
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
Labels: 3.0, 3.1, 3.2

#34178 [BugFix] Fix forward compatibility for newly added PEntryObject type
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/privilege/RolePrivilegeCollectionV2.java
  fe/fe-core/src/test/java/com/starrocks/privilege/AuthorizationMgrTest.java
Labels: 3.2

#34201 [BugFix] Build curl without brotli
  thirdparty/build-thirdparty.sh
Labels: 3.2

#34187 [Feature] Revert "[Feature] support cloud table schema change using different shard group (#33642)"
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: META-REVIEW

#34259 [Doc] fix format in 3.1.4 release notes
  docs/release_notes/release-3.1.md
Labels: documentation

#34060 [BugFix] Expr prepare() should do only once
  be/src/exprs/lambda_function.cpp
  be/src/exprs/lambda_function.h
  be/src/exprs/map_apply_expr.cpp
  be/src/exprs/map_apply_expr.h
  test/sql/test_join/R/test_join_array
  test/sql/test_join/R/test_join_map
  test/sql/test_join/R/test_join_struct
  test/sql/test_join/T/test_join_array
  test/sql/test_join/T/test_join_map
  test/sql/test_join/T/test_join_struct
Labels: 2.5, 3.0, 3.1, 3.2

#34260 [Enhancement] remove predicate column id in IcebergFilter
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergFilter.java
Labels: 3.1, 3.2

#34267 [BugFix] Fix select ORC MapVector's filter nullptr bug
  be/src/formats/orc/apache-orc/c++/src/Vector.cc
  be/src/storage/lake/key_index.h
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/test_data/orc_scanner/map_filter_bug.orc
Labels: 2.5, 3.0, 3.1, 3.2

#34272 [BugFix] Fix creating jdbc resource blocks with lock acquired
  fe/fe-core/src/main/java/com/starrocks/catalog/JDBCResource.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceMgr.java
Labels: 3.0, 3.1, 3.2

#34298 [Doc] Update file format support in Hive catalog and file external table in v3.2
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/file_external_table.md
Labels: documentation

#34034 [Enhancement] optimize agg cost model
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPushAggTest.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q11.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q13.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q21.sql
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q3.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q11.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q13.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q22.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q22.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/constant-query.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/grouping-sets.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/predicate-pushdown.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/select.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/set-operation.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/window.sql
  fe/fe-core/src/test/resources/sql/query_dump/two_stage_agg.json
  fe/fe-core/src/test/resources/sql/scheduler/tpch/q11.sql
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q13.sql
  fe/fe-core/src/test/resources/sql/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/tpch/q11.sql
  fe/fe-core/src/test/resources/sql/tpch/q13.sql
  fe/fe-core/src/test/resources/sql/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q13.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q21.sql
Labels: 3.2

#34226 [BugFix] Fix hive partition not in no eval conjuncts with OR predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HivePartitionPruneTest.java
Labels: good first issue, 2.5, 3.0, 3.1, 3.2

#34327 [BugFix] include more info when compation output verification failed
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34328 [Enhancement] Implement append_selective_shallow_copy for NullableColumn
  be/src/column/adaptive_nullable_column.cpp
  be/src/column/adaptive_nullable_column.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
Labels: 2.5, 3.0, 3.1, 3.2

#34291 [Enhancement] double jmockit's maximum heap memory size to avoid fe UT crash
  fe/fe-core/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#34348 [BugFix] fix flaky ut `JoinLocalShuffleTest#joinWithAgg`
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinLocalShuffleTest.java
Labels: 3.2

#34356 [BugFix] Fix bug QueryStatement return null when getRedirectStatus (backport #8087)
  fe/fe-core/src/main/java/com/starrocks/sql/ast/QueryStatement.java
Labels: automerge

#34357 [BugFix] fix clang build error
  be/src/util/bthreads/util.h
Labels: 3.1, 3.2

#34314 [Doc] adjust group_concat for toc
  docs/sql-reference/sql-functions/aggregate-functions/group_concat.md
  docs/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.0, 3.1, 3.2

#34099 [BugFix] Alter table add column error cause by generated column(#34095)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: 3.1, 3.2

#33622 [BugFix] Fix FE dead lock when commit txn and alter routine load job concurrrently
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
Labels: 2.5, 3.0, 3.1, 3.2

#32830 [Enhancement] Support bitmap binary field from hive in spark load
  docs/loading/SparkLoad.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/DppUtils.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/etl/SparkEtlJob.java
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#34352 [BugFix] PersistentIndex may keep unused delete operations
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/test/storage/persistent_index_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34351 [BugFix][Cherry-Pick][Branch-2.5] Fix select ORC MapVector's filter nullptr bug
  be/src/formats/orc/apache-orc/c++/src/Vector.cc
Labels: automerge

#34379 [Enhancement] Upgrade guava to 32.0.1-jre due to CVE-2023-2976
  java-extensions/hive-reader/pom.xml
Labels: 3.2

#34283 [BugFix] fix segment mem_usage race condition
  be/src/storage/lake/metacache.cpp
  be/src/storage/lake/metacache.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/test/storage/lake/metacache_test.cpp
  be/test/storage/lake/rowset_test.cpp
Labels: 3.1, 3.2

#34382 [BugFix] Make 'start_bthread' and 'start_bthread_and_join' inline
  be/src/util/bthreads/util.h
Labels: 3.1, 3.2

#31905 [Feature] Support where exprs in synchronized materialized view
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/schema_change.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/schema_change.cpp
  be/src/storage/schema_change.h
  be/src/storage/schema_change_utils.cpp
  be/src/storage/schema_change_utils.h
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/analysis/InPredicate.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVUtils.java
  fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateSyncMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/task/AlterReplicaTaskTest.java
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/Descriptors.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_sync_materialized_view_rewrite
  test/sql/test_materialized_view/R/test_sync_materialized_view_with_where
  test/sql/test_materialized_view/T/test_sync_materialized_view_rewrite
  test/sql/test_materialized_view/T/test_sync_materialized_view_with_where
Labels: behavior_changed, PROTO-REVIEW

#33922 [BugFix] fix some bugs on column with row
  be/src/runtime/local_tablets_channel.h
  be/src/storage/row_store_encoder.cpp
  be/src/storage/row_store_encoder_simple.cpp
  be/src/storage/rowset_update_state.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
Labels: 3.2

#34401 [Doc] Update SHOW_PROC.md current_queries description
  docs/sql-reference/sql-statements/Administration/SHOW_PROC.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#34397 [BugFix] fix hudi jni scanner read char type's fault
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
Labels: 3.2

#34399 [BugFix] Initialize convert function in parquet scanner repeatedly
  be/src/exec/parquet_scanner.cpp
Labels: 3.1, 3.2

#34331 [BugFix] Fix persistent index compatibility issue
  be/src/storage/persistent_index.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34316 [BugFix] Fix be crash when execute show proc '/current_queries'
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
Labels: 2.5, 3.0, 3.1, 3.2

#34380 [BugFix] Check column exist in vertical compaction
  be/src/storage/compaction.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/vertical_compaction_task.cpp
Labels: 3.2

#34406 [Enhancement] don't copy iceberg file scan task when disable column statistics
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.1, 3.2

#34390 [Doc] add func doc is_role_in_session
  docs/TOC.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-functions/utility-functions/is_role_in_session.md
  docs/sql-reference/sql-functions/utility-functions/isnotnull.md
  docs/sql-reference/sql-statements/account-management/SET_ROLE.md
Labels: documentation, 3.1, 3.2

#34436 [BugFix] Fix special partition error with NULL predicate
  fe/fe-core/src/main/java/com/starrocks/planner/RangePartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: 3.1, 3.2

#34237 [BugFix] Remove the db lock when releasing schedule resource
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/common/CloseableLock.java
Labels: 2.5, 3.0, 3.1, 3.2

#34289 [BugFix] Enhance the robustness of dynamic partitioning.
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
Labels: 2.5, 3.0, 3.1, 3.2

#34398 [Enhancement] Avoid checking group concurrency_limit when enabling group level queue
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  be/test/exec/pipeline/query_context_manger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/QueryQueueManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/TFragmentInstanceFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
  gensrc/thrift/InternalService.thrift
Labels: 3.1, 3.2, PROTO-REVIEW

#34047 [Enhancement] BitmapValue support copy on write
  be/src/column/adaptive_nullable_column.cpp
  be/src/column/adaptive_nullable_column.h
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.cpp
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/map_column.cpp
  be/src/column/map_column.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/exec/cross_join_node.cpp
  be/src/exec/join_hash_map.tpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.cpp
  be/src/exprs/bitmap_functions.cpp
  be/src/exprs/struct_functions.cpp
  be/src/types/bitmap_value.cpp
  be/src/types/bitmap_value.h
  be/test/column/object_column_test.cpp
  be/test/types/bitmap_value_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34176 [Enhancement] Check db nullable for replay of replica opreations
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 3.0, 3.1, 3.2

#34400 [BugFix] fix `PrintableMap` bug when properties contains quotation mark
  fe/fe-core/src/main/java/com/starrocks/common/util/PrintableMap.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateTableStmtTest.java
Labels: 3.2

#34435 [Doc] Fix global variable name in 3.1 rn
  docs/release_notes/release-3.1.md
Labels: documentation

#34384 [BugFix] add equivalent to CallOperator
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.1, 3.2

#34480 [Enhancement] rename `use-staros` to `enable-shared-data`
  build.sh
  docker/dockerfiles/artifacts/artifact.Dockerfile
  run-be-ut.sh
Labels: 3.0, 3.1, 3.2

#34486 [Doc] adjust group_concat and fix links
  docs/TOC.md
  docs/sql-reference/sql-functions/aggregate-functions/group_concat.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-statements/all-commands.md
  docs/sql-reference/sql-statements/data-manipulation/DROP_TASK.md
Labels: documentation

#34479 [Enhancement] Avoid checking group concurrency_limit when enabling group level queue (backport #34398)
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  be/test/exec/pipeline/query_context_manger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryQueueManager.java
  gensrc/thrift/InternalService.thrift
Labels: title needs [type]

#34300 [Enhancement] Choose 4 stage aggregate as default when group by columns has low ndv
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.1, 3.2

#34482 [Enhancement] Optimize the performance of BitmapValue::add()
  be/src/types/bitmap_value.cpp
  be/src/types/bitmap_value.h
Labels: 2.5, 3.0, 3.1, 3.2

#34440 [BugFix] Bugfix Applying MergeTwoProjectRule before MergeProjectWithChildRule And CTEConsumeOperator without children report errors
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/pruner/CPJoinGardener.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/pruner/UniquenessBasedTablePruneRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/TablePruningTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/TablePruningTestTPCDS.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSTestUtil.java
  fe/fe-core/src/test/resources/sql/tpcds_constraints/AddForeignKeys.sql
  fe/fe-core/src/test/resources/sql/tpcds_constraints/AddUniqueKeys.sql
Labels: 3.1, 3.2

#33466 [Enhancement](1/n)Get tablet schema from a specific version of tablet metadata
  be/src/exec/lake_meta_scanner.cpp
  be/src/exec/lake_meta_scanner.h
  be/src/exec/meta_scanner.h
  be/src/exec/olap_meta_scanner.cpp
  be/src/exec/olap_meta_scanner.h
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/versioned_tablet.cpp
  be/src/storage/lake/versioned_tablet.h
  be/src/storage/lake_meta_reader.cpp
  be/src/storage/lake_meta_reader.h
  be/src/storage/meta_reader.cpp
  be/src/storage/meta_reader.h
  be/src/storage/olap_meta_reader.cpp
  be/src/storage/olap_meta_reader.h
  be/test/exec/lake_meta_scanner_test.cpp
Labels: 3.2

#34505 [Enhancement] Remove Unused htrace in broker
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#34515 [Doc] Minor fix on Create storage volume syntax
  docs/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.1, 3.2

#34532 [Doc] move to us-east-1
  docs/loading/Loading_data_template.md
  docs/loading/s3.md
Labels: documentation

#34487 [BugFix] Fix chunk columns and schema fields check in memtable::insert
  be/src/storage/memtable.cpp
Labels: 3.2

#34322 [Enhancement] Refine error prompt
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
Labels: 2.5, 3.0, 3.1, 3.2

#34511 [BugFix] fix date_format expr partition prune bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ColumnFilterConverter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ConstantFunction.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/PartitionColPredicateEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/FurtherPartitionPruneTest.java
Labels: 3.1

#34527 [BugFix] Fix query may hang in right outer join
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  test/sql/test_spill/R/test_spill_hash_join
  test/sql/test_spill/T/test_spill_hash_join
Labels: 3.1, 3.2

#34324 [BugFix] Fix inconsistency crash when generated column backuped after base compaction(#34323)
  be/src/runtime/snapshot_loader.cpp
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
Labels: 3.1, 3.2

#34543 [BugFix] conflict between light schema change and migration (#34542)
  be/src/storage/data_dir.cpp
Labels: 3.2

#34317 [BugFix] forget to choose cn when starosAgent returned "failed to get primary backend"
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/cluster/SystemInfoServiceTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/UtilsTest.java
Labels: 3.1, 3.2

#34573 [Doc] Fix script
  docs/using_starrocks/query_rewrite_with_materialized_views.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#34208 [Enhancement] support decimal eq string cast flag
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#34484 [Feature] Support more specific error message
  be/src/agent/agent_task.cpp
  be/src/common/status.cpp
  be/src/common/status.h
  be/test/common/status_test.cpp
Labels: behavior_changed

#34599 [Doc] mod Jupyter and add it to TOC
  docs/TOC.md
  docs/integrations/IDE_integrations/jupysql.md
  docs/integrations/other_integrations/jupysql.md
Labels: documentation

#33839 [BugFix] Fix skip journal failed bug
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: 2.5, 3.0, 3.1, 3.2

#34241 [Enhancement] update error message of quality issue with ingested data
  fe/fe-core/src/main/java/com/starrocks/common/DataQualityException.java
  fe/fe-core/src/main/java/com/starrocks/task/LoadEtlTask.java
Labels: 2.5, 3.0, 3.1, 3.2

#34558 [Enhancement] remove db lock in MetricRepo
  fe/fe-core/src/main/java/com/starrocks/http/rest/MetricsAction.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/metric/TableMetricsRegistry.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricRepoTest.java
Labels: 3.0, 3.1, 3.2

#33494 [BugFix] reuse http brpc stub and config rpc_connect_timeout_ms
  be/src/common/config.h
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/util/brpc_stub_cache.h
Labels: 2.5, 3.0, 3.1, 3.2

#34590 [BugFix] Fix bug list automatic partition lost meta info
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.0, 3.1, 3.2

#34627 [BugFix] Fix bug information_schema.schemata catalog name is null
  be/src/exec/schema_scanner/schema_schemata_scanner.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#33929 [Feature]Support array_contains_seq functions like trino contains_sequence and ck hasSubstr function
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/test/exprs/array_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/array_contains_seq.md
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: documentation

#34608 [Doc] add new page
  docs/using_starrocks/query_acceleration_with_auto_increment.md
Labels: documentation, 3.0, 3.1, 3.2

#34619 [Enhancement] Check if locations are valid when creating storage volume
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1, 3.2

#34662 [Enhancement] Check db nullable for replay of replica opreations (backport #34176)
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#34638 [Enhancement] Turn on the default starcache UT switch to build the starrocks unittests with datacache.
  gensrc/thrift/InternalService.thrift
  run-be-ut.sh
Labels: PROTO-REVIEW

#34683 [Enhancement] Fixed incorrect printing of log information
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 3.0, 3.1, 3.2

#34407 [BugFix] fix null field change to string error
  be/src/storage/convert_helper.cpp
  be/test/storage/convert_helper_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34674 [Enhancement] jdbc use connectionAttributes to help developers implement some parameters
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlAuthPacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlCapability.java
Labels: 3.1, 3.2

#34675 [BugFix]fix #33976
  fe/fe-core/src/main/java/com/starrocks/http/action/IndexAction.java
Labels: 2.5, 3.0, 3.1, 3.2

#34603 [BugFix] Fix 'NPE: The URI scheme of endpointOverride must not be null'
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergAwsClientFactory.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergAwsClientFactoryTest.java
Labels: 3.1, 3.2

#34601 [BugFix] Fix wrong file name in restore if the path end with slash (#34597)
  be/src/fs/hdfs/fs_hdfs.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#33053 [Enhancement] Optimize the partitioning method of MV based on JDBC Table
  fe/fe-core/src/main/java/com/starrocks/analysis/DateLiteral.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MockedJDBCMetadata.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteJDBCTest.java
Labels: sig/materialized view, behavior_changed, 3.2

#34680 [BugFix] do not remove non deterministic func in group by keys
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#34556 [Enhancement] Read dcg segment without column index
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake_meta_reader.cpp
  be/src/storage/meta_reader.cpp
  be/src/storage/meta_reader.h
  be/src/storage/olap_meta_reader.cpp
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/tablet_updates.cpp
  be/test/CMakeLists.txt
  be/test/storage/meta_reader_test.cpp
  be/test/storage/rowset/segment_iterator_test.cpp
  be/test/storage/rowset/segment_test.cpp
Labels: 3.2

#34443 [Refactor] Add txn id for light schema change task
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableAddOrDropColumnsInfo.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/TableAddOrDropColumnsInfoTest.java
Labels: META-REVIEW

#34319 [BugFix] Fix mv rewrite bug for count agg func with rollup
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  test/sql/test_materialized_view/R/test_materialized_view_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_rewrite
Labels: 3.1, 3.2

#34668 [BugFix] Provide detail error message when alter task failed
  be/src/agent/agent_task.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/test/java/com/starrocks/alter/PseudoClusterAlterTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
Labels: 2.5, 3.0, 3.1, 3.2

#34623 [Enhancement][Cherry-Pick] support decimal eq string cast flag (#34208)
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
Labels: automerge

#34682 [BugFix] Fix iceberg position delete bug in orc format
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/test/formats/orc/orc_chunk_reader_test.cpp
Labels: 3.0, 3.1, 3.2

#34213 [Feature] support sync cloud table meta by http api
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/SyncCloudTableMetaAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/http/SyncCloudTableMetaTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: documentation

#31841 [Feature] Broker load supports json
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/test/exec/json_parser_test.cpp
  be/test/exec/json_scanner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/FileScanNodeTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: behavior_changed, PROTO-REVIEW

#34687 [BugFix] Fix applying runtime filter of decimal type on ORC
  be/src/formats/orc/orc_chunk_reader.cpp
Labels: 3.0, 3.1, behavior_changed, 3.2

#34734 [BugFix] Fix setup RF params when converting fragment to thrift format
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: 2.5

#34749 [Feature] support sync cloud table meta by http api (backport #34213)
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/SyncCloudTableMetaAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/http/SyncCloudTableMetaTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: automerge

#34564 [BugFix] Fix unexpectedly modification that broker load obtains profile
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
Labels: 3.1, behavior_changed, 3.2

#34731 [BugFix] Fix automatic partition write data into wrong partition when many partition created concurrency
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
Labels: 3.0, 3.1, 3.2

#34312 [Enhancement] Refactor window function processing
  be/src/common/config.h
  be/src/exec/analytic_node.cpp
  be/src/exec/analytic_node.h
  be/src/exec/analytor.cpp
  be/src/exec/analytor.h
  be/src/exec/pipeline/analysis/analytic_sink_operator.cpp
  be/src/exec/pipeline/analysis/analytic_sink_operator.h
  be/src/exprs/agg/count.h
  be/src/exprs/agg/window.h
  be/src/util/runtime_profile.h
  be/test/exec/analytor_test.cpp
  test/sql/test_window_function/R/test_basic_multi_window_function
  test/sql/test_window_function/R/test_basic_window_function
  test/sql/test_window_function/R/test_removable_cumulative_process
  test/sql/test_window_function/R/test_window_function_streaming
  test/sql/test_window_function/T/test_basic_multi_window_function
  test/sql/test_window_function/T/test_basic_window_function
  test/sql/test_window_function/T/test_removable_cumulative_process
  test/sql/test_window_function/T/test_window_function_streaming
Labels: 3.1, 3.2

#34261 [Enhancement] Lake pk table comaction optimization
  be/src/common/config.h
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/rowset.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_compaction_state.cpp
  be/src/storage/lake/update_compaction_state.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/lake/vertical_compaction_task.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/test_util.h
Labels: 3.1, behavior_changed, 3.2

#34767 [Doc] Update resource_group.md
  docs/administration/resource_group.md
Labels: documentation

#34757 [Doc] Delete docs/administration/deploy_cn.md
  docs/administration/deploy_cn.md
  docs/administration/enable_fqdn.md
Labels: documentation

#34761 [Doc] Delete docs/quick_start/Deploy.md
  docs/quick_start/Deploy.md
Labels: documentation

#34723 [Doc] Delete docs/administration/Cluster_administration.md
  docs/administration/Cluster_administration.md
  docs/administration/Scale_up_down.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#28789 [Enhancement]Optimize publish version through batch in SHARED_DATA
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/lake/tablet_metadata.h
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/transactions.h
  be/src/storage/lake/txn_log_applier.h
  be/test/service/lake_service_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionGraph.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateBatch.java
  fe/fe-core/src/test/java/com/starrocks/catalog/FakeEditLog.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionGraphTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionStateBatchTest.java
  gensrc/proto/lake_service.proto
Labels: behavior_changed, 3.2, META-REVIEW, PROTO-REVIEW

#34785 [Doc] add 5 pipe related sql docs and s3 load doc
  docs/loading/s3.md
  docs/sql-reference/sql-statements/data-manipulation/ALTER_PIPE.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE_PIPE.md
  docs/sql-reference/sql-statements/data-manipulation/DROP_PIPE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW_PIPES.md
  docs/sql-reference/sql-statements/data-manipulation/SUSPEND_or_RESUME_PIPE.md
Labels: documentation

#34790 [Enhancement] abort transaction without database lock
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#34805 [Doc] add missing key word in syntax
  docs/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, title needs [type]

#34784 [Doc] 3.2 add apache ranger
  docs/TOC.md
  docs/administration/range_plugin.md
  docs/assets/ranger_added_service.png
  docs/assets/ranger_home.png
  docs/assets/ranger_properties.png
  docs/assets/ranger_service_details.png
  docs/assets/ranger_show_config.png
Labels: documentation, 3.2

#34814 [BugFix] add lock forr _rowset_stats
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#34789 [BugFix][Cherry-Pick][Branch-2.5] Fix HDFS stat information lost in profile and avoid BE crashed when get HDFS stat
  be/src/fs/fs_hdfs.cpp
Labels: automerge

#34793 [Enhancement] report error to FE if backend is not compiled with shared-data support
  be/src/agent/heartbeat_server.cpp
Labels: 3.1, 3.2

#34569 [Enhancement] skip optimizer lock for materialized view
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: 2.5, 3.0, 3.1, 3.2

#34853 [BugFix] [BackPort] Spark connector support cloud native table (#25497)
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/test/java/com/starrocks/http/TableQueryPlanActionTest.java
Labels: automerge

#34857 [Doc] fix SQLAlchemy link in superset_support.md
  docs/integrations/superset_support.md
Labels: documentation

#34855 [Doc] Add the supported version for Partitioning based on the column expression in starrocks shared-data mode
  docs/table_design/expression_partitioning.md
Labels: documentation, 3.1, 3.2

#34851 [Doc] Refine Property Description
  docs/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#34519 [BugFix] Update tablet schema and compaction have writer/read conflict
  be/src/storage/tablet.cpp
Labels: 3.2
