Repository StarRocks/starrocks, pull requests merged in 2023-10, with the labels that each got.

#32008 [Doc] MDX 2 compatibility
  docs/administration/Blacklist.md
  docs/administration/Configuration.md
  docs/administration/Monitor_and_Alert.md
  docs/administration/privilege_item.md
  docs/administration/resource_group.md
  docs/benchmarking/SSB_Benchmarking.md
  docs/data_source/External_table.md
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/elasticsearch_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/data_source/catalog/jdbc_catalog.md
  docs/data_source/catalog/paimon_catalog.md
  docs/data_source/file_external_table.md
  docs/deployment/deploy_broker.md
  docs/deployment/deploy_shared_data.md
  docs/deployment/starrocks_on_aws.md
  docs/developers/code-style-guides/restful-api-standard.md
  docs/developers/trace-tools/Trace.md
  docs/faq/loading/Broker_load_faq.md
  docs/loading/Flink-connector-starrocks.md
  docs/loading/Loading_intro.md
  docs/loading/Spark-connector-starrocks.md
  docs/release_notes/release-3.1.md
  docs/sql-reference/sql-functions/json-functions/overview-of-json-functions-and-operators.md
  docs/sql-reference/sql-statements/Administration/CREATE RESOURCE GROUP.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
  docs/sql-reference/sql-statements/account-management/SHOW GRANTS.md
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/SELECT.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/alter-routine-load.md
  docs/sql-reference/sql-statements/generated_columns.md
  docs/table_design/expression_partitioning.md
  docs/table_design/list_partitioning.md
  docs/unloading/Spark_connector.md
  docs/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
  docs/using_starrocks/data_modeling_with_materialized_views.md
  docs/using_starrocks/query_cache.md
Labels: documentation, 2.5, 2.4, 2.3, 2.2, 3.0, 3.1, 3.2

#32019 [Doc] fix image tags
  docs/developers/development-environment/ide-setup.md
  docs/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
Labels: documentation, 3.0, 3.1, 3.2

#32025 [Doc] Format configuration docs
  docs/administration/Configuration.md
Labels: documentation

#32026 [Doc] fix spacing
  docs/administration/Configuration.md
Labels: documentation

#32027 [Doc] Update data_lake_query_acceleration_with_materialized_views.md
  docs/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
Labels: documentation

#32029 [Doc] fix MDX 2 compliance
  docs/administration/Blacklist.md
  docs/administration/Configuration.md
  docs/administration/Monitor_and_Alert.md
  docs/administration/resource_group.md
  docs/administration/starrocks_on_aws.md
  docs/data_source/External_table.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/developers/trace-tools/Trace.md
  docs/faq/loading/Broker_load_faq.md
  docs/sql-reference/sql-functions/JAVA_UDF.md
  docs/sql-reference/sql-functions/json-functions/overview-of-json-functions-and-operators.md
  docs/sql-reference/sql-statements/Administration/CREATE RESOURCE GROUP.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/SELECT.md
  docs/sql-reference/sql-statements/data-manipulation/alter-routine-load.md
Labels: documentation

#32034 [Doc] Add example of setting multiple global variables
  docs/sql-reference/sql-statements/Administration/SET.md
Labels: documentation

#32036 [Doc] Update catalog_overview.md
  docs/data_source/catalog/catalog_overview.md
Labels: documentation, 2.5, 2.4, 3.0, 3.1, 3.2

#32028 [BugFix] Fix ignorance of where in AdminShowReplicaStatus
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AdminStmtAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/AdminShowReplicaStatusStmtTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#32033 [Enhancement] Support delay some time before drop tablet on tablet report
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#32051 [Doc] Update Configuration.md
  docs/administration/Configuration.md
Labels: documentation, 3.0, 3.1, 3.2

#31927 [Doc] shared data
  docs/TOC.md
  docs/assets/commonMarkdown/sharedDataCNconf.md
  docs/assets/commonMarkdown/sharedDataIntro.md
  docs/assets/commonMarkdown/sharedDataUse.md
  docs/assets/commonMarkdown/sharedDataUseIntro.md
  docs/deployment/deploy_shared_data.md
  docs/deployment/deployment_overview.md
  docs/deployment/shared_data/azure.md
  docs/deployment/shared_data/gcs.md
  docs/deployment/shared_data/minio.md
  docs/deployment/shared_data/s3.md
  docs/introduction/StarRocks_intro.md
  docs/release_notes/release-3.0.md
  docs/release_notes/release-3.1.md
  docs/sql-reference/sql-statements/Administration/CREATE STORAGE VOLUME.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/table_design/Data_distribution.md
  docs/table_design/expression_partitioning.md
  docs/table_design/list_partitioning.md
Labels: documentation, 3.1, 3.2

#32062 [Enhancement] Resolve hostname in frontend
  fe/fe-core/src/main/java/com/starrocks/common/util/DnsCache.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionDAG.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
Labels: 3.2

#32065 [Doc] fix missing import
  docs/deployment/shared_data/gcs.md
  docs/deployment/shared_data/minio.md
  docs/deployment/shared_data/s3.md
Labels: documentation, 3.1, 3.2

#32056 [Enhancement] Resolve hostname in FE
  fe/fe-core/src/main/java/com/starrocks/common/util/DnsCache.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
Labels: 2.5, 3.0

#32055 [BugFix] Fix use-after-free in GlobalRuntimeFilter
  be/src/exprs/runtime_filter_bank.cpp
  test/sql/test_grf/R/test_grf
Labels: 2.5, 3.0, 3.1, 3.2

#31947 [Enhancement] remove some useless operatitons when start as cn
  be/src/agent/heartbeat_server.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/data_dir.cpp
  be/src/storage/data_dir.h
  be/src/storage/options.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: 3.1, 3.2

#31550 [Enhancement] Support delete sql for cloud native primary key table with sort key
  be/src/storage/delta_writer.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/memtable.h
Labels: 3.1, 3.2

#31952 [Doc] Release 2.5.13
  docs/release_notes/release-2.5.md
Labels: documentation

#32059 [BugFix] Fix iceberg hive catalog + s3 protocol will occur S3Client authentication failed
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
Labels: 3.1, 3.2

#32094 [Doc] update docs/deployment/sr_operator.md
  docs/deployment/sr_operator.md
Labels: documentation

#32005 [BugFix] fix too many open files when PCU generate too many segment files
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.1, 3.2

#32106 [BugFix] coalesce(date, datetime) should return datetime type
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/ExpressionAnalyzerTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#32111 [Enhancement] Increase vacuum RPC timeout
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
Labels: 3.1, 3.2

#32125 [Doc] fix broken links in create routine load
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Labels: documentation

#32129 [Doc] corr window functions support order by and window clause
  docs/release_notes/release-3.1.md
  docs/sql-reference/sql-functions/Window_function.md
  docs/sql-reference/sql-statements/data-manipulation/SELECT.md
Labels: documentation, 2.5

#32132 [Doc] delete misleading description in create routine load
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Labels: documentation

#32130 [Doc] update role inherit figure
  docs/administration/privilege_overview.md
  docs/assets/privilege-role-inheri.png
  docs/assets/privilege-role_inheri.png
Labels: documentation, 3.0, 3.1, 3.2

#31990 [Feature] Support url_extract_host Function(#31969)
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  gensrc/script/functions.py
Labels: documentation

#32057 fix refresh mv failed because of partition range not include
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
Labels: sig/materialized view

#31910 [Enhancement] Limit RPC max concurrency of lake service
  be/src/common/config.h
  be/src/service/service_be/starrocks_be.cpp
Labels: documentation, 3.1, 3.2

#32097 [BugFix] fix string format pattern
  fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java
Labels: 3.1, 3.2

#31968 [UT] add testcases for url_extract_host function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  docs/TOC.md
  docs/sql-reference/sql-functions/string-functions/url_extract_host.md
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: documentation

#31970 [Enhancement] Get tablet schema by index id in lake::DeltaWriter
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/storage_engine.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/auto_increment_partial_update_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/condition_update_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/schema_change_test.cpp
Labels: 3.2

#32126 [Feature] Modify pipeline dop by fragments in query queue
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/GlobalVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryQueueManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/AllocatedSlots.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/LogicalSlot.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/PendingSlotRequest.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotRequestQueue.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowRunningQueriesStmt.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW

#32154 [BugFix] fix subquery check in join on predicate (backport #30876)
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: automerge

#31547 [Enhancement] allow creating index on mv
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: sig/materialized view, 3.0, 3.1, 3.2

#31951 [Enhancement] Optimize global lock when creating table/mv/view
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogManager.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/StringUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/MarkedCountDownLatch.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/QueryableReentrantLock.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/QueryableReentrantReadWriteLock.java
  fe/fe-core/src/main/java/com/starrocks/load/OlapDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/DropAutoIncrementMapTask.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportExportingTask.java
  fe/fe-core/src/main/java/com/starrocks/task/PushTask.java
  fe/fe-core/src/main/java/com/starrocks/task/UpdateTabletMetaInfoTask.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobPrimaryKeyTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/concurrent/CountingLatchTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/concurrent/QueryableReentrantLockTest.java
  fe/fe-core/src/test/java/com/starrocks/load/DeleteHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/server/ConcurrentDDLTest.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 2.5, 3.0, 3.1, 3.2

#31962 [BugFix] Fix FSIO stats lost in hdfs_scanner_text
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/jni_scanner.cpp
Labels: 3.1, 3.2

#32016 [Enhancement] Only create necessay partitions when refreshing mv by partition
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
Labels: sig/materialized view, 3.0, 3.1, 3.2

#31994 [Enhancement] Support fill data cache when querying cloud native mv
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
Labels: 3.1, 3.2

#32173 [Cherry-pick][branch-3.1] support refresh iceberg mv by partition
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
Labels: title needs [type]

#32143 [BugFix] Fix hudi type converter
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/ColumnTypeConverterTest.java
Labels: 3.0, 3.1, 3.2

#32190 [BugFix][Cherry-Pick][Branch-3.0] Fix FSIO stats lost in hdfs_scanner_text
  be/src/exec/hdfs_scanner.cpp
Labels: 2.5

#31839 [BugFix] Fix deltalake glue catalog
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadataFactory.java
Labels: 3.2

#31799 [Enhancement] reduce disk cost of persistent index and do some refactoring
  be/src/storage/lake/lake_local_persistent_index.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/persistent_index_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#31380 [Enhancement] Refine profile to support visualization refactor(4)
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.h
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.h
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/data_stream_recvr.h
  be/src/runtime/sender_queue.cpp
  be/src/runtime/sender_queue.h
  be/test/util/runtime_profile_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfilingExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
Labels: 3.1, 3.2

#31475 [Enhancement] Add PushDownTopNBelowUnionRule to support push down topn below union all
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownTopNBelowOuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownTopNBelowUnionRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitScanORToUnionRule.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PushDownTopnNTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  fe/fe-core/src/test/resources/sql/query_dump/union_all_with_topn_runtime_filter.json
  test/sql/test_materialized_view/R/test_materialized_view_union
  test/sql/test_materialized_view/T/test_materialized_view_union
  test/sql/test_union/R/test_union_all_with_topn
  test/sql/test_union/T/test_union_all_with_topn
Labels: 3.2

#31577 [BugFix] Rebuild materialized index meta after schema change
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
Labels: sig/materialized view, 3.0, 3.1, 3.2

#31105 [Feature] Datacache sql management, only support blacklist in this pr
  be/src/connector/hive_connector.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DatacacheExprRewriter.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DatacacheMgr.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DatacacheOptions.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DatacacheRule.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DatacacheStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ClearDatacacheRulesStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateDatacacheRuleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropDatacacheRuleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowDatacacheRulesStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/DatacacheStmtAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DatacacheMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DatacachePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: behavior_changed, PROTO-REVIEW

#32181 [BugFix] Set default AWS region when user not specific region explictily
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergAwsClientFactory.java
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudConfigurationProvider.java
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudCredential.java
  fe/fe-core/src/test/java/com/starrocks/credential/AWSCloudConfigurationTest.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
Labels: 3.1, 3.2

#32222 [Enhancement] Rename variable's name from Datacache to DataCache
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheExprRewriter.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheMgr.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheOptions.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheRule.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DataCacheStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ClearDataCacheRulesStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateDataCacheRuleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropDataCacheRuleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowDataCacheRulesStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/DataCacheStmtAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DataCacheMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DataCachePlanTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#31929 [BugFix] Don't limit scan threads for stream load to avoid deadlock
  be/src/common/config.h
  be/src/exec/connector_scan_node.cpp
  be/src/exec/connector_scan_node.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
  be/test/exec/connector_scan_node_test.cpp
Labels: 3.0, 3.1, 3.2

#32152 [Enhancement] Prevent memory overruns during Parquet data parsing
  be/src/exec/parquet_reader.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#32218 [Enhancement] Refine profile for version smaller than or equals to 3.0
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.h
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/runtime/data_stream_mgr.cpp
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/data_stream_recvr.h
  be/src/runtime/sender_queue.cpp
  be/src/runtime/sender_queue.h
  be/test/util/runtime_profile_test.cpp
Labels: 2.5

#32031 [BugFix] Fix analyze mv privilege check
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeJobStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowBasicStatsMetaStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowHistogramStatsMetaStmt.java
  fe/fe-core/src/test/java/com/starrocks/connector/MockedMetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: sig/materialized view, 3.2

#32228 [Enhancement] use bthread::Mutex in PipelineSenderQueue
  be/src/runtime/sender_queue.h
Labels: 2.5, 3.0, 3.1, 3.2

#32105 [Enhancement] Support sortkey reorder
  be/src/storage/schema_change.cpp
  be/src/storage/schema_change_utils.cpp
  be/test/storage/lake/schema_change_test.cpp
Labels: 3.1, 3.2

#32257 [BugFix] Disable unstable query queue UT
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
Labels: 3.2

#32207 [BugFix] Fix Incorrect Sql Statement Display in Profile Page
  fe/fe-core/src/main/java/com/starrocks/http/action/WebBaseAction.java
  fe/fe-core/src/test/java/com/starrocks/http/QueryProfileActionTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#32264 [BugFix] Disable unstable query queue UT
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
Labels: 3.2

#32255 [BugFix] fix create mv privilege
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: sig/materialized view, 2.5, 3.0, 3.1, behavior_changed, 3.2

#32274 Revert "[Refactor] Seperate starcache from staros to avoid build staros modules if unnecessary. (#30687)"
  be/CMakeLists.txt
  be/test/block_cache/block_cache_test.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/io/cache_input_stream_test.cpp
  build.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
  thirdparty/vars.sh
Labels: title needs [type]

#32280 [BugFix] Fix NPE in non-partition table
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#32276 Revert "[Refactor] Seperate starcache from staros to avoid build staros modules if unnecessary. (#30687)"
  be/CMakeLists.txt
  be/test/block_cache/block_cache_test.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/io/cache_input_stream_test.cpp
  build.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
  thirdparty/vars.sh
Labels: title needs [type]

#32273 [Enhancement] Make iceberg aws authentication's error msg more clear
  be/src/exec/hdfs_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergAwsClientFactory.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergAwsClientFactoryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/io/IcebergCachingFileIOTest.java
Labels: 3.1, 3.2

#31560 [BugFix] Fix routine load info persistence issue
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
Labels: 3.1, 3.2

#32229 [BugFix]Revert "[Enhancement] remove some useless operatitons when start as c…
  be/src/agent/heartbeat_server.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/data_dir.cpp
  be/src/storage/data_dir.h
  be/src/storage/options.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: 3.2

#31758 [Feature] Support Tencent cos filesystem
  build.sh
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationConstants.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudType.java
  fe/fe-core/src/main/java/com/starrocks/credential/tencent/TencentCloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/credential/tencent/TencentCloudConfigurationProvider.java
  fe/fe-core/src/main/java/com/starrocks/credential/tencent/TencentCloudCredential.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: behavior_changed

#32219 [BugFix][Enhancement] skip building ht in hash join build side if query is cancelled
  be/src/exec/pipeline/hashjoin/hash_join_build_operator.cpp
Labels: 3.0, 3.1, 3.2

#30813 [BugFix] Fix query partition compensate predicates for mv rewrite
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteMultiTableJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mv_on_mv2.json
Labels: 3.1, 3.2

#32293 [Enhancement] cp dla optimize
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/subfield_expr.cpp
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/meta_helper.h
  be/src/runtime/descriptor_helper.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/group_reader_test.cpp
  be/test/formats/parquet/test_data/test_parquet_struct_in_struct.parquet
  docs/table_design/Temporary_partition.md
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
  gensrc/thrift/Descriptors.thrift
  test/sql/test_external_file/R/test_parquet_struct_in_struct
  test/sql/test_external_file/T/test_parquet_struct_in_struct
Labels: documentation

#32300 [BugFix] Populate parquet data with system timezone when the data timezone is empty
  be/src/exec/arrow_to_starrocks_converter.cpp
  be/test/exec/parquet_scanner_test.cpp
  be/test/exec/test_data/parquet_data/data_json.parquet
  be/test/exec/test_data/parquet_data/generate.py
Labels: 3.2

#32330 [Enhancement] add more information to invalid segment footer issue message
  be/src/storage/rowset/page_io.cpp
Labels: 3.1, 3.2

#32331 [Enhancement][backport] Optimize global lock when creating table/mv/view (#31951)
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/common/util/StringUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/server/ConcurrentDDLTest.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 2.5, 3.0, 3.1

#32310 [Branch-3.1] fix refresh mv error when iceberg table is empty
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
Labels: title needs [type]

#32294 [BugFix][Cherry-Pick] Fix NPE in non-partition table
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: automerge

#32314 [UT] Fix unstable test BinlogReaderTest.test_read_full_columns
  be/test/storage/binlog_reader_test.cpp
Labels: behavior_changed

#32266 [BugFix] check whether partitioned mv for jdbc is supported
  fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MockedJDBCMetadata.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConnectorPlanTestBase.java
Labels: 3.1, 3.2

#32141 [Enhancement] support partition rollup for string column in mv
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewPartitionFunctionChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionExprAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
Labels: sig/materialized view, 3.1, 3.2

#32304 [Enhancement] Upgrade snappy-java due to CVE-2023-43642
  fe/fe-core/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#9763 [Enhancement]support creating multiple single connections between BE
  be/src/common/config.h
  be/src/util/brpc_stub_cache.h
Labels: 3.1, 3.2

#32281 [BugFix] Fix load with incomplete sort key
  be/src/storage/lake/delta_writer.cpp
  be/test/storage/lake/partial_update_test.cpp
Labels: 3.1, 3.2

#32178 [Refactor] Enhance runtime filter push-down
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/TPCDSCoordTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q7.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
Labels: documentation, behavior_changed

#32306 [Enhancement] print more log and stack for audit and paimon table
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/qe/AuditEventProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/AuditLogBuilder.java
Labels: 3.2

#31498 [Enhancement] Rename `block_cache` configurations to `data_cache` and support configuring data cache size by different expression.
  be/src/block_cache/CMakeLists.txt
  be/src/block_cache/cache_options.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/common/config.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/options.cpp
  be/src/storage/options.h
  be/test/block_cache/block_cache_test.cpp
  be/test/exec/hdfs_scanner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: behavior_changed, PROTO-REVIEW

#32374 [Enhancement] Upgrade tomcat to 8.5.93 due to CVE-2023-41080
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#32191 [Doc] Add table creation properties to Iceberg catalog doc and Iceberg table creation info to CREATE TABLE doc
  docs/data_source/catalog/iceberg_catalog.md
  docs/sql-reference/sql-statements/data-definition/CREATE DATABASE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation

#32375 [Enhancement] Make JEMALLOC_CONF mutable in be.conf
  bin/start_backend.sh
Labels: 3.1, 3.2

#32303 [Enhancement] Refine profile to support visualization refactor(5)
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
Labels: 3.0, 3.1, 3.2

#31505 [BugFix] Fix synchronized materialized view with upper column names
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  test/sql/test_materialized_view/R/test_sync_materialized_view2
  test/sql/test_materialized_view/T/test_sync_materialized_view2
Labels: 3.1, 3.2

#32400 [Refactor] Remove limitation of groovy script (#31500)(cherry-pick)
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteScriptExecutor.java
Labels: automerge

#31401 [Enhancement] Fixes #15063, Support COUNT_IF function
  docs/TOC.md
  docs/sql-reference/sql-functions/aggregate-functions/count_if.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteCountIfFunction.java
  test/sql/test_agg_function/R/test_count_if
  test/sql/test_agg_function/T/test_count_if
Labels: documentation, 3.0, 3.1, 3.2

#32077 [Enhancement] use resolveExpr to resolve the materialized view's partition expr
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: sig/materialized view, 3.1, 3.2

#31904 [BugFix] Force cte resue when plan has non-deterministic function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ForceCTEReuseRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
Labels: 3.2

#31549 [Enhancement] ExchangeSink returns RPC error not internal error
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
Labels: 2.5, 3.0, 3.1, 3.2

#32370 [Enhancement] Upgrade snappy-java due to CVE-2023-43642
  fe/fe-core/pom.xml
Labels: 2.5, 3.0, 3.1

#32393 [BugFix] array_cum_sum two bugs: overflow and const col error
  be/src/exprs/array_functions.cpp
  be/test/exprs/array_functions_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#32292 [BugFix] Fix ASAN wrong DCHECK for per-bucket-optimize
  be/src/exec/scan_node.cpp
Labels: 3.2

#32361 [Enhancement]add detail message when cancel
  fe/fe-core/src/main/java/com/starrocks/http/HttpConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpResultSender.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/GetNextTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/StartSchedulingTest.java
Labels: behavior_changed, 3.2

#32343 [Enhancement] Do not use partial update in update statement in row mode
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeUpdateTest.java
Labels: 3.1, 3.2

#32285 [BugFix] Fix str2date partitioned mv (#31964)
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MockedJDBCMetadata.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
Labels: sig/materialized view

#32307 [Enhancement] autovacuum without list tablet metadata
  be/src/common/config.h
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
Labels: 3.1, 3.2

#32405 [Enhancement] Does not share vacuum's thread pool for other tasks
  be/src/agent/agent_server.cpp
  be/src/service/service_be/lake_service.cpp
  be/test/service/lake_service_test.cpp
Labels: 3.1, 3.2

#32420 [BugFix] fix get partition names when table has bool type partition column using glue
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/IHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorInternalMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/HiveTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteFileOperationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/CachingHiveMetastoreTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetastoreOperationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetastoreTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveStatisticsProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/hudi/HudiMetadataTest.java
Labels: 3.2

#31794 [Enhancement] Support optimize table change distribution method
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
Labels: behavior_changed, 3.2

#32454 [BugFix] fix compression_code doesn't work on iceberg table
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
Labels: 3.1, 3.2

#32317 [Enhancement] cast date/datetime to number in FE
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/ConstantOperatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/FoldConstantsRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: behavior_changed, 3.2

#32426 [BugFix] Fix union isnullable error
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EmptyValueTest.java
Labels: 3.2

#32457 [Enhancement] optimize the string compare performance of binary function
  be/src/exprs/binary_function.h
Labels: 2.5, 3.0, 3.1, 3.2

#31924 [Enhancement] Check parquet statistics correctness using sort order
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/metadata.cpp
  be/src/formats/parquet/metadata.h
  be/test/formats/parquet/metadata_test.cpp
Labels: 3.1, 3.2

#31978 [BugFix] Fix segment size in metadata cache
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/rowset/bitmap_index_reader.cpp
  be/src/storage/rowset/bitmap_index_reader.h
  be/src/storage/rowset/bloom_filter_index_reader.cpp
  be/src/storage/rowset/bloom_filter_index_reader.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/zone_map_index.cpp
  be/src/storage/rowset/zone_map_index.h
  be/src/storage/tablet_schema.h
  be/test/CMakeLists.txt
  be/test/storage/lake/metadata_cache_test.cpp
  be/test/storage/rowset/column_reader_writer_test.cpp
  be/test/storage/rowset/map_column_rw_test.cpp
  be/test/storage/rowset/struct_column_rw_test.cpp
Labels: 3.1, 3.2

#32494 [Enhancement] Upgrade XNIO due to CVE-2022-0084
  fe/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#32498 [BugFix] padding char partition column values using hive sink
  be/src/exec/pipeline/sink/table_function_table_sink_operator.cpp
Labels: 3.2

#32459 [Enhancement] Create dummy storage descriptor for iceberg/deltalake table from glue
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/converters/CatalogToHiveConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/unified/UnifiedMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/GlueToHiveConverterTest.java
Labels: 3.2

#32509 [Doc] Update resource_group.md
  docs/administration/resource_group.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#32532 [Doc] fix broken links
  docs/README.md
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/deployment/deploy_manually.md
  docs/deployment/shared_data/gcs.md
  docs/deployment/shared_data/minio.md
  docs/deployment/shared_data/s3.md
  docs/faq/loading/Routine_load_faq.md
  docs/loading/InsertInto.md
  docs/release_notes/release-3.0.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-statements/Utility/DESCRIBE.md
  docs/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/sql-reference/sql-statements/data-definition/DROP_MATERIALIZED_VIEW.md
  docs/sql-reference/sql-statements/data-definition/SET_CATALOG.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW_CREATE_TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/table_design/Temporary_partition.md
  docs/using_starrocks/Materialized_view-single_table.md
Labels: documentation

#32538 [Doc] fix broken links
  docs/faq/Others.md
  docs/sql-reference/sql-statements/data-definition/ALTER_RESOURCE.md
  docs/sql-reference/sql-statements/generated_columns.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#32506 [BugFix] fix not copy hasVarArgs field in function
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/FunctionSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: 2.5

#32537 [Enhancement][backport] Optimize global lock when creating table/mv/view (#31951) (#32331)
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/common/util/StringUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/InfoSchemaDbTest.java
  fe/fe-core/src/test/java/com/starrocks/server/ConcurrentDDLTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: automerge

#32547 [Enhancement] Upgrade zookeeper to 3.9.1 due to CVE-2023-44981
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#32477 [Enhancement] Refine profile to support visualization refactor(6)
  be/src/exec/pipeline/operator.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfilingExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
Labels: 3.1, 3.2

#32511 [BugFix] Fix topn push down bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownTopNBelowOuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownTopNBelowUnionRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PushDownTopnNTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.2

#32517 [BugFix] Fix orc late materialization error result in list/map type
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.cc
Labels: 2.5, 3.0, 3.1, 3.2

#32489 [Enhancement] Validate write single file parameter of unloading
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: 3.2

#32562 [Enhancement] Upgrade libcurl due to CVE-2023-38545/CVE-2023-38546
  thirdparty/vars.sh
Labels: 2.5, 3.0, 3.1, 3.2

#32572 [BugFix] Fix txn id repeat bug after FE restart
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
Labels: 3.1, 3.2

#32305 [Enhancement] auto detect and set jvm xmx parameter
  bin/common.sh
  bin/start_fe.sh
Labels: 2.5, 3.0, 3.1, 3.2

#32341 [BugFix] Fix invalid bucket size
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
Labels: 3.2

#32340 [BugFix] Fix range/list partition table automatic bucket fail
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
Labels: 3.2

#31570 [Enhancement]Enhance paimon reader for decimal type
  be/src/exec/jni_scanner.cpp
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiColumnValue.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScanner.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnValue.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapColumnVector.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonColumnValue.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonTypeUtils.java
Labels: 3.2

#32586 [BugFix]revert hive_max_split_size to 64MB
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.2

#32599 [Doc] add privilege faq and update unit in system_variable
  docs/administration/privilege_faq.md
  docs/reference/System_variable.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#32582 [BugFix] fix lz4 type using arrow sink
  be/src/formats/parquet/file_writer.cpp
Labels: 3.1, 3.2

#32439 [BugFix] Fix ci failure of sort key reorder in shared-nothing mode
  be/src/storage/schema_change_utils.cpp
  be/src/storage/schema_change_utils.h
Labels: 3.1, 3.2

#32600 [Doc] Add QuickBI doc
  docs/TOC.md
  docs/integrations/BI_integrations/QuickBI.md
Labels: documentation

#32520 [BugFix] ban partition clause on external table
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
Labels: 3.1, 3.2

#32557 [Enhancement] Avoid build slice when building GlobalRuntimeFilter
  be/src/column/binary_column.h
  be/src/column/column_helper.h
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/types/logical_type_infra.h
  be/test/exprs/runtime_filter_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#32495 [Enhancement] Disable enable_async_write_back property
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/common/util/PropertyAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
Labels: 3.0, 3.1, behavior_changed, 3.2

#32581 [BugFix] No check on success of protobuf serialization
  be/src/fs/fs.h
  be/src/storage/delta_column_group.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/protobuf_file.cpp
  be/src/storage/protobuf_file.h
  be/src/storage/tablet_meta.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/protobuf_file_test.cpp
Labels: 3.1, 3.2

#32660 [Doc] broken links
  docs/data_source/External_table.md
  docs/deployment/deploy_manually.md
  docs/faq/Others.md
  docs/integrations/other_integrations/intro.md
  docs/quick_start/Deploy.md
  docs/sql-reference/sql-functions/bitmap-functions/sub_bitmap.md
  docs/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-functions/map-functions/map_apply.md
  docs/sql-reference/sql-functions/map-functions/map_values.md
  docs/sql-reference/sql-functions/string-functions/character_length.md
  docs/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/sql-reference/sql-statements/data-definition/ALTER_RESOURCE.md
  docs/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation

#32593 [Enhancement] auto detect and set jvm xmx parameter
  bin/common.sh
  bin/start_fe.sh
Labels: 2.5, 3.0

#31995 [Enhancement] Remove compaction transaction running limit check for cloud native table
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: 3.1, 3.2

#32623 [Doc] add-overview-of-authentication-to-kafka
  docs/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
Labels: documentation

#32635 [BugFix] Fix constructLakeGroups NEP bug when loading colocate index image of new meta format
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
Labels: 3.0, 3.1, 3.2

#32672 [Doc] Mergify/bp/branch 2.5/pr 32660
  docs/data_source/External_table.md
  docs/deployment/deploy_manually.md
  docs/quick_start/Deploy.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-functions/map-functions/map_values.md
  docs/sql-reference/sql-functions/string-functions/character_length.md
  docs/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation

#32680 [Doc] Mergify/bp/branch 2.5/pr 32660
  docs/sql-reference/sql-functions/utility-functions/catalog.md
  docs/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW_TABLES.md
  docs/sql-reference/sql-statements/data-types/data-type-list.md
  docs/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
Labels: documentation

#32645 [Enhancement] Avoid build slice for array_max and array_min
  be/src/column/column_helper.h
  be/src/exprs/array_functions.tpp
Labels: 3.0, 3.1, 3.2

#32683 [UT] Fix broken UT
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  be/test/storage/protobuf_file_test.cpp
Labels: behavior_changed

#32681 [BugFix] Fix iceberg aws "Multiple HTTP implementations were found on the classpath" exception
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
Labels: 3.1, 3.2
