Repository StarRocks/starrocks, pull requests merged in 2023-05, with the labels that each got.

#22789 Update deploy_with_docker.md
  docs/quick_start/deploy_with_docker.md
Labels: documentation, title needs [type]

#22668 [Doc] Update doc for async_load_task_pool_size
  docs/administration/Configuration.md
  docs/loading/Loading_intro.md
Labels: documentation, 2.5, 3.0

#22755 [Enhancement] Add ability to manually compact pk tablets by table or partition
  be/src/common/config.h
  be/src/script/script.cpp
  be/src/storage/olap_server.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: 2.5, 3.0

#22798 [Doc] Update User Privilege Examples
  docs/administration/User_privilege.md
Labels: documentation, 3.0

#22756 [Enhancement] Dump tablet metadata of cloud native table
  be/src/http/CMakeLists.txt
  be/src/http/action/lake/dump_tablet_metadata_action.cpp
  be/src/http/action/lake/dump_tablet_metadata_action.h
  be/src/http/http_stream_channel.cpp
  be/src/http/http_stream_channel.h
  be/src/service/service_be/http_service.cpp
Labels: 3.0

#22814 [Doc] fix markdown lint errors and optimize language
  docs/administration/Profiling.md
  docs/administration/helm.md
  docs/administration/monitor_manage_big_queries.md
  docs/administration/sr_operator.md
  docs/release_notes/release-3.0.md
  docs/using_starrocks/Materialized_view.md
  docs/using_starrocks/sorted_aggregate.md
Labels: documentation, 3.0

#22810 [Enhancement] Add session variable enableQueryTabletAffinity (backport #22809)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: automerge

#22773 [Enhancement] support iso week function (#20511)
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/test/exprs/time_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/week_iso.md
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#22819 [Doc] Fix package version
  docs/quick_start/Deploy.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#22830 [Enhancement] Make transfer log more accurate
  fe/fe-core/src/main/java/com/starrocks/ha/StateChangeExecutor.java
Labels: 2.5, 2.4, 2.3, 3.0

#22821 [BugFix] Preserve the order of the producer in the passthrough queue of Adaptive DOP
  be/src/exec/pipeline/adaptive/collect_stats_context.cpp
  be/src/exec/pipeline/adaptive/collect_stats_context.h
Labels: 3.0

#22663 [Enhancement] Optimize compensatePartitionPredicateForOlapScan to use getPrunedPartitionPredicates instead
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q14.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q15-1.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q15-2.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q15.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q4.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q8.sql
Labels: 3.0

#22853 [Doc] add-faq-for-real-time-synchronization-from-mysql-into-sr
  docs/TOC.md
  docs/faq/loading/synchronize_mysql_into_sr.md
Labels: documentation

#22860 [Doc] add-faq-for-real-time-synchronization-from-mysql-into-sr (#22853)
  docs/TOC.md
  docs/faq/loading/synchronize_mysql_into_sr.md
Labels: documentation

#22861 [Doc] add-faq-for-real-time-synchronization-from-mysql-into-sr (#22853)
  docs/TOC.md
  docs/faq/loading/synchronize_mysql_into_sr.md
Labels: documentation

#22840 [Enhancement] [Cherry-Pick] support to_binary/from_binary function (#20899)
  be/src/exprs/CMakeLists.txt
  be/src/exprs/binary_functions.cpp
  be/src/exprs/binary_functions.h
  be/test/CMakeLists.txt
  be/test/exprs/binary_function_test.cpp
  be/test/exprs/binary_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/binary-functions/from_binary.md
  docs/sql-reference/sql-functions/binary-functions/to_binary.md
  gensrc/script/functions.py
  gensrc/script/gen_functions.py
  test/sql/test_binary_functions/R/test_binary_functions
  test/sql/test_binary_functions/T/test_binary_functions
Labels: documentation, automerge

#22811 [Enhancement] Automatically create block cache directories if it is configured but not exist.
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/service/starrocks_main.cpp
  be/src/storage/options.cpp
  be/src/storage/options.h
  be/test/block_cache/block_cache_test.cpp
Labels: 3.0

#22872 Update membership.md
  community/membership.md
Labels: title needs [type]

#22876 [Doc] add binary function, adjust toc, add version info
  docs/TOC.md
  docs/sql-reference/sql-functions/binary-functions/from_binary.md
  docs/sql-reference/sql-functions/binary-functions/to_binary.md
  docs/sql-reference/sql-functions/crytographic-functions/base64_decode_binary.md
  docs/sql-reference/sql-functions/crytographic-functions/base64_decode_string.md
  docs/sql-reference/sql-functions/math-functions/cosh.md
  docs/sql-reference/sql-functions/math-functions/sinh.md
  docs/sql-reference/sql-functions/math-functions/tanh.md
  docs/sql-reference/sql-functions/string-functions/hex.md
  docs/sql-reference/sql-functions/string-functions/hex_decode_binary.md
  docs/sql-reference/sql-functions/string-functions/hex_decode_string.md
  docs/sql-reference/sql-statements/account-management/SHOW ROLES.md
  docs/sql-reference/sql-statements/data-types/BINARY.md
  docs/sql-reference/sql-statements/data-types/JSON.md
Labels: documentation

#22882 [Doc] cp binary-related to Branch 3.0
  docs/TOC.md
  docs/sql-reference/sql-functions/binary-functions/from_binary.md
  docs/sql-reference/sql-functions/binary-functions/to_binary.md
  docs/sql-reference/sql-functions/crytographic-functions/base64_decode_binary.md
  docs/sql-reference/sql-functions/crytographic-functions/base64_decode_string.md
  docs/sql-reference/sql-functions/math-functions/cosh.md
  docs/sql-reference/sql-functions/math-functions/sinh.md
  docs/sql-reference/sql-functions/math-functions/tanh.md
  docs/sql-reference/sql-functions/string-functions/hex.md
  docs/sql-reference/sql-functions/string-functions/hex_decode_binary.md
  docs/sql-reference/sql-functions/string-functions/hex_decode_string.md
  docs/sql-reference/sql-statements/account-management/SHOW ROLES.md
  docs/sql-reference/sql-statements/data-types/BINARY.md
  docs/sql-reference/sql-statements/data-types/JSON.md
Labels: documentation

#22880 [BugFix] Make all SchemaScanners return one row at a time
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_be_cloud_native_compactions_scanner.cpp
  be/src/exec/schema_scanner/schema_be_compactions_scanner.cpp
  be/src/exec/schema_scanner/schema_be_configs_scanner.cpp
  be/src/exec/schema_scanner/schema_be_logs_scanner.cpp
  be/src/exec/schema_scanner/schema_be_metrics_scanner.cpp
  be/src/exec/schema_scanner/schema_be_tablets_scanner.cpp
  be/src/exec/schema_scanner/schema_be_threads_scanner.cpp
  be/src/exec/schema_scanner/schema_be_txns_scanner.cpp
  be/src/exec/schema_scanner/schema_fe_tablet_schedules_scanner.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#22854 [Enhancement] The replication rules of CTAS are consistent with those of table crea…
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: 2.5, 3.0

#22900 Revert "[Enhancement] Automatically create block cache directories if it is configured but not exist. (backport #22811)"
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/service/starrocks_main.cpp
  be/src/storage/options.cpp
  be/src/storage/options.h
  be/test/block_cache/block_cache_test.cpp
Labels: title needs [type]

#22897 [Enhancement][Cherry-pick] The replication rules of CTAS are consistent with those of table crea…
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: automerge

#22898 [Enhancement][Cherry-Pick] The replication rules of CTAS are consistent with those of table crea…
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: automerge

#22906 [Doc] Update release-3.0.md
  docs/release_notes/release-3.0.md
Labels: documentation

#22871 [Enhancement] Join all the thread to make BE support graceful exit
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: 2.5, 3.0

#22757 [Enhancement] Enable ignore lost segment
  be/src/common/config.h
  be/src/storage/lake/rowset.cpp
Labels: 3.0

#22916 [BugFix][Cherry-Pick][Branch-3.0] Fix parquet late materialize bug for complex types
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/stored_column_reader.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/test_data/map_struct_subfield_optional.parquet
  be/test/formats/parquet/test_data/map_struct_subfield_required.parquet
Labels: automerge

#22886 [BugFix] Fix the memory leak of lambda function
  be/src/exprs/lambda_function.cpp
  be/src/exprs/lambda_function.h
  be/test/exprs/lambda_array_expr_test.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: 2.5, 3.0

#22925 [Doc] fix driver_url, java_home, spark_connector
  docs/data_source/External_table.md
  docs/data_source/catalog/jdbc_catalog.md
  docs/unloading/Spark_connector.md
Labels: documentation, 3.0

#22928 Revert "[Enhancement] Automatically create block cache directories if it is configured but not exist."
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/service/starrocks_main.cpp
  be/src/storage/options.cpp
  be/src/storage/options.h
  be/test/block_cache/block_cache_test.cpp
Labels: title needs [type]

#22933 [Doc] cp change to java_home in hive external table Branch 2.5
  docs/data_source/External_table.md
  docs/unloading/Spark_connector.md
Labels: 2.4

#22943 [BugFix][Cherry-Pick][Branch-3.0] Fix BE access S3 failed when S3 bucket name contains dots
  be/src/common/s3_uri.cpp
  be/test/common/s3_uri_test.cpp
  fe/fe-core/pom.xml
Labels: automerge

#22745 [BugFix] Fix decommission BE failed after dropped materialized view
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
Labels: 2.5, 2.4, 3.0

#22955 [Doc] update data types support for hive catalog
  docs/data_source/catalog/hive_catalog.md
Labels: documentation

#22957 [Doc] update data types support for hive catalog in Branch 3.0
  docs/data_source/catalog/hive_catalog.md
Labels: documentation

#22954 [BugFix] The hdfs client repeatedly executes disconnect when destruct HdfsFsCache
  be/src/fs/hdfs/hdfs_fs_cache.h
Labels: 3.0

#22968 [Doc] Update Download links
  docs/loading/Flink_cdc_load.md
  docs/release_notes/release-2.0.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#22953 [doc] update download link in quickstart
  docs/quick_start/Deploy.md
Labels: documentation, title needs [type]

#22963 [BugFix] Fix the bug of MemTracker use after free when gracefully exit
  be/src/runtime/exec_env.cpp
Labels: 3.0

#22964 [Doc] add param link to broker load
  docs/loading/BrokerLoad.md
Labels: documentation

#22983 [Doc] Update download link in 3.0
  docs/quick_start/Deploy.md
Labels: documentation

#22985 [Doc] add param link to broker load in Branch 2.5
  docs/loading/BrokerLoad.md
Labels: documentation

#22772 [Enhancement] Save the memory use in tablet report
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 2.5, 2.4, 2.3, 3.0

#22688 [BugFix] Fix un-processed NULL_TYPE
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
Labels: 2.5, 2.4, 2.3, 3.0

#22419 [Enhancement] Support query single sync MV by using hint
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/BestIndexRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVProjectAggProjectScanRewrite.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneScanColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/implementation/OlapScanImplementationRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/DistributionPrunerRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/PartitionPruneRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: sig/materialized view

#22962 [BugFix][Cherry-Pick] Fix CTAS will set sql limit (#22813)
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: automerge

#22995 [BugFix] clear destination info of child when removing exchange node (backport #19792)
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: automerge

#22977 [BugFix] clear destination info of child when removing exchange node (backport #19792)
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: automerge

#22966 [BugFix] clear destination info of child when removing exchange node (backport #19792)
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: automerge

#22868 [BugFix] Disable dervie not null predicates for mv rewrite plan
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerConfig.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/IsNullPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinOnClauseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownJoinPredicateBase.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: 3.0

#22922 [BugFix] fix union rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: sig/materialized view, 2.5, 3.0

#22939 [BugFix] Maintaining consistency in BE and FE for the parameter validtion in LEAD/LAG function
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  test/sql/test_lead_lag/R/test_lead_lag
  test/sql/test_lead_lag/T/test_lead_lag
Labels: 2.5, 3.0

#23029 [Cherry-Pick][Feature] hive client pool timeout of iceberg table is configurable
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
Labels: title needs [type]

#23030 [Cherry-Pick][Feature] hive client pool timeout of iceberg table is configurable
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergHiveCatalog.java
Labels: title needs [type]

#23026 [Doc] update external table
  docs/data_source/External_table.md
Labels: documentation

#20835 [Enhancement] Introduce datasketches toolkit
  build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: 3.0

#23039 [Doc] Update Lateral_join.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation

#22961 [BugFix][Cherry-Pick] Fix CTAS will set sql limit (#22813)
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: automerge

#22960 [BugFix][Cherry-Pick] Fix CTAS will set sql limit (#22813)
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: automerge

#23054 [Doc] update external table in Branch 2.4
  docs/data_source/External_table.md
Labels: documentation

#23055 [Doc] update external table in Branch 2.3
  docs/data_source/External_table.md
Labels: documentation

#23060 [Doc] update json length and modify import
  docs/administration/Memory_management.md
  docs/administration/Monitor_and_Alert.md
  docs/loading/DataX-starrocks-writer.md
  docs/quick_start/Architecture.md
  docs/quick_start/Deploy.md
  docs/quick_start/deploy_with_docker.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/SPARK LOAD.md
  docs/sql-reference/sql-statements/data-types/JSON.md
  docs/table_design/Materialized_view.md
  docs/using_starrocks/Using_HLL.md
  docs/using_starrocks/Using_bitmap.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#23067 [Doc] cp json length and bitmap to Branch 2.5
  docs/administration/Memory_management.md
  docs/administration/Monitor_and_Alert.md
  docs/loading/DataX-starrocks-writer.md
  docs/quick_start/Architecture.md
  docs/quick_start/Deploy.md
  docs/quick_start/deploy_with_docker.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/SPARK LOAD.md
  docs/sql-reference/sql-statements/data-types/JSON.md
  docs/table_design/Materialized_view.md
  docs/using_starrocks/Using_HLL.md
  docs/using_starrocks/Using_bitmap.md
Labels: documentation, 2.4, 2.3

#23069 [Doc] cp update json length and modify import to 2.4
  docs/administration/Memory_management.md
  docs/administration/Monitor_and_Alert.md
  docs/loading/DataX-starrocks-writer.md
  docs/quick_start/Architecture.md
  docs/quick_start/Deploy.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/SPARK LOAD.md
  docs/sql-reference/sql-statements/data-types/JSON.md
  docs/table_design/Materialized_view.md
  docs/using_starrocks/Using_HLL.md
  docs/using_starrocks/Using_bitmap.md
Labels: documentation

#23070 [Doc] cp update json length and modify import to 2.3
  docs/administration/Memory_management.md
  docs/administration/Monitor_and_Alert.md
  docs/loading/DataX-starrocks-writer.md
  docs/quick_start/Architecture.md
  docs/quick_start/Deploy.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/SPARK LOAD.md
  docs/sql-reference/sql-statements/data-types/JSON.md
  docs/table_design/Materialized_view.md
  docs/using_starrocks/Using_HLL.md
  docs/using_starrocks/Using_bitmap.md
Labels: documentation

#23068 [BugFix] Fix unstable ut for decommission test
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/DecommissionTest.java
Labels: 2.5, 3.0

#23062 [Enhancement] Fix FE crash bug when replaying delete replica log
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
Labels: 3.0

#23057 [BugFix] Return script execution output as ResultSet
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteScriptExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/qe/ExecuteScriptTest.java
Labels: 2.5, 3.0

#23097 [Doc] fix broken links of create routine load
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/RoutineLoad.md
  docs/loading/load_from_pulsar.md
Labels: documentation

#23098 [Doc] add param link to Broker Load in Branch 2.3
  docs/loading/BrokerLoad.md
Labels: documentation

#23099 [Doc] add param link to Broker Load in Branch 2.4
  docs/loading/BrokerLoad.md
Labels: documentation

#23102 [Doc] fix TOC in Branch 3.0
  docs/TOC.md
Labels: documentation

#23106 [Doc] fix broken links of create routine load
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/RoutineLoad.md
Labels: documentation

#23104 [Doc] fix broken links of create routine load (#23097)
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/RoutineLoad.md
Labels: documentation

#23107 [Doc] fix broken links of create routine load
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/RoutineLoad.md
Labels: documentation

#23103 [Doc]fix broken links of create routine load (#23097)
  docs/loading/Etl_in_loading.md
  docs/loading/Load_to_Primary_Key_tables.md
  docs/loading/RoutineLoad.md
Labels: documentation

#22090 [Enhancement] Populate the block cache with the 'overwrite' option to avoid checking the existence by reading the block.
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/cachelib_wrapper.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/io/cache_input_stream.cpp
  be/test/block_cache/block_cache_test.cpp
Labels: 3.0

#22820 [Enhancement] Avoid printing too many irrelevant logs when be hang
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/pipeline_driver_poller.cpp
Labels: documentation

#23083 [Enhancement] Support date_add function for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/ComplexFunctionCallTransformer.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: 3.0

#23116 [BugFix][Cherry-Pick][Branch-2.5] Fix using wrong parquet column chunk index in dict filter
  be/src/formats/parquet/group_reader.cpp
Labels: automerge

#23027 [BugFix] Disable using bucket keys as local shuffle keys
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: 2.5, 2.4, 2.3, 3.0

#23120 [BugFix] set inString flag correctly when removing comment
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/RemoveCommentTest.java
Labels: 2.4

#22356 [BugFix] overflow in parsing parquet int96 timestamp
  be/src/exec/parquet_reader.cpp
  be/test/exec/parquet_scanner_test.cpp
  be/test/exec/test_data/parquet_data/int96_timestamp.parquet
Labels: 2.5, 2.4, 2.3, 3.0

#22336 [BugFix] Different column types in different chunks
  be/src/column/column_helper.h
  be/src/exec/file_scanner.cpp
Labels: 2.5, 2.4, 3.0

#23144 [BugFix] Fix default catalog name
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java
Labels: 3.0

#22969 [Enhancement] Use memory data size to calculate reader chunk size in cloud native tablet compaction
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/horizontal_compaction_task.h
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset.h
Labels: 3.0

#23147 [Cherry-Pick][Enhancement] Add login info to audit log
  fe/fe-core/src/main/java/com/starrocks/common/AuditLog.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/qe/AuditLogBuilder.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlProtoTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectSchedulerTest.java
Labels: title needs [type]

#23145 [Enhancement] enable enable_background_refresh_connector_metadata config mutable
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 2.5, 3.0

#23155 [Doc] modify parse_json related content
  docs/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/cast.md
  docs/sql-reference/sql-statements/data-types/JSON.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#22611 [Enhancement][BugFix] simplify cancel process of spilling
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.h
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.h
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.h
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
  be/src/exec/spill/spiller.h
  be/src/exec/spill/spiller.hpp
Labels: 3.0

#23132 [Enhancement] add some trace log for dictionary manager
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnDict.java
Labels: 2.5, 2.4, 2.3, 3.0

#23188 [Cherry-Pick][Enhancement] Save the memory use in tablet report
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: title needs [type]

#23170 [BugFix] Different column types in different chunks (backport #22336) (branch-3.0)
  be/src/column/column_helper.h
  be/src/exec/file_scanner.cpp
Labels: automerge

#23158 [BugFix] overflow in parsing parquet int96 timestamp (backport #22356) (branch-2.4)
  be/src/exec/vectorized/parquet_reader.cpp
  be/test/exec/test_data/parquet_data/int96_timestamp.parquet
  be/test/exec/vectorized/parquet_scanner_test.cpp
Labels: automerge

#23171 [BugFix] Different column types in different chunks (backport #22336) (branch-2.5)
  be/src/column/column_helper.h
  be/src/exec/vectorized/file_scanner.cpp
Labels: automerge

#22140 [Enhancement] Dump a new snapshot if persistent index keep too many WAL
  be/src/storage/persistent_index.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#22799 [Enhancement] Support delete sql for primary key table with sort key
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/memtable.h
Labels: 2.5, 3.0

#23195 [Cherry-Pick][BugFix] Fix decommission BE failed after dropped materialized view
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
Labels: title needs [type]

#23194 [Cherry-Pick][BugFix] Fix decommission BE failed after dropped materialized view
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
Labels: title needs [type]

#23204 [Cherry-Pick][Enhancement] Optimize tablet scheduler for large pending tablets case
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: title needs [type]

#23199 [Cherry-Pick][Enhancement] Add hint to insert into error msg if thrift server pool is exhausted
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java
  fe/fe-core/src/main/java/com/starrocks/common/ThriftServerEventProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: title needs [type]

#23203 [Enhancement] The spark load timeout of 5 minutes that waits for yarn to be set is optimized to a custom configuration
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/LoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkEtlJobHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadPendingTaskTest.java
Labels: 3.0

#22699 [Enhancement] Optimize broker access timeout avoid failure when broker load is heavy
  be/src/exec/file_scanner.cpp
Labels: 2.5, 3.0

#23161 [Enhancement] support postgresql db/schema/table/column name upercase and numeric without precision
  be/src/exec/jdbc_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java
Labels: 3.0

#23207 [Enhancement] support mysql streaming resultset
  java-extensions/jdbc-bridge/src/main/java/com/starrocks/jdbcbridge/JDBCScanner.java
Labels: 3.0

#23196 [Doc] add limits in array and align en
  docs/sql-reference/sql-statements/data-types/Array.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#23197 [BugFix] set inString flag correctly when removing comment (backport #23120)
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/RemoveCommentTest.java
Labels: automerge

#23222 [BugFix] Disable using bucket keys as local shuffle keys (backport #23027)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: automerge

#23227 [BugFix] Disable using bucket keys as local shuffle keys (backport #23027)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: automerge, 2.5, 2.4, 2.3, 3.0

#23224 [BugFix] Disable using bucket keys as local shuffle keys (backport #23027)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: automerge, 2.5, 2.4, 2.3, 3.0

#23230 [BugFix] Disable using bucket keys as local shuffle keys (backport #23027)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: automerge, 2.5, 2.4, 2.3, 3.0

#23142 [Doc] Add Hive Meta Polling
  docs/administration/Configuration.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, 2.5, 3.0

#23248 Revert "[BugFix] Different column types in different chunks (#22336) …
  be/src/column/column_helper.h
  be/src/exec/vectorized/file_scanner.cpp
Labels: title needs [type]

#23247 Revert "[BugFix] Different column types in different chunks (#22336)"
  be/src/column/column_helper.h
  be/src/exec/vectorized/file_scanner.cpp
Labels: title needs [type]

#23246 Revert "[BugFix] Different column types in different chunks (#22336)"
  be/src/column/column_helper.h
  be/src/exec/file_scanner.cpp
Labels: title needs [type]

#23245 Revert "[BugFix] Different column types in different chunks (#22336)"
  be/src/column/column_helper.h
  be/src/exec/file_scanner.cpp
Labels: title needs [type]

#23268 [Doc] add Prerequisite to jdbc catalog
  docs/data_source/catalog/jdbc_catalog.md
Labels: documentation

#22078 [Feature] Recover binlog when loading tablets
  be/src/agent/agent_task.cpp
  be/src/storage/binlog_file_reader.cpp
  be/src/storage/binlog_file_reader.h
  be/src/storage/binlog_file_writer.cpp
  be/src/storage/binlog_file_writer.h
  be/src/storage/binlog_manager.cpp
  be/src/storage/binlog_manager.h
  be/src/storage/binlog_util.cpp
  be/src/storage/binlog_util.h
  be/src/storage/data_dir.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/test/storage/binlog_file_test.cpp
  be/test/storage/binlog_manager_test.cpp
  be/test/storage/binlog_test_base.cpp
  be/test/storage/binlog_test_base.h
  be/test/storage/tablet_binlog_test.cpp
  be/test/storage/tablet_meta_test.cpp
  gensrc/proto/binlog.proto
  gensrc/proto/olap_file.proto
Labels: sig/materialized view

#23278 [Doc] update 3.0 toc
  docs/TOC.md
Labels: documentation

#23164 [Doc] add multi-table load to 2 broker load docs
  docs/loading/BrokerLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#23235 [Doc] update docs for deploying starrocks on aws
  docs/TOC.md
  docs/administration/AWS_Cloudformation.md
  docs/administration/starrocks_on_aws.md
  docs/assets/StarRocks_on_AWS_1.png
  docs/assets/StarRocks_on_AWS_2.png
  docs/assets/StarRocks_on_AWS_3.png
  docs/assets/StarRocks_on_AWS_4.png
  docs/assets/StarRocks_on_AWS_5.png
  docs/faq/loading/Routine_load_faq.md
Labels: documentation

#23288 [Doc] update docs for deploying starrocks on aws (#23235)
  docs/administration/AWS_Cloudformation.md
  docs/administration/starrocks_on_aws.md
  docs/assets/StarRocks_on_AWS_1.png
  docs/assets/StarRocks_on_AWS_2.png
  docs/assets/StarRocks_on_AWS_3.png
  docs/assets/StarRocks_on_AWS_4.png
  docs/assets/StarRocks_on_AWS_5.png
  docs/faq/loading/Routine_load_faq.md
Labels: documentation

#22608 [Doc] Fix copy/paste mistake in Bloomfilter_index.md
  docs/using_starrocks/Bloomfilter_index.md
Labels: documentation, 2.5, 2.4, 2.3

#23298 [Doc] add multi-table load to 2 broker load docs in Branch 2.5
  docs/loading/BrokerLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#23299 [Doc] add multi-table load to 2 broker load docs in Branch 2.4
  docs/loading/BrokerLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#23301 [Doc] add multi-table load to 2 broker load docs in Branch 2.3
  docs/loading/BrokerLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#23257 [Enhancement][Cherry-Pick][Branch-2.4] Change primary index hash from crc32 to XXH3_64
  be/src/storage/primary_index.cpp
Labels: automerge

#23303 [Doc] update sql_dialect desc in System variable
  docs/reference/System_variable.md
Labels: documentation

#23237 [Enhancement] The spark load timeout of 5 minutes that waits for yarn to be set is optimized to a custom configuration
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/LoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkEtlJobHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadPendingTaskTest.java
Labels: 2.5

#23309 [Doc] Update System variable
  docs/reference/System_variable.md
Labels: documentation

#22948 aarch64: optimizations to test_hash, make_mask using Neon intrinsics
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
Labels: title needs [type]

#23187 [Enhancement] Support vertical compaction for cloud native non primary key tablet
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/compaction_policy.h
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/lake/tablet_reader.h
  be/src/storage/lake/vertical_compaction_task.cpp
  be/src/storage/lake/vertical_compaction_task.h
  be/test/CMakeLists.txt
  be/test/storage/lake/compaction_task_test.cpp
Labels: 3.0

#23281 [branch-2.4] some trace/bugfix cherry pick
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/DictMappingRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnDict.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: title needs [type]

#23260 [BugFix] support sorted streaming aggregate for array type
  be/src/exec/sorted_streaming_aggregator.cpp
  be/src/runtime/types.cpp
  test/sql/test_sorted_streaming_agg/R/sorted_streaming_agg
  test/sql/test_sorted_streaming_agg/R/sorted_streaming_agg_spill
  test/sql/test_sorted_streaming_agg/T/sorted_streaming_agg
  test/sql/test_sorted_streaming_agg/T/sorted_streaming_agg_spill
Labels: 3.0

#23319 Update deploy_with_docker.md (#22710)
  docs/quick_start/deploy_with_docker.md
Labels: documentation, title needs [type]

#23061 [Enhancement] make map keys unique and implement distinct_map_keys() for external tables
  be/src/column/map_column.cpp
  be/src/column/map_column.h
  be/src/exec/tablet_sink.cpp
  be/src/exprs/map_functions.cpp
  be/src/exprs/map_functions.h
  be/test/column/map_column_test.cpp
  be/test/exprs/map_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/map-functions/distinct_map_keys.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
  gensrc/script/functions.py
Labels: documentation

#23324 [Doc] update release notes
  docs/release_notes/release-2.5.md
  docs/release_notes/release-3.0.md
Labels: documentation

#23330 [Doc] Add SHOW CREATE CATALOG to Branch 2.5
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE CATALOG.md
Labels: documentation

#23328 [Doc] modify cbo-related switch
  docs/reference/System_variable.md
  docs/release_notes/release-2.4.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation, 2.5, 2.4, 3.0

#23176 [Enhancement] add doc about type and correct some behaviors
  docs/TOC.md
  docs/sql-reference/sql-statements/data-types/Map.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
Labels: documentation

#23308 [BugFix] Fix BE schema scan node data distribution
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InformationSchemaBeFeTableTest.java
Labels: 2.5, 2.4, 2.3, 3.0

#23342 [Doc] cherry-pick deprecated variable to Branch 2.5
  docs/reference/System_variable.md
  docs/using_starrocks/Lateral_join.md
Labels: documentation, automerge

#23340 [Doc] update lake table wording in query cache
  docs/using_starrocks/query_cache.md
Labels: documentation

#23143 [BugFix] overflow in parsing parquet int96 timestamp (backport #22356) (branch-2.5)
  be/src/exec/vectorized/parquet_reader.cpp
  be/test/exec/test_data/parquet_data/int96_timestamp.parquet
  be/test/exec/vectorized/parquet_scanner_test.cpp
Labels: automerge

#23300 [Enhancement] Optimize a subtle inline performance problem
  be/src/common/compiler_util.h
  be/src/exec/aggregate/agg_hash_map.h
Labels: 3.0

#23375 [BugFix] Fix show tablet order by limit bug
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
Labels: 2.5, 3.0

#22300 [Enhancement] Support mv_rewrite_staleness param for mv rewrite
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
Labels: 3.0

#22936 [Feature] implement str_to_map()
  be/src/column/map_column.h
  be/src/exprs/CMakeLists.txt
  be/src/exprs/split.cpp
  be/src/exprs/split_part.cpp
  be/src/exprs/str_to_map.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/string-functions/str_to_map.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  gensrc/script/functions.py
Labels: documentation
