Repository StarRocks/starrocks, pull requests merged in 2023-06, with the labels that each got.

#24488 [Doc] Update Iceberg catalog
  docs/data_source/External_table.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#24436 [Enhancement] Support some unicode function transformer for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: 3.0

#24459 [BugFix] fix NPE when valueRelation without alias
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCTETest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q9.sql
Labels: 2.4, 2.3

#24502 [BugFix] forbid rewrite projection with one dict col mapping to multiple output col (backport #24425)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: automerge

#24517 Revert "[Enhancement] Add log to target routine load job timeout (#22623)
  be/src/service/internal_service.cpp
Labels: title needs [type]

#24509 [Doc] Update usage notes in Iceberg catalog
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/integrations/authenticate_to_azure_storage.md
  docs/integrations/authenticate_to_gcs.md
Labels: documentation

#23892 [BugFix] add pushdown predicate process when join reorder
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderHelper.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociateBaseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OuterJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TableFunctionTest.java
Labels: 3.0

#24482 [Enhancement][Cherry-Pick][Branch-2.4] Reset last_compaction_time_ms of PrimaryKey table after clone finished (#20760)
  be/src/storage/tablet_updates.cpp
Labels: automerge

#24183 [BugFix] skip to interpolate spill process if sort spill is disabled
  be/src/exec/topn_node.cpp
Labels: 3.0

#24474 [BugFix] fix the problem that auto spilling trigger timing is wrong
  be/src/exec/spill/query_spill_manager.h
Labels: 3.0

#24157 [Enhancement] Enable config default mv resource group memory and cpu limit.
  be/src/common/config.h
  be/src/exec/workgroup/work_group.cpp
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: sig/materialized view

#24519 [Doc] routine load support avro
  docs/loading/Loading_intro.md
  docs/loading/RoutineLoad.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Labels: documentation

#24522 [Doc] add 2.3.13 rn
  docs/release_notes/release-2.3.md
Labels: documentation

#24535 [Doc] Add Spilling
  docs/TOC.md
  docs/administration/spill_to_disk.md
  docs/reference/System_variable.md
Labels: documentation, 3.0

#24546 [Doc] add 3.0.1 rn
  docs/release_notes/release-3.0.md
Labels: documentation

#24473 [BugFix] fix incorrect LocalExchangePeakMemoryUsage in profile
  be/src/exec/pipeline/exchange/local_exchange_sink_operator.cpp
Labels: 3.0

#24163 [Feature] Support swap materialized view
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ParserErrorMsg.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  test/sql/test_materialized_view/R/test_mv_swap
  test/sql/test_materialized_view/T/test_mv_swap
Labels: sig/materialized view

#24560 [Doc] bugfix in dynamic partitioning
  docs/table_design/dynamic_partitioning.md
Labels: documentation

#24381 [Enhancement] Optimize the error output when alter operation is prohibited
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
Labels: 2.5, 3.0

#24576 [Doc] Fix LTS
  docs/deployment/upgrade.md
Labels: documentation, 2.5, 3.0

#24588 [Doc] Remove deprecated variable
  docs/reference/System_variable.md
Labels: documentation, 2.4, 2.3

#24520 [BugFix] Fix invalid open replicated storage when has limit
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
Labels: 2.5, 3.0

#24585 [Doc] Update data example in Broker Load for Branch 2.5
  docs/loading/BrokerLoad.md
Labels: documentation

#24510 [Enhancement] Refine table creation timedout error message
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 2.4, 2.3, 3.0

#24602 [Doc] Update usage notes in Iceberg catalog
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#24604 [Doc] add v2.5 support for s3-compatible storage
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#24609 [Doc] add v2.5 support for s3-compatible storage
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#24130 [BugFix] drop mv partition deal with function call partition column.
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: sig/materialized view

#24590 [BugFix] Fix HDFS stat information lost in profile and avoid BE crashed when get HDFS stat
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/fs/fs_util.h
  be/src/fs/hdfs/fs_hdfs.cpp
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
Labels: 3.0

#24612 [BugFix] Fix checkpoint failed bug when writing cluster
  fe/fe-core/src/main/java/com/starrocks/cluster/Cluster.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.0

#23348 [Feature] Support function last_day
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/src/types/date_value.cpp
  be/src/types/date_value.h
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/last_day.md
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#24553 [Doc] Add temporary partitions
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
  docs/table_design/Temporary_partition.md
Labels: documentation

#24379 [Feature][Cherry-Pick] Support basic partition by range expr table writeable
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionExprAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExpressionPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ListPartitionDescTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PartitionDescTest.java
Labels: automerge

#24617 [Doc] Add param desc to authenticate to aws
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#24629 [Doc] Add param desc to authenticate to aws in Branch 3.0
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#24630 [Doc] add temorary partitions
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
  docs/table_design/Temporary_partition.md
Labels: documentation

#24633 [Doc] add temorary partitions
  docs/TOC.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
  docs/table_design/Temporary_partition.md
Labels: documentation, title needs [type]

#24580 [Doc] Update support for sr external table in release-3.0.md
  docs/release_notes/release-3.0.md
Labels: documentation

#24465 [BugFix] fix mv on union bug
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  test/sql/test_materialized_view/R/test_materialized_view_union
Labels: sig/materialized view, 2.5, 3.0

#24442 [Enhancement] strip debug symbol in release mode
  build.sh
Labels: 2.5, 3.0

#24527 [Enhancement] Change default create tablet timeout to 10 second
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 2.5, 2.4, 2.3, 3.0

#24648 [Enhancement] Remove unused log
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
Labels: 2.5, 3.0

#24137 [Feature] support struct constructor
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/exprs/struct_functions.cpp
  be/src/exprs/struct_functions.h
  be/test/column/struct_column_test.cpp
  be/test/exprs/struct_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-statements/data-types/STRUCT.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MapType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/StructField.java
  fe/fe-core/src/main/java/com/starrocks/catalog/StructType.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SyntaxSugars.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StructTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
  gensrc/script/functions.py
  gensrc/thrift/Types.thrift
Labels: documentation

#24661 [BugIFx] dont update `bytes_read` when peek fails
  be/src/exec/hdfs_scanner.cpp
Labels: title needs [type]

#24666 Revert "[Tool] Checkout submodules recursive"
  .github/workflows/ci-pipeline-branch.yml
  .github/workflows/ci-pipeline.yml
Labels: title needs [type]

#24404 [Doc] update case expr
  docs/TOC.md
  docs/sql-reference/sql-functions/condition-functions/case_when.md
Labels: documentation, 2.5, 3.0

#24681 [Doc] cp case when to Branch 2.5
  docs/TOC.md
  docs/developers/debuginfo.md
  docs/sql-reference/sql-functions/condition-functions/case_when.md
Labels: documentation

#24678 [Doc] cp case when to Branch 3.0
  docs/TOC.md
  docs/sql-reference/sql-functions/condition-functions/case_when.md
Labels: documentation

#24586 [BugFix] array function doest not process const inputs
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.tpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: 2.5, 2.4, 2.3, 3.0

#24694 [Refactor][cherry-pick][branch-3.0] Adjust the auto tablet distribution for exist table (#24543)
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DistributionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HashDistributionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RandomDistributionInfo.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableAutoTabletTest.java
Labels: automerge

#24672 [Doc] add variables and reorganize
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-definition/ALTER DATABASE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE TABLE.md
Labels: documentation, 3.0

#24704 [BugFix] array function doest not process const inputs (backport #24586)
  be/src/exprs/vectorized/array_functions.cpp
  be/src/exprs/vectorized/array_functions.tpp
  be/test/exprs/vectorized/array_functions_test.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: automerge

#24707 [BugFix] array function doest not process const inputs (backport #24586)
  be/src/exprs/vectorized/array_functions.cpp
  be/src/exprs/vectorized/array_functions.tpp
  be/test/exprs/vectorized/array_functions_test.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: automerge

#24714 [Doc] bugfix in colocate join and routine load (#24710)
  docs/loading/RoutineLoad.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/using_starrocks/Colocate_join.md
Labels: documentation

#24715 [Doc] bugfix in colocate join and routine load (#24710)
  docs/loading/RoutineLoad.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/using_starrocks/Colocate_join.md
Labels: documentation

#24697 [BugFix] array function doest not process const inputs (backport #24586)
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.tpp
  be/test/exprs/array_functions_test.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: automerge

#24711 [BugFix] array function doest not process const inputs (backport #24586)
  be/src/column/array_column.cpp
  be/src/exprs/vectorized/array_functions.cpp
  be/src/exprs/vectorized/array_functions.tpp
  be/test/exprs/vectorized/array_functions_test.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: automerge

#24693 [BugFix] Fix sync analyze stmt print timeout log
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 2.5, 2.4, 3.0

#24719 Update TSC_members.md
  community/TSC_members.md
Labels: title needs [type]

#24734 [Doc] Fix the drop database instance problem in the document
  docs/sql-reference/sql-statements/data-definition/DROP DATABASE.md
Labels: documentation

#22959 [Doc]update 3.0 navigation
  docs/introduction/StarRocks_intro.md
Labels: documentation

#24746 [Doc] update 3.0 navigation
  docs/introduction/StarRocks_intro.md
Labels: documentation

#24748 [Enhancement] Make l0 snapshot size configurable
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/test/exec/sorting_test.cpp
  be/test/test_main.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#24770 [Doc] fix dead link of create table page
  docs/introduction/StarRocks_intro.md
Labels: documentation

#24768 [BugFix] Fix bug force refresh mv failed
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  test/sql/test_materialized_view/R/test_materialized_view_status
  test/sql/test_materialized_view/T/test_materialized_view_status
Labels: 2.5, 3.0

#24777 [Doc] Update Iceberg catalog usage notes
  docs/data_source/External_table.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#24776 [BugFix][Cherry-Pick] Fix bug force refresh failed
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
Labels: automerge

#24751 [BugFix] condition update maybe save duplicate recode if primary key table using persistent index
  be/src/storage/primary_index.cpp
Labels: 2.5, 3.0

#24680 [BugFix] Fix memory illegal modification
  be/src/common/config.h
  be/src/storage/memtable.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/primary_key_encoder.cpp
  be/test/storage/primary_key_encoder_test.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#24641 [Enhancement][Cherry-pick][Branch-2.5] Add zone map for sort key column (#24593)
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
Labels: automerge

#24779 [BugFix][Cherry-Pick] Fix bug force refresh failed
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  test/sql/test_materialized_view/R/test_materialized_view_status
  test/sql/test_materialized_view/T/test_materialized_view_status
Labels: automerge

#24355 [Enhancement] Support struct cast function
  be/src/exprs/cast_expr.cpp
  be/src/exprs/cast_nested.cpp
  docs/sql-reference/sql-statements/data-types/STRUCT.md
  fe/fe-core/src/main/java/com/starrocks/analysis/SubfieldExpr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/StructType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/NormalizePredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StructTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
  test/sql/test_semi/R/test_struct
  test/sql/test_semi/T/test_struct
Labels: documentation

#24758 [BugFix][Cherry-Pick] CP statistics bugs to Branch 2.4
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: automerge

#24759 [BugFix][Cherry-Pick] CP statistics bugs to Branch 2.5
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: automerge

#24792 [BugFix][Cherry-pick][Branch-3.0] Fix memory illegal modification (#24680)
  be/src/common/config.h
  be/src/storage/memtable.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/primary_key_encoder.cpp
  be/test/storage/primary_key_encoder_test.cpp
Labels: automerge

#24808 [BugFix][cherry-pick][branch-2.5] Don't set default bucket num for table when not specified
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#24807 [BugFix][cherry-pick][branch-3.0] Don't set default bucket num for table when not specified
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#24793 [BugFix] Fix bug drop not exists task NPE
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  test/sql/test_task/R/test_drop
  test/sql/test_task/T/test_drop
Labels: 2.5, 3.0

#24810 [Enhancement] Reduce unnecessary computation
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
Labels: 2.5, 2.4, 3.0

#24828 [BugFix][Cherry-Pick] Fix bug drop not exists task NPE
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
Labels: automerge

#24829 [Enhancement] clear unsupported keys from array nested types (backport #24811)
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeLateralTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
Labels: automerge

#24803 [Enhancement] Do not display type when table comment is empty
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowTableStmtTest.java
  test/sql/test_default_enable_replicated_storage/R/test_enable_mv
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_random_distribution/R/test_random_distribution
Labels: 2.5, 3.0

#24837 [BugFix] Fix invalid available_chunk_source_count make broker load hang
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
Labels: 2.5, 3.0

#24839 [Doc] Update authenticate to aws
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#24806 [Enhancement] Detailed error message of invalid table state
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/InvalidOlapTableStateException.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 2.4, 2.3, 3.0

#24855 [Doc] Update authenticate to aws in Branch 3.0
  docs/integrations/authenticate_to_aws_resources.md
Labels: documentation

#24801 [BugFix] Fix residual insert query when it already fail
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
Labels: 2.5, 3.0

#24834 [Doc] add 2 i/o variables and optimize
  docs/reference/System_variable.md
Labels: documentation, 3.0

#24696 [Enhancement] change map type constructor to aovid conflicting with json or struct
  docs/sql-reference/sql-statements/data-types/Map.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MapExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MapTypeTest.java
  test/sql/test_function/R/test_conditional_fn
  test/sql/test_function/T/test_conditional_fn
  test/sql/test_semi/R/test_struct
  test/sql/test_semi/T/test_struct
Labels: documentation

#24862 [BugFix] Fix LDAP Auth miss check password result bug
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProviderForNative.java
Labels: 3.0

#24874 [Doc] cp add 2 variables to Branch 2.5
  docs/reference/System_variable.md
Labels: documentation

#24873 [Doc] Update Configuration.md
  docs/administration/Configuration.md
Labels: documentation

#24882 [Doc] [Doc] Update Configuration.md
  docs/administration/Configuration.md
Labels: documentation

#24883 [Doc] Update Configuration.md
  docs/administration/Configuration.md
Labels: documentation

#24879 [Doc] Update Configuration.md in Branch 3.0
  docs/administration/Configuration.md
Labels: documentation

#24533 [Feature][CherryPick] support view in materialized view for 3.0 (#23476)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstTraverser.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: documentation

#24911 [Doc] remove NEGATIVE from kerberos in BROKER LOAD
  docs/administration/Configuration.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24917 [Doc] remove NEGATIVE from kerberos in BROKER LOAD in Branch 3.0
  docs/administration/Configuration.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24918 [Doc] remove NEGATIVE from kerberos in BROKER LOAD in Branch 2.5
  docs/administration/Configuration.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24920 [Doc] remove NEGATIVE from kerberos in BROKER LOAD in Branch 2.3
  docs/administration/Configuration.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24858 [Enhancement] Decorrelate the NetworkTime calculation from the system clocks
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
  be/src/service/internal_service.cpp
  gensrc/proto/internal_service.proto
Labels: 2.5, 2.4, 2.3, 3.0

#24921 [Feature][Cherry-Pick] Support automatic partition by value
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/PartitionMeasure.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  test/sql/test_automatic_partition/R/test_automatic_partition_list
  test/sql/test_automatic_partition/T/test_automatic_partition_list
Labels: automerge

#24931 [Doc] align desc params in BROKER LOAD
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24934 [Doc] align desc params in BROKER LOAD for Branch 2.5
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24922 [BugFix] Fix cancel load failure because of non existed table
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.0

#24936 [Enhancement][Cherry-pick][Branch-3.0] Add property prefix in Iceberg rest catalog
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
Labels: automerge

#24899 [BugFix] Make pipeline_driver's total_timer exclude the prepare time
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: 2.5, 2.4, 2.3, 3.0

#24949 [BugFix] Fix audit log bug for create OLAP table
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTableStmt.java
Labels: 2.5

#24910 [BugFix] Fix be not become dead when it restart in short time
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
Labels: 2.5, 2.4, 3.0

#24948 [Enhancement] support dynamice config apply thread count
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/storage/update_manager.cpp
Labels: 2.5, 3.0

#24725 [Enhancement] Make cloud native table query robust when BE restart
  fe/fe-core/src/main/java/com/starrocks/qe/SimpleScheduler.java
  fe/fe-core/src/test/java/com/starrocks/qe/SimpleSchedulerTest.java
Labels: 3.0

#23843 [Enhancement] Make pk table compaction's rowset size threshold large and configurable
  be/src/common/config.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: 3.0

#24944 [Doc] Update BROKER LOAD
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24970 [Doc] Update BROKER LOAD in Branch 2.3
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#24973 [Doc] Modify NEGATIVE note in BROKER LOAD
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#24909 [BugFix] fix comment lost escape character
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 2.5, 2.4, 3.0

#24692 [Feature] support any/all_match() for arrays
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/src/exprs/array_functions.tpp
  be/test/exprs/array_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/all_match.md
  docs/sql-reference/sql-functions/array-functions/any_match.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: documentation

#24747 [Enhancement] mv rewrite support time_slice
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: sig/materialized view

#24749 [Enhancement] Make repair for bad tablet start ASAP
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PriorityRepairProcNode.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AdminStmtAnalyzer.java
Labels: 2.5, 3.0

#24757 [BugFix][Cherry-Pick] statistics bug to Branch 3.0
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectSchedulerTest.java
Labels: automerge

#25007 [BugFix] fix comment lost escape character (backport #24909)
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: automerge

#25003 [BugFix] fix comment lost escape character (backport #24909)
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
Labels: automerge

#24955 [Enhancement] Implement remove_first_n_values of MapColumn and ArrayColumn
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/map_column.cpp
  be/src/column/map_column.h
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
  test/sql/test_map/R/test_map
  test/sql/test_map/T/test_map
Labels: 3.1

#24802 [Enhancement] Add ls_tablet_dir to script engine
  be/src/script/script.cpp
Labels: 2.5, 3.0

#25032 [BugFix] Fix NPE
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: 2.4, 2.3

#24942 [BugFix] fix cloud table does not support cross db colocation
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColocateTableIndexTest.java
Labels: 3.0

#24999 [BugFix] Make the role list comparison deterministic
  fe/fe-core/src/test/java/com/starrocks/privilege/AuthorizationMgrTest.java
Labels: 3.0, 3.1

#24353 [Enhancement] add more memory usage profiles for spill
  be/src/exec/hash_join_components.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.h
  be/src/exec/pipeline/nljoin/nljoin_context.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/input_stream.h
  be/src/exec/spill/mem_table.cpp
  be/src/exec/spill/mem_table.h
  be/src/exec/spill/serde.cpp
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
  be/src/exec/spill/spiller.cpp
  be/src/exec/spill/spiller.h
  be/src/exec/spill/spiller.hpp
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/data_stream_recvr.h
  be/src/runtime/sender_queue.cpp
  be/src/util/runtime_profile.h
Labels: 3.0

#25074 [BugFix] add pushdown predicate process when join reorder (backport #23892)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderHelper.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociateBaseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OuterJoinReorderTest.java
Labels: automerge

#25075 [Doc] Update Insert upon verification
  docs/loading/InsertInto.md
Labels: documentation, 2.5, 3.0, 3.1

#24996 [BugFix] Fix colocate table across different db not working
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 2.5, 3.0, 3.1

#25061 [BugFix] Fix grants_to system table incorrectly showing deleted objects bug
  fe/fe-core/src/main/java/com/starrocks/catalog/system/starrocks/GrantsTo.java
Labels: 3.0, 3.1

#25080 [Enhancement] Make forward compatibility easier when adding new priv obj
  fe/fe-core/src/main/java/com/starrocks/privilege/ForwardCompatiblePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
Labels: 3.1

#25005 [Enhancement] Support insert overwrite specify partition for automatic partition table
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  test/sql/test_automatic_partition/R/test_insert_overwrite
  test/sql/test_automatic_partition/T/test_insert_overwrite
Labels: 3.0, 3.1

#25071 [Enhancement] List partition name to value encoding
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzerUtilsTest.java
Labels: 3.0, 3.1

#24962 [BugFix] Fix incorrect error message when create routine load failed
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
Labels: 2.5, 3.0

#25068 [Feature] support any/all_match() for arrays (backport #24692)
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/src/exprs/array_functions.tpp
  be/test/exprs/array_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/all_match.md
  docs/sql-reference/sql-functions/array-functions/any_match.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: documentation

#25120 [Enhancement] Opt the memory usage of ordinal index
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
Labels: 2.5, 2.4, 3.0, 3.1

#25030 [Enhancement] Improve storage volume backward compatibility
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedNothingStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1

#25034 [BugFix] array_agg order by nest types
  docs/sql-reference/sql-functions/array-functions/array_agg.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
Labels: documentation, 3.0, 3.1

#25114 [Refactor] adjust default value of some configs
  docs/administration/Configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: documentation

#25045 [Doc] reorganize show tablet and add return fields
  docs/sql-reference/sql-statements/data-manipulation/SHOW TABLET.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0, 3.1

#24856 [BugFix] fix external table commit timeout treated as failure
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: 2.5, 2.4, 2.3, 3.0

#25066 [BugFix] array func's inputs should be array
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  test/sql/test_array_fn/R/test_array_fn
Labels: 3.1

#25152 [BugFix] Fix bug automatic partition lost slot id
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.0, 3.1

#25156 [BugFix] fix external table commit timeout treated as failure (backport #24856)
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: automerge

#25165 [BugFix] fix external table commit timeout treated as failure (backport #24856)
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: automerge

#25077 [Doc] Add DROP TASK and ALTER MV ACTIVE
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
  docs/sql-reference/sql-statements/data-manipulation/DROP TASK.md
  docs/sql-reference/sql-statements/data-manipulation/SUBMIT TASK.md
Labels: documentation

#25166 [Enhancement][Cherry-Pick] Support insert overwrite specify partition for automatic partition table
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  test/conf/sr.conf
  test/sql/test_automatic_partition/R/test_insert_overwrite
  test/sql/test_automatic_partition/T/test_insert_overwrite
Labels: automerge

#25175 [Doc] Add DROP TASK and ALTER MV ACTIVE (#25077)
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
  docs/sql-reference/sql-statements/data-manipulation/DROP TASK.md
  docs/sql-reference/sql-statements/data-manipulation/SUBMIT TASK.md
Labels: documentation
