Repository StarRocks/starrocks, pull requests merged in 2023-12, with the labels that each got.

#35813 [BugFix] Fix pindex background compaction bug
  be/src/storage/persistent_index.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36164 [BugFix] Check duplicate column names in files sink
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: 3.2

#36214 Revert "[BugFix] limit lake table publish version thread pool size (backport #35637)"
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/PublishVersionDaemonTest.java
Labels: title needs [type]

#35983 [BugFix] Support union rewrite by pulling up query's extra predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RewriteContext.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
Labels: 3.2

#36223 [BugFix] spillable partition sort sink use-after-free
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/pipeline/spill_process_channel.h
  test/sql/test_spill/R/test_short_circuit
  test/sql/test_spill/T/test_short_circuit
Labels: 3.0, 3.1, 3.2

#36169 [Doc] Add some materialized view' configurations in docs
  docs/en/administration/Configuration.md
  docs/zh/administration/Configuration.md
Labels: documentation, 3.2

#36146 [Enhancement] Add a config to enable/disable mv active checker
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MVActiveChecker.java
Labels: 3.1, 3.2

#36101 [Enhancement]enlarge default virtual node number be more friendly to cache
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: 3.1, 3.2

#36226 [BugFix] fix deadlock when suspend pipe
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeManager.java
Labels: 3.2

#36261 [Doc] Add 2.5.16 and 2.5.15 rn
  docs/en/release_notes/release-2.5.md
  docs/zh/release_notes/release-2.5.md
Labels: documentation

#36259 Revert "[BugFix] Fix paimon jni reader may explore the hive metastore (backport #35777)"
  be/src/connector/hive_connector.cpp
  be/src/exec/jni_scanner.cpp
  be/src/exec/jni_scanner.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  gensrc/thrift/Descriptors.thrift
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
Labels: title needs [type]

#36068 [Enhancement] Add IO profiler
  be/src/agent/agent_task.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/fs/fs_posix.cpp
  be/src/http/action/pprof_actions.cpp
  be/src/http/action/pprof_actions.h
  be/src/io/CMakeLists.txt
  be/src/io/fd_input_stream.cpp
  be/src/io/fd_output_stream.cpp
  be/src/io/io_profiler.cpp
  be/src/io/io_profiler.h
  be/src/script/script.cpp
  be/src/service/service_be/http_service.cpp
  be/src/storage/memtable.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/primary_index.cpp
  be/src/storage/segment_flush_executor.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/task/engine_alter_tablet_task.cpp
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#36224 [BugFix] fix persistent index link file failure when old files remain
  be/src/storage/persistent_index.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36272 [BugFix] Fix refresh for mv with complex name
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskBuilderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshTest.java
Labels: 3.0, 3.1, 3.2

#36281 [BugFix] fix large binary column overflow when column writer append
  be/src/column/binary_column.cpp
  be/src/storage/rowset/column_writer.cpp
  be/test/storage/rowset/column_reader_writer_test.cpp
Labels: 3.1, 3.2

#36301 [Doc] rename markdownlint config
  .github/workflows/ci-doc-checker.yml
  docs/.markdownlint.json
Labels: documentation, 3.0, 3.1, 3.2

#36235 [Doc] document for array_unique_agg
  docs/en/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/zh/sql-reference/sql-functions/array-functions/array_unique_agg.md
Labels: documentation, 3.2

#36040 [Enhancement] print error message when create catalog with failure
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/unified/UnifiedConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogMgrTest.java
Labels: behavior_changed

#36292 [BugFix] fix update replica version by mistake in txn log applier
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#36180 [Enhancement] try to avoid acquire lock in metric
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsRegistry.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
Labels: 2.5, 3.0, 3.1, 3.2

#36258 [BugFix] fix hive scanner read sturct with char and varchar type
  be/test/exec/test_data/jni_scanner/test_hive_format/struct.seq
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
  test/sql/test_external_file/R/test_hive_jni_format
  test/sql/test_external_file/T/test_hive_jni_format
Labels: 3.2

#35392 [Doc] Align CN shared data deploy
  docs/en/assets/commonMarkdown/sharedDataUse.md
  docs/en/deployment/deploy_broker.md
  docs/en/deployment/shared_data/hdfs.md
  docs/en/deployment/shared_data/other.md
  docs/en/using_starrocks/Materialized_view-single_table.md
  docs/zh/assets/commonMarkdown/sharedDataCNconf.md
  docs/zh/assets/commonMarkdown/sharedDataIntro.md
  docs/zh/assets/commonMarkdown/sharedDataUse.md
  docs/zh/assets/commonMarkdown/sharedDataUseIntro.md
  docs/zh/deployment/deploy_broker.md
  docs/zh/deployment/deploy_shared_data.md
  docs/zh/deployment/shared_data/azure.md
  docs/zh/deployment/shared_data/gcs.md
  docs/zh/deployment/shared_data/hdfs.md
  docs/zh/deployment/shared_data/minio.md
  docs/zh/deployment/shared_data/other.md
  docs/zh/deployment/shared_data/s3.md
  docs/zh/using_starrocks/Materialized_view-single_table.md
Labels: documentation, 3.2

#36350 [Doc] Minor fix
  docs/docusaurus/sidebars.json
  docs/en/assets/commonMarkdown/sharedDataIntro.md
  docs/en/deployment/deploy_shared_data.md
  docs/zh/deployment/deploy_manually.md
  docs/zh/deployment/deploy_shared_data.md
  docs/zh/deployment/deployment_overview.md
  docs/zh/introduction/Features.md
  docs/zh/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.1.md
  docs/zh/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/table_design/Data_distribution.md
  docs/zh/table_design/expression_partitioning.md
  docs/zh/table_design/list_partitioning.md
Labels: documentation, 3.2

#36346 [BugFix] Fix bucket colocate agg error when enable spill
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.h
  be/src/exec/pipeline/bucket_process_operator.cpp
  be/src/exec/pipeline/bucket_process_operator.h
  be/src/exec/pipeline/spill_process_channel.h
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/spiller.hpp
  test/sql/test_spill/R/test_spill_aggregate
  test/sql/test_spill/T/test_spill_aggregate
Labels: 3.2

#36351 [BugFix] Fix full sort circular reference leak
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
Labels: 3.0, 3.1, 3.2

#36192 [Enhancement] Improved file delete method during vacuum process
  be/src/storage/lake/vacuum.cpp
Labels: 3.1, 3.2

#36371 [BugFix] hive jni scanner with rcbinary deal with timezone
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveColumnValue.java
  test/sql/test_external_file/R/test_hive_jni_format
  test/sql/test_external_file/T/test_hive_jni_format
Labels: 3.2

#36387 [Doc] fix links in 3.2
  docs/zh/data_source/External_table.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
Labels: documentation

#36336 [BugFix] Fix load fail when load multi partition and enable lake_enable_batch_publish_version
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateBatch.java
Labels: 3.2

#36339 [BugFix] Fix OlapTableSink close crash if it is not prepare success
  be/src/exec/tablet_sink.cpp
Labels: 3.1, 3.2

#36380 [BugFix] fix mv task definition bug after mv rename
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskBuilderTest.java
Labels: 3.0, 3.1, 3.2

#33538 [Enhancement] Support bitmap_hash for count(distinct x) rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateFunctionRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateExtractor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/BitmapRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/CountRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/DateTruncEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/EquivalentShuttleContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IAggregateRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IPredicateRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/RewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/TimeSliceRewriteEquivalent.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
Labels: 3.2

#36406 [Doc] Fix links 25
  docs/docusaurus/sidebars.json
  docs/en/cover_pages/functions_like.mdx
  docs/zh/cover_pages/functions_like.mdx
  docs/zh/data_source/External_table.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
Labels: documentation

#35897 [BugFix] Add direct error message for optimize restrict
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/OptimizeClause.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
Labels: 3.2

#36411 [Doc] Change loading mode to loading method in stream load doc
  docs/en/loading/StreamLoad.md
Labels: documentation

#36236 [BugFix] fix lakeTaskExecutor in PublishVersionDaemon
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/PublishVersionDaemonTest.java
Labels: behavior_changed

#36003 [Doc] update 3.2 doc "dynamically add buckets for randomly distributed table"
  docs/en/table_design/Data_distribution.md
  docs/zh/table_design/Data_distribution.md
Labels: documentation, 3.2

#36177 [BugFix] fix ArrayIndexOutOfBoundsException in HiveScanner
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveScanner.java
Labels: 3.2

#36377 [BugFix] Check whether the result column generated by array_agg overflows
  be/src/exprs/agg/array_agg.h
Labels: 2.5, 3.0, 3.1, 3.2

#36248 [Doc]correctify temporary partition parameter name in broker load statement
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
Labels: documentation

#36421 [Doc] Refine Information Schema and fix Where
  docs/docusaurus/sidebars.json
  docs/en/reference/information_schema/information_schema.md
  docs/en/reference/overview-pages/information_schema.md
  docs/en/release_notes/release-2.5.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/Materialized_view-single_table.md
  docs/en/using_starrocks/Materialized_view.md
  docs/zh/reference/information_schema/information_schema.md
  docs/zh/reference/overview-pages/information_schema.md
  docs/zh/release_notes/release-2.5.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/Materialized_view-single_table.md
  docs/zh/using_starrocks/Materialized_view.md
Labels: documentation, 3.2

#36257 [Enhancement] Handle timeouts in compaction
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  gensrc/proto/lake_service.proto
Labels: 3.1, 3.2, PROTO-REVIEW

#36434 [Doc] Backport pr 36421
  docs/docusaurus/sidebars.json
  docs/en/reference/information_schema/information_schema.md
  docs/en/reference/overview-pages/information_schema.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/Materialized_view-single_table.md
  docs/en/using_starrocks/Materialized_view.md
  docs/zh/reference/information_schema/information_schema.md
  docs/zh/reference/overview-pages/information_schema.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/Materialized_view-single_table.md
  docs/zh/using_starrocks/Materialized_view.md
Labels: documentation, automerge

#36399 [BugFix] Fix create/alter table with zero bucket size
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTableTest.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
Labels: 3.2

#36344 [BugFix] make convert_tz microsecond-aware
  be/src/exprs/time_functions.cpp
  be/src/types/timestamp_value.cpp
  be/src/types/timestamp_value.h
  test/sql/test_time_fn/R/test_convert_tz
  test/sql/test_time_fn/T/test_convert_tz
Labels: 3.2

#36357 [BugFix] Pushdown distinct agg across window not support complex expr
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownDistinctAggregateRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregatePushDownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/pushdown_distinct_agg_below_window2.json
  test/sql/test_push_down_distinct_agg_across_window/R/test_push_down_distinct_agg_across_window
  test/sql/test_push_down_distinct_agg_across_window/T/test_push_down_distinct_agg_across_window
Labels: 2.5, 3.0, 3.1, 3.2

#36407 [Doc] Add Loading_data_template.md to zh in 3.2 to fix check error
  docs/zh/loading/Loading_data_template.md
Labels: documentation

#36474 [Doc] Fix sidebar
  docs/docusaurus/sidebars.json
Labels: documentation

#36447 [BugFix] fix lakeTaskExecutor in PublishVersionDaemon (#36236)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/PublishVersionDaemonTest.java
Labels: behavior_changed

#31109 [BugFix] Fix a typo in error message
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.2

#35799 [Enhancement] Add additional information when Avro scanner parsing timeout
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: 3.0, 3.1, 3.2

#36479 [Enhancement] only do tablet commit info check when replica is normal
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionStateTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#36454 [Enhancement] add `static_query_mem_limit` absolute value for query memory limit
  be/src/exec/connector_scan_node.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/io/shared_buffered_input_stream.cpp
Labels: 3.1, 3.2

#36113 [Enhancement] Add a runtime config to enable log stream load request/response
  be/src/common/config.h
  be/src/http/action/stream_load.cpp
  be/src/http/action/transaction_stream_load.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36498 [BugFix] Pushdown distinct agg across window not support complex expr(backport #36357)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownDistinctAggregateRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregatePushDownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/pushdown_distinct_agg_below_window2.json
  test/sql/test_push_down_distinct_agg_across_window/R/test_push_down_distinct_agg_across_window
  test/sql/test_push_down_distinct_agg_across_window/T/test_push_down_distinct_agg_across_window
Labels: 3.1, backport_ok

#36499 [BugFix] Pushdown distinct agg across window not support complex expr(backport #36357)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownDistinctAggregateRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregatePushDownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/pushdown_distinct_agg_below_window2.json
  test/sql/test_push_down_distinct_agg_across_window/R/test_push_down_distinct_agg_across_window
  test/sql/test_push_down_distinct_agg_across_window/T/test_push_down_distinct_agg_across_window
Labels: 3.2, backport_ok

#36503 [Doc] use relative path for the internal links
  docs/en/loading/automq-routine-load.md
  docs/zh/loading/automq-routine-load.md
Labels: documentation, 3.1, 3.2

#36476 [BugFix] fix jni scanner handle decimal type
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
Labels: 3.2

#36516 [Doc] Update behavior change about timeout setting in 3.1.0 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#36518 [Doc] Remove txn_commit_rpc_timeout_ms from Parameter configuration doc
  docs/en/administration/Configuration.md
  docs/zh/administration/Configuration.md
Labels: documentation, 3.1, 3.2

#36448 [BugFix] fix lakeTaskExecutor in PublishVersionDaemon (#36236)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/PublishVersionDaemonTest.java
Labels: behavior_changed

#36253 [Doc] Analyze external table
  docs/en/administration/Configuration.md
  docs/en/data_source/catalog/hudi_catalog.md
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-functions/date-time-functions/week_iso.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/zh/administration/Configuration.md
  docs/zh/reference/System_variable.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.2

#36453 [Enhancement] compute node skip update report version when create table
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 3.1, behavior_changed, 3.2

#36543 [Doc] fix sql (missing bracket) - Update CREATE_ROUTINE_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#36566 [BugFix] no throw exception when loading plugin fail
  fe/fe-core/src/main/java/com/starrocks/plugin/PluginMgr.java
  fe/fe-core/src/test/java/com/starrocks/plugin/PluginMgrTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#36478 [BugFix] Fix actual fields size in csv scanner
  be/src/exec/csv_scanner.cpp
  be/src/exec/file_scanner.h
  be/test/exec/csv_scanner_test.cpp
Labels: 3.1, 3.2

#33432 [BugFix] BE in ASAN mode may crash when ingestion and drop tablet concurrently
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/src/storage/update_manager.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36384 [BugFix] Fix export task split in cloud native table export job
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/test/java/com/starrocks/load/ExportJobTest.java
Labels: 3.0, 3.1, 3.2

#36603 [Enhancement] support reading lake data using http api
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
Labels: 3.2

#36475 [Enhancement] [UT] Add PlannerDebugOptions to support debug options for query tests
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/Tracers.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/QueryDebugOptions.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewHiveTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
Labels: 3.2, META-REVIEW

#36618 [Doc] change name of like_predicate
  docs/en/sql-reference/sql-functions/like-predicate-functions/like.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_extract.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_replace.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/like.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/regexp.md
Labels: documentation

#36621 [Doc] Fix a spelling error
  docs/en/integrations/authenticate_to_azure_storage.md
Labels: documentation

#36623 [Doc] resolve conflict in 3.0
  docs/zh/administration/Configuration.md
Labels: documentation

#36349 Update array_generate.md
  docs/zh/sql-reference/sql-functions/array-functions/array_generate.md
Labels: documentation, title needs [type]

#36626 remove array_generate from 3.0
  docs/en/sql-reference/sql-functions/array-functions/array_generate.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/zh/release_notes/release-3.0.md
  docs/zh/sql-reference/sql-functions/array-functions/array_generate.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation, title needs [type]

#36388 [Enhancement] Introduced a timeout parameter for lake::PublishVersionRequest
  be/src/agent/agent_server.cpp
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/storage/lake/transactions.cpp
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
  be/src/util/time.h
  be/test/service/lake_service_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
  gensrc/proto/lake_service.proto
Labels: 3.1, 3.2, PROTO-REVIEW

#36641 [BugFIx][Branch-3.2] Fix bug FE can not start when getPhysicalPartition return null
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: title needs [type]

#34854 [Enhancement] Optimize shuffle join with skew data
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/JoinRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildOutputPropertyGuarantor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/JoinHelper.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SkewJoinOptimizeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneShuffleColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinTest.java
Labels: behavior_changed, 3.2

#36601 [Enhancement] more timely memory release about cloud native pk table compaction
  be/src/storage/lake/update_compaction_state.cpp
Labels: 3.1, 3.2

#36635 [Enhancement] Return the error message of the publish version task to the FE
  be/src/service/service_be/lake_service.cpp
  be/test/service/lake_service_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  gensrc/proto/lake_service.proto
Labels: 3.1, 3.2, PROTO-REVIEW

#36625 [Bugfix] fix broken sqlcase mv_basic
  test/sql/test_materialized_view/R/test_create
Labels: title needs [type]

#36675 [Doc] clarify the data formats supported by kafka connector
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#36534 [Enhancement] scale compaction score to a reasonable and user friendly range
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#36702 [Doc] Refine starlet_port desc
  docs/en/administration/Configuration.md
  docs/en/deployment/environment_configurations.md
  docs/zh/administration/Configuration.md
  docs/zh/deployment/environment_configurations.md
Labels: documentation, 3.0, 3.1, 3.2

#36685 [BugFix] fix --enable-shared-data option for be ut script
  run-be-ut.sh
Labels: 3.2

#36717 [BugFix] clear iceberg partitionNames cache after iceberg sink
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.2

#36731 [BugFix] fix delete flag lost in persistent index minor compact
  be/src/block_cache/cache_options.h
  be/src/storage/persistent_index.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36563 [BugFix] Fast schema evolution task lost default expr
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableAddOrDropColumnsInfo.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/persist/TableAddOrDropColumnsInfoTest.java
  test/sql/test_ddl/R/test_alter_pk_reorder
  test/sql/test_ddl/T/test_alter_pk_reorder
  test/sql/test_fast_schema_evolution/R/test_fast_schema_evolution
  test/sql/test_fast_schema_evolution/T/test_fast_schema_evolution
Labels: 3.2, META-REVIEW

#36710 [Enhancement] upgrade staros to v3.2-rc4
  be/src/fs/fs_starlet.cpp
  be/test/fs/fs_starlet_test.cpp
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
Labels: 3.2

#36627 [BugFix] Fix the issue of filesystem class conflicts due to the introduction of paimon dependency
  fe/fe-core/pom.xml
  java-extensions/paimon-reader/pom.xml
Labels: 3.2

#36732 [BugFix] Fix optimize job replay fail when partial partition fail
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/ReplacePartitionOperationLog.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/DDLTestBase.java
Labels: 3.2, META-REVIEW

#36560 [Enhancement] Add default_mv_partition_refresh_number to set default partition_refresh_num
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVTestUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVRewriteWithSchemaChangeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_create_mv_with_params
  test/sql/test_materialized_view/T/test_create_mv_with_params
Labels: behavior_changed, 3.2

#36676 [Feature] support microsecond-aware now function
  be/src/exprs/time_functions.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/test/exprs/time_functions_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  gensrc/thrift/InternalService.thrift
Labels: behavior_changed, PROTO-REVIEW

#36779 [Doc] Add cover page for shared-data deployment
  docs/zh/cover_pages/shared_data_deployment.mdx
Labels: documentation, 3.2

#36473 [BugFix] Fix iceberg mv refresh NPE when snapshot is expired
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergPartitionUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: 3.1, 3.2

#36774 [Enhancement] Use Starlet's read_all() interface to read metadata in shared data mode
  be/src/fs/fs_starlet.cpp
Labels: 3.2

#36786 [Doc] Create management.mdx
  docs/zh/cover_pages/management.mdx
Labels: documentation

#36338 [BugFix]Fix NPE when enable batch publish
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateBatch.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.2

#36470 [Feature] Support from_unixtime for partition by expr part 1
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionExprAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExpressionPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  test/sql/test_partition_by_expr/R/test_expr_from_unixtime
  test/sql/test_partition_by_expr/R/test_expr_substr
  test/sql/test_partition_by_expr/R/test_expr_substr_add_partition
  test/sql/test_partition_by_expr/R/test_expr_substr_prune_partition
  test/sql/test_partition_by_expr/T/test_expr_from_unixtime
  test/sql/test_partition_by_expr/T/test_expr_substr
  test/sql/test_partition_by_expr/T/test_expr_substr_add_partition
  test/sql/test_partition_by_expr/T/test_expr_substr_prune_partition
Labels: behavior_changed

#36592 [Feature]Support crc32 function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/string-functions/crc32.md
  gensrc/script/functions.py
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: documentation

#36806 [Doc] Add authentication keywords to aws policies doc
  docs/en/reference/aws_iam_policies.md
  docs/zh/reference/aws_iam_policies.md
Labels: documentation

#36796 [Doc] Align capitalization of func names
  docs/en/sql-reference/sql-functions/scalar-functions/hll_cardinality.md
  docs/en/sql-reference/sql-functions/utility-functions/isnull.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/json_array.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/json_object.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_each.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_exists.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_query.md
  docs/zh/sql-reference/sql-functions/math-functions/rand.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#36780 [BugFix] Fix DataStreamRecvr profile use-after-free
  be/src/exec/exchange_node.cpp
  be/src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/data_stream_recvr.h
Labels: 2.5, 3.0, 3.1, 3.2

#36809 [BugFix] fix display colocate_with property
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 2.5, 3.0, 3.1, 3.2

#36826 [BugFix] Fix ConcurrentModificationException for ConnectorTableInfo
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorTableInfo.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorTblMetaInfoMgrTest.java
Labels: 3.0, 3.1, 3.2

#36836 [BugFix] fix scan blocked by unreleased tokens
  be/src/exec/pipeline/scan/scan_operator.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36849 [BugFix][Cherry-Pick][Branch-2.5] Fix deltalake glue catalog (backport #31839)
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadataFactory.java
Labels: automerge

#36854 [BugFix] Not use query cache if the plan contains non-deterministic time function
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  fe/fe-core/src/test/java/com/starrocks/planner/FragmentNormalizerTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#36878 [BugFix] Not use query cache if the plan contains non-deterministic time function(backport #36854)
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  fe/fe-core/src/test/java/com/starrocks/planner/FragmentNormalizerTest.java
Labels: 2.5, backport_ok

#36879 [BugFix] Not use query cache if the plan contains non-deterministic time function(backport #36854)
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  fe/fe-core/src/test/java/com/starrocks/planner/FragmentNormalizerTest.java
Labels: 3.0, backport_ok

#34838 [BugFix] Turn off `enable_connector_adaptive_io_tasks` to avoid lock confilct in IOTasksMemLimiter
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: 2.5, 3.0, 3.1, 3.2

#36861 [BugFix] No need to evalute rollup index when chunk is empty after where-expr evaluation
  be/src/storage/schema_change_utils.cpp
Labels: 3.2

#36845 [BugFix] fix display colocate_with property (backport #36809)
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: automerge

#36897 [Doc] Fix system var
  docs/docusaurus/.gitignore
  docs/en/reference/System_variable.md
Labels: documentation

#36899 [Doc] Fix system var 30
  docs/en/reference/System_variable.md
Labels: documentation

#35080 [Feature] sys.fe_locks
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/sys_fe_locks.cpp
  be/src/exec/schema_scanner/sys_fe_locks.h
  be/src/exec/schema_scanner/sys_object_dependencies.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeLocks.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeLocksTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
Labels: 3.1, 3.2, PROTO-REVIEW

#36891 [BugFix] fix mv rewrite bug when mv has column reorder
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: 3.1, 3.2

#36906 [BugFix] Fix task/report thrift rpc use wrong client cache
  be/src/agent/CMakeLists.txt
  be/src/agent/client_cache.cpp
  be/src/agent/client_cache.h
  be/src/agent/finish_task.cpp
  be/src/agent/report_task.cpp
  be/src/runtime/client_cache.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36871 [Enhancement] support set_var in multiple query blocks
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstTraverser.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetVarTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#36922 [BugFix] Fix function error hashcode (backport #35225)
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
Labels: automerge

#36870 [Enhancement] Add function serialize/deserialize/serializeToString to BitmapValue
  fe/plugin-common/src/main/java/com/starrocks/types/BitmapValue.java
  fe/plugin-common/src/main/java/com/starrocks/types/Roaring64Map.java
  fe/plugin-common/src/test/java/com/starrocks/types/BitmapValueTest.java
Labels: 3.0, 3.1, 3.2

#36933 [BugFix] Make sure isForwardToLeader immutable in the StmtExecutor's lifecycle (backport #34315)
  fe/fe-core/src/main/java/com/starrocks/plugin/AuditEvent.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SetVar.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
Labels: automerge

#36959 [Enhancement] Upgrade airbyte vulnerability dependency
  contrib/destination-starrocks/build.gradle
Labels: 3.1, 3.2

#36960 [Doc] fix links in 2.3
  docs/en/loading/Load_to_Primary_Key_tables.md
  docs/en/sql-reference/sql-functions/aggregate-functions/hll_raw_agg.md
  docs/en/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/zh/data_source/External_table.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
  docs/zh/sql-reference/sql-statements/data-types/Array.md
  docs/zh/unloading/Export.md
Labels: documentation

#36965 [Doc] fix two bugs in insert
  docs/en/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/en/sql-reference/sql-statements/data-manipulation/INSERT.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/zh/sql-reference/sql-statements/data-manipulation/INSERT.md
Labels: documentation

#36819 [Enhancement] Skip read pindex when we pick all rowsets to do compaction for primary key table
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#36956 [Enhancement] rewrite hive configuration explicitly
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/hadoop/HadoopExt.java
Labels: 3.2

#36032 [Enhancement] Supports runtime modification of some BE and Starlet params
  be/src/agent/agent_server.cpp
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/service/staros_worker.cpp
  be/src/storage/storage_engine.cpp
Labels: 3.1, 3.2

#36955 [Doc] fix bitmapvalue links and shared-data links
  docs/en/deployment/shared_data/azure.md
  docs/en/deployment/shared_data/gcs.md
  docs/en/deployment/shared_data/minio.md
  docs/en/loading/BrokerLoad.md
  docs/en/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
Labels: documentation, 3.0, 3.1, 3.2

#36853 [BugFix] No merge redundant task runs if the task run is sync mode refresh
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: 3.1, 3.2

#36893 [Doc] Update SHOW_SQLBLACKLIST.md
  docs/en/sql-reference/sql-statements/Administration/SHOW_SQLBLACKLIST.md
Labels: documentation

#36896 [Doc] split configuration.md into FE and BE
  docs/docusaurus/sidebars.json
  docs/en/administration/BE_configuration.md
  docs/en/administration/FE_configuration.md
  docs/en/administration/stargo.md
  docs/en/data_source/catalog/hive_catalog.md
  docs/en/deployment/deploy_manually.md
  docs/en/faq/Sql_faq.md
  docs/en/faq/loading/Broker_load_faq.md
  docs/en/faq/loading/Routine_load_faq.md
  docs/en/faq/loading/Stream_load_faq.md
  docs/en/loading/BrokerLoad.md
  docs/en/loading/RoutineLoad.md
  docs/en/loading/StreamLoad.md
  docs/en/loading/cloud_storage_load.md
  docs/en/release_notes/release-3.2.md
  docs/en/sql-reference/sql-functions/JAVA_UDF.md
  docs/en/sql-reference/sql-statements/Administration/ADMIN_SHOW_CONFIG.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/zh/administration/BE_configuration.md
  docs/zh/administration/FE_configuration.md
  docs/zh/administration/http_interface.md
  docs/zh/administration/stargo.md
  docs/zh/data_source/catalog/hive_catalog.md
  docs/zh/deployment/deploy_manually.md
  docs/zh/faq/Deploy_faq.md
  docs/zh/faq/loading/Broker_load_faq.md
  docs/zh/faq/loading/Routine_load_faq.md
  docs/zh/faq/loading/Stream_load_faq.md
  docs/zh/loading/BrokerLoad.md
  docs/zh/loading/RoutineLoad.md
  docs/zh/loading/StreamLoad.md
  docs/zh/reference/System_variable.md
  docs/zh/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.2.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-statements/Administration/ADMIN_SHOW_CONFIG.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
Labels: documentation, 3.2

#36917 [BugFix] distinguish the init sampling stats collect job
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
Labels: documentation, 3.1, 3.2

#36986 [Doc] fix links in Branch 2.1
  docs/zh/data_source/Manage_data.md
  docs/zh/loading/Loading_intro.md
  docs/zh/quick_start/Create_table.md
  docs/zh/release_notes/release-1.19.md
  docs/zh/release_notes/release-2.0.md
  docs/zh/release_notes/release-2.1.md
  docs/zh/sql-reference/sql-functions/json-functions/json-operators.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_CREATE_TABLE.md
  docs/zh/using_starrocks/Connector.md
  docs/zh/using_starrocks/External_table.md
  docs/zh/using_starrocks/filemanager.md
Labels: documentation

#36972 [Enhancement][Cherry-pick][Branch-2.5] Skip read pindex when we pick all rowsets to do compaction for primary key table (backport #36819)
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
Labels: automerge

#36222 [Feature] Adds routine_load_unstable_threshold_second
  be/src/runtime/routine_load/data_consumer_group.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RLTaskTxnCommitAttachment.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
  gensrc/thrift/FrontendService.thrift
Labels: behavior_changed, META-REVIEW, PROTO-REVIEW

#36950 [Enhancement] Querying for non-existing partitions should report an error
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#37001 [Doc] fix links in Branch 2.5
  docs/en/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
  docs/en/sql-reference/sql-statements/data-definition/DROP_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/zh/sql-reference/sql-statements/data-definition/DROP_MATERIALIZED_VIEW.md
Labels: documentation

#36993 [Doc] fix links in Branch 2.2
  docs/en/data_source/External_table.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
  docs/en/sql-reference/sql-statements/data-types/JSON.md
  docs/zh/loading/Loading_intro.md
  docs/zh/sql-reference/sql-functions/array-functions/unnest.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/json_array.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/json_object.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/zh/sql-reference/sql-functions/json-functions/json-operators.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/arrow-function.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/cast.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_double.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_int.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_string.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_each.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_exists.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_query.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_string.md
  docs/zh/sql-reference/sql-functions/json-functions/overview-of-json-functions-and-operators.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_INDEX.md
  docs/zh/sql-reference/sql-statements/data-types/JSON.md
  docs/zh/using_starrocks/Connector.md
  docs/zh/using_starrocks/Lateral_join.md
  docs/zh/using_starrocks/Using_HLL.md
Labels: documentation

#37010 [Feature] Adds routine_load_unstable_threshold_second (backport #36222) (branch-2.5)
  be/src/runtime/routine_load/data_consumer_group.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RLTaskTxnCommitAttachment.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadProgress.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge

#36987 [BugFix] change lastVersionUpdateTime to nanoTime
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
Labels: 2.5, 3.0, 3.1, 3.2

#36765 [Feature] Support a complete index metadata of GIN
  be/src/storage/CMakeLists.txt
  be/src/storage/metadata_util.cpp
  be/src/storage/metadata_util.h
  be/src/storage/tablet_index.cpp
  be/src/storage/tablet_index.h
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
  be/src/util/json_util.cpp
  be/src/util/json_util.h
  be/test/CMakeLists.txt
  be/test/storage/table_schema_test.cpp
  be/test/storage/tablet_index_test.cpp
  be/test/util/json_util_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IndexDef.java
  fe/fe-core/src/main/java/com/starrocks/analysis/IndexFactory.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Index.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/InvertedIndexParams.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/GINIndexTest.java
  gensrc/proto/tablet_schema.proto
  gensrc/thrift/Descriptors.thrift
Labels: META-REVIEW, PROTO-REVIEW

#37032 [BugFix] Fix primary key alter sort key bug (backport #30531)
  be/src/storage/schema_change.cpp
  test/sql/test_ddl/R/alter_table
  test/sql/test_ddl/T/alter_table
Labels: automerge

#37014 [Doc] Update account and container param names for Azure authentication
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/en/data_source/catalog/hive_catalog.md
  docs/en/data_source/catalog/hudi_catalog.md
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/data_source/catalog/paimon_catalog.md
  docs/en/data_source/catalog/unified_catalog.md
  docs/en/integrations/authenticate_to_azure_storage.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/hive_catalog.md
  docs/zh/data_source/catalog/hudi_catalog.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/data_source/catalog/paimon_catalog.md
  docs/zh/data_source/catalog/unified_catalog.md
  docs/zh/integrations/authenticate_to_azure_storage.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
Labels: documentation

#36701 [Feature] support spill_mem_limit_threshold in resource group
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  be/src/runtime/current_thread.h
  be/src/runtime/mem_tracker.h
  be/test/exec/pipeline/pipeline_driver_queue_test.cpp
  be/test/exec/pipeline/query_context_manger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroup.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterResourceGroupStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
  gensrc/thrift/WorkGroup.thrift
Labels: META-REVIEW, PROTO-REVIEW

#37040 [BugFix] Fix the compilation bug introduced by runtime modification starlet params
  be/src/http/action/update_config_action.cpp
Labels: 3.1, 3.2

#37042 [Doc] remove a link in Branch 3.0
  docs/en/administration/Configuration.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_REPOSITORY.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
Labels: documentation

#37043 [Doc] unlist docs in 2.1
  docs/en/administration/timezone.md
  docs/en/sql-reference/sql-functions/date-time-functions/from_unixtime.md
  docs/zh/quick_start/Import_and_query.md
Labels: documentation

#37048 [Doc] fix links in Branch 2.5
  docs/en/administration/Configuration.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
Labels: documentation

#37051 [Doc] fix links in Branch 2.3
  docs/en/administration/deploy_with_manager.md
  docs/en/faq/loading/Routine_load_faq.md
  docs/en/quick_start/Create_table.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/en/sql-reference/sql-statements/data-types/Array.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-functions/json-functions/overview-of-json-functions-and-operators.md
Labels: documentation
