Repository StarRocks/starrocks, pull requests merged in 2023-01, with the labels that each got.

#16071 [BugFix] Fix FE UT
  fe/fe-core/src/test/java/com/starrocks/catalog/TypeTest.java
Labels: be-build

#16076 [BugFix] clone instead of reference to map key column and value column
  be/src/exprs/map_functions.cpp
Labels: be-build, 2.5

#16075 [Refactor][backport] clone instead of reference to map key column and value column
  be/src/exprs/vectorized/map_element_expr.cpp
  be/src/exprs/vectorized/map_functions.cpp
Labels: automerge, be-build

#16013 [BugFix] Fix AUTO TABLET bug of CTAS
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CTASAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/MaterializedViewAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#16078 [BugFix] Enable normal work in higher version JDK
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#16079 [Enhancement] Make some keywords nonReserved
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: be-build

#16084 Refactor pseudo functions
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
Labels: title needs [type], be-build

#16085 [Feature] Support map_from_arrays and row functions
  be/src/exprs/map_functions.cpp
  be/src/exprs/map_functions.h
  be/src/exprs/struct_functions.cpp
  be/src/exprs/struct_functions.h
  be/test/exprs/map_functions_test.cpp
  be/test/exprs/struct_functions_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/sql-reference/sql-functions/struct-functions/row.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
  gensrc/script/vectorized/vectorized_functions.py
Labels: be-build

#16041 [BugFix] Fix FE memory leak when refresh mv failed
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
Labels: Approved, be-build, 2.5, 2.4

#15371 [Feature] Support multi-column IN subqueries in WHERE clause
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiInPredicate.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/MultiInPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
Labels: Approved, be-build

#15613 [Enhancement] Balance and repair use the same slot for tablet scheduler
  fe/fe-core/src/main/java/com/starrocks/clone/BeLoadRebalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/SchedulerWorkingSlotsProcDir.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BalanceTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
Labels: be-build

#16118 [BugFix] [cherry-pick] Don't try catch the memory alloc of brpc transmit_chunk (#16047)
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/runtime/data_stream_sender.cpp
Labels: automerge, be-build

#15969 [Enhancement] segment replicate executor support fast cancel
  be/src/storage/delta_writer.cpp
  be/src/storage/segment_replicate_executor.cpp
  be/src/storage/segment_replicate_executor.h
Labels: Approved, be-build

#16119 [BugFix] [cherry-pick] Don't try catch the memory alloc of brpc transmit_chunk (#16047)
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/runtime/data_stream_sender.cpp
Labels: automerge, be-build

#16112 [Enhancement] Support window function for Trino parser on starrocks
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
Labels: Approved, be-build

#16123 [Doc] adjust toc and modify map
  docs/TOC.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
Labels: documentation, be-build

#16124 [Doc] adjust toc to Branch 2.4
  docs/TOC.md
Labels: documentation, be-build

#16125 [Doc] adjust toc to Branch 2.3
  docs/TOC.md
Labels: documentation, be-build

#16126 [Doc] adjust toc to Branch 2.5
  docs/TOC.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
Labels: documentation, be-build

#15970 [BugFix]log4j can not follow links
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: Approved, be-build

#15403 [Enhancement] set connector scan thread number by `8 x cpu`
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  docs/administration/Configuration.md
Labels: documentation, Approved, be-build

#15738 [BugFix] transaction stream load cancel bug
  be/src/http/action/transaction_stream_load.cpp
Labels: Approved, be-build, 2.5, 2.4

#16049 [BugFix] Fix replicated storage write hang when async writer fail
  be/src/runtime/local_tablets_channel.cpp
  be/src/service/service_be/internal_service.cpp
  be/src/storage/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/segment_replicate_executor.cpp
  be/src/storage/txn_manager.cpp
Labels: Approved, be-build, 2.5

#15955 [Enhancement] Optimize display of explain costs
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q1.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q11.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q12.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q13.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q14.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q15.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q16.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q17.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q19.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q2.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q22.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q4.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q6.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q8.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q1.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q10.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q11.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q12.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q14.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q15.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q16.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q17.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q19.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q2.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q20.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q21.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q22.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q3.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q5.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q6.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q7.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q8.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q1.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q15.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q2.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q3.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
Labels: Approved, be-build

#16140 [Doc] Update query_cache.md in Branch 2.5
  docs/using_starrocks/query_cache.md
Labels: documentation, be-build

#16139 [Doc] Update query_cache.md
  docs/using_starrocks/query_cache.md
Labels: documentation, Approved, be-build

#16142 [Doc] add links for hll functions
  docs/sql-reference/sql-functions/aggregate-functions/hll_union_agg.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
  docs/sql-reference/sql-statements/data-types/HLL.md
  docs/using_starrocks/Materialized_view.md
  docs/using_starrocks/Using_HLL.md
Labels: documentation, Approved, be-build

#15935 [BugFix] Refactor remove_expired_versions to limit max version count and fix protential concurrent call issues
  be/src/storage/tablet.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/src/storage/task/engine_clone_task.cpp
Labels: Approved, be-build, 2.5, 2.4, 2.3

#16132 [Enhancement] Remove struct subfield colon separator and change struct subfield equals() behavior
  fe/fe-core/src/main/java/com/starrocks/catalog/StructField.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStructTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypeTest.java
Labels: be-build

#16117 [Refactor] Refactor CastExpr constructor to support Map and Struct
  be/src/exprs/CMakeLists.txt
  be/src/exprs/cast_expr.cpp
  be/src/exprs/cast_expr.h
  be/src/exprs/cast_expr_array.cpp
  be/src/exprs/cast_nested.cpp
Labels: Approved, be-build

#16074 [BugFix] Fix query use jsonTye between-and decimalV3Type failed
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
Labels: be-build, 2.5

#16017 [Feature] Support mv maintenance task interact with task executor
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/BinlogConsumeStateVO.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVEpoch.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceJob.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceTask.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/mv/MVMaintenanceJobTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: sig/materialized view, be-build

#13724 [Refactor] Fix compile warning: the use of tmpnam is dangerous.
  be/test/util/filesystem_util_test.cpp
Labels: Approved, be-build

#16144 [BugFix] use a tinyint col to fill empty project (backport #15662)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggToMetaScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCHPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
Labels: automerge, be-build

#16133 [Enhancement] fix disk space occupation problems after insert overwrite
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobRunnerTest.java
Labels: Approved, be-build

#16164 [Doc] update toc for Branch 2.4
  docs/TOC.md
Labels: documentation, be-build

#16163 [BugFix] Make complex type have no ConstColumn
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/column.h
  be/src/column/map_column.cpp
  be/src/column/map_column.h
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/exprs/anyval_util.cpp
  be/src/exprs/cast_nested.cpp
  be/src/exprs/function_call_expr.cpp
Labels: Approved, be-build

#16130 [BugFix] Can't ingest data via starrrocks external table from starrocks' lower version to higher version
  gensrc/thrift/FrontendService.thrift
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#16146 [BugFix] Use data columns to get column statistics instead of all columns
  fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java
Labels: be-build

#16170 [Doc] modify desc for downloading smt package
  docs/loading/Flink_cdc_load.md
Labels: documentation, Approved, be-build

#16165 [Feature] Support map and struct cast
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
Labels: be-build

#16122 [BugFix] array_filter[nullable_col, null] results' null col is not set
  be/src/exprs/array_functions.tpp
  be/test/exprs/array_functions_test.cpp
Labels: Approved, be-build, 2.5

#15919 [BugFix] Do not register load reporting tasks to ProfileReportWorker for stream load
  be/src/exec/pipeline/query_context.cpp
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: Approved, be-build, 2.5

#15746 [Feature] Support select binlog
  be/src/connector/CMakeLists.txt
  be/src/connector/binlog_connector.cpp
  be/src/connector/binlog_connector.h
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/exec/CMakeLists.txt
  be/src/exec/connector_scan_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exec/stream/scan/stream_scan_operator.cpp
  be/src/exec/stream/scan/stream_scan_operator.h
  fe/fe-core/src/main/java/com/starrocks/planner/BinlogScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewPlanTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: Approved, sig/materialized view, be-build

#16178 [BugFix] Fix cast bugs
  be/src/exprs/cast_nested.cpp
Labels: be-build

#16185 [Doc] Update Load_to_Primary_Key_tables.md in Branch 2.3
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, be-build

#16184 [Doc] Update Load_to_Primary_Key_tables.md in Branch 2.4
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, be-build

#16183 [Doc] Update Load_to_Primary_Key_tables.md in Branch 2.5
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, be-build

#16182 [Doc] Update Load_to_Primary_Key_tables.md
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, Approved, be-build

#16188 [Doc] update primary key load in Branch 2.4
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, be-build

#16189 [Doc] update primary key load in Branch 2.3
  docs/loading/Load_to_Primary_Key_tables.md
Labels: documentation, be-build

#16192 [Enhancement] fix disk space occupation problems after insert overwrite
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobRunnerTest.java
Labels: be-build

#16136 [BugFix] Fix primary key replicated storage flush fail
  be/src/storage/delta_writer.cpp
  be/src/storage/rowset/rowset_writer.cpp
  be/test/storage/rowset/rowset_test.cpp
Labels: Approved, be-build, 2.5

#15949 [Enhancement] Support RuntimeFilter build in TopN Node
  be/src/exec/chunks_sorter.h
  be/src/exec/chunks_sorter_heap_sort.cpp
  be/src/exec/chunks_sorter_heap_sort.h
  be/src/exec/chunks_sorter_topn.cpp
  be/src/exec/chunks_sorter_topn.h
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/runtime_filter_types.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/pipeline/sort/partition_sort_sink_operator.h
  be/src/exec/pipeline/sort/sort_context.cpp
  be/src/exec/pipeline/sort/sort_context.h
  be/src/exec/stream/aggregate/agg_state_data.h
  be/src/exec/topn_node.cpp
  be/src/exec/topn_node.h
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/storage/olap_runtime_range_pruner.h
  be/src/storage/olap_runtime_range_pruner.hpp
  be/src/storage/rowset/segment_iterator.cpp
  be/test/exprs/runtime_filter_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/AggregationNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/AnalyticEvalNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/NestLoopJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ProjectNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterBuildNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/planner/SetOperationNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SortNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/RuntimeFilter.thrift
Labels: Approved, be-build

#16141 [Feature] Implement a simple TableReader for testing
  be/src/storage/table_reader.cpp
  be/src/storage/table_reader.h
  be/test/CMakeLists.txt
  be/test/storage/table_reader_test.cpp
Labels: Approved, sig/materialized view, be-build

#16208 [BugFix] Fix merge memo lose best expression (#16135) [cherry-pick]
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: automerge, be-build

#16199 [BugFix] Fix unstable ut for colocate test
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
Labels: Approved, be-build, 2.5

#16207 [BugFix] Fix merge memo lose best expression (#16135) [cherry-pick]
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java
Labels: automerge, be-build

#16214 [Enhancement] Get accurate build type on make time
  be/CMakeLists.txt
  be/src/common/build_version.cc.in
  build-support/gen_build_version.py
Labels: be-build

#16121 [Enhancement] [cherry-pick] segment replicate executor support fast cancel (#15969)
  be/src/storage/delta_writer.cpp
  be/src/storage/segment_replicate_executor.cpp
  be/src/storage/segment_replicate_executor.h
Labels: automerge, be-build

#15614 [Enhancement] Balance and repair use the same slot for tablet scheduler
  fe/fe-core/src/main/java/com/starrocks/clone/BeLoadRebalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/SchedulerWorkingSlotsProcDir.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BalanceTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
Labels: be-build

#16209 [BugFix] Fix merge memo lose best expression (#16135) [cherry-pick]
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java
Labels: automerge, be-build

#15938 [Feature] Replace old auth api with new privilege
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationManager.java
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/action/WebBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/ColocateMetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/GlobalDictMetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/CheckDecommissionAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetDdlStmtAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetLoadInfoAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MetaReplayerCheckAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MetricsAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MigrationAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RowCountAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/SetConfigAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowProcAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/StorageTypeCheckAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableRowCountAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableSchemaAction.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadFunctionalExprProvider.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadFunctionalExprProvider.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlPassword.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DataDescription.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SetVar.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
Labels: Approved, be-build

#16116 [Refactor] refactor window aggregate function with type traits
  be/src/exprs/agg/aggregate_traits.h
  be/src/exprs/agg/window.h
Labels: Approved, be-build

#16205 [BugFix] Fix distinct + having check
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#16238 [BugFix] Null-safe-equals operator <=> incorrect behavior for null equals non-null
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRuleTest.java
Labels: Approved, be-build, 2.5

#16250 [BugFix] Fix limit db length to 509, and restore the limit of other names
  fe/fe-core/src/main/java/com/starrocks/common/FeNameFormat.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableAutoTabletTest.java
Labels: Approved, be-build, 2.5

#16235 [BugFix] Fix BE crash when TopN filter apply on Lowcardinality column
  be/src/storage/olap_runtime_range_pruner.h
  be/src/storage/olap_runtime_range_pruner.hpp
  be/src/storage/predicate_parser.cpp
  be/src/storage/predicate_parser.h
  be/src/storage/rowset/segment_iterator.cpp
Labels: Approved, be-build

#16234 [Refactor] Remove legacy code
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/tablet_meta_manager_test.cpp
Labels: Approved, be-build

#16270 [Refactor] Removed outdated log4j 1.2
  fe/fe-core/pom.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: be-build

#16269 [Refactor] Make TabletMeta return format v2
  be/src/connector/binlog_connector.cpp
  be/src/connector/lake_connector.cpp
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/tablet_scanner.cpp
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/storage/compaction.cpp
  be/src/storage/horizontal_compaction_task.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/spark_load.cpp
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/memtable.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/predicate_parser.cpp
  be/src/storage/primary_index.cpp
  be/src/storage/push_handler.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/src/storage/rowset_merger.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/storage/schema_change.cpp
  be/src/storage/schema_change_utils.cpp
  be/src/storage/table_reader.cpp
  be/src/storage/tablet_reader.cpp
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/task/engine_checksum_task.cpp
  be/src/storage/type_utils.h
  be/src/storage/update_compaction_state.cpp
  be/src/storage/vertical_compaction_task.cpp
  be/test/storage/base_compaction_test.cpp
  be/test/storage/cumulative_compaction_test.cpp
  be/test/storage/default_compaction_policy_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset/segment_iterator_test.cpp
  be/test/storage/rowset/segment_rewriter_test.cpp
  be/test/storage/rowset/segment_test.cpp
  be/test/storage/rowset_merger_test.cpp
  be/test/storage/rowset_update_state_test.cpp
  be/test/storage/schema_change_test.cpp
  be/test/storage/size_tiered_compaction_policy_test.cpp
  be/test/storage/table_reader_test.cpp
  be/test/storage/table_schema_test.cpp
  be/test/storage/tablet_mgr_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/task/engine_storage_migration_task_test.cpp
  be/test/storage/update_manager_test.cpp
Labels: be-build

#16267 [BugFix] fix type casting from json to array
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
Labels: be-build, 2.5, 2.4

#16198 [Enhancement] Fix external table use mysql format
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: be-build

#16281 [Enhancement][Cherry-pick][Branch-2.3] Make schema changed table not to be moved to trash
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge, be-build

#16265 [Enhancement] Instead of using def for null values, use empty to represent null
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: Approved, be-build

#16262 [BugFix] Fix cancel decommission statement miss analyze
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AlterSystemStmtAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
Labels: Approved, be-build

#16242 [BugFix] Forgot to abort failed compaction transaction
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
Labels: Approved, be-build

#16073 [BugFix] Show resource group with empty classifiers
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroup.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
Labels: be-build, 2.5

#16295 [Doc] Update BROKER LOAD.md in Branch 2.5
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, be-build

#16296 [Doc] Update BROKER LOAD.md in Branch 2.4
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, be-build

#16297 [Doc] Update BROKER LOAD.md in Branch 2.3
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, be-build

#16241 [BugFix] Fix issue 16239
  be/src/http/action/transaction_stream_load.cpp
Labels: Approved, be-build, 2.5, 2.4

#14152 [Feature] Support binlog configuration and modification
  be/src/agent/agent_task.cpp
  be/src/storage/binlog_manager.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/test/storage/tablet_meta_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogConfig.java
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogManager.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/UpdateTabletMetaInfoTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PartitionCommitInfo.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/binlog/BinlogManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/MasterService.thrift
Labels: sig/materialized view, be-build

#16261 [BugFix] Set default replication number to 1 for lake table
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved, be-build

#16252 [BugFix] Change lower to upper in _get_row_ranges_by_key_ranges
  be/src/storage/rowset/segment_iterator.cpp
Labels: Approved, be-build

#16294 [Doc] Update BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, Approved, be-build

#16307 [Doc] add content for block cache
  docs/administration/Configuration.md
  docs/data_source/Block_cache.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/reference/System_variable.md
Labels: documentation, be-build

#16299 [Doc] delete incorrect content in hive catalog from Branch 2.4
  docs/data_source/catalog/hive_catalog.md
Labels: documentation, be-build

#16304 [Doc] add content for block cache Branch 2.5
  docs/administration/Configuration.md
  docs/data_source/Block_cache.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/reference/System_variable.md
Labels: documentation, be-build

#16288 [BugFix] DictMappingRewriter support compoundPredicate (backport #15737)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/DictMappingRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: automerge, be-build

#16300 [Enhancement] reduce the loop time in building scanNode (backport #16236)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/DistributionSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/many_partitions.json
Labels: automerge, be-build

#16308 [Enhancement] reduce the loop time in building scanNode (backport #16236)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/DistributionSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/many_partitions.json
Labels: automerge, be-build

#16293 [BugFix] Fix desc sync mv column name is wrong
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DescribeStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/DescribeStmtTest.java
Labels: Approved, be-build, 2.5, 2.4

#16327 [Refactor] Remove the dependency of QueryAnalyzer for BinlogScanNode
  fe/fe-core/src/main/java/com/starrocks/planner/BinlogScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
Labels: be-build

#16298 [BugFix] create_cast_expr encounter unexpected null causing crash
  be/src/exprs/cast_expr.cpp
  be/test/exprs/cast_expr_test.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
Labels: Approved, be-build

#16335 [Doc] remove incorrect content from catalog of Branch 2.4
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation, be-build

#16336 [Refactor] Move ArrayType to types
  be/src/exec/pipeline/exchange/local_exchange_sink_operator.h
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/stream/aggregate/stream_aggregate_operator.h
  be/src/runtime/types.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/types.cpp
  be/src/types/CMakeLists.txt
  be/src/types/array_type_info.cpp
  be/src/types/array_type_info.h
  be/test/storage/column_aggregator_test.cpp
Labels: be-build

#15081 [Refactor] Use AggregateFunction in storage layer
  be/src/exprs/agg/maxmin.h
  be/src/storage/column_aggregate_func.cpp
  be/src/storage/column_aggregator.h
  be/test/storage/column_aggregator_test.cpp
Labels: be-build

#16338 [Enhancement] Get default user name
  conf/hadoop_env.sh
Labels: be-build

#16339 [Enhancement] Support array type for Trino parser on starrocks
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/FunctionCallTransformer.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: be-build

#16358 [Enhancement] [cherry-pick] remove restriction of add array type column in non duplicate key model. (#14992)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: automerge, be-build

#16063 [BugFix] Fix delta table binary predicate error
  fe/fe-core/src/main/java/com/starrocks/connector/delta/ExpressionConverter.java
Labels: Approved, be-build

#15729 [Enhancement] Flush persistent index in advance to reduce memory usage during data load of primary key
  be/src/common/config.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/test/storage/persistent_index_test.cpp
  gensrc/proto/persistent_index.proto
Labels: Approved, be-build

#16347 [BugFix] BinlogConfig buildFromProperties fix
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogConfig.java
  fe/fe-core/src/test/java/com/starrocks/binlog/BinlogConfigTest.java
Labels: be-build

#16368 [BugFix] use group by cols of agg to rewrite correlated predicates (backport #15960)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/query_dump/union_with_subquery.json
Labels: automerge, be-build

#16357 [BugFix] fix potential heap overflow in snappy slice source
  be/src/util/block_compression.cpp
  be/src/util/compression/block_compression.cpp
Labels: be-build

#16363 [BugFix] use group by cols of agg to rewrite correlated predicates (backport #15960)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/query_dump/union_with_subquery.json
Labels: automerge, be-build

#16355 [Enhancement] Support explain query statement for Trino parser on starrocks
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: Approved, be-build

#16369 [Enhancement] [cherry-pick] remove restriction of add array type column in non duplicate key model. (#14992)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: automerge, be-build

#15734 [BugFix] Fix iceberg table cannot create expression literal when column type is boolean
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/ScalarOperatorToIcebergExpr.java
Labels: Approved, be-build

#16290 [Enhancement] log of removing expired job
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadManager.java
Labels: Approved, be-build

#16323 [BugFix] Backend not found
  fe/fe-core/src/main/java/com/starrocks/qe/SimpleScheduler.java
  fe/fe-core/src/test/java/com/starrocks/qe/SimpleSchedulerTest.java
Labels: Approved, be-build

#16376 [Enhancement] explain is not forbidden by sql black list
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: Approved, be-build

#15973 [Enhancement][Cherry-pick][branch-2.5] Optimize mem usage of partial update
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/memtable.cpp
  be/src/storage/memtable.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset_update_state.cpp
  be/src/storage/rowset_update_state.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset_update_state_test.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: automerge, be-build

#16263 [BugFix][CherryPick][Branch-2.4] Fix be crash because of dropping tablet
  be/src/storage/olap_common.h
  be/src/storage/rowset/rowset.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: be-build

#16264 [BugFix][CherryPick][Branch-2.3] Fix be crash because of dropping tablet (#15959)
  be/src/storage/olap_common.h
  be/src/storage/rowset/rowset.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: be-build

#16387 [Enhancement]After executing the build.sh with some parameters, the display prompt is inaccurate, all of which are [Successfully build StarRocks]
  build.sh
Labels: be-build

#16167 [Refactor] Fix the wrong log when preCommit failed
  fe/fe-core/src/main/java/com/starrocks/common/FeNameFormat.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableAutoTabletTest.java
Labels: Approved, be-build

#16382 [Enhancement] support "select into outfile" without properties
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  fe/fe-core/src/main/java/com/starrocks/analysis/OutFileClause.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: Approved, be-build

#16351 [Enhancement] optimize harmonic mean evaluation in hll::estimate_cardinality
  be/src/types/hll.cpp
Labels: Approved, be-build

#16379 [Enhancement] [cherry-pick] remove restriction of add array type column in non duplicate key model. (#14992)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: automerge, be-build

#16381 [BugFix] BE crash when ingesting data from nested array to json
  be/src/exec/arrow_to_json_converter.cpp
  be/src/exec/arrow_to_starrocks_converter.cpp
  be/test/exec/test_data/parquet_data/issue_16375.py
Labels: be-build, 2.5, 2.4

#16400 [Doc] Add blog link
  README.md
Labels: title needs [type], be-build

#16356 [Enhancement] Optimize the performance for regexp_replace
  be/src/exprs/string_functions.cpp
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/re2-2022-12-01.patch
  thirdparty/vars.sh
Labels: be-build

#16405 [Doc] Update EXPORT.md
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
Labels: documentation, be-build

#16406 [Doc] Update EXPORT.md in Branch 2.5
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
Labels: documentation, be-build

#16408 [Doc] Update EXPORT.md in Branch 2.4
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
Labels: documentation, be-build

#16409 [Doc] Update EXPORT.md in Branch 2.3
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
Labels: documentation, be-build

#16410 delete palo from sparkload
  docs/loading/SparkLoad.md
Labels: documentation, Approved, title needs [type], be-build

#16407 [Enhancement] Support Struct/Map type for Trino parser on starrocks
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: be-build

#16418 [BugFix] Fix brpc compile error
  be/src/service/internal_service.h
  be/src/util/bthreads/executor.h
  thirdparty/download-thirdparty.sh
  thirdparty/patches/brpc-0.9.5.patch
  thirdparty/patches/brpc-0.9.7.patch
  thirdparty/patches/brpc-1.3.0.patch
  thirdparty/vars.sh
Labels: 2.5, 2.4, 2.3, 2.2

#16416 [BugFix] use a tinyint col to fill empty project (backport #15662)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggToMetaScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregatePushDownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/agg-pushdown.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/select.sql
  fe/fe-core/src/test/resources/sql/optimized-plan/window.sql
  fe/fe-core/src/test/resources/sql/query_dump/subquery_statistics.json
  fe/fe-core/src/test/resources/sql/subquery/exists-subquery.sql
Labels: automerge, be-build

#16423 [Feature] Add session var random_select_olap_replicas
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: be-build

#16435 [BugFix] Fix librdkafka compile error
  thirdparty/build-thirdparty.sh
Labels: be-build, 2.5, 2.4, 2.3

#15667 [Refactor] Unify the unit tests related names for BE and FE
  docs/developers/build-starrocks/handbook.md
  run-be-ut.sh
  run-fe-ut.sh
Labels: 2.5, 2.4, 2.3, 2.2

#16437 [Refactor]update test to forbid sql with where
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
Labels: Approved, be-build

#16431 [BugFix] only set not null for primary key column
  fe/fe-core/src/main/java/com/starrocks/analysis/KeysDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: Approved, be-build, 2.5, 2.4

#16177 [Refactor] limit Local exchange buffer size by memory usage rather than by row count
  be/src/common/config.h
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exec/pipeline/exchange/local_exchange.h
  be/src/exec/pipeline/exchange/local_exchange_memory_manager.h
  be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/local_exchange_source_operator.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/pipeline_builder.cpp
Labels: Approved, be-build

#16450 [Enhancement] support bitmap hll percentile type for mv backport 2.5
  be/src/storage/rowset/segment_writer.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: automerge, be-build

#16452 [Doc] format sql syntax and add 2.5 rc03 release notes
  docs/data_source/Block_cache.md
  docs/faq/Deploy_faq.md
  docs/release_notes/release-2.5.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP USER.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, be-build

#16280 [Enhancement][Cherry-pick][Branch-2.4] Make schema changed table not to be moved to trash
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge, be-build

#16479 Revert "[BugFix] Fix brpc compile error (backport #16418)"
  be/src/service/internal_service.h
  be/src/util/bthreads/executor.h
  thirdparty/download-thirdparty.sh
  thirdparty/patches/brpc-1.3.0.patch
  thirdparty/patches/incubator-brpc-0.9.5.patch
  thirdparty/patches/incubator-brpc-0.9.7.patch
  thirdparty/vars.sh
Labels: automerge, title needs [type]

#16354 [Enhancement] remove sensitive info from create resource stmt audit
  fe/fe-core/src/main/java/com/starrocks/common/util/PrintableMap.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateResourceStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/ResourceStmtTest.java
Labels: Approved, be-build

#16395 [Refactor][Cherry-pick][Branch-2.3] Fix the wrong log when preCommit failed (#16167)
  bin/common.sh
  fe/fe-core/src/main/java/com/starrocks/common/FeNameFormat.java
Labels: automerge, be-build

#16451 [BugFix] Fix query struct type subfield with analytic node error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/ExpressionMapping.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypeTest.java
Labels: Approved, be-build

#16487 [Doc] format syntax to Branch 2.4
  docs/faq/Deploy_faq.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP USER.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, be-build

#16488 [Doc] format syntax to Branch 2.3
  docs/faq/Deploy_faq.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP USER.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, be-build

#16485 [Doc] format syntax to Branch 2.5
  docs/data_source/Block_cache.md
  docs/faq/Deploy_faq.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP ROLE.md
  docs/sql-reference/sql-statements/account-management/DROP USER.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, be-build

#16434 [Refactor] Remove some of the dependencies on ExecEnv::GetInstance()
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/lake_tablets_channel.h
  be/src/runtime/load_channel.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/schema_change.h
  be/src/storage/task/engine_alter_tablet_task.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/horizontal_compaction_task_test.cpp
  be/test/storage/lake/schema_change_test.cpp
Labels: be-build

#16481 [Refactor] Remove check when registering functions
  fe/fe-core/src/main/java/com/starrocks/catalog/AnyArrayType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/AnyElementType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/AnyMapType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/AnyStructType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
Labels: Approved, be-build
