Repository StarRocks/starrocks, pull requests merged in 2023-08, with the labels that each got.

#28285 [BugFix] fix hms version issue when creating iceberg table
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetastoreClientTest.java
Labels: 3.1

#28223 [BugFix]refresh will invalidate cache when table is drop on hive/glue
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/CachingHiveMetastoreTest.java
Labels: 2.5, 3.0, 3.1

#28058 [BugFix] Release lock early in the drop tablet
  be/src/storage/tablet_manager.cpp
Labels: 2.5, 3.0, 3.1

#28220 [BugFix] Fix UDF couldn't be found in upper case DataBase
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: 2.5, 3.0, 3.1

#27488 [BugFix] remove primary index entry when apply rowset failed
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1

#28283 [Enhancement] Fix StructColumn::byte_size memory estimation error
  be/src/column/adaptive_nullable_column.h
  be/src/column/array_column.cpp
  be/src/column/column.h
  be/src/column/fixed_length_column_base.h
  be/src/column/json_column.h
  be/src/column/map_column.cpp
  be/src/column/nullable_column.h
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/test/column/struct_column_test.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#28311 [BugFix] Fix memory leak bug caused by label cleaner
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetStreamLoadState.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: 2.5, 3.0, 3.1

#28097 [Enhancement] Add a fallback strategy to deal with inconsistencies in materialized view metadata
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/persist/ChangeMaterializedViewRefreshSchemeLog.java
  fe/fe-core/src/test/java/com/starrocks/persist/ChangeMaterializedViewRefreshSchemeLogTest.java
Labels: 2.5, 3.0, 3.1

#28366 [BugFix] Disable read pretch by default
  be/src/common/config.h
Labels: 3.1

#28374 [Doc] New headings for MV docs
  docs/using_starrocks/Materialized_view-single_table.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, 3.1

#28357 [BugFix][Cherry-pick][Branch-2.5] Re-Order operation on a table with seperated primary keys and sort keys may cause data corruption (#27850)
  be/src/storage/schema_change.cpp
  be/src/storage/tablet_updates.cpp
Labels: automerge

#28136 [Enhancement] Encode file modification time to data cache key. (#27755)
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/test/io/cache_input_stream_test.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileDesc.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileTableScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedRemoteFileSystem.java
  gensrc/thrift/PlanNodes.thrift
Labels: 2.5

#28385 [BugFix] Delete unexpected rows when auto increment column is key (#28384)
  be/src/exec/tablet_sink.cpp
Labels: 3.0

#28325 [Doc] add general scenario example to grant
  docs/administration/User_privilege.md
  docs/administration/privilege_item.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation, 3.0, 3.1

#28118 [BugFix] Do not add login log to QueryDetailQueue when connection module is not configed
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
  fe/fe-core/src/test/java/com/starrocks/common/util/LogUtilTest.java
Labels: 3.0, 3.1

#28386 [Enhancement] Dynamic partition time unit support year
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DynamicPartitionUtilTest.java
Labels: 2.5, 3.0, 3.1

#28276 [Enhancement] refactor date_diff function
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  docs/sql-reference/sql-functions/date-time-functions/date_diff.md
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/ComplexFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  gensrc/script/functions.py
  test/sql/test_datetime/R/test_date_diff
  test/sql/test_datetime/T/test_date_diff
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation, 3.0, 3.1

#28390 [BugFix][Cherry-pick][branch-2.3] fix pk compaction bug (#13106)
  be/src/storage/tablet_updates.cpp
Labels: automerge

#28379 [Enhancement][Cherry-Pick] Add a fallback strategy to deal with inconsistencies in materialized …
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/persist/ChangeMaterializedViewRefreshSchemeLog.java
Labels: automerge

#28112 [Enhancement] reduce memory usage in agg states
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/sorted_streaming_aggregator.cpp
  be/src/exec/sorted_streaming_aggregator.h
  be/src/exec/stream/aggregate/stream_aggregator.cpp
  be/src/exec/stream/aggregate/stream_aggregator.h
Labels: 3.0, 3.1

#28412 [Doc] Update SHOW BACKENDS on priv
  docs/sql-reference/sql-statements/Administration/SHOW BACKENDS.md
Labels: documentation, 3.0, 3.1

#27841 [Doc] add list partitioning
  docs/TOC.md
  docs/assets/list_partitioning.png
  docs/table_design/Data_distribution.md
  docs/table_design/automatic_partitioning.md
  docs/table_design/expression_partitioning.md
  docs/table_design/list_partitioning.md
Labels: documentation

#28405 [Doc] Revise INSERT reference
  docs/sql-reference/sql-statements/data-manipulation/insert.md
Labels: documentation, 2.5, 3.0, 3.1

#28370 [Enhancement] Opt the memory usage of column zonmap for all null
  be/src/storage/rowset/zone_map_index.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#28455 [Doc] add expr& list partitioning
  docs/TOC.md
  docs/assets/list_partitioning.png
  docs/table_design/Data_distribution.md
  docs/table_design/automatic_partitioning.md
  docs/table_design/expression_partitioning.md
  docs/table_design/list_partitioning.md
Labels: documentation

#27646 [BugFix] remove unnecessary check in statistic calculate phase
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnDict.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticRangeValues.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: 3.0, 3.1

#28463 [Doc] Remove Preview from Spill
  docs/administration/spill_to_disk.md
Labels: documentation, 3.1

#28389 [Enhancement] External olap table support temp partition
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionType.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/test/java/com/starrocks/external/starrocks/TableMetaSyncerTest.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 3.0, 3.1

#28472 [BugFix] Fix follower fe CpuCores not synchronized
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 3.1

#28093 [BugFix] Materialized view should update all its refreshed base table partitions after refresh
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/MVTaskRunExtraMessage.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: sig/materialized view, 3.0, 3.1

#28397 [Enhancement] improve user prompt about too many versions error
  be/src/storage/delta_writer.cpp
Labels: 2.5, 3.0, 3.1

#28100 [BugFix] fix join probe metric is 0
  be/src/exec/hash_joiner.cpp
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/src/exec/pipeline/hashjoin/hash_join_probe_operator.cpp
  be/test/exec/join_hash_map_test.cpp
Labels: 3.0, 3.1

#28506 [Doc] update 3.1 keywords
  docs/sql-reference/sql-statements/keywords.md
Labels: documentation, 3.1

#28473 [BugFix] Recalculate max_continuous_version after schema change finished
  be/src/storage/schema_change.cpp
  be/src/storage/tablet.h
  be/src/storage/version_graph.cpp
  be/src/storage/version_graph.h
Labels: 2.5, 3.0, 3.1

#28456 [BugFix] Fix the problem of configuration failure when Paimon Catalog uses S3-compatible storage system.
  docs/data_source/catalog/paimon_catalog.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonConnector.java
Labels: documentation, 3.1

#28482 [Enhancement] Change some default session variables for MV refresh
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
Labels: sig/materialized view, 3.1

#28433 [BugFix]Fix unrecognize database name with uppercase in udf Function…
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionName.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/CreateFunctionStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/DropFunctionStmtTest.java
Labels: title needs [type]

#28504 [Enhancement] improve user prompt about too many versions error (backport #28397)
  be/src/storage/delta_writer.cpp
Labels: automerge

#28523 [Enhancement] improve usert prompt when data loading meets drop table or schema change (backport #28425)
  be/src/storage/delta_writer.cpp
  be/src/storage/tablet_updates.cpp
Labels: automerge

#28402 [Enhancement] support limited memory stream aggregate
  be/src/common/config.h
  be/src/exec/aggregator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.h
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_streaming_source_operator.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/AggregationNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  gensrc/thrift/PlanNodes.thrift
Labels: 3.0, 3.1

#27898 [Enhancement] Optimize routine load error message
  fe/fe-core/src/main/java/com/starrocks/planner/LoadScanNode.java
Labels: 3.1

#28500 [BugFix] Fix the wrong query state of failed query
  fe/fe-core/src/main/java/com/starrocks/qe/QueryState.java
Labels: 2.5, 3.0, 3.1

#28508 [BugFix] PUBLIC role should not in immutable names set
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeBuiltinConstants.java
Labels: 3.0, 3.1

#28520 [Doc] Update param in Paimon catalog
  docs/data_source/catalog/paimon_catalog.md
  docs/table_design/Data_distribution.md
Labels: documentation

#28211 [Enhancement] Reduce consumption time when routine load txn timeout
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaTaskInfo.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 3.1

#28501 [Enhancement] Tips for optimizing replication_num when creating a table
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
Labels: 2.5, 3.0, 3.1

#28327 [Doc] 3.1 Iceberg table sink - 1
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/data_source/catalog/paimon_catalog.md
Labels: documentation

#28302 [Enhancement] update dockerfile, make command example accurate
  docker/dockerfiles/allin1/allin1-ubi.Dockerfile
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
  docker/dockerfiles/artifacts/artifact.Dockerfile
  docker/dockerfiles/be/be-ubi.Dockerfile
  docker/dockerfiles/be/be-ubuntu.Dockerfile
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  docker/dockerfiles/fe/fe-ubi.Dockerfile
  docker/dockerfiles/fe/fe-ubuntu.Dockerfile
  docker/dockerfiles/toolchains/toolchains-centos7.Dockerfile
  docker/dockerfiles/toolchains/toolchains-ubuntu.Dockerfile
Labels: 3.0, 3.1

#28542 Revert "[BugFix] Fix follower fe CpuCores not synchronized (#28472)"
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: title needs [type]

#28499 [Doc] Add loads table
  docs/administration/information_schema.md
  docs/loading/cloud_storage_load.md
  docs/loading/hdfs_load.md
Labels: documentation

#28548 [Doc] Update broker load docs & Information Schema in Branch 3.1
  docs/administration/information_schema.md
  docs/loading/cloud_storage_load.md
  docs/loading/hdfs_load.md
Labels: documentation

#28535 [BugFix] Fix external olap table temp partition
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
Labels: 3.0

#28524 [Enhancement] support check page statistics from profile
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/column_chunk_reader.cpp
Labels: 2.5, 3.0, 3.1

#28560 [Enhancement][Cherry-Pick] Tips for optimizing replication_num when creating a table
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#28551 [Enhancement] Support zstd compression for paimon connector
  java-extensions/paimon-reader/pom.xml
Labels: 3.1

#28553 [Enhancement] Support v3 version image of storage volume mgr
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1

#28550 [Doc] add partial_update_mode in sys variables
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/UPDATE.md
Labels: documentation, title needs [type]

#28562 [Enhancement] more profile information about late materialize and bugfix
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_reader.cpp
Labels: 2.5, 3.0, 3.1

#28578 [Enhancement] more profile message (backport #28562 #28524)
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_reader.cpp
Labels: 2.5

#28554 [BugFix] Rethrow exception when refresh mv failed
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q7.sql
Labels: sig/materialized view

#28572 [BugFix] fix a wrong DCHECK in SenderQueue
  be/src/runtime/sender_queue.cpp
Labels: 3.1

#28552 [BugFix] CacheProbeChunkNum update mistakenly
  be/src/exec/query_cache/cache_operator.cpp
Labels: 2.5, 3.0, 3.1

#28391 [Enhancement] Not showing JDBC external table password
  fe/fe-core/src/main/java/com/starrocks/catalog/JDBCResource.java
  fe/fe-core/src/test/java/com/starrocks/catalog/JDBCResourceTest.java
Labels: 2.5, 2.4, 3.0, 3.1

#28590 [Doc] updating pk table guarantees atomicity
  docs/table_design/table_types/primary_key_table.md
Labels: documentation

#28555 [BugFix] remove unnecessary check in statistic calculate phase  (backport #27646)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnDict.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticRangeValues.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: automerge

#28184 [Enhancement] Add FE memory related metrics
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetailQueue.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TxnStateCallbackFactory.java
  test/sql/test_metrics/R/test_memory_metrics
  test/sql/test_metrics/T/test_memory_metrics
Labels: 2.5, 3.0, 3.1

#28479 [Enhancement] Support text-based profile analysis(2)
  be/src/exec/query_cache/cache_operator.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
Labels: 3.1

#28623 [ Doc]wrong version in pk table
  docs/table_design/Sort_key.md
Labels: documentation, title needs [type]

#28516 [BugFix] Fix the issue of reading paimon table on S3
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonConnector.java
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudCredential.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonConnectorTest.java
  java-extensions/paimon-reader/pom.xml
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
Labels: 3.1

#28595 [BugFix] Fix bug multi partition support maxvalue
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionKeyDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RangePartitionDesc.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 2.5, 3.0, 3.1

#28583 [BugFix] Txn watermark should be reset too after decommission state is reset
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
Labels: 2.5, 3.0, 3.1

#28568 [BugFix] Fix bug paimon table miss implement getUUID
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.1

#28604 [Doc] Add link to bitmap value and update sys variables
  docs/TOC.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/sql-reference/sql-functions/function-list.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
  docs/sql-reference/sql-statements/data-types/data-type-list.md
Labels: documentation, 2.5, 3.0, 3.1

#28217 [Enhancement] make runtime filter number as config
  be/src/exec/hash_joiner.cpp
Labels: 2.5, 3.0, 3.1

#28488 [BugFix] Clear garbage file if clone primary key table failed
  be/src/storage/task/engine_clone_task.cpp
Labels: 2.5, 3.0, 3.1

#28602 [Doc] Maxvalue can not be used for multi partition cols
  docs/deployment/sr_operator.md
  docs/loading/SparkLoad.md
  docs/table_design/Data_distribution.md
Labels: documentation, title needs [type]

#28567 [BugFix] Grant builtin storage volume usage in follower
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
Labels: 3.1

#28643 [BugFix] Only use staleness in query rewrite
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  test/sql/test_materialized_view/R/test_materialized_view_staleness
  test/sql/test_materialized_view/T/test_materialized_view_staleness
Labels: 3.1

#28636 [BugFix] Fix insert job clean
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
Labels: 2.5, 3.0, 3.1

#28592 [BugFix] Forbidden delete by complex type conditition
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/DeleteTest.java
Labels: 3.0, 3.1

#28673 [Doc] add description for config ignore_materialized_view_error
  docs/administration/Configuration.md
Labels: documentation, 2.5, 3.0, 3.1

#28677 [BugFix][Cherry-Pick] Fix table get mysql type
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: automerge

#28681 [BugFix] Fix insert job clean(backport #28636)
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadManager.java
Labels: automerge

#28687 [BugFix] fix jni scanner init failed and crashed
  be/src/connector/hive_connector.cpp
  be/src/exec/jni_scanner.cpp
Labels: 3.1

#28691 remove useless symbol link
  fe/doris_local.md
Labels: title needs [type]

#28696 Revert "[Enhancement] Enlarge the value of config hive_max_split_size (backport #28209)"
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: title needs [type]

#28697 Revert "[Enhancement] Enlarge the value of config hive_max_split_size (backport #28209)"
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: title needs [type]

#28650 [Test] sql test for pipe
  be/src/exec/schema_scanner/schema_pipe_files.cpp
  be/src/exec/schema_scanner/schema_pipes.cpp
  test/sql/test_pipe/R/basic
  test/sql/test_pipe/T/basic
  test/sql/test_pipe/data/col_not_null.parquet
Labels: title needs [type]

#28591 [Doc] 3.1 update BRROKER LOAD & System variables
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation

#28340 [Enhancement] Support query trino view
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveView.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/trino/TrinoViewColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/trino/TrinoViewDefinition.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveViewPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/trino/TrinoViewTest.java
Labels: 3.1

#28131 [Feature] support to_iso8601 function
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/src/runtime/time_types.cpp
  be/src/runtime/time_types.h
  docs/sql-reference/sql-functions/date-time-functions/to_iso8601.md
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#28684 [Enhancement] re-implement bthread_shared_mutex
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.h
  be/src/util/bthreads/bthread_shared_mutex.h
  be/src/util/bthreads/shared_mutex.h
  be/test/util/bthreads/shared_mutex_test.cpp
Labels: 3.1

#27990 [Feature] support regex_extact_all
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/like_predicate-functions/regexp_extract_all.md
  gensrc/script/functions.py
Labels: documentation

#28435 [Enhancement] reduce meaningless join transformation
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociateBaseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinCommutativityRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/JoinLeftAsscomRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OuterJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/enumerate-plan/tpch-q21.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q2.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q22.sql
  fe/fe-core/src/test/resources/sql/query_dump/reduce_transformation_1.json
  fe/fe-core/src/test/resources/sql/query_dump/reduce_transformation_2.json
  fe/fe-core/src/test/resources/sql/query_dump/reduce_transformation_3.json
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q10.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q2.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q20.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q21.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q5.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q7.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q8.sql
  fe/fe-core/src/test/resources/sql/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/tpch/q9.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q2.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
Labels: 3.0, 3.1

#28021 [BugFix] Fix issue with routine Load audit logging bug
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateRoutineLoadAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
Labels: 2.5, 3.0, 3.1

#28710 [BugFix] Revert invalid date partition prune (backport #27780)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ColumnFilterConverter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: automerge

#28711 [BugFix] Revert invalid date partition prune (backport #27780)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ColumnFilterConverter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: automerge

#28708 [BugFix] Revert invalid date partition prune (backport #27780)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ColumnFilterConverter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: automerge

#28612 [Enhancement] Support os page cache in block cache.
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/starcache_wrapper.cpp
  be/src/common/config.h
  be/src/service/service_be/starrocks_be.cpp
  be/test/exec/hdfs_scanner_test.cpp
Labels: 3.1

#28468 [Enhancement] optimize the re-balance strategy for backend scan range
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: 3.0, 3.1

#28661 [BugFix] Cleaning up rowset_stats after the primary key table completes alter job
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 3.0, 3.1

#28571 [Doc] Add datalake faq&update Configuration.md
  docs/TOC.md
  docs/administration/Configuration.md
  docs/data_source/datalake_faq.md
Labels: documentation

#28745 [Doc] 3.1 hive table view
  docs/data_source/catalog/hive_catalog.md
Labels: documentation

#28728 [BugFix] Add SpinLock protect concurrency accesses to TicketChecker
  be/src/exec/query_cache/ticket_checker.cpp
  be/src/exec/query_cache/ticket_checker.h
Labels: 2.5, 3.0, 3.1

#28752 [Doc] add table links to Information Schema
  docs/administration/information_schema.md
Labels: documentation

#28762 Update information_schema.md
  docs/administration/information_schema.md
Labels: title needs [type]

#28755 [BugFix][Cherry-Pick][Branch-2.5] Fix ORC late materialization bug when contains complex type column
  be/src/formats/orc/apache-orc/c++/include/orc/Vector.hh
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.cc
  be/src/formats/orc/apache-orc/c++/src/Reader.cc
  be/src/formats/orc/apache-orc/c++/src/Vector.cc
  be/test/formats/orc/orc_lazy_load_test.cpp
Labels: automerge

#28736 [BugFix] Support set tablet state in script engine to fix tablet in NOT_READAY state in tablet meta caused by #21223
  be/src/script/script.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#28781 [BugFix] Fix the openjdk installation command in start_fe.sh
  bin/start_fe.sh
Labels: 2.5, 2.4, 3.0, 3.1

#28783 [Doc] Update files.md to correct table function name
  docs/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.1

#28722 [Enhancement] Optimize segment iterator initialization
  be/src/storage/rowset/segment_iterator.cpp
Labels: 3.1

#28798 [Feature] Add url extract parameter(backport #26854 #27630 #27726 #27769)
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/CMakeLists.txt
  be/test/exprs/string_fn_url_extract_parameter_test.cpp
  docs/TOC.md
  docs/sql-reference/sql-functions/string-functions/url_decode.md
  docs/sql-reference/sql-functions/string-functions/url_encode.md
  gensrc/script/functions.py
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
  test/sql/test_url_extract_parameter/R/test_url_extract_parameter
  test/sql/test_url_extract_parameter/T/test_url_extract_parameter
Labels: documentation

#28644 [Enhancement] Support ignore show external catalog privilege item in grantsTo system table
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/GrantsTo.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/catalog/InfoSchemaDbTest.java
Labels: 3.0, 3.1

#28821 [Doc] fix broken links in release note 3.1
  docs/release_notes/release-3.1.md
Labels: documentation, title needs [type]

#28829 [Doc] add a bugfix to 2.5.10 rn
  docs/release_notes/release-2.5.md
Labels: documentation

#28704 [Doc] add description for config of dynamic partition
  docs/table_design/dynamic_partitioning.md
Labels: documentation

#28818 [BugFix] Fix bug Json metadata lost fn info
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionRangePartitionInfoTest.java
Labels: 3.0, 3.1

#28753 [Enhancement] Implement bthread support for future/promise
  be/src/util/CMakeLists.txt
  be/src/util/bthreads/future.h
  be/src/util/bthreads/future_impl.cpp
  be/src/util/bthreads/future_impl.h
  be/test/CMakeLists.txt
  be/test/util/bthreads/future_test.cpp
  be/test/util/bthreads/promise_test.cpp
  be/test/util/bthreads/shared_future_test.cpp
Labels: 3.1

#28811 [BugFix] Should not check `canLoad` state when finishing transaction
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 2.5, 3.0, 3.1

#28850 [BugFix] Fix BE crash when null lowcard column not fill with default value
  be/src/runtime/global_dict/parser.cpp
  test/sql/test_global_dict/R/dict_basic_query
  test/sql/test_global_dict/T/dict_basic_query
Labels: 2.5, 3.0, 3.1

#28815 [Enhancement] Disable colocate overall balance by default
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 2.5, 3.0, 3.1

#28856 [Feature] support to_iso8601 function (#28131)
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/src/runtime/time_types.cpp
  be/src/runtime/time_types.h
  docs/sql-reference/sql-functions/date-time-functions/to_iso8601.md
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#28866 [Enhancement] Use cloudera's security fixes log4j 1.2.17
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 2.5, 3.0, 3.1

#28654 [BugFix] Support sync mv with complex expression rewrite without partition column output
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
Labels: 3.1

#28864 [Enhancement] Support ignore show external catalog privilege item in grantsTo system table (#28644)
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/GrantsTo.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/catalog/InfoSchemaDbTest.java
Labels: 3.0

#28855 [Enhancement] Replica should be forcefully deleted after clone
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 2.5, 3.0, 3.1

#28865 [BugFix] Ignore non-partition refresh tables in update meta
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ForeignKeyConstraint.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ForeignKeyConstraintTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.1

#28813 [Enhancement] Support text-based profile analysis(3)
  fe/fe-core/src/main/java/com/starrocks/common/util/DebugUtil.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfilingExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfileParser.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DebugUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileParserTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: 3.1

#28826 [Enhancement] Remove txn rollback logs when aborting empty delta writers
  be/src/runtime/local_tablets_channel.cpp
Labels: 2.5, 3.0, 3.1

#28810 [Doc] 3.0.4 sparkload supports date/datetime/decimal as bucketing cols
  docs/loading/SparkLoad.md
Labels: documentation

#28812 [Doc]2.5.9 sparkload supports date/datetime/decimal as bucketing cols #28810
  docs/loading/SparkLoad.md
Labels: title needs [type]

#28804 [Doc] sparkload-supports-DATE/DATETIME/DECIMAL-as-bucketing-cols
  docs/loading/SparkLoad.md
Labels: documentation

#28693 [Enhancement] show more info when calling seqChooseBackendIds
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 2.5, 3.0, 3.1

#28737 [Feature] Support storage_cooldown_ttl for table
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SinglePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleRangePartitionDesc.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageCoolDownTest.java
Labels: 3.0, 3.1

#28857 [Enhancement] Support column default for default value
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 3.0, 3.1

#28919 [Enhancement] Remove txn rollback logs when aborting empty delta writers (backport #28826)
  be/src/runtime/local_tablets_channel.cpp
Labels: automerge

#28878 [Enhancement] Call request toString only when debug is enabled to avoid memory allocation
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
Labels: 2.5, 3.0, 3.1

#28875 [Doc] add-returned-Description-of-return-fields-and-examples
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW PARTITIONS.md
Labels: documentation

#28950 [Doc] Cp add returned description of return fields and examples
  docs/sql-reference/sql-statements/data-manipulation/SHOW PARTITIONS.md
Labels: documentation

#28929 [BugFix] Fix use-after-free of SchemaLoadTrackingLogsScanner
  be/src/exec/schema_scanner/schema_load_tracking_logs_scanner.cpp
Labels: 3.1

#28867 [BugFix] prune complex type need deal with scan without project
  be/test/formats/parquet/test_data/test_parquet_struct_in_struct.parquet
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java
  test/sql/test_external_file/R/test_parquet_read_range
  test/sql/test_external_file/R/test_parquet_struct_in_struct
  test/sql/test_external_file/T/test_parquet_read_range
  test/sql/test_external_file/T/test_parquet_struct_in_struct
Labels: 2.5, 3.0, 3.1

#28188 [Enhancement] support coalesce block cache read to reduce cache read overhead.
  be/src/block_cache/CMakeLists.txt
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/cachelib_wrapper.h
  be/src/block_cache/io_buffer.cpp
  be/src/block_cache/io_buffer.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
  be/test/io/cache_input_stream_test.cpp
Labels: 3.1

#28847 [BugFix][Cherry-Pick][Branch-2.3] Fix Be crash in ASAN mode if load a unapplied rowset from disk (#22331)
  be/src/storage/tablet_updates.cpp
Labels: automerge

#28941 [BugFix] Fix query hive int partition column like '02' error
  fe/fe-core/src/main/java/com/starrocks/analysis/IntLiteral.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
Labels: 2.5, 3.0, 3.1

#28914 [Doc] Fix Format
  docs/deployment/deploy_shared_data.md
Labels: documentation, 3.1

#28979 [BugFix] Don't always get hedged read metrics
  be/src/common/config.h
  be/src/fs/hdfs/fs_hdfs.cpp
Labels: 3.0, 3.1

#28980 [Cherry-pick][branch-3.1][BugFix] Fix query hive int partition column like '02' error (#28941)
  fe/fe-core/src/main/java/com/starrocks/analysis/IntLiteral.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
Labels: title needs [type]

#28987 [BugFix] Ignore non-partition refresh tables in update meta (#28865) (#28924)
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
Labels: 3.1

#28932 [BugFix] load dcg in load_snapshot cause meta inconsistency if fail (#28931)
  be/src/storage/tablet_updates.cpp
Labels: 3.1

#28986 [BugFix] Fix the error interpretation of <> inside the html page
  fe/fe-core/src/main/java/com/starrocks/http/action/QueryProfileAction.java
  fe/fe-core/src/test/java/com/starrocks/http/QueryProfileActionTest.java
Labels: 2.5, 2.4, 3.0, 3.1
