Repository StarRocks/starrocks, pull requests merged in 2023-03, with the labels that each got.

#18664 [BugFix] Fix Backend get stuck on startup
  be/src/runtime/current_thread.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
Labels: Approved, be-build

#18624 [Doc] update file external table doc
  docs/data_source/file_external_table.md
Labels: documentation, Approved, be-build, 2.5, 3.0

#18633 [BugFix] fix show routine/stream load parser bug
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowStreamLoadStmtTest.java
Labels: Approved, be-build

#18639 [BugFix] Relax check condition for retention
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: Approved, be-build

#18674 [Feature] Support lake materialized view crud (#18523)
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TablesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/ShardDeleter.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVMaintenanceJob.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionChecker.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionLogApplierFactory.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateListenerFactory.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeLakeTabletManager.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
Labels: be-build

#18609 [BugFix] Revert "[Enhancement] OlapTableSink of non-pipeline engine support fast cancel (#15398)"
  be/src/exec/data_sink.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/plan_fragment_executor.cpp
Labels: Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18643 [BugFix] Fix inconsistent column count bug in TransPartitionProcNode
  fe/fe-core/src/main/java/com/starrocks/common/proc/TransPartitionProcNode.java
Labels: Approved, be-build, 3.0

#18644 [Enhancement] Add minimun segment num to trigger compaction avoid too frequently compare to previous version
  be/src/storage/size_tiered_compaction_policy.cpp
Labels: Approved, be-build, 2.5, 3.0

#18626 [Enhancement] Rename cloud native aws config
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
  fe/fe-core/src/test/java/com/starrocks/staros/StarMgrServerTest.java
Labels: Approved, be-build, 3.0

#18555 [Feature] Introduce the starrocks python client using SQLAlchemy
  contrib/sqlalchemy-connector/README.md
  contrib/sqlalchemy-connector/requirements/common.txt
  contrib/sqlalchemy-connector/setup.py
  contrib/sqlalchemy-connector/sqlalchemy_starrocks/dialect.py
  contrib/starrocks-python-client/LICENSE
  contrib/starrocks-python-client/README.md
  contrib/starrocks-python-client/setup.py
  contrib/starrocks-python-client/starrocks/sqlalchemy/__init__.py
  contrib/starrocks-python-client/starrocks/sqlalchemy/dialect.py
Labels: be-build

#18647 [Enhancement] Logging is added for all materialized view inactive
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: Approved, be-build, 2.5, 3.0

#18642 [BugFix] Fix AuthenticationManager init failure
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationManager.java
Labels: Approved, be-build, 3.0

#18703 [Doc] Revert "[Doc] lead/lag supports ignore nulls (backport #18373)"
  docs/sql-reference/sql-functions/Window_function.md
Labels: documentation, automerge, be-build

#18603 [BugFix] Fix write fail randomly since some preparation work was not completed when committing
  be/src/exec/tablet_sink.cpp
  be/src/runtime/local_tablets_channel.cpp
Labels: Approved, be-build, 2.5, 3.0

#18634 [BugFix] Fix the BUG that some keyword mistake set reserved
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: Approved, be-build

#18594 [Enhancement] Use spaces instead of underscore syntax in PrivilegeType and ObjectType
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ObjectType.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeActions.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/RBACExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: Approved, be-build

#18708 [Cherry-pick] Revert "[Enhancement] OlapTableSink of non-pipeline engine support fast cancel (#15398)" (#18609)
  be/src/exec/data_sink.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/plan_fragment_executor.cpp
Labels: automerge, title needs [type], be-build

#18112 [Enhancement]Support iceberg local disk metadata cache
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IOUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java
Labels: Approved, be-build

#18549 [Enhancement] tablet sink dop and scan node dop is not equal in some case
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
Labels: Approved, be-build

#18631 [BugFix] use schema deserialize chunk.
  be/src/storage/table_reader.cpp
  be/src/storage/table_reader.h
Labels: Approved, be-build

#18701 [Doc] fix format in loading faq doc
  docs/faq/loading/Loading_faq.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18649 [Enhancement] optimize storage medium infer when having mixed types
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/test/java/com/starrocks/catalog/StorageMediumInferTest.java
Labels: be-build, 2.5, 2.4, 2.3, 3.0

#18709 [Cherry-pick] Revert "[Enhancement] OlapTableSink of non-pipeline engine support fast cancel (#15398)" (#18609)
  be/src/exec/data_sink.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/plan_fragment_executor.cpp
Labels: automerge, title needs [type], be-build

#18712 [BugFix] Fix automatic partition creation crash when olap table sink write fail
  be/src/exec/pipeline/olap_table_sink_operator.cpp
  be/src/exec/pipeline/olap_table_sink_operator.h
  be/src/exec/tablet_sink.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.h
  be/src/storage/delta_writer.cpp
  gensrc/proto/internal_service.proto
Labels: Approved, be-build, 3.0

#18597 [Feature] Add function utc_time()
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/test/exprs/time_functions_test.cpp
  docs/sql-reference/sql-functions/date-time-functions/utc_time.md
  gensrc/script/functions.py
Labels: be-build

#18586 [UT] Add avro parsing unit tests
  be/test/CMakeLists.txt
  be/test/exec/avro_scanner_test.cpp
  be/test/exec/test_data/json_scanner/avro_array_schema.json
  be/test/exec/test_data/json_scanner/avro_basic_schema.json
  be/test/exec/test_data/json_scanner/avro_complex_schema.json
  be/test/exec/test_data/json_scanner/avro_map_schema.json
  be/test/exec/test_data/json_scanner/avro_nest_schema.json
  be/test/exec/test_data/json_scanner/avro_union_schema.json
Labels: Approved, be-build

#18630 [Enhancement] avoid duplicated local shuffle of lake table
  be/src/connector/connector.h
  be/src/connector/lake_connector.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: Approved, be-build, 3.0

#18707 [Cherry-pick] Revert "[Enhancement] OlapTableSink of non-pipeline engine support fast cancel (#15398)" (#18609)
  be/src/exec/data_sink.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/plan_fragment_executor.cpp
Labels: automerge, title needs [type], be-build

#18749 Don't print unused rewritten plan in MV uts
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: title needs [type]

#18638 [Doc] optimize alter table and system_variable
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18752 [Enhancement] Reduce log printing
  be/src/storage/lake/tablet_manager.cpp
Labels: Approved, 3.0

#18663 [Refactor] Refactor table get mysql type
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: Approved, be-build

#18551 [Feature] support full sort spill to disk
  be/src/common/config.h
  be/src/exec/CMakeLists.txt
  be/src/exec/chunks_sorter.h
  be/src/exec/chunks_sorter_full_sort.cpp
  be/src/exec/chunks_sorter_full_sort.h
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/sort/local_merge_sort_source_operator.cpp
  be/src/exec/pipeline/sort/local_partition_topn_context.cpp
  be/src/exec/pipeline/sort/local_partition_topn_context.h
  be/src/exec/pipeline/sort/local_partition_topn_sink.cpp
  be/src/exec/pipeline/sort/local_partition_topn_sink.h
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/pipeline/sort/partition_sort_sink_operator.h
  be/src/exec/pipeline/sort/sort_context.cpp
  be/src/exec/pipeline/sort/sort_context.h
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.h
  be/src/exec/pipeline/spill_process_channel.cpp
  be/src/exec/pipeline/spill_process_channel.h
  be/src/exec/pipeline/spill_process_operator.cpp
  be/src/exec/pipeline/spill_process_operator.h
  be/src/exec/spill/query_spill_manager.cpp
  be/src/exec/spill/query_spill_manager.h
  be/src/exec/spill/spiller.cpp
  be/src/exec/spill/spiller_path_provider.h
  be/src/exec/spillable_chunks_sorter_full_sort.cpp
  be/src/exec/spillable_chunks_sorter_sort.h
  be/src/exec/topn_node.cpp
  be/src/exec/topn_node.h
  be/src/formats/parquet/file_reader.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/runtime_state.h
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/storage/lake/spark_load.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/stream/mem_state_table_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: Approved, be-build

#18574 [Enhancement] Support update BE config using update statement
  be/src/exec/data_sink.cpp
  be/src/http/action/update_config_action.cpp
  be/src/http/action/update_config_action.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/command_executor.cpp
  be/src/runtime/command_executor.h
  be/src/runtime/schema_table_sink.cpp
  be/src/runtime/schema_table_sink.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/test/CMakeLists.txt
  be/test/runtime/command_executor_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/SchemaTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaTableSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/rpc/PBackendService.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeUpdateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InformationSchemaBeFeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
  gensrc/thrift/DataSinks.thrift
Labels: Approved, be-build, 2.5, 3.0

#18623 [BugFix] BE maybe crash when we delete all records in PrimaryKey table with persistent index in branch-2.5+
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
Labels: be-build, 2.5, 3.0

#18746 [BugFix] Fix get db name exception before ext table priv supported
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalog.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
Labels: Approved, be-build, 3.0

#18713 [BugFix] Fix low cardinality optimize rewrite default limit for partition-topn
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: be-build, 2.5, 2.4, 2.3, 3.0

#18741 [BugFix] Forbid partition-related parameters for non-partitioned materialized …
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: Approved, be-build, 2.5, 3.0

#18787 [BugFix] remove useless python import
  contrib/starrocks-python-client/starrocks/__init__.py
  contrib/starrocks-python-client/starrocks/sqlalchemy/__init__.py
Labels: be-build

#18671 [Enhancement] Upgrade iceberg version to 1.1.0
  fe/fe-core/pom.xml
Labels: Approved, be-build

#18780 [BugFix] Fix TOP-N filter may cause wrong result when using with lowcardinality optimize
  be/src/exec/olap_scan_prepare.cpp
  be/src/storage/olap_runtime_range_pruner.hpp
Labels: Approved, be-build, 3.0

#18716 [UT] Add sql test case for automatic partition
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
Labels: Approved, be-build, 3.0

#18721 [Enhancement] Set the default `block_cache_checksum_enable` to `false` to avoid the checksum overhead
  be/src/block_cache/fb_cachelib.cpp
  be/src/common/config.h
Labels: be-build, 2.5

#18764 [Feature] Support show lake materialized view
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndicesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/privilege/MaterializedViewPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeActions.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowTabletStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
Labels: Approved, be-build

#18488 [BugFix] Fix dead lock of primary key table
  be/src/storage/tablet_updates.cpp
Labels: Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18444 [BugFix] Fix some compatibility for auto increment column (#18443)
  be/src/exec/tablet_sink.cpp
  be/src/storage/delta_writer.h
  be/src/storage/metadata_util.cpp
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupMeta.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved, be-build, 3.0

#18748 [Refactor] Add some comments (#18313)
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: Approved, be-build

#18670 [BugFix] Avoid sampling statistics using count as an alias to duplicate the column name in the table
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: Approved, be-build

#18775 [UT] Make MaterializedViewTests more stable
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewSSBTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
Labels: be-build

#18772 [Enhancement] update `has_any_predicate` for all connectors
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/connector/lake_connector.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
Labels: Approved, be-build

#18751 [Doc] Revise Datadog doc
  docs/integrations/datadog_support.md
Labels: documentation, Approved, be-build, 2.5, 3.0

#18759 [BugFix] ENGINE type in information_schema.tables of external table
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
Labels: Approved, be-build, 3.0

#18744 [Doc] Update broker load faq doc
  docs/faq/loading/Broker_load_faq.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18743 [Enhancement][Cherry-pick] Logging is added for all materialized view inactive
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: be-build

#18810 [Enhancement] use starrocks libre2 and libprotobuf for starlet
  be/CMakeLists.txt
  build.sh
  run-be-ut.sh
Labels: Approved, 3.0

#18791 [Doc] Update the feature introduction page.
  docs/assets/1.1-7-mv.png
  docs/introduction/Features.md
Labels: documentation, Approved, be-build

#18802 [Enhancement] avoid duplicated local shuffle of lake table (#18630)
  be/src/connector/connector.h
  be/src/connector/lake_connector.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: be-build

#18730 [Enhancement] Support iceberg metadata two level cache
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IOUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved, be-build

#18809 [Enhancement] Refactor iceberg connector on fe [stage 1]
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileDesc.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileInfo.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: be-build, 3.0

#18774 [Doc] optimize sum/retention/hll
  docs/sql-reference/sql-functions/aggregate-functions/retention.md
  docs/sql-reference/sql-functions/aggregate-functions/sum.md
  docs/sql-reference/sql-statements/data-definition/HLL.md
  docs/sql-reference/sql-statements/data-types/HLL.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18793 [Feature] support show full columns from external catalog table
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowColumnStmt.java
Labels: Approved, be-build

#17425 [BugFix] Fix Lowcardinality optimization could not work in Materialized View
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build, 2.5

#18859 [Cherry-Pick] support show full columns from external catalog table
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowColumnStmt.java
Labels: title needs [type]

#18837 [Enhancement] Iceberg refactor and optimize [stage 2]
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergFilter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergTableTest.java
Labels: be-build

#18812 [BugFix] Fix session web page display error
  fe/fe-core/src/main/java/com/starrocks/http/action/SessionAction.java
Labels: Approved, be-build, 2.5, 3.0

#18869 [Feature] Support show lake materialized view (#18764)
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndicesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/privilege/MaterializedViewPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeActions.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowTabletStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
Labels: be-build

#18729 [BugFix] Fix bug grant system objectType object NPE
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SetDefaultRoleStmt.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
Labels: Approved, be-build

#18820 [Enhancement] Try to share starlet filesystem instance to reduce memory usage
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
Labels: Approved, be-build, 3.0

#18882 [Cherry-Pick] Iceberg refactor and optimize [stage 2] (#18837)
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergFilter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergTableTest.java
Labels: automerge, title needs [type], be-build

#18872 [Doc] Fix RG query type
  docs/administration/resource_group.md
Labels: documentation, be-build, 2.5, 3.0

#18857 [Feature] support protection for admin user
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: be-build

#18885 [Enhancement] iceberg refactor and optimize on fe [stage 3]
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/TableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: be-build

#18521 [BugFix] fix timestamp underflow for parquet format
  be/src/formats/parquet/column_converter.cpp
  be/src/runtime/time_types.h
  be/src/types/timestamp_value.cpp
  be/src/types/timestamp_value.h
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/test_data/parquet_scanner/timestamp_to_datetime.parquet
Labels: be-build

#18770 [BugFix] fix lake pk index cache ref leak and update delvec cache strategy
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/util/dynamic_cache.h
  be/test/storage/lake/condition_update_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: Approved, be-build, 3.0

#18660 [Enhancement] Default replication_num based on run mode
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/RunMode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RestoreStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: Approved, be-build, 3.0

#18898 [Enhancement][Cherry-Pick] iceberg refactor and optimize on fe [stage 3]
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/TableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: automerge, be-build

#18822 [cherry-pick][branch-3.0][Enhancement] Add lag metrics for PAUSED Kafka Jobs (#18558)
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: automerge, title needs [type], be-build

#18823 [cherry-pick][branch-2.5][Enhancement] Add lag metrics for PAUSED Kafka Jobs (#18558)
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: automerge, title needs [type], be-build

#18891 [Enhancement] refactor and optimize iceberg connector on fe [stage 4]
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergPartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergFileStats.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
Labels: be-build

#18800 [Feature] support view delta join mv rewrite (#18146)
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RewriteContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/SingleTableMvRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build

#18895 [BugFix] Avoid BE crash when apache-orc throw orc::ParseError exception
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
Labels: Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18884 [BugFix] fix create table crash, define hash func for TTaskType
  be/src/agent/agent_server.cpp
Labels: be-build, 2.5, 2.4, 2.3, 3.0

#18902 [Enhancement][cherry-pick] iceberg optimize #18198 #18112 #18671 #18730
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IOUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: automerge, be-build

#18920 [Enhancement]Check if default replication num greater than alive backends num for lake table
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
Labels: 3.0

#18941 [Enhancement] Explicit DateTimeValue constructor
  be/src/runtime/datetime_value.h
Labels: 3.0

#18914 [Doc] Add missing SQL docs
  docs/TOC.md
  docs/sql-reference/sql-statements/Administration/ADD SQLBLACKLIST.md
  docs/sql-reference/sql-statements/Administration/DELETE SQLBLACKLIST.md
  docs/sql-reference/sql-statements/Administration/EXPLAIN.md
  docs/sql-reference/sql-statements/Administration/KILL.md
  docs/sql-reference/sql-statements/Administration/SET.md
  docs/sql-reference/sql-statements/Administration/SHOW SQLBLACKLIST.md
  docs/sql-reference/sql-statements/Administration/SHOW VARIABLES.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18899 [BugFix] Fix potential bug: bthread::execution_queue_join() on invalid id
  be/src/storage/lake/async_delta_writer.cpp
Labels: be-build, 3.0

#18727 [Doc] 3.0 replace()
  docs/sql-reference/sql-functions/string-functions/replace.md
Labels: documentation, be-build

#18370 [Doc]add bitmap func related be config
  docs/administration/Configuration.md
Labels: documentation, Approved, be-build

#18931 [BugFix] Support user can kill its own connection or query
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
Labels: Approved, be-build, 3.0

#18861 [Cherry-Pick] support show full columns from external catalog table
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowColumnStmt.java
Labels: title needs [type], be-build

#18868 [Enhancement] Optimize scan range placement of hdfs backend selector
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: Approved, be-build

#18803 [Refactor] Adapt to the new shadow partition
  be/src/exec/tablet_info.cpp
  be/src/runtime/load_channel.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  gensrc/thrift/Descriptors.thrift
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
Labels: Approved, be-build, 3.0

#17150 [Doc] Add Audit Loader
  docs/TOC.md
  docs/administration/audit_loader.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18838 [BugFix] make wait for version timeout smaller than exec_plan_fragment rpc timeout
  be/src/storage/tablet_updates.cpp
Labels: be-build, 2.5, 2.4, 2.3, 3.0

#18815 [Doc] update column mapping in loading docs
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#18841 [BugFix] Forward parallel fragment exec instance num and report success to leader
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java
  gensrc/thrift/InternalService.thrift
Labels: be-build

#18935 [Enhancement] Get thread dump before acquire database lock
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: be-build

#18932 [Enhancement] Get thread dump before acquire database lock
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: be-build

#18933 [Enhancement] Get thread dump before acquire database lock
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: be-build

#18934 [Enhancement] Get thread dump before acquire database lock
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: be-build

#18801 [BugFix] Fix ASAN crash when streaming AGG group by with const column
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/stream/aggregate/stream_aggregator.cpp
Labels: be-build, 3.0

#18917 [Enhancement][Cherry-Pick][Branch-3.0] Improve subfield partial load for complex type column
  fe/fe-core/src/main/java/com/starrocks/catalog/ComplexTypeAccessGroup.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ComplexTypeAccessPath.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ComplexTypeAccessPathType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ComplexTypeAccessPaths.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MapType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/StructType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
Labels: automerge, be-build

#18669 [Feature] support update lake table colocation info by http api
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/ColocateMetaService.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved, be-build

#18921 [Tool] meta_tool support dump segment data and short key index
  be/src/column/datum_convert.h
  be/src/runtime/current_thread.h
  be/src/runtime/memory/mem_chunk_allocator.cpp
  be/src/storage/types.cpp
  be/src/storage/types.h
  be/src/tools/meta_tool.cpp
  be/src/types/logical_type.h
Labels: Approved, be-build

#18842 [Enhancement] add accumulator for sorted streaming aggregator
  be/src/exec/pipeline/aggregate/sorted_aggregate_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/sorted_aggregate_streaming_sink_operator.h
  be/src/exec/pipeline/aggregate/sorted_aggregate_streaming_source_operator.cpp
  be/src/exec/sorted_streaming_aggregator.cpp
  be/src/exec/sorted_streaming_aggregator.h
Labels: be-build, 2.5, 3.0

#17927 [BugFix] Fix ORC's SearchArgument not followed with case sensitive behavior
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
Labels: be-build

#18987 [Enhancement] Default replication_num based on run mode (#18660)
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/RunMode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RestoreStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: be-build

#18865 [BugFix] Report error when creating table with unknown properties
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleRangePartitionDesc.java
  fe/fe-core/src/test/java/com/starrocks/binlog/BinlogManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewPlanTest.java
Labels: be-build, 3.0

#18940 [Doc] Modify enable_hive_metastore_cache to enable_metastore_cache in external catalog
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
Labels: documentation, be-build

#18750 [Feature] Support mv refresh by partition for hive table
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/Partition.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build

#18913 [Enhancement] Refactor and optimize iceberg connector on fe [stage 5]
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Resource.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CatalogLoader.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRepository.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/glue/IcebergGlueCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/TableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergResourceTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergCustomCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergGlueCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergHiveCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergRESTCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TableTestBase.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TestTables.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/cost/IcebergStatisticProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculatorTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogLevelTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: Approved, be-build

#18893 [Enhancement] Add MultiLevelFeedScanTaskQueue
  be/src/common/config.h
  be/src/exec/pipeline/pipeline_driver_queue.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/workgroup/scan_executor.cpp
  be/src/exec/workgroup/scan_task_queue.cpp
  be/src/exec/workgroup/scan_task_queue.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group_fwd.h
  be/src/runtime/exec_env.cpp
  be/test/CMakeLists.txt
  be/test/exec/pipeline/pipeline_driver_queue_test.cpp
  be/test/exec/workgroup/scan_task_queue_test.cpp
Labels: be-build, 2.5, 2.4, 2.3, 3.0

#19010 [doc]Update release-2.5.md
  docs/release_notes/release-2.5.md
Labels: documentation, title needs [type]

#19014 [doc] update administration
  docs/administration/Cluster_administration.md
Labels: documentation, title needs [type]

#18821 [Doc] add strict mode doc & update EXPORT doc
  docs/TOC.md
  docs/loading/load_concept/strict_mode.md
  docs/sql-reference/sql-statements/data-manipulation/EXPORT.md
Labels: documentation, Approved, be-build, 2.5, 3.0

#18915 [Doc] Update spark&flink connector unloading docs
  docs/unloading/Flink_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3, 3.0

#19022 [Doc] Fix typo in field
  docs/administration/information_schema.md
Labels: documentation, be-build, 2.5, 3.0

#18863 [BugFix] Reset current database after using catalog
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ChangeCatalogDBTest.java
Labels: Approved, be-build, 2.5, 3.0

#18993 [BugFix][Cherry-Pick][Branch-2.5] Fix ORC's SearchArgument not followed with case sensitive behavior
  be/src/exec/vectorized/hdfs_scanner_orc.cpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
Labels: automerge, be-build

#18016 [Enhancement] show proc by names
  fe/fe-core/src/main/java/com/starrocks/common/proc/DbsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TablesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TransDbProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TransStateProcDir.java
Labels: Approved, be-build

#18614 [BugFix] Fix wrong implementation of first_value/last_value/lead/lag with ignore nulls
  be/src/exprs/agg/window.h
Labels: Approved, be-build, 3.0

#19007 [Enhancement]Check if default replication num greater than alive backends num for lake table
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
Labels: Approved, be-build

#19047 [Doc] mod enable_hive_metastore_cache in catalog
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
Labels: documentation, Approved, be-build, 2.5, 3.0

#18836 [BugFix] Fix FE host redundant bug when restart FE node in k8s cluster
  fe/fe-core/src/main/java/com/starrocks/common/util/NetUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/ha/BDBHATest.java
  fe/fe-core/src/test/java/com/starrocks/server/NodeMgrTest.java
Labels: be-build, 2.5, 2.4, 3.0

#19039 [BugFix] Revert "Fix mysql client unable to change current catalog"
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/UseCatalogStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
Labels: be-build

#18833 [Enhancement] Add hybrid run mode for developes
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/RunMode.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: Approved, be-build, 3.0

#18975 [Feature] Automatic partition support async mv
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: be-build

#19043 [Enhancement] starosworker on demand get shard info
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
Labels: Approved, be-build, 3.0

#19038 [BugFix] Revert "Fix mysql client unable to change current catalog"
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/UseCatalogStmtTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#19052 [Enhancement] Reduce thrift size 1: remove unnecessary field of SlotDescriptor in FE
  fe/fe-core/src/main/java/com/starrocks/analysis/DescriptorTable.java
  fe/fe-core/src/main/java/com/starrocks/analysis/GroupByClause.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TupleDescriptor.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
Labels: Approved, be-build

#18959 [Doc] Added jupysql integration
  docs/integrations/intro.md
  docs/integrations/jupysql.md
Labels: documentation, be-build

#19015 [Doc] Update Desc auto_refresh_partitions_limit
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
Labels: documentation, Approved, be-build, 2.5, 3.0

#19075 [Doc] Update Flink_connector.md
  docs/unloading/Flink_connector.md
Labels: documentation, be-build

#19074 [Doc] Update Flink_connector.md
  docs/unloading/Flink_connector.md
Labels: documentation, be-build

#19077 [Doc] Update Spark_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, be-build

#19076 [Doc] Update Spark_connector.md
  docs/unloading/Spark_connector.md
Labels: documentation, be-build

#18992 [Refactor] Adjust stream load planner timeout reduce the db lock timeout error
  be/src/http/action/stream_load.cpp
Labels: Approved, be-build

#19060 [BugFix] Fix replay InsertOverwriteJob NPE bug
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobManager.java
Labels: Approved, be-build, 2.5, 2.4, 3.0

#19071 [Refactor] use StarRocksConnectorException instead of StarRocksIcebergException
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/StarRocksIcebergException.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/glue/IcebergGlueCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergCustomCatalogTest.java
Labels: be-build, 3.0

#19069 [Enhancement] hive metastore cache max num is configurable by catalog properties
  fe/fe-core/src/main/java/com/starrocks/connector/CachingRemoteFileConf.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastoreConf.java
Labels: be-build, 2.5, 3.0

#19050 [BugFix] Fix be_ prefix information schema table only run in one be
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: Approved, be-build, 2.5, 2.4, 3.0

#19072 [BugFix] fix that display hive metastore api profile with mutiple tables in query
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/sql/PlannerProfile.java
Labels: be-build, 2.5, 3.0

#19012 [BugFix] Fix partial partition query rewrite for external table
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalDeltaLakeScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalFileScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build, 2.5, 3.0

#19087 [BugFix] Remove map_from_arrays() functions in FE UT
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#19097 fix:spell mistake starrocks.thridparty -> starrocks.thirdparty
  fe/fe-core/pom.xml
Labels: title needs [type], be-build

#19099 [Enhancement] Statistic table use unique key type in shared_data mode
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
Labels: be-build, 3.0

#18996 [Tool] meta_tool support dump segment data and segment index (#18921)
  be/src/column/datum_convert.h
  be/src/runtime/current_thread.h
  be/src/runtime/memory/mem_chunk_allocator.cpp
  be/src/storage/types.cpp
  be/src/storage/types.h
  be/src/tools/meta_tool.cpp
  be/src/types/logical_type.h
Labels: automerge, be-build

#18997 [Tool] meta_tool support dump segment data and segment index (#18921)
  be/src/column/datum_convert.h
  be/src/runtime/current_thread.h
  be/src/runtime/memory/chunk_allocator.cpp
  be/src/tools/meta_tool.cpp
Labels: automerge, be-build

#18905 [Enhancement] Support Kerberos Authentication in RBAC
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationManager.java
  fe/fe-core/src/main/java/com/starrocks/authentication/KerberosAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Password.java
Labels: Approved, be-build, 3.0
