Repository StarRocks/starrocks, pull requests merged in 2023-07, with the labels that each got.

#25804 [Enhancement]Use inferred storage medium and cooldown time if not provided
  fe/fe-core/src/main/java/com/starrocks/catalog/DataProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/common/PropertyAnalyzerTest.java
Labels: documentation, 2.5, 3.0, 3.1

#25035 [Enhancement] remove unnecessary dcheck in dynmaic cache
  be/src/util/dynamic_cache.h
Labels: 3.0, 3.1

#26304 [Enhancement] Rename FE config async_load_task_pool_size to max_broker_load_job_concurrency and make it mutable (#25736)
  docs/administration/Configuration.md
  docs/loading/BrokerLoad.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/task/PriorityLeaderTaskExecutor.java
Labels: documentation

#26356 [BugFix] fix sort key as scan range in lake pk table
  be/src/storage/lake/tablet_reader.cpp
Labels: 3.1

#26362 [BugFix] Fix missing params bug in builtin s3 storage volume
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1

#26238 [Enhancement] Optimize the root path choosing logic on tablet creation
  be/src/common/config.h
  be/src/storage/data_dir.cpp
  be/src/storage/data_dir.h
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: 2.5, 3.0, 3.1

#26358 [BugFix] Fix the issue of loading journal type 100
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
Labels: 2.5, 3.0, 3.1

#25880 [Doc] 3.1 map/struct/named_struct/row/all_match/any_match
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/all_match.md
  docs/sql-reference/sql-functions/array-functions/any_match.md
  docs/sql-reference/sql-functions/array-functions/array_generate.md
  docs/sql-reference/sql-functions/struct-functions/named_struct.md
  docs/sql-reference/sql-functions/struct-functions/row.md
  docs/sql-reference/sql-statements/data-types/Map.md
  docs/sql-reference/sql-statements/data-types/STRUCT.md
Labels: documentation, 3.1

#26136 [Doc] 3.1 str_to_map, map_concat, element_at, cardinality, distinct_m…
  docs/sql-reference/sql-functions/array-functions/array_length.md
  docs/sql-reference/sql-functions/array-functions/cardinality.md
  docs/sql-reference/sql-functions/array-functions/element_at.md
  docs/sql-reference/sql-functions/map-functions/cardinality.md
  docs/sql-reference/sql-functions/map-functions/distinct_map_keys.md
  docs/sql-reference/sql-functions/map-functions/element_at.md
  docs/sql-reference/sql-functions/map-functions/map_apply.md
  docs/sql-reference/sql-functions/map-functions/map_concat.md
  docs/sql-reference/sql-functions/map-functions/map_filter.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/sql-reference/sql-functions/map-functions/map_keys.md
  docs/sql-reference/sql-functions/map-functions/map_size.md
  docs/sql-reference/sql-functions/map-functions/map_values.md
  docs/sql-reference/sql-functions/map-functions/transform_keys.md
  docs/sql-reference/sql-functions/map-functions/transform_values.md
  docs/sql-reference/sql-functions/string-functions/str_to_map.md
Labels: documentation, 3.1

#26379 [Doc] update show create table and optimize show partitions
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW PARTITIONS.md
  docs/table_design/Data_distribution.md
Labels: documentation, 2.5, 3.0, 3.1

#26343 [Enhancement] Declare some methods with nodiscard attribute
  be/src/agent/agent_server.cpp
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/workgroup/scan_executor.cpp
  be/src/http/action/update_config_action.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/lake_snapshot_loader.cpp
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_writer.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/src/storage/txn_manager.cpp
  be/src/util/threadpool.h
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/service/lake_service_test.cpp
  be/test/storage/base_compaction_test.cpp
  be/test/storage/cumulative_compaction_test.cpp
  be/test/storage/default_compaction_policy_test.cpp
  be/test/storage/lake/auto_increment_partial_update_test.cpp
  be/test/storage/lake/condition_update_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: 3.0, 3.1

#26350 [Doc] minior modification in 2.3.xrn
  docs/release_notes/release-2.3.md
Labels: documentation

#26405 [Doc] cp update show create table
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW PARTITIONS.md
  docs/table_design/Data_distribution.md
Labels: documentation

#26407 [Doc] update 3.0 function docs based on 3.1
  docs/TOC.md
  docs/sql-reference/sql-functions/array-functions/array_length.md
  docs/sql-reference/sql-functions/array-functions/cardinality.md
  docs/sql-reference/sql-functions/array-functions/element_at.md
  docs/sql-reference/sql-functions/map-functions/cardinality.md
  docs/sql-reference/sql-functions/map-functions/element_at.md
  docs/sql-reference/sql-functions/map-functions/map_filter.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/sql-reference/sql-functions/map-functions/map_keys.md
  docs/sql-reference/sql-functions/map-functions/map_size.md
  docs/sql-reference/sql-functions/map-functions/map_values.md
  docs/sql-reference/sql-functions/map-functions/transform_keys.md
  docs/sql-reference/sql-functions/map-functions/transform_values.md
Labels: documentation

#26280 [BugFix] fix lake primary index load concurrent
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/lake_primary_index.h
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
Labels: 3.1

#26363 [BugFix] Bind storage volume to db when it has been created successfully
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1

#26408 [Enhancement] Does not carry min_active_txn_id in heartbeat requests
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  gensrc/thrift/HeartbeatService.thrift
Labels: 3.1

#26433 [Doc] add 2.5.8/3.0.3 rn
  docs/release_notes/release-2.5.md
  docs/release_notes/release-3.0.md
  docs/table_design/Data_distribution.md
Labels: documentation

#26430 [BugFix] Fix replay colocate table NPE BUG
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.1

#26175 [BugFix] Bind storage volume to table when it has been created successfully
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
Labels: 3.1

#26133 [Feature] Table function table() supports HDFS
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/util/starrocks_metrics.h
Labels: documentation

#26123 [BugFix][Cherry-pick][Branch-2.5] Failed delete job do not return until timeout (#23320)
  fe/fe-core/src/main/java/com/starrocks/common/MarkedCountDownLatch.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/OlapDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/task/PushTask.java
Labels: automerge

#26250 [BugFix] Fix wrong result local-dictionary exceed max(int16)
  be/src/storage/column_predicate_rewriter.cpp
  test/sql/test_push_down_predicate/R/test_expr_predicate_push_down
  test/sql/test_push_down_predicate/T/test_expr_predicate_push_down
Labels: 2.5, 2.4, 3.0, 3.1

#26452 Update case_when.md
  docs/sql-reference/sql-functions/condition-functions/case_when.md
Labels: documentation, title needs [type]

#26411 [Enhancement] Preventing the vacuum process from blocking the tablet creation
  be/src/service/service_be/lake_service.cpp
Labels: 3.1

#26435 [BugFix] Fix orc load fail
  be/src/formats/orc/orc_chunk_reader.cpp
Labels: 3.0, 3.1

#24880 [Enhancement] mv rewrite predicate split support multi range
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateSplit.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateSplitTest.java
Labels: sig/materialized view

#26157 [BugFix] avoid allocate memory when dump trace info
  be/src/common/logconfig.cpp
  be/src/runtime/current_thread.h
Labels: 3.1

#23510 [Enhancement] broker support multiple name services
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
  fs_brokers/apache_hdfs_broker/src/test/java/com/starrocks/broker/hdfs/TestFileSystemManager.java
Labels: 2.5, 2.4, 2.3, 3.0

#26425 [Enhancement] Reducing the impact of slow transactions on auto vacuum
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: 3.1

#26318 [Enhancement] Upgrade thirdparty lib hadoop to 3.3.6
  thirdparty/vars-aarch64.sh
  thirdparty/vars-x86_64.sh
Labels: 2.5, 3.0, 3.1

#26451 [BugFix] Fix replay create db and table with storage volume
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
Labels: 3.1

#26478 [Doc] 3.1 table function
  docs/loading/BrokerLoad.md
  docs/loading/Loading_intro.md
Labels: documentation

#26483 [Doc] Remove documents of deleted configurations
  docs/administration/Configuration.md
Labels: documentation

#26414 [Enhancement] Calculate compaction score from max size-tiered level rowsets for cloud native table
  be/src/storage/lake/compaction_policy.cpp
  be/test/storage/lake/compaction_policy_test.cpp
Labels: 3.0, 3.1

#26419 [Enhancement] Wait starmgr address ready when get shard info from starmgr
  be/src/service/staros_worker.cpp
Labels: 3.0, 3.1

#26162 [Enhancement] Check params of storage volume
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedNothingStorageVolumeMgrTest.java
Labels: 3.1

#26443 [BugFix] Support to read larger parquet page header
  be/src/common/config.h
  be/src/formats/parquet/page_reader.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/test_data/large_page_header.parquet
Labels: 3.0, 3.1

#26486 [BugFix] primary key table with sort key compaction maybe failed
  be/src/storage/compaction_utils.cpp
Labels: 2.5, 3.0, 3.1

#26498 [BugFix] Fix bug when multi-column partition the error message is incorrect
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 2.5, 3.0, 3.1

#26514 [BugFix] Revert (#26133)
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/util/starrocks_metrics.h
Labels: 3.1

#26520 [Enhancement] Upgrade hadoop to 3.3.6 due to commons-configuration2
  fe/pom.xml
Labels: 2.5, 3.0, 3.1

#26457 [BugFix] Exit if create thread failed when submit apply task
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#26454 [Enhancement] use specific kvstore when rowset link files and remove files
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
  test/sql/test_partial_update_column_mode/R/test_partial_update_rowset_link
  test/sql/test_partial_update_column_mode/T/test_partial_update_rowset_link
Labels: 3.1

#26484 [BugFix] conditional expression process const columns error
  be/src/exprs/condition_expr.cpp
  be/test/exprs/coalesce_expr_test.cpp
  be/test/exprs/compound_predicate_test.cpp
  be/test/exprs/condition_expr_test.cpp
  be/test/exprs/if_expr_test.cpp
  be/test/exprs/mock_vectorized_expr.h
  be/test/exprs/null_if_expr_test.cpp
Labels: 3.1

#26285 [Enhancement] infer bucket number for materialized view
  be/src/util/stack_trace_mutex.cpp
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  test/sql/test_materialized_view/R/test_create
  test/sql/test_materialized_view/R/test_show_materialized_view
  test/sql/test_materialized_view/T/test_create
Labels: 3.1

#26232 [BugFix] Fix priority of polymorphic function error
  be/src/exprs/array_functions.cpp
  be/src/exprs/subfield_expr.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/T/test_array_fn
Labels: 3.1

#26535 [Enhancement][Cherry-Pick] Upgrade hadoop to 3.3.6 due to commons-configuration2
  fe/pom.xml
Labels: automerge

#26471 [BugFix] ReplicationNum has not been reset when doing restore (#26423)
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 2.5, 2.4, 3.0, 3.1

#26542 [BugFix][Cherry-Pick] Fix bug when multi-column partition the error message is incorrect
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: automerge

#26525 [BugFix] Fix Query hive/hudi with class cast exception
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/ListPartitionPrunerTest.java
Labels: 3.0, 3.1

#23366 [BugFix] fix recover tablet not work
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 2.5, 3.0

#26485 [BugFix] Fix load Problem for generated column 2(#25828)
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
Labels: 3.1

#25690 [Enhancement] Add object storage timeout parameters to support configuring them
  be/src/common/config.h
  be/src/fs/fs_s3.cpp
Labels: 3.0, 3.1

#26562 [BugFix] fix recover tablet not work (backport #23366)
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: automerge

#26572 [BugFix] Remove package org.codehaus.jackson ref code
  fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/EsRestClient.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetLogFileAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableRowCountAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableSchemaAction.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/elasticsearch/PartitionPhaseTest.java
Labels: 2.5, 3.0, 3.1

#26585 [BugFix][Cherry-Pick] Remove package org.codehaus.jackson ref code
  fe/fe-core/src/main/java/com/starrocks/external/elasticsearch/EsRestClient.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetLogFileAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableRowCountAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableSchemaAction.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/external/elasticsearch/PartitionPhaseTest.java
Labels: automerge

#26594 [branch-2.3] support hash join short_circuit_break child(1) open stage
  be/src/exec/vectorized/hash_join_node.cpp
Labels: title needs [type]

#26588 [Enhancement] Limit the frequency of remote storage requests through configuration
  be/src/common/config.h
  be/src/fs/fs_starlet.cpp
  be/src/io/output_stream.h
  be/src/io/throttled_output_stream.h
  be/src/io/throttled_seekable_input_stream.h
  be/src/storage/lake/vacuum.cpp
Labels: 3.1

#26595 [Enhancement] Add some bvars about metacache of cloud native table
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
Labels: 3.1

#26574 [BugFix] Fix MustNullExpr chunk is nullptr
  be/src/exprs/cast_expr.cpp
Labels: 3.1

#26592 [BugFix] fix version not found when concurrent clone and publish version
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 2.5, 3.0, 3.1

#26586 [BugFix] fill AUTO_INCREMENT fail in Cloud Native mode(#26584)
  be/src/storage/lake/delta_writer.cpp
Labels: 3.0, 3.1

#26518 [Enhancement] Add LastReportVersion to Replica to help detect data lose on backend
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 2.5, 3.0, 3.1

#26579 [Enhancement] Make properties optional for create repository syntax
  be/src/runtime/snapshot_loader.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: 2.5, 3.0, 3.1

#26619 [Enhancement][Cherry-Pick] Add table_id to information_schema.tables_config
  be/src/exec/vectorized/schema_scanner/schema_tables_config_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/SchemaTable.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge

#26603 [BugFix] probe_remain finishes prematurely because of join runtimefilter
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
Labels: 2.5, 2.4, 3.0, 3.1

#26593 [BugFix] Fix bug insert overwrite by value support multi partition
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  test/sql/test_automatic_partition/R/test_insert_overwrite
  test/sql/test_automatic_partition/T/test_insert_overwrite
Labels: 3.0, 3.1

#26641 [Doc] cp add dynamic config and update hive catalog to Branch 2.5
  docs/administration/Configuration.md
  docs/data_source/catalog/hive_catalog.md
  docs/sql-reference/sql-statements/Administration/ADMIN SET CONFIG.md
  docs/sql-reference/sql-statements/Administration/ADMIN SHOW CONFIG.md
Labels: documentation

#26633 [Doc] add note for dynamic config and update hive catalog
  docs/administration/Configuration.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/jdbc_catalog.md
  docs/sql-reference/sql-statements/Administration/ADMIN SET CONFIG.md
  docs/sql-reference/sql-statements/Administration/ADMIN SHOW CONFIG.md
Labels: documentation, 3.0, 3.1

#26631 [BugFix] Fix the mem leak of build in predicate for es external table
  be/src/exec/es/es_predicate.cpp
Labels: 2.5, 2.4, 3.0, 3.1

#26654 [BugFix] fix cache key access failure in staros worker
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
Labels: 3.1

#26652 [BugFix] Bugfix of generate_series
  be/src/exprs/table_function/generate_series.h
  test/sql/test_generate_series/R/test_generate_series
  test/sql/test_generate_series/T/test_generate_series
Labels: 3.1

#26415 [Feature] add function of date_diff in multi actions
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/date_diff.md
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#26647 [BugFix] throw exception when writing unsupported parquet type data.
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  be/src/formats/parquet/file_writer.cpp
  be/test/formats/parquet/file_writer_test.cpp
Labels: 3.1

#26596 [BugFix] remove line separator correctly when log stmt
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MultiJoinReorderTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/tpchcost/q1.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
Labels: 2.5, 3.0, 3.1

#26463 [BugFix] Fix possible inconsistencies in the global dictionary
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/runtime/global_dict/types_fwd_decl.h
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/storage/rowset/column_writer.h
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/segment_flush_executor.cpp
  be/test/storage/rowset_merger_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/IDictManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/MockDictManager.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PartitionCommitInfo.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TabletCommitInfo.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  gensrc/proto/descriptors.proto
  gensrc/proto/internal_service.proto
  gensrc/thrift/Data.thrift
  gensrc/thrift/Types.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_global_dict/R/continuous_insert
  test/sql/test_global_dict/R/truncate_with_insert
  test/sql/test_global_dict/T/continuous_insert
  test/sql/test_global_dict/T/truncate_with_insert
Labels: 2.5, 3.0, 3.1

#25388 [Enhancement] Support colocate sender in tablet sink
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/exec/tablet_sink_colocate_sender.cpp
  be/src/exec/tablet_sink_colocate_sender.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/exec/tablet_sink_sender.cpp
  be/src/exec/tablet_sink_sender.h
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  gensrc/thrift/DataSinks.thrift
  test/sql/test_materialized_view/R/test_sync_materialized_view_with_colocate
  test/sql/test_materialized_view/T/test_sync_materialized_view_with_colocate
Labels: sig/materialized view, 3.1

#26670 [Doc] add 3.1 generate_series
  docs/TOC.md
  docs/sql-reference/sql-functions/table-functions/generate_series.md
Labels: 3.1

#26663 [Doc] INSERT FROM S3
  docs/loading/InsertInto.md
  docs/sql-reference/sql-statements/data-manipulation/insert.md
Labels: 3.1

#26417 [Doc] Add annotations for shared-data
  docs/administration/Configuration.md
  docs/deployment/deploy_shared_data.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, 3.0, 3.1

#26303 [Doc] 3.1-add-col-mode-partial-update
  docs/sql-reference/sql-statements/data-manipulation/UPDATE.md
Labels: documentation

#26293 [Doc] 3.1-add-shared-data-related-feature
  docs/sql-reference/sql-statements/auto_increment.md
  docs/table_design/automatic_partitioning.md
  docs/table_design/table_types/primary_key_table.md
Labels: documentation

#26489 [Enhancement] randomize mv refresh start
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: documentation, 3.1

#26657 [BugFix] Fix create hive/hive catalog with param hive.metastore.type error
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnector.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
Labels: 2.5, 3.0, 3.1

#26668 [BugFix] Fix dynamic partition prefix require is not false
  fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DynamicPartitionTableTest.java
Labels: 2.5, 3.0, 3.1

#26598 [Enhancement] Optimize the partition prune for hive table
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/ListPartitionPrunerTest.java
Labels: 2.5, 3.0, 3.1

#26578 [ Doc]3.1 add generated col
  docs/TOC.md
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/generated_columns.md
Labels: documentation, title needs [type]

#26468 [Doc] Add more docs for Materaizlied Views
  docs/sql-reference/sql-functions/date-time-functions/date_slice.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, 3.1

#26179 [Doc] 3.1 MV Updates
  docs/sql-reference/sql-statements/data-definition/ALTER MATERIALIZED VIEW.md
  docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, 3.1

#26025 [BugFix] fix memory usage issue of spillable hash join
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.h
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
  be/src/exec/spill/spiller.hpp
Labels: 3.0, 3.1

#26737 [Cherry-pick][Branch-2.5][BugFix] Fix create hive/hive catalog with param hive.metastore.type error (#26657)
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnector.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
Labels: title needs [type]

#26731 add limit in spark load
  docs/loading/SparkLoad.md
  docs/sql-reference/sql-statements/data-manipulation/SPARK LOAD.md
Labels: documentation, title needs [type]

#26727 [Doc] Add Azure Blob
  docs/administration/Configuration.md
  docs/deployment/deploy_shared_data.md
Labels: 3.1

#26746 [Cherry-pick][branch-3.0][Feature] support dayofweek_iso function (#26240)
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/day_of_week_iso.md
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation, title needs [type]

#26761 Update README.md
  README.md
Labels: title needs [type]

#26762 Update ide-setup.md
  docs/developers/development-environment/ide-setup.md
Labels: documentation, title needs [type]

#26763 Update IDEA.md
  docs/developers/development-environment/IDEA.md
Labels: documentation, title needs [type]

#26738 [BugFix] Fix use-after-free when set_call_back
  be/src/exec/aggregator.cpp
  be/src/exec/hash_joiner.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/nljoin/nljoin_context.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_build_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.cpp
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/pipeline/spill_process_operator.cpp
  be/src/exec/spill/executor.h
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/spiller.h
  be/src/exec/spillable_chunks_sorter_full_sort.cpp
Labels: 3.0, 3.1

#26732 [BugFix] fix parquet writer when writing struct type with field id
  be/src/formats/parquet/file_writer.cpp
  be/test/formats/parquet/file_writer_test.cpp
Labels: 3.1

#26743 [BugFix] Disable inserting NULL values into partition columns in an Iceberg table
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: 3.1

#26702 [BugFix] make parser error message more clear
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
Labels: 3.1

#26509 [BugFix] Add invalid tablet meta cleaner
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletMeta.java
  fe/fe-core/src/main/java/com/starrocks/clone/ClusterLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/task/PublishVersionTask.java
Labels: 2.5, 3.0, 3.1

#26431 [Enhancement] Support query dump for materialized view
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServerHandler.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/QueryDumpAction.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalcUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/ReplayMetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DeletePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/UpdatePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/join_agg1.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/join_agg2.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/join_agg3.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/join_agg4.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mv_on_mv1.json
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q5.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q7.sql
  test/sql/test_default_enable_replicated_storage/R/test_enable_mv
  test/sql/test_materialized_view/R/test_show_materialized_view
Labels: sig/materialized view, 3.1

#26778 [Doc] Bugfix in 3.1 docs
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/UPDATE.md
Labels: documentation

#26323 [Doc] 3.1-random-distribution
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/table_design/Data_distribution.md
Labels: documentation, title needs [type]

#26789 [Doc] Shared-data minor update
  docs/deployment/deploy_shared_data.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: 3.1

#26766 [Enhancement] Don't parse partition value for each chunk when inserting static partition iceberg table
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.h
Labels: 3.1

#26786 [Enhancement][Cherry-pick] Add LastReportVersion to Replica to help detect data lose on backend
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: automerge

#26422 [Feature] Suppport jodatime_format function
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/src/runtime/datetime_value.cpp
  be/src/runtime/datetime_value.h
  be/test/exprs/time_functions_test.cpp
  docs/sql-reference/sql-functions/date-time-functions/jodatime_format.md
  gensrc/script/functions.py
Labels: documentation

#26759 [Cherry-pick][Branch-3.0][Enhancement]Optimize the partition prune for hive table (#26598)
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/ListPartitionPrunerTest.java
Labels: title needs [type]

#26401 [Enhancement] Support complex type expression push down
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_scan_prepare.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/tablet_scanner.cpp
  be/src/storage/column_predicate_rewriter.cpp
  be/src/storage/column_predicate_rewriter.h
  be/src/storage/rowset/array_column_iterator.cpp
  be/src/storage/rowset/array_column_iterator.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/map_column_iterator.cpp
  be/src/storage/rowset/map_column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/struct_column_iterator.cpp
  be/src/storage/rowset/struct_column_iterator.h
  be/src/types/logical_type.h
  fe/fe-core/src/main/java/com/starrocks/analysis/CollectionElementExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SubfieldExpr.java
Labels: 3.1

#26821 Update README.md
  README.md
Labels: title needs [type]

#26815 [BugFix] Fix Routine load parameters persistence issue
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
Labels: 3.1

#26819 [BugFix] Fix the mem statistics bug of ordinal index
  be/src/storage/rowset/ordinal_page_index.h
Labels: 2.5, 2.4, 3.0, 3.1

#26823 [Doc] add links in decimal
  docs/sql-reference/sql-statements/data-types/DECIMAL.md
Labels: 3.1

#25498 [Doc] add query hints
  docs/administration/Query_planning.md
  docs/assets/8-9.png
Labels: documentation

#26813 [BugFix] Fix & Optimizing Partition Scheduling
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 3.0, 3.1

#26855 [Tool] Fix security issues (backport #26774)
  .github/workflows/ci-merged.yml
  .github/workflows/ci-pipeline-branch.yml
Labels: automerge

#26758 [Enhancement] Support week/day_of_week function for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
Labels: 3.0, 3.1

#26852 [Doc] add spark connector
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/loading/Spark-connector-starrocks.md
  docs/loading/SparkLoad.md
Labels: documentation

#26867 [BugFix][Cherry-Pick] Fix & Optimizing Partition Scheduling
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#26870 [BugFix][Cherry-Pick] Fix & Optimizing Partition Scheduling
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#26892 [Doc] update bitmap description and figure
  docs/assets/6.1.2-2-old.png
  docs/assets/6.1.2-2.png
  docs/using_starrocks/Using_bitmap.md
Labels: 2.5, 3.0, 3.1

#26905 [Enhancement] Upgrade hadoop to 3.3.6 due to security
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 2.5, 3.0, 3.1

#26901 [BugFix] fix wrong sql_aggregate_functions info
  be/src/exec/aggregator.cpp
Labels: 3.0, 3.1

#26875 [Enhancement] Increase RPC timeout of lake service
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
Labels: 3.0, 3.1

#26788 [BugFix] skip update replica version which is not been commited
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TabletCommitInfo.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: 2.5, 3.0, 3.1

#26760 [BugFix] Fix date type as partition value when inserting iceberg table
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.cpp
  be/src/exec/pipeline/sink/iceberg_table_sink_operator.h
  be/test/CMakeLists.txt
  be/test/exec/iceberg/iceberg_table_sink_operator_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
Labels: 3.1

#26874 [BugFix] Fix the mem leak of AvroScanner
  be/src/exec/avro_scanner.cpp
Labels: 2.5, 3.0, 3.1

#26914 [Doc] fix bugs in pics
  docs/assets/3.1-2.png
  docs/assets/starrocks_operator.png
Labels: documentation

#26750 [Enhancement] Add more bvars
  be/src/common/config.h
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/vacuum.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/util/threadpool.h
Labels: 3.1

#26681 [BugFix] do not support create list partition cloud table
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
Labels: 3.0, 3.1

#26781 [BugFix] fix precision loss issue when importing datetime type data
  fe/fe-core/src/main/java/com/starrocks/analysis/DateLiteral.java
  test/sql/test_datetime/R/test_datetime
  test/sql/test_datetime/T/test_datetime
Labels: 3.0, 3.1

#26945 [BugFix] Fix desc storage volume privilege error msg
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerVisitor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.1

#26849 [Enhancement] Add load flush statistic log for cloud native tablet
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/memtable.cpp
Labels: 3.0, 3.1

#26916 [Enhancement] support some binary/date function for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/ComplexFunctionCallTransformer.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: 3.0, 3.1

#26946 [Doc] Update table data in Using_bitmap.md
  docs/using_starrocks/Using_bitmap.md
Labels: 2.5, 3.0, 3.1

#26858 [BugFix] Fix error of storage volume name in grants table
  fe/fe-core/src/main/java/com/starrocks/privilege/StorageVolumePEntryObject.java
  test/conf/sr.conf
  test/sql/test_storage_volume/R/grant
  test/sql/test_storage_volume/T/grant
Labels: 3.1

#26757 [BugFix] Optional append_default need levels otherwise result is wrong
  be/src/formats/parquet/stored_column_reader.cpp
  be/src/formats/parquet/stored_column_reader.h
  be/test/exec/test_data/parquet_scanner/optional_column_levels.parq
  test/sql/test_external_file/R/test_parquet_optional_column_levels
  test/sql/test_external_file/T/test_parquet_optional_column_levels
Labels: 2.5, 3.0, 3.1

#26954 [Cherry-pick][Branch-3.0][Feature] Support function last_day (#23348)
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  be/src/types/date_value.cpp
  be/src/types/date_value.h
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/last_day.md
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: title needs [type]

#26890 [BugFix] Fixed the problem of inaccurate memory statistics with auto spill turned on
  be/src/exec/spill/executor.h
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/spiller.h
  be/src/runtime/current_thread.h
Labels: 3.0, 3.1

#26943 [BugFix] improve error message when creating table in system database
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 2.5, 3.0, 3.1

#26937 [BugFix] const_null_column has lost type use unfold_const_column to expand it
  be/src/exprs/condition_expr.cpp
  be/test/exprs/condition_expr_test.cpp
  test/sql/test_function/R/test_conditional_fn
  test/sql/test_function/T/test_conditional_fn
Labels: 3.1

#26983 [Doc] 3.1 Alter table comment and add show create database
  docs/TOC.md
  docs/release_notes/release-3.1.md
  docs/sql-reference/sql-statements/Utility/DESCRIBE.md
  docs/sql-reference/sql-statements/data-definition/ALTER DATABASE.md
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE DATABASE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-definition/DROP DATABASE.md
  docs/sql-reference/sql-statements/data-definition/DROP TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW ALTER.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE DATABASE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW DATABASES.md
Labels: 3.1

#26944 [BugFix] check null as default catalog
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
Labels: 2.5, 3.1

#26913 [BugFix] Fix insert empty result as canceled load
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  test/sql/test_insert_empty/R/test_insert
  test/sql/test_insert_empty/T/test_insert
Labels: 2.5, 3.0, 3.1

#26986 [Enhancement] Refine trace log and delete txn log in background
  be/src/common/config.h
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
Labels: 3.1

#27025 [BugFix] Avoid holding db locks for a long time due to refresh table failure
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
Labels: 2.5, 3.0, 3.1

#26877 [BugFix] Fix show grants for resource group priv obj
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourceGroupPEntryObject.java
Labels: 3.0, 3.1
