Repository StarRocks/starrocks, pull requests merged in 2023-02, with the labels that each got.

#17140 [UT] Fix error ut
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q21.sql
Labels: be-build

#17151 [BugFix] fix element_memory_usage of ArrayColumn
  be/src/column/array_column.cpp
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#17073 [Enhancement] enhance state change executor test
  fe/fe-core/src/main/java/com/starrocks/ha/StateChangeExecutor.java
  fe/fe-core/src/test/java/com/starrocks/ha/StateChangeExecutorTest.java
Labels: Approved, be-build

#17129 [Enhancement] Upgrade hudi version and remove useless packages
  fe/fe-core/pom.xml
  fe/pom.xml
  java-extensions/hudi-reader/pom.xml
Labels: Approved, be-build

#17139 [Doc] Add 2.0 Upgrade tip
  docs/administration/Cluster_administration.md
Labels: documentation, Approved, be-build, 2.5

#17026 [Tool] update dockerfile
  docker/dockerfiles/buildx/Dockerfile_be_ubuntu
  docker/dockerfiles/buildx/Dockerfile_fe_ubuntu
Labels: Approved, be-build

#17164 [Tool] port docker related scripts and dockerfile from 'main' branch
  docker/bin/be_entrypoint.sh
  docker/bin/be_prestop.sh
  docker/bin/build-be-ubuntu.sh
  docker/bin/build-dev-toolchain-ubuntu.sh
  docker/bin/build-dev-ubuntu.sh
  docker/bin/build-fe-ubuntu.sh
  docker/bin/build_all_in_one.sh
  docker/bin/cn_entrypoint.sh
  docker/bin/cn_prestop.sh
  docker/bin/dockerignore
  docker/bin/fe_entrypoint.sh
  docker/bin/fe_prestop.sh
  docker/dockerfiles/Dockerfile-be-ubuntu
  docker/dockerfiles/Dockerfile-fe-ubuntu
  docker/dockerfiles/Dockerfile_all_in_one
  docker/dockerfiles/Dockerfile_be_centos
  docker/dockerfiles/Dockerfile_be_ubuntu_arm64_v8
  docker/dockerfiles/Dockerfile_cn_centos
  docker/dockerfiles/Dockerfile_fe_alpine
  docker/dockerfiles/Dockerfile_fe_ubuntu_arm64_v8
  docker/dockerfiles/buildx/Dockerfile_be_ubuntu
  docker/dockerfiles/buildx/Dockerfile_fe_ubuntu
Labels: be-build

#17163 [BugFix] Fix/Unify batch create week partition logical
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiRangePartitionDesc.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DynamicPartitionUtilTest.java
Labels: be-build, 2.5, 2.4, 2.3

#17178 [BugFix] Fix/Unify batch create week partition logical
  fe/fe-core/src/main/java/com/starrocks/analysis/MultiRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DynamicPartitionUtilTest.java
Labels: be-build

#17130 [BugFix] Fix local shuffle
  be/src/exec/aggregate/aggregate_blocking_node.cpp
  be/src/exec/aggregate/aggregate_streaming_node.cpp
  be/src/exec/aggregate/distinct_blocking_node.cpp
  be/src/exec/aggregate/distinct_streaming_node.cpp
  be/src/exec/analytic_node.cpp
  be/src/exec/except_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/intersect_node.cpp
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
  be/src/exec/pipeline/source_operator.h
  be/src/exec/topn_node.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: Approved, be-build, 2.5, 2.4, 2.3

#16708 [Enhancement] remove the lock when acquire compress context
  be/src/util/compression/compression_context_pool.h
Labels: Approved, be-build

#16537 [Feature] Add local tablet reader and rpc interface
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/service/service_be/internal_service.cpp
  be/src/service/service_be/internal_service.h
  be/src/storage/CMakeLists.txt
  be/src/storage/local_tablet_reader.cpp
  be/src/storage/local_tablet_reader.h
  be/src/storage/table_reader.cpp
  be/src/storage/table_reader.h
  be/test/storage/table_reader_test.cpp
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
Labels: Approved, be-build

#17198 [UT] fix mv rewrite ut
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, be-build

#17186 [BugFix] Add check logical for show data
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
Labels: Approved, be-build

#17202 [Doc] Add the missing doc for split string function
  docs/sql-reference/sql-functions/string-functions/split.md
Labels: documentation, be-build

#17152 [Enhancement] make `backend not found` error message accurate
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorMonitor.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: be-build

#17158 [Doc]correctify toc of routine load
  docs/TOC.md
Labels: documentation, Approved, be-build

#17076 [BugFix] fix pk lake table partial update multi segment
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/rowset_update_state.cpp
  be/test/CMakeLists.txt
  be/test/storage/lake/partial_update_test.cpp
Labels: Approved, be-build

#17122 [Refactor] Refactor streaming load max mb
  be/src/common/config.h
Labels: Approved, be-build

#17090 [BugFix] Update cachelib library to adapt the cpp abi compatibility with starrocks
  thirdparty/vars.sh
Labels: be-build

#17194 [Enhancement] add more info in logging for the cases of exec plan fragment failed and clone
  be/src/storage/task/engine_clone_task.cpp
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: Approved, be-build

#17192 [BugFix] fix min-readable-version lost during replay
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/persist/ReplicaPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: Approved, be-build, 2.5, 2.4, 2.3

#17167 [BugFix] Fix auth upgrade failure when object not found
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/privilege/FunctionPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/MaterializedViewPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/UserPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ViewPEntryObject.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
Labels: be-build

#17205 [UT] fix mv rewrite ut (#17198)
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: be-build

#17184 [BugFix] fix Column::element_memory_usage
  be/src/column/array_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.h
  be/src/column/map_column.cpp
  be/test/column/array_column_test.cpp
  be/test/column/binary_column_test.cpp
  be/test/column/const_column_test.cpp
  be/test/column/map_column_test.cpp
  be/test/column/struct_column_test.cpp
  be/test/exec/query_cache/query_cache_test.cpp
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#17232 [Doc] delete an outdated note from JSON.md
  docs/sql-reference/sql-statements/data-types/JSON.md
Labels: documentation, Approved, be-build

#17223 [Enhancement] Throw compile error when _GLIBCXX_USE_CXX11_ABI=0
  be/src/service/starrocks_main.cpp
Labels: Approved, be-build

#17237 [BugFix] fix refresh hive metadata
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CacheUpdateProcessor.java
Labels: Approved, be-build, 2.5

#17211 [BugFix] Fix password null after auth upgrade
  fe/fe-core/src/main/java/com/starrocks/analysis/Delimiter.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationManager.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UserAuthenticationInfo.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ParseUtil.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
Labels: Approved, be-build

#17246 [UT] rm unstable ut BalanceTest
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BalanceTest.java
Labels: Approved, be-build

#17241 [Enhancement] Upgrade ivy to 2.5.1 due to CVE-2022-37865
  fe/fe-core/pom.xml
Labels: be-build

#17174 [Feature] lake table support multi worker schema change
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
Labels: Approved, be-build

#17259 [Doc] update replicated_storage
  docs/administration/Configuration.md
  docs/data_source/Block_cache.md
  docs/release_notes/release-2.5.md
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
Labels: documentation, Approved, be-build

#17249 [Doc] add-2.3.8-rn
  docs/release_notes/release-2.3.md
Labels: documentation, Approved, be-build

#17155 [Feature] RBAC support show grants/show role/show users
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/CatalogPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/FunctionPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/GlobalFunctionPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollection.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourceGroupPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourcePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/UserPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokeRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantPrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokeRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowGrantsStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowRolesStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/GrantRevokeRoleStmtTest.java
Labels: Approved, be-build

#17196 [Enhancement] Execute immediately after the dynamic partition table is created
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DynamicPartitionTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/resources/sql/query_dump/select_sbuquery_with_multi_join.json
Labels: Approved, be-build

#17268 [Doc] Adjust layout of ALTER TABLE.md according to chinese
  docs/sql-reference/sql-statements/data-definition/ALTER TABLE.md
Labels: documentation, Approved, be-build

#17234 [BugFix] Support show full fields syntax.
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: Approved, be-build, 2.5, 2.4, 2.3

#17220 [Feature]Support ignore nulls for lead/lag window function
  be/src/column/column_helper.cpp
  be/src/column/column_helper.h
  be/src/exec/analytor.cpp
  be/src/exprs/agg/factory/aggregate_factory.hpp
  be/src/exprs/agg/factory/aggregate_resolver_window.cpp
  be/src/exprs/agg/window.h
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: be-build

#17215 [Enhancement] Fix build warnings with clang14
  be/src/column/CMakeLists.txt
  be/src/column/chunk_extra_data.cpp
  be/src/column/chunk_extra_data.h
  be/src/column/stream_chunk.cpp
  be/src/column/stream_chunk.h
  be/src/exec/pipeline/sort/partition_sort_sink_operator.h
  be/src/exec/topn_node.cpp
  be/src/runtime/data_stream_recvr.cpp
  be/src/runtime/sorted_chunks_merger.cpp
  be/src/runtime/sorted_chunks_merger.h
  be/src/storage/lake/update_manager.cpp
Labels: Approved, be-build

#17257 [BugFix] Lost connection after query
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/IMTCreator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
Labels: Approved, be-build

#17279 [Refactor] Revise error message
  fe/fe-core/src/main/java/com/starrocks/alter/Alter.java
Labels: Approved, be-build

#17287 [Feature] starmgr version upgrade to v0.2.2
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
Labels: Approved, be-build

#17285 [Enhancement][Cherry-pick] Support show full fields syntax
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: automerge, be-build

#17292 [Feature] Support recursive directory filetable
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
Labels: Approved, be-build

#17291 [Enhancement] Support show full fields syntax
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: be-build

#17288 [Doc] Reset root Password
  docs/administration/User_privilege.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#17227 [BugFix] unify Operator hashCode method
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSetOperation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalWindowOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/OperatorEqualsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: Approved, be-build

#17214 [Refactor] Specify the app class loader of hudi scanner explicitly
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScannerFactory.java
  java-extensions/java-utils/src/main/java/com/starrocks/utils/loader/ChildFirstClassLoader.java
Labels: be-build

#17210 [Refactor] Specify the app class loader of hudi scanner explicitly
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScannerFactory.java
  java-extensions/java-utils/src/main/java/com/starrocks/utils/loader/ChildFirstClassLoader.java
Labels: be-build

#17101 [Refactor] Wait for apply finish when exec primary key publish version
  be/src/agent/agent_server.cpp
  be/src/agent/publish_version.cpp
  be/src/agent/publish_version.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/common/config.h
  be/src/service/internal_service.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/src/storage/txn_manager.cpp
  be/src/storage/txn_manager.h
  be/test/storage/persistent_index_test.cpp
  be/test/storage/publish_version_task_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset_update_state_test.cpp
  be/test/storage/table_reader_test.cpp
Labels: Approved, be-build

#17044 [Refactor] Refactor error msg when body exceed max size during stream load
  be/src/http/action/stream_load.cpp
  be/src/http/action/transaction_stream_load.cpp
Labels: Approved, be-build

#17093 [Refactor] Refactor parallel stream load error msg
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
Labels: Approved, be-build

#17209 [Enhancement] disable AVX512 by default
  be/CMakeLists.txt
  build.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
Labels: be-build

#16876 [Feature] lake pk table support dup publish, multi cluster and add memory tracker
  be/src/runtime/exec_env.cpp
  be/src/storage/del_vector.cpp
  be/src/storage/del_vector.h
  be/src/storage/lake/gc.cpp
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/lake_primary_index.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/tablet_metadata.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/util/dynamic_cache.h
  be/test/CMakeLists.txt
  be/test/storage/lake/gc_test.cpp
  be/test/storage/lake/meta_file_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
  be/test/storage/lake/tablet_writer_test.cpp
  gensrc/proto/lake_types.proto
Labels: Approved, be-build

#17077 [Enhancement] Support OuterJoin in MV Rewrite
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateAggregateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/OnlyScanRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: Approved, sig/materialized view, be-build

#17260 [BugFix] Fix invalid compaction when tablet not in running state
  be/src/storage/default_compaction_policy.cpp
  be/src/storage/size_tiered_compaction_policy.cpp
  be/test/storage/default_compaction_policy_test.cpp
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: Approved, be-build, 2.5

#17311 [BugFix] Fix auth upgrade failure on follower when replaying log
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: Approved, be-build

#17321 [BugFix] strict the dictmapping check for rewrite scalarOperator(backport #17318)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DictMappingRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: automerge, be-build

#15988 [Enhancement] optimize json parser
  be/src/column/chunk.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
Labels: Approved, be-build

#17327 [Doc] update query cache
  docs/using_starrocks/query_cache.md
Labels: documentation, Approved, be-build

#17302 [BugFix] when forward query to leader fe forward the current catalog in connect context
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: Approved, be-build, 2.5, 2.4, 2.3

#17336 [Enhancement] enable enable_experimental_mv by default
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: Approved, be-build

#17213 [BugFix] MV rewrite with cast expression
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: Approved, sig/materialized view, be-build

#17308 [BugFix] unify Operator equal method (backport #17199)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalSetOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalWindowOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalDeltaLakeScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalEsScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalFileScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHiveScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHudiScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalIcebergScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMergeJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMetaScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSetOperation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalWindowOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/OperatorEqualsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: automerge, be-build

#17309 [BugFix] fix Column::element_memory_usage (backport #17184)
  be/src/column/array_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.h
  be/test/column/array_column_test.cpp
  be/test/column/binary_column_test.cpp
  be/test/column/const_column_test.cpp
Labels: automerge, be-build

#17310 [BugFix] fix Column::element_memory_usage (backport #17184)
  be/src/column/array_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/fixed_length_column_base.h
  be/test/column/array_column_test.cpp
  be/test/column/binary_column_test.cpp
  be/test/column/const_column_test.cpp
Labels: automerge, be-build

#17326 [Refactor]Unify representation of directory recursive traverse property
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorInternalMgr.java
Labels: Approved, be-build

#17315 [Refactor] Fix min_cumulative_compaction_failure_interval_sec misspell
  be/src/common/config.h
  be/src/storage/compaction_manager.cpp
  be/src/storage/tablet_manager.cpp
  docs/administration/Configuration.md
Labels: Approved, be-build

#17304 [BugFix] Fix unused DCHECK in DictMappingExpr
  be/src/exprs/dictmapping_expr.cpp
  be/src/exprs/dictmapping_expr.h
  be/src/storage/column_predicate_rewriter.cpp
  be/src/storage/rowset/segment_iterator.cpp
Labels: Approved, be-build, 2.5, 2.4

#17295 [BugFix] Fix set transaction miss session/global var type keyword
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SetTransaction.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: Approved, be-build, 2.5

#17356 [Doc] Fix docs for left and right
  docs/sql-reference/sql-functions/string-functions/left.md
  docs/sql-reference/sql-functions/string-functions/right.md
  docs/sql-reference/sql-functions/string-functions/strleft.md
  docs/sql-reference/sql-functions/string-functions/strright.md
Labels: documentation, be-build

#17289 [BugFix] Fix stream cascade merge may got a wrong result
  be/src/exec/sorting/merge_cascade.cpp
  be/src/testutil/exprs_test_helper.h
  be/test/CMakeLists.txt
  be/test/runtime/merge_cascade_test.cpp
Labels: Approved, be-build, 2.5, 2.4, 2.3

#17269 [BugFix] Fix partition prune null predicate error
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PartitionPredicatePrune.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: Approved, be-build

#17364 [Refactor] Enable OAUTHBEARER in kafka
  thirdparty/build-thirdparty.sh
Labels: be-build

#17341 [BugFix] Fix the problem of slow `show frontends` when the Kubernetes pod restart
  fe/fe-core/src/main/java/com/starrocks/ha/BDBHA.java
  fe/fe-core/src/main/java/com/starrocks/ha/HAProtocol.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/ha/BDBHATest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: Approved, be-build, 2.5, 2.4

#17368 [Refactor] Bump librdkafka to version 2.0.2
  thirdparty/vars.sh
Labels: be-build

#17201 [BugFix]support cross database udf in view
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
Labels: be-build

#17370 [Refactor]Cherry-pick]Support recursive directory filetable #17292 and Unify representation #17326
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorInternalMgr.java
Labels: automerge, be-build

#17369 [Refactor] Mask secret fields in RoutineLoad
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
Labels: be-build

#17294 [Doc] correctify description for duplicate key table
  docs/table_design/Data_model.md
Labels: documentation, Approved, be-build

#17132 [Doc] Add 2.5 BE config items
  docs/administration/Configuration.md
Labels: documentation, Approved, be-build, 2.5

#17329 [Doc] Separate MV docs
  docs/TOC.md
  docs/using_starrocks/Materialized_view-single_table.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved, be-build, 2.5

#17377 [BugFix][Branch_2.3] when forward query to leader fe forward the current catalog in connect context (backport #17302)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge, be-build

#17378 [BugFix][Branch-2.4] when forward query to leader fe forward the current catalog in connect context (backport #17302)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge, be-build

#17379 [BugFix][Branch-2.5]when forward query to leader fe forward the current catalog in connect context (backport #17302)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: automerge, be-build

#16595 [BugFix] Use sort key to process predicates to get scan range while sort key is assigned.
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/pipeline/scan/olap_scan_context.cpp
  be/src/storage/tablet_reader.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: Approved, be-build, 2.5

#17254 [Tool] Make FE UT log level be configurable
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/common/log4j2.xml
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedFrontend.java
  fe/fe-core/src/test/resources/log4j2.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
Labels: be-build

#17222 [Refactor] Use thirdparty jar packages as the source of broker dependency
  fs_brokers/apache_hdfs_broker/build.sh
  thirdparty/build-thirdparty.sh
Labels: be-build

#17362 [Enhancement] avoid build slice cache in BinaryColumn
  be/src/column/binary_column.h
  be/src/exec/sorted_streaming_aggregator.cpp
  be/src/exec/sorting/merge_column.cpp
  be/src/exec/sorting/sort_column.cpp
  be/src/exec/sorting/sort_permute.cpp
  be/src/exprs/string_functions.cpp
Labels: Approved, be-build

#17180 [Enhancement] Array support decimalV3
  fe/fe-core/src/main/java/com/starrocks/catalog/ArrayType.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/ColumnTypeConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/analyzer/SimpleExpressionAnalyzer.java
Labels: Approved, be-build

#17406 [Doc] Rearrange Release notes
  docs/release_notes/release-2.4.md
Labels: documentation, Approved, be-build

#17394 [Doc] Update Query Rewrite Desc for 2.5.1
  docs/using_starrocks/Materialized_view.md
Labels: documentation, Approved, be-build, 2.5

#17405 [BugFix] strict the dictmapping check for rewrite scalarOperator (backport #17318)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/physical/DictMappingRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: automerge, be-build

#17299 [Feature] lake colocate table support schema change
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
Labels: Approved, be-build

#17306 [Feature] Support Grant/Revoke multi role statement in RBAC
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRevokeClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: Approved, be-build

#17412 [BugFix] Fix the problem that Librdkafka is not patched
  thirdparty/download-thirdparty.sh
  thirdparty/patches/librdkafka.patch
Labels: be-build, 2.5, 2.4, 2.3, 2.2

#17411 [BugFix] Fix the problem that Librdkafka is not patched
  thirdparty/download-thirdparty.sh
Labels: be-build

#17401 [Enhancement] make StateChangeExecutorTest more robust
  fe/fe-core/src/test/java/com/starrocks/ha/StateChangeExecutorTest.java
Labels: Approved, be-build

#17324 [Enhancement] Add standard unit of time check for batch build partition
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RangePartitionDesc.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
Labels: be-build

#17395 [Refactor] remove deprecated config hive_recursive_directory and recursive_dir_search_enabled
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorInternalMgr.java
Labels: Approved, be-build, 2.5

#17400 [BugFix] replace comment to a space when remove it (backport #17389)
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: automerge, be-build

#17396 [BugFix] unify Operator equal method (backport #17199)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalSetOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalWindowOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalEsScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHiveScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHudiScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMergeJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMetaScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSetOperation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalWindowOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/OperatorEqualsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: automerge, be-build

#17247 [Enhancement] Add config refresh daemon
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ConfigRefreshDaemon.java
  fe/fe-core/src/main/java/com/starrocks/common/ConfigRefreshListener.java
  fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: be-build

#17312 [Doc] update storage_medium in create table and ignore nulls of first/last-value
  docs/data_source/Block_cache.md
  docs/sql-reference/sql-functions/Window_function.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/table_design/Data_model.md
Labels: documentation, Approved, be-build, 2.5

#17393 [BugFix][cherry-pick] Complex shuffle join with aggregate bug (#16834)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
Labels: automerge, be-build

#17392 [BugFix][Cherry-pick] Complex shuffle join with aggregate bug (#16834)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: automerge, be-build

#17107 [BugFix] Adjust NULL_TYPE hack processing
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/connector/analyzer/SimpleExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
Labels: Approved, be-build

#17421 [BugFix] Fix the problem of slow show frontends when the Kubernetes pod restart
  fe/fe-core/src/main/java/com/starrocks/ha/BDBHA.java
  fe/fe-core/src/main/java/com/starrocks/ha/HAProtocol.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/test/java/com/starrocks/ha/BDBHATest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
Labels: be-build

#17323 [BugFix] Fix close stage may using null RuntimeState
  be/src/exprs/expr_context.cpp
  be/src/exprs/java_function_call_expr.cpp
  be/src/exprs/java_function_call_expr.h
Labels: be-build, 2.4, 2.3

#17413 [Doc] Add details for query rewrite
  docs/using_starrocks/Materialized_view.md
Labels: documentation, be-build, 2.5

#17258 [Enhancement] support count in meta scan
  be/src/storage/lake_meta_reader.cpp
  be/src/storage/lake_meta_reader.h
  be/src/storage/meta_reader.cpp
  be/src/storage/meta_reader.h
  be/src/storage/olap_meta_reader.cpp
  be/src/storage/olap_meta_reader.h
  be/test/CMakeLists.txt
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggToMetaScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
Labels: Approved, be-build

#17417 [BugFix] Fix location as reserved keyword bug
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
Labels: Approved, be-build, 2.5

#17418 [BugFix] Forbid modify bucket when alter colocate dynamic partition table.
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: Approved, be-build, 2.5, 2.4, 2.3, 2.2

#17449 [BugFix] use synchronized way to allocate table id
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorTableId.java
Labels: be-build

#17420 [BugFix] Fix query lake table throw NPE
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
Labels: Approved, be-build

#17432 [Refactor] Fix typo of error message
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
Labels: be-build

#17448 [Doc] 2.5.1 release notes and cbo
  docs/administration/Configuration.md
  docs/data_source/Block_cache.md
  docs/release_notes/release-2.5.md
  docs/using_starrocks/Cost_based_optimizer.md
Labels: documentation, Approved, be-build, 2.5

#17398 [BugFix] unify Operator equal method (backport #17199)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalSetOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalWindowOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalEsScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashAggregateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHiveScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHudiScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMergeJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalMetaScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalProjectOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalRepeatOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSetOperation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTableFunctionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalTopNOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalUnionOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalWindowOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/OperatorEqualsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: automerge, be-build

#17385 [BugFix] Fix compaction crash since lock conflict
  be/src/storage/compaction_task.h
Labels: Approved, be-build, 2.5

#16456 [Enhancement] Optimize ExportExportingSubTask Retry Strategy
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportExportingTask.java
Labels: Approved, be-build

#17471 [BugFix] typo in log of broker
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsService.java
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/HDFSBrokerServiceImpl.java
Labels: be-build, 2.5

#17216 [BugFix] empty_database_backup_success (#17217)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2.java
Labels: Approved, be-build

#17049 [Enhancement] Improve collect cte operator performance
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CTEUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderGreedy.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneTrueFilterRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectConstTest.java
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
Labels: Approved, be-build

#17433 [BugFix] Make the first parameter of date_trunc case-insensitive
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
Labels: Approved, be-build, 2.5

#17435 [Enhancement] Avoid potential checks leading to FE crash
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: Approved, be-build

#17434 [Enhancement] Compatible with only load once rowset avoid trigger compaction
  be/src/storage/size_tiered_compaction_policy.cpp
Labels: Approved, be-build

#16458 [Enhancement] remove snapshot phase for olap table export
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java
Labels: be-build

#17428 [Refactor] Add olap table sink commit tablet log
  be/src/exec/tablet_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
Labels: Approved, be-build

#17380 [Enhancement] Normailze compaction score avoid excessive score
  be/src/storage/size_tiered_compaction_policy.cpp
Labels: Approved, be-build

#17482 [Doc] add version info for 2.3
  docs/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md
  docs/sql-reference/sql-functions/bitmap-functions/bitmap_union_count.md
  docs/sql-reference/sql-functions/date-time-functions/time_slice.md
Labels: documentation, Approved, be-build, 2.5, 2.4, 2.3

#17390 [BugFix][cherry-pick] Fix partition prune null predicate error (#17269)
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PartitionPredicatePrune.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
Labels: automerge, be-build, 2.5, 2.4, 2.3, 2.2

#15619 [Enhancement] Remove db lock when planning olap table query
  fe/fe-core/src/main/java/com/starrocks/catalog/MvId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/http/StarRocksHttpTestCase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTest.java
Labels: Approved, be-build

#17488 [BugFix] Support for CHARACTER reserved words syntax
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: Approved, be-build, 2.5, 2.4

#17489 [Enhancement][Cherry-pick] Avoid potential checks leading to FE crash
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: automerge, be-build

#17505 [Enhancement] remove log4j 1.x dependency
  fe/fe-core/pom.xml
Labels: be-build

#17492 [Enhancement][Cherry-pick] Avoid potential checks leading to FE crash
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
Labels: automerge, be-build

#17337 [Refactor] Simplify and decouple the syntax of GrantPriv in RBAC
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthUpgrader.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/CatalogPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/FunctionPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/GlobalFunctionPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/MaterializedViewPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeManager.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourceGroupPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ResourcePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/UserPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ViewPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantPrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRevokePrivilegeObjects.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokePrivilegeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/AuthUpgraderTest.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: Approved, be-build

#17509 [Doc] add version info for 2.5
  docs/TOC.md
  docs/administration/Configuration.md
  docs/data_source/External_table.md
  docs/data_source/catalog/hudi_catalog.md
  docs/loading/Loading_intro.md
  docs/reference/System_variable.md
  docs/release_notes/release-2.5.md
  docs/sql-reference/sql-functions/Window_function.md
  docs/sql-reference/sql-functions/aggregate-functions/max_by.md
  docs/sql-reference/sql-functions/aggregate-functions/window_funnel.md
  docs/sql-reference/sql-functions/array-functions/array_filter.md
  docs/sql-reference/sql-functions/array-functions/array_map.md
  docs/sql-reference/sql-functions/array-functions/array_sortby.md
  docs/sql-reference/sql-functions/bitmap-functions/sub_bitmap.md
  docs/sql-reference/sql-functions/date-time-functions/time_slice.md
  docs/sql-reference/sql-functions/date-time-functions/week.md
  docs/sql-reference/sql-statements/account-management/EXECUTE AS.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/using_starrocks/query_cache.md
Labels: documentation, Approved, be-build

#17501 [BugFix] Fix lock scope
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
Labels: Approved, be-build

#17502 [Enhancement] remove log4j 1.x dependency in FE
  fe/fe-core/pom.xml
Labels: Approved, be-build

#17522 [Enhancement] disable Dynamic Partition in replay dump test
  fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: Approved, be-build

#17238 [Tool] Build and publish starrocks image in a hermetic multi-stage docker build pipeline.
  .dockerignore
  .github/workflows/release-docker-image.yml
  docker/dockerfiles/README.md
  docker/dockerfiles/artifact-ubuntu.Dockerfile
  docker/dockerfiles/be-ubuntu.Dockerfile
  docker/dockerfiles/dev-env-ubuntu.Dockerfile
  docker/dockerfiles/fe-ubuntu.Dockerfile
  docker/dockerfiles/img.png
Labels: be-build

#17325 [Feature] Add scan range assignment signature in debug mode
  fe/fe-core/src/main/java/com/starrocks/qe/BackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/FragmentScanRangeAssignment.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
Labels: be-build

#17481 [Refactor] Fix tscan for size_tiered_compaction_policy.cpp
  be/src/storage/size_tiered_compaction_policy.cpp
  be/src/storage/size_tiered_compaction_policy.h
Labels: Approved, be-build

#17500 [Doc] fix condition update doc
  docs/loading/Load_to_Primary_Key_tables.md
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation, Approved, be-build

#16729 [Feature] Generate binlog when publishing the ingestion
  be/src/common/config.h
  be/src/storage/CMakeLists.txt
  be/src/storage/binlog_builder.cpp
  be/src/storage/binlog_builder.h
  be/src/storage/binlog_file_reader.h
  be/src/storage/binlog_file_writer.cpp
  be/src/storage/binlog_file_writer.h
  be/src/storage/binlog_manager.cpp
  be/src/storage/binlog_manager.h
  be/src/storage/binlog_util.h
  be/src/storage/olap_common.cpp
  be/src/storage/olap_common.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/test/CMakeLists.txt
  be/test/storage/binlog_builder_test.cpp
  be/test/storage/binlog_file_test.cpp
  be/test/storage/binlog_manager_test.cpp
  be/test/storage/binlog_test_base.cpp
  be/test/storage/binlog_test_base.h
  be/test/storage/tablet_binlog_test.cpp
  gensrc/proto/binlog.proto
Labels: sig/materialized view, be-build

#17531 [Doc] Update loading intro &TOC in Branch 2.5
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/loading/Flink_cdc_load.md
  docs/loading/Loading_intro.md
Labels: documentation, be-build

#17532 [Doc] Update loading intro &TOC in Branch 2.4
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/loading/Flink_cdc_load.md
  docs/loading/Loading_intro.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation, be-build

#17542 [Doc] Update loading intro &TOC in Branch 2.3
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
  docs/loading/Flink_cdc_load.md
  docs/loading/Loading_intro.md
Labels: documentation, be-build
