Repository StarRocks/starrocks, pull requests merged in 2023-04, with the labels that each got.

#20455 [BugFix] fix wrong column ref in RewriteSumByAssociativeRule
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSumByAssociativeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: 3.0

#20349 [BugFix] Use the same verification rules for creating user names and resource groups
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupClassifier.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java
Labels: 3.0

#20757 [Bugfix] Fix compile error in AWS Graviton
  build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/aws-sdk-cpp-patch-1.9.179-LINK_LIBRARIES_ALL.patch
Labels: title needs [type]

#20805 [Enhancement][Cherry-Pick][Branch-2.5] Report error state tablet to FE and show error state tablet in statistic (#19517)
  be/src/storage/tablet_updates.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IncompleteTabletsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicasProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/StatisticProcDir.java
  gensrc/thrift/MasterService.thrift
Labels: automerge

#20828 [Doc] 3.0 privilege doc
  docs/TOC.md
  docs/administration/privilege_item.md
  docs/administration/privilege_overview.md
  docs/assets/assets/privilege-manage.jpg
  docs/assets/assets/privilege-object.jpg
  docs/assets/assets/privilege-role-inheri.jpg
  docs/assets/assets/privilege-role.jpg
  docs/assets/privilege-manage.jpg
  docs/assets/privilege-object.jpg
  docs/assets/privilege-role-inheri.jpg
  docs/assets/privilege-role.jpg
  docs/sql-reference/sql-functions/utility-functions/current_role.md
  docs/sql-reference/sql-statements/account-management/ALTER USER.md
  docs/sql-reference/sql-statements/account-management/CREATE USER.md
  docs/sql-reference/sql-statements/account-management/GRANT.md
  docs/sql-reference/sql-statements/account-management/REVOKE.md
  docs/sql-reference/sql-statements/account-management/SET DEFAULT ROLE.md
  docs/sql-reference/sql-statements/account-management/SET ROLE.md
  docs/sql-reference/sql-statements/account-management/SHOW GRANTS.md
  docs/sql-reference/sql-statements/account-management/SHOW USERS.md
Labels: documentation, title needs [type]

#20775 [BugFix] Make cloud native table shared scan same as olap table
  be/src/common/config.h
  be/src/connector/connector.h
  be/src/connector/lake_connector.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/scan_node.h
  be/test/CMakeLists.txt
  be/test/exec/connector_scan_node_test.cpp
Labels: 3.0

#20685 [Doc] Deploy faq and variable
  docs/faq/Deploy_faq.md
Labels: documentation

#20846 [Doc] update set catalog
  docs/sql-reference/sql-statements/data-definition/SET CATALOG.md
Labels: documentation

#20842 [Enhancement][Cherry-pick] Modify the ttl semantics to start counting from the current time
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
Labels: automerge

#20853 [Doc] Update Deploy_faq.md to 2.5
  docs/faq/Deploy_faq.md
Labels: documentation

#20843 [BugFix] fix librdkafka undefined symbol rd_kafka_sasl_scram*
  thirdparty/build-thirdparty.sh
Labels: 2.5, 3.0

#20595 [BugFix] Fix parsing errors in the fractional part of DATETIME type
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DateLiteralNewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/ConstantOperatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 3.0

#20585 [Enhancement] Support persistent the extra messages in TaskRunStatus for MVs
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatusChange.java
Labels: 3.0

#20863 [Doc] update Iceberg catalog
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#20852 [BugFix] Fix NPE when replicate not specify
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 3.0

#20862 [BugFix] backport #20843 to 2.5
  thirdparty/build-thirdparty.sh
Labels: automerge

#19418 [Enhancement] Improve disk balance speed when added multi backends
  fe/fe-core/src/main/java/com/starrocks/clone/BackendLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/clone/DiskAndTabletLoadReBalancerTest.java
Labels: be-build, 2.5, 3.0

#20874 [BugFix] Fix the problem that the result of lead/lag is unstable
  be/src/exprs/agg/window.h
Labels: 3.0

#20549 [BugFix]Fix jdbc catalog NPE issue when query have filter
  fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/JDBCScanNode.java
Labels: 3.0

#20885 [BugFix] Fix memory leak in LocalExchange
  be/src/exec/pipeline/exchange/local_exchange.h
Labels: 2.5, 2.4, 2.3, 3.0

#20881 [BugFix][Cherry-pick] Fix NPE when replicate not specify
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: automerge

#20902 bugfix in 3.0 docs
  docs/sql-reference/sql-statements/auto_increment.md
  docs/sql-reference/sql-statements/data-manipulation/UPDATE.md
  docs/table_design/automatic_partitioning.md
Labels: documentation, title needs [type]

#20906 [Doc] 3.0 release notes
  docs/TOC.md
  docs/release_notes/release-3.0.md
Labels: documentation

#20747 [Enhancement] Remove twice calls to listPartitionNames when refreshing
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
Labels: 2.5, 3.0

#20741 [BugFix] fix args type of 'getNextNotification' interface
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
Labels: 2.5, 3.0

#20182 [Enhancement] Use original expression as column name for MV
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: sig/materialized view, 3.0

#20924 [BugFix] Remove `--use-staros` parameter in artifacts build cmd
  docker/dockerfiles/artifacts/artifact.Dockerfile
Labels: 2.5

#20893 [Enhancement] Ignore thrift retry log
  be/src/agent/utils.cpp
Labels: 2.5, 3.0

#20901 [BugFix] Round up the tablet number when auto determine tablet distribution
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 3.0

#20926 [BugFix] Fix the failure to refresh when joining the internal and external tables of the materialized view
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: 2.5, 3.0

#20945 [Doc] update 3.0 doc - privilege
  docs/TOC.md
  docs/administration/User_privilege.md
  docs/administration/deploy_shared_data.md
  docs/administration/monitor_manage_big_queries.md
  docs/administration/privilege_item.md
  docs/release_notes/release-3.0.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/sql-reference/sql-functions/string-functions/replace.md
  docs/sql-reference/sql-statements/account-management/ALTER USER.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/SET DEFAULT ROLE.md
  docs/sql-reference/sql-statements/account-management/SET ROLE.md
  docs/sql-reference/sql-statements/account-management/SHOW AUTHENTICATION.md
  docs/sql-reference/sql-statements/account-management/SHOW ROLES.md
  docs/sql-reference/sql-statements/account-management/SHOW USERS.md
Labels: documentation, 3.0

#20942 [Doc] mod 3.0 docs
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
  docs/data_source/catalog/jdbc_catalog.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-statements/data-definition/CREATE EXTERNAL CATALOG.md
  docs/sql-reference/sql-statements/data-definition/SET CATALOG.md
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE CATALOG.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation

#20947 [BugFix][Cherry-pick] Fix the failure to refresh when joining the internal and external tables of the materialized view
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: automerge

#20950 [Doc] cherry-pick 3.0 updates
  docs/TOC.md
  docs/administration/User_privilege.md
  docs/administration/deploy_shared_data.md
  docs/administration/monitor_manage_big_queries.md
  docs/administration/privilege_item.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/sql-reference/sql-functions/string-functions/replace.md
  docs/sql-reference/sql-statements/account-management/ALTER USER.md
  docs/sql-reference/sql-statements/account-management/CREATE ROLE.md
  docs/sql-reference/sql-statements/account-management/SET DEFAULT ROLE.md
  docs/sql-reference/sql-statements/account-management/SET ROLE.md
  docs/sql-reference/sql-statements/account-management/SHOW AUTHENTICATION.md
  docs/sql-reference/sql-statements/account-management/SHOW ROLES.md
  docs/sql-reference/sql-statements/account-management/SHOW USERS.md
Labels: documentation, automerge

#20956 [Doc] add 2.5.4 rn
  docs/release_notes/release-2.5.md
Labels: documentation

#20955 [BugFix] Broadcast prober always different from builder (#20946)
  be/src/exec/pipeline/hashjoin/hash_joiner_factory.h
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/hash_joiner.h
Labels: 2.5, 2.4, 2.3

#20954 [BugFix] Broadcast prober always different from builder (#20946)
  be/src/exec/pipeline/hashjoin/hash_joiner_factory.h
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/hash_joiner.h
Labels: 2.5, 2.4, 2.3

#20962 Bugfix in 3.0 docs
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/table_design/automatic_partitioning.md
Labels: documentation, title needs [type]

#20975 bugfix in 3.0 docs
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
  docs/table_design/automatic_partitioning.md
Labels: documentation, title needs [type]

#20974 [Doc] mod return value types in function docs
  docs/sql-reference/sql-functions/crytographic-functions/base64_decode_binary.md
  docs/sql-reference/sql-functions/string-functions/hex_decode_binary.md
Labels: documentation

#20977 Modify http port of query dump instance
  docs/faq/Dump_query.md
Labels: documentation, title needs [type], 2.5, 2.4, 2.3, 3.0

#20964 [BugFix] fix query stuck issue due to prepare failure when enable_profile=true
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: 2.5, 3.0

#19441 [Enhancement] Support Iceberg ScanMetrics for hive/glue catalog
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergMetricsReporter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/glue/IcebergGlueCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergCustomCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: be-build

#20989 Add NUMBER and NUMERIC to nonReserved Keywords
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: title needs [type]

#20988 [BugFix] Fix DCHECK failed when run map's function
  be/src/exprs/anyval_util.cpp
Labels: 2.5, 3.0

#20995 [BugFix] Fix listTableStatus miss analyze query Statement
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstTraverser.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.0

#20991 [Enhancement] Print FE version into start log
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
Labels: 2.5, 2.4, 2.3, 3.0

#21016 [Doc] update docker related docs (#20623)
  docs/TOC.md
  docs/administration/deploy_with_docker.md
  docs/developers/build-starrocks/Build_in_docker.md
  docs/developers/build-starrocks/handbook.md
  docs/quick_start/Deploy.md
Labels: documentation

#20996 [BugFix][Cherry-pick] Forbid modify bucket when alter colocate dynamic partition table
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: automerge

#21000 [BugFix] Fix unsupported type reporting NPE
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 2.5, 2.4, 2.3, 3.0

#20978 [Doc] minor modification in data model
  docs/table_design/Data_model.md
Labels: documentation

#20990 [Doc] 3.0 reservedkw+defaultvalue+variable
  docs/administration/deploy_shared_data.md
  docs/reference/System_variable.md
  docs/release_notes/release-3.0.md
  docs/sql-reference/sql-functions/Window_function.md
  docs/sql-reference/sql-statements/keywords.md
Labels: documentation, title needs [type]

#21045 [Doc] keyword/window/default value to Branch 3.0
  docs/administration/deploy_shared_data.md
  docs/reference/System_variable.md
  docs/sql-reference/sql-functions/Window_function.md
  docs/sql-reference/sql-statements/keywords.md
Labels: documentation

#21021 [Doc] Add all-in-one docker deploy
  docs/quick_start/deploy_in_docker.md
Labels: documentation

#21048 [BugFix] Fix bug of Replay recover table throws NPE
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
Labels: 2.5, 2.4, 2.3, 3.0

#21046 [Doc] modify webpage rendering
  docs/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Labels: documentation

#21020 [Doc] Add all-in-one docker deploy
  docs/quick_start/deploy_in_docker.md
Labels: documentation

#21059 [Doc] fix vertical bars
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
  docs/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
Labels: documentation

#21058 [BugFix][Cherry-pick] Fix unsupported type reporting NPE
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: automerge

#21063 [BugFix][Cherry-pick] Fix unsupported type reporting NPE
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: automerge

#21064 Add NUMBER and NUMERIC to nonReserved Keywords
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: title needs [type]

#21066 [BugFix][Cherry-pick] Fix unsupported type reporting NPE
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: automerge

#20688 [Enhancement] Fix incomplete prune partition when mv with union-all
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessorTest.java
Labels: 3.0

#21068 Revert "[BugFix][Cherry-Pick][Branch-3.0] Fix not support GCS authentication in broker load and custom core-site.xml in GCS and Azure"
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/HdfsEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudType.java
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureCloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureStorageCloudCredential.java
  fe/fe-core/src/main/java/com/starrocks/credential/gcp/GCPCloudConfiguration.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileTableScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
Labels: title needs [type]

#21056 [BugFix][Cherry-Pick] fix args type of 'getNextNotification' interface
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
Labels: automerge

#21054 [BugFix][Cherry-Pick] fix args type of 'getNextNotification' interface
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
Labels: automerge

#20967 [Enhancement] Enhance FE/BE to output logs to console directly
  bin/start_backend.sh
  bin/start_fe.sh
  docker/dockerfiles/be/be_entrypoint.sh
  docker/dockerfiles/be/cn_entrypoint.sh
  docker/dockerfiles/fe/fe_entrypoint.sh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 2.5, 3.0

#21073 [BugFix] Fix PlainPasswordAuthenticationProvider miss plain password check result bug
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/test/java/com/starrocks/authentication/PlainPasswordAuthenticationProviderTest.java
Labels: 3.0

#21084 [Doc] add s3 compatible storage content to catalog
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#21093 [Doc] Remove config for tcmalloc on version 2.4+
  docs/administration/Configuration.md
Labels: documentation

#20564 [Enhancement] shallow copy cols from build table when building join chunk
  be/src/column/column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/exec/cross_join_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_joiner.cpp
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.tpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/test/exec/join_hash_map_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/NestLoopJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q19.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q19.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q20.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q21.sql
  fe/fe-core/src/test/resources/sql/tpchcost/q20.sql
Labels: 3.0

#21082 [Enhancement] add some staros config item
  be/src/common/config.h
  be/src/service/staros_worker.cpp
Labels: 3.0

#21091 [Doc] fix format in BROKER LOAD
  docs/sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
Labels: documentation

#20966 [BugFix] add check for join type mismatch in view delta mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: 2.5, 3.0

#20958 [BugFix] auto increment id lost when restart fe and get negative id when counter overflow (#20873)
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.0

#21099 [Doc] update 3.0 and Fix doc issues by albert
  docs/TOC.md
  docs/administration/User_privilege.md
  docs/administration/privilege_overview.md
  docs/administration/stargo.md
  docs/faq/Sql_faq.md
  docs/release_notes/release-3.0.md
  docs/sql-reference/sql-statements/account-management/SET_DEFAULT_ROLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE VIEW.md
Labels: documentation, title needs [type]

#21101 [Doc] cherrypick 3.0 and issue fixes
  docs/TOC.md
  docs/administration/User_privilege.md
  docs/administration/privilege_overview.md
  docs/administration/stargo.md
  docs/faq/Sql_faq.md
  docs/sql-reference/sql-statements/account-management/SET_DEFAULT_ROLE.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE VIEW.md
Labels: documentation

#21102 [Doc] cherrypick-property/faq/stargo to Branch 2.5
  docs/administration/stargo.md
  docs/faq/Sql_faq.md
  docs/sql-reference/sql-statements/data-definition/CREATE TABLE.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE VIEW.md
Labels: documentation

#21105 [Doc] cp Branch 2.4
  docs/administration/stargo.md
  docs/faq/Sql_faq.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE VIEW.md
Labels: documentation

#21108 [Doc] cp to Branch 2.3
  docs/administration/stargo.md
  docs/faq/Sql_faq.md
  docs/sql-reference/sql-statements/data-manipulation/SHOW CREATE VIEW.md
Labels: documentation

#21125 [Doc] Minor modification in data model
  docs/table_design/Data_model.md
Labels: documentation

#21126 [Doc] minor modification in data model
  docs/table_design/Data_model.md
Labels: documentation

#21128 [Doc] minor modification in data model
  docs/table_design/Data_model.md
Labels: documentation

#21119 [BugFix][Cherry-pick] add check for join type mismatch in view delta mv rewrite for 2.5 (#20966)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: automerge

#21118 [Enhancement][Minor] Print analysis exception for udf creation
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateFunctionStmt.java
Labels: documentation

#21022 [Doc] Add all-in-one docker deploy
  docs/quick_start/deploy_in_docker.md
Labels: documentation

#21140 [Doc] Add SHOW EXPORT
  docs/sql-reference/sql-statements/data-manipulation/SHOW EXPORT.md
Labels: documentation

#21138 [BugFix] to avoid early deleted shared_ptr in map_apply (backport #19120)
  be/src/exprs/array_map_expr.cpp
  be/src/exprs/map_apply_expr.cpp
Labels: automerge

#21144 [Doc] Add SHOW EXPORT in Branch 3.0
  docs/sql-reference/sql-statements/data-manipulation/SHOW EXPORT.md
Labels: documentation

#21142 [Doc]add 2.2.13 rn
  docs/release_notes/release-2.2.md
Labels: documentation

#20703 [Enhancement] remove delete restriction on the auto-increment table(#20702)
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/memtable.cpp
  be/src/storage/memtable.h
  be/src/storage/rowset/rowset_writer_context.h
  be/src/storage/rowset_update_state.cpp
  be/src/storage/rowset_update_state.h
  be/src/storage/tablet_updates.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  gensrc/proto/internal_service.proto
  gensrc/thrift/DataSinks.thrift
Labels: 3.0

#20417 [Enhancement] optimize refresh external connector table in background
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CacheUpdateProcessor.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastoreConf.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/ConnectorTableMetadataProcessor.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnectorInternalMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/IHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/Partition.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiConnectorInternalMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveConnectorTest.java
Labels: 2.5, 3.0

#21150 [Enhancement] Enhance FE/BE to output logs to console directly (#20967)
  bin/start_backend.sh
  bin/start_fe.sh
  docker/dockerfiles/be/be_entrypoint.sh
  docker/dockerfiles/be/cn_entrypoint.sh
  docker/dockerfiles/fe/fe_entrypoint.sh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.0

#21149 [Enhancement] Enhance FE/BE to output logs to console directly (#20967)
  bin/start_backend.sh
  bin/start_fe.sh
  docker/dockerfiles/be/be_entrypoint.sh
  docker/dockerfiles/be/cn_entrypoint.sh
  docker/dockerfiles/fe/fe_entrypoint.sh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 2.5

#20590 [BugFix] Fix disk space occupation problems of multiple replicas
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 2.5, 2.4, 2.3, 3.0

#21161 [Enhancement] Use new log4j LogManager
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/AWSCatalogMetastoreClient.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/converters/CatalogToHiveConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/AWSGlueMetastoreCacheDecorator.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/GlueMetastoreClientDelegate.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/BatchCreatePartitionsHelper.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/BatchDeletePartitionsHelper.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/ExpressionHelper.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/MetricsAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeBackupJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownAggregateCollector.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/pom.xml
Labels: 3.0

#21187 [BugFix][Cherry-pick][Branch-2.3] Fix timeout when getting kafka partition offset
  be/src/runtime/routine_load/data_consumer.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/service/internal_service.cpp
Labels: automerge

#21184 [BugFix][Cherry-pick][Branch-2.4] Fix timeout when getting kafka partition offset
  be/src/runtime/routine_load/data_consumer.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/service/internal_service.cpp
Labels: automerge

#21157 [Enhancement] Remove unsed Jindo sdk in BE
  build.sh
Labels: 3.0

#21148 [Enhancement] Add iceberg partition prune info when executing explain verbose query
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
Labels: 2.5, 3.0

#21176 [Enhancement] Upgrade jackson Due to CVE-2022-42003
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
  java-extensions/hudi-reader/pom.xml
  java-extensions/udf-examples/pom.xml
Labels: 2.5, 3.0

#21180 [BugFix][Cherry-pick][Branch-3.0] Fix timeout when getting kafka partition offset
  be/src/runtime/routine_load/data_consumer.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/service/internal_service.cpp
Labels: automerge

#21181 [BugFix][Cherry-pick][Branch-2.5] Fix timeout when getting kafka partition offset
  be/src/runtime/routine_load/data_consumer.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/service/internal_service.cpp
Labels: automerge

#21198 [Enhancement] shallow copy cols from build table when building join chunk (backport #20564)
  be/src/column/column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/join_hash_map.tpp
Labels: automerge

#21199 [Enhancement] shallow copy cols from build table when building join chunk (backport #20564)
  be/src/column/column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/join_hash_map.tpp
Labels: automerge

#21195 [Enhancement] shallow copy cols from build table when building join chunk (backport #20564)
  be/src/column/column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/vectorized/cross_join_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/hash_joiner.cpp
  be/src/exec/vectorized/join_hash_map.tpp
Labels: automerge

#21209 [BugFix][Cherry-Pick][Branch-3.0] Avoid BE crash when CSV reader try to read complex types
  be/src/column/chunk.cpp
  be/src/column/chunk.h
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/hdfs_scanner_text.h
  be/src/formats/CMakeLists.txt
  be/src/formats/csv/array_converter.cpp
  be/src/formats/csv/converter.cpp
  be/src/formats/csv/converter.h
  be/src/formats/csv/default_value_converter.cpp
  be/src/formats/csv/default_value_converter.h
  be/test/CMakeLists.txt
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/test_data/csv_scanner/array_struct_map.csv
  be/test/exec/test_data/csv_scanner/newly_add_column.csv
  be/test/formats/csv/default_value_converter_test.cpp
Labels: automerge

#21217 [Doc] Update 3.0 shared data
  docs/administration/deploy_shared_data.md
Labels: documentation, 3.0

#21151 [BugFix] Fix thread running out for avro import
  be/src/runtime/routine_load/data_consumer_group.cpp
Labels: 3.0

#21224 [BugFix] Ensure persisting tablet meta after schemachange
  be/src/storage/tablet_updates.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#20638 [Doc] Update DATE.md
  docs/sql-reference/sql-statements/data-types/DATE.md
Labels: documentation, 2.5, 2.4, 2.3, 3.0

#21227 [Enhancement] Get stacktrace by function name
  be/src/script/script.cpp
  be/src/util/stack_util.cpp
  be/src/util/stack_util.h
Labels: 2.5, 2.4, 2.3, 3.0

#21169 [BugFix][Cherry-pick][Branch-2.5] Fix disk space occupation problems of multiple replicas
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#21170 [BugFix][Cherry-pick][Branch-2.4] Fix disk space occupation problems of multiple replicas
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#21171 [BugFix][Cherry-pick][Branch-2.3] Fix disk space occupation problems of multiple replicas
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: automerge

#21134 [BugFix] consider null values when remove scan predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/FurtherPartitionPruneTest.java
Labels: 2.5, 2.4, 3.0

#21267 [Doc] fix format
  docs/data_source/catalog/deltalake_catalog.md
  docs/data_source/catalog/hive_catalog.md
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#21246 [Enhancement] Put all the errors of the automatic partition outside
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.0

#21177 [BugFix] exclude cn when allow create cloudnative table
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
Labels: 3.0

#21277 [BugFix] Fix the problem of chunks partitioner not handling nullable column well
  be/src/exec/partition/chunks_partitioner.h
Labels: 2.5, 2.4, 2.3, 3.0

#21260 [BugFix] JDBC Catalog use 0 as tableid lead to column parser error
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorTableId.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/iceberg/hive/IcebergGlueCatalog.java
  fe/fe-core/src/main/java/org/apache/iceberg/hive/IcebergHiveCatalog.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.0

#20027 [Enhancement] Add local exchange for nest loop join's left child
  be/src/exec/cross_join_node.cpp
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exec/pipeline/exchange/local_exchange.h
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
Labels: 3.0

#21265 [Enhancement] Improve refresh external table performance
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
Labels: 2.5, 3.0

#21296 [BugFix][Cherry-Pick][Branch-2.5] Avoid BE crash when CSV reader try to read complex types
  be/src/formats/csv/converter.cpp
Labels: automerge

#21323 Revert "[BugFix] Fix wrong state of 'isExecuteInOneTablet' when it comes to agg or analytic (backport #19690)"
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/BinderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/StructTypePlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q15-1.sql
Labels: automerge, title needs [type]

#21320 [Feature] support SASL_SCRAM for librdkafka (branch-3.0) (backport #21285)
  thirdparty/build-thirdparty.sh
Labels: automerge

#21279 [Enhancement]Do not check cluster capacity when in shared_data runMode
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 3.0

#21330 [BugFix] Fix mv ttl task invalid when restart Fe
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
Labels: 2.5, 3.0

#21327 [Doc] update iceberg & hudi catalog docs
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#21344 [Doc] update iceberg & hudi catalog docs in Branch 3.0
  docs/data_source/catalog/hudi_catalog.md
  docs/data_source/catalog/iceberg_catalog.md
Labels: documentation

#21340 [Doc] Update mv switch parameter value
  docs/administration/Configuration.md
  docs/release_notes/release-2.5.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, 3.0

#21342 [Doc] update mv switch parameter value
  docs/TOC.md
  docs/administration/Configuration.md
  docs/release_notes/release-2.5.md
  docs/sql-reference/sql-functions/map-functions/map_from_arrays.md
  docs/using_starrocks/Materialized_view.md
Labels: documentation, title needs [type]

#21324 [BugFix][Cherry-pick-2.3] Fix wrong state of 'isExecuteInOneTablet' when it comes to agg or analytic
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/BinderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
Labels: automerge

#21077 [BugFix] Fix FE failing to pass jsonpaths to be for avro import
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
Labels: 3.0

#21298 [Enhancement] Disable automatic partition in cloud native table
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
Labels: 3.0

#21351 [Doc] update query cache
  docs/using_starrocks/query_cache.md
Labels: documentation

#21357 [Doc] update query cache in Branch 3.0
  docs/using_starrocks/query_cache.md
Labels: documentation

#21329 [Doc] 2.3 update navigation
  docs/TOC.md
  docs/introduction/StarRocks_intro.md
Labels: documentation

#21336 [Doc] update 2.5 navigation
  docs/introduction/StarRocks_intro.md
Labels: documentation

#21337 [Doc] update 3.0 navigation
  docs/introduction/StarRocks_intro.md
Labels: documentation

#21360 [BugFix] Fix bug information function analyze use global state in session
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SetDefaultRoleExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SetRoleExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.0

#21358 [Doc] add limit for automatic partitioning
  docs/table_design/Data_distribution.md
Labels: documentation

#21141 [BugFix] Fix statistic sql will query statistic table
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/TableStatsCacheLoader.java
Labels: 3.0

#21135 [Feature] Support function next_day
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  docs/TOC.md
  docs/sql-reference/sql-functions/date-time-functions/next_day.md
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  gensrc/script/functions.py
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: documentation

#21369 [BugFix] Fix time_slice function unstable result since interval type not match
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: 3.0

#21127 [BugFix] BE stream load rollback failure
  be/src/runtime/stream_load/stream_load_executor.cpp
Labels: 2.5, 2.4, 2.3, 3.0

#21377 [BugFix] Fix union query rewrite not work when use ttl mv for external table
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOptimizationTest.java
Labels: 2.5, 3.0

#21305 [BugFix] JDBC scanner encountered down_cast error while constcolumn is nullable
  be/src/exec/jdbc_scanner.cpp
Labels: 2.5, 3.0

#21349 [Enhancement] make spill_local_storage_dir not dependent on storage_root_path
  be/src/common/config.h
  be/src/exec/spill/dir_manager.cpp
Labels: 3.0

#21299 [Enhancement] support ANSI SQL ignore nulls syntax
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
Labels: 3.0
