Repository StarRocks/starrocks, pull requests merged in 2024-01, with the labels that each got.

#37909 [BugFix] Fix mv refresh with mysql external table bug
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MysqlSchemaResolverTest.java
Labels: 3.2

#38199 [Doc] Wrap task name
  docs/en/sql-reference/sql-statements/data-manipulation/DROP_TASK.md
  docs/zh/sql-reference/sql-statements/data-manipulation/DROP_TASK.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#38207 [BugFix] Fix sql tests returning empty result for ddl
  test/sql/test_catalog/R/test_iceberg_hadoop_catalog
  test/sql/test_information_schema/R/test_external_catalog_information_schema
Labels: 3.2

#38110 [Enhancement] remove garbage delta column files when expired version
  be/src/storage/delta_column_group.cpp
  be/src/storage/delta_column_group.h
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/update_manager.cpp
  be/src/storage/update_manager.h
  be/test/storage/delta_column_group_test.cpp
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.1, 3.2

#38210 [Doc] 3.2.2 release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#37550 [Enhancement] Print hint message for waiting globalStateMgr to be ready
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: 2.5, 3.0, 3.1, 3.2

#38211 [Enhancement] Support topn runtime filter for pruned partition filter
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
Labels: 3.1, 3.2

#38216 [BugFix] Fix user show tables has result when no permission of external table bug
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowTableMockMeta.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowTablesTest.java
Labels: 3.0, 3.1, 3.2

#38244 [Doc] Update LTS info in README.md
  docs/zh/README.md
Labels: documentation

#38234 [Enhancement] skip preload if memory exceed
  be/src/storage/lake/update_manager.cpp
Labels: 3.1, 3.2

#38226 [BugFix] accumulate ndv in or predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MockTpchStatisticStorage.java
Labels: 2.5, 3.0, 3.1, 3.2

#37688 [BugFix] The tablet schema in rowset meta is incomplete in partial update
  be/src/storage/delta_writer.cpp
Labels: 3.2

#38054 [BugFix] fix compatibility between 2.5 FE and 3.0 BE
  be/src/exec/pipeline/scan/chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.h
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  be/src/exec/schema_scanner/schema_materialized_views_scanner.h
  be/src/util/thrift_rpc_helper.cpp
  be/src/util/thrift_rpc_helper.h
  gensrc/thrift/FrontendService.thrift
Labels: 3.0, 3.1, 3.2, PROTO-REVIEW

#38219 [Enhancement] Support bitmap_hash for count(distinct x) rewrite (backport #33538)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateFunctionRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateExtractor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/BitmapRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/CountRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/DateTruncEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/EquivalentShuttleContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IAggregateRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IPredicateRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/IRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/RewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/TimeSliceRewriteEquivalent.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
Labels: automerge

#38254 [Doc] Add doc for enable_materialized_view_rewrite_for_insert
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#38092 [Doc] update grant/revoke in Branch 2.5
  docs/en/administration/User_privilege.md
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
  docs/en/sql-reference/sql-statements/account-management/REVOKE.md
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/zh/administration/User_privilege.md
  docs/zh/sql-reference/sql-statements/account-management/GRANT.md
  docs/zh/sql-reference/sql-statements/account-management/REVOKE.md
Labels: documentation

#37638 [Enhancement] Routine load task schduling
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaTaskInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaTaskInfoTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#38147 [UT] add test case for select into outfile
  test/sql/test_sink/R/test_issue_38020
  test/sql/test_sink/T/test_issue_38020
Labels: 2.5, 3.0, 3.1, 3.2

#38138 [Enhancement] Upgrade netty due to CVE-2022-41881
  fe/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#37686 [Enhancement] Support passing through Hive table columns' comment for Show Create Table and etc.
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
Labels: 3.2

#37452 [Enhancement] Support querying Iceberg tables that have been REPLACE PARTITION FIELD
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.2

#38278 [Doc] Update mem_limit unit
  docs/en/administration/BE_configuration.md
  docs/en/administration/Memory_management.md
  docs/zh/administration/BE_configuration.md
  docs/zh/administration/Memory_management.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#37637 [BugFix] Fix map_element bug when const map and variable key
  be/src/column/column_helper.h
  be/src/column/datum.h
  be/src/column/map_column.cpp
  be/src/exprs/array_functions.cpp
  be/src/exprs/map_element_expr.cpp
  be/src/exprs/map_expr.cpp
  be/test/exprs/map_element_expr_test.cpp
  be/test/exprs/map_expr_test.cpp
  test/sql/test_join/R/test_join_map
  test/sql/test_join/R/test_join_struct
  test/sql/test_map/R/test_map
  test/sql/test_map/T/test_map
  test/sql/test_semi/R/test_binary
Labels: 3.1, 3.2

#38194 [BugFix] Fix nullpointer exeception when create partition concurrent
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.0, 3.1, 3.2

#38292 [Doc] Fix links in 3.1.6 release notes
  docs/en/release_notes/release-2.5.md
  docs/en/release_notes/release-3.1.md
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#38200 [Feature] modify some cloud star cache configs
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/service/staros_worker.cpp
Labels: behavior_changed

#34365 [Feature] Arithmetic expression JIT
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/exec/aggregator.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_operation.h
  be/src/exprs/decimal_binary_function.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/jit/ir_helper.cpp
  be/src/exprs/jit/ir_helper.h
  be/src/exprs/jit/jit_engine.cpp
  be/src/exprs/jit/jit_engine.h
  be/src/exprs/jit/jit_expr.cpp
  be/src/exprs/jit/jit_expr.h
  be/src/exprs/jit/jit_functions.cpp
  be/src/exprs/jit/jit_functions.h
  be/src/exprs/literal.cpp
  be/src/exprs/literal.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/runtime_state.h
  be/src/testutil/exprs_test_helper.h
  be/src/types/logical_type.h
  be/test/exprs/arithmetic_expr_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/Exprs.thrift
  gensrc/thrift/InternalService.thrift
  gensrc/thrift/Opcodes.thrift
  gensrc/thrift/StatusCode.thrift
  test/sql/test_jit/R/test_arithmetic
  test/sql/test_jit/T/test_arithmetic
Labels: PROTO-REVIEW

#38279 [Doc] add 3.0.9 rn
  docs/en/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.0.md
Labels: documentation

#38281 [Doc] Update gcs.md
  docs/en/loading/gcs.md
Labels: documentation

#38296 [Doc] Add doc for table function: unnest_bitmap
  docs/en/sql-reference/sql-functions/bitmap-functions/unnest_bitmap.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/unnest_bitmap.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.1, 3.2

#37740 [Enhancement] Adjust calculation method for page cache mem usage metrics
  be/src/storage/page_cache.cpp
  be/src/util/lru_cache.cpp
  be/src/util/lru_cache.h
Labels: 2.5, 3.0, 3.1, 3.2

#37419 [Feature] support to read iceberg equality delete file for mor.
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/CMakeLists.txt
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/src/exec/mor_processor.cpp
  be/src/exec/mor_processor.h
  be/src/storage/chunk_helper.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/join_hash_map_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TableTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#38349 [Doc]modify the contents in behaviour changes on 3.0.9rn
  docs/en/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.0.md
Labels: documentation

#38341 [Feature] add session variable enable_query_queue
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
Labels: 2.5-merged

#37546 [Enhancement] optimize mv rewrite performance by prune search space
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/schema/MSchema.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePerfTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/QueryDumpPlannerBenchTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mv_join_rewrite.json
Labels: 3.1, 3.2

#38280 [Enhancement] Add some FE http metrics
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpMetricRegistry.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServerHandler.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: 2.5, 3.0, 3.1, 3.2

#38299 [Enhancement] reduce tablet shard read lock holding time when calc persistent index compact score
  be/src/storage/olap_server.cpp
  be/src/storage/tablet_manager.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38358 [BugFix] fix wrong order by scope for distinct query
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#38377 [BugFix] fix error message when dropping table
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
Labels: 3.1, 3.2

#38392 [Doc] Update StarRocks_intro.md
  docs/en/introduction/StarRocks_intro.md
Labels: documentation

#38336 [BugFix] Fix incorrect memory usage stats in compaction state
  be/src/storage/lake/update_compaction_state.cpp
  be/src/storage/update_compaction_state.cpp
Labels: 3.1, 3.2

#36746 [BugFix] Fix secondary tablet writer does not abort properly
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/async_delta_writer.cpp
  be/src/storage/async_delta_writer.h
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/segment_flush_executor.cpp
  be/src/storage/segment_flush_executor.h
  be/test/CMakeLists.txt
  be/test/storage/segment_flush_executor_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38351 [Doc] update length of names in system limit
  docs/en/reference/System_limit.md
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_DATA.md
  docs/zh/reference/System_limit.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_DATA.md
Labels: documentation, 3.2

#38348 [BugFix] Fix naaj when join conditions has binary equal predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: 3.0, 3.1, 3.2

#38368 [BugFix] support abort sink in the connector metadata
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/CatalogConnectorMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  test/sql/test_hive/R/test_hive_sink
  test/sql/test_hive/T/test_hive_sink
Labels: 3.2

#38410 [Doc] Add default_mv_refresh_immediate
  docs/en/administration/FE_configuration.md
  docs/zh/administration/FE_configuration.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#38390 [Doc] Create FAQ_On_Github.md
  docs/docusaurus/sidebars.json
  docs/en/data_source/datalake_faq.md
  docs/en/faq/FAQ_On_Github.md
  docs/en/faq/Others.md
  docs/en/faq/Sql_faq.md
  docs/en/faq/loading/Loading_faq.md
  docs/zh/faq/FAQ_On_Github.md
  docs/zh/faq/Others.md
  docs/zh/faq/Sql_faq.md
  docs/zh/faq/loading/Broker_load_faq.md
  docs/zh/faq/loading/CloudCanal_load_faq.md
  docs/zh/faq/loading/Flink_connector_faq.md
  docs/zh/faq/loading/Loading_faq.md
  docs/zh/faq/loading/Routine_load_faq.md
  docs/zh/faq/loading/Stream_load_faq.md
Labels: documentation, 3.0, 3.1, 3.2

#38375 [Doc] add func crc32 [3.3 maybe]
  docs/en/sql-reference/sql-functions/string-functions/crc32.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/string-functions/crc32.md
Labels: documentation

#37809 [Enhancement] Add metrics for shortciruit query
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitHybridExecutor.java
Labels: 3.2

#38430 [Doc] Unify param names in azure-related docs
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/en/data_source/catalog/hive_catalog.md
  docs/en/data_source/catalog/hudi_catalog.md
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/data_source/catalog/paimon_catalog.md
  docs/en/data_source/catalog/unified_catalog.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/hive_catalog.md
  docs/zh/data_source/catalog/hudi_catalog.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/data_source/catalog/paimon_catalog.md
  docs/zh/data_source/catalog/unified_catalog.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
Labels: documentation

#38385 [BugFix] Should not add full row column in vertical compaction's rowset writer
  be/src/column/schema.cpp
  be/src/column/schema.h
  be/src/storage/delta_writer.cpp
  be/src/storage/memtable.cpp
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/rowset_merger.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_schema.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.2

#37676 [BugFix] fixed-35898 : mv refresh with postgres table in jdbc catalog
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/PostgresSchemaResolverTest.java
Labels: 3.1, 3.2

#38437 [Doc] Unify param names in azure-related docs (backport #38437)
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/en/data_source/catalog/hive_catalog.md
  docs/en/data_source/catalog/hudi_catalog.md
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/data_source/catalog/paimon_catalog.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/hive_catalog.md
  docs/zh/data_source/catalog/hudi_catalog.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/data_source/catalog/paimon_catalog.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
Labels: documentation

#38414 [Enhancement] Using LazyColumnReader in orc lazy materialization
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.cc
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.hh
  be/src/formats/orc/apache-orc/c++/src/Reader.cc
Labels: 3.1, 3.2

#38411 [Enhancement] Optimize the performance of calc mem usage for bitmap column
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/test/storage/chunk_helper_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38444 [Doc] Add pipe related sql commands to sql overview page
  docs/en/sql-reference/sql-statements/all-commands.md
  docs/zh/sql-reference/sql-statements/all-commands.md
Labels: documentation

#38380 [BugFix] Fix common type is date when date compare datetime
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#38420 [BugFix] Set instance memtracker in Connector Sink IO task
  be/src/exec/parquet_writer.cpp
  be/src/exec/parquet_writer.h
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/file_writer.h
Labels: 3.2

#38464 [BugFix] check base table existence when updating meta
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
Labels: 2.5, 3.0, 3.1, 3.2

#38443 [Enhancement] optimzie plan retry strategy
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: 2.5, 3.0, 3.1, 3.2

#38472 [Doc] Update now(p) and add variable transaction_read_only
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/en/sql-reference/sql-functions/date-time-functions/now.md
  docs/en/sql-reference/sql-functions/date-time-functions/utc_timestamp.md
  docs/zh/reference/System_variable.md
  docs/zh/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/zh/sql-reference/sql-functions/date-time-functions/now.md
  docs/zh/sql-reference/sql-functions/date-time-functions/utc_timestamp.md
Labels: documentation, 3.1, 3.2

#38421 [BugFix] Add more error messages for tablet lost replicas error
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.2

#38481 [Enhancement] Revert Upgrade netty due to CVE-2022-41881
  fe/pom.xml
Labels: 3.0, 3.2, 3.1-merged, 2.5-merged

#38394 [Doc] adding in a top level topic, project help.
  docs/docusaurus/sidebars.json
  docs/en/project_help/project_help.mdx
  docs/en/project_help/slack.md
  docs/zh/project_help/project_help.mdx
  docs/zh/project_help/slack.md
Labels: documentation

#38393 [BugFix] fix pk table apply compaction crash because of double free
  be/src/storage/tablet_updates.cpp
Labels: 3.1, 3.2

#38496 [Enhancement] unify __int128 to string conversion
  be/src/runtime/large_int_value.cpp
  be/src/runtime/large_int_value.h
Labels: 3.1, 3.2

#38485 [BugFix] fix multi view join rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/test/java/com/starrocks/planner/ViewBaseMvRewriteTest.java
Labels: 3.2

#37972 [Feature]List partition supports Datacache.partition_duration
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
Labels: behavior_changed

#36249 [Enhancement] Use standalone lake compaction txn timeout config
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
Labels: behavior_changed

#38504 [Enhancement]sql-tester supports deltalake catalog
  test/conf/sr.conf
Labels: 3.0, 3.1, 3.2

#38510 [Feature]List partition supports Datacache.partition_duration (backport #37972)
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
Labels: behavior_changed

#38509 [Feature]List partition supports Datacache.partition_duration (backport #37972)
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
Labels: behavior_changed

#38445 [BugFix] Clearify error message when creating column with row type
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
Labels: 3.2

#38520 [BugFix] Make sys.fe_locks work
  be/src/exec/schema_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeLocks.java
Labels: 3.2

#35676 [Enhancement] Assign a new schema id after finish fast schema evolution
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/rowset/rowset.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_schema.cpp
  be/src/storage/tablet_schema.h
  be/test/CMakeLists.txt
  be/test/storage/fast_schema_evolution_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableAddOrDropColumnsInfo.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/TableAddOrDropColumnsInfoTest.java
  gensrc/proto/descriptors.proto
  gensrc/thrift/Descriptors.thrift
Labels: 3.2, META-REVIEW, PROTO-REVIEW

#38532 [BugFix] Fix count_down_pipeline may cause use-after-free
  be/src/exec/pipeline/fragment_context.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38490 [BugFix]fix bug of isOutputColumn on deltalake table
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.1, 3.2

#38196 [Enhancement] Support create mv base on iceberg table with partition transform
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergPartitionTransform.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergPartitionUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/MockIcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TableTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: 3.2

#36559 [BugFix] Optimize partition compensate strategy for performance(Part1)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/QueryDebugOptions.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryMaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewHiveTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewLowCardTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/schema/MSchema.java
  fe/fe-core/src/test/java/com/starrocks/schema/MTable.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVPartitionCompensateOptBench.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/NormalizePredicateBench.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q11.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch/q5.sql
Labels: 3.2, META-REVIEW

#37912 [Enhancement] add connnector_sink_compression_codec to control file compression scheme
  fe/fe-core/src/main/java/com/starrocks/analysis/OutFileClause.java
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergTableSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/planner/HiveTableSinkTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: behavior_changed, 3.2

#38465 [BugFix]fix some profile bug for parquet reader
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/column_chunk_reader.cpp
  be/src/formats/parquet/column_chunk_reader.h
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/stored_column_reader.cpp
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
Labels: 3.2

#38530 [BugFix] Use uuid in replication txn label to avoid duplicated txn label exception
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
Labels: 3.1, 3.2

#32399 [Enhancement] Optimize task run and task run status to be better for show materialized views
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/MaterializedViewsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowMaterializedViewStatus.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/MVTaskRunExtraMessage.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowMaterializedViewsStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/schema/MSchema.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  gensrc/thrift/FrontendService.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_create_mv_with_params
  test/sql/test_materialized_view/R/test_mv_iceberg_rewrite
  test/sql/test_materialized_view/T/test_create_mv_with_params
  test/sql/test_materialized_view/T/test_mv_iceberg_rewrite
Labels: META-REVIEW, PROTO-REVIEW

#36688 [BugFix] Fix exec state report lost lead to ingestion status getting stuck
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/exec_state_reporter.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38558 [BugFix] Fix shortcircuit creating wrong values chunk
  be/src/exec/short_circuit_hybrid.cpp
Labels: 3.2

#38271 [BugFix] Fix race condition in BucketProcess AGG
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/bucket_process_operator.cpp
  be/src/exec/pipeline/bucket_process_operator.h
  be/src/exec/pipeline/chunk_accumulate_operator.h
  be/src/exec/pipeline/limit_operator.h
  be/src/exec/pipeline/project_operator.cpp
  be/src/exec/pipeline/project_operator.h
  be/src/exec/query_cache/owner_info.h
  be/src/storage/chunk_helper.cpp
  be/test/storage/chunk_helper_test.cpp
  test/sql/test_agg/R/test_bucket_agg
  test/sql/test_agg/T/test_bucket_agg
  test/sql/test_spill/R/test_spill_aggregate
  test/sql/test_spill/T/test_spill_aggregate
Labels: 3.2

#38562 [BugFix] Fix the bug of release pk column memory in the apply stage
  be/src/column/column.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/update_compaction_state.cpp
  be/src/storage/update_compaction_state.h
Labels: 2.5, 3.0, 3.1, 3.2

#38536 [BugFix] fix hang when chunk source mem bytes exceeds scan mem limit
  be/src/connector/connector.h
  be/src/connector/hive_connector.h
  be/src/exec/connector_scan_node.cpp
  be/src/exec/connector_scan_node.h
  be/src/exec/pipeline/scan/chunk_source.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
Labels: 3.2

#35538 [BugFix] Fix lake batch publish & alter job with physical partition
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartitionImpl.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndicesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PhysicalPartitionImplTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest2.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.2

#38215 [BugFix] ensure hdfsFile resource is released during close
  be/src/fs/hdfs/fs_hdfs.cpp
  be/test/CMakeLists.txt
  be/test/fs/fs_hdfs_test.cpp
  run-be-ut.sh
Labels: 2.5, 3.0, 3.1, 3.2

#38599 [BugFix] fix pk tablet's data size when call get_tablet_stat
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: 3.0, 3.1, 3.2

#38499 [BugFix] Release pk state cache when txn is aborted
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.1, 3.2

#38597 [BugFix] Fix Some partitions cannot analyze due to time inconsistency
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
Labels: 3.2

#38582 [Enhancement] simplify binary equals expr
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/FurtherPartitionPruneTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
Labels: 3.1, 3.2

#38589 [Enhancement] covert to equal for null predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ConvertToEqualForNullRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/ConvertToEqualForNullRuleTest.java
Labels: 3.2

#38617 [BugFix] Fix OrcChunkReader::lazy_seek_to failed
  be/src/formats/orc/apache-orc/c++/src/Reader.cc
Labels: 3.1, 3.2

#38595 [BugFix] Fix not support projectNode for short circuit read
  be/src/exec/exec_node.h
  be/src/exec/short_circuit.cpp
  be/src/exec/short_circuit_hybrid.cpp
  be/src/exec/short_circuit_hybrid.h
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitHybridExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ShortCircuitTest.java
  test/sql/test_short_circuit/R/test_short_circuit
  test/sql/test_short_circuit/T/test_short_circuit
Labels: 3.2

#38641 [Doc] Change default for upgrade and downgrade
  docs/en/deployment/downgrade.md
  docs/en/deployment/upgrade.md
  docs/zh/deployment/downgrade.md
  docs/zh/deployment/upgrade.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#38635 [Enhancement] Add be config item: query_cache_num_lanes_per_driver
  be/src/common/config.h
  be/src/exec/pipeline/fragment_executor.cpp
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2

#38640 [BugFix] fix hierarchical mv active issue
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/MaterializedViewExceptions.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MVActiveChecker.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#38661 [Enhancement] Add be config item: query_cache_num_lanes_per_driver (backport #38635)
  be/src/common/config.h
  be/src/exec/pipeline/fragment_executor.cpp
Labels: 2.5, behavior_changed, backport_ok

#38658 [Doc] handle replication_num in s3 load doc and hdfs load doc
  docs/en/loading/hdfs_load.md
  docs/en/loading/s3.md
  docs/zh/loading/hdfs_load.md
  docs/zh/loading/s3.md
Labels: documentation

#38652 [BugFix] Use delete predicates to filter data when creating sync mv
  be/src/storage/rowset/rowset.h
  be/src/storage/schema_change.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_reader.cpp
  be/src/storage/tablet_reader.h
  test/sql/test_materialized_view/R/test_sync_materialized_view2
  test/sql/test_materialized_view/T/test_sync_materialized_view2
Labels: 2.5, 3.0, 3.1, 3.2

#31940 [Enhancement] JDBC connector supports TIME type
  be/src/exec/jdbc_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/JDBCMetadataTest.java
  java-extensions/jdbc-bridge/src/main/java/com/starrocks/jdbcbridge/JDBCScanner.java
  java-extensions/udf-extensions/src/main/java/com/starrocks/udf/UDFHelper.java
Labels: 3.1, behavior_changed, 3.2

#38660 [Enhancement] Optimize view based rewrite trace log
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
Labels: 3.2

#36772 [Enhancement]Reduce HeadObject before read segment file
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/rowset_update_state.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/spark_load.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/vertical_compaction_task.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/src/storage/rowset/segment_rewriter.h
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/storage/tablet_updates.cpp
  be/src/tools/meta_tool.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/metacache_test.cpp
  be/test/storage/lake/rowset_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
  be/test/storage/lake/tablet_writer_test.cpp
  be/test/storage/meta_reader_test.cpp
  be/test/storage/rowset/column_reader_writer_test.cpp
  be/test/storage/rowset/map_column_rw_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset/segment_iterator_test.cpp
  be/test/storage/rowset/segment_rewriter_test.cpp
  be/test/storage/rowset/segment_test.cpp
  be/test/storage/rowset/struct_column_rw_test.cpp
  be/test/storage/segment_flush_executor_test.cpp
  gensrc/proto/lake_types.proto
Labels: 3.1, 3.2, PROTO-REVIEW

#38598 [BugFix] Fix automatic create partition return inconsistency result when tablet rebalance
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.0, 3.1, 3.2

#38663 [BugFix] Increase column_with_row column length limit to MAX_VARCHAR_LENGTH
  be/src/storage/tablet_manager.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.2

#38692 [Doc] handle replication_num in s3 load doc and hdfs load doc in Branch 3.1 (backport #38692)
  docs/en/loading/hdfs_load.md
  docs/en/loading/s3.md
  docs/zh/loading/hdfs_load.md
  docs/zh/loading/s3.md
Labels: documentation

#38563 [Enhancement] Log detail exception messages in some methods of HdfsFsManager
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
Labels: 2.5, 3.0, 3.1, 3.2

#38714 [Doc] handle replication_num in query cache doc
  docs/en/using_starrocks/query_cache.md
  docs/zh/using_starrocks/query_cache.md
Labels: documentation

#38650 [BugFix] Add valid source of boost
  thirdparty/vars.sh
Labels: 3.2

#38699 [Enhancement] disable hdfs scan count optimization when exists iceberg equality files
  be/src/connector/hive_connector.cpp
Labels: 3.1, 3.2

#37145 [Doc] optimize the syntax of ALTER TABLE MODIFY PARTITION. Update ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, 3.0, 3.1, 3.2

#38712 [Doc] add overviews for table design
  docs/docusaurus/sidebars.json
  docs/en/assets/table_design/Catalog_db_tbl.png
  docs/en/assets/table_design/table_overview.png
  docs/en/table_design/StarRocks_table_design.md
  docs/en/table_design/catalog_db_tbl.md
  docs/zh/assets/table_design/Catalog_db_tbl.png
  docs/zh/assets/table_design/table_overview.png
  docs/zh/table_design/StarRocks_table_design.md
  docs/zh/table_design/catalog_db_tbl.md
Labels: documentation, 3.2

#38701 [BugFix] Fix local key partition shuffler using a nearly unbouded large buffer
  be/src/exec/pipeline/pipeline_builder.cpp
Labels: 3.2

#38537 [Enhancement]Enhance JNI reader for date and timestamp type
  be/src/connector/hive_connector.cpp
  be/src/exec/jni_scanner.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OdpsTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java
  gensrc/thrift/Descriptors.thrift
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveColumnValue.java
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveScanner.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiColumnValue.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiScannerUtils.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScanner.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnType.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ColumnValue.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapColumnVector.java
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsColumnValue.java
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsSplitScanner.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonColumnValue.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
Labels: 3.2, PROTO-REVIEW

#38754 [Doc] move releasenotes to top nav
  docs/docusaurus/sidebars.json
  docs/en/cover_pages/connector_index.mdx
  docs/en/cover_pages/release_notes_index.mdx
  docs/en/cover_pages/release_notes_overview.mdx
  docs/zh/cover_pages/connector_index.mdx
  docs/zh/cover_pages/release_notes_index.mdx
  docs/zh/cover_pages/release_notes_overview.mdx
Labels: documentation

#36648 [Enhancement] Optimization of memory usage for rowset metadata.
  be/src/storage/base_tablet.h
  be/src/storage/data_dir.cpp
  be/src/storage/rowset/rowset_meta.h
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_update_state.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/txn_manager.cpp
Labels: 3.2

#38543 [BugFix] Remove invalid predicates after mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarRangePredicateExtractor.java
  fe/fe-core/src/test/java/com/starrocks/schema/MSchema.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.0, 3.1, 3.2

#38627 [Enhancement] Do not throw exception if calling hms stats thrift api fails
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveCommitter.java
Labels: 3.2

#38704 Revert "[BugFix] fix compatibility between 2.5 FE and 3.0 BE (#38054)"
  be/src/exec/pipeline/scan/chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.h
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  be/src/exec/schema_scanner/schema_materialized_views_scanner.h
  be/src/util/thrift_rpc_helper.cpp
  be/src/util/thrift_rpc_helper.h
  gensrc/thrift/FrontendService.thrift
Labels: title needs [type], PROTO-REVIEW

#38702 Revert "[BugFix] fix compatibility between 2.5 FE and 3.0 BE (backport #38054)"
  be/src/exec/pipeline/scan/chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.h
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  be/src/exec/schema_scanner/schema_materialized_views_scanner.h
  be/src/util/thrift_rpc_helper.cpp
  be/src/util/thrift_rpc_helper.h
  gensrc/thrift/FrontendService.thrift
Labels: title needs [type]

#38727 [BugFix] Fix not support true predicate on pk for short circuit read
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/rowstore/RowStoreUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ShortCircuitPlanner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ShortCircuitTest.java
  test/sql/test_short_circuit/R/test_short_circuit
  test/sql/test_short_circuit/T/test_short_circuit
Labels: 3.2

#38788 [Doc] correct levels in release notes
  docs/en/release_notes/release-2.2.md
  docs/en/release_notes/release-2.3.md
  docs/en/release_notes/release-2.5.md
  docs/en/release_notes/release-3.0.md
  docs/en/release_notes/release-3.1.md
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-2.2.md
  docs/zh/release_notes/release-2.5.md
  docs/zh/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#38542 [BugFix] Fix external OLAP table load failed bug
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: 3.2

#38739 [Doc] add func regexp_extract_all, update get_json_string, and sidebar
  docs/docusaurus/sidebars.json
  docs/en/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_string.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_extract_all.md
  docs/zh/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_string.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/regexp_extract_all.md
Labels: documentation, 3.2

#38197 [Feature] support ngram_search's ascii version
  be/src/exprs/CMakeLists.txt
  be/src/exprs/ngram.cpp
  be/src/exprs/string_functions.h
  docs/en/sql-reference/sql-functions/string-functions/ngram_search.md
  gensrc/script/functions.py
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: documentation

#38765 [BugFix] Fix NPE when spark load not specify properties
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
Labels: 2.5, 3.0, 3.1, 3.2

#38790 [Enhancement] reduce min publish version thread number
  be/src/agent/agent_common.h
Labels: 3.1, behavior_changed, 3.2

#38729 [BugFix] Change operationType of OP_UPSERT_TRANSACTION_STATE_BATCH
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
Labels: 3.1, 3.2

#38797 [Enhancement] Don't do clearIORanges() in orc reader's prepareCache()
  be/src/formats/orc/orc_input_stream.cpp
Labels: 3.0, 3.1, 3.2

#38785 [Doc]Improve the External Catalog Ranger configuration document
  docs/en/administration/ranger_plugin.md
  docs/zh/administration/ranger_plugin.md
Labels: documentation, 3.1, 3.2

#38827 [Doc] update function list and get_json_object to Branch 3.0
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_string.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_string.md
Labels: documentation, 2.5

#38330 [Feature] Support pk table replication from another cluster for olap table and cloud-native table
  be/src/agent/publish_version.cpp
  be/src/fs/fs_memory.cpp
  be/src/fs/fs_memory.h
  be/src/storage/del_vector.cpp
  be/src/storage/del_vector.h
  be/src/storage/lake/replication_txn_manager.cpp
  be/src/storage/lake/replication_txn_manager.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/replication_txn_manager.cpp
  be/src/storage/replication_txn_manager.h
  be/src/storage/replication_utils.cpp
  be/src/storage/replication_utils.h
  be/src/storage/rowset/rowset_meta.h
  be/test/agent/agent_task_test.cpp
  be/test/storage/lake/replication_txn_manager_test.cpp
  be/test/storage/replication_txn_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/test/java/com/starrocks/replication/ReplicationJobTest.java
  fe/fe-core/src/test/java/com/starrocks/replication/ReplicationMgrTest.java
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW

#38801 [BugFix] fix mv with sql_select_limit
  fe/fe-core/src/main/java/com/starrocks/catalog/MvPlanContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#38832 [Enhancement] Set max user processes to 65535 in start_fe.sh
  bin/common.sh
  bin/start_backend.sh
  bin/start_fe.sh
  docs/en/deployment/environment_configurations.md
  docs/zh/deployment/environment_configurations.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#38732 [BugFix] CTAS uses column expression partition force partition columns not all…
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  test/sql/test_automatic_partition/R/test_automatic_partition_ctas
  test/sql/test_automatic_partition/T/test_automatic_partition_ctas
Labels: 3.1, 3.2

#37181 [BugFix] prepare stmt need redirect
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrepareAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PrepareStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  test/sql/test_preparestatement/R/test_prepare_statment_partition_changed
  test/sql/test_preparestatement/R/test_preprare_statement
  test/sql/test_preparestatement/R/test_preprare_statement_nopk_delete
  test/sql/test_preparestatement/T/test_prepare_statment_partition_changed
  test/sql/test_preparestatement/T/test_preprare_statement
  test/sql/test_preparestatement/T/test_preprare_statement_nopk_delete
Labels: 3.2

#36957 [BugFix] Fix BE memory violation issue caused by microsecond formatter %f
  be/src/runtime/datetime_value.cpp
  test/sql/test_function/R/test_date_format
  test/sql/test_function/T/test_date_format
Labels: 3.2

#38892 [Doc] change the position of flinkcdc3.0
  docs/en/loading/Flink-connector-starrocks.md
  docs/zh/loading/Flink-connector-starrocks.md
Labels: documentation

#38903 [Doc] Fix broken links in release notes
  docs/en/release_notes/release-2.2.md
  docs/en/release_notes/release-2.3.md
  docs/en/release_notes/release-2.4.md
  docs/en/release_notes/release-2.5.md
  docs/en/release_notes/release-3.0.md
  docs/en/release_notes/release-3.1.md
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-1.19.md
  docs/zh/release_notes/release-2.0.md
  docs/zh/release_notes/release-2.1.md
  docs/zh/release_notes/release-2.2.md
  docs/zh/release_notes/release-2.3.md
  docs/zh/release_notes/release-2.4.md
  docs/zh/release_notes/release-2.5.md
  docs/zh/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#38842 [Doc] Add doc for 'sql_mode'
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.0, 3.1, 3.2

#38888 [BugFix]support null partition_value to avoid crash
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/formats/parquet/file_reader.cpp
  test/sql/test_hive/R/test_hive_catalog
  test/sql/test_hive/T/test_hive_catalog
Labels: 2.5, 3.0, 3.1, 3.2

#38816 [Doc] add load tools
  docs/docusaurus/sidebars.json
  docs/en/assets/load_tools.png
  docs/en/cover_pages/loading_tools_integration.mdx
  docs/en/faq/loading/DataX_faq.md
  docs/en/integrations/loading_tools/CloudCanal.md
  docs/en/integrations/loading_tools/CloudCanal.mdx
  docs/en/integrations/loading_tools/DataX-starrocks-writer.md
  docs/en/integrations/loading_tools/DataX.mdx
  docs/en/integrations/loading_tools/SMT.md
  docs/en/integrations/loading_tools/loading_tools_integration.mdx
  docs/en/loading/loading_tools.md
  docs/zh/assets/load_tools.png
  docs/zh/cover_pages/loading_tools_integration.mdx
  docs/zh/integrations/loading_tools/CloudCanal.md
  docs/zh/integrations/loading_tools/CloudCanal.mdx
  docs/zh/integrations/loading_tools/DataX-starrocks-writer.md
  docs/zh/integrations/loading_tools/DataX.mdx
  docs/zh/integrations/loading_tools/SMT.md
  docs/zh/integrations/loading_tools/loading_tools_integration.mdx
  docs/zh/loading/Loading_intro.md
  docs/zh/loading/loading_tools.md
Labels: documentation, 3.2

#38893 [Enhancement] update staros to v3.2-rc6
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
Labels: 3.2

#38940 [Doc] Update loading_tools.md
  docs/en/integrations/loading_tools/SMT.md
  docs/en/loading/loading_tools.md
  docs/zh/integrations/loading_tools/SMT.md
Labels: documentation, 3.2

#37726 [Enhancement] thrift_used_clients counter performance optimization in thrift client reopen scene
  be/src/runtime/client_cache.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38942 [Enhancement] add connnector_sink_compression_codec to control file compression scheme (backport #37912)
  fe/fe-core/src/main/java/com/starrocks/analysis/OutFileClause.java
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergTableSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/planner/HiveTableSinkTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: behavior_changed

#38334 [BugFix] reuse the task and label when resuming task
  fe/fe-core/src/main/java/com/starrocks/common/LabelAlreadyUsedException.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeTaskDesc.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/PipeManagerTest.java
Labels: 3.2
