Repository StarRocks/starrocks, pull requests merged in 2024-03, with the labels that each got.

#41954 [BugFix] do not display isPending column for queries forwarded to the leader (backport #41652)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: behavior_changed

#41953 [BugFix] do not display isPending column for queries forwarded to the leader(backport #41652)
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: behavior_changed

#41949 [BugFix] Fix orc chunk reader search argument build check
  be/src/formats/orc/orc_chunk_reader.cpp
Labels: 3.0, 3.1, 3.2

#41919 [BugFix] tolerant trailing slash after bucket name in storage volume location
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/storagevolume/StorageVolumeTest.java
Labels: 3.2

#40598 [Feature] concat_ws supports array type parameters
  be/src/exprs/array_functions.h
  be/test/exprs/array_functions_test.cpp
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  gensrc/script/functions.py
Labels: behavior_changed

#37616 [Enhancement] Print compaction task statistics logs for cloud native table
  be/src/exec/schema_scanner/schema_be_cloud_native_compactions_scanner.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/compaction_task.h
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/horizontal_compaction_task.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/tablet_writer.h
  be/src/storage/lake/vertical_compaction_task.cpp
  be/src/storage/lake/vertical_compaction_task.h
  be/src/storage/olap_common.h
  be/test/CMakeLists.txt
  be/test/storage/lake/compaction_task_context_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
Labels: 3.1, behavior_changed, 3.2

#41970 [Enhancement] remove unnecessary function call to optimize ut time cost
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
Labels: 3.2

#41993 [UT] Optimize BDB run time
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBEnvironmentTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#41989 [Enhancement] Support config alias names
  be/src/common/config.h
  be/src/common/configbase.cpp
  be/src/common/configbase.h
  be/test/common/config_test.cpp
  conf/be_test.conf
Labels: 2.5, 3.0, 3.1, 3.2

#41957 [BugFix] Fix mv partition range bug for external tables
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteHiveTest.java
  test/sql/test_materialized_view/R/test_materialized_view_refresh_with_many_to_many
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg
  test/sql/test_materialized_view/T/test_materialized_view_refresh_with_many_to_many
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg
Labels: 3.2

#41991 [Doc] add CREATE TALBE and INSERT data examples to intersect_count
  docs/en/sql-reference/sql-functions/bitmap-functions/intersect_count.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/bitmap.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/intersect_count.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, doc-feedback

#41921 [BugFix] Format the datacache path configurations before checking it instead of returning error directly.
  be/src/block_cache/block_cache.cpp
  be/src/storage/options.cpp
  be/test/block_cache/block_cache_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#42024 [Doc] resolve conflicts in 3.0 Spark-connector-starrocks.md
  docs/en/loading/Spark-connector-starrocks.md
Labels: documentation

#42006 [BugFix] Add the missing closure ref count in multi_get (#42005)
  be/src/storage/table_reader.cpp
Labels: 3.2

#41755 [BugFix] Fixe bug where tablet was not deleted from meta when removing disk path from be.conf
  be/src/agent/agent_task.cpp
  be/src/agent/task_worker_pool.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
Labels: 2.5, 3.0, 3.1, 3.2

#41966 [Doc]Update the demo in kafka connector
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#41933 [BugFix] create table with local persistent index by mistake when CN doesn't have local disk
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.1, 3.2

#41731 [BugFix] Fix bug which cause storage volume is shown unexpectedly
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
Labels: 3.1, 3.2

#42030 [BugFix] Fix orc search argument build failed
  be/src/formats/orc/orc_chunk_reader.cpp
  test/sql/test_external_file/R/test_orc_build_search_argument
  test/sql/test_external_file/T/test_orc_build_search_argument
Labels: 3.0, 3.1, 3.2

#41946 [BugFix] fix expr ref pruned column in transformation phase
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistinctAggTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42059 [BugFix] Revert "[Enhancement] Delete pindex file when disable pindex (#39312)"
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/storage_engine.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#41940 [BugFix] fix resolve partition column failed where create mv
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SlotRefResolver.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: 3.1, 3.2

#42056 [Doc] recategorize a few functions
  docs/docusaurus/sidebars.json
  docs/en/loading/Flink-connector-starrocks.md
  docs/en/loading/Spark-connector-starrocks.md
  docs/en/sql-reference/sql-functions/aggregate-functions/hll_union_agg.md
  docs/en/sql-reference/sql-functions/array-functions/array_sort.md
  docs/en/sql-reference/sql-functions/array-functions/array_sortby.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_to_binary.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/percentile-functions/percentile_approx.mdx
  docs/en/sql-reference/sql-functions/percentile-functions/percentile_cont.mdx
  docs/en/sql-reference/sql-functions/percentile-functions/percentile_disc.mdx
  docs/en/sql-reference/sql-functions/scalar-functions/hll_empty.md
  docs/en/sql-reference/sql-functions/scalar-functions/hll_hash.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/en/sql-reference/sql-statements/data-types/HLL.md
  docs/zh/loading/Spark-connector-starrocks.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/hll_union_agg.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/percentile_cont.md
  docs/zh/sql-reference/sql-functions/array-functions/array_contains_all.md
  docs/zh/sql-reference/sql-functions/array-functions/array_cum_sum.md
  docs/zh/sql-reference/sql-functions/array-functions/array_difference.md
  docs/zh/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/bitmap_to_binary.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/intersect_count.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/percentile-functions/percentile_approx.mdx
  docs/zh/sql-reference/sql-functions/percentile-functions/percentile_cont.mdx
  docs/zh/sql-reference/sql-functions/percentile-functions/percentile_disc.mdx
  docs/zh/sql-reference/sql-functions/percentile-functions/percentile_union.md
  docs/zh/sql-reference/sql-functions/scalar-functions/hll_empty.md
  docs/zh/sql-reference/sql-functions/scalar-functions/hll_hash.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/zh/sql-reference/sql-statements/data-types/HLL.md
  docs/zh/using_starrocks/Using_HLL.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#42082 [Doc] Remove Azure Blob credentials from minio
  docs/en/deployment/shared_data/minio.md
Labels: documentation, 3.1, 3.2

#41941 [Doc] publish new loading overview docs
  docs/docusaurus/sidebars.json
  docs/en/administration/information_schema.md
  docs/en/assets/commonMarkdown/sharedDataUse.md
  docs/en/assets/loading_intro_overview.png
  docs/en/assets/quick-start/MinIO-create.png
  docs/en/faq/loading/Loading_faq.md
  docs/en/loading/BrokerLoad.md
  docs/en/loading/Flink-connector-starrocks.md
  docs/en/loading/InsertInto.md
  docs/en/loading/Loading_data_template.md
  docs/en/loading/Loading_intro.md
  docs/en/loading/loading.mdx
  docs/en/loading/loading_introduction/Loading_intro.md
  docs/en/loading/loading_introduction/loading_concepts.md
  docs/en/loading/loading_introduction/loading_considerations.md
  docs/en/loading/loading_introduction/loading_overview.mdx
  docs/en/reference/information_schema/loads.md
  docs/en/table_design/table_types/aggregate_table.md
  docs/en/table_design/table_types/duplicate_key_table.md
  docs/en/table_design/table_types/primary_key_table.md
  docs/en/table_design/table_types/unique_key_table.md
  docs/zh/administration/information_schema.md
  docs/zh/assets/commonMarkdown/sharedDataUse.md
  docs/zh/assets/loading_intro_overview.png
  docs/zh/assets/quick-start/MinIO-create.png
  docs/zh/faq/loading/Loading_faq.md
  docs/zh/loading/BrokerLoad.md
  docs/zh/loading/Flink-connector-starrocks.md
  docs/zh/loading/Loading_intro.md
  docs/zh/loading/loading.mdx
  docs/zh/loading/loading_introduction/Loading_intro.md
  docs/zh/loading/loading_introduction/loading_concepts.md
  docs/zh/loading/loading_introduction/loading_considerations.md
  docs/zh/loading/loading_introduction/loading_overview.mdx
  docs/zh/reference/information_schema/loads.md
  docs/zh/table_design/table_types/aggregate_table.md
  docs/zh/table_design/table_types/duplicate_key_table.md
  docs/zh/table_design/table_types/primary_key_table.md
  docs/zh/table_design/table_types/unique_key_table.md
Labels: documentation, 3.2

#41332 [BugFix] Fix gin problems
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/tablet_scanner.cpp
  be/src/runtime/snapshot_loader.cpp
  be/src/runtime/snapshot_loader.h
  be/src/storage/column_expr_predicate.cpp
  be/src/storage/column_in_predicate.cpp
  be/src/storage/inverted/clucene/clucene_inverted_reader.cpp
  be/src/storage/inverted/clucene/clucene_inverted_writer.cpp
  be/src/storage/inverted/clucene/match_operator.h
  be/src/storage/inverted/index_descriptor.hpp
  be/src/storage/inverted/inverted_index_option.cpp
  be/src/storage/inverted/inverted_plugin_factory.cpp
  be/src/storage/inverted/inverted_reader.h
  be/src/storage/olap_common.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet_index.h
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  gensrc/thrift/StatusCode.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: PROTO-REVIEW

#42034 [Enhancement] Replace_if_not_null support bitmap type
  fe/fe-core/src/main/java/com/starrocks/catalog/AggregateType.java
  test/sql/test_bitmap_functions/R/test_bitmap_replace_if_not_null
  test/sql/test_bitmap_functions/T/test_bitmap_replace_if_not_null
Labels: 2.5, 3.0, 3.1, 3.2

#42058 [BugFix] array compare cast error
  be/src/column/array_column.cpp
  be/src/util/memcmp.h
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
  test/sql/test_join/R/test_join_array
Labels: 3.0, 3.1, 3.2

#42098 [UT] Fixed stack-use-after-return in UT
  be/test/storage/lake/compaction_scheduler_test.cpp
Labels: 3.1, 3.2

#42055 [BugFix] Fix delete predicate in cross cluster replication for shared-data mode
  be/src/storage/lake/replication_txn_manager.cpp
  be/src/storage/lake/replication_txn_manager.h
  be/test/storage/lake/replication_txn_manager_test.cpp
Labels: 3.1, 3.2

#41969 [BugFix] Keep update statement output column's type consistent with target table's columns
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  test/sql/test_dml/R/test_update
  test/sql/test_dml/T/test_update
Labels: 3.2

#42078 [Doc]Update ranger_plugin.md
  docs/zh/administration/ranger_plugin.md
Labels: documentation, 3.1, 3.2

#41324 [BugFix] En hance rule base mv rewrite
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/DebugOperatorTracer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/TablePruningTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/ViewBaseMvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TracerMVTest.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mock_agg_with_having3.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mock_join_agg1.json
  test/sql/test_materialized_view/R/test_materialized_view_force_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_force_rewrite
Labels: behavior_changed

#42116 [Doc] add note of resource name autocomplete to ranger_plugin
  docs/en/administration/ranger_plugin.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.1, 3.2

#42061 [BugFix] disable dict_mapping function in shared data mode
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/DictQueryFunctionTest.java
Labels: 3.2

#42077 [BugFix] Report total number of tablets to FE in shared-data mode
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowBackendsStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowComputeNodesStmt.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BackendsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ComputeNodeProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.1, behavior_changed, 3.2

#41655 [Doc] Update audit_loader.md
  docs/en/administration/audit_loader.md
  docs/zh/administration/audit_loader.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#42086 [Enhancement] return 1295 when statement is not supported by prepare-statement
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorReport.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrepareAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  test/sql/test_auto_increment/R/test_auto_increment
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_column_rename/R/test_column_rename
  test/sql/test_column_rename/R/test_column_rename2
  test/sql/test_dictionary/R/test_dictionary
  test/sql/test_drop_table/R/test_drop_table
  test/sql/test_hive/R/test_hive_sink
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg
  test/sql/test_preparestatement/R/test_prepare_statment_partition_changed
  test/sql/test_primary_index_cache_expire/R/test_primary_index_cache_expire
Labels: 3.2

#42130 [Doc] fix translation error in the bitmap indexes
  docs/en/table_design/indexes/Bitmap_index.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#41895 [BugFix] Unconsistent delvec after disk disable (#41893)
  be/src/storage/storage_engine.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_mgr_test.cpp
Labels: 3.2

#42100 [BugFix] Fix race condition when access delete predicate list in tablet meta (#42099)
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
Labels: 2.5, 3.0, 3.1, 3.2

#42052 [BugFix] Fix mv refresh possible deadlock between checkBaseTablePartitionChange and prepareRefreshPlan
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42139 [BugFix] foreignKey constraints should not be changed by the caller
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
Labels: 3.1, 3.2

#42173 [Enhancement] use rbo view based mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  test/sql/test_materialized_view/R/test_view_based_mv_rewrite
  test/sql/test_materialized_view/T/test_view_based_mv_rewrite
Labels: 3.2

#42087 [BugFix] fix wrong slot index when handling iceberg delete columns
  be/src/exec/hdfs_scanner.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/meta_helper.h
  be/test/formats/parquet/group_reader_test.cpp
Labels: 3.2

#41975 [BugFix] mask secret parameters when create storage volume failed(#41975)
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/storagevolume/StorageVolumeTest.java
Labels: 3.1, 3.2

#41358 [Doc] add user variable hint doc
  docs/en/administration/Query_planning.md
  docs/zh/administration/Query_planning.md
Labels: documentation

#42178 [Feature] support regex_extact_all (backport #27990)
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_extract_all.md
  gensrc/script/functions.py
  test/sql/test_function/R/test_regex
  test/sql/test_function/T/test_regex
Labels: documentation

#42171 [BugFix] return null if to_json input is null
  be/src/exprs/cast_expr_json.cpp
  test/sql/test_json/R/to_json
  test/sql/test_json/T/to_json
Labels: 3.1, 3.2

#42110 [Enhancement] Improve hdfs metrics display
  be/src/exec/hdfs_scanner.cpp
  be/src/fs/hdfs/fs_hdfs.cpp
  be/src/fs/hdfs/fs_hdfs.h
Labels: 3.0, 3.1, 3.2

#42190 [Enhancement] Upgrade postgresql due to CVE-2024-1597
  fe/pom.xml
Labels: 2.5, 3.0, 3.1, 3.2

#42198 [BugFix] making this version comparison more resilient as it fails issues/41016
  contrib/dbt-connector/dbt/adapters/starrocks/impl.py
Labels: 3.2

#42140 [Doc] add rising_wave.md to integrations
  docs/docusaurus/sidebars.json
  docs/en/administration/BE_configuration.md
  docs/en/administration/FE_configuration.md
  docs/en/administration/Monitor_and_Alert.md
  docs/en/administration/Profiling.md
  docs/en/benchmarking/TPC_DS_Benchmark.md
  docs/en/deployment/starrocks_on_aws.md
  docs/en/faq/Others.md
  docs/en/integrations/IDE_integrations/Dataphin.md
  docs/en/integrations/loading_tools/CloudCanal.md
  docs/en/integrations/streaming/rising_wave.md
  docs/en/loading/Kafka-connector-starrocks.md
  docs/en/reference/System_variable.md
  docs/en/release_notes/release-2.3.md
  docs/en/release_notes/release-3.1.md
  docs/en/release_notes/release-3.2.md
  docs/en/sql-reference/sql-functions/Window_function.md
  docs/en/sql-reference/sql-functions/date-time-functions/date_trunc.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
  docs/en/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-definition/CANCEL_ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_FUNCTION.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-types/HLL.md
  docs/en/table_design/list_partitioning.md
  docs/zh/integrations/streaming/rising_wave.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.1, 3.2

#42121 [BugFix] Fix column name length inconsistent
  be/src/storage/delete_handler.cpp
  be/test/storage/delete_handler_test.cpp
Labels: 3.1, 3.2

#42226 [Doc] fix chinese characters in Branch 3.1 (backport #42140)
  docs/en/administration/Configuration.md
  docs/en/administration/Monitor_and_Alert.md
  docs/en/administration/Profiling.md
  docs/en/benchmarking/TPC_DS_Benchmark.md
  docs/en/deployment/starrocks_on_aws.md
  docs/en/faq/Others.md
  docs/en/integrations/IDE_integrations/Dataphin.md
  docs/en/loading/Kafka-connector-starrocks.md
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-functions/Window_function.md
  docs/en/sql-reference/sql-functions/date-time-functions/date_trunc.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
  docs/en/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_FUNCTION.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-types/HLL.md
  docs/en/table_design/list_partitioning.md
Labels: documentation

#42217 [BugFix] Fixe bug where tablet was not deleted from meta when removing disk path from be.conf (backport 41755)
  fe/fe-core/src/main/java/com/starrocks/master/MasterImpl.java
  fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
Labels: automerge

#41955 [BugFix] Fix bug which will cause pk index in cn can not be evicted and gc
  be/src/storage/olap_server.cpp
Labels: 3.1, 3.2

#42132 [BugFix] fix bugs of query dump for view and add support of query dump for mv on view
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  fe/fe-core/src/test/resources/sql/query_dump/mv_on_view.json
Labels: 3.1, 3.2

#42147 [Enhancement] adaptive choose execute nodes base on the volume of processed data
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/DefaultWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/WorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/RemoteFragmentAssignmentStrategy.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ExchangeSortToMergeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsEstimateCoefficient.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/AdaptiveChooseNodesTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/SessionVariableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MockTpchStatisticStorage.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
Labels: 3.2

#42230 [BugFix] remain unsupported operator when dict mapping rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DictMappingRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  test/sql/test_low_cardinality/R/test_low_cardinality
  test/sql/test_low_cardinality/T/test_low_cardinality
Labels: 2.5, 3.0, 3.1, 3.2

#41130 [Enhancement] Support size-tiered compaction for pk
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/rowset_column_partial_update_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.1, behavior_changed, 3.2

#42254 [BugFix] schema id should default to index id
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
Labels: 3.2

#42280 [ Enhancement]Upgrade paimon version to 0.7
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PaimonTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
  java-extensions/paimon-reader/pom.xml
Labels: title needs [type]

#42235 [Enhancement] add timezone in log event timestamp
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.1, 3.2

#42294 [Enhancement] update timezone format in log event
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.1, 3.2

#42288 [UT] Fix long running BeRestartTest and DecommissionTest
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeRestartTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/DecommissionTest.java
Labels: 3.2

#42284 [BugFix] fix reading iceberg equality delete correctness issue
  be/src/exec/hdfs_scanner.cpp
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: 3.2

#42229 [BugFix] Fix union all rewrite bugs in pulling up predicates and add materialized_view_union_rewrite_mode param
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/QueryDebugOptions.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateSetRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  test/sql/test_materialized_view/R/test_materialized_view_union_all_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_union_all_rewrite
Labels: 3.1, 3.2, META-REVIEW

#42307 [UT] head-use-after-free
  be/src/storage/lake/compaction_scheduler.cpp
Labels: 3.1, 3.2

#42318 [UT] fix asan mem leak in `GroupReaderTest` test case
  be/test/formats/parquet/group_reader_test.cpp
Labels: 3.2

#42031 [BugFix] Fix show load npe
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadMgrTest.java
Labels: 3.0, 3.1, 3.2

#42311 [BugFix] fix profile scan metrics skewed
  be/src/exec/pipeline/scan/scan_operator.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#42308 [Doc] add 3.1.9 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#42287 [BugFix] Fix auth upgrade log replay error when upgrading to main branch
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/AuthUpgradeInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
Labels: META-REVIEW

#42337 [UT] Fix unstable ut use dedicate test table
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/DDLTestBase.java
Labels: 3.2

#42347 [UT] ASAN false positive with exception
  be/src/util/stack_util.cpp
  be/src/util/stack_util.h
Labels: 2.5, 3.0, 3.1, 3.2

#42338 [UT] refactor and make RowsetColumnPartialUpdateTest stable
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.1, 3.2

#42282 [BugFix] Fix NPE from trim() method when no enable parameter given in GlobalDictMetaService request
  fe/fe-core/src/main/java/com/starrocks/http/meta/GlobalDictMetaService.java
Labels: 3.0, 3.1, 3.2

#42344 [UT] Add option to run-be-ut.sh to filter cases of specific group
  be/src/testutil/parallel_test.h
  be/test/column/binary_column_test.cpp
  be/test/column/chunk_test.cpp
  run-be-ut.sh
Labels: 2.5, 3.0, 3.1, 3.2

#42283 [BugFix] Fix LoadMgr Deadlock when there are many spark loads in the same database
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
Labels: 2.5, 3.0, 3.1, 3.2

#42281 [BugFix] Fix generated column become NULL after compaction in pk table
  be/src/storage/rowset/rowset_meta.h
  be/src/storage/tablet_updates.cpp
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: 3.2

#42317 [BugFix] Skip the temporary directory created by spark when list hive directory recursively
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedRemoteFileSystem.java
Labels: 3.1, behavior_changed, 3.2

#42195 [BugFix] Fix compatibility problem of storage volume
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1, 3.2

#42346 [Enhancement] Support datetime microsecond in ORC format (branch-3.2) (backport #42179)
  be/src/exec/orc_scanner.cpp
  be/test/exec/test_data/orc_scanner/generate_timestamp.py
  be/test/exec/test_data/orc_scanner/timestamp.orc
  be/test/formats/orc/orc_chunk_reader_test.cpp
Labels: behavior_changed

#42348 [Enhancement] Support datetime microsecond in ORC format (branch-3.1) (backport #42179)
  be/src/exec/orc_scanner.cpp
  be/test/exec/test_data/orc_scanner/generate_timestamp.py
  be/test/exec/test_data/orc_scanner/timestamp.orc
  be/test/formats/orc/orc_chunk_reader_test.cpp
Labels: behavior_changed

#42202 [Enhancement] Reduce duplicate data in RpcDataPackage during RPC transmission.
  fe/fe-core/src/main/java/com/starrocks/rpc/AttachmentRequest.java
  fe/fe-core/src/test/java/com/starrocks/rpc/PExecPlanFragmentRequestTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42158 [BugFix] Reset replica minReadableVerion in restore
  fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ReplicaTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42314 [BugFix]Fix the bug of setting the default value for the float type when creating table
  fe/fe-core/src/main/java/com/starrocks/analysis/FloatLiteral.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ColumnDefTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeDecimalV3Test.java
Labels: 3.2

#41964 [Doc] Categorize Parameters
  docs/en/administration/BE_configuration.md
  docs/en/administration/FE_configuration.md
  docs/zh/administration/BE_configuration.md
  docs/zh/administration/FE_configuration.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#42400 [Doc] update stable branch and doc path in readme
  docs/README.md
  docs/docusaurus/docusaurus.config.js
  docs/zh/README.md
  docs/zh/feedback-and-contribute.md
Labels: documentation

#42231 [Feature] Support pivot syntax
  docs/en/sql-reference/sql-statements/data-manipulation/SELECT.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SELECT.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PivotAggregation.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PivotRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PivotValue.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ParserErrorMsg.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzePivotTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/TransformerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
  fe/fe-core/src/test/resources/sql/logical-plan/pivot.sql
  test/sql/test_pivot/R/test_pivot
  test/sql/test_pivot/T/test_pivot
Labels: documentation

#42413 [Doc] doc updates from release notes
  docs/docusaurus/sidebars.json
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/reference/System_variable.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.2

#42419 [Doc]Add desc according updates in 3.2.4&3.1.9
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/table_design/dynamic_partitioning.md
  docs/en/table_design/hybrid_table.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/table_design/dynamic_partitioning.md
  docs/zh/table_design/hybrid_table.md
Labels: documentation, 3.1, 3.2

#42398 [Enhancement] adjust lake_autovacuum_grace_period_minutes to 30mins
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.1, behavior_changed, 3.2

#42437 [Doc] add milliseconds_diff func and update file external table according to v3.1.9 and 3.2.4 rn
  docs/docusaurus/sidebars.json
  docs/en/data_source/file_external_table.md
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-functions/date-time-functions/milliseconds_diff.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_extract_all.md
  docs/zh/data_source/file_external_table.md
  docs/zh/reference/System_variable.md
  docs/zh/sql-reference/sql-functions/date-time-functions/milliseconds_diff.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/regexp_extract_all.md
Labels: documentation, 3.2

#42421 [UT] Fix colocate balancer unstable ut
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42397 [BugFix] report error instead of crash when hyper scan failed
  be/src/exprs/like_predicate.cpp
Labels: 3.0, 3.1, 3.2

#42369 [Enhancement] to avoid `s3://` not supported case
  be/CMakeLists.txt
  build.sh
  conf/core-site.xml
Labels: 2.5, 3.0, 3.1, 3.2

#41267 [Feature] support to read iceberg equality delete file with parquet format
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/src/exec/mor_processor.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
  gensrc/thrift/Descriptors.thrift
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: PROTO-REVIEW

#42427 [Doc] update Hive catalog doc based on 3.2.4 release notes
  docs/en/data_source/catalog/hive_catalog.md
  docs/zh/data_source/catalog/hive_catalog.md
Labels: documentation, 3.2

#41982 [BugFix] Fix LDAP authentication bug where empty password can successfully login on AD server
  fe/fe-core/src/main/java/com/starrocks/mysql/security/LdapSecurity.java
Labels: 2.5, 3.0, 3.1, 3.2

#42469 [Doc] No need storage medium for shared-data CN
  docs/en/assets/commonMarkdown/sharedDataCNconf.md
  docs/zh/assets/commonMarkdown/sharedDataCNconf.md
Labels: documentation, 3.1, 3.2

#41675 [Enhancement] Remove partition directory with retry in shared data clusters
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RecycleListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RecyclePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RecyclePartitionInfoV1.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RecyclePartitionInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RecycleRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/persist/DisablePartitionRecoveryInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableCleanerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/RecyclePartitionInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
  test/sql/test_drop_partition/R/test_drop_partition
  test/sql/test_drop_partition/T/test_drop_partition
Labels: 3.1, 3.2, META-REVIEW

#42438 [BugFix] fix query iceberg equality delete parquet file without primary key column
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: 3.2

#42486 [UT] Fix lake data file gc tool
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
Labels: 3.1, 3.2

#42333 [Enhancement] Add fe config enable_legacy_compatibility_for_replication for cross cluster replication
  fe/fe-core/src/main/java/com/starrocks/catalog/AggregateType.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnDef.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TypeTest.java
Labels: 3.1, 3.2

#42499 [Enhancement] Swap the FileMetaData instance directly instead of `move` because the class has no a movable assignment operator.
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/metadata.cpp
Labels: 3.2

#42498 [Doc] Add Partitioned Prefix feature doc
  docs/en/deployment/shared_data/gcs.md
  docs/en/deployment/shared_data/minio.md
  docs/en/deployment/shared_data/s3.md
  docs/en/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
  docs/zh/deployment/shared_data/gcs.md
  docs/zh/deployment/shared_data/minio.md
  docs/zh/deployment/shared_data/other.md
  docs/zh/deployment/shared_data/s3.md
  docs/zh/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.2

#41956 [Enhancement] enhance mv rewrite by considering sort key during selecting best mv
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/BestMvSelector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.1, 3.2

#42454 [BugFix] fix incorrect argument type check
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  test/sql/test_agg/R/test_distinct_agg
  test/sql/test_agg/T/test_distinct_agg
Labels: 3.1, 3.2

#41958 [Enhancement] adaptively enable jit
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_operation.h
  be/src/exprs/binary_predicate.cpp
  be/src/exprs/case_expr.cpp
  be/src/exprs/cast_expr.cpp
  be/src/exprs/compound_predicate.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/expr_context.cpp
  be/src/exprs/jit/ir_helper.h
  be/src/exprs/jit/jit_engine.cpp
  be/src/exprs/jit/jit_engine.h
  be/src/exprs/jit/jit_expr.cpp
  be/src/exprs/jit/jit_expr.h
  be/src/exprs/literal.cpp
  be/src/exprs/literal.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/test/exprs/binary_predicate_test.cpp
  be/test/exprs/case_expr_test.cpp
  be/test/exprs/exprs_test_helper.h
  be/test/exprs/jit_func_cache_test.cpp
  docs/zh/administration/Memory_management.md
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_jit/R/test_arithmetic
  test/sql/test_jit/R/test_fpe
  test/sql/test_jit/R/test_jit_cast
  test/sql/test_jit/R/test_jit_dict
  test/sql/test_jit/R/test_jit_expr
  test/sql/test_jit/T/test_arithmetic
  test/sql/test_jit/T/test_fpe
  test/sql/test_jit/T/test_jit_cast
  test/sql/test_jit/T/test_jit_dict
  test/sql/test_jit/T/test_jit_expr
Labels: documentation, PROTO-REVIEW

#42205 [BugFix] Clear dcg cache for non primary key table when drop_tablet/tablet init(#42203)
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
Labels: 3.1, 3.2

#42551 [Doc] Fix Feedback issue on SHOW MV
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
Labels: documentation, doc-feedback

#42552 [Doc] Fix Nav for Developers
  docs/zh/developers/How_to_Contribute.md
  docs/zh/developers/build-starrocks/handbook.md
  docs/zh/developers/code-style-guides/protobuf-guides.md
  docs/zh/developers/code-style-guides/restful-api-standard.md
  docs/zh/developers/code-style-guides/thrift-guides.md
  docs/zh/developers/development-environment/IDEA.md
  docs/zh/developers/development-environment/ide-setup.md
  docs/zh/developers/trace-tools/Trace.md
Labels: documentation, 3.2

#42500 [Enhancement] opt interleaving probe to avoid bad cases
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/src/simd/simd.h
  be/test/simd/simd_test.cpp
Labels: 3.2

#42450 [Enhancement] Improve StorageAccessException message
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageAccessException.java
  test/sql/test_files/R/test_error
  test/sql/test_files/T/test_error
Labels: 3.1, 3.2

#42547 [BugFix] MultilineOperator neglects runtime filters
  be/src/exec/pipeline/operator.h
  be/src/exec/query_cache/conjugate_operator.cpp
  be/src/exec/query_cache/conjugate_operator.h
  be/src/exec/query_cache/multilane_operator.cpp
  be/src/exec/query_cache/multilane_operator.h
  test/sql/test_multilane_operator_missing_runtime_filter/R/test_multilane_operator_missing_runtime_filter
  test/sql/test_multilane_operator_missing_runtime_filter/T/test_multilane_operator_missing_runtime_filter
Labels: 3.0, 3.1, 3.2

#42557 [Doc] optimize range for data types and provide examples for any_value
  docs/docusaurus/sidebars.json
  docs/en/sql-reference/sql-functions/aggregate-functions/any_value.md
  docs/en/sql-reference/sql-statements/data-types/BIGINT.md
  docs/en/sql-reference/sql-statements/data-types/BINARY.md
  docs/en/sql-reference/sql-statements/data-types/CHAR.md
  docs/en/sql-reference/sql-statements/data-types/DATE.md
  docs/en/sql-reference/sql-statements/data-types/DATETIME.md
  docs/en/sql-reference/sql-statements/data-types/INT.md
  docs/en/sql-reference/sql-statements/data-types/LARGEINT.md
  docs/en/sql-reference/sql-statements/data-types/SMALLINT.md
  docs/en/sql-reference/sql-statements/data-types/STRING.md
  docs/en/sql-reference/sql-statements/data-types/TINYINT.md
  docs/en/sql-reference/sql-statements/data-types/VARCHAR.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/any_value.md
  docs/zh/sql-reference/sql-statements/data-types/BINARY.md
  docs/zh/sql-reference/sql-statements/data-types/CHAR.md
  docs/zh/sql-reference/sql-statements/data-types/DATE.md
  docs/zh/sql-reference/sql-statements/data-types/DATETIME.md
  docs/zh/sql-reference/sql-statements/data-types/LARGEINT.md
  docs/zh/sql-reference/sql-statements/data-types/VARCHAR.md
Labels: documentation, 3.2, doc-feedback

#42517 [BugFix] Reset historical io stats after catch io profile
  be/src/io/io_profiler.cpp
  be/src/io/io_profiler.h
  be/test/io/io_profiler_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#42555 [Enhancement] Remove duplicated http request log
  fe/fe-core/src/main/java/com/starrocks/http/HttpServerHandler.java
Labels: 3.1, 3.2

#40815 [BugFix] Fix observer node recovery bug
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
Labels: 2.5, 3.0, 3.1, 3.2

#42186 [Feature] Support collect Hive histogram statistics
  be/src/runtime/statistic_result_writer.cpp
  be/src/runtime/statistic_result_writer.h
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AnalyzeHistogramDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AnalyzeTypeDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropHistogramStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowHistogramStatsMetaStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalHistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalHistogramStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/test/java/com/starrocks/statistic/AnalyzeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
  test/sql/test_analyze_statistics/R/test_analyze_hive_stats
  test/sql/test_analyze_statistics/R/test_analyze_olap_stats
  test/sql/test_analyze_statistics/T/test_analyze_hive_stats
  test/sql/test_analyze_statistics/T/test_analyze_olap_stats
Labels: META-REVIEW

#42221 [BugFix] Check the return value after load primary index in pk compaction
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#42596 [Enhancement] Specify maven plugin version to avoid download maven-metadata.xml every time
  fe/hive-udf/pom.xml
  fe/spark-dpp/pom.xml
Labels: 3.2

#42563 [BugFix] Use current query's column factory to check whether query's column ref has been rewritten instead of relation's column refs
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
Labels: 3.1, 3.2

#42353 [BugFix] eliminate constant in group by key
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSetType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/EliminateGroupByConstantRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitMultiPhaseAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  test/sql/test_agg/R/test_distinct_agg
  test/sql/test_agg/T/test_distinct_agg
Labels: 3.0, 3.1, 3.2

#42355 [BugFix] fix cloud native pk concurrent partial update issue
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/partial_update_test.cpp
Labels: 3.1, 3.2

#42615 [UT] Fixed the flaky test LakePublishBatchTest.testPublishTableDropped
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.2

#42590 [BugFix] fix bug of FunctionCall doesn't handle child error correctly
  be/src/exprs/function_call_expr.cpp
  test/sql/test_array_fn/R/test_array_fn
Labels: behavior_changed

#42625 [BugFix] Fix olap external table authorization
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
Labels: 3.1, 3.2

#42097 [BugFix] fix resolve partition column failed where create mv (backport #41940)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SlotRefResolver.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: automerge

#42609 [Doc] Add table type comparison
  docs/docusaurus/sidebars.json
  docs/en/table_design/table_types/table_capabilities.md
  docs/zh/table_design/table_types/table_capabilities.md
Labels: documentation, 3.1, 3.2

#42639 [BugFix] Compatible with older version's array in arrayAgg->merge()
  be/src/exprs/agg/array_agg.h
Labels: behavior_changed

#42650 [Doc]Fix broken links in table capabilities
  docs/en/table_design/table_types/table_capabilities.md
  docs/zh/table_design/table_types/table_capabilities.md
Labels: documentation, 3.1, 3.2

#42405 [Doc] add a universal CREATE TABLE sample for window function examples
  docs/en/sql-reference/sql-functions/Window_function.md
  docs/zh/sql-reference/sql-functions/Window_function.md
Labels: documentation, 3.1, 3.2

#42628 [Refactor] Delete warehouse proc related code
  fe/fe-core/src/main/java/com/starrocks/common/proc/ProcService.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Cluster.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/DefaultWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/LocalWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Warehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseInfo.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseProcDir.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SubmitTaskStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/http/ProcWarehousesTest.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseMgrTest.java
Labels: META-REVIEW

#42636 [Enhancement] Add SingleFlight for eliminating redundant work
  be/src/util/bthreads/future.h
  be/src/util/bthreads/single_flight.h
  be/test/CMakeLists.txt
  be/test/util/bthreads/single_flight_test.cpp
Labels: 3.1, 3.2

#42672 [Doc] fix language display of table capabilities
  docs/en/table_design/table_types/table_capabilities.md
  docs/zh/table_design/table_types/table_capabilities.md
Labels: documentation, 3.1, 3.2

#42661 [BugFix] fix not rewrite agg callOperator ref constants
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/EliminateGroupByConstantRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: 3.1, 3.2

#42660 [Enhancement] Remove cachelib library and dependencies to reduce the thirdparty space.
  build.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: 3.1, 3.2

#42656 [BugFix] Delete meaningless error log
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
Labels: 3.1, 3.2

#42516 [Enhancement] Using ORC column id in SearchArgument
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/hdfs_scanner_text.h
  be/src/formats/orc/apache-orc/c++/include/orc/Type.hh
  be/src/formats/orc/apache-orc/c++/include/orc/sargs/SearchArgument.hh
  be/src/formats/orc/apache-orc/c++/src/TypeImpl.cc
  be/src/formats/orc/apache-orc/c++/src/TypeImpl.hh
  be/src/formats/orc/apache-orc/c++/src/sargs/PredicateLeaf.cc
  be/src/formats/orc/apache-orc/c++/src/sargs/PredicateLeaf.hh
  be/src/formats/orc/apache-orc/c++/src/sargs/SearchArgument.cc
  be/src/formats/orc/apache-orc/c++/src/sargs/SearchArgument.hh
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
  be/src/formats/orc/orc_mapping.h
  be/src/formats/orc/utils.h
  be/test/formats/orc/orc_chunk_reader_test.cpp
Labels: 3.0, 3.1, 3.2

#42699 [Doc] Update _DDL.mdx
  docs/en/assets/quick-start/_DDL.mdx
Labels: documentation, 3.0, 3.1, 3.2

#42664 [Doc] Remove param of partition_live_number from column expression partition
  docs/en/table_design/expression_partitioning.md
  docs/zh/table_design/expression_partitioning.md
Labels: documentation, 3.1, 3.2

#42676 [BugFix] fix unique table skip short circuit
  fe/fe-core/src/main/java/com/starrocks/sql/ShortCircuitPlannerHybrid.java
  test/sql/test_spill/R/test_short_circuit_unique
  test/sql/test_spill/T/test_short_circuit_unique
Labels: 3.2

#42721 [Enhancement] enhance mv rewrite by considering sort key during selecting best mv for 3.2 (backport #41956)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/BestMvSelector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: behavior_changed

#42725 [BugFix] revert constant function eq other type bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#42634 [Enhancement] Reorder hive/hudi scan ranges to improve probe sql
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteScanRangeLocationsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DataCachePlanTest.java
Labels: 3.2

#42723 [BugFix] Fix disk metrics bug when partition name does not end with number.
  be/src/util/disk_info.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#42736 [BugFix] Fix streaming aggregate always force streaming in when query memory limit is 0
  be/src/exec/pipeline/pipeline_driver.cpp
Labels: 3.2
