Repository StarRocks/starrocks, pull requests merged in 2024-10, with the labels that each got.

#51244 [Enhancement] refactor array_map's implementation
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/chunk.cpp
  be/src/column/column.cpp
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/nullable_column.h
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_map_expr.cpp
  be/src/exprs/array_map_expr.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/lambda_function.cpp
  be/src/exprs/lambda_function.h
  be/src/exprs/literal.h
  be/src/exprs/map_apply_expr.cpp
  be/test/exprs/lambda_array_expr_test.cpp
  test/sql/test_array/R/test_array_map
  test/sql/test_array/T/test_array_map
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#51589 [Doc] Update index.js
  docs/docusaurus/src/components/Features/index.js
Labels: documentation, 3.1, 3.2, 3.3

#51590 [Doc] fix link
  docs/en/deployment/shared_data/feature-support-shared-data.md
Labels: documentation, 3.1, 3.2, 3.3

#51596 [Doc] Update feature-support-shared-data.md
  docs/zh/deployment/shared_data/feature-support-shared-data.md
Labels: documentation

#51598 [Doc] add keywords
  docs/en/administration/query_profile_overview.md
Labels: documentation, 3.1, 3.2, 3.3

#51609 [Doc] prep for adding CN config info
  docs/en/_assets/commonMarkdown/CN_config_method.md
  docs/en/administration/management/BE_configuration.md
Labels: documentation, 3.2, 3.3

#51091 [BugFix] fix lake compaction compaction sorter bug
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatistics.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatisticsSnapshot.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/Quantiles.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/RandomSorter.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSelector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSorter.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/Selector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/SimpleSelector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/Sorter.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/PartitionStatisticsSnapshotTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/QuantilesTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSorterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/SimpleSelectorTest.java
Labels: 3.2, 3.3

#51617 [BugFix] fix array_map crash
  be/src/exprs/array_map_expr.cpp
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#51625 [BugFix] Disable execution group for partial support colocate join
  fe/fe-core/src/main/java/com/starrocks/planner/ExecGroup.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupExecutionPlanTest.java
Labels: 3.3

#51639 [Doc] keyword
  docs/en/administration/query_profile_overview.md
Labels: documentation, 3.2, 3.3

#51621 [Doc] Fix unit error
  docs/en/table_design/indexes/Bitmap_index.md
Labels: documentation, 3.2, 3.3

#51455 [Enhancement]implement to_days function in FE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2, 3.3

#50417 [Enhancement] improve statistics strategy for insert overwrite
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/listener/GlobalLoadJobListenerBus.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobStatsListener.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/qe/DmlType.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectionTrigger.java
  fe/fe-core/src/main/java/com/starrocks/transaction/InsertOverwriteJobStats.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TableCommitInfo.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobRunnerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/InMemoryStatisticStorage.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectionTriggerTest.java
Labels: 3.3

#51638 [BugFix] Fix bug audit roll num does not work
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.2, 3.3

#51440 [BugFix] Adding dynamic partition failure for one table may block other tables
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/test/java/com/starrocks/clone/DynamicPartitionSchedulerTest.java
Labels: 3.3

#51612 [BugFix] fix cloud native persistent index sst compaction when sst files contain same max_rss_rowid
  be/src/storage/lake/lake_persistent_index.cpp
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
Labels: 3.3

#51673 [Enhancement] A build machine that supports the AVX2 instruction set compiles a package without the AVX2 instruction set.
  build.sh
Labels: 3.1, behavior_changed, 3.2, 3.3

#51647 [BugFix] Fix UnionAll cannot process order by expression
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
Labels: 3.0, 3.1, 3.2, 3.3

#51628 [Enhancement] staros agent listShard does not need replica info
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
Labels: 3.2, 3.3

#51669 [Doc] Update Metabase.md to discourage decimals
  docs/en/integrations/BI_integrations/Metabase.md
Labels: documentation

#51578 [Enhancement] Transform count(distinct pk) into count(pk)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
Labels: behavior_changed

#51684 [Enhancement] Support gc for cloud native persistent index files
  be/src/storage/lake/filenames.h
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
Labels: 3.3

#51704 [UT] Fix unstable mv sql tests
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobMaterializedViewTest.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_the_same_tables
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_the_same_tables
  test/sql/test_transparent_mv/R/test_transparent_mv_mysql
  test/sql/test_transparent_mv/T/test_transparent_mv_mysql
Labels: 3.3

#51697 [Enhancement] Improve files() with wrong credentials error message
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageAccessException.java
  test/sql/test_files/R/test_error
  test/sql/test_files/T/test_error
Labels: behavior_changed, 3.2, 3.3

#51674 [BugFix] Fix split scan rule reuse column id
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/FilterSelectivityEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitScanORToUnionRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SplitScanToUnionTest.java
Labels: 3.1, 3.2, 3.3

#51699 [BugFix] Fix iceberg datacache auto populate failed
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DataCachePopulateRewriteRule.java
Labels: 3.3

#51710 [UT] Fix unstable sql test test_random_distribution.test_select_async_mv
  test/sql/test_random_distribution/R/test_random_distribution
  test/sql/test_random_distribution/T/test_random_distribution
Labels: 3.1, 3.2, 3.3

#51732 [Enhancement] remove useless error logs
  be/src/storage/tablet_updates.cpp
Labels: 3.1, 3.2, 3.3

#51726 [BugFix] Fix incorrect partition name when hash code is negative
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: 3.1, 3.2, 3.3

#51743 [Doc] add document in fe configuration
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.2, 3.3

#51752 [Doc] Fix line 281，2.7s->2.077s
  docs/en/table_design/indexes/Bitmap_index.md
Labels: documentation, 3.2, 3.3

#51748 [BugFix] Fix jdbc catalog change password not effect
  java-extensions/jdbc-bridge/src/main/java/com/starrocks/jdbcbridge/JDBCScanner.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#51614 [Enhancement] Assume --test option in run-be-ut.sh is a single test suite/case name
  run-be-ut.sh
Labels: 3.2, 3.3

#51666 [Doc] Add Compaction for Shared-data
  docs/docusaurus/sidebars.json
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/compaction.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/compaction.md
Labels: documentation, 3.1, 3.2, 3.3

#51661 [Doc] Update Meta Recovery
  docs/en/administration/Meta_recovery.md
  docs/zh/administration/Meta_recovery.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#51453 [Enhancement]implement dayofweek in FE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2, 3.3

#51755 [BugFix] Fix analyzer exception for generated column rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  test/sql/test_materialized_column/R/test_generated_column_rewrite
  test/sql/test_materialized_column/T/test_generated_column_rewrite
Labels: 3.2, 3.3

#51781 [BugFix] When the reserved keyword uses backquotes as input, deserialization causes parseSqlToExpr syntax error, which results in a checkpoint failure.
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/Identifier.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionRangePartitionInfoTest.java
Labels: 3.1, behavior_changed, 3.2

#51764 [BugFix] Don't update datacache metrics after cache select
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
Labels: 3.3

#50120 [Enhancement] Support disable table base compaction by time ranges
  be/src/agent/agent_common.h
  be/src/agent/agent_server.cpp
  be/src/agent/agent_task.cpp
  be/src/agent/agent_task.h
  be/src/storage/CMakeLists.txt
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/src/storage/task/engine_compaction_control_task.cpp
  be/src/storage/task/engine_compaction_control_task.h
  be/test/storage/compaction_manager_test.cpp
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionControlScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentBatchTask.java
  fe/fe-core/src/main/java/com/starrocks/task/CompactionControlTask.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/Types.thrift
  test/sql/test_compaction_cron/R/test_compaction_cron
  test/sql/test_compaction_cron/T/test_compaction_cron
Labels: META-REVIEW, PROTO-REVIEW

#51816 [UT] remove execute_script in UT
  be/test/fs/key_cache_test.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.3

#51613 [BugFix] Fix mysql jdbc incompatible bug
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: 3.3

#51763 [Enhancement] Make some system tables query from leader fe
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeBvarsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeCloudNativeCompactionsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeCompactionsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeConfigsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeDataCacheMetricsTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeLogsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeMetricsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeTabletsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeThreadsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeTxnsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/CharacterSetsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/CollationsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ColumnPrivilegesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ColumnsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/EnginesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/EventsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/FeMetricsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/FeTabletSchedulesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/GlobalVariablesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/KeyColumnUsageSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/LoadTrackingLogsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/LoadsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/MaterializedViewsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PartitionsMetaSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PartitionsSystemTableSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PipeFileSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PipesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ReferentialConstraintsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/RoutineLoadJobsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/RoutinesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/SchemaPrivilegesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/SchemataSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/SessionVariablesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/StatisticsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/StreamLoadsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TableConstraintsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TablePrivilegesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TablesConfigSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TablesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TaskRunsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TasksSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TemporaryTablesTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TriggersSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/UserPrivilegesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/VerboseSessionVariablesSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ViewsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/GrantsTo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/RoleEdges.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeLocks.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeMemoryUsage.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysObjectDependencies.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_routine_load/R/test_commit_offset
  test/sql/test_routine_load/T/test_commit_offset
Labels: 3.2, 3.3

#51709 [BugFix] Fix optimize table fail with special characters
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/test_optimize_table
Labels: 3.2, 3.3

#50873 [Enhancement] Skip tablet schema in rowset meta during ingestion.
  be/src/common/config.h
  be/src/storage/base_tablet.h
  be/src/storage/compaction_task.h
  be/src/storage/data_dir.cpp
  be/src/storage/olap_common.h
  be/src/storage/rowset/rowset_meta.h
  be/src/storage/rowset/rowset_meta_manager.cpp
  be/src/storage/rowset/rowset_meta_manager.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/src/storage/txn_manager.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.2, 3.3

#50627 [Enhancement] Improve DataCache io adaptor
  be/src/block_cache/CMakeLists.txt
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/cache_options.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/datacache_utils.cpp
  be/src/block_cache/datacache_utils.h
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/http/action/update_config_action.cpp
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/cache_select_input_stream.hpp
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/block_cache/datacache_utils_test.cpp
Labels: 3.3

#51828 [BugFix] Fix NullPointerException in getTabletsInHighLoadPath when select tablets to balance
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
Labels: 3.1, 3.2, 3.3

#51857 [Doc] Update Materialized_view.md
  docs/en/using_starrocks/async_mv/Materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3

#51830 [BugFix] fix dataCacheInfo leak in idToDataCacheInfo
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PartitionInfoTest.java
Labels: 3.1, 3.2, 3.3

#51837 [BugFix] Fix wrong physical partition used in fast schema evolution in shared-data mode
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
Labels: 3.3

#51767 [BugFix]fix npe issue for external table
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: 3.2, 3.3

#51723 [BugFix] unify the behavior of default AutoCollector
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
Labels: 3.2, 3.3

#51794 [BugFix] view is not supported by cache select
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DataCacheStmtAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DataCacheStmtAnalyzerTest.java
Labels: 3.3

#51833 [BugFix] fix array_map's error result when inputs are constant
  be/src/exprs/array_map_expr.cpp
  test/sql/test_array_fn/R/test_array_map_2
Labels: 3.2, 3.3

#51670 [Enhancement] delta lake support incremental scan ranges delivery
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadata.java
  fe/fe-core/src/main/java/com/starrocks/planner/DeltaLakeScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstance.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#51677 [BugFix] When the reserved keyword uses backquotes as input, deserialization causes parseSqlToExpr syntax error, which results in log edit failure.
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColumnId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExpressionRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/ColumnIdExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/Identifier.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ExpressionRangePartitionInfoTest.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
Labels: behavior_changed, 3.3

#51835 [BugFix] fix no matching function error in array_contains/array_position
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java
  test/sql/test_array_fn/R/test_array_contains
  test/sql/test_array_fn/T/test_array_contains
Labels: 3.2, 3.3

#51799 [Enhancement] auto change replication_num of system tables
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadsHistorySyncer.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/FileListTableRepo.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoCreator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TableKeeper.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticUtilsTest.java
Labels: behavior_changed, 3.2, 3.3

#51819 [Doc] 3.3.5 Minor Doc Updates
  docs/en/sql-reference/data-types/date-types/DATETIME.md
  docs/en/sql-reference/sql-statements/cluster-management/plan_profile/EXPLAIN.md
  docs/zh/sql-reference/data-types/date-types/DATETIME.md
  docs/zh/sql-reference/sql-statements/cluster-management/plan_profile/EXPLAIN.md
Labels: documentation, 3.3

#51896 [BugFix] Fix add sub partition after table dropped
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.2, 3.3

#51812 [BugFix] fix issue when using placeholder in column position in prepare stmt
  fe/fe-core/src/main/java/com/starrocks/analysis/Parameter.java
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
Labels: 3.3

#51811 [BugFix] fix setDouble issue in jdbc with prepare stmt
  fe/fe-core/src/main/java/com/starrocks/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/LiteralExprCompareTest.java
Labels: 3.3

#51838 [Enhancement] memory tracker for statistics
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
Labels: 3.3

#51832 [BugFix] Upgrade BDBJE to 18.3.20 to fix UnkonwnMasterException
  fe/pom.xml
Labels: 3.3

#51889 [BugFix] Fix BE crash when schema scan rpc failed
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/schema_scanner/schema_variables_scanner.cpp
  test/sql/test_scan/R/test_schema_scan_rpc_failed
  test/sql/test_scan/T/test_schema_scan_rpc_failed
Labels: 3.0, 3.1, 3.2, 3.3

#51905 [BugFix] Fix unknown error when delta lake query's predicate has struct subfield
  fe/fe-core/src/main/java/com/starrocks/connector/delta/ScalarOperationToDeltaLakeExpr.java
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.3

#51890 [BugFix] fix iceberg scan properties
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.3

#51813 [Enhancement] Add some util in script for TDE debug; Fix memleak in wrenbind
  be/src/script/script.cpp
  be/src/storage/lake/rowset.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/thirdparty/wrenbind17/wrenbind17/vm.hpp
  be/test/fs/key_cache_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/lake/tablet_reader_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.3

#51696 [Doc] Update SHOW PROC on replications
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
Labels: documentation, 3.1, 3.2, 3.3

#51662 [Doc] Add a section on StarRocks alert rules and their handling methods
  docs/docusaurus/sidebars.json
  docs/en/_assets/alert_routine_load_tracking.png
  docs/en/_assets/alert_show_proc.png
  docs/en/_assets/alert_show_proc_3.png
  docs/en/_assets/alert_show_statistic.png
  docs/en/_assets/alert_show_statistic_db.png
  docs/en/_assets/alert_show_tablet.png
  docs/en/administration/management/monitoring/alert.md
  docs/zh/_assets/alert_routine_load_tracking.png
  docs/zh/_assets/alert_show_proc.png
  docs/zh/_assets/alert_show_proc_3.png
  docs/zh/_assets/alert_show_statistic.png
  docs/zh/_assets/alert_show_statistic_db.png
  docs/zh/_assets/alert_show_tablet.png
  docs/zh/administration/management/monitoring/alert.md
Labels: documentation, 3.1, 3.2, 3.3

#51921 [Doc] Update Fast Schema Evolution for Shared-data
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
Labels: documentation, 3.3

#51946 [BugFix] fix .net can not read sr
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3

#51949 [Enhancement] Update default replication transaction timeout from 1 hour to 1 day
  docs/en/administration/data_migration_tool.md
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/data_migration_tool.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: documentation, 3.1, behavior_changed, 3.2, 3.3

#51968 [Enhancement] Update default replication transaction timeout from 1 hour to 1 day (backport #51949)
  docs/en/administration/data_migration_tool.md
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/data_migration_tool.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: documentation

#50735 [Doc] Update sql_select_limit system variable doc
  docs/en/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.2, 3.3

#51630 [BugFix] Fix reset ids for restore
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 3.1, 3.2, 3.3

#51982 [Doc] Fix unit error , line 412
  docs/en/table_design/indexes/Bitmap_index.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#51998 [Doc] move keywords
  docs/en/loading/RoutineLoad.md
  docs/en/quick_start/routine-load.md
  docs/zh/loading/RoutineLoad.md
Labels: documentation, 3.1, 3.2, 3.3

#51994 [Refactor] Remove meta context related code
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupMeta.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/io/DeepCopy.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Daemon.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBTool.java
  fe/fe-core/src/main/java/com/starrocks/meta/MetaContext.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BrokerMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/StatisticProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/external/starrocks/TableMetaSyncerTest.java
  fe/fe-core/src/test/java/com/starrocks/ha/BDBHATest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/metablock/SRMetaBlockV1Test.java
  fe/fe-core/src/test/java/com/starrocks/persist/metablock/SRMetaBlockV2Test.java
  fe/fe-core/src/test/java/com/starrocks/privilege/AuthorizationMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoFrontend.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/server/GlobalStateMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedFrontend.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: META-REVIEW

#51515 [Enhancement] Support complex data types (eg. Array/Struct/Map) when get table schema.
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseResult.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/RestBaseResultV2.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/ColumnView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/IndexView.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TablePartitionActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TableSchemaActionTest.java
Labels: META-REVIEW

#51966 [BugFix] fix asan crash in array_map
  be/src/exprs/column_ref.cpp
  be/src/exprs/column_ref.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/lambda_function.cpp
  be/src/exprs/placeholder_ref.h
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#51939 [Enhancement] Loading task should abort transaction if fail because of timeout
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadErrorUtils.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: 3.1, 3.2, 3.3

#52005 [Doc] Set level 4 heading for Alert
  docs/en/administration/management/monitoring/alert.md
  docs/zh/administration/management/monitoring/alert.md
Labels: documentation, 3.1, 3.2, 3.3

#52009 [Doc] Update Replication configurations
  docs/en/administration/data_migration_tool.md
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/data_migration_tool.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3

#51944 [BugFix] Fix incorrect materialized view row count
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
Labels: 3.2, 3.3

#51972 [Enhancement] Support Async delete files from Recycle Bin
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ReplaceLakePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
Labels: 3.3

#52017 [BugFix] Fix mv refresh with multi partition columns ref base tables
  fe/fe-core/src/main/java/com/starrocks/catalog/combinator/AggStateCombinator.java
  fe/fe-core/src/main/java/com/starrocks/catalog/combinator/AggStateMergeCombinator.java
  fe/fe-core/src/main/java/com/starrocks/catalog/combinator/AggStateUnionCombinator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PCell.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PListCell.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PCTRefreshListPartitionOlapTest.java
  test/test_sql_cases.py
Labels: 3.3

#50926 [Enhancement] Add properties excluded_refresh_tables for MaterializedView
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvRefreshArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: 3.3

#52023 [BugFix] fix counter QuerySumMemoryUsage
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
Labels: 3.2, 3.3

#52036 [BugFix] Prevent crash if type mismatch in BinaryDictPageDecoder
  be/src/storage/rowset/binary_dict_page.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#51902 [BugFix] unify the behavior of default AutoCollector (backport #51723)
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
Labels: automerge

#52058 [Enhancement] clang-19 compatibility
  be/src/exprs/agg/array_agg.h
  be/src/exprs/agg/array_union_agg.h
  be/src/exprs/agg/distinct.h
  be/src/storage/chunk_helper.cpp
  be/test/exec/parquet_scanner_test.cpp
Labels: 3.3

#51996 [Enhancement] Skip rebalancing scan ranges for hdfs backend selector by default when using datacache.
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: 3.3

#52038 [Enhancement] table level stats meta support incremental column stats for external table
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowBasicStatsMetaStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalBasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
Labels: META-REVIEW, 3.3

#52032 [Bugfix] Fix incremental scan ranges when scan ranges are bound to pipeline drivers
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/TFragmentInstanceFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstance.java
  test/sql/test_deltalake/R/test_deltalake_scan_ranges
  test/sql/test_deltalake/T/test_deltalake_scan_ranges
  test/sql/test_hive/R/test_hive_scan_ranges
  test/sql/test_hive/T/test_hive_scan_ranges
Labels: title needs [type]

#52020 [Enhancement] reduce the number of fd hold by hash join spilling
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/data_stream.cpp
  be/src/exec/spill/input_stream.h
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/log_block_manager.h
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
Labels: 3.3

#52048 [BugFix] fix running fragment count during exec env exit
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/internal_service.cpp
  be/src/testutil/init_test_env.h
Labels: 3.2, 3.3

#51935 [BugFix] Fix spill cost too much memory when enable group execution
  be/src/exec/spill/mem_table.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#52076 [UT] fix flaky test test_mv_swap
  test/sql/test_materialized_view/R/test_mv_swap
  test/sql/test_materialized_view/T/test_mv_swap
Labels: 3.1, 3.2, 3.3

#52105 [UT] Fix unstable test_mv_refresh_with_event_trigger_and_nested_mvs test case
  test/lib/sr_sql_lib.py
Labels: 3.3

#52080 [Enhancement] add default hash function and dump query resource usage
  be/src/column/column_hash.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/exec/pipeline/exchange/sink_buffer.h
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exprs/ngram.cpp
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/local_pass_through_buffer.h
  be/src/runtime/sender_queue.h
  be/src/util/hash.h
Labels: 3.0, 3.1, 3.2, 3.3

#52111 [Enhancement] Enhance thread pool configs of backup restore
  be/src/agent/agent_server.cpp
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/Backup_and_restore.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/Backup_and_restore.md
Labels: documentation, 3.1, behavior_changed, 3.2, 3.3

#50962 [BugFix] Fix dict_mapping expression crash caused by multiple open in ExprContext::clone
  be/src/exprs/dict_query_expr.cpp
  test/sql/test_dict_mapping_function/R/test_dict_mapping_function
  test/sql/test_dict_mapping_function/T/test_dict_mapping_function
Labels: 3.2, 3.3

#52070 [BugFix] support trigger individual cloud native index compaction
  be/src/storage/CMakeLists.txt
  be/src/storage/compaction_utils.h
  be/src/storage/lake/cloud_native_index_compaction_task.cpp
  be/src/storage/lake/cloud_native_index_compaction_task.h
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.3

#52029 [BugFix] fix lake compaction threads not exit properly
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
Labels: 3.2, 3.3

#52149 [Enhancement] ConsolidateLikesRule yields non-optimized predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ConsolidateLikesRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithMultiLikeTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#52151 [BugFix] Fix rows and bytes rate statistic in routine load
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/PulsarRoutineLoadJobTest.java
Labels: 3.2, 3.3

#50875 [BugFix] Setting max_compaction_concurrency to -1/0 via dynamic parameter is not as expected.
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/src/storage/olap_server.cpp
  be/test/storage/compaction_manager_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/resource_management/Memory_management.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/resource_management/Memory_management.md
Labels: documentation, 3.1, 3.2, 3.3

#52119 [Enhancement] Fix known XSS vulnerabilities
  .trivyignore
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/http/action/LogAction.java
  fe/fe-core/src/main/java/com/starrocks/http/action/QueryProfileAction.java
  fe/fe-core/src/main/java/com/starrocks/http/action/SystemAction.java
  fe/fe-core/src/test/java/com/starrocks/http/LogActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/QueryProfileActionTest.java
  fe/pom.xml
Labels: 3.2, 3.3

#52074 [BugFix] Fix online optimize conflict with expression partition
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterOpType.java
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/OnlineOptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/test_optimize_table
Labels: 3.3

#46402 [BugFix] Fix physical partition for rebalance
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/test/java/com/starrocks/clone/DiskAndTabletLoadReBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/PartitionUtilsTest.java
Labels: 3.2, 3.3

#52176 [BugFix] fix array_map asan crash
  be/src/exprs/lambda_function.cpp
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.3

#51701 [Enhancement][Refactor] optimize array_contains_all/array_contains_seq function
  be/src/column/column_helper.cpp
  be/src/column/column_helper.h
  be/src/exprs/array_functions.h
  be/src/exprs/array_functions.tpp
  be/src/util/bit_mask.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_contains
  test/sql/test_array_fn/T/test_array_contains
Labels: 3.2, 3.3

#52085 [Doc] Fix EN CREATE INDEX reference
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_INDEX.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#52208 [UT] Remove unstable drop task test
  test/sql/test_task/R/test_drop
Labels: 3.3

#52163 [Doc] Update System_limit.md - remove column name changes mention
  docs/en/sql-reference/System_limit.md
Labels: documentation

#52125 [BugFix] dictionary_get did not support third params for materialized view
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DictionaryGetExpr.java
Labels: 3.2, 3.3

#52077 [Enhancement] Support backup restore for logical view
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/Status.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/View.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/CatalogMocker.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/UnitTestUtil.java
Labels: behavior_changed, 3.3

#51728 [BugFix]Avoid printing token in be log
  be/src/agent/heartbeat_server.cpp
  be/src/agent/heartbeat_server.h
  be/test/agent/heartbeat_server_test.cpp
Labels: 3.2, 3.3

#52233 [Doc] Optimize Description for array_contains_seq
  docs/en/sql-reference/sql-functions/array-functions/array_contains_seq.md
  docs/zh/sql-reference/sql-functions/array-functions/array_contains_seq.md
Labels: documentation, 3.3

#52202 [Doc] Separate FILES() into loading and unloading
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.3

#52078 [Doc] Update list_partitioning.md
  docs/en/table_design/data_distribution/list_partitioning.md
  docs/zh/table_design/data_distribution/list_partitioning.md
Labels: documentation, 3.3

#52241 [Doc] 3.3.5 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#52240 [Doc] 3.2.12 release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#52239 [BugFix] Remove query sync mv read lock
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
Labels: 3.3

#51992 [BugFix] Consider CN number in HashJoinCostModel.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q21.sql
Labels: 3.2, 3.3

#52123 [BugFix] informationschema.task_runs timezone fix
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TaskRunsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeFileRecord.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: 3.2, 3.3

#52168 [Enhancement] only call getAliveComputeNodes once per OlapScanNode
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseManagerTest.java
Labels: 3.2, 3.3

#52263 [BugFix] Reset replication number for partition info to let the restored partitions use the given value
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 3.1, 3.2, 3.3

#52279 [Doc] Forbid https in endpoint address
  docs/zh/sql-reference/sql-statements/loading_unloading/BROKER_LOAD.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#52231 [BugFix] Always check memory limit during preload segment
  be/src/storage/tablet_updates.cpp
  be/src/storage/update_manager.cpp
Labels: 3.2, 3.3

#52297 [Doc] Update REFRESH_EXTERNAL_TABLE.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/REFRESH_EXTERNAL_TABLE.md
Labels: documentation, 3.3

#52120 [Enhancement] Disable optimize table on auto bucket table
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/test_optimize_table
Labels: behavior_changed, 3.2, 3.3

#52285 [Doc] Forbid https in GCS endpoint
  docs/en/administration/management/Backup_and_restore.md
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
  docs/zh/administration/management/Backup_and_restore.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#52258 [BugFix] Fix tablet meta use tabletMeta uses partition_id and physical_partition_id at the same time to cause confusion
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletMeta.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/com/starrocks/consistency/CheckConsistencyJob.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/persist/ConsistencyCheckInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/BinlogConsumeStateVO.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TempPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
Labels: 3.2, 3.3

#52301 [BugFix] Fix cancel optimize table fail
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/test_optimize_table
Labels: 3.2, 3.3

#52210 [BugFix] Fix materialized columns in files() query plan
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ImportColumnDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/load/BrokerFileGroupTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/StreamLoadScanNodeTest.java
  test/sql/test_files/R/csv_format
  test/sql/test_files/T/csv_format
Labels: 3.2, 3.3

#52288 [Enhancement] Support push down avg aggregate function in mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateFunctionRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewPushDownRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/common/AggregatePushDownUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/AggregatePushDownContext.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewAggPushDownRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  test/sql/test_materialized_view/R/test_materialized_view_agg_pushdown_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_agg_pushdown_rewrite
Labels: 3.3

#52332 [Doc] Add Flink connector release notes 1.2.10
  docs/en/ecosystem_release/flink_connector.md
  docs/zh/ecosystem_release/flink_connector.md
Labels: documentation

#52293 [Enhancement] Add count_distinct_implementation/enable_count_distinct_rewrite_by_hll_bitmap to control count distinct's implmentation
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RewriteContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/BitmapRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/HLLRewriteEquivalent.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_materialized_view_rewrite_count_distinct
  test/sql/test_materialized_view/T/test_materialized_view_rewrite_count_distinct
Labels: 3.3

#52329 [Doc] Fix typo of resource group
  docs/en/administration/management/resource_management/resource_group.md
  docs/zh/administration/management/resource_management/resource_group.md
Labels: documentation, 3.3

#52213 [Enhancement] Support TCP Keep-Alive on MySQL connections
  docs/en/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlServer.java
Labels: documentation, behavior_changed, 3.3

#52335 [BugFix] fix kudu timestamp data reading issue
  java-extensions/kudu-reader/src/main/java/com/starrocks/kudu/reader/KuduColumnValue.java
  java-extensions/kudu-reader/src/main/java/com/starrocks/kudu/reader/KuduScannerUtils.java
Labels: 3.3

#52340 [Doc] remove excess links
  docs/en/sql-reference/sql-statements/Catalog/SHOW_CREATE_CATALOG.md
Labels: documentation, 3.3

#52343 [Doc] remove link
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_BACKENDS.md
Labels: documentation, 3.3

#52315 [Doc] Refine Description for csv.skip_header
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.3

#52346 [Doc] Brokerless doc update
  docs/en/sql-reference/sql-statements/loading_unloading/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/BROKER_LOAD.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#52253 [Doc] Update data_migration_tool.md
  docs/en/administration/data_migration_tool.md
  docs/zh/administration/data_migration_tool.md
Labels: documentation, 3.1, 3.2, 3.3

#52342 [BugFix] Fix partition column sequence is incorrect when delta lake with multi partition columns
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/FileScanTask.java
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.3

#52230 [Enhancement] Upgrade async-profiler to 3.0
  build.sh
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
  thirdparty/build-thirdparty.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.3
