Repository StarRocks/starrocks, pull requests merged in 2024-12, with the labels that each got.

#53115 [Doc] Add 3.3.7 Release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#53363 [Enhancement] interrupt sleep when cancel query
  be/src/exprs/utility_functions.cpp
  be/test/exprs/utility_functions_test.cpp
Labels: 3.2, 3.3, 3.4

#53391 [BugFix] Fix ctas & insert into select with multi level partition table
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FeNameFormat.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnDef.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  test/sql/test_automatic_partition/R/test_multi_expr
  test/sql/test_automatic_partition/T/test_multi_expr
Labels: 3.4

#53394 [BugFix] Fix alter mv with excluded_refresh_tables bug
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: 3.3, 3.4

#53403 [BugFix] Fix wrong plan in max(count(distinct)) when enable lowcardinality
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53428 [UT] update unstable UT
  test/sql/test_low_cardinality/R/test_low_cardinality_array
  test/sql/test_low_cardinality/T/test_low_cardinality_array
Labels: 3.3, 3.4

#53421 [Enhancement] add tuning guides to query profile
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/OperatorTuningGuides.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanTuningAdvisor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  test/sql/test_feedback/R/test_feedback
  test/sql/test_feedback/T/test_feedback
Labels: 3.4

#53423 [UT] Fix unstable case for restoreJob
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.3, 3.4

#53442 [Doc] Update Architecture.md
  docs/en/introduction/Architecture.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53443 [Doc] Update Architecture.md
  docs/zh/introduction/Architecture.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53429 [Enhancement] Improve the message of ERR_NO_FILES_FOUND
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
Labels: 3.2, 3.3, 3.4

#53432 [Enhancement] add optimized query count to show_plan_advisor
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/OperatorTuningGuides.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanAdvisorExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanTuningAdvisor.java
  fe/fe-core/src/test/java/com/starrocks/qe/feedback/analyzer/PlanTuningAnalyzerTest.java
Labels: 3.4

#53474 [BugFix] Release the starcache instance before the block cache instance being destructed to avoid some unexpected issues when stopping.
  be/src/block_cache/block_cache.cpp
Labels: 3.3, 3.4

#53235 [BugFix] fix partition min/max prune with null-value partitions
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PartitionColumnMinMaxRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
  test/sql/test_list_partition/R/test_list_partition_minmax
  test/sql/test_list_partition/T/test_list_partition_minmax
Labels: 3.2, 3.3, 3.4

#53499 [Doc] PDF generation
  docs/PDFoutput/.gitignore
  docs/docusaurus/Dockerfile
  docs/docusaurus/PDF/.gitignore
  docs/docusaurus/PDF/README.md
  docs/docusaurus/PDF/URLS.txt.example
  docs/docusaurus/PDF/docker-compose.yaml
  docs/docusaurus/PDF/generatePdf.js
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
  docs/zh/administration/management/management.mdx
  docs/zh/administration/management/resource_management/resource_management.mdx
  docs/zh/cover_pages/batch_loading_integration.mdx
  docs/zh/cover_pages/deployment_preparation.mdx
  docs/zh/cover_pages/developers.mdx
  docs/zh/cover_pages/ide_tools.mdx
  docs/zh/cover_pages/loading_kafka.mdx
  docs/zh/cover_pages/loading_spark.mdx
  docs/zh/cover_pages/manage_deployment.mdx
  docs/zh/cover_pages/performance_tuning.mdx
  docs/zh/cover_pages/query_acceleration.mdx
  docs/zh/cover_pages/shared_data_deployment.mdx
  docs/zh/cover_pages/shared_nothing_deployment.mdx
  docs/zh/deployment/shared_data/shared_data.mdx
  docs/zh/integrations/loading_tools/loading_tools_integration.mdx
  docs/zh/integrations/streaming/apache_kafka.mdx
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53447 [Doc] Add System Variable enable_filter_unused_columns_in_scan_stage
  docs/en/administration/data_migration_tool.md
  docs/zh/administration/data_migration_tool.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53157 [Doc] Update zh and en doc about CloudCanal(BladePipe)
  docs/en/_assets/3.11-1.png
  docs/en/_assets/3.11-2.png
  docs/en/_assets/3.11-3.png
  docs/en/_assets/3.11-4.png
  docs/en/_assets/3.11-5.png
  docs/en/_assets/3.11-6.png
  docs/en/_assets/3.11-7.png
  docs/en/_assets/3.11-8.png
  docs/en/integrations/loading_tools/CloudCanal.md
  docs/zh/_assets/3.11-1.png
  docs/zh/_assets/3.11-2.png
  docs/zh/_assets/3.11-3.png
  docs/zh/_assets/3.11-4.png
  docs/zh/_assets/3.11-5.png
  docs/zh/_assets/3.11-6.png
  docs/zh/_assets/3.11-7.png
  docs/zh/_assets/3.11-8.png
  docs/zh/integrations/loading_tools/CloudCanal.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53477 [Doc] Fix Wrong Example in Bitmap Index
  docs/en/table_design/indexes/Bitmap_index.md
  docs/zh/table_design/indexes/Bitmap_index.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53498 [Doc] Fixed SHOW DATA command syntax in documentation.
  docs/en/sql-reference/sql-statements/Database/SHOW_DATA.md
Labels: documentation

#52889 [Enhancement] support common expr reuse strategy on scan predicates
  be/src/exec/pipeline/select_operator.cpp
  be/src/exec/pipeline/select_operator.h
  be/src/exec/select_node.cpp
  be/src/exec/select_node.h
  fe/fe-core/src/main/java/com/starrocks/planner/SelectNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Operator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/TableScanPredicateExtractor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PullUpScanPredicateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OnPredicateMoveAroundRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/ScanPredicateExprReuseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithCaseWhenTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PredicatePushDownTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/RemoveAggTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsSQLTest.java
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  fe/fe-core/src/test/resources/sql/subquery/scalar-subquery.sql
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW, 3.3

#53407 [Enhancement] Add runtime cpu flags check
  be/src/common/daemon.cpp
  be/src/util/cpu_info.cpp
  be/src/util/cpu_info.h
  be/test/CMakeLists.txt
  be/test/gutil/cpu_test.cc
  be/test/util/cpu_info_test.cpp
Labels: 3.3, 3.4

#53413 [BugFix] fix incorrect error info for state of DeltaWriter
  be/src/storage/delta_writer.cpp
Labels: 3.3, 3.4

#53469 [BugFix] Repair GC logic for shared-data persistent index while multi-disk is used for storage
  be/src/storage/lake/local_pk_index_manager.cpp
  be/src/storage/lake/local_pk_index_manager.h
  be/test/storage/lake/local_pk_index_manager_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#53473 [BugFix] Fix column pruning for mv transparent union rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
Labels: 3.3, 3.4

#53536 [BugFix] Fix restore job mistake use error partition id bug
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.4

#53470 [UT] Fix unstable test case
  test/sql/test_low_cardinality/R/test_low_cardinality_array
  test/sql/test_low_cardinality/T/test_low_cardinality_array
Labels: 3.3, 3.4

#53534 [BugFix] Cases with only one-stage local agg don't need to be processed
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/skeleton/SkeletonBuilder.java
Labels: 3.4

#53422 [BugFix] Add warehouse column in show load
  fe/fe-core/src/main/java/com/starrocks/common/proc/LoadProcDir.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowLoadStmtTest.java
Labels: behavior_changed, 3.3, 3.4

#53548 [BugFix]Dictionary drop operations and refresh operations collide, resulting in inconsistent metadata.
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
Labels: 3.3, 3.4

#53519 [Doc] Add SQL Digest Doc
  docs/en/administration/sql_digest.md
  docs/zh/administration/sql_digest.md
Labels: documentation, 3.3, 3.4

#53532 [Doc] Revert Batch Drop Partitions (backport #49056)
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation

#53537 [Enhancement] Record builded tuning guide to query profile
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/OperatorTuningGuides.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanTuningAdvisor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
Labels: 3.4

#53555 [Enhancement] external table adaptation feedback
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/skeleton/ScanNode.java
  test/sql/test_feedback/R/test_external_table_join_feedback
  test/sql/test_feedback/T/test_external_table_join_feedback
Labels: 3.4

#53513 [BugFix] fix feedback when checking if a tuning guide needs to be generated
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/analyzer/StreamingAggTuningAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/qe/feedback/analyzer/PlanTuningAnalyzerTest.java
  test/sql/test_feedback/R/test_agg_feedback
  test/sql/test_feedback/R/test_join_feedback
  test/sql/test_feedback/T/test_agg_feedback
  test/sql/test_feedback/T/test_join_feedback
Labels: 3.4

#53056 [Enhancement] Use dynamic batch size for simdjson to parse multiple json document
  be/src/common/config.h
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/test/exec/json_parser_test.cpp
Labels: behavior_changed, 3.3, 3.4

#53546 [Doc] Add docker version description
  docs/en/developers/build-starrocks/Build_in_docker.md
  docs/zh/developers/build-starrocks/Build_in_docker.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53586 [Enhancement] Use dynamic batch size for simdjson to parse multiple json document (backport #53056)
  be/src/common/config.h
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/test/exec/json_parser_test.cpp
Labels: behavior_changed

#53594 [UT] Fix test_range_predicate_rewrite test
  test/sql/test_materialized_view/R/test_range_predicate_rewrite
  test/sql/test_materialized_view/T/test_range_predicate_rewrite
Labels: 3.3, 3.4

#53600 [UT] Remove noisy fe ut messages
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateSyncMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RuntimeFilterTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobPrimaryKeyTest.java
  fe/fe-core/src/test/java/com/starrocks/benchmark/MVPartitionCompensateOptBench.java
  fe/fe-core/src/test/java/com/starrocks/benchmark/MvPreProcessorWithSSBBench.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MysqlSchemaResolverTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunFIFOQueueTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.4

#53564 [BugFix] Fix transaction stream load lock leak
  be/src/http/action/transaction_stream_load.cpp
  be/src/http/action/transaction_stream_load.h
  be/test/http/transaction_stream_load_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#53606 [UT] fix unstable backup restore case
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobPrimaryKeyTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.4

#53623 [Doc] Use axios
  docs/docusaurus/Dockerfile
  docs/docusaurus/PDF/README.md
  docs/docusaurus/PDF/docker-compose.yaml
  docs/docusaurus/PDF/generatePdf.js
Labels: documentation

#53632 [UT] fix TestPipelineControlFlow
  be/test/exec/pipeline/pipeline_test_base.cpp
Labels: 3.3, 3.4

#53618 [Enhancement] Add candidate tuning guide to profile for easy troubleshooting
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ApplyTuningGuideRule.java
  test/sql/test_feedback/R/test_join_feedback
  test/sql/test_feedback/T/test_join_feedback
Labels: 3.4

#53634 [BugFix] Fix Left Anti join null_array UAF
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.tpp
  test/sql/test_join/R/test_null_aware_anti_join
  test/sql/test_join/T/test_null_aware_anti_join
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53603 [UT] Eliminate overuse projecting CommonAccessPaths
  fe/fe-core/src/main/java/com/starrocks/planner/ScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/EliminateOveruseColumnAccessPathRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/OveruseColumnAccessPathTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ComplexTypePrunePlanTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53622 [Enhancement] support async list hive partitions
  fe/fe-core/src/main/java/com/starrocks/connector/AsyncTaskQueue.java
  fe/fe-core/src/main/java/com/starrocks/connector/GetRemoteFilesParams.java
  fe/fe-core/src/main/java/com/starrocks/connector/HMSPartitionBasedRemoteInfoSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/HMSPartitionBasedRemoteInfoSourceTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteFileOperationsTest.java
Labels: 3.4

#53651 [UT] fix unstable test_mv_refresh_with_mv_reuse case
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_mv_reuse
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_mv_reuse
Labels: 3.4

#53614 [BugFix] Add lock to prevent concurrency issue in committed_rs_map
  be/src/storage/tablet.cpp
  be/src/storage/txn_manager.cpp
Labels: 3.2, 3.3, 3.4

#52790 [Enhancement] Support the conversion from json to struct.
  be/src/exprs/CMakeLists.txt
  be/src/exprs/cast_expr.cpp
  be/src/exprs/cast_expr.h
  be/src/exprs/cast_expr_struct.cpp
  be/test/exprs/cast_expr_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  test/sql/test_cast/R/test_cast_json_to_struct
  test/sql/test_cast/T/test_cast_json_to_struct
Labels: 3.2, 3.3

#53612 [Enhancement] Add metrics for thread pools used by agent tasks and compaction
  be/src/agent/agent_server.cpp
  be/src/storage/compaction_manager.cpp
  be/src/util/starrocks_metrics.h
  be/test/util/starrocks_metrics_test.cpp
Labels: 3.2, 3.3, 3.4

#53658 [BugFix] Use latest collects stats job columns as stats meta columns
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalBasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
Labels: 3.4

#53642 [Refactor] Remove PBackendService
  be/src/exec/dictionary_cache_writer.h
  be/src/exec/tablet_sink_index_channel.h
  be/src/gen_cpp/CMakeLists.txt
  be/src/http/action/metrics_action.h
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_sender.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/service/service_be/internal_service.cpp
  be/src/service/service_be/internal_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/segment_replicate_executor.h
  be/src/storage/table_reader.cpp
  be/src/util/brpc_stub_cache.h
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
Labels: PROTO-REVIEW

#53656 [BugFix] fix partial update failure due to column name case
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UpdateStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/UpdatePlanTest.java
  test/sql/test_partial_update_column_mode/R/test_upper_case_partial_update
  test/sql/test_partial_update_column_mode/T/test_upper_case_partial_update
Labels: 3.2, 3.3, 3.4

#53660 [BugFix] Fix ExecuteOption may change task's taskRunProperties bug
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
Labels: 3.2, 3.3, 3.4

#51883 [Feature] Support inet_aton function
  be/src/common/format_ip.h
  be/src/exprs/CMakeLists.txt
  be/src/exprs/inet_aton.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/inet_aton.md
  docs/zh/sql-reference/sql-functions/string-functions/inet_aton.md
  gensrc/script/functions.py
Labels: documentation

#53661 [Enhancement] short circuit optimization on `select limit` case (on FE side)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/FeExecuteCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/AllAtOnceExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/PhasedExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/StartSchedulingTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ShortCircuitTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.4

#53696 [Enhancement] BE cancels the create tablet task if it has already timed out
  be/src/agent/agent_task.cpp
  be/src/agent/finish_task.cpp
  be/test/agent/agent_task_test.cpp
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  gensrc/thrift/AgentService.thrift
Labels: 3.2, PROTO-REVIEW, 3.3, 3.4

#53708 [Enhancement] improve error message of killed sql
  fe/fe-core/src/main/java/com/starrocks/common/util/SqlUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
Labels: 3.2, 3.3, 3.4

#53706 [BugFix] CastOperator skips predicate pushdown for KuduConnector
  fe/fe-core/src/main/java/com/starrocks/connector/kudu/KuduPredicateConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/kudu/KuduPredicateConverterTest.java
Labels: 3.3, 3.4

#53739 [UT] fix unstable test_mv_refresh_with_mv_reuse case
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_mv_reuse
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_mv_reuse
Labels: 3.4

#49748 [Doc] Chenge aws.s3.endpoint to aws.s3.region
  docs/en/administration/Query_planning.md
  docs/en/administration/management/Backup_and_restore.md
  docs/zh/administration/Query_planning.md
  docs/zh/administration/management/Backup_and_restore.md
Labels: documentation, 3.1, 3.2, 3.3

#53756 [UT] Fix DeadLockTest test5 UT unstable
  fe/fe-core/src/test/java/com/starrocks/common/lock/DeadLockTest.java
Labels: 3.3, 3.4

#53683 [UT] fix concurrent-safety of AlterMaterializedViewTest.testMVOnMVReload
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Daemon.java
Labels: 3.2, 3.3, 3.4

#53780 [BugFix] Fix files() load counter NPE in coordinator
  fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java
Labels: 3.1

#53676 [BugFix] Fix or split to scan lose partition predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitScanORToUnionRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SplitScanToUnionTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53738 [Doc] Revise Backup Restore according to feedback
  docs/en/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/en/table_design/data_distribution/list_partitioning.md
  docs/zh/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/list_partitioning.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53814 [BugFix] Fix sync mv rewrite bug with where expression in shared data mode
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  test/sql/test_lake_sync_mv/R/test_lake_sync_mv_rewrite
  test/sql/test_lake_sync_mv/T/test_lake_sync_mv_rewrite
Labels: 3.4

#53820 [UT][BugFix] avoid sharing sub column with input columns in map_apply
  be/src/exprs/map_apply_expr.cpp
Labels: 3.2, 3.3, 3.4

#53821 [BugFix] fix error message for parquet DATA_PAGE_V2
  be/src/formats/parquet/column_chunk_reader.cpp
Labels: 3.2, 3.3, 3.4

#53809 [BugFix]Memory leak for insert load job.
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
Labels: 3.3, 3.4

#53058 [BugFix] fix missing query metrics
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.3, 3.4

#53748 [BugFix] Support Iceberg multi level namespace and vended-credentials
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/OAuth2SecurityConfig.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/OAuth2SecurityProperties.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/SecurityEnum.java
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergTableSink.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/rest/OAuth2SecurityConfigTest.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
Labels: 3.4

#53834 [Doc] Supplement 3.3.7 Release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#53854 [Doc] Update current.json
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#53835 [BugFix] fix ComputeNode status after upgraded from an old version
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
Labels: 3.4

#53766 [Feature] Support query deletion vector for delta lake
  be/src/connector/CMakeLists.txt
  be/src/connector/deletion_vector/deletion_vector.cpp
  be/src/connector/deletion_vector/deletion_vector.h
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/util/CMakeLists.txt
  be/src/util/base85.cpp
  be/src/util/base85.h
  be/test/CMakeLists.txt
  be/test/connector/deletion_vector/deletion_vector_test.cpp
  be/test/util/base85_test.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/FileScanTask.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/ScanFileUtils.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_deltalake/R/test_deltalake_dv
  test/sql/test_deltalake/T/test_deltalake_dv
Labels: PROTO-REVIEW

#53792 [BugFix] Fix cannot insert into overwrite a hive partition when files are written by hive
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveWriteUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveWriteUtilsTest.java
Labels: 3.2, 3.3, 3.4

#53860 [Enhancement] Make region is optional in iceberg rest catalog vended credentials
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
Labels: documentation

#53822 [BugFix] Fix random bucket partition can not be compactioned issue
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/MetaUtilTest.java
Labels: 3.4

#53878 [BugFix] fix lock release issue in cloud native pk table
  be/src/storage/lake/update_manager.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#53848 [Enhancement] Support PredicateTree for parquet page index
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/scalar_column_reader.cpp
  be/src/formats/parquet/scalar_column_reader.h
  be/src/formats/parquet/zone_map_filter_evaluator.h
  be/src/storage/rowset/segment_iterator.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/formats/parquet/page_index_test.cpp
Labels: 3.4

#53863 [Enhancement] smooth the jemalloc memory fragmentation
  be/src/common/config.h
  be/src/common/daemon.cpp
Labels: 3.2, 3.3, 3.4

#53811 [BugFix] Fix show table status not check view privilege
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/starrocks_intellij_style.xml
  test/sql/test_rbac/R/test_view_privilege
  test/sql/test_rbac/T/test_view_privilege
Labels: 3.3, 3.4

#53574 [Doc] Add Desc of max_automatic_partition_number
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53714 [Doc] Add meaning of 0 for variables
  docs/en/administration/management/resource_management/query_queues.md
  docs/en/sql-reference/System_variable.md
  docs/zh/administration/management/resource_management/query_queues.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53742 [Doc] Change dict_mapping parameter
  docs/en/sql-reference/sql-functions/dict-functions/dict_mapping.md
  docs/zh/sql-reference/sql-functions/dict-functions/dict_mapping.md
Labels: documentation, 3.2, 3.3, 3.4

#53289 [Enhancement] Refine the error message when creating a mv for iceberg catalog
  docs/en/using_starrocks/Materialized_view-single_table.md
  docs/en/using_starrocks/async_mv/Materialized_view.md
  docs/zh/using_starrocks/Materialized_view-single_table.md
  docs/zh/using_starrocks/async_mv/Materialized_view.md
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: documentation, 3.4

#53735 [Enhancement] Add histogram metric and node info metric in json metric
  fe/fe-core/src/main/java/com/starrocks/metric/JsonMetricVisitor.java
Labels: 3.1, 3.2, 3.3, 3.4

#53013 [Feature] support analyze predicate columns
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_analyze_status.cpp
  be/src/exec/schema_scanner/schema_analyze_status.h
  be/src/exec/schema_scanner/schema_column_stats_usage_scanner.cpp
  be/src/exec/schema_scanner/schema_column_stats_usage_scanner.h
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  fe/fe-core/src/main/java/com/starrocks/analysis/TableName.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/AnalyzeStatusSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ColumnStatsUsageSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TableKeeper.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AnalyzeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Projection.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeStatus.java
  fe/fe-core/src/main/java/com/starrocks/statistic/NativeAnalyzeStatus.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/ColumnFullId.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/ColumnUsage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/PredicateColumnsMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/PredicateColumnsStorage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/TableNamePredicate.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
  fe/fe-core/src/test/java/com/starrocks/statistic/columns/ColumnUsageTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/columns/PredicateColumnsStorageTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_analyze_statistics/R/test_predicate_columns
  test/sql/test_analyze_statistics/T/test_predicate_columns
Labels: META-REVIEW, PROTO-REVIEW

#53922 [Doc] 3.2.13 Release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#53901 [BugFix] Fix list files when no files were found
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  test/sql/test_files/R/csv_format
  test/sql/test_files/T/csv_format
Labels: 3.4

#53928 [Doc] Add meaning of 0 for variables (backport #53714)
  docs/en/administration/management/resource_management/query_queues.md
  docs/en/sql-reference/System_variable.md
  docs/zh/administration/management/resource_management/query_queues.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.1, 3.2, 3.3

#53898 [Enhancement] Optimize the Chunk destructor
  be/src/util/phmap/phmap.h
Labels: 3.4

#53925 [BugFix] Fix log block not record disks requested from the DirManager
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/file_block_manager.h
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/log_block_manager.h
  be/test/io/spill_block_manager_test.cpp
Labels: 3.3, 3.4

#53382 [Enhancement] Append LIST partition info when list table partitions by rest api.
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/PartitionInfoView.java
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TablePartitionActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/PartitionUtilsTest.java
Labels: META-REVIEW

#53864 [Enhancement] Optimize LoadsHistorySyncer
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadsHistorySyncer.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
Labels: 3.3, 3.4

#53951 [BugFix]The OP_DROP_TABLE_V2 event is not triggered when an error is reported for dropping a materialized view.
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
Labels: 3.3, 3.4

#53926 [BugFix] Add insert_max_filter_ratio value check
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableVarConverters.java
  test/sql/test_files/R/test_insert_properties
  test/sql/test_files/T/test_insert_properties
Labels: 3.4

#53940 [Enhancement] Improve query queue pending timeout error message
  fe/fe-core/src/main/java/com/starrocks/qe/QueryQueueManager.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
Labels: behavior_changed, 3.4

#53921 [Feature] bulk load optimization (Part 1 - block manager)
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/load_spill_block_manager.cpp
  be/src/storage/lake/load_spill_block_manager.h
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/src/storage/lake/spill_mem_table_sink.h
  be/test/CMakeLists.txt
  be/test/storage/lake/load_spill_block_manager_test.cpp
Labels: behavior_changed

#49349 [BugFix] When replica enter decommission, transaction will nerver complete.
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#53981 [Doc] 3.1.16 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#53825 [Doc] Add zh Desc to UDF isolation
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53985 [BugFix] Fix avro bytes type to json
  be/src/formats/avro/binary_column.cpp
  be/test/exec/avro_scanner_test.cpp
  be/test/exec/test_data/avro_scanner/avro_basic_schema.json
Labels: 3.3, 3.4

#53866 [BugFix] Fix dynamic overwrite replay & gc fail
  fe/fe-core/src/main/java/com/starrocks/common/util/RangeUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/persist/CreateInsertOverwriteJobLog.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  test/sql/test_dynamic_overwrite/R/test_overwrite
  test/sql/test_dynamic_overwrite/T/test_overwrite
Labels: 3.4

#53850 [Enhancement] Add cluster idle HTTP api
  fe/fe-core/src/main/java/com/starrocks/alter/AlterHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataExecutor.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/IdleAction.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoExecutor.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanAdvisorExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunFIFOQueue.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/util/CustomizedQueryExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HyperStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/IdleStatus.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseIdleChecker.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  test/sql/test_warehouse/R/test_idle_status
  test/sql/test_warehouse/T/test_idle_status
Labels: 3.2, 3.3, 3.4

#44297 [BugFix] Report exception when the java udf was error
  be/src/exprs/java_function_call_expr.cpp
  test/sql/test_udf/R/test_jvm_udf
  test/sql/test_udf/T/test_jvm_udf
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3, 3.4

#53994 [Doc] Fix an error in ALTER_STORAGE_VOLUME document
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/ALTER_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/ALTER_STORAGE_VOLUME.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#54021 [Doc] Fix Misleading Desc in GRANT and REVOKE
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
  docs/en/sql-reference/sql-statements/account-management/REVOKE.md
  docs/zh/sql-reference/sql-statements/account-management/GRANT.md
  docs/zh/sql-reference/sql-statements/account-management/REVOKE.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53759 [Enhancement] reduce min/max counters from query profile
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/test/util/runtime_profile_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/Counter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  gensrc/thrift/RuntimeProfile.thrift
Labels: PROTO-REVIEW, 3.3, 3.4

#53847 [BugFix] Fix show cloud native sync materialized views
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
Labels: 3.4

#54026 [Enhancement] remove the nonsense fragmentation tracker
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
Labels: 3.2, 3.3, 3.4

#54030 [Doc] Files() supports NAS
  docs/en/loading/loading_introduction/feature-support-loading-and-unloading.md
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/unloading/unload_using_insert_into_files.md
  docs/zh/loading/loading_introduction/feature-support-loading-and-unloading.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/unloading/unload_using_insert_into_files.md
Labels: documentation, 3.4

#53893 [BugFix] Fix stream load backend/frontend streaming
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/ShowStreamLoadTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: 3.3, 3.4

#54044 [BugFix] Fix query error when delta lake using shallow clone
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaConnectorScanRangeSource.java
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.3, 3.4

#54057 [Enhancement] add io metric for deletion vector
  be/src/connector/deletion_vector/deletion_vector.cpp
  be/src/connector/deletion_vector/deletion_vector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/group_reader.cpp
Labels: 3.4

#53967 [Enhancement] Support struct subfield zonemap filter in parquet reader
  be/src/formats/parquet/complex_column_reader.cpp
  be/src/formats/parquet/complex_column_reader.h
  be/src/formats/parquet/zone_map_filter_evaluator.h
  be/test/formats/parquet/file_reader_test.cpp
Labels: 3.4

#54029 [BugFix] Add more checks for pk table apply retry
  be/src/storage/storage_engine.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
Labels: 3.2, 3.3, 3.4

#54058 [Enhancement] Use insert into target colum when collecting statistics
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalHistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HyperStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/SampleInfo.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsSQLTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#54061 [BugFix] Fix commit transaction not in write lock in replication job
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
Labels: 3.1, 3.2, 3.3, 3.4

#54041 [BugFix] Fix jni scanner call update_materialized_columns with case sensitive
  be/src/exec/jni_scanner.cpp
Labels: 3.3, 3.4

#54065 [Enhancement] skip replica which in error state
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/test/java/com/starrocks/catalog/LocalTabletTest.java
Labels: 3.2, 3.3, 3.4

#54083 [BugFix] Fix struct subfield zonemap filter failed
  be/src/formats/parquet/complex_column_reader.cpp
Labels: 3.4

#54075 [Enhancement] update staros to 3.4-rc2
  be/CMakeLists.txt
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  thirdparty/starlet-artifacts-version.sh
Labels: 3.4

#54113 [BugFix] Fix wrong physical partition id in colocate table balancer
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
Labels: 3.4

#54118 [Doc] Add documents for datacache SLRU eviction policy.
  docs/en/administration/management/BE_configuration.md
  docs/en/data_source/data_cache.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/data_source/data_cache.md
Labels: documentation, 3.4

#54130 [UT] Fix BE failed UT
  be/src/storage/tablet_updates.cpp
Labels: 3.2, 3.3, 3.4

#54081 [BugFix] Set has delete for tables replicated by the starrocks data migration tool
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
Labels: 3.1, 3.2, META-REVIEW, 3.3, 3.4

#54073 [Enhancement] Disable optimize table with partition description change
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: behavior_changed, 3.4

#54127 [BugFix] Fix query error for delta lake when column mapping mode use upper-case
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaUtils.java
  test/sql/test_deltalake/R/test_deltalake_column_mapping
  test/sql/test_deltalake/T/test_deltalake_column_mapping
Labels: 3.3, 3.4

#54069 [Enhancement] skip PK table apply state preload when memory usage high
  be/src/common/config.h
  be/src/storage/delta_writer.cpp
  be/src/storage/lake/delta_writer.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: behavior_changed, 3.2, 3.3, 3.4

#54121 [UT] Add test for warehouse idle checker
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/IdleAction.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseIdleChecker.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/lake/AlterJobV2HookTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest2.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseIdleCheckerTest.java
  test/sql/test_warehouse/R/test_idle_status
  test/sql/test_warehouse/T/test_idle_status
Labels: 3.2, 3.3, 3.4

#54080 [BugFix] correct field `memCostBytes` in AuditLog
  fe/fe-core/src/main/java/com/starrocks/common/util/AuditStatisticsUtil.java
Labels: 3.2, 3.3, 3.4

#54114 [Doc] Update note for BE label
  docs/en/administration/management/resource_management/be_label.md
  docs/zh/administration/management/resource_management/be_label.md
Labels: documentation, 3.2, 3.3, 3.4

#54152 [Enhancement] release the query queue slots asap (backport #54032)
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
Labels: automerge

#54129 [Doc] Update documents to add some configurations and functions related to datacache.
  docs/en/administration/management/BE_configuration.md
  docs/en/data_source/data_cache.md
  docs/en/data_source/data_cache_observe.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/data_source/data_cache.md
  docs/zh/data_source/data_cache_observe.md
Labels: documentation, 3.4

#54124 [BugFix] Fix LockManager remove waiter not check own state bug
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
Labels: 3.3, 3.4

#54122 [Enhancement] Support aws.glue.catalog_id parameters
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/MetastoreClientUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/glue/util/MetastoreClientUtilsTest.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/credential/CloudConfigurationConstants.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/iceberg/IcebergAwsClientFactory.java
Labels: 3.4

#54173 [Enhancement] Ignore ShowStmt for idle check
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.2, 3.3, 3.4

#54195 [BugFix] Fix query error for delta lake with is null filter
  fe/fe-core/src/main/java/com/starrocks/connector/delta/ScalarOperationToDeltaLakeExpr.java
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.3, 3.4

#54197 [BugFix] Fix replaceColumnRef bug (backport #53476)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ReplaceColumnRefRewriter.java
Labels: automerge

#54190 [Enhancement] Load and Export add warehouse parameter
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.3, 3.4

#54177 [Enhancement] Eliminate sort column when all predicates of the column are equivalent predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/EliminateSortColumnWithEqualityPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/EliminateSortColumnWithEqualityPredicateTest.java
  fe/fe-core/src/test/resources/sql/optimized-plan/window.sql
Labels: 3.4

#54204 [BugFix] Fix query error for delta lake partitioned table with column mapping
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/ScanFileUtils.java
  test/sql/test_deltalake/R/test_deltalake_column_mapping
  test/sql/test_deltalake/T/test_deltalake_column_mapping
Labels: 3.3, 3.4

#53862 [Enhancement] support collecting array/map type column statistics
  be/src/runtime/statistic_result_writer.cpp
  be/src/runtime/statistic_result_writer.h
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/main/java/com/starrocks/statistic/base/CollectionTypeColumnStats.java
  fe/fe-core/src/main/java/com/starrocks/statistic/base/ColumnClassifier.java
  fe/fe-core/src/main/java/com/starrocks/statistic/base/ColumnStats.java
  fe/fe-core/src/main/java/com/starrocks/statistic/base/SubFieldColumnStats.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/ConstQueryJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/FullQueryJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/HyperQueryJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/HyperStatisticSQLs.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/MetaQueryJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/ColumnSampleManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsMetaMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsSQLTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/hyper/HyperJobTest.java
  gensrc/thrift/Data.thrift
  test/sql/test_refresh_statistics/R/test_clear_stats
  test/sql/test_refresh_statistics/T/test_clear_stats
Labels: PROTO-REVIEW

#52858 [Enhancement] Support analyze paimon table and optimize query execution
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalPaimonScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/UtilsTest.java
Labels: 3.2, 3.3, 3.4

#53973 [Feature] bulk load optimization (Part 2 - SpillMemTableSink)
  be/src/common/config.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/load_spill_block_manager.cpp
  be/src/storage/lake/load_spill_block_manager.h
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/src/storage/lake/spill_mem_table_sink.h
  be/src/storage/memtable.cpp
  be/src/storage/memtable.h
  be/src/storage/memtable_flush_executor.cpp
  be/src/storage/memtable_flush_executor.h
  be/src/storage/memtable_rowset_writer_sink.h
  be/src/storage/memtable_sink.h
  be/test/CMakeLists.txt
  be/test/storage/lake/load_spill_block_manager_test.cpp
  be/test/storage/lake/spill_mem_table_sink_test.cpp
  be/test/storage/memtable_flush_executor_test.cpp
Labels: behavior_changed

#54182 [BugFix] fix char padding missing after partial update
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/tablet_updates.cpp
  test/sql/test_stream_load/R/test_partial_update_with_char
  test/sql/test_stream_load/T/test_partial_update_with_char
Labels: 3.1, 3.2, 3.3, 3.4

#54216 [Enhancement] support lake_clear_corrupted_cache option for BE
  be/src/common/config.h
  be/src/storage/lake/tablet_manager.cpp
Labels: 3.3, 3.4
