Repository StarRocks/starrocks, pull requests merged in 2024-07, with the labels that each got.

#47573 [BugFix] Fix create dictionary fail if the dictionary table is from external catalog
  fe/fe-core/src/main/java/com/starrocks/catalog/Dictionary.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/planner/DictionaryCacheSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DictionaryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowDictionaryStmt.java
  test/lib/sr_sql_lib.py
Labels: behavior_changed, META-REVIEW, 3.3

#47332 [Refactor] add a config to ignore rpc overcrowded problem
  be/src/common/config.h
  be/src/exec/dictionary_cache_writer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/service/brpc.h
  be/src/storage/segment_replicate_executor.cpp
Labels: title needs [type]

#47674 [UT] Fix unstable UT: ColocateTableBalancerTest.testSystemStable
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.1, 3.2, 3.3

#47664 [UT] add lake pk deterministic test
  be/src/testutil/deterministic_test_utils.h
  be/test/CMakeLists.txt
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
  be/test/storage/persistent_index_consistency_test.cpp
Labels: 3.3

#47572 [Enhancement] Avoid using tablet schema map in cross cluster replication
  be/src/storage/tablet_meta.cpp
  be/src/storage/tablet_meta.h
Labels: 3.1, 3.2, 3.3

#47685 [UT] add debug log for ColocateTableBalancerTest
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.1, 3.2, 3.3

#47633 [Enhancement] Support Dictionary on compute node
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DictionaryMgrTest.java
Labels: 3.3

#47402 [Enhancement] lazy initialization external catalg
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorContext.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/LazyConnector.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/delta/DeltaLakeConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/unified/UnifiedConnectorTest.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogMgrTest.java
Labels: 3.3

#47594 [Enhancement] adjust lake compaction history output
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
Labels: documentation, behavior_changed, 3.2, 3.3

#47639 [BugFix] didn't catch the exception in getAuthorizationInfo
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
  fe/fe-core/src/test/java/com/starrocks/http/BadHttpRequestTest.java
Labels: 3.1, 3.2, 3.3

#47706 [UT] add debug log for ColocateBalanceTest
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.1, 3.2, 3.3

#45493 [Enhancement] Collect routine load committed and aborted tasks number metric
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/metric/TableMetricsEntity.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: 3.3

#47713 [Doc] change search ranking for partition
  docs/en/data_source/catalog/catalog_intro.mdx
  docs/en/table_design/Data_distribution.md
  docs/en/table_design/expression_partitioning.md
  docs/zh/data_source/catalog/catalog_intro.mdx
  docs/zh/table_design/Data_distribution.md
  docs/zh/table_design/indexes/Bitmap_index.md
  docs/zh/table_design/list_partitioning.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#47700 [BugFix] Fix ast to sql exception when writing audit log
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  test/sql/test_files/R/test_error
  test/sql/test_files/T/test_error
  test/sql/test_files/orc_format/map_decimal_date.lz4.orc
Labels: 3.2, 3.3

#47675 [BugFix] forbid low cardinality optimization when cast string col to array<string>
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
  test/sql/test_low_cardinality/R/test_low_cardinality_array
  test/sql/test_low_cardinality/T/test_low_cardinality_array
Labels: 3.3

#47726 [UT] Fix colocate balancer ut
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.1, 3.2, 3.3

#47593 [Enhancement] Support date_trunc with week granularity for asychronized materialized view
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionFunctionChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_date_trunc_week
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_date_trunc_week
Labels: 3.3

#47738 [BugFix] Fix replaying task run bug
  fe/fe-core/src/main/java/com/starrocks/scheduler/Constants.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskTest.java
Labels: 3.1, 3.2, 3.3

#47667 [BugFix] Fix aggregate rewrite lose predicate
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/EliminateAggRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
Labels: 3.3

#47701 [BugFix] Fix follower cannot hit mv after altering table
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
Labels: 3.3

#46913 [Enhancement] Reduce getAliveComputeNodes call to reduce rpc call
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseManagerTest.java
Labels: 3.3

#47144 [Enhancement] Retry apply after apply failed.
  be/src/common/config.h
  be/src/common/status.h
  be/src/storage/olap_server.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/src/storage/update_manager.h
  be/src/testutil/init_test_env.h
  be/test/storage/tablet_updates_test.cpp
Labels: behavior_changed, 3.2, 3.3

#47714 [BugFix] Reject rename col which is referenced in rollup
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
Labels: 3.1, 3.2, 3.3

#47737 [BugFix] fix bug of profile crash on ASAN
  be/src/exec/pipeline/operator.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
  test/sql/test_profile/R/test_profile
  test/sql/test_profile/T/test_profile
  test/sql/test_profile/T/test_profile_analysis.sh
Labels: 3.3

#47744 [Enhancement] adjust lake compaction history output (backport #47594)
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
Labels: documentation

#47760 [Enhancement] Set session variable enable_stats_to_optimize_skew_join to false
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveTPCHPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCHPlanWithCostTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCHPlanWithHistogramCostTest.java
Labels: 3.2, 3.3

#47728 [Enhancement] support user variable in analytic function
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/UserVariableExpr.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ExprUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectHintTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  test/sql/test_hint/R/test_hint
  test/sql/test_hint/T/test_hint
Labels: 3.2, 3.3

#47702 [Enhancement] Support column access privilege for Ranger
  conf/ranger/ranger-servicedef-starrocks.json
  fe/fe-core/src/main/java/com/starrocks/privilege/AccessController.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ColumnPrivilege.java
  fe/fe-core/src/main/java/com/starrocks/privilege/NativeAccessController.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ranger/hive/RangerHiveAccessController.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ranger/starrocks/RangerStarRocksAccessController.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: behavior_changed, 3.2, 3.3

#47732 [BugFix] Fix match of source ip for resource group
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupClassifier.java
  fe/fe-core/src/main/java/com/starrocks/common/util/NetUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ResourceGroupClassifierTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/NetUtilsTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47796 [BugFix] Fix parse Mysql Client Protocol COM_CHANGE_USER with conn_attr error bug
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlChangeUserPacket.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlChangeUserPacketTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47811 [BugFix] Ensure proxy result buffer is not null if it's proxy
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.1

#47779 [Doc]Update jdbc_catalog.md
  docs/zh/data_source/catalog/jdbc_catalog.md
Labels: documentation, 3.2, 3.3

#47771 [Doc] Rename chart repo to starrocks
  docs/en/deployment/helm.md
  docs/en/ecosystem_release/starrocks-kubernetes-operator.md
  docs/en/quick_start/helm.md
  docs/zh/deployment/helm.md
  docs/zh/ecosystem_release/starrocks-kubernetes-operator.md
Labels: documentation

#47780 [Doc]Update jdbc_catalog.md
  docs/en/data_source/catalog/jdbc_catalog.md
Labels: documentation, 3.2, 3.3

#47711 [BugFix] fix several correctness issues about cloud native pk index
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/sstable/iterator.h
  be/src/storage/sstable/iterator_wrapper.h
  be/src/storage/sstable/merger.cpp
  be/src/storage/sstable/options.h
  be/src/storage/sstable/two_level_iterator.cpp
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.3

#47798 [Enhancement] Optimize array_sortby for multi key columns
  be/src/column/array_column.h
  be/src/exec/sorting/sort_column.cpp
  be/src/exec/sorting/sort_helper.h
  be/src/exec/sorting/sort_permute.cpp
  be/src/exec/sorting/sort_permute.h
  be/src/exec/sorting/sorting.h
  be/src/exprs/array_functions.cpp
  test/sql/test_array_fn/R/test_array_fn
  test/sql/test_array_fn/R/test_array_sortby
  test/sql/test_array_fn/T/test_array_fn
  test/sql/test_array_fn/T/test_array_sortby
Labels: 3.3

#47759 [BugFix] Fix unknown error of 'ANALYZE PROFILE FROM xx' sql
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.3

#47452 [Enhancement] Defense catalog inconsistent with connector
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
Labels: 3.3

#47839 [UT] Fix EncryptionKeyTest.ConstructorWithPB ASAN
  be/test/fs/key_cache_test.cpp
Labels: 3.3

#47826 [BugFix] Fix duplicated column unique id in adding column when upgraded to 3.3 than downgraded to 3.2 for shared-data mode
  be/src/storage/metadata_util.cpp
  be/src/storage/rowset/segment.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
Labels: 3.1

#47801 [BugFix] Fix user admin role can modify root password bug
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterUserStmtTest.java
Labels: 3.1, 3.2, 3.3

#47837 [UT] Add enable_mv_refresh_insert_strict config and fix mv unstable test cases
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/CachedPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/DefaultTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/HivePartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/IcebergPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/JDBCPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/OlapPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/PaimonPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiffer.java
  fe/fe-core/src/test/java/com/starrocks/benchmark/MvRefreshConcurrencyTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorJdbcTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_multi_union2
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_multi_union2
Labels: 3.3

#47858 [Enhancement] ignore untracked gen_cpp cmake-build files
  .gitignore
Labels: 3.3

#47829 [Doc] Clarify hybrid row-column storage support on shared-data
  docs/en/table_design/hybrid_table.md
  docs/zh/table_design/hybrid_table.md
Labels: documentation, 3.2, 3.3

#47849 [BugFix] fix cast invalid negative largeint to datetime error
  be/src/exprs/cast_expr.cpp
  test/sql/test_cast/R/test_cast_to_datetime
  test/sql/test_cast/T/test_cast_to_datetime
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47845 [BugFix] Fix Delete table Statement mistake check select privilege bug in ColumnPrivilege
  conf/ranger/ranger-servicedef-starrocks.json
  fe/fe-core/src/main/java/com/starrocks/privilege/AccessController.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ColumnPrivilege.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ranger/hive/RangerHiveAccessController.java
  fe/fe-core/src/main/java/com/starrocks/privilege/ranger/starrocks/RangerStarRocksAccessController.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.2, 3.3

#47775 [BugFix] Bump simdjson to 3.9.4 and Fix struct field columns inconsistent when loading from bad json
  be/src/formats/json/numeric_column.cpp
  be/src/formats/json/struct_column.cpp
  be/test/formats/json/map_column_test.cpp
  be/test/formats/json/numeric_column_test.cpp
  be/test/formats/json/struct_column_test.cpp
  thirdparty/vars.sh
Labels: 3.2, 3.3

#47541 [BugFix] Uninstalling StarRocks Cluster is stuck in k8s
  docker/dockerfiles/be/cn_entrypoint.sh
Labels: 3.1, 3.2, 3.3

#47873 [BugFix] Fix HivePartitionTraits get table name error for hive resource table
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/HivePartitionTraits.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorPartitionTraitsTest.java
Labels: 3.2, 3.3

#47666 [BugFix] fix query stuck issue in spill restore phase
  be/CMakeLists.txt
  be/src/exec/spill/spiller.hpp
Labels: 3.3

#47835 [Enhancement] Make mv default resource group configurable and add default_mv_resource_group_concurrency_limit
  be/src/common/config.h
  be/src/exec/workgroup/work_group.cpp
  be/src/exec/workgroup/work_group.h
  be/src/http/action/update_config_action.cpp
Labels: 3.1, 3.2, 3.3

#47833 [BugFix] Fix replayBatchDeleteReplica failed when doing checkpoint
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/persist/BatchDeleteReplicaInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.1, 3.2, META-REVIEW, 3.3

#47648 [Enhancement] Support mv rewrite when select only with mv's group by key
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateFunctionRollupUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
Labels: 3.3

#47800 [Enhancement] add retry to hive getPartitionColumnStats
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetaClientTest.java
Labels: 3.1, 3.2, 3.3

#47850 [Doc] Add new example to parse_json
  docs/en/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
  docs/zh/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#47201 [Feature] Support regexp_split function
  be/src/exprs/CMakeLists.txt
  be/src/exprs/regexp_split.cpp
  be/src/exprs/regexp_split.h
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/regexp_split.md
  docs/zh/sql-reference/sql-functions/string-functions/regexp_split.md
  gensrc/script/functions.py
Labels: documentation

#47920 [BugFix] Fix mv with hudi catalog base rewrite bug
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessNonPartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowMaterializedViewStatus.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  test/sql/test_materialized_view/R/test_range_predicate_rewrite
  test/sql/test_materialized_view/T/test_range_predicate_rewrite
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_hudi_catalog
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_hudi_catalog
Labels: 3.3

#47918 [Doc] Fix typo in Create Index Page
  docs/en/sql-reference/sql-statements/data-definition/CREATE_INDEX.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#47832 [Doc] Add desc for BE config primary_key_limit_size
  docs/en/administration/management/BE_configuration.md
  docs/en/table_design/table_types/primary_key_table.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/table_design/table_types/primary_key_table.md
Labels: documentation, 3.1, 3.2, 3.3

#47921 [Doc] Add Boundary to Shared-data and Rename Block Cache to Data Cache
  docs/docusaurus/sidebars.json
  docs/en/administration/management/BE_configuration.md
  docs/en/deployment/shared_data/competence_boundary-shared-data.md
  docs/en/release_notes/release-3.2.md
  docs/en/release_notes/release-3.3.md
  docs/en/using_starrocks/block_cache.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/deployment/shared_data/competence_boundary-shared-data.md
  docs/zh/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.3.md
  docs/zh/using_starrocks/block_cache.md
Labels: documentation, 3.1, 3.2, 3.3

#47695 [Doc] Add docs for MV Default Resource Group
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/resource_management/resource_group.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/resource_management/resource_group.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
Labels: documentation, 3.1, 3.2, 3.3

#47865 [BugFix] fix ngram_search crash
  be/src/storage/column_predicate_rewriter.cpp
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: 3.3

#47960 [Doc] Rename chart repo to starrocks (backport #47771)
  docs/en/deployment/helm.md
  docs/zh/deployment/helm.md
  docs/zh/ecosystem_release/starrocks-kubernetes-operator.md
Labels: documentation

#47528 [BugFix] Fix delete index file failed when destory VerticalRowsetWriter after compaction
  be/src/storage/rowset/rowset_writer.cpp
  be/test/storage/base_compaction_test.cpp
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: 3.3

#47861 [BugFix] Fix the problem that table creation fails when the default value of a…
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#47949 [Refactor] Optimize infer bucket policy avoid to generate too few bucket num
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogUtilsTest.java
Labels: behavior_changed

#47980 [BugFix] Remove broker thirdparty jars copy
  fs_brokers/apache_hdfs_broker/build.sh
Labels: 3.2

#47981 [BugFix] Remove broker thirdparty jars copy
  fs_brokers/apache_hdfs_broker/build.sh
Labels: 3.1

#47809 [Enhancement] optimize the performance of refreshExternalTable stage of MV refresh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TableSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshNonPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
Labels: 3.1, 3.2, 3.3

#47864 [BugFix] [Refactor] Trigger to refresh related mvs after replacing temp partitions if base table is a mv
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/listener/GlobalLoadJobListenerBus.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobStatsListener.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_event_trigger_and_nested_mvs
Labels: 3.1, 3.2, 3.3

#47797 [Feature] List Partition For AMV(Part 3): Support nullable partition columns for list partition table/materialized view
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ListPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionValue.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PCTRefreshListPartitionOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_list_partitions_with_nullable
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_list_partitions_with_nullable
Labels: 3.3

#47983 [UT] Fix unstable mv sql tester tests
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  test/sql/test_materialized_view/R/test_create_mv_with_params
  test/sql/test_materialized_view/R/test_materialized_view_incremental_refresh_on_hive
  test/sql/test_materialized_view/R/test_mv_partition_compensate_hive
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/R/test_mv_partition_union_rewrite_mode_iceberg
  test/sql/test_materialized_view/T/test_create_mv_with_params
  test/sql/test_materialized_view/T/test_materialized_view_incremental_refresh_on_hive
  test/sql/test_materialized_view/T/test_mv_partition_compensate_hive
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/T/test_mv_partition_union_rewrite_mode_iceberg
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_list_partitions_basic
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_hudi_catalog
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_list_partitions_basic
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_hudi_catalog
  test/sql/test_transparent_mv/R/test_transparent_mv_iceberg_part1
  test/sql/test_transparent_mv/R/test_transparent_mv_iceberg_part2
  test/sql/test_transparent_mv/R/test_transparent_mv_union_iceberg
  test/sql/test_transparent_mv/T/test_transparent_mv_iceberg_part1
  test/sql/test_transparent_mv/T/test_transparent_mv_iceberg_part2
  test/sql/test_transparent_mv/T/test_transparent_mv_union_iceberg
Labels: 3.3

#47036 [Feature] Support vector index meta
  be/src/storage/metadata_util.cpp
  be/src/storage/tablet_index.cpp
  be/test/CMakeLists.txt
  be/test/storage/metadata_util_test.cpp
  be/test/storage/tablet_index_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/analysis/BloomFilterIndexUtil.java
  fe/fe-core/src/main/java/com/starrocks/analysis/InvertedIndexUtil.java
  fe/fe-core/src/main/java/com/starrocks/analysis/VectorIndexUtil.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Index.java
  fe/fe-core/src/main/java/com/starrocks/catalog/IndexParams.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/InvertedIndexParams.java
  fe/fe-core/src/main/java/com/starrocks/common/NgramBfIndexParamsKey.java
  fe/fe-core/src/main/java/com/starrocks/common/VectorIndexParams.java
  fe/fe-core/src/main/java/com/starrocks/common/io/ParamsKey.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/IndexDef.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/GINIndexTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/VectorIndexTest.java
  gensrc/proto/tablet_schema.proto
  gensrc/thrift/Descriptors.thrift
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_vector_index/R/test_vector_index
  test/sql/test_vector_index/T/test_vector_index
Labels: behavior_changed, PROTO-REVIEW

#47993 [Enhancement] Remove jindo sdk from broker
  fs_brokers/apache_hdfs_broker/build.sh
  fs_brokers/apache_hdfs_broker/src/pom.xml
Labels: 3.1, 3.2, 3.3

#47984 [Doc] Replace aws.s3.region with aws.s3.endpoint in Paimon Catalog
  docs/en/data_source/catalog/paimon_catalog.md
  docs/zh/data_source/catalog/paimon_catalog.md
Labels: documentation, 3.1, 3.2, 3.3

#47964 [Doc] Rename chart repo to starrocks (backport #47771)
  docs/en/deployment/helm.md
  docs/en/quick_start/helm.md
  docs/zh/deployment/helm.md
  docs/zh/ecosystem_release/starrocks-kubernetes-operator.md
Labels: documentation

#47742 [Enhancement] support archive task run history
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoExecutor.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TableKeeper.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/ArchiveTaskRunsLog.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: META-REVIEW, 3.3

#47842 [BugFix] fix exp returns incorrect value
  be/src/exprs/math_functions.cpp
  be/test/exprs/math_functions_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47974 [BugFix] Fix logical tablet internal parallel SIGFPE
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/storage/rowset/segment_group.cpp
  be/src/storage/rowset/segment_group.h
  test/sql/test_tablet_internal_parallel/R/test_logical_split
  test/sql/test_tablet_internal_parallel/T/test_logical_split
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47975 [BugFix] return empty list in case of MV optimizer failure
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.2, 3.3

#47310 [BugFix] Disallow auto conversion for the cols of Non-OLAP table that's being created from double/float to decimal type in CTAS
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
Labels: 3.2, 3.3

#48042 [BugFix] Fix the problem that table creation fails when the default value of a…(backport #47861)
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: behavior_changed

#48021 [BugFix]copy no_cast_column to reuse _result_chunk of jdbcScanner
  be/src/exec/jdbc_scanner.cpp
  be/src/exprs/clone_expr.h
Labels: 3.2, 3.3

#48048 [BugFix] Fix the problem that table creation fails when the default value of a…(backport #47861)
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: behavior_changed

#48034 [BugFix] Fix HudiPartitionTraits get table name error for hudi resource table
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/HudiPartitionTraits.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorPartitionTraitsTest.java
Labels: 3.2, 3.3

#48000 [BugFix] Fix missing set execution id in user variable var
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  test/sql/test_user_variables/R/test_user_variable
  test/sql/test_user_variables/T/test_user_variable
Labels: 3.2, 3.3

#48013 [BugFix] fix wrong result type of TemporaryTableMgr.getAllTemporaryTables
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/server/TemporaryTableMgrTest.java
Labels: 3.3

#48060 [Enhancement] Remove useless log of persistent index
  be/src/storage/persistent_index.cpp
Labels: 3.2, 3.3

#48065 [UT] use its own name for each test suite
  fe/fe-core/src/test/java/com/starrocks/alter/OnlineOptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
Labels: 3.2, 3.3

#48070 [Doc] Add FQDN to shared-data quick start
  docs/en/quick_start/shared-data.md
Labels: documentation, 3.1, 3.2, 3.3

#47946 [Enhancement] support upsert/delete mix transaction rebuild in cloud native pk index
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/persistent_index_memtable.cpp
  be/src/storage/lake/update_manager.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW, 3.3

#47632 [Feature] Support kill query by query_id
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/KillStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/KillStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/KillQueryHandleTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW

#48001 [BugFix] Fix NPE due to MvRewriteContext not correctly initialized
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewPushDownRewriter.java
Labels: 3.3

#47791 [Enhancement] Limit err msg size if there is an exception when converting JSON when loading
  be/src/util/json_converter.cpp
  be/test/formats/json/nullable_column_test.cpp
  test/common/data/stream_load/sr_invalid_json.json
  test/sql/test_json/R/test_invalid_json
  test/sql/test_json/T/test_invalid_json
Labels: 3.3

#48087 [BugFix] Add aliyun and ks3 jar in broker pom
  fs_brokers/apache_hdfs_broker/src/broker-core/pom.xml
Labels: 3.2

#48088 [BugFix] Add aliyun and ks3 jar in broker pom
  fs_brokers/apache_hdfs_broker/src/broker-core/pom.xml
Labels: 3.1

#47118 [Enhancement] Enable spill by default for connector sink
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
Labels: behavior_changed, 3.3

#48020 [BugFix] fix ViewScan nullable column
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
Labels: 3.2, 3.3

#47838 [BugFix] Fix automatic partition hang when open timeout is too long exhausted automatic partition rpc thread pool
  be/src/common/config.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/runtime/exec_env.cpp
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.1, behavior_changed, 3.2, 3.3

#45666 [Enhancement] Optimize creating table using a shared initial tablet metadata between tablets in shared-data mode
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/filenames.h
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/metadata_iterator.cpp
  be/src/storage/lake/metadata_iterator.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/vacuum.cpp
  be/src/storage/task/engine_batch_load_task.cpp
  be/test/storage/lake/starlet_location_provider_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
  gensrc/thrift/AgentService.thrift
Labels: PROTO-REVIEW, 3.3

#47320 [BugFix] Fix be crash caused by uncaught future_error exception
  be/src/storage/lake/vacuum.cpp
Labels: 3.1, 3.2, 3.3

#48110 [UT]fix test case
  test/sql/test_cast/R/test_cast_to_datetime
  test/sql/test_cast/T/test_cast_to_datetime
Labels: 3.0, 3.1

#48096 [Enhancement] Enable spill by default for connector sink (backport #47118)
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
Labels: behavior_changed

#47852 [Refactor] Add max_bucket_number_per_partition limit to partition table
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CreateTableAnalyzerTest.java
Labels: behavior_changed

#48106 [UT] [BugFix] Trigger to refresh related mvs when base tables has deleted rows
  fe/fe-core/src/main/java/com/starrocks/listener/GlobalLoadJobListenerBus.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobStatsListener.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_list_partitions_with_nullable
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_delete
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_list_partitions_with_nullable
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_delete
Labels: 3.1, 3.2, 3.3

#48050 [BugFix] Change the default datacache disk path to avoid directory creation failure due to permission issues.
  be/src/block_cache/cache_options.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/disk_space_monitor.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
Labels: 3.3

#48146 [BugFix] Fix possible dead lock in LoadJobStatsListener
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
Labels: 3.1, version:3.2.9

#48130 [BugFix] Fix not catching strong references to chunks sorter causing BE crash
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/pipeline/spill_process_operator.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#48056 [BugFix] Fix incorrect connection state update when register/unregister conn
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#48051 [BugFix] Fix escape character in default value
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: behavior_changed

#48113 [UT] Fix unstable mv sql tests
  test/sql/test_materialized_view/R/test_create_mv_with_params
  test/sql/test_materialized_view/T/test_create_mv_with_params
Labels: 3.1

#48090 [Enhancement] Change show memory format for show dictionary
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DictionaryMgrTest.java
Labels: behavior_changed, 3.3

#48143 [BugFix] Fix bug of dropping temporary table if exists
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TemporaryTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.3

#48193 [Doc] Add 3.2.9 Release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#48185 [Doc] Add Extra Downgrade note
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#48190 [BugFix] get_json_xx return same column ptr
  be/src/exprs/json_functions.cpp
Labels: 3.3

#48180 [BugFix] Fix concurrent execute let rewrite failed
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateProjectRule.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#47862 [Feature] Add array function of array_repeat
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/test/exprs/array_functions_test.cpp
  docs/en/sql-reference/sql-functions/array-functions/array_repeat.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/array-functions/array_repeat.md
  docs/zh/sql-reference/sql-functions/function-list.md
  gensrc/script/functions.py
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
Labels: documentation

#48150 [BugFix] Fix possible dead lock in LoadJobStatsListener
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  test/sql/test_materialized_view/R/test_create_mv_with_params
  test/sql/test_materialized_view/T/test_create_mv_with_params
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_time_slice
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_time_slice
Labels: 3.1, 3.3

#48215 [BugFix] fix show data from temporary table
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TemporaryTableTest.java
Labels: 3.3

#48229 [BugFix] Fix NestLoop Join runtime filter not evaluate in Exchange node (backport #47348)
  be/src/exec/pipeline/exchange/exchange_source_operator.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exprs/expr_context.h
  be/src/exprs/runtime_filter_bank.cpp
  test/sql/test_nest_loop_join/R/test_nest_loop_join
  test/sql/test_nest_loop_join/T/test_nest_loop_join
Labels: automerge

#48232 [Refactor] add a config to ignore rpc overcrowded problem (backport #47332)
  be/src/common/config.h
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/service/brpc.h
  be/src/storage/segment_replicate_executor.cpp
Labels: automerge

#35854 [BugFix] fix the issue of inaccurate limit data after show export sorting
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/ExportMgrTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#48194 [BugFix] Fix openssl_supports_aesni compile on ARM
  be/src/fs/encrypt_file.cpp
Labels: 3.3

#48198 [Doc] Minor fix on format
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#48230 [BugFix] Fix the bug of array out-of-bounds access
  be/src/storage/persistent_index.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 3.1, 3.2, 3.3

#48228 [BugFix] fix snapshot inconsistent during query
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.1, 3.2, 3.3

#47802 [BugFix] follower sync dictionary refresh state
  fe/fe-core/src/main/java/com/starrocks/catalog/Dictionary.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/persist/DictionaryMgrInfo.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DictionaryMgrTest.java
Labels: META-REVIEW, 3.3

#48260 [Doc] Add ZH isnotnull doc
  docs/zh/sql-reference/sql-functions/utility-functions/isnotnull.md
Labels: documentation, 3.1, 3.2, 3.3

#48227 [BugFix] normalized CTE name to lower case for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
Labels: 3.1, 3.2, 3.3

#48256 [BugFix] Use copyOnlyForQuery instead of deepCopy to avoid time costs in mv refresh's collectBaseTableSnapshotInfos
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TableSnapshotInfo.java
Labels: 3.1, 3.2, 3.3

#48241 [BugFix] Fix the data correctness issue for datacache caused by inconsistent data lifetime during asynchronous cache population.
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
Labels: 3.2, 3.3

#48274 [BugFix] Fix NPE when pending refresh MV when base table is changed
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
Labels: 3.1, 3.2, 3.3

#43907 [Enhancement] Migrate part of db lock to table lock in SchemaChange
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/CompactionHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java
Labels: 3.3

#48226 [BugFix] Fix overflow for array_sortby
  be/src/exec/sorting/sort_column.cpp
  be/src/exec/sorting/sort_permute.h
  test/sql/test_array_fn/R/test_array_sortby
  test/sql/test_array_fn/T/test_array_sortby
Labels: 3.3

#48280 [Doc]Update GRANT.md
  docs/zh/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#48281 [Doc]Update GRANT.md
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#48314 [Doc] Add Helm quickstart to Chinese docs
  docs/docusaurus/sidebars.json
  docs/zh/assets/deployment/_OperatorPrereqs.mdx
  docs/zh/quick_start/helm.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#48295 [Doc] Update data_cache.md
  docs/zh/data_source/data_cache.md
Labels: documentation, 3.3

#48296 [Doc]Update data_cache.md
  docs/en/data_source/data_cache.md
Labels: documentation, 3.3

#48321 [BugFix] fix redirection of internal log to console
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.1, 3.2, 3.3

#48299 [Enhancement] support download profile on fe http service
  fe/fe-core/src/main/java/com/starrocks/http/action/QueryProfileAction.java
Labels: 3.0, 3.1, 3.2, 3.3

#48332 [Doc] Update Architecture.md
  docs/en/introduction/Architecture.md
Labels: documentation

#47904 [BugFix] Fix statistics agg functions to return NULL incorrectly
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exprs/agg/covariance.h
  be/src/exprs/agg/factory/aggregate_factory.hpp
  be/src/exprs/agg/factory/aggregate_resolver.hpp
  be/src/exprs/agg/factory/aggregate_resolver_variance.cpp
  be/src/exprs/agg/nullable_aggregate.h
  be/src/exprs/agg/variance.h
  test/sql/test_agg_function/R/test_always_null_statistic_funcs
  test/sql/test_agg_function/T/test_always_null_statistic_funcs
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#48151 [BugFix] Fix can't read struct with empty subfield in parquet
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/meta_helper.h
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/iceberg_schema_evolution_file_reader_test.cpp
  be/test/formats/parquet/test_data/iceberg_schema_evolution/struct_map_array.parquet
Labels: 3.0, 3.1, 3.2, 3.3

#48196 [BugFix] fix constant evaluation before expr open
  be/src/exprs/cast_expr.h
  be/src/exprs/cast_expr_array.cpp
Labels: 3.2, 3.3

#47121 [Enhancement] [Refactor] (Multi Ref Base Table Part1) Enhance materialized view multi ref base table derivation
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvJoinFilter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvRefreshArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessListPartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessRangePartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/common/util/SRStringUtils.java
  fe/fe-core/src/main/java/com/starrocks/mv/analyzer/MVPartitionExpr.java
  fe/fe-core/src/main/java/com/starrocks/mv/analyzer/MVPartitionExprEqChecker.java
  fe/fe-core/src/main/java/com/starrocks/mv/analyzer/MVPartitionExprResolver.java
  fe/fe-core/src/main/java/com/starrocks/mv/analyzer/MVPartitionSlotRefResolver.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPlanBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ListPartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiff.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MVPartitionExprResolverTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MvJoinFilterTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/server/ConcurrentDDLTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_multi_union3
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_multi_union3
  test/sql/test_transparent_mv/R/test_transparent_mv_basic
  test/sql/test_transparent_mv/R/test_transparent_mv_hive
  test/sql/test_transparent_mv/R/test_transparent_mv_iceberg_part2
  test/sql/test_transparent_mv/R/test_transparent_mv_olap
  test/sql/test_transparent_mv/T/test_transparent_mv_hive
  test/sql/test_transparent_mv/T/test_transparent_mv_iceberg_part2
  test/sql/test_transparent_mv/T/test_transparent_mv_olap
Labels: 3.3

#48361 [Enhancement] Support current_role constant simplification at FE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectConstTest.java
Labels: 3.2, 3.3

#48197 [BugFix] Fixed the bug that clusterid cannot be parsed when using --helper during upgrade
  fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
  fe/fe-core/src/main/java/com/starrocks/persist/StorageInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
Labels: META-REVIEW, 3.3

#48363 [BugFix] fix npe on iceberg v1 table when table uuid is null
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.1, 3.2, 3.3
