Repository StarRocks/starrocks, pull requests merged in 2024-04, with the labels that each got.

#41996 [BugFix] Fix metrics of meta_log_count wrong bug on share-data mode
  fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
Labels: 3.0, 3.1, 3.2

#43434 [Doc] update FE parameters for broker load
  docs/en/loading/cloud_storage_load.md
  docs/zh/loading/cloud_storage_load.md
Labels: documentation, 3.1, 3.2, 3.3

#43435 [Doc] add job splitting info to BROKER LOAD sql doc
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3

#41938 [Feature] Add a second version implementation of get table schema and partition API.
  fe/fe-core/src/main/java/com/starrocks/catalog/DistributionInfo.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseResult.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/RestBaseResultV2.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/TableBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/TablePartitionAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/TableSchemaAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/ColumnView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/DistributionInfoView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/IndexView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/MaterializedIndexMetaView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/PartitionInfoView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/TableSchemaView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/TabletView.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/package-info.java
  fe/fe-core/src/main/java/com/starrocks/load/PartitionUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/test/java/com/starrocks/http/BadHttpRequestTest.java
  fe/fe-core/src/test/java/com/starrocks/http/ExecuteSqlActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/RestBaseResultTest.java
  fe/fe-core/src/test/java/com/starrocks/http/StarRocksHttpTestCase.java
  fe/fe-core/src/test/java/com/starrocks/http/TableQueryPlanActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TablePartitionActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TableSchemaActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/PartitionUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadPendingTaskTest.java
Labels: META-REVIEW, feature

#43332 [Doc] add desc for the addfield transform
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#43306 [Feature] temporary table(part-0): introduce TemporaryTableMgr
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/TemporaryTableMgrTest.java
Labels: feature

#43454 [BugFix] metadata_journal_skip_bad_journal_ids only work on restart
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#43445 [BugFix] Fix iceberg sink to string partition with special characters
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.3

#43470 [UT] Fix testConcurrentlyDropDbAndCreateTable running too slow
  fe/fe-core/src/test/java/com/starrocks/server/ConcurrentDDLTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#42932 [Feature] Support to convert ARRAY/STRUCT/MAP to arrow
  be/src/util/arrow/starrocks_column_to_arrow.cpp
  be/test/util/arrow/starrocks_column_to_arrow_test.cpp
Labels: feature

#43103 [Enhancement] merge tiny stripes / RowGroups when do splitting
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_orc.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/io/shared_buffered_input_stream.cpp
  test/sql/test_external_file/R/test_orc_split_task
  test/sql/test_external_file/R/test_parquet_split_task
  test/sql/test_external_file/T/test_orc_split_task
  test/sql/test_external_file/T/test_parquet_split_task
Labels: 3.2

#43443 [Enhancement] update CBO_EQ_TYPE default value to DECIMAL
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: behavior_changed

#42895 [Feature] Use sstables in LakePersistentIndex
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/filenames.h
  be/src/storage/lake/key_index.h
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/persistent_index_memtable.cpp
  be/src/storage/lake/persistent_index_memtable.h
  be/src/storage/lake/persistent_index_sstable.cpp
  be/src/storage/lake/persistent_index_sstable.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/sstable/persistent_index_sstable.cpp
  be/src/storage/sstable/table.cpp
  be/src/storage/sstable/table.h
  be/test/CMakeLists.txt
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/lake/persistent_index_memtable_test.cpp
  be/test/storage/lake/persistent_index_sstable_test.cpp
  gensrc/proto/types.proto
Labels: PROTO-REVIEW, feature

#43458 [BugFix] Disallow parquet writer to write map value of null key
  be/src/formats/parquet/chunk_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/level_builder.h
  be/test/formats/parquet/parquet_file_writer_test.cpp
Labels: behavior_changed, 3.3

#43481 [BugFix] Fix orc writer write float/double columns
  be/src/formats/orc/orc_file_writer.cpp
  be/test/formats/orc/orc_file_writer_test.cpp
Labels: 3.3

#43382 [BugFix] Fix use after free when read the GIN
  be/src/storage/inverted/clucene/clucene_inverted_reader.cpp
  be/src/storage/inverted/clucene/clucene_inverted_reader.h
Labels: 3.3

#43504 [Enhancement][FlatJson] support fold json_query
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 3.3

#43463 [Doc]Add more info in helm chart
  docs/en/deployment/helm.md
  docs/zh/deployment/helm.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43552 [BugFix] fix drop system table
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#43553 [Doc] remove semicolon when formatting the output
  docs/en/loading/automq-routine-load.md
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/Materialized_view.md
  docs/zh/loading/automq-routine-load.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/Materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3

#43566 [UT] Fix unstable ut
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#43503 [Feature][FlatJson] Refactor json cast logical
  be/src/exprs/cast_expr.cpp
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/util/json_converter.h
  be/test/exprs/cast_expr_test.cpp
  be/test/exprs/json_functions_test.cpp
Labels: behavior_changed, feature

#43570 [Doc] add a limit for schema change in alter table
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43444 [BugFix] Iceberg sink supports null partition
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  test/sql/test_sink/R/test_iceberg_sink
  test/sql/test_sink/T/test_iceberg_sink
Labels: behavior_changed, 3.3

#43469 [BugFix] Fixed several warehouse-related issues caused by modifications left behind
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionOperationParams.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithoutChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockID.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BackendsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ComputeNodeProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/LakeTabletsProcNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/SchemaScanNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseTest.java
Labels: 3.3

#43547 [Feature][FlatJson] support get_json_bool/bigint function
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  gensrc/script/functions.py
Labels: feature

#43567 [BugFix] Return unkown stage even if refTablePartitionNameToRefresh is empty
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
Labels: 3.3

#43591 [BugFix] Fix datacache sql-test failed
  test/sql/test_datacache/R/test_datacache_metrics
  test/sql/test_datacache/T/test_datacache_metrics
Labels: 3.3

#43565 [BugFix] Truncate hive table's text string if length excceed varchar's length
  be/src/formats/csv/string_converter.cpp
  be/src/util/utf8.h
  be/test/formats/csv/string_converter_test.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#43595 [Doc] fix jdbc catalog doc
  docs/en/data_source/catalog/jdbc_catalog.md
  docs/zh/data_source/catalog/jdbc_catalog.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43602 [BugFix] fix parquet reader split io tasks
  be/src/formats/parquet/file_reader.cpp
Labels: 3.2, 3.3

#43601 [Doc] fix broken external links
  docs/docusaurus/sidebars.json
  docs/en/administration/management/monitoring/Monitor_and_Alert.md
  docs/en/benchmarking/SSB_Benchmarking.md
  docs/en/data_source/catalog/elasticsearch_catalog.md
  docs/en/developers/development-environment/ide-setup.md
  docs/en/developers/trace-tools/Trace.md
  docs/en/faq/FAQ_On_Github.md
  docs/en/integrations/BI_integrations/Superset.md
  docs/en/loading/Flink-connector-starrocks.md
  docs/en/loading/RoutineLoad.md
  docs/en/loading/automq-routine-load.md
  docs/en/using_starrocks/Using_HLL.md
  docs/zh/administration/management/monitoring/Monitor_and_Alert.md
  docs/zh/benchmarking/SSB_Benchmarking.md
  docs/zh/faq/FAQ_On_Github.md
  docs/zh/integrations/BI_integrations/Superset.md
  docs/zh/loading/Flink-connector-starrocks.md
  docs/zh/loading/automq-routine-load.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43550 [Enhancement] Simplify the StmtExecutor proxy logic and unify the StmtExecutor constructor
  fe/fe-core/src/main/java/com/starrocks/analysis/HintNode.java
  fe/fe-core/src/main/java/com/starrocks/analysis/TableRef.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/HelpStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DateTruncTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/HelpStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetCatalogStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/UseCatalogStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/UseDbStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ComputeNodeProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/StmtExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
Labels: 3.3

#43403 [BugFix] Unpack const column when in local exchange source operator
  be/src/column/chunk.cpp
  be/src/column/chunk.h
  be/src/exec/pipeline/aggregate/repeat/repeat_operator.cpp
  be/src/exec/pipeline/aggregate/repeat/repeat_operator.h
  be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteGroupingSetsByCTERule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanFragmentWithCostTest.java
  test/sql/test_grouping_sets/R/test_grouping_sets_v1
  test/sql/test_grouping_sets/R/test_grouping_sets_v2
  test/sql/test_grouping_sets/T/test_grouping_sets_v1
  test/sql/test_grouping_sets/T/test_grouping_sets_v2
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#42523 [Doc] for periodical task
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
Labels: documentation

#43641 [Doc] Fix markdown link syntax in doc
  docs/en/administration/user_privs/ranger_plugin.md
  docs/zh/administration/user_privs/ranger_plugin.md
Labels: documentation, 3.1, 3.2, 3.3

#43640 [Doc] Remove refresh_moment from 2.5
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
Labels: documentation

#43092 [BugFix] fix view delta mv rewrite
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/Generator.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PermutationGenerator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/PermutationGeneratorTest.java
Labels: 3.1, 3.2

#43637 [UT] disable long running BeRestartTest
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/BeRestartTest.java
Labels: 3.2, 3.3

#43653 [Doc] update docs about data change&transformation during loading
  docs/en/loading/Etl_in_loading.md
  docs/en/loading/Load_to_Primary_Key_tables.md
  docs/zh/loading/Etl_in_loading.md
  docs/zh/loading/Load_to_Primary_Key_tables.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43652 [Feature] Support log profile to file
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
Labels: behavior_changed, feature

#42449 [Enhancement]aggregation pipeline shared limit
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_sink_operator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/AggregationNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#43457 [BugFix] External catalog failed to verify create drop insert permissions
  fe/fe-core/src/main/java/com/starrocks/privilege/ranger/hive/RangerHiveAccessController.java
Labels: 3.3

#43673 Revert "[Tool] SQL-Tester support keep_alive mode (backport #43341)"
  .github/workflows/approve-checker.yml
  .github/workflows/ci-pipeline.yml
  .github/workflows/inspection-reusable-pipeline.yml
  .github/workflows/label-action.yml
  test/conf/sr.conf
  test/lib/github_issue.py
  test/lib/sr_sql_lib.py
  test/requirements.txt
  test/run.py
Labels: title needs [type]

#43543 [Enhancement] Add file read count statistic in file scanner
  be/src/connector/file_connector.cpp
  be/src/connector/file_connector.h
  be/src/exec/avro_scanner.cpp
  be/src/exec/csv_scanner.cpp
  be/src/exec/file_scanner.h
  be/src/exec/iceberg/iceberg_delete_file_iterator.cpp
  be/src/exec/iceberg/iceberg_delete_file_iterator.h
  be/src/exec/json_scanner.cpp
  be/src/exec/orc_scanner.cpp
  be/src/exec/parquet_reader.cpp
  be/src/exec/parquet_reader.h
  be/src/exec/parquet_scanner.cpp
  be/test/exec/csv_scanner_test.cpp
  be/test/exec/json_scanner_test.cpp
  be/test/exec/orc_scanner_test.cpp
  be/test/exec/parquet_scanner_test.cpp
Labels: 3.1, 3.2, 3.3

#43546 [Enhancement] Optimize parquet scanner by arrow io coalesce
  be/src/common/config.h
  be/src/exec/parquet_reader.cpp
Labels: 3.1, 3.2, 3.3

#43668 [Feature] Support log profile to file (backport #43652)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
Labels: behavior_changed, feature

#43197 [Enhancement] Print primary key table migration failed reason
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 3.1, 3.2

#43327 [Enhancement] support lake compaction validation
  be/src/common/config.h
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/compaction_task_context.h
  be/test/storage/lake/compaction_scheduler_test.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW

#43586 [Doc] fix description of starlet_cache_evict_high_water
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#43630 [BugFix] Fix PushDownTopNBelowUnionRule bug when pushdown topn ordering contains duplicated column refs
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownTopNBelowUnionRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/topn_push_down_union.json
  test/sql/test_push_down_predicate/R/test_topn_push_down_union
  test/sql/test_push_down_predicate/T/test_topn_push_down_union
Labels: 3.1, 3.2, 3.3

#43690 [Feature] Support log profile to file (backport #43652)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
Labels: behavior_changed, feature

#43164 [Enhancement] Use standalone lake compaction txn timeout config (backport #36249)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
Labels: behavior_changed

#43636 [Doc]Update ranger_plugin.md
  docs/en/administration/user_privs/ranger_plugin.md
  docs/zh/administration/user_privs/ranger_plugin.md
Labels: documentation, 3.1, 3.2, 3.3

#43695 [Doc] adjust the position of Iceberg tutorial in Data Lakes nav
  docs/docusaurus/sidebars.json
  docs/en/data_source/icebergtutorial.mdx
  docs/zh/data_source/icebergtutorial.mdx
Labels: documentation, 3.2, 3.3

#43569 [BugFix] fix race condition issue about persistent index's l0
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/primary_index_test.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#43329 [Doc] add orc_use_column_names
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.1, 3.2

#43629 [Enhancement] Add enable_materialized_view_text_based_rewrite to enable text based rewrite or not
  fe/fe-core/src/main/java/com/starrocks/catalog/MvPlanContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: behavior_changed, 3.3

#43517 [Feature] Support using LakePersistentIndex in cloud native table
  be/src/common/config.h
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/compaction_task.h
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/lake_primary_index.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/persistent_index_sstable.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/lake/vertical_compaction_task.cpp
  be/test/storage/lake/compaction_test_utils.h
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/test_util.h
  gensrc/proto/lake_types.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW, feature

#43564 [BugFix]fix prepare execute bug when use jdbc
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PrepareStmt.java
  test/sql/test_preparestatement/R/test_preprare_statement
  test/sql/test_preparestatement/T/test_preprare_statement
Labels: 3.2, 3.3

#43716 [Enhancement] warning log print backend id when an instance report fails
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
Labels: 3.2, 3.3

#43740 [Feature] Support manual compaction for cloud native table (backport #40566)
  fe/fe-core/src/main/java/com/starrocks/alter/CompactionHandler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatistics.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/RandomSorter.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSelector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSorter.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CompactionClause.java
  fe/fe-core/src/test/java/com/starrocks/alter/CompactionHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/PartitionStatisticsTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSorterTest.java
Labels: behavior_changed, feature

#43588 [BugFix] Add enable_materialized_view_metrics_collect to control whether to collect mv's metrics
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/metric/IMaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsBlackHoleEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsRegistry.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/MVRewriteValidator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteMetricsTest.java
Labels: 3.1, 3.2, 3.3

#43707 [BugFix] fix graceful exit crash when query iceberg eq-delete parquet file
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
Labels: 3.1, 3.2, 3.3

#43483 [BugFix] Fix IllegalStateException when clean StreamLoadTask
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: 3.0, 3.1, 3.2, 3.3

#43750 [BugFix] Fix Trino parser ctas when has multi fe
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoCtasTest.java
Labels: 3.3

#43473 [Enhancement] Support MATCH expression for reading GIN
  be/src/exprs/CMakeLists.txt
  be/src/exprs/expr.cpp
  be/src/exprs/match_expr.cpp
  be/src/exprs/match_expr.h
  be/src/storage/column_expr_predicate.cpp
  be/src/storage/column_expr_predicate.h
  be/src/storage/inverted/clucene/clucene_inverted_reader.cpp
  be/src/storage/inverted/clucene/clucene_inverted_reader.h
  be/src/storage/inverted/inverted_index_common.hpp
  be/src/storage/inverted/inverted_index_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/MatchExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AggregationAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/MatchExprOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/GINIndexTest.java
  gensrc/thrift/Exprs.thrift
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: behavior_changed, PROTO-REVIEW, 3.3

#43661 [Feature] Add mv meta function to inspect mv plan cache
  fe/fe-core/src/main/java/com/starrocks/sql/common/DebugOperatorTracer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/function/MetaFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConstantExpressionTest.java
  test/sql/test_materialized_view/R/test_mv_meta_functions
  test/sql/test_materialized_view/T/test_mv_meta_functions
Labels: behavior_changed, feature

#43717 [BugFix] Fix potential huge leader fe memory occupation when load profile is enabled
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
Labels: 3.2, 3.3

#43526 [Feature][FlatJson] FE support json type inference in query
  fe/fe-core/src/main/java/com/starrocks/catalog/ColumnAccessPath.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldAccessPathNormalizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW, feature

#43774 [BugFix] Fix potential huge leader fe memory occupation when load profile is enabled (backport #43717)
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
Labels: behavior_changed

#43730 [Refactor] Change protobuf package name from starrocks.lake to starrocks
  be/src/exprs/table_function/list_rowsets.cpp
  be/src/exprs/table_function/list_rowsets.h
  be/src/runtime/lake_snapshot_loader.cpp
  be/src/runtime/lake_snapshot_loader.h
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/lake/compaction_policy.h
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/metacache.h
  be/src/storage/lake/schema_change.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/tablet_metadata.h
  be/src/storage/lake/tablet_reader.h
  be/src/storage/lake/txn_log.h
  be/src/storage/lake/txn_log_applier.h
  be/src/storage/lake/types_fwd.h
  be/src/storage/lake/update_manager.h
  be/src/storage/lake/versioned_tablet.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/src/storage/rowset/segment_rewriter.h
  be/src/tools/meta_tool.cpp
  be/test/exec/lake_meta_scanner_test.cpp
  be/test/runtime/lake_tablets_channel_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/lake/test_util.h
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW

#43734 [BugFix] Fix hive sink using textfile format
  fe/fe-core/src/main/java/com/starrocks/planner/HiveTableSink.java
Labels: 3.3

#40489 [Feature] Support populate datacache asynchronously.
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/io/cache_input_stream_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW, feature

#43725 [BugFix] Fix orc writer write column that has no nulls
  be/src/formats/orc/orc_file_writer.cpp
  be/src/formats/orc/orc_file_writer.h
  be/test/formats/orc/orc_file_writer_test.cpp
Labels: 3.3

#43778 [UT] Optimize testTransparentRewriteWithJoinMv1 ut performance
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteHiveTest.java
Labels: 3.3

#43594 [Enhancement] Improve no source file error message
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/FileScanNodeTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#43793 [BugFix] fix pk dump crash in persistent index
  be/src/storage/persistent_index.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.1, 3.2, 3.3

#43777 [Feature] Support populate datacache asynchronously. (backport #40489)
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/io/cache_input_stream_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: feature

#43781 [Feature] Support populate datacache asynchronously. (backport #40489)
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/io/cache_input_stream_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: feature

#43571 [Enhancement] enable split io task by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteScanRangeLocationsTest.java
Labels: 3.2, 3.3

#43490 [Feature] Insert statement support partial update mode
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  test/sql/test_insert_empty/R/test_insert_partial_update
  test/sql/test_insert_empty/T/test_insert_partial_update
  test/sql/test_materialized_column/R/test_materialized_column
Labels: behavior_changed, feature

#43699 [BugFix] Disable memory tracker by defalt
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  test/sql/test_sys/R/test_fe_memory_usage
Labels: 3.1, 3.2, 3.3

#43789 [Enhancement] make index application configurable
  be/src/common/config.h
  be/src/storage/rowset/scalar_column_iterator.cpp
  be/src/storage/rowset/scalar_column_iterator.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment_iterator.cpp
  test/sql/test_scan/test_pushdown_or_predicate/R/test_index_and_filter_on_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/R/test_parse_and_rewrite_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_index_and_filter_on_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_parse_and_rewrite_or_predicate
Labels: 3.3

#43803 [BugFix] One-staged aggrregation's having predicates should not applied to pre-cache aggregate operator
  be/src/exec/aggregator.h
  be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.cpp
  test/sql/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr/R/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr
  test/sql/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr/T/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#43489 [BugFix] add DefaultSharedDataWorkerProvider for shared-data mode
  fe/fe-core/src/main/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/ColocatedBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/NormalBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/DefaultWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/WorkerProvider.java
  fe/fe-core/src/test/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/DefaultWorkerProviderTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#43650 [Enhancement] Improve referenced column and column mapping expr invalid error message when getting load plan
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/test/java/com/starrocks/load/LoadTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#43823 [BugFix] One-staged aggrregation's having predicates should not applied to pre-cache aggregate operator (backport #43803)
  be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.cpp
  be/src/exec/vectorized/aggregator.h
  test/sql/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr/R/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr
  test/sql/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr/T/test_one_stage_aggr_having_preds_should_apply_to_pre_cache_aggr
Labels: automerge, version:2.5.21

#43791 [Doc]clarify desc for loading overhead caused by generated cols
  docs/en/sql-reference/sql-statements/generated_columns.md
  docs/zh/sql-reference/sql-statements/generated_columns.md
Labels: documentation, 3.1, 3.2, 3.3

#43830 [BugFix] Disable duplicate sort key when creating table (backport #43206)
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: behavior_changed

#43752 [Feature] Support load from tablet of LakePersistentIndex
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/primary_key_compaction_policy.cpp
  be/src/storage/lake/rowset.h
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW, feature

#36202 [Doc]add dict_mapping
  docs/docusaurus/sidebars.json
  docs/en/sql-reference/sql-functions/dict-functions/dict_mapping.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/dict-functions/dict_mapping.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.2, 3.3

#43802 [BugFix] Fix Lake Schema Change miss use warehouse bug
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseTest.java
Labels: 3.3

#43839 [BugFix] Fix subList error when cutting paths in FileScanNode
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/test/java/com/starrocks/planner/FileScanNodeTest.java
Labels: 3.1, 3.2, 3.3

#43808 [Enhancement] Make it optional to have starrocks_be.debuginfo in allin1 image
  docker/dockerfiles/allin1/allin1-ubi.Dockerfile
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
Labels: 3.1, 3.2, 3.3

#43849 [BugFix] Remove deprecated ObjectStorageUtils
  fe/fe-core/src/main/java/com/starrocks/connector/ObjectStorageUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/ObjectStorageUtilsTest.java
Labels: 3.3

#43675 [Enhancement]Support get stats for subfield of struct type from statistics storage
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorColumnStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorHistogramColumnStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SkewJoinOptimizeRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/RewriteTreeTask.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SplitScanToUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCHPlanWithHistogramCostTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/MockHistogramStatisticStorage.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
Labels: 3.3

#43868 [UT] Fix unstable SQL TEST for GIN
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: 3.3

#43874 [Doc] fix the wrong category name of dictionary function
  docs/en/sql-reference/sql-functions/function-list.md
Labels: documentation, 3.2, 3.3

#43836 [Enhancement] INSERT INTO FILES() support user-specified column separator and row delimiter
  be/src/runtime/table_function_table_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/planner/TableFunctionTableSinkTest.java
  gensrc/thrift/Descriptors.thrift
  test/sql/test_sink/R/test_csv_file_sink
  test/sql/test_sink/T/test_csv_file_sink
Labels: behavior_changed, PROTO-REVIEW, 3.3

#43842 [BugFix] fix One tablet property cause multi stage agg result wrong
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/LogicalProperty.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#43890 [Doc] remove array_contains_seq from 3.2 doc
  docs/en/sql-reference/sql-functions/array-functions/array_contains_seq.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/array-functions/array_contains_seq.md
  docs/zh/sql-reference/sql-functions/function-list.md
Labels: documentation

#42956 [Enhancement](5/n) Adding or dropping columns without data rewriting in share data mode
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/schema_change.h
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/metadata_util.cpp
  be/src/storage/metadata_util.h
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  gensrc/proto/lake_types.proto
  gensrc/thrift/AgentService.thrift
Labels: META-REVIEW, PROTO-REVIEW

#43893 Revert "[Enhancement] enable split io task by default (backport #43571)"
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteScanRangeLocationsTest.java
Labels: title needs [type]

#42851 [BugFix] Refactor the partition refresh of materialized view for paimon table
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/Partition.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/RowDataConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorPartitionTraitsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.2, 3.3

#43809 [Enhancement] support replace for primary index
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/test/storage/persistent_index_test.cpp
  be/test/storage/primary_index_test.cpp
Labels: 3.1, 3.2, 3.3

#43898 [Doc]add version info for dict_mapping
  docs/en/sql-reference/sql-functions/dict-functions/dict_mapping.md
  docs/zh/sql-reference/sql-functions/dict-functions/dict_mapping.md
Labels: documentation, 3.2, 3.3

#43861 [Enhancement] enhance view delta rewrite to support join derive rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/view_delta.json
Labels: 3.1, 3.2, 3.3

#43872 [Enhancement] Unify error msg of default storage volume not exists
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1, 3.2, 3.3

#43917 [BugFix] Fix update planner more compitable between ouput column and target table column
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  test/sql/test_dml/R/test_update
  test/sql/test_dml/T/test_update
Labels: 3.1, 3.2, 3.3

#43936 [UT] remove setting session variables have not been added
  .gitignore
  test/sql/test_scan/test_pushdown_or_predicate/R/test_index_and_filter_on_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/R/test_parse_and_rewrite_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_index_and_filter_on_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_parse_and_rewrite_or_predicate
Labels: 3.3

#43889 [BugFix] Fix forgot to handle error
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/tablet_updates.cpp
Labels: 3.1, 3.2, 3.3

#43935 [BugFix] disable per bucket optimize in force spill mode
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PhysicalDistributionAggOptRule.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
Labels: 3.2, 3.3

#43834 [Enhancement] Sstable block cache and memory usage of LakePerisistentIndex
  be/src/common/config.h
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/persistent_index.h
Labels: 3.3

#43887 [Enhancement] Upgrade staros v3.3 rc0
  conf/asan_suppressions.conf
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  run-be-ut.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/aws-sdk-cpp-1.10.36-instance-profile-deadlock.patch
  thirdparty/patches/aws-sdk-cpp-1.9.179.patch
  thirdparty/patches/aws-sdk-cpp-patch-1.9.179-LINK_LIBRARIES_ALL.patch
  thirdparty/patches/aws-sdk-cpp-patch-1.9.179-s2n-compile-error.patch
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
  thirdparty/vars.sh
Labels: 3.3

#43145 [Enhancement] Support runtime profile for broker load
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ExecPlan.java
  fe/fe-core/src/test/java/com/starrocks/load/LoadPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
Labels: 3.1, 3.2

#43843 [BugFix] Add TaskRunScheduler to support task runs' FIFO scheduler
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: documentation, 3.1, 3.2, 3.3

#43937 [Enhancement] show cloud compaction redirects to leader
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowProcStmt.java
Labels: 3.1, 3.2, 3.3

#43963 [UT] Fix MetaRecoveryTest UT bug when insert performed slowly.
  fe/fe-core/src/test/java/com/starrocks/consistency/MetaRecoveryDaemonTest.java
Labels: 3.1, 3.2, 3.3

#43956 [Refactor] Remove security integration related code
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProviderForExternal.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegrationFactory.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
Labels: META-REVIEW

#43981 [UT] Fix alter tablet meta ut failure without staros
  be/test/storage/lake/alter_tablet_meta_test.cpp
Labels: 3.1, 3.2, 3.3

#43994 [Doc] Unify names in Authentication
  docs/zh/administration/user_privs/Authentication.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43813 [Enhancement] Prune the pure pushdown predicate column after filtering by GIN
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/storage/column_expr_predicate.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_options.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  be/src/storage/tablet_reader.cpp
  be/src/storage/tablet_reader_params.h
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: PROTO-REVIEW, 3.3

#43973 [Feature] unnest left join on true (backport #42924)(backport #43296)
  be/src/exprs/table_function/multi_unnest.h
  be/src/exprs/table_function/table_function.h
  be/src/exprs/table_function/unnest.h
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunction.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableFunctionRelation.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeLateralTest.java
  gensrc/thrift/Types.thrift
  test/sql/test_unnest/R/test_unnest_left_join
  test/sql/test_unnest/T/test_unnest_left_join
Labels: feature

#44002 Revert "[Enhancement] enable split io task by default (backport #4357…
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteScanRangeLocationsTest.java
Labels: title needs [type]

#44006 [BugFix] Fix be related information_schema tables not work correctly with CN deployment
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaScanNode.java
Labels: 3.1, 3.2

#43891 [Feature] Support manually update the datacache quota online and automatically adjust datacache disk quota.
  be/src/block_cache/CMakeLists.txt
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cache_options.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/cachelib_wrapper.h
  be/src/block_cache/disk_space_monitor.cpp
  be/src/block_cache/disk_space_monitor.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/io/cache_input_stream.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/options.cpp
  be/src/testutil/scoped_updater.h
  be/test/CMakeLists.txt
  be/test/block_cache/block_cache_test.cpp
  be/test/block_cache/disk_space_monitor_test.cpp
  be/test/block_cache/test_cache_utils.h
Labels: feature

#43897 [Enhancement] Optimize automatic bucket for cloud native table by avoid list s3
  be/src/runtime/load_channel_mgr.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
Labels: 3.2, 3.3

#44020 [Feature] Support manually update the datacache quota online and automatically adjust datacache disk quota. (backport #43891)
  be/src/block_cache/CMakeLists.txt
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cache_options.cpp
  be/src/block_cache/cache_options.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/cachelib_wrapper.h
  be/src/block_cache/disk_space_monitor.cpp
  be/src/block_cache/disk_space_monitor.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/io/cache_input_stream.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/options.cpp
  be/src/testutil/scoped_updater.h
  be/test/CMakeLists.txt
  be/test/block_cache/block_cache_test.cpp
  be/test/block_cache/disk_space_monitor_test.cpp
  be/test/block_cache/test_cache_utils.h
Labels: behavior_changed, feature

#44030 [BugFix] Fix external db & table privilege compatibility
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/test/java/com/starrocks/privilege/PrivilegeCollectionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.2, 3.3

#44034 [BugFix] Fix race condition issue in PrimaryIndex::memory_usage()
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/test/storage/persistent_index_test.cpp
Labels: 3.1, 3.2, 3.3

#43970 [Doc] explain that flink cdc is one of many methods to synchronize data from mysql to sr
  docs/en/assets/4.9.2.png
  docs/en/loading/Flink_cdc_load.md
  docs/zh/assets/4.9.2.png
  docs/zh/loading/Flink_cdc_load.md
Labels: documentation, title needs [type]

#43886 [Enhancement] change _index_lock to read/write lock
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: 3.2, 3.3

#43119 [Feature]query_pool support spill_mem_limit_threshold
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
Labels: feature

#44003 [Doc]Doc for unnest left join on true
  docs/en/sql-reference/sql-functions/array-functions/unnest.md
  docs/zh/sql-reference/sql-functions/array-functions/unnest.md
Labels: documentation, 3.2, 3.3

#44039 [UT] fix unstable case: test_spill_aggregate
  test/sql/test_spill/R/test_spill_aggregate
  test/sql/test_spill/T/test_spill_aggregate
Labels: 3.0, 3.1, 3.2, 3.3

#43975 [BugFix] fix pruned predicate not be rewritten
  fe/fe-core/src/main/java/com/starrocks/sql/common/DebugOperatorTracer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeRewriter.java
  test/sql/test_hive/T/test_hive_mv
Labels: 3.1, 3.2, 3.3

#44038 [BugFix] Fix persistent index type can not take effect
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.3

#44018 [BugFix] Fix alter order clause miss use warehouse id
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
Labels: 3.3

#44067 [BugFix] Support Hudi query in data delete condition for 0.12 version above
  fe/pom.xml
  java-extensions/hudi-reader/pom.xml
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3

#44091 [Doc] Use consistent version info
  docs/en/sql-reference/sql-statements/data-manipulation/REFRESH_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-manipulation/REFRESH_MATERIALIZED_VIEW.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43162 [Feature] temporary table(part-1): support create/drop/show temporary table
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/ShowTemporaryTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableLikeAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DeleteAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DropStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTableAsSelectStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTemporaryTableAsSelectStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTemporaryTableLikeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTemporaryTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropTemporaryTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TemporaryTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/MockedMetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/ReplayMetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/http/StarRocksHttpTestCase.java
  fe/fe-core/src/test/java/com/starrocks/privilege/RBACMockedMetadataMgr.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowTableMockMeta.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeUpdateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CTASAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_temporary_table/R/temporary_table
  test/sql/test_temporary_table/T/temporary_table
Labels: behavior_changed, META-REVIEW, PROTO-REVIEW, feature

#44032 [Enhancement] optimize hudi table metadata fetch remote files
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/CachingRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileDesc.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemotePathKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
Labels: 3.2, 3.3

#43920 [Enhancement] support bucket shuffle join on colocate group execution
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/group_execution/execution_group.cpp
  be/src/exec/pipeline/group_execution/execution_group.h
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
  be/src/exec/pipeline/pipeline_fwd.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
  be/test/exec/pipeline/pipeline_test_base.cpp
  be/test/exec/stream/stream_pipeline_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/LocalFragmentAssignmentStrategy.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionDAG.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupExecutionPlanTest.java
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/RuntimeFilter.thrift
  test/sql/test_group_execution/R/test_group_execution_join
  test/sql/test_group_execution/T/test_group_execution_join
Labels: PROTO-REVIEW

#43419 [BugFix] fix crash in iceberg query
  be/src/formats/parquet/meta_helper.cpp
  be/test/formats/parquet/iceberg_schema_evolution_file_reader_test.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#44088 [BugFix] Fix heap-overflow in MultiGet of sstable
  be/src/storage/sstable/table.cpp
  be/test/storage/lake/persistent_index_sstable_test.cpp
Labels: 3.3

#44121 [Doc] update slack link
  docs/en/developers/How_to_Contribute.md
  docs/en/introduction/StarRocks_intro.md
  docs/en/project_help/slack.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#44105 [BugFix] Fix upper case column name make GIN metadata incorrect
  be/src/storage/metadata_util.cpp
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: 3.3

#44104 [Doc] Refine metadata_enable_recovery_mode docs
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/Administration/ADMIN_SET_PARTITION_VERSION.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/Administration/ADMIN_SET_PARTITION_VERSION.md
Labels: documentation, 3.3

#43964 [BugFix] Optional warehouse id
  gensrc/proto/internal_service.proto
Labels: PROTO-REVIEW, 3.3
