Repository StarRocks/starrocks, pull requests merged in 2024-08, with the labels that each got.

#49261 [Doc] Add example - modify column in batch
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, 3.1, 3.2, 3.3

#49246 [Enhancement] Support release block cache and some other thread pool before core dump
  be/src/agent/agent_server.cpp
  be/src/agent/agent_server.h
  be/src/agent/task_worker_pool.cpp
  be/src/block_cache/starcache_wrapper.cpp
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
Labels: 3.3

#49228 [Feature] support iceberg manifests table
  be/src/runtime/descriptors.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetaSplit.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataTableType.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergManifestsTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergMetadataTableFactory.java
  gensrc/thrift/Types.thrift
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/AbstractIcebergMetadataScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergHistoryTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergManifestsTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataColumnValue.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataLogEntriesScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScannerFactory.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergRefsTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergSnapshotsTableScanner.java
  test/sql/test_iceberg/R/test_metadata_table
  test/sql/test_iceberg/T/test_metadata_table
Labels: PROTO-REVIEW

#49226 [Enhancement] Improve load json array not set strip_outer_array error message
  be/src/exec/json_parser.cpp
  be/test/exec/json_parser_test.cpp
Labels: 3.1, behavior_changed, 3.2, 3.3

#48783 [Enhancement] Introduce datacache adaptive populate
  be/src/connector/hive_connector.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheOptions.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCachePopulateMode.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
  fe/fe-core/src/main/java/com/starrocks/planner/DeltaLakeScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileTableScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HudiScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DataCachePopulateRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DataCacheAutomaticPopulateTest.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DataCachePopulateModeTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q1.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q10.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q11.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q12.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q13.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q14.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q15.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q16.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q17.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q18.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q19.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q2.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q20.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q21.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q22.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q3.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q4.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q5.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q6.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q7.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q8.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q9.sql
  gensrc/thrift/DataCache.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.3

#48998 [BugFix] fix blacklist not prevent insert sql
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
Labels: 3.1, 3.2, 3.3

#49240 [BugFix] Only repair mv when table's version/version time are matched with mv's version map
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobMVListener.java
  fe/fe-core/src/main/java/com/starrocks/mv/MVMetaVersionRepairer.java
  fe/fe-core/src/main/java/com/starrocks/mv/MVRepairHandler.java
  fe/fe-core/src/test/java/com/starrocks/planner/mv/MVMetaVersionRepairerTest.java
  fe/fe-core/src/test/java/com/starrocks/server/MVRepairHandlerTest.java
  test/sql/test_materialized_view_refresh/R/test_mv_event_trigger_with_stream_load
  test/sql/test_materialized_view_refresh/T/test_mv_event_trigger_with_stream_load
Labels: 3.3

#49253 [BugFix] don't fill catalog and database name to cte relation in the hive catalog
  fe/fe-core/src/main/java/com/starrocks/catalog/ConnectorView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergView.java
  test/sql/test_hive/R/test_hive_catalog
  test/sql/test_hive/T/test_hive_catalog
Labels: 3.3

#49270 [Feature] support iceberg files table
  be/src/runtime/descriptors.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetaSpec.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataTableType.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergFilesTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergMetadataTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergMetadataScanNode.java
  gensrc/thrift/Types.thrift
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergFilesTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScannerFactory.java
  test/sql/test_iceberg/R/test_metadata_table
  test/sql/test_iceberg/T/test_metadata_table
Labels: PROTO-REVIEW

#48248 [Feature] adapt limit for sqlserver (#48214)
  be/src/connector/jdbc_connector.cpp
Labels: behavior_changed

#49260 [Doc]Update Architecture.md
  docs/zh/introduction/Architecture.md
Labels: documentation, 3.3

#46773 [Feature] Unify load observation interface through information_schema.loads & _statistics_.loads_history
  be/src/exec/schema_scanner/schema_load_tracking_logs_scanner.cpp
  be/src/exec/schema_scanner/schema_loads_scanner.cpp
  be/src/runtime/stream_load/stream_load_executor.cpp
  docs/en/reference/information_schema/load_tracking_logs.md
  docs/zh/reference/information_schema/load_tracking_logs.md
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/LoadTrackingLogsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/LoadsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/EtlStatus.java
  fe/fe-core/src/main/java/com/starrocks/load/LoadConstants.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadsHistorySyncer.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/ManualLoadTxnCommitAttachment.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/ShowStreamLoadTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_information_schema/R/test_loads
  test/sql/test_information_schema/T/test_loads
  test/sql/test_insert_empty/R/test_insert
  test/sql/test_insert_empty/T/test_insert
Labels: documentation, META-REVIEW, PROTO-REVIEW

#49157 [Enhancement] Fix some hudi cve problems
  build.sh
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/server/HudiTableFactory.java
  fe/fe-core/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java
  fe/fe-core/src/test/java/com/starrocks/connector/HiveMetastoreApiConverterTest.java
  fe/pom.xml
  java-extensions/hadoop-ext/pom.xml
  java-extensions/hive-reader/pom.xml
  java-extensions/hudi-reader/pom.xml
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/kudu-reader/pom.xml
  java-extensions/paimon-reader/pom.xml
  java-extensions/pom.xml
Labels: 3.3

#49304 [Enhancement] Security Fixes
  fs_brokers/apache_hdfs_broker/src/broker-core/pom.xml
  fs_brokers/apache_hdfs_broker/src/pom.xml
Labels: 3.3

#49066 [BugFix]deal with pageindex before collect_io_range of data page
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
  be/test/formats/parquet/page_index_test.cpp
Labels: 3.3

#49288 [BugFix] Fix star count return null rather zero bug for mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/count_star_rewrite.json
  test/sql/test_materialized_view_rewrite/R/test_mv_rewrite_with_count_star
  test/sql/test_materialized_view_rewrite/T/test_mv_rewrite_with_count_star
Labels: 3.1, 3.2, 3.3

#49293 [BugFix] Fix View ColumnId bug when creating view with comments
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewAnalyzer.java
Labels: 3.3

#48477 [Feature] Support setting session vars in user property
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UserProperty.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/persist/AlterUserInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteAsExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowUserPropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseCreateAlterUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowUserPropertyStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/UserPropertyTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ExecuteAsStmtTest.java
Labels: META-REVIEW

#49307 [BugFix] Skip duplicated json keys in json scanner
  be/src/exec/json_scanner.cpp
  be/test/exec/json_scanner_test.cpp
  be/test/exec/test_data/json_scanner/test_duplicate_key.json
Labels: 3.1, 3.2, 3.3

#49130 [BugFix] fix last_refresh status of mv task
  fe/fe-core/src/main/java/com/starrocks/qe/ShowMaterializedViewStatus.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/TaskRunStatus.java
Labels: 3.1, 3.2, 3.3

#49291 [Enhancement] Move add / drop rollup code from Db Lock to Table Level Lock
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.3

#49328 [BugFix] Fix decimal type for pushing down aggregate on grouping-set
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggregateGroupingSetsRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetsTest.java
Labels: 3.3

#49335 [Enhancement] Print BE/CN IP in memory tracker errMsg
  be/src/runtime/mem_tracker.cpp
Labels: 3.3

#49326 [Enhancement] release the TaskRun.lock when archiving history
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.3

#49355 [BugFix] Fix plan and alter concurrent issue
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/OptimisticVersion.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
Labels: 3.2, 3.3

#48795 [BugFix] Fix pk concurrent apply issue
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.cpp
  be/src/storage/task/engine_clone_task.cpp
  be/test/agent/agent_task_test.cpp
Labels: 3.1, 3.2, 3.3

#49348 [BugFix]collect chunk io when pageindex didn't filter any page
  be/src/formats/parquet/scalar_column_reader.cpp
  be/test/formats/parquet/page_index_test.cpp
Labels: 3.3

#49336 [BugFix] Fix insert with partial update mode not working in cloud native
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
Labels: 3.3

#49351 [Tool] make starrocks compilable on gcc12/gcc13/clang18
  be/CMakeLists.txt
  be/src/exec/es/es_scan_reader.cpp
  be/src/exec/tablet_info.cpp
  be/src/exprs/agg/percentile_cont.h
  be/src/http/action/checksum_action.cpp
  be/src/http/action/datacache_action.cpp
  be/src/http/download_action.cpp
  be/src/http/http_client.h
  be/src/runtime/load_path_mgr.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/segment_flush_executor.cpp
  be/src/util/c_string.h
  be/test/exprs/like_test.cpp
  be/test/storage/rowset/rle_page_test.cpp
  be/test/util/bit_stream_utils_test.cpp
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  thirdparty/download-thirdparty.sh
  thirdparty/patches/rocksdb-6.22.1-metadata-header.patch
Labels: PROTO-REVIEW

#49388 [BugFix] Fix lake table upgrade downgrade
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
Labels: 3.2, 3.3

#49354 [Doc] add "compile with Docker" and "deploy manually" steps for contributors
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/en/deployment/deploy_manually.md
  docs/zh/deployment/deploy_manually.md
Labels: documentation, 3.3

#49295 [BugFix] Docker container cannot display ascii correctly
  docker/dockerfiles/toolchains/toolchains-centos7.Dockerfile
  docker/dockerfiles/toolchains/toolchains-ubuntu.Dockerfile
Labels: 3.0, 3.1, 3.2, 3.3

#49300 [Enhancement] Some code refactor for TDE
  be/src/fs/key_cache.cpp
  be/src/fs/key_cache.h
  be/test/fs/key_cache_test.cpp
  fe/fe-core/src/main/java/com/starrocks/encryption/KeyMgr.java
  fe/fe-core/src/main/java/com/starrocks/encryption/NormalKey.java
  fe/fe-core/src/test/java/com/starrocks/encryption/KeyMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/encryption/NormalKeyTest.java
  gensrc/proto/encryption.proto
Labels: PROTO-REVIEW, 3.3

#49394 [BugFix] Fix subpartitions with tablet pruing bug
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/lib/sr_sql_lib.py
  test/sql/test_random_distribution/R/test_random_distribution_tablet_prune
  test/sql/test_random_distribution/T/test_random_distribution_tablet_prune
Labels: 3.3

#49330 [Enhancement] Optimize text based mv rewrite performance
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryMaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTextBasedRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteMetricsTest.java
Labels: 3.2, META-REVIEW, 3.3

#48104 [Enhancement][FlatJson] support multi-layer flat json
  be/src/column/column_access_path.cpp
  be/src/column/column_access_path.h
  be/src/column/json_column.cpp
  be/src/column/json_column.h
  be/src/common/config.h
  be/src/exec/tablet_scanner.cpp
  be/src/exprs/cast_expr.cpp
  be/src/exprs/json_functions.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/compaction_utils.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/general_tablet_writer.h
  be/src/storage/lake/pk_tablet_writer.cpp
  be/src/storage/lake/tablet.cpp
  be/src/storage/lake/tablet_writer.h
  be/src/storage/lake/versioned_tablet.cpp
  be/src/storage/olap_common.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/column_writer.h
  be/src/storage/rowset/json_column_compactor.cpp
  be/src/storage/rowset/json_column_compactor.h
  be/src/storage/rowset/json_column_iterator.cpp
  be/src/storage/rowset/json_column_iterator.h
  be/src/storage/rowset/json_column_writer.cpp
  be/src/storage/rowset/json_column_writer.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer_context.h
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/rowset/segment_writer.h
  be/src/storage/tablet_updates.cpp
  be/src/util/json.cpp
  be/src/util/json.h
  be/src/util/json_flattener.cpp
  be/src/util/json_flattener.h
  be/test/CMakeLists.txt
  be/test/exprs/flat_json_functions_test.cpp
  be/test/exprs/json_functions_test.cpp
  be/test/storage/rowset/flat_json_column_compact_test.cpp
  be/test/storage/rowset/flat_json_column_rw_test.cpp
  be/test/util/json_flattener_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldAccessPathNormalizer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
  gensrc/proto/segment.proto
Labels: PROTO-REVIEW

#49224 [Enhancement] support force delete shard meta
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: 3.1, 3.2, 3.3

#49396 [BugFix] Fix mv rewrite with avg function and having exprs
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/R/test_mv_partition_compensate_mysql
  test/sql/test_materialized_view/R/test_mv_rewrite_with_agg
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/T/test_mv_partition_compensate_mysql
  test/sql/test_materialized_view/T/test_mv_rewrite_with_agg
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_event_trigger_and_nested_mvs
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_event_trigger_and_nested_mvs
Labels: 3.2, 3.3

#49385 [Enhancement] Support json logical type in parquet files()
  be/src/exec/parquet_schema_builder.cpp
  test/sql/test_files/R/json_parquet
  test/sql/test_files/T/json_parquet
  test/sql/test_files/parquet_format/json.parquet
Labels: 3.2, 3.3

#49341 [BugFix] fix concurrent issue between primary index unload and compaction
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/test/storage/lake/local_pk_index_manager_test.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 3.1, 3.2, 3.3

#49416 [BugFix] Fix use after free in partition_meta table
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp
Labels: 3.3

#49433 [BugFix] Fix NPE when replaying of adding sub partition
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
Labels: 3.3

#49125 [BugFix] Fix auto bucket delete job
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/OlapDeleteJob.java
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
  test/sql/test_load_profile/T/test_load_profile
Labels: 3.2, 3.3

#49436 [Enhancement] Support const folding for replace()
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 3.3

#49457 [Tool] Auto translate
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/translate.yml
  docs/translation/configs/config.yaml
  docs/translation/configs/evaluation_prompt.txt
  docs/translation/configs/human_prompt.txt
  docs/translation/configs/language_dicts/zh.yaml
  docs/translation/configs/system_prompt.txt
Labels: documentation

#49098 [Enhancement] Support mutable bucket num table property
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  gensrc/thrift/AgentService.thrift
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_bucket/T/test_automatic_partition
Labels: 3.2, META-REVIEW, PROTO-REVIEW, 3.3

#49010 [BugFix] Fix ConsistencyChecker error dropping tablet if creating table takes too long
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.1, 3.2, 3.3

#49323 [BugFix] Fix the bug that the backend of other clusters is added to the current cluster when synchronizing Olap external table metadata
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/SchemaTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.3

#49453 [Doc]Update EN feature support docs
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/en/using_starrocks/feature-support-asynchronous-materialized-views.md
Labels: documentation, 3.1, 3.2, 3.3

#49452 [Doc] Update CN feature support doc
  docs/zh/data_source/feature-support-data-lake-analytics.md
  docs/zh/using_starrocks/feature-support-asynchronous-materialized-views.md
Labels: documentation, 3.1, 3.2, 3.3

#49054 [BugFix] fix column overflow when handle too large partial update
  be/src/common/config.h
  be/src/storage/rowset/horizontal_update_rowset_writer.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/rowset_meta.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/test/storage/rowset_column_partial_update_test.cpp
  gensrc/proto/olap_file.proto
Labels: 3.2, PROTO-REVIEW, 3.3

#49459 [Doc] Update feature-support-shared-data.md
  docs/en/deployment/shared_data/feature-support-shared-data.md
  docs/zh/deployment/shared_data/feature-support-shared-data.md
Labels: documentation, 3.1, 3.2, 3.3

#49280 [Doc] Add Rename Column doc
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, 3.3

#49284 [Doc] Add doc - ZSTD supports compression level
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
Labels: documentation, 3.3

#49338 [Doc] Add new FE BE param for 3.3.2
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3

#49383 [Doc] Note for AWS S3 authentication in shared-data
  docs/en/deployment/shared_data/s3.md
  docs/zh/deployment/shared_data/s3.md
Labels: documentation, 3.1, 3.2, 3.3

#49450 [BugFix] Fix incorrect generated column serialized data for dictionary_get expression
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  test/sql/test_dictionary/R/test_dictionary
  test/sql/test_dictionary/T/test_dictionary
Labels: 3.3

#49282 [Doc] Add doc - Read Iceberg Views
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/zh/data_source/feature-support-data-lake-analytics.md
Labels: documentation, 3.1, 3.2, 3.3

#49283 [Doc] Remove read iceberg view from 3.3.1
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#49339 [Doc] Add notes to information schema views not applicable
  docs/en/reference/information_schema/column_privileges.md
  docs/en/reference/information_schema/engines.md
  docs/en/reference/information_schema/events.md
  docs/en/reference/information_schema/key_column_usage.md
  docs/en/reference/information_schema/partitions.md
  docs/en/reference/information_schema/referential_constraints.md
  docs/en/reference/information_schema/routines.md
  docs/en/reference/information_schema/schema_privileges.md
  docs/en/reference/information_schema/statistics.md
  docs/en/reference/information_schema/table_constraints.md
  docs/en/reference/information_schema/table_privileges.md
  docs/en/reference/information_schema/triggers.md
  docs/en/reference/information_schema/user_privileges.md
  docs/zh/reference/information_schema/column_privileges.md
  docs/zh/reference/information_schema/engines.md
  docs/zh/reference/information_schema/events.md
  docs/zh/reference/information_schema/key_column_usage.md
  docs/zh/reference/information_schema/partitions.md
  docs/zh/reference/information_schema/referential_constraints.md
  docs/zh/reference/information_schema/routines.md
  docs/zh/reference/information_schema/schema_privileges.md
  docs/zh/reference/information_schema/statistics.md
  docs/zh/reference/information_schema/table_constraints.md
  docs/zh/reference/information_schema/table_privileges.md
  docs/zh/reference/information_schema/triggers.md
  docs/zh/reference/information_schema/user_privileges.md
Labels: documentation, 3.2, 3.3

#49462 [Doc] Update Default for qe_max_connection
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#49393 [Enhancement] Support show create view for connector view
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowCreateTableStmt.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveViewTest.java
  test/sql/test_hive/R/test_hive_view
  test/sql/test_hive/T/test_hive_view
Labels: 3.3

#49325 [Doc] Add/Drop fields in STRUCT
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
Labels: documentation, 3.2, 3.3

#49062 [Doc] Update ALTER_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
Labels: documentation

#49227 [Enhancement] add trace for MVTextRewrite in optimizer
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
Labels: 3.1, 3.2, 3.3

#49212 [BugFix] [Enhancement] Fix nullptr and support Iceberg null padding
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/meta_helper.h
  be/test/formats/parquet/iceberg_schema_evolution_file_reader_test.cpp
Labels: behavior_changed, 3.2, 3.3

#49526 [BugFix] Remove json value from error message
  be/src/exec/json_parser.cpp
  be/test/exec/json_parser_test.cpp
Labels: 3.1, 3.2, 3.3

#49518 [BugFix] fix error message of kill
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.2, 3.3

#49541 [Doc] Test of auto-translate
  docs/en/quick_start/quick_start.mdx
Labels: documentation, 3.1, 3.2, 3.3

#49517 [BugFix] Fix orc tinyint on aarch64
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.cc
  test/sql/test_files/R/orc_tinyint_aarch64
  test/sql/test_files/T/orc_tinyint_aarch64
  test/sql/test_files/orc_format/tinyint.orc
Labels: 3.1, 3.2, 3.3

#49346 [Feature] Support write vector index
  be/src/common/config.h
  be/src/runtime/snapshot_loader.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/index/index_descriptor.h
  be/src/storage/index/inverted/clucene/clucene_inverted_reader.cpp
  be/src/storage/index/inverted/clucene/clucene_inverted_writer.cpp
  be/src/storage/index/inverted/clucene/match_operator.cpp
  be/src/storage/index/vector/tenann/tenann_index_builder.cpp
  be/src/storage/index/vector/tenann/tenann_index_builder.h
  be/src/storage/index/vector/tenann/tenann_index_utils.cpp
  be/src/storage/index/vector/tenann/tenann_index_utils.h
  be/src/storage/index/vector/vector_index_builder.cpp
  be/src/storage/index/vector/vector_index_builder.h
  be/src/storage/index/vector/vector_index_builder_factory.cpp
  be/src/storage/index/vector/vector_index_builder_factory.h
  be/src/storage/index/vector/vector_index_writer.cpp
  be/src/storage/index/vector/vector_index_writer.h
  be/src/storage/rowset/array_column_writer.cpp
  be/src/storage/rowset/column_writer.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/segment_replicate_executor.cpp
  be/src/storage/tablet_meta.h
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/test/CMakeLists.txt
  be/test/storage/index/vector_index_test.cpp
  gensrc/proto/data.proto
  gensrc/proto/tablet_schema.proto
  gensrc/proto/types.proto
  test/sql/test_vector_index/R/test_vector_index
  test/sql/test_vector_index/T/test_vector_index
Labels: PROTO-REVIEW

#49437 [BugFix] Fix partition live number not update
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TablePropertyTest.java
Labels: 3.1, 3.2, 3.3

#49126 [Enhancement] Do not swallow connector exception for hive acid table
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
Labels: 3.3

#49141 [Enhancement] Support Iceberg rest catalog with vended credential disabled
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/pom.xml
Labels: behavior_changed, 3.3

#49195 [Enhancement] Physical partitions in the same logical partition use the same shard_group_id to make the shard distribution more even
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: 3.2, 3.3

#49511 [Enhancement] optimize common expression reuse strategy in lambda functions
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 3.2, 3.3

#49540 [Doc] The batch_size parameter has been deprecated and should be replaced by chunk_size.
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#48350 [Doc]fix doc of ngram index
  docs/en/table_design/indexes/Ngram_Bloom_Filter_Index.md
  docs/zh/table_design/indexes/Ngram_Bloom_Filter_Index.md
Labels: documentation, 3.3

#49376 [BugFix] Fix incorrect compaction status show in JSON format
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.1, 3.2, 3.3

#49539 [BugFix] Missing backends information when determining whether to use distributed plan mode
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
Labels: 3.3

#49555 [BugFix] use real iceberg file content id
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScanner.java
Labels: 3.3

#49425 [Enhancement] Fix cve problems in java-extensions module
  build.sh
  java-extensions/common-runtime/pom.xml
  java-extensions/hadoop-ext/pom.xml
  java-extensions/hive-reader/pom.xml
  java-extensions/hive-reader/src/test/java/com/starrocks/hive/reader/TestHiveScanner.java
  java-extensions/hudi-reader/pom.xml
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiColumnValue.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiScannerUtils.java
  java-extensions/hudi-reader/src/test/java/com/starrocks/hudi/reader/TestHudiSliceScanner.java
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/java-utils/pom.xml
  java-extensions/java-utils/src/main/java/com/starrocks/utils/Platform.java
  java-extensions/jdbc-bridge/pom.xml
  java-extensions/jni-connector/pom.xml
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapColumnVector.java
  java-extensions/jni-connector/src/test/java/TestColumnType.java
  java-extensions/jni-connector/src/test/java/TestScannerHelper.java
  java-extensions/jni-connector/src/test/java/TestSelectedFields.java
  java-extensions/kudu-reader/pom.xml
  java-extensions/kudu-reader/src/test/java/com/starrocks/kudu/reader/TestKuduSplitScanner.java
  java-extensions/odps-reader/pom.xml
  java-extensions/paimon-reader/pom.xml
  java-extensions/paimon-reader/src/test/java/com/starrocks/paimon/reader/TestPaimonSplitScanner.java
  java-extensions/pom.xml
  java-extensions/udf-examples/pom.xml
  java-extensions/udf-extensions/pom.xml
  java-extensions/udf-extensions/src/main/java/com/starrocks/udf/UDFSecurityManager.java
  java-extensions/udf-extensions/src/test/java/com/starrocks/udf/CallStubGeneratorTest.java
  java-extensions/udf-extensions/src/test/java/com/starrocks/udf/FunctionStatesTest.java
  java-extensions/udf-extensions/src/test/java/com/starrocks/udf/SecurityTest.java
  run-java-exts-ut.sh
Labels: 3.3

#49469 [Enhancement] adapt MergeLimitDirectRule to iceberg metadata table
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MergeLimitDirectRule.java
  test/sql/test_iceberg/R/test_metadata_table
  test/sql/test_iceberg/T/test_metadata_table
Labels: 3.3

#49094 [Enhancement] desc iceberg table with transform type
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  test/sql/test_iceberg/R/test_iceberg_show_stmt
  test/sql/test_iceberg/T/test_iceberg_show_stmt
Labels: 3.2, 3.3

#49576 [Doc] Add 3.3.2 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#49590 [Doc] Add 3.3 downgrade warning
  docs/en/deployment/downgrade.md
  docs/zh/deployment/downgrade.md
Labels: documentation, 3.3

#49503 [Enhancement] Provide clear error message if skip_headers is set in select from files option
  be/src/exec/csv_scanner.cpp
  be/test/exec/csv_scanner_test.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#46085 [Enhancement] Add broker address in broker rpc error message
  be/src/fs/fs_broker.cpp
  be/test/fs/fs_broker_test.cpp
Labels: 3.1, behavior_changed, 3.2, 3.3

#46786 [BugFix] Fix mv partition prune failed when partition column predicate with function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
Labels: 3.3

#47198 [Enhancement] Optimize performance of get physical partition from olap table
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.2, 3.3

#49569 [BugFix] fix iceberg partition prune on v2 table
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  test/sql/test_iceberg/R/test_iceberg_transformed_partition
  test/sql/test_iceberg/T/test_iceberg_transformed_partition
Labels: 3.3

#49609 [Enhancement] add maxStringLength for JsonTemplateLayout
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.2, 3.3

#49510 [Doc] update datacache populate doc
  docs/en/data_source/data_cache.md
  docs/en/data_source/data_cache_observe.md
  docs/en/reference/System_variable.md
  docs/zh/data_source/data_cache.md
  docs/zh/data_source/data_cache_observe.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.3

#49395 [BugFix] Fix http server direct buffer leak for request body
  fe/fe-core/src/main/java/com/starrocks/http/HttpServerHandler.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
Labels: 2.5, 3.1, 3.2, 3.3

#49430 [Enhancement] Enable dynamic partition pruning for non-slot-ref probe expr
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/subfield_expr.cpp
  test/sql/test_dpp/R/test_dpp
  test/sql/test_dpp/T/test_dpp
Labels: 3.3

#45338 [Enhancement] Support mv refresh to use materialized view rewrite by enable_mv_refresh_query_rewrite config
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPlanBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PCTRefreshListPartitionOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorJdbcTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorPaimonTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_event_trigger
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_multi_union3
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_mv_reuse
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_event_trigger
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_multi_union3
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_mv_reuse
  test/test_sql_cases.py
Labels: 3.3

#49318 [Enhancement] optimize schema scan execution
  be/src/exec/pipeline/pipeline.cpp
  be/src/exec/pipeline/scan/chunk_source.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.cpp
  be/src/exec/pipeline/scan/schema_chunk_source.h
Labels: 3.2, 3.3

#49598 [Enhancement] Optimize concurrency of broker load from local file
  fe/fe-core/src/main/java/com/starrocks/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/com/starrocks/sql/LoadPlanner.java
  fe/fe-core/src/test/java/com/starrocks/load/LoadPlannerTest.java
Labels: 3.1, 3.2, 3.3

#49619 [BugFix] Fix thrift rpc not reopen after failed
  be/src/exec/pipeline/audit_statistics_reporter.cpp
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/util/thrift_rpc_helper.cpp
  be/test/util/thrift_rpc_helper_test.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#49455 [Feature] support iceberg partitions table
  be/src/runtime/descriptors.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataTableType.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergMetadataTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergPartitionsTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalIcebergMetadataScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/IcebergPartitionsTableRewriteRule.java
  gensrc/thrift/Types.thrift
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/iceberg/IcebergPartitionUtils.java
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergFilesTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergManifestsTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataColumnValue.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScannerFactory.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergPartitionsTableScanner.java
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergRefsTableScanner.java
  java-extensions/pom.xml
  test/sql/test_iceberg/R/test_metadata_table
  test/sql/test_iceberg/T/test_metadata_table
Labels: PROTO-REVIEW

#49622 [UT] Add csv split scan ut
  be/test/exec/csv_scanner_test.cpp
Labels: 3.3

#49633 [Enhancement] fix common expression reuse issue in MapOperator
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 3.2, 3.3

#49618 [Enhancement] Add tracer for delta log reader
  fe/fe-core/src/main/java/com/starrocks/common/profile/TimeWatcher.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeEngine.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeJsonHandler.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeParquetHandler.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/TraceDefaultJsonHandler.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/TraceDefaultParquetHandler.java
  test/sql/test_deltalake/R/test_deltalake_trace
  test/sql/test_deltalake/T/test_deltalake_trace
Labels: 3.3

#49442 [Enhancement] evaluate SchemaTable in FE
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/TaskRunsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SchemaTableEvaluateRule.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: 3.3

#49648 [BugFix] fix counter compressed_size
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
Labels: 3.1, 3.2, 3.3

#49649 [Enhancement] upgrade iceberg version to 1.6.0
  fe/fe-core/pom.xml
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/iceberg/SerializableTable.java
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/pom.xml
Labels: 3.3

#49611 [Enhancement] Add big query error in audit log
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/exec/workgroup/work_group.cpp
  fe/fe-core/src/main/java/com/starrocks/http/HttpConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  gensrc/thrift/StatusCode.thrift
  test/sql/test_resource_group/R/test_resource_group_big_query
  test/sql/test_resource_group/T/test_resource_group_big_query
Labels: 2.5, 3.0, 3.1, 3.2, PROTO-REVIEW, 3.3

#49688 [Doc] User Variable supports ARRAY
  docs/en/reference/user_defined_variables.md
  docs/zh/reference/user_defined_variables.md
Labels: documentation, 3.2, 3.3

#49690 [BugFix] fix type mismatch error in meta scan count
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggToMetaScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToMetaScanRule.java
  test/sql/test_agg/R/test_meta_scan_agg
  test/sql/test_agg/T/test_meta_scan_agg
Labels: 3.0, 3.1, 3.2, 3.3

#49692 [BugFix]s3 bytes range contain first and last byte
  be/src/io/s3_input_stream.cpp
Labels: 3.3

#48860 [Enhancement] configure S3 client rename_file operation timeout
  be/src/common/config.h
  be/src/fs/fs_s3.cpp
  be/test/fs/fs_s3_test.cpp
Labels: behavior_changed

#49702 [BugFix] make sure metadata cache quit safety
  be/src/storage/rowset/rowset.cpp
  be/src/storage/tablet_manager.h
Labels: 3.2, 3.3

#49519 [Enhancement] cancel all fragments when query finished
  be/src/exec/pipeline/fragment_context.cpp
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  gensrc/proto/internal_service.proto
Labels: PROTO-REVIEW

#49710 [Enhancement] Modify ErrorReportException from return String to Exception
  fe/fe-core/src/main/java/com/starrocks/common/ErrorReportException.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/OlapDeleteJob.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlPassword.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AccessDeniedException.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionDescAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/common/util/KafkaUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseManagerTest.java
Labels: 3.3

#49391 [Enhancement] optimize MIN/MAX on partition columns
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PartitionColumnMinMaxRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.3

#49444 [BugFix] Fix pk get error ouput rowset schema during compaction
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/tablet_manager_test.cpp
Labels: 3.3

#49712 [Enhancement] information_schema.columns support generated column expression
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: behavior_changed, PROTO-REVIEW, 3.3

#49722 [BugFix] Support to access s3n:// path
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudConfiguration.java
Labels: 3.0, 3.1, 3.2, 3.3

#49550 [BugFix] fix del encryption upgrade issue
  be/src/storage/lake/pk_tablet_writer.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/test_util.h
Labels: 3.3

#49734 [Enhancement] information_schema.columns support generated column expression (backport #49712)
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: behavior_changed

#49124 [BugFix] Fix the miss LakeTable schema change / OlapTable rollup schema change hang when FE meets runtime exception
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
Labels: 3.2, 3.3

#49670 [BugFix] Fix spillable hash join wrong result when split partition yield
  be/src/exec/spill/data_stream.cpp
  be/src/exec/spill/data_stream.h
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/input_stream.h
  be/src/exec/spill/mem_table.cpp
  be/src/exec/spill/mem_table.h
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
Labels: 3.3

#49542 [Enhancement] Optimize routine load task schedule strategy, the distribution of nodes is as even as possible in scenarios with large differences in task scale.
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadManagerTest.java
Labels: 3.2, 3.3

#49732 [Enhancement] Security Fixes
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: 3.3

#49757 [Enhancement] Introduce trivy to detect cve problems
  fe/fe-core/pom.xml
  java-extensions/paimon-reader/pom.xml
  trivy.yaml
Labels: 3.3

#49392 [Enhancement] Move column schema change and modify properties from db lock to table level lock
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddRollupClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterLoadErrorUrlClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterTableClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterTableColumnClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BackendClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnRenameClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CompactionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropRollupClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/FrontendClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ModifyBackendClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ModifyBrokerClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ModifyPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionRenameClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ReplacePartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RollupRenameClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableRenameClause.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/BatchRollupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterDataCachePartitionDurationTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerWithMVTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AddRollupClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DropRollupClauseTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ListPartitionDescTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVRewriteWithSchemaChangeTest.java
  test/sql/test_add_drop_field/R/test_add_drop_field
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_column_rename/R/test_column_rename
  test/sql/test_function/R/test_substr
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_materialized_view/R/test_mv_swap
  test/sql/test_storage_volume/R/set_as_default
  test/sql/test_task/R/test_drop
Labels: 3.3

#49771 [Doc] Update SMT.md
  docs/en/integrations/loading_tools/SMT.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#49763 [UT] clean files and dirs after UT finished
  be/test/storage/lake/lake_data_source_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  be/test/storage/meta_reader_test.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 3.3

#49742 [BugFix] Fix spill preagg miss rows when has streaming chunks
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  test/sql/test_spill/R/test_spill_agg_streaming_strategy
  test/sql/test_spill/T/test_spill_agg_streaming_strategy
Labels: 3.1, 3.2, 3.3

#49746 [BugFix] fix redundant partition info in CompactionManager meta
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
Labels: 3.1, 3.2, 3.3

#49755 [BugFix] fix common expr reuse issue in nested lambda expr
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuseRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorsReuseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 3.2, 3.3

#46903 [Doc] Add more docs about materialized views
  docs/en/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-manipulation/CANCEL_REFRESH_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-manipulation/DROP_TASK.md
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CANCEL_REFRESH_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-manipulation/DROP_TASK.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_MATERIALIZED_VIEW.md
Labels: documentation, 3.3

#49431 [Enhancement] Make `warehouse` variable session accessable only
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
Labels: behavior_changed, 3.3

#49769 [BugFix] Fix error create table sql
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  test/sql/test_fast_schema_evolution/R/test_fast_schema_evolution
  test/sql/test_fast_schema_evolution/T/test_fast_schema_evolution
Labels: 3.2, 3.3

#49824 [Enhancement] Ignore apache-hdfs-broker cve in trivy
  trivy.yaml
Labels: 3.3

#49828 [Feature] Support setting session vars in user property (backport #48477)
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UserProperty.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/persist/AlterUserInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteAsExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowUserPropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseCreateAlterUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateUserStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowUserPropertyStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/UserPropertyTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ExecuteAsStmtTest.java
Labels: META-REVIEW

#49812 [Enhancement] Support Lock auto closeable
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/AutoCloseableLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/AutoCloseableLockerTest.java
Labels: 3.3

#49845 [Doc] Add backup restore notes to references
  docs/en/sql-reference/sql-statements/data-definition/backup_restore/BACKUP.md
  docs/en/sql-reference/sql-statements/data-definition/backup_restore/RESTORE.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/BACKUP.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/RESTORE.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#49842 [BugFix] fix wrong sched_entity for schema_chunk_source
  be/src/exec/pipeline/scan/schema_chunk_source.cpp
Labels: 3.2, 3.2-merged, 3.3

#49449 [Enhancement] Add memory alloc profile log
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: 3.3

#49837 [BugFix] Fix pipe insert sql does not have credentials
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/FilePipeSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/StorageVolumeAnalysisTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectUsingAliasTest.java
  test/sql/test_pipe/R/basic
  test/sql/test_pipe/T/basic
Labels: 3.2, 3.3

#49756 [UT] dynamic link libstdc++ when build test with ASAN
  be/CMakeLists.txt
  run-be-ut.sh
Labels: 3.3

#49807 [Doc] List Partitioning does not support partition live number
  docs/en/table_design/expression_partitioning.md
  docs/zh/table_design/expression_partitioning.md
Labels: documentation, 3.1, 3.2, 3.3

#49818 [Doc] Minor Upgrade note
  docs/en/deployment/downgrade.md
  docs/en/deployment/upgrade.md
  docs/zh/deployment/downgrade.md
  docs/zh/deployment/upgrade.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#49881 [Doc]Update BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.2, 3.3

#49882 [Doc]Update BE_configuration.md
  docs/en/administration/management/BE_configuration.md
Labels: documentation, 3.2, 3.3

#49836 [Enhancement] Enable delta lake checkpoint meta cache by default
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeCatalogProperties.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeParquetHandler.java
  fe/fe-core/src/test/java/com/starrocks/connector/delta/DeltaLakeParquetHandlerTest.java
Labels: 3.3

#49843 [BugFix] Fix remove task NPE since db not exists
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: 3.1, 3.2, 3.3

#49764 [BugFix] Fix replace temp partition bug for multi column partition table
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  test/sql/test_automatic_partition/R/test_replace_temp_partition
  test/sql/test_automatic_partition/T/test_replace_temp_partition
Labels: 3.0, 3.1, 3.2, 3.3

#48262 [Enhancement] Improve cache select performance
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cache_options.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/CMakeLists.txt
  be/src/exec/cache_select_scanner.cpp
  be/src/exec/cache_select_scanner.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_orc.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/src/formats/CMakeLists.txt
  be/src/formats/disk_range.hpp
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
  be/src/formats/orc/orc_input_stream.h
  be/src/formats/orc/utils.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/io/CMakeLists.txt
  be/src/io/cache_input_stream.h
  be/src/io/cache_select_input_stream.hpp
  be/test/CMakeLists.txt
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/iceberg/iceberg_delete_builder_test.cpp
  be/test/formats/disk_range_test.cpp
  be/test/formats/orc/utils_test.cpp
  be/test/formats/parquet/column_converter_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/file_writer_test.cpp
  be/test/formats/parquet/iceberg_schema_evolution_file_reader_test.cpp
  be/test/formats/parquet/page_index_test.cpp
  be/test/formats/parquet/parquet_cli_reader.h
  be/test/formats/parquet/parquet_file_writer_test.cpp
  be/test/formats/parquet/parquet_footer_test.cpp
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_datacache/R/test_datacache_select
  test/sql/test_datacache/T/test_datacache_select
Labels: PROTO-REVIEW, 3.3
