Repository StarRocks/starrocks, pull requests merged in 2024-05, with the labels that each got.

#44668 [Doc] range partitioning column supports timestamp&string
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/table_design/Data_distribution.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/table_design/Data_distribution.md
Labels: documentation, 3.3

#45004 [Doc] Add 3.3 support for Amazon S3 Express One Zone Storage
  docs/en/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.3

#45014 [BugFix] fix ctas and statistics collect issues on temporary tables
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  test/sql/test_temporary_table/R/temporary_table
  test/sql/test_temporary_table/T/temporary_table
Labels: 3.3

#45038 [BugFix] Check format length for jodadatetime_format
  be/src/exprs/time_functions.cpp
  be/src/runtime/datetime_value.cpp
  test/sql/test_datetime/R/test_jodatime_format
  test/sql/test_datetime/T/test_jodatime_format
Labels: 3.0, 3.1, 3.2, 3.3

#45029 [Enhancement] Remove `internal_service_async_thread_num`
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
Labels: 2.5, 3.0, behavior_changed

#44420 [Refactor] Add curly braces {} for switch case in edit log
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
Labels: META-REVIEW

#44965 [Enhancement] Enable read pindex by page by default
  be/src/common/config.h
Labels: 3.1, behavior_changed, 3.2, 3.3

#45035 [BugFix]nullable column xor_checksum always calc the whole column
  be/src/column/nullable_column.cpp
  be/test/column/nullable_column_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45070 [Enhancement] Adds config to set socket_keepalive for brpc. Needs brpc 1.8
  be/CMakeLists.txt
  be/src/common/config.h
  be/src/service/service_be/starrocks_be.cpp
  build.sh
Labels: 3.2, 3.3

#45084 [Doc] Add 3.3 MV supports Iceberg Partition Transform
  docs/en/using_starrocks/create_partitioned_materialized_view.md
  docs/en/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
  docs/zh/using_starrocks/create_partitioned_materialized_view.md
  docs/zh/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
Labels: documentation, 3.2, 3.3

#44616 [Enhancement] support disable lake compaction
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSelector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/Selector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/SimpleSelector.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/SimpleSelectorTest.java
Labels: documentation, 3.2, 3.3

#39321 [Doc] add flat json doc - 3.3
  docs/docusaurus/sidebars.json
  docs/en/administration/management/BE_configuration.md
  docs/en/assets/flat_json.png
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_bool.md
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_int.md
  docs/en/using_starrocks/Flat_json.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/assets/flat_json.png
  docs/zh/reference/System_variable.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_bool.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/get_json_int.md
  docs/zh/using_starrocks/Flat_json.md
Labels: documentation, 3.3

#44766 [Doc] add config (metadata lock at table level)
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3

#44825 [BugFix] initilize editLog in StarOSBDBJEJournalSystem
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
  fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java
Labels: 3.3

#44758 [Doc] deplicate key table, aggregate table & unique key table support order by
  docs/en/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/table_design/StarRocks_table_design.md
  docs/en/table_design/indexes/Prefix_index_sort_key.md
  docs/en/table_design/table_types/aggregate_table.md
  docs/en/table_design/table_types/duplicate_key_table.md
  docs/en/table_design/table_types/table_capabilities.md
  docs/en/table_design/table_types/table_types.md
  docs/en/table_design/table_types/unique_key_table.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/table_design/StarRocks_table_design.md
  docs/zh/table_design/indexes/Prefix_index_sort_key.md
  docs/zh/table_design/table_types/aggregate_table.md
  docs/zh/table_design/table_types/duplicate_key_table.md
  docs/zh/table_design/table_types/table_capabilities.md
  docs/zh/table_design/table_types/table_types.md
  docs/zh/table_design/table_types/unique_key_table.md
Labels: documentation, 3.3

#44947 [Doc] Add CSV support for Files
  docs/en/assets/commonMarkdown/loadMethodIntro.md
  docs/en/loading/azure.md
  docs/en/loading/cloud_storage_load.md
  docs/en/loading/gcs.md
  docs/en/loading/hdfs_load.md
  docs/en/loading/minio.md
  docs/en/loading/s3.md
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/unloading/unload_using_insert_into_files.md
  docs/zh/assets/commonMarkdown/loadMethodIntro.md
  docs/zh/loading/azure.md
  docs/zh/loading/cloud_storage_load.md
  docs/zh/loading/gcs.md
  docs/zh/loading/hdfs_load.md
  docs/zh/loading/minio.md
  docs/zh/loading/s3.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/unloading/unload_using_insert_into_files.md
Labels: documentation, 3.3

#45074 [Doc] Add labels on BEs
  docs/docusaurus/sidebars.json
  docs/en/administration/management/resource_management/be_label.md
  docs/zh/administration/management/resource_management/be_label.md
Labels: documentation, 3.3

#45116 [Enhancement] support disable lake compaction (backport #44616)
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/ScoreSelector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/Selector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/SimpleSelector.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/ScoreSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/SimpleSelectorTest.java
Labels: documentation

#45076 [Doc] add inverted index
  docs/docusaurus/sidebars.json
  docs/en/table_design/indexes/inverted_index.md
  docs/zh/table_design/indexes/inverted_index.md
Labels: documentation, 3.3

#40841 [Doc] add doc for ngram index
  docs/docusaurus/sidebars.json
  docs/en/sql-reference/sql-functions/function-list.md
  docs/en/sql-reference/sql-functions/string-functions/ngram_search.md
  docs/en/table_design/indexes/Ngram_Bloom_Filter_Index.md
  docs/zh/sql-reference/sql-functions/function-list.md
  docs/zh/sql-reference/sql-functions/string-functions/ngram_search.md
  docs/zh/table_design/indexes/Ngram_Bloom_Filter_Index.md
Labels: documentation

#44695 [BugFix] Use correct warehouseId when stream load is used to load data
  be/src/exec/tablet_sink.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/action/transaction_stream_load.cpp
  be/src/runtime/stream_load/stream_load_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/DefaultWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Warehouse.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.3

#45128 [Doc] Fix starlet_use_star_cache default
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#43933 [BugFix] Fix duplicate metric labels
  fe/fe-core/src/main/java/com/starrocks/metric/Metric.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricsTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45040 [BugFix] fix not sending a correct eof packet
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  test/lib/sr_sql_lib.py
  test/requirements.txt
  test/sql/test_preparestatement/R/test_driver_prepare
  test/sql/test_preparestatement/T/test_driver_prepare
Labels: 3.1, 3.2, 3.3

#45104 [Enhancement] add config enable_temporary_table_statistic_collect
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  test/sql/test_temporary_table/R/temporary_table
  test/sql/test_temporary_table/T/temporary_table
Labels: 3.3

#45061 [BugFix] make iceberg db/table name to lower case for hive/glue catalog
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
Labels: 3.2, 3.3

#45142 [Doc] Remove extra --daemon
  docs/en/administration/management/enable_fqdn.md
  docs/zh/administration/management/enable_fqdn.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#44111 [BugFix] Broadcast Join should not generate nondetermistic GRF
  be/src/exec/aggregate/aggregate_base_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/project_node.cpp
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterPushDownContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_runtime_filter_push_down_on_left_join/R/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_left_join/T/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/R/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/T/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#44153 [Enhancement] frontend RPC error message
  be/src/runtime/client_cache.h
  be/src/util/thrift_rpc_helper.cpp
  be/src/util/thrift_rpc_helper.h
  be/test/CMakeLists.txt
  be/test/util/thrift_rpc_helper_test.cpp
Labels: 3.1, 3.2, 3.3

#45099 [Enhancement] Support datacache metrics display in compute node
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectMetrics.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DataCacheSelectMetricsTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.3

#45107 [Enhancement] Add host start time info on BE start
  bin/start_backend.sh
  bin/start_fe.sh
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#44331 [Enhancement] Improve insert column mismatch error message
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_scan/test_pushdown_or_predicate/R/test_parse_and_rewrite_or_predicate
Labels: 3.1, behavior_changed, 3.2, 3.3

#45102 [BugFix] Unfold partition const column before comparing partition range
  be/src/exec/tablet_info.cpp
  test/sql/test_partition_by_expr/R/test_expr_from_unixtime
  test/sql/test_partition_by_expr/T/test_expr_from_unixtime
Labels: 3.2, 3.3

#45034 [BugFix] fix bug of array_genearate
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeArrayTest.java
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
Labels: 3.0, 3.1, 3.2, 3.3

#45144 [BugFix]fix uncorrectly probing hash table in null safe join condition
  be/src/exec/join_hash_map.cpp
  test/sql/test_join/R/test_null_safe_equal
  test/sql/test_join/T/test_null_safe_equal
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45176 [BugFix] Broadcast Join should not generate nondetermistic GRF (backport #44111)
  be/src/exec/aggregate/aggregate_base_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/project_node.cpp
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RuntimeFilterTest.java
  test/sql/test_runtime_filter_push_down_on_left_join/R/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_left_join/T/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/R/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/T/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
Labels: automerge, backport_ok, version:3.2.7

#42540 [Enhancement] enable SQLDigest, but not over than slow query time, sh…
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
Labels: 3.2

#45101 [BugFix] Fix be calling fe not setting rpc timeout
  be/src/exec/pipeline/audit_statistics_reporter.cpp
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/runtime/fragment_mgr.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45177 [BugFix] Broadcast Join should not generate nondetermistic GRF (backport #44111)
  be/src/exec/aggregate/aggregate_base_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/project_node.cpp
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RuntimeFilterTest.java
  test/sql/test_runtime_filter_push_down_on_left_join/R/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_left_join/T/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/R/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/T/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
Labels: automerge, backport_ok, version:3.1.12

#45181 [BugFix] Broadcast Join should not generate nondetermistic GRF (backport #44111)
  be/src/exec/aggregate/aggregate_base_node.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/project_node.cpp
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_runtime_filter_push_down_on_left_join/R/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_left_join/T/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/R/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/T/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
Labels: automerge, backport_ok, version:3.0.10

#44693 [BugFix] Fix show routine load when warehouse not exist
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseManagerTest.java
Labels: 3.3

#45117 [BugFix] interleaving join can't support joins with other conjuncts
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/test/exec/join_hash_map_test.cpp
  test/sql/test_join/R/test_interleaving_join
  test/sql/test_join/T/test_interleaving_join
Labels: 3.2, 3.3

#45183 [Enhancement] Remove internal_service_async_thread_num (branch-3.0) (backport #45029)
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
Labels: behavior_changed

#45214 [BugFix] Broadcast Join should not generate nondetermistic GRF (backport #44111)
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/vectorized/aggregate/aggregate_base_node.cpp
  be/src/exec/vectorized/hash_join_node.cpp
  be/src/exec/vectorized/hash_join_node.h
  be/src/exec/vectorized/project_node.cpp
  be/src/exprs/vectorized/runtime_filter_bank.cpp
  be/src/exprs/vectorized/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/JoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_runtime_filter_push_down_on_left_join/R/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_left_join/T/test_runtime_filter_push_down_on_left_join
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/R/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
  test/sql/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf/T/test_runtime_filter_push_down_on_local_right_offsprings_of_broadcast_join_with_grf
Labels: automerge, backport_ok, version:2.5.21

#45174 [BugFix] Fix spark load failure due to not setting tablet version
  be/src/storage/task/engine_batch_load_task.cpp
Labels: 3.3

#45218 [BugFix] fix struct prune fields on uncopy schema
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
Labels: 3.3

#45227 [Doc] update case-sensitive description for column alias
  docs/en/reference/System_limit.md
  docs/en/sql-reference/sql-statements/data-manipulation/SELECT.md
  docs/zh/reference/System_limit.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SELECT.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#43837 [BugFix] Fix Log print error in ReportHandler
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#44662 [Enhancement] Use fair lock to avoid lock starvation
  fe/fe-core/src/main/java/com/starrocks/alter/AlterHandler.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/RepositoryMgr.java
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogManager.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BrokerMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DomainResolver.java
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletMeta.java
  fe/fe-core/src/main/java/com/starrocks/common/ConfigRefreshDaemon.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/FairReentrantLock.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/FairReentrantReadWriteLock.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/QueryableReentrantLock.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/QueryableReentrantReadWriteLock.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorTblMetaInfoMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemotePathKey.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/consistency/MetaRecoveryDaemon.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheMgr.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFs.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/CloseSafeDatabase.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeManager.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/HostBlacklist.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/system/BackendCoreStat.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/common/util/concurrent/QueryableReentrantLockTest.java
Labels: 3.1, 3.2, 3.3

#44611 [BugFix] Fix AgentTask not finished when node as compute node
  be/src/agent/agent_server.cpp
  be/src/agent/agent_task.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 3.2, 3.3

#45239 [BugFix] fix getting timstamp type partition null value when iceberg exists partition evolution
  fe/fe-core/src/main/java/com/starrocks/connector/PartitionUtil.java
  test/lib/sr_sql_lib.py
  test/sql/test_iceberg/R/test_iceberg_catalog
  test/sql/test_iceberg/T/test_iceberg_catalog
Labels: 3.2, 3.3

#45235 [BugFix] Fix dynamic partition table unexpectly stop scheduling
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/CurrentQueryBackendInstanceProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowDynamicPartitionStmt.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TablePropertyTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45243 [BugFix] check session variable when altering mv
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
Labels: 3.1, 3.2, 3.3

#45043 [BugFix] Fix SetStmt to String NPE bug
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: 3.1, 3.2, 3.3

#45265 [BugFix] fix cloudnative tablet compaction threadpool name typo
  be/src/storage/lake/compaction_scheduler.cpp
Labels: 3.1, 3.2, 3.3

#44955 [BugFix] [Refactor] Optimize PartitionBasedMvRefreshProcessor db locks(Part1)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsRegistry.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteMetricsTest.java
Labels: 3.1, 3.2, 3.3

#45275 [BugFix] Fix the bug of bitmap_to_binary/bitmap_to_base64 processing null
  be/src/exprs/bitmap_functions.cpp
  test/sql/test_bitmap_functions/R/test_bitmap_binary
  test/sql/test_bitmap_functions/R/test_bitmap_to_base64
  test/sql/test_bitmap_functions/T/test_bitmap_binary
  test/sql/test_bitmap_functions/T/test_bitmap_to_base64
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#44736 [Doc] add MaxCompute catalog
  docs/docusaurus/sidebars.json
  docs/en/data_source/catalog/maxcompute_catalog.md
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_CREATE_CATALOG.md
  docs/zh/data_source/catalog/maxcompute_catalog.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_CREATE_CATALOG.md
Labels: documentation, 3.3

#45285 [BugFix] Fix order by desc limit regression
  be/src/connector/lake_connector.cpp
  be/src/connector/lake_connector.h
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/lake/tablet_reader.h
  be/src/storage/tablet_reader.cpp
  test/sql/test_sort/R/test_topn
  test/sql/test_sort/T/test_topn
Labels: 3.0, 3.1, 3.2, 3.3

#42285 [BugFix] fix jni-reader for struct type when writing nulls to off heap
  java-extensions/hive-reader/src/test/java/com/starrocks/hive/reader/TestHiveScanner.java
  java-extensions/hive-reader/src/test/resources/test_primitive_type/row_1.avro
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapColumnVector.java
Labels: 3.2

#45319 [BugFix] check session variable when altering mv (backport #45243)
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
Labels: automerge

#45315 [BugFix]fix fe deadlock by static initialization
  fe/fe-core/src/main/java/com/starrocks/analysis/LiteralExpr.java
Labels: 3.2, 3.3

#44981 [Enhancement] [Refactor] Refactor schema scanner & support push predicates into fe for materialized views/task run status
  be/src/exec/pipeline/scan/schema_scan_context.cpp
  be/src/exec/pipeline/scan/schema_scan_context.h
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_be_tablets_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.h
  be/src/exec/schema_scanner/schema_fe_tablet_schedules_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_load_tracking_logs_scanner.cpp
  be/src/exec/schema_scanner/schema_loads_scanner.cpp
  be/src/exec/schema_scanner/schema_materialized_views_scanner.cpp
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp
  be/src/exec/schema_scanner/schema_pipe_files.cpp
  be/src/exec/schema_scanner/schema_pipes.cpp
  be/src/exec/schema_scanner/schema_routine_load_jobs_scanner.cpp
  be/src/exec/schema_scanner/schema_schema_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_schemata_scanner.cpp
  be/src/exec/schema_scanner/schema_stream_loads_scanner.cpp
  be/src/exec/schema_scanner/schema_table_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_tables_config_scanner.cpp
  be/src/exec/schema_scanner/schema_tables_scanner.cpp
  be/src/exec/schema_scanner/schema_task_runs_scanner.cpp
  be/src/exec/schema_scanner/schema_tasks_scanner.cpp
  be/src/exec/schema_scanner/schema_temp_tables_scanner.cpp
  be/src/exec/schema_scanner/schema_user_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_variables_scanner.cpp
  be/src/exec/schema_scanner/schema_views_scanner.cpp
  be/src/exec/schema_scanner/starrocks_grants_to_scanner.cpp
  be/src/exec/schema_scanner/starrocks_role_edges_scanner.cpp
  be/src/exec/schema_scanner/sys_fe_locks.cpp
  be/src/exec/schema_scanner/sys_fe_memory_usage.cpp
  be/src/exec/schema_scanner/sys_object_dependencies.cpp
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_information_schema/R/test_task_run_status
  test/sql/test_information_schema/T/test_task_run_status
  test/sql/test_materialized_view/R/test_mv_swap
  test/sql/test_materialized_view/T/test_mv_swap
Labels: 3.1, 3.2, PROTO-REVIEW, 3.3

#44622 [Enhancement] Faster PK table compaction transaction apply strategy (Part-2 local table)
  be/src/storage/CMakeLists.txt
  be/src/storage/local_primary_key_compaction_conflict_resolver.cpp
  be/src/storage/local_primary_key_compaction_conflict_resolver.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/rows_mapper.cpp
  be/src/storage/rows_mapper.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer.h
  be/src/storage/rowset/rowset_writer_context.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset_merger.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/primary_index_test.cpp
  be/test/storage/rowset/rowset_test.cpp
  be/test/storage/rowset_merger_test.cpp
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.3

#45345 [Doc] some fixes in functions
  docs/en/release_notes/release-3.1.md
  docs/en/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/en/sql-reference/sql-functions/array-functions/element_at.md
  docs/en/sql-reference/sql-functions/date-time-functions/to_tera_date.md
  docs/en/sql-reference/sql-functions/date-time-functions/to_tera_timestamp.md
  docs/en/sql-reference/sql-functions/map-functions/element_at.md
  docs/en/sql-reference/sql-functions/map-functions/map_concat.md
  docs/zh/release_notes/release-3.1.md
  docs/zh/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/zh/sql-reference/sql-functions/array-functions/element_at.md
  docs/zh/sql-reference/sql-functions/date-time-functions/to_tera_date.md
  docs/zh/sql-reference/sql-functions/date-time-functions/to_tera_timestamp.md
  docs/zh/sql-reference/sql-functions/map-functions/element_at.md
  docs/zh/sql-reference/sql-functions/map-functions/map_concat.md
  docs/zh/sql-reference/sql-functions/string-functions/substring_index.md
Labels: documentation, 3.1, 3.2, 3.3

#44389 [Doc] Update current_timestamp.md
  docs/en/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/zh/sql-reference/sql-functions/date-time-functions/current_timestamp.md
Labels: documentation, 2.5, 3.1, 3.2, 3.3

#44047 [Doc]Update ranger_plugin.md
  docs/en/administration/user_privs/ranger_plugin.md
  docs/zh/administration/user_privs/ranger_plugin.md
Labels: documentation, 3.1, 3.2, 3.3

#45204 [Doc] support cache select docs for cloud table
  docs/en/data_source/data_cache_warmup.md
  docs/zh/data_source/data_cache_warmup.md
Labels: documentation, 3.3

#45340 [BugFix] fix compiling error
  be/src/storage/lake/rowset_update_state.h
  be/src/storage/rowset/cast_column_iterator.h
  be/src/storage/rowset/column_iterator_decorator.h
Labels: 3.3

#45240 [BugFix] fix incorrect mysql binary resultset packet
  be/src/column/adaptive_nullable_column.cpp
  be/src/column/adaptive_nullable_column.h
  be/src/column/array_column.cpp
  be/src/column/array_column.h
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/column.h
  be/src/column/const_column.h
  be/src/column/decimalv3_column.cpp
  be/src/column/decimalv3_column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/json_column.cpp
  be/src/column/json_column.h
  be/src/column/map_column.cpp
  be/src/column/map_column.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/column/object_column.cpp
  be/src/column/object_column.h
  be/src/column/struct_column.cpp
  be/src/column/struct_column.h
  be/src/runtime/mysql_result_writer.cpp
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  test/sql/test_preparestatement/R/test_driver_prepare
  test/sql/test_preparestatement/T/test_driver_prepare
Labels: 3.2, 3.3

#45344 [BugFix] fix next_day/previous_day wrong result if value is invalid
  be/src/exprs/time_functions.cpp
  test/sql/test_time_fn/R/test_time_fn
  test/sql/test_time_fn/T/test_time_fn
Labels: 3.2, 3.3

#45314 [BugFix] Release driver token ASAP
  be/src/exec/pipeline/driver_limiter.cpp
  be/src/exec/pipeline/fragment_context.cpp
  be/src/runtime/exec_env.cpp
  be/src/util/starrocks_metrics.h
  test/sql/test_pipeline/R/test_exceed_driver_limit
  test/sql/test_pipeline/T/test_exceed_driver_limit
Labels: 2.5, 3.0, 3.1, 3.2, 2.5-merged, 3.3

#45234 [Enhancement] Starocks FE should promptly update its Kafka client to fix the CVE-2023-25194 vulnerability
  fe/pom.xml
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3

#45033 [Enhancement] Optimize automatic partition concurrent create partition
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  test/sql/test_automatic_partition/R/test_automatic_partition_concurrent
  test/sql/test_automatic_partition/T/test_automatic_partition_concurrent
Labels: 3.1, 3.2, 3.3

#45351 [Enhancement] Support use table_name to filter scan in information_schema.tables
  be/src/exec/schema_scanner/schema_tables_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  gensrc/thrift/FrontendService.thrift
Labels: 2.5, 3.0, 3.1, 3.2, PROTO-REVIEW, 3.3

#43616 [Feature] Optimize `count(1)` in hdfs scanner by rewriting plan to `sum`
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_orc.h
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/jni_scanner.cpp
  be/src/exec/jni_scanner.h
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
  be/src/formats/parquet/file_reader.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/MockIcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveScanTest.java
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveScanner.java
  test/sql/test_external_file/R/test_csv_compression_format
  test/sql/test_external_file/R/test_hive_jni_format
  test/sql/test_external_file/R/test_orc_count_star_opt
  test/sql/test_external_file/R/test_parquet_count_star_opt
  test/sql/test_external_file/T/test_csv_compression_format
  test/sql/test_external_file/T/test_hive_jni_format
  test/sql/test_external_file/T/test_orc_count_star_opt
  test/sql/test_external_file/T/test_parquet_count_star_opt
  test/sql/test_external_file/T/test_query_external_file
  test/sql/test_iceberg/R/test_iceberg_catalog
  test/sql/test_iceberg/T/test_iceberg_catalog
Labels: feature

#45266 [Doc] Update the doc of starrocks cross-cluster data migration tool
  docs/en/administration/data_migration_tool.md
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/data_migration_tool.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#45374 [UT] Split PartitionBasedMvRefreshProcessorTest.java file
  fe/fe-core/src/test/java/com/starrocks/scheduler/MVRefreshTestBase.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorJdbcTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorPaimonTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshTest.java
Labels: 3.3

#45408 [Enhancement] Improve insert column mismatch error message (backport #44331)
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_scan/test_pushdown_or_predicate/R/test_parse_and_rewrite_or_predicate
Labels: behavior_changed

#45365 [Doc] Use unnest_bitmap to replace unnest(bitmap_to_array(xxx))
  docs/en/assets/lateral_join_type_conversion.png
  docs/en/using_starrocks/Lateral_join.md
  docs/zh/assets/lateral_join_type_conversion.png
  docs/zh/using_starrocks/Lateral_join.md
Labels: documentation, 3.1, 3.2, 3.3

#45396 [BugFix] Use Default Warehouse in EsScanNode
  fe/fe-core/src/main/java/com/starrocks/planner/EsScanNode.java
Labels: 3.2, 3.3

#45379 [Bugfix] fix decimal overflow problem in avg
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeDecimalV3Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  test/sql/test_agg_function/R/test_avg_over_flow
  test/sql/test_agg_function/T/test_avg_over_flow
  test/sql/test_decimal/R/test_decimal_overflow
Labels: title needs [type]

#45249 [BugFix] Fix ranger policy rewrite error in materialized view
  fe/fe-core/src/main/java/com/starrocks/privilege/SecurityPolicyRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/Relation.java
  fe/fe-core/src/test/java/com/starrocks/privilege/ranger/RangerInterfaceTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.1, 3.2, 3.3

#45419 [BugFix] Use Default Warehouse in EsScanNode (backport #45396)
  fe/fe-core/src/main/java/com/starrocks/planner/EsScanNode.java
Labels: 3.2

#45407 [Doc] add 3.3 release note
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#45274 [BugFix] enhance column pruning for query with predicates after mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45393 [Enhancement] Add interface Chunk::remove_columns_by_index
  be/src/column/chunk.cpp
  be/src/column/chunk.h
  be/src/exec/chunks_sorter_full_sort.cpp
  be/src/exec/chunks_sorter_full_sort.h
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/test/column/chunk_test.cpp
Labels: 3.2, 3.3

#45436 [Doc] fixes in 3.3 release notes
  docs/en/release_notes/release-3.3.md
Labels: documentation

#45423 [BugFix] Fix querying information_schema.columns without db bug
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  test/sql/test_information_schema/R/test_column
  test/sql/test_information_schema/T/test_column
Labels: 3.3

#45409 [Doc] Fixed the formatting of the text Using_HLL, missing a small parenthesis
  docs/zh/using_starrocks/Using_HLL.md
Labels: documentation, 3.1, 3.2, 3.3

#45006 [BugFix] Multi bytes CSV row/column delimiter for `files()`
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/common/CsvFormat.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorReport.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadScanNode.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/FileScanNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/StreamLoadScanNodeTest.java
Labels: 3.3

#45441 [BugFix] Fix use_broker compatibility in outfile
  be/src/runtime/file_result_writer.h
Labels: 2.5

#45442 [Doc] Add description for FE configuration tablet_sched_be_down_tolerate_time_s
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#45401 [Enhancement] Give more error message for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/TrinoParserUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/trino/TrinoParserUnsupportedException.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoParserNotSupportTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: 3.1, 3.2, 3.3

#45426 [Enhancement] add key_metadata field in the iceberg distributed plan
  be/src/runtime/metadata_result_writer.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/IcebergMetadataCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/iceberg/LogicalIcebergMetadataTable.java
  fe/fe-core/src/main/java/org/apache/iceberg/MetadataParser.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  gensrc/thrift/Data.thrift
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScanner.java
Labels: PROTO-REVIEW

#45056 [BugFix] (MV) Optimize PartitionBasedMvRefreshProcessor db locks(Part 2)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PlannerMetaLocker.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockInterface.java
Labels: 3.3

#45063 [BugFix] Support BE log sys_log_level modify to take effect dynamically
  be/src/common/config.h
  be/src/common/logconfig.cpp
  be/src/http/action/update_config_action.cpp
  be/src/util/logging.h
Labels: 3.1, behavior_changed, 3.2, 3.3

#44887 [Feature] [Doc] Add oracle jdbc catalog
  be/src/exec/jdbc_scanner.cpp
  docs/en/data_source/catalog/jdbc_catalog.md
  docs/zh/data_source/catalog/jdbc_catalog.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/OracleSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/OracleSchemaResolverTest.java
  fe/pom.xml
Labels: documentation

#45456 [BugFix] fix persistence of mv sort key
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: 3.1, 3.2, 3.3

#45372 [Enhancement] Add catalog information in FE's query_detail #40894
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetail.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailQueueTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailTest.java
Labels: behavior_changed, 3.3

#45460 [Doc] remove an incorrect description in to_tera_date() function
  docs/en/sql-reference/sql-functions/date-time-functions/to_tera_date.md
  docs/en/sql-reference/sql-functions/date-time-functions/to_tera_timestamp.md
Labels: documentation, 3.2, 3.3

#45477 [UT] Fix ut for colocate balancer test
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.1, 3.2, 3.3

#45471 [BugFix] Add TaskRunScheduler to support task runs' FIFO scheduler (backport #43843)
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: documentation

#45405 [Enhancement] Refine the error message when connection limit reached
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/action/SessionAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowProcesslistStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowDbStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowDeleteTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectionLimitTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.0, 3.1, 3.2, 3.3

#45488 [Doc] update function/sql template and add config template
  docs/README.md
  docs/en/sql-reference/How_to_Write_Functions_Documentation.md
  docs/en/sql-reference/SQL_command_template.md
  docs/en/sql-reference/template_for_config.md
  docs/zh/feedback-and-contribute.md
  docs/zh/sql-reference/How_to_Write_Functions_Documentation.md
  docs/zh/sql-reference/How_to_write_SQL_command_doc.md
  docs/zh/sql-reference/template_for_config.md
Labels: documentation, 3.1, 3.2, 3.3

#45492 [BugFix] [UT] Distinguish TaskRun by using unique taskRunId (backport #44748)
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
  test/lib/sr_sql_lib.py
Labels: META-REVIEW

#45478 [BugFix] Fix cn crash when no disk
  be/src/storage/memtable_flush_executor.cpp
Labels: 3.1, 3.2, 3.3

#45494 [Enhancement] avoid load image failed when create connector with exception
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/CatalogMgrTest.java
Labels: 3.1, 3.2, 3.3

#45465 [Enhancement] The logic of the output column is split into two stages.
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/mor_processor.cpp
  be/test/exec/join_hash_map_test.cpp
Labels: 3.3

#45446 [Enhancement] release staros v3.3-rc1
  be/src/fs/fs_starlet.cpp
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
Labels: 3.3

#45220 [Enhancement] Fix serveral cache select use problems
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectMetrics.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/DataCacheSelectProcessor.java
  fe/fe-core/src/test/java/com/starrocks/datacache/DataCacheSelectMetricsTest.java
Labels: 3.3

#45289 [BugFix] fix cloud table compaction task concurrency issue
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/test/storage/lake/compaction_scheduler_test.cpp
Labels: 3.1, 3.2, 3.3

#45520 [BugFix] Add TaskRunScheduler to support task runs' FIFO scheduler (backport #43843)
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: documentation

#45519 [BugFix] Add TaskRunScheduler to support task runs' FIFO scheduler (backport #43843)
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: documentation

#44456 [Enhancement] Add background warehouse and use the correct warehouse
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableCleanerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgent2ndTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.3

#45544 [Doc] fix obs in loading from s3-compatible storage
  docs/en/loading/BrokerLoad.md
  docs/en/loading/cloud_storage_load.md
  docs/zh/loading/BrokerLoad.md
  docs/zh/loading/cloud_storage_load.md
Labels: documentation, 2.5, 3.1, 3.2, 3.3

#45364 [Refactor] Introduce ColumnId to support Column renaming (part1)
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColumnId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/planner/DictionaryCacheSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColumnIdTest.java
  test/sql/test_alter_table/R/test_alter_table_abnormal
  test/sql/test_column_rename/R/test_column_rename2
  test/sql/test_fast_schema_evolution/R/test_fast_schema_evolution
Labels: META-REVIEW

#45238 [BugFix] Pause routine load job when warehouse not exist
  fe/fe-core/src/main/java/com/starrocks/common/util/KafkaUtil.java
  fe/fe-core/src/test/java/com/starrocks/common/util/KafkaUtilTest.java
Labels: 3.3

#45528 [Enhancement] support cache select metrics for cloud table
  be/src/connector/lake_connector.cpp
  be/src/fs/fs_starlet.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/olap_common.h
  be/src/storage/rowset/segment_iterator.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
Labels: 3.3

#45028 [Enhancement] Support log query profile to file
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
Labels: 3.1, 3.2, 3.3

#45473 [Refactor] Refactor cross-cluster replication limits
  be/src/agent/agent_server.cpp
  docs/en/administration/data_migration_tool.md
  docs/zh/administration/data_migration_tool.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationMgr.java
Labels: documentation, META-REVIEW

#45517 [BugFix] Fix schemachange failed caused by storage migration
  be/src/storage/task/engine_storage_migration_task.cpp
  be/test/storage/task/engine_storage_migration_task_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45152 [UT] add test case for multi-column mv loose rewrite
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: 3.3

#45569 [Enhancement] Put del vec filter after all other index filter
  be/src/common/config.h
  be/src/storage/rowset/segment_iterator.cpp
Labels: 3.1, 3.2, 3.3

#45568 [BugFix] fix empty required fields in jni scanner
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveScanner.java
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScanner.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ScannerHelper.java
  java-extensions/jni-connector/src/test/java/TestScannerHelper.java
  java-extensions/kudu-reader/src/main/java/com/starrocks/kudu/reader/KuduSplitScanner.java
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsSplitScanner.java
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
Labels: 3.3

#44764 [Enhancement] Enable transparent union rewrite by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/Explain.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVCompensation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVUnionRewriteMode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  test/sql/test_materialized_view/R/test_materialized_view_union_all_rewrite
  test/sql/test_materialized_view/R/test_mv_partition_compensate_hive
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/R/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/R/test_mv_partition_compensate_mysql
  test/sql/test_materialized_view/R/test_mv_partition_compensate_olap
  test/sql/test_materialized_view/R/test_mv_partition_union_rewrite_mode_iceberg
  test/sql/test_materialized_view/T/test_materialized_view_union_all_rewrite
  test/sql/test_materialized_view/T/test_mv_partition_compensate_hive
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part1
  test/sql/test_materialized_view/T/test_mv_partition_compensate_iceberg_part2
  test/sql/test_materialized_view/T/test_mv_partition_compensate_mysql
  test/sql/test_materialized_view/T/test_mv_partition_compensate_olap
  test/sql/test_materialized_view/T/test_mv_partition_union_rewrite_mode_iceberg
  test/sql/test_transparent_mv/R/test_transparent_mv_basic
  test/sql/test_transparent_mv/R/test_transparent_mv_hive
  test/sql/test_transparent_mv/R/test_transparent_mv_mysql
  test/sql/test_transparent_mv/R/test_transparent_mv_olap
  test/sql/test_transparent_mv/R/test_transparent_mv_union_hive
  test/sql/test_transparent_mv/R/test_transparent_mv_union_iceberg
  test/sql/test_transparent_mv/R/test_transparent_mv_union_olap
  test/sql/test_transparent_mv/T/test_transparent_mv_basic
  test/sql/test_transparent_mv/T/test_transparent_mv_hive
  test/sql/test_transparent_mv/T/test_transparent_mv_mysql
  test/sql/test_transparent_mv/T/test_transparent_mv_olap
  test/sql/test_transparent_mv/T/test_transparent_mv_union_hive
  test/sql/test_transparent_mv/T/test_transparent_mv_union_iceberg
  test/sql/test_transparent_mv/T/test_transparent_mv_union_olap
Labels: 3.3

#45570 [UT] get identifier field ids from equality delete file for adaptation
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
Labels: 3.1, 3.2, 3.3

#45481 [Enhancement] optimize column mode partial update when memory is limited
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.1, 3.2, 3.3

#45592 [BugFix] fix cache select task property not set correctly
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SubmitTaskStmt.java
Labels: 3.3

#45322 [Enhancement] make the default mv task as manual
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  test/sql/test_materialized_view/R/test_auto_refresh
  test/sql/test_materialized_view/T/test_auto_refresh
Labels: 3.1, behavior_changed, 3.2, 3.3

#45612 [UT] optimize error message when creating hive/iceberg db/table
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreOperations.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveWriteUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/GlueMetastoreClientDelegate.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/glue/IcebergGlueCatalog.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetastoreOperationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveWriteUtilsTest.java
Labels: behavior_changed, 3.2, 3.3

#45613 [UT] Fix NPE for query queue test
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
Labels: 3.2, 3.3

#37322 [Doc] Fix the numeric range description in the documentation for array_to_b…
  docs/en/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_from_string.md
  docs/zh/sql-reference/sql-functions/array-functions/array_to_bitmap.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/bitmap_from_string.md
Labels: documentation, 3.1, 3.2

#45589 [Enhancement] Empty hash table support lazy materialize join
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/test/exec/join_hash_map_test.cpp
Labels: 3.3

#45614 [BugFix] fix stale histogram lead to unexpected stats
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q19.sql
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#45597 [BugFix] The usage and size of pindex is not update during deletion
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/test/storage/persistent_index_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#44984 [BugFix] Fix hive view privilege checking
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
Labels: 3.1, 3.2, 3.3

#45598 [BugFix] Support MERGED state for task run
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/Constants.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/MVTaskRunExtraMessage.java
  fe/fe-core/src/test/java/com/starrocks/benchmark/TaskSchedulerBench.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunFIFOQueueTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_event_trigger
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_event_trigger
Labels: 3.1, 3.2, 3.3

#45641 [Enhancement] hint enhancement (backport #37356)
  fe/fe-core/src/main/java/com/starrocks/analysis/HintNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SelectList.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/StatementBase.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSingleTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: behavior_changed

#45663 [Doc] add 2.5.21 release notes
  docs/en/release_notes/release-2.5.md
  docs/zh/release_notes/release-2.5.md
Labels: documentation

#44499 [Enhancement] adjust the BE and CN schedule policy
  fe/fe-core/src/main/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/DefaultWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/WorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/DefaultWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: behavior_changed, 3.2, 3.3

#45673 [BugFix] fix cloud native pk table memory statistic issue
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/tablet_updates.cpp
Labels: 3.1, 3.2, 3.3

#45674 [UT] pass snapshot id to IcebergTableName when listing partition names
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
Labels: 3.3

#45537 [BugFix] Unify the performance of CTAS and Create Table when the distribution key is NULL
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  test/sql/test_random_distribution/R/test_random_distribution
Labels: behavior_changed, 3.3

#45675 [Enhancement] UniqueMetrics of OlapTableSink's profile support runtime profile report
  be/src/exec/pipeline/olap_table_sink_operator.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: 3.1, 3.2, 3.3

#45647 [BugFix] Fix orc dict filter bug
  be/src/exec/hdfs_scanner_orc.cpp
  test/sql/test_external_file/R/test_orc_predicates
  test/sql/test_external_file/T/test_orc_predicates
  test/sql/test_external_file/files/string-dict-column.orc
Labels: 3.0, 3.1, 3.2, 3.3

#45659 [Enhancement] Add background warehouse and use the correct warehouse (backport #44456)
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ComputeNodeProcDir.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/RecycleLakeRangePartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableCleanerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgent2ndTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/UtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: automerge

#45500 [BugFix] Fix duplicated error rows in load tracking log
  be/src/exec/tablet_sink.cpp
  test/sql/test_information_schema/R/test_loads
  test/sql/test_information_schema/T/test_loads
Labels: 3.1, 3.2, 3.3

#45480 [Enhancement] Improve routine load too many error rows message
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#45678 [Doc] remove parameter change in v2.5.21 because it's already in 2.5.20
  docs/en/release_notes/release-2.5.md
  docs/en/sql-reference/template_for_config.md
  docs/zh/release_notes/release-2.5.md
  docs/zh/sql-reference/template_for_config.md
Labels: documentation
