Repository StarRocks/starrocks, pull requests merged in 2024-11, with the labels that each got.

#52464 [Doc] Remove query rewrite limits of External MV
  docs/en/using_starrocks/async_mv/use_cases/query_rewrite_with_materialized_views.md
  docs/zh/using_starrocks/async_mv/use_cases/query_rewrite_with_materialized_views.md
Labels: documentation, 3.1, 3.2, 3.3

#52462 [Doc] Clarify Task and TaskRun
  docs/en/sql-reference/sql-statements/loading_unloading/ETL/SUBMIT_TASK.md
  docs/zh/sql-reference/sql-statements/loading_unloading/ETL/SUBMIT_TASK.md
Labels: documentation, 3.1, 3.2, 3.3

#52514 [Doc] Fix md table format
  docs/zh/administration/management/Backup_and_restore.md
Labels: documentation, 3.1, 3.2, 3.3

#52468 [Enhancement] Rebase warehouse proc framework
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/GrantsTo.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ProcService.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/WarehouseInfosBuilder.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/metric/WarehouseMetricMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/warehouse/DefaultWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/LoadJobWithWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Warehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseInfo.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseLoadInfoBuilder.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseLoadStatusInfo.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseProcDir.java
Labels: META-REVIEW, 3.3

#42982 [Enhancement] Support Query cache in shared_data
  be/src/connector/lake_connector.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/query_cache/cache_operator.cpp
  be/src/exec/query_cache/cache_operator.h
  be/src/exec/query_cache/cache_param.h
  be/src/storage/base_tablet.h
  be/src/storage/lake/rowset.h
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/tablet_reader.cpp
  be/src/storage/lake/tablet_reader.h
  be/src/storage/lake/versioned_tablet.cpp
  be/src/storage/lake/versioned_tablet.h
  be/src/storage/rowset/base_rowset.h
  be/src/storage/rowset/rowset.h
  be/src/storage/tablet.cpp
  be/src/storage/tablet.h
  be/src/storage/tablet_manager.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  gensrc/thrift/Planner.thrift
  test/sql/test_query_cache/R/test_query_cache
  test/sql/test_query_cache/R/test_query_cache_shard_data
  test/sql/test_query_cache/T/test_query_cache
  test/sql/test_query_cache/T/test_query_cache_shard_data
Labels: PROTO-REVIEW, feature

#52509 [Doc] Update iceberg.md
  docs/en/quick_start/iceberg.md
  docs/en/sql-reference/sql-statements/Catalog/CREATE_EXTERNAL_CATALOG.md
  docs/zh/quick_start/iceberg.md
Labels: documentation, 3.3

#52501 [BugFix] Fix NullPointerException in CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
Labels: 3.1, 3.2, 3.3

#52498 [Enhancement] Enhance text base mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTextBasedRewriteTest.java
Labels: 3.2, 3.3

#52506 [Enhancement] pushdown runtime filter when cbo_agg_push is enabled and join type is broadcast and rf builded from colocate group
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPushAggTest.java
Labels: 3.3

#52548 [Doc] Update iceberg_catalog.md
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/quick_start/iceberg.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/quick_start/iceberg.md
Labels: documentation, 3.1, 3.2, 3.3

#52544 [BugFix] Fix local file rename in broker
  fs_brokers/apache_hdfs_broker/src/broker-core/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: 3.1, 3.2, 3.3

#52541 [Enhancement] avoid to extract constant expr as common expr in array_map
  be/src/exprs/lambda_function.cpp
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#52513 [BugFix] Fix create table use order by case sensitive
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  test/sql/test_create_table/R/test_create_table_case_sensitive
  test/sql/test_create_table/T/test_create_table_case_sensitive
Labels: behavior_changed, 3.3

#52557 [Enhancement] Disable alter expression partition name
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  test/sql/test_alter_table/R/test_alter_partition
  test/sql/test_alter_table/T/test_alter_partition
Labels: behavior_changed, 3.3

#52555 [BugFix] Cherry pick apache orc bugfix: fix return wrong result if lack of hasnull
  be/src/formats/orc/apache-orc/c++/src/sargs/PredicateLeaf.cc
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#51036 [BugFix] fix list partition multi values' probelm
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: 3.2, 3.3

#52579 [BugFix] Fix chunk accumulator miss assign _max_size
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/hash_partition_context.cpp
  test/sql/test_spill/R/test_spill_aggregate
  test/sql/test_spill/T/test_spill_aggregate
Labels: 3.0, 3.1, 3.2, 3.3

#52236 [Enhancement] adjust async-profile queue strategy
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/ThreadPoolManagerTest.java
Labels: behavior_changed, 3.3

#52512 [Enhancement] change mysql_server_version from 5.1.0 to 8.0.33
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlHandshakePacketTest.java
Labels: behavior_changed

#49957 [Enhancement] only report BE which is dead or in blacklist
  fe/fe-core/src/main/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/DefaultWorkerProvider.java
  fe/fe-core/src/test/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/DefaultWorkerProviderTest.java
Labels: 3.2, 3.3

#52590 [Enhancement] add metrics for pk table error state
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/util/starrocks_metrics.cpp
  be/src/util/starrocks_metrics.h
  be/test/storage/lake/meta_file_test.cpp
Labels: 3.1, 3.2, 3.3

#52575 [Enhancement] Use more clear type description in ParquetField
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/schema.cpp
  be/src/formats/parquet/schema.h
  be/src/util/system_metrics.cpp
  be/test/formats/parquet/group_reader_test.cpp
  be/test/formats/parquet/parquet_cli_reader.h
  be/test/formats/parquet/parquet_schema_test.cpp
Labels: 3.2, 3.3

#52508 [BugFix] Fix pipeline metrics after resource group
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/pipeline_driver_executor.h
  be/src/exec/workgroup/scan_executor.cpp
  be/src/exec/workgroup/scan_executor.h
  be/src/runtime/exec_env.cpp
  be/src/util/starrocks_metrics.cpp
  be/test/exec/workgroup/scan_task_queue_test.cpp
Labels: 3.3

#52574 [Enhancement] Optimize upload and download for backup restore
  be/src/common/config.h
  be/src/runtime/snapshot_loader.cpp
Labels: 3.1, 3.2, 3.3

#52628 [Doc] Mark ARM as usable
  docs/en/deployment/deployment_overview.md
  docs/en/deployment/deployment_prerequisites.md
  docs/zh/deployment/deployment_overview.md
  docs/zh/deployment/deployment_prerequisites.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#52461 [Enhancement] support base manual compaction for cloud table
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/compaction_policy.h
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/primary_key_compaction_policy.h
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/compaction_policy_test.cpp
  be/test/storage/lake/compaction_scheduler_test.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatisticsSnapshot.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/PartitionStatisticsSnapshotTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW, 3.3

#52584 [BugFix] Fix incorrect execution plan when generated column rewrite in join relation if left table and right table has the same column name
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceScalarOperatorRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GeneratedColumnTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_column/R/test_generated_column_rewrite
  test/sql/test_materialized_column/T/test_generated_column_rewrite
Labels: behavior_changed, 3.2, 3.3

#52625 [Enhancement] push runtime in_filter through agg node
  be/src/exec/aggregate/aggregate_base_node.cpp
  be/src/exec/aggregate/aggregate_base_node.h
Labels: 3.3

#52500 [Enhancement] Support IS_DISTINCT_FROM in Trino dialect.
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoParserNotSupportTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  test/sql/test_trino_dialect/R/test_distinct_from
  test/sql/test_trino_dialect/T/test_distinct_from
Labels: 3.2, 3.3

#52644 [BugFix] Fix incorrect execution plan when generated column rewrite in join relation if left table and right table has the same column name (backport #52584)
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceScalarOperatorRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GeneratedColumnTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_column/R/test_generated_column_rewrite
  test/sql/test_materialized_column/T/test_generated_column_rewrite
Labels: behavior_changed

#50821 [BugFix] The update_config interface still returns success after the dynamic parameter setup fails.
  be/src/common/configbase.cpp
  be/src/common/configbase.h
  be/src/http/action/update_config_action.cpp
  be/src/http/action/update_config_action.h
  be/test/common/config_test.cpp
Labels: behavior_changed, 3.2, 3.3

#52511 [BugFix] Avoid token print in FE log.
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
Labels: 3.2, 3.3

#52503 [Enhancement] Set the memory profiling sample interval to 2m bytes instead of time
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.2, 3.3

#52621 [Enhancement] try to prevent create pk table with __op column name by mistake
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FeNameFormat.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: behavior_changed, 3.3

#52649 [BugFix] remove unnecessary replicate for outer_common_expr
  be/src/exprs/array_map_expr.cpp
Labels: 3.3

#52681 [Doc]Add version requirement for kafka connector
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 3.1, 3.2, 3.3

#52608 [Enhancement] Support sampling statistics collection for external table
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveStatisticsProvider.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorAnalyzeTask.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/StatisticsUtils.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ColumnStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalBasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalSampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateAnalyzeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveStatisticsProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/statistics/ConnectorAnalyzeTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateAnalyzeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_hive/R/test_hive_analyze
  test/sql/test_hive/T/test_hive_analyze
Labels: META-REVIEW

#52683 [BugFix] fix concat expr with multiple args nullsFraction
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculatorTest.java
Labels: 3.1, 3.2, 3.3

#52410 [Feature] Support db level UDF for backup restore
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupMeta.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Function.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AbstractBackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/FunctionRef.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RestoreStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DatabaseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeBackupRestoreTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: behavior_changed, META-REVIEW

#52704 [BugFix] fix backend node lastStartTime updated by hbTime unexpectedly
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
  fe/fe-core/src/test/java/com/starrocks/system/ComputeNodeTest.java
Labels: 3.2, 3.3

#52709 [Enhancement] support sys_log_warn_modules in fe conf
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.0, 3.1, 3.2, 3.3

#51615 [Feature] Support dynamic overwrite for insert overwrite
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJob.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/persist/CreateInsertOverwriteJobLog.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobRunnerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/CreateInsertOverwriteJobLogTest.java
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_dynamic_overwrite/R/test_overwrite
  test/sql/test_dynamic_overwrite/T/test_overwrite
Labels: META-REVIEW, PROTO-REVIEW

#52712 [Feature]Trino dialect supports insert into syntax
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/TrinoParserUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoInsertTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: behavior_changed

#52692 [BugFix] fix slot id conflicts in array_map
  be/src/exprs/array_map_expr.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/lambda_function.cpp
  be/src/exprs/lambda_function.h
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#52757 [Doc] leave edit url out of PDF
  docs/docusaurus/src/css/custom.css
  docs/docusaurus/static/img/Discourse_icon.svg
  docs/docusaurus/static/img/chat.svg
  docs/docusaurus/static/img/chaticon.svg
  docs/docusaurus/static/img/feedback-docs-icon.svg
  docs/docusaurus/static/img/slack-new-logo.svg
Labels: documentation, 2.5, 3.1, 3.2, 3.3

#52752 [BugFix] Fix Expr::open crash when evaluate const throw exception
  be/src/exprs/expr_context.cpp
  test/sql/test_exception/R/test_number_overflow
  test/sql/test_exception/T/test_number_overflow
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#52766 [Enhancement] auto change replication_num of system tables (backport #51799)
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadsHistorySyncer.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/FileListTableRepo.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoCreator.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TableKeeper.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticUtilsTest.java
Labels: automerge, behavior_changed

#52738 [BugFix] close hudi fsview to avoid resource leak
  fe/fe-core/src/main/java/com/starrocks/connector/CachingRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileScanContext.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemotePathKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
Labels: 3.2, 3.3

#52710 [Doc] The txn_commit_rpc_timeout_ms parameter is deprecated since v3.2.0.
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3

#52655 [Enhancement] Do not do filter pushdown for project that contains lambda function
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateProjectRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: 3.3

#52687 [BugFix] add lock to avoid publish and update schema run concurrency for pk table
  be/src/storage/tablet.cpp
  be/src/storage/tablet_meta_manager.cpp
  be/src/storage/tablet_meta_manager.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
Labels: 3.2, 3.3

#52705 [Enhancement] Enhance Lock Manager Memory and CPU resource consumption
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeLocks.java
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/MultiUserLock.java
Labels: 3.3

#52372 [Enhancement] support alter persistent index type in shared-data pk table
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  gensrc/proto/lake_types.proto
  gensrc/thrift/AgentService.thrift
Labels: META-REVIEW, PROTO-REVIEW, 3.3

#52796 [BugFix] Fix compile error in asan mode
  be/src/util/system_metrics.cpp
Labels: 3.2, 3.3

#52782 [BugFix] Add HistogramMetric to support histogram with tags
  fe/fe-core/src/main/java/com/starrocks/metric/HistogramMetric.java
  fe/fe-core/src/main/java/com/starrocks/metric/JsonMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/SimpleCoreMetricVisitor.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricsTest.java
Labels: 3.2, 3.3

#52809 [BugFix]Avoid printing token in be log (#51728)
  be/src/agent/heartbeat_server.cpp
  be/src/agent/heartbeat_server.h
  be/test/agent/heartbeat_server_test.cpp
Labels: 3.2, 3.3

#52400 [Enhancement] optimize histogram implementation
  be/src/column/column_helper.h
  be/src/exprs/agg/aggregate_traits.h
  be/src/exprs/agg/histogram.h
  be/src/exprs/lambda_function.cpp
  be/test/exprs/agg/aggregate_test.cpp
  test/sql/test_analyze_statistics/R/test_histogram_function
  test/sql/test_analyze_statistics/T/test_histogram_function
Labels: 3.3

#52797 [Doc] Fix time unit error
  docs/zh/table_design/indexes/Bitmap_index.md
Labels: documentation, 3.2, 3.3

#52804 [BugFix] Fix unique/foreign contraints properties in lake table
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
Labels: 3.3

#52707 [Enhancement] support del files and cloud native index recover for shared-data pk table
  be/src/storage/lake/lake_primary_key_recover.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/update_manager.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.3

#52795 [BugFix] Use correct lock in Tablet::delete_all_files
  be/src/storage/tablet.cpp
  be/test/storage/size_tiered_compaction_policy_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#52765 [BugFix]fix core dump when start the be with page_cache init metrics
  be/src/storage/page_cache.cpp
Labels: 3.1, 3.2, 3.3

#52800 [Enhancement] Reduce lock time of schema change in scenarios with a large number of columns
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
Labels: 3.1, 3.2, 3.3

#52847 [Doc] Starting from recovery mode does not need helper
  docs/en/administration/Meta_recovery.md
  docs/zh/administration/Meta_recovery.md
Labels: documentation, 3.1, 3.2, 3.3

#52852 [Doc] Update TPC-H_Benchmarking.md
  docs/en/benchmarking/TPC-H_Benchmarking.md
Labels: documentation, 3.1, 3.2, 3.3

#52660 [Feature]Add parameter to set whether trino dialect is downgraded
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoDialectDowngradeTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoTestBase.java
Labels: behavior_changed

#52829 [Enhancement] Optimize ProcProfile logging time
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.2, 3.3

#52618 [BugFix] Fix drop partition in different db could not refresh MV
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: 3.2, 3.3

#52846 [BugFix] fix PushdownSubfieldRule for the join pushdown
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/pushdown_subfield.json
Labels: 3.2, 3.3

#52743 [BugFix] Fix an exception when reading a Paimon table with array<row> column
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonColumnValue.java
Labels: 3.2, 3.3

#52871 [BugFix] disable modify backend host in shared-data mode
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/system/SystemInfoServiceTest.java
Labels: 3.2, 3.3

#52751 [Feature] bar function
  be/src/exprs/utility_functions.cpp
  be/src/exprs/utility_functions.h
  docs/en/sql-reference/sql-functions/utility-functions/bar.md
  docs/en/sql-reference/sql-functions/utility-functions/equiwidth_bucket.md
  docs/zh/sql-reference/sql-functions/utility-functions/bar.md
  docs/zh/sql-reference/sql-functions/utility-functions/equiwidth_bucket.md
  gensrc/script/functions.py
  test/sql/test_function/R/test_synopse
  test/sql/test_function/T/test_synopse
Labels: documentation

#52729 [Feature] Support new syntax for Backup/Restore
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AbstractBackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RestoreStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ParserErrorMsg.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeBackupRestoreTest.java
Labels: behavior_changed

#52885 [BugFix] Do not copy null_column data in fnv_hash() and crc32_hash method of NullableColumn
  be/src/column/nullable_column.cpp
Labels: 3.3

#52556 [Feature] (batch write part3) Implement batch write on BE
  be/src/common/config.h
  be/src/exec/connector_scan_node.cpp
  be/src/exec/csv_scanner.cpp
  be/src/exec/csv_scanner.h
  be/src/exec/file_scanner.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/action/stream_load.h
  be/src/http/http_common.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/batch_write/batch_write_mgr.cpp
  be/src/runtime/batch_write/batch_write_mgr.h
  be/src/runtime/batch_write/batch_write_util.cpp
  be/src/runtime/batch_write/batch_write_util.h
  be/src/runtime/batch_write/isomorphic_batch_write.cpp
  be/src/runtime/batch_write/isomorphic_batch_write.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/stream_load/stream_load_context.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_pipe.cpp
  be/src/runtime/stream_load/stream_load_pipe.h
  be/src/runtime/stream_load/time_bounded_stream_load_pipe.cpp
  be/src/runtime/stream_load/time_bounded_stream_load_pipe.h
  be/src/runtime/stream_load/transaction_mgr.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/test/CMakeLists.txt
  be/test/http/stream_load_test.cpp
  be/test/runtime/batch_write/batch_write_mgr_test.cpp
  be/test/runtime/batch_write/batch_write_util_test.cpp
  be/test/runtime/batch_write/isomorphic_batch_write_test.cpp
  be/test/runtime/stream_load_pipe_test.cpp
  be/test/runtime/time_bounded_stream_load_pipe_test.cpp
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadHttpHeader.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  gensrc/proto/doris_internal_service.proto
  gensrc/proto/internal_service.proto
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#51776 [UT] Optimize the logic of assertDeadLock to reduce UT failures
  fe/fe-core/src/test/java/com/starrocks/common/lock/LockTestUtils.java
Labels: 3.3

#52880 [Enhancement] Added compatible code for PhysicalPartition and LogicalPartition splitting
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
Labels: META-REVIEW

#52903 [BugFix] fix in-memory pk index memory leak
  be/src/storage/primary_index.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.1, 3.2, 3.3

#52897 [UT] fix unstable MemLimitedChunkQueueTest
  be/src/exec/pipeline/exchange/mem_limited_chunk_queue.cpp
  be/test/exec/pipeline/mem_limited_chunk_queue_test.cpp
Labels: 3.3

#52909 [BugFix] Fix array_map common-expression crash
  be/src/exprs/array_map_expr.cpp
  be/src/exprs/array_map_expr.h
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.2, 3.3

#52851 [BugFix]Avoid printing token in be log (#51728)
  be/test/CMakeLists.txt
Labels: 3.2, 3.3

#52895 [Feature] Support Backup/Restore for external catalog
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupMeta.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AbstractBackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CancelBackupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CatalogRef.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RestoreStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ParserErrorMsg.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeBackupRestoreTest.java
Labels: behavior_changed, META-REVIEW

#52934 [Enhancement][Refactor] optimize array_contains_all/array_contains_seq function (backport #51701)
  be/src/column/column_helper.cpp
  be/src/column/column_helper.h
  be/src/exprs/array_functions.h
  be/src/exprs/array_functions.tpp
  be/src/util/bit_mask.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  gensrc/script/functions.py
  test/sql/test_array_fn/R/test_array_contains
  test/sql/test_array_fn/T/test_array_contains
Labels: automerge

#52926 [Bug] fix feedback npe when pushdown local agg
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/analyzer/StreamingAggTuningAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/skeleton/SkeletonBuilder.java
Labels: title needs [type]

#52950 [BugFix]Fix the bug of limit optimization on prune partition
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.2

#52945 [Doc] Fix Broken links in 3.0 Release notes
  docs/en/release_notes/release-3.0.md
  docs/zh/release_notes/release-3.0.md
Labels: documentation

#52103 [Enhancement] Do checkpoint on follower node to relieve memory pressure on leader
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/ha/BDBHA.java
  fe/fe-core/src/main/java/com/starrocks/ha/HAProtocol.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/BootstrapFinishAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseResult.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowMetaInfoAction.java
  fe/fe-core/src/main/java/com/starrocks/journal/CheckpointException.java
  fe/fe-core/src/main/java/com/starrocks/journal/CheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/journal/GlobalStateCheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/journal/StarMgrCheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java
  fe/fe-core/src/main/java/com/starrocks/leader/CheckpointController.java
  fe/fe-core/src/main/java/com/starrocks/leader/MetaHelper.java
  fe/fe-core/src/main/java/com/starrocks/monitor/jvm/JvmStats.java
  fe/fe-core/src/main/java/com/starrocks/persist/MetaCleaner.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/main/java/com/starrocks/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/test/java/com/starrocks/ha/BDBHATest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/server/NodeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/staros/StarMgrServerTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
  gensrc/thrift/FrontendService.thrift
Labels: META-REVIEW, PROTO-REVIEW

#52944 [BugFix] Fix compile error in aarch64
  be/src/column/column_hash.h
  be/src/util/hash.h
Labels: 3.3

#52793 [Feature] Unify cache instance between DLA and cloud native datacache.
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cache_options.h
  be/src/block_cache/datacache_utils.cpp
  be/src/block_cache/datacache_utils.h
  be/src/block_cache/disk_space_monitor.cpp
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/http/action/update_config_action.cpp
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  be/src/io/cache_select_input_stream.hpp
  be/src/service/service_be/starrocks_be.cpp
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  be/test/CMakeLists.txt
  be/test/block_cache/block_cache_test.cpp
  be/test/block_cache/datacache_utils_test.cpp
  be/test/block_cache/disk_space_monitor_test.cpp
  be/test/http/action/update_config_action_test.cpp
  be/test/io/cache_input_stream_test.cpp
Labels: behavior_changed

#52963 [Doc] Add 3.3.6 Release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#52740 [BugFix] Ignore to refresh if base table has dropped one partition
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/DefaultTraits.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/OlapPartitionTraits.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorHiveTest.java
Labels: 3.2, 3.3

#52968 [BugFix] fix MetdataCache concurrency issue
  be/src/storage/rowset/metadata_cache.cpp
  be/src/storage/rowset/metadata_cache.h
  be/src/storage/rowset/rowset.cpp
  be/test/storage/rowset/metadata_cache_test.cpp
Labels: 3.2, 3.3

#52923 [BugFix] Fix disable base compaction with minute granularity & fe/be recover
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/src/storage/compaction_task.cpp
  be/src/storage/tablet_meta.h
  be/test/storage/compaction_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionControlScheduler.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  test/sql/test_compaction_cron/R/test_compaction_cron
  test/sql/test_compaction_cron/T/test_compaction_cron
Labels: 3.2, 3.3

#52967 [BugFix] Publish version operation should be successful even if the warehouse is not exist
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseTest.java
Labels: 3.3

#52894 [BugFix] fix shaded partition when manually added
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SingleItemListPartitionDesc.java
  test/sql/test_list_partition/R/test_add_list_partition
  test/sql/test_list_partition/T/test_add_list_partition
Labels: 3.1, 3.2, 3.3

#52990 [BugFix] Fix hive text reader can't recognize last empty element
  be/src/formats/csv/array_reader.cpp
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/test_data/csv_scanner/array_last_element_is_empty.csv
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#52719 [Enhancement]support connection pool for poco client
  be/src/fs/s3/poco_common.cpp
  be/src/fs/s3/poco_common.h
  be/src/fs/s3/poco_http_client.cpp
  be/src/fs/s3/pool_base.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/service/service_be/starrocks_be.cpp
Labels: behavior_changed

#52965 [BugFix] fix partition id integer overflow
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#53008 [BugFix] fix 100-continue compatibility issue for HTTP/1.0
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/test/java/com/starrocks/http/LoadActionTest.java
Labels: 3.1, 3.2, 3.3

#53010 [BugFix] enable http/1.1 when proxying http request for FE
  docker/dockerfiles/allin1/services/feproxy/feproxy.conf.template
Labels: 3.1, 3.2, 3.3

#52977 [BugFix] Fix show keys from support external catalog
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.2, 3.3

#50334 [BugFix] Fix routine load job change to cancelled state when txn expired
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobMetaTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadTaskSchedulerTest.java
Labels: 3.1, 3.2, 3.3

#52996 [Enhancement] Support partition by minute granularity time_slice
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
Labels: 3.3

#53029 [BugFix] Use STARROCKS_ROOT env
  docker/dockerfiles/be/upload_coredump.sh
  docker/dockerfiles/fe/fe-ubi.Dockerfile
  docker/dockerfiles/fe/fe-ubuntu.Dockerfile
Labels: 3.3

#52706 [BugFix] fix the misleading FE thrift rpc fail message
  fe/fe-core/src/main/java/com/starrocks/rpc/ThriftRPCRequestExecutor.java
Labels: 3.2, 3.3

#53045 [Refactor] Remove meaningless profiler operator mem peaks
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/runtime/current_thread.cpp
  be/src/runtime/current_thread.h
  docs/en/administration/query_profile_details.md
  docs/zh/administration/query_profile_details.md
Labels: documentation

#52326 [BugFix] Fix for npe NormalizePredicateRule
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/NormalizePredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/NormalizePredicateRuleTest.java
Labels: 3.2, 3.3

#53061 [Enhancement]avoid Aws::Client::ClientConfiguration default ctor which has a remote access
  be/src/fs/fs_s3.cpp
  be/src/fs/fs_s3.h
  be/test/fs/fs_s3_test.cpp
  be/test/fs/poco_http_client_test.cpp
  be/test/io/s3_input_stream_test.cpp
  be/test/io/s3_output_stream_test.cpp
Labels: 3.4

#52973 [Enhancement] Ignore union type tag when converting avro to json
  be/src/common/config.h
  be/src/formats/avro/binary_column.cpp
  be/test/exec/avro_scanner_test.cpp
  be/test/exec/test_data/avro_scanner/avro_basic_schema.json
Labels: 3.3

#53083 [BugFix] Fix compaction task type has been changed in the execute queue
  be/src/storage/compaction_candidate.h
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/test/storage/compaction_manager_test.cpp
Labels: 3.2, 3.3, 3.4

#53077 [Enhancement] add pipeline time guard
  be/src/common/config.h
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/util/time_guard.h
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#52246 [Enhancement] adjust drop_tablet_worker_count to half of the core number by default
  be/src/agent/agent_server.cpp
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
Labels: behavior_changed, 3.3, 3.4

#53119 [BugFix] Fix compiler report warning in uninitialized
  be/src/util/time_guard.h
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53111 [Doc] Fixed description of insert behavior on primary key table
  docs/en/table_design/table_types/table_types.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53101 [BugFix] Fix migrate storage medium miss auto-bucket partition bug
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
Labels: 3.4

#53055 [Enhancement] Opt memory tracker for FE
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryTrackable.java
Labels: 3.2, 3.3, 3.4

#53137 [Enhancement] Add toString to StructField for easy debugging
  fe/fe-core/src/main/java/com/starrocks/catalog/StructField.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/StructFieldDescTest.java
Labels: 3.4

#52925 [BugFix] Fix tablet scheduler exception
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
Labels: 3.2, 3.3

#50328 [Enhancement] optimize scheduler one task cost
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadTaskSchedulerTest.java
Labels: 2.5, 3.1, behavior_changed, 3.2, 3.3

#53183 [Doc] fix en doc of kafka cdc
  docs/en/loading/Kafka-connector-starrocks.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53151 [UT] Fix unstable fe ut
  fe/fe-core/src/test/java/com/starrocks/transaction/GtidGeneratorTest.java
Labels: 3.3, 3.4

#52612 [Doc] Added function introduction of auditloader 4.2.1
  docs/en/administration/management/audit_loader.md
  docs/zh/administration/management/audit_loader.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3, 3.4

#53170 [Doc] Doc for Forbidding Base Compaction
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
Labels: documentation, 3.2, 3.3, 3.4

#53175 [Doc] Fix Back Slash in create storage volume
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53152 [BugFix] Fix dynamic_overwrite on non automatic partition table
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  test/sql/test_dynamic_overwrite/R/test_overwrite
  test/sql/test_dynamic_overwrite/T/test_overwrite
Labels: 3.4

#53210 [Doc] Add Kafka Connector Example
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53172 [BugFix] fix compression context pool slow down after long running
  be/src/util/compression/compression_context_pool.h
  be/test/util/block_compression_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#53237 [UT] fix unstable testChooseBestRelatedMVs2
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
Labels: 3.3, 3.4

#53205 [BugFix] Fix compaction task cannot be disabled while in the execution queue
  be/src/storage/compaction_candidate.h
  be/src/storage/compaction_manager.cpp
  be/src/storage/compaction_manager.h
  be/src/storage/compaction_task.h
  be/src/storage/tablet.h
  be/test/storage/compaction_manager_test.cpp
Labels: 3.2, 3.3, 3.4

#53243 [Doc] Update Supported OS
  docs/en/deployment/deployment_prerequisites.md
  docs/zh/deployment/deployment_prerequisites.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53171 [Doc] Unify External MV source
  docs/en/using_starrocks/async_mv/Materialized_view.md
  docs/zh/using_starrocks/async_mv/Materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53217 [Enhancement] add Type Check for decimal input
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java
Labels: 3.2, 3.3, 3.4

#53226 [BugFix] Fix mv agg push down rewrite decimal type bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/common/AggregatePushDownUtils.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewAggPushDownRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  test/sql/test_materialized_view/R/test_materialized_view_agg_pushdown_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_agg_pushdown_rewrite
Labels: 3.3, 3.4

#53229 [BugFix] Disable date_trunc equivalent replace if binary type is LE
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/equivalent/DateTruncEquivalent.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
Labels: 3.1, 3.2, 3.3, 3.4

#53218 [BugFix] Fix mv non rollup rewrite result contains aggregate functions
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
Labels: 3.1, 3.2, 3.3, 3.4

#53212 [BugFix] Fix MVPCTRefreshPlanBuilder generate plan bug if output contains complex expressions
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPlanBuilder.java
  test/sql/test_materialized_view_refresh/R/test_mv_refresh_with_union
  test/sql/test_materialized_view_refresh/T/test_mv_refresh_with_union
Labels: 3.2, 3.3, 3.4

#53267 [BugFix] fix fe cast problem
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/FoldConstantsRuleTest.java
Labels: 3.1, 3.2, 3.3, 3.4

#53266 [BugFix] Fix ioprofiler in cloud native env
  be/src/fs/fs_starlet.cpp
  be/src/io/direct_s3_output_stream.cpp
  be/src/io/s3_input_stream.cpp
  be/src/io/s3_output_stream.cpp
Labels: 3.3, 3.4

#53057 [BugFix] Set chunk_size = 0 when rows_read=0 after applying row_delete_filter in orc scanner.
  be/src/exec/hdfs_scanner_orc.cpp
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#53334 [BugFix] fix bad sst when using cloud native pk index
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/sstable/table_builder.cpp
  be/test/storage/lake/persistent_index_sstable_test.cpp
Labels: 3.3, 3.4

#53207 [Enhancement] improve sql digest for massive compound predicates
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotRef.java
  fe/fe-core/src/main/java/com/starrocks/planner/LoadScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SqlDigestBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SqlDigestBuilderTest.java
Labels: 3.2, 3.3, 3.4

#53265 [BugFix] Fix some fragment not recv runtime filter
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/runtime_filter_types.h
Labels: 3.3, 3.4

#53336 [BugFix] Fix compile on non-staros
  be/src/io/s3_input_stream.cpp
Labels: 3.3, 3.4

#52600 [Feature] table sample
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/olap_common.h
  be/src/storage/range.h
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/data_sample.cpp
  be/src/storage/rowset/data_sample.h
  be/src/storage/rowset/ordinal_page_index.cpp
  be/src/storage/rowset/ordinal_page_index.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_options.h
  be/src/storage/rowset/scalar_column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  be/src/storage/tablet_reader.cpp
  be/src/storage/tablet_reader_params.h
  be/src/storage/zone_map_detail.h
  be/test/CMakeLists.txt
  be/test/storage/rowset/data_sample_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/ParseUtil.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/TableSampleClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalOlapScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/TableSampleClauseTest.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_scan/R/test_table_sample
  test/sql/test_scan/T/test_table_sample
  tools/benchmark/table_sample.sh
Labels: PROTO-REVIEW

#53062 [BugFix] Fix the issue where FE restart fails when creating a table containing too many tablets
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/journal/SerializeException.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  fe/fe-core/src/test/java/com/starrocks/server/SerializeFailedTable.java
Labels: 3.1, 3.2, META-REVIEW, 3.3, 3.4

#53261 [Refactor] Remove AuthorizationInfo in LoadJob
  fe/fe-core/src/main/java/com/starrocks/catalog/AuthorizationInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/InsertLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadMgrTest.java
Labels: META-REVIEW

#53359 [BugFix] Fix asan build error
  be/src/util/system_metrics.cpp
Labels: 3.4

#53355 [BugFix] Fix get compaction status crash
  be/src/storage/tablet.cpp
  be/test/storage/compaction_manager_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#53329 [BugFix] With a high streamload frequency and too many tablets involved, TabletCommitInfos will take up too much memory.
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: 3.1, 3.2, 3.3, 3.4

#53360 [Doc]Update environment_configurations.md
  docs/zh/deployment/environment_configurations.md
Labels: documentation, 3.3, 3.4
