Repository StarRocks/starrocks, pull requests merged in 2024-09, with the labels that each got.

#50516 [Enhancement] Rewrite `&>>` in a portable way
  bin/start_backend.sh
  bin/start_fe.sh
Labels: 3.1, 3.2, 3.3

#50330 [BugFix] Rewrite repair
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/scalar_column_iterator.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.cpp
  be/src/storage/rowset/segment_options.h
  be/src/storage/rowset/segment_rewriter.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#50399 [BugFix] Fix statistic collect get physical partition concurrency issue
  fe/fe-core/src/main/java/com/starrocks/listener/LoadJobStatsListener.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.2, 3.3

#50314 [Enhancement] support adaptive partition hash join
  be/src/common/config.h
  be/src/exec/hash_join_components.cpp
  be/src/exec/hash_join_components.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/join_hash_map.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/mor_processor.cpp
  be/src/exec/pipeline/hashjoin/hash_join_probe_operator.cpp
  be/src/util/cpu_info.h
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#50300 [Enhancement] improve partial update by column mode overflow estimate strategy
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.2, 3.3

#50536 [BugFix] Make DiskRange more robust
  be/src/formats/disk_range.hpp
  be/test/formats/disk_range_test.cpp
Labels: 3.3

#50346 [BugFix] fix _total_consumed_bytes in MemCacheManager
  be/src/runtime/current_thread.h
Labels: 3.2, 3.3

#50506 [BugFix] fix replaceNullType2Boolean when handle struct type
  fe/fe-core/src/main/java/com/starrocks/catalog/StructField.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  test/common/data/stream_load/sr_struct_schema_change_data1.json
  test/common/data/stream_load/sr_struct_schema_change_data2.json
  test/sql/test_schema_change/R/test_struct_schema_change
  test/sql/test_schema_change/T/test_struct_schema_change
Labels: 3.2, 3.3

#50468 [Doc] Add Shared-data Deployment doc on HDFS
  docs/docusaurus/sidebars.json
  docs/en/deployment/shared_data/azure.md
  docs/en/deployment/shared_data/gcs.md
  docs/en/deployment/shared_data/hdfs.md
  docs/en/deployment/shared_data/minio.md
  docs/en/deployment/shared_data/s3.md
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.1, 3.2, 3.3

#50551 [Doc] Backup Restore for Colocate Tables
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.2, 3.3

#50550 [Doc] Add EN Accelerate with AUTO INCREMENT
  docs/en/using_starrocks/query_acceleration_with_auto_increment.md
Labels: documentation, 3.2, 3.3

#50546 [BugFix] skip add the alias into fieldMapping when order by expr not referenced this alias
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/OrderByTest.java
Labels: 2.5, 3.1, 3.2, 3.3

#50483 [Enhancement] Support show proc replications
  fe/fe-core/src/main/java/com/starrocks/common/proc/ProcService.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicationsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationMgr.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/replication/ReplicationMgrTest.java
Labels: 3.1, 3.2, META-REVIEW, 3.3

#50481 [Enhancement] Support infer struct type from parquet in files()
  be/src/exec/parquet_schema_builder.cpp
  be/test/exec/parquet_scanner_test.cpp
  test/sql/test_across_engine/R/test_sink_nested
  test/sql/test_pipe/R/basic
Labels: 3.3

#50559 [Enhancement] support more pushdown functions
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldAccessPathNormalizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldExpressionCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PushDownJoinProjectionTest.java
Labels: 3.2, 3.3

#50515 [Enhancement][Build] Static link libbfd library
  be/CMakeLists.txt
Labels: 3.2, 3.3

#50589 [Doc] add mv feature support
  docs/docusaurus/sidebars.json
Labels: documentation, 3.1, 3.2, 3.3

#50597 [UT] Fix unstable testChooseBestRelatedMVs1
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
Labels: 3.3

#50601 [Doc] Fix Nav issues and unlisted docs
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/docusaurus/sidebars.json
Labels: documentation, 3.1, 3.2, 3.3

#50603 [Doc]Update create_partitioned_materialized_view.md
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/create_partitioned_materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3

#50602 [Doc]Update create_partitioned_materialized_view.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/create_partitioned_materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3

#50420 [BugFix]: make be thrift server socket keep-alive
  be/src/util/thrift_server.cpp
Labels: 3.1, 3.2, 3.3

#50479 [Enhancement] fix `-h` option, add --with-compress-debug-symbol
  build.sh
Labels: 3.2, 3.3

#50412 [BugFix] Fix BDBJE handshake bug
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/pom.xml
Labels: 3.3

#50475 [BugFix] tolerate partial failure of full statistics
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
Labels: 3.2, 3.3

#50488 [BugFix] fix multiple partition column statistics
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  test/lib/sr_sql_lib.py
  test/sql/test_list_partition/R/test_list_partition_cardinality
  test/sql/test_list_partition/T/test_list_partition_cardinality
Labels: 3.1, 3.2, 3.3

#50560 [Enhancement] upgrade staros to v3.3-rc5
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
Labels: 3.3

#50632 [BugFix] Fix the bug of stream load binary type
  be/src/formats/json/nullable_column.cpp
  test/common/data/stream_load/test_stream_load_binary_type.json
  test/sql/test_binary_type/R/test_binary_type
  test/sql/test_binary_type/T/test_binary_type
Labels: 3.1, 3.2, 3.3

#50189 [Enhancement] support incremental scan ranges deployment at FE side
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/CoordinatorPreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Deployer.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/TFragmentInstanceFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/FragmentAssignmentStrategyFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/LocalFragmentAssignmentStrategy.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/AllAtOnceExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/PhasedExecutionSchedule.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/IncrementalDeployHiveTest.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#50576 [Enhancement] support lower/upper constant fold
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConstantExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  test/sql/test_function/R/test_get_query_dump
  test/sql/test_function/T/test_get_query_dump
Labels: 3.2, 3.3

#50626 [BugFix] Fix decimal literal equals uncheck type
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DecimalTypeTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#50513 [Enhancement] Starrocks to support function SESSION_USER()
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
Labels: 3.2, 3.3

#50613 [Enhancement] Support to pushdown compound predicates in orc
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/test/exec/hdfs_scanner_test.cpp
Labels: 3.0, 3.1, 3.2, 3.3

#50672 [UT] Fix unstable ut
  be/test/storage/tablet_updates_test.cpp
Labels: 3.1, 3.2, 3.3

#50595 [Enhancement] add memory statistic for cloud native persistent index's sstable
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/persistent_index_sstable.cpp
  be/src/storage/lake/persistent_index_sstable.h
  be/src/storage/sstable/table.cpp
  be/src/storage/sstable/table.h
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/lake/persistent_index_sstable_test.cpp
Labels: 3.3

#50679 [Doc] 3.1.15 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#50631 [Enhancement] remove partition predicate from cardinality estimation
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
  test/sql/test_list_partition/R/test_list_partition_cardinality
  test/sql/test_list_partition/T/test_list_partition_cardinality
Labels: 3.2, 3.3

#49841 [Enhancement] Optimize memory tracker
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/Connector.java
  fe/fe-core/src/main/java/com/starrocks/connector/LazyConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/CachingDeltaLakeMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/IDeltaLakeMetastore.java
  fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/ElasticsearchConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/memory/AgentTaskTracker.java
  fe/fe-core/src/main/java/com/starrocks/memory/InternalCatalogMemoryTracker.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryTrackable.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/memory/QueryTracker.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetailQueue.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistory.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentTaskQueue.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TxnStateCallbackFactory.java
  fe/fe-core/src/test/java/com/starrocks/connector/delta/CachingDeltaLakeMetastoreTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/delta/DeltaLakeConnectorTest.java
Labels: 3.1, 3.2, 3.3

#50697 [Doc] broken links
  docs/en/release_notes/release-2.5.md
  docs/en/release_notes/release-3.0.md
  docs/zh/integrations/IDE_integrations/Dataphin.md
  docs/zh/release_notes/release-2.5.md
Labels: documentation, 3.1, 3.2, 3.3

#50596 [Enhancement] improve return filename from delta column group by index
  be/src/storage/delta_column_group.h
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/tablet_updates.cpp
  be/test/storage/delta_column_group_test.cpp
  be/test/storage/lake/meta_file_test.cpp
  be/test/storage/tablet_meta_manager_test.cpp
Labels: 3.2, 3.3

#50680 [Doc] Update what_is_starrocks.md
  docs/zh/introduction/what_is_starrocks.md
Labels: documentation

#50645 [Feature] Support IF EXISTS in the FUNCTION statement
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/GlobalFunctionMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateFunctionStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropFunctionStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/catalog/DatabaseTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalFunctionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/CreateFunctionStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/DropFunctionStmtTest.java
Labels: behavior_changed

#50668 [Enhancement] reduce lock granular of TabletStatMgr
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
Labels: 3.2, 3.3

#50692 [BugFix] Fix non isomorphic profile during data load
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
Labels: 3.2, 3.3

#50721 [UT] remove some timeout fe unit tests
  fe/fe-core/src/main/java/com/starrocks/catalog/GlobalFunctionMgr.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergMetadataScanNodeTest.java
Labels: 3.3

#50542 [Doc] Update System_limit.md
  docs/en/sql-reference/System_limit.md
  docs/zh/sql-reference/System_limit.md
Labels: documentation, 2.5, 3.1, 3.2, 3.3

#50127 [Doc][FlatJson] update flat json documents
  docs/en/administration/management/BE_configuration.md
  docs/en/using_starrocks/Flat_json.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/using_starrocks/Flat_json.md
Labels: documentation, 3.3

#50719 [Doc] 3.3.3 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#49140 [Doc] MV supports List Partitioning
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/Materialized_view.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/Materialized_view.md
Labels: documentation, 3.3

#49143 [Doc] List Partition Key supports Null values
  docs/en/table_design/list_partitioning.md
  docs/zh/table_design/list_partitioning.md
Labels: documentation, 3.3

#50361 [Doc] User Property Docs
  docs/en/administration/management/resource_management/Query_management.md
  docs/en/administration/user_privs/User_privilege.md
  docs/en/deployment/post_deployment_setup.md
  docs/en/sql-reference/System_variable.md
  docs/en/sql-reference/sql-statements/account-management/ALTER_USER.md
  docs/en/sql-reference/sql-statements/account-management/CREATE_USER.md
  docs/en/sql-reference/sql-statements/account-management/SET_PROPERTY.md
  docs/en/sql-reference/sql-statements/account-management/SHOW_PROPERTY.md
  docs/zh/administration/management/resource_management/Query_management.md
  docs/zh/administration/user_privs/User_privilege.md
  docs/zh/deployment/post_deployment_setup.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/sql-reference/sql-statements/account-management/ALTER_USER.md
  docs/zh/sql-reference/sql-statements/account-management/CREATE_USER.md
  docs/zh/sql-reference/sql-statements/account-management/SET_PROPERTY.md
  docs/zh/sql-reference/sql-statements/account-management/SHOW_PROPERTY.md
Labels: documentation, 3.3

#50358 [Doc]New Meta Cache for Iceberg and Delta Lake
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/en/data_source/catalog/iceberg_catalog.md
  docs/en/sql-reference/System_variable.md
  docs/zh/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/iceberg_catalog.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.3

#50699 [BugFix] add null value count to iceberg value count
  be/src/formats/parquet/parquet_file_writer.cpp
  test/sql/test_iceberg/R/test_write_null
  test/sql/test_iceberg/T/test_write_null
Labels: 3.1, 3.2, 3.3

#50686 [Enhancement] reduce mem alloc failed because unfair memory sharing
  be/src/connector/connector.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exec/workgroup/work_group.cpp
  be/src/runtime/exec_env.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  gensrc/thrift/InternalService.thrift
Labels: 3.2, PROTO-REVIEW, 3.3

#50756 [Doc] Update Deploy_faq.md remove the description of pk do not balance
  docs/en/faq/Deploy_faq.md
  docs/zh/faq/Deploy_faq.md
Labels: documentation, 3.2, 3.3

#50762 [BugFix] fix npe of remove partition predicte
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PartitionPruneTest.java
Labels: 3.2, 3.3

#50705 [UT] add condition update test to pk consistency test
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
Labels: 3.3

#50757 [BugFix] MV rewrite may generate wrong plans if query only contains constant call operators
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
Labels: 3.1, 3.2, 3.3

#50561 [BugFix] Fix the bug in the FE clone scheduling that causes an infinite loop
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
Labels: 3.1, 3.2, 3.3

#47548 [Feature] Unify load profile through analyze profile & support session/table profile collect granularity
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ExplainAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  gensrc/thrift/AgentService.thrift
  test/common/data/stream_load/kv.csv
  test/sql/test_load_profile/R/test_load_profile
  test/sql/test_load_profile/T/test_load_profile
Labels: documentation, META-REVIEW, PROTO-REVIEW

#50788 [Doc] Add Dict Obj Docs
  docs/en/sql-reference/sql-functions/dict-functions/dictionary_get.md
  docs/en/sql-reference/sql-statements/dictionary/CANCEL_REFRESH_DICTIONARY.md
  docs/en/sql-reference/sql-statements/dictionary/CREATE_DICTIONARY.md
  docs/en/sql-reference/sql-statements/dictionary/DROP_DICTIONARY.md
  docs/en/sql-reference/sql-statements/dictionary/REFRESH_DICTIONARY.md
  docs/en/sql-reference/sql-statements/dictionary/SHOW_DICTIONARY.md
  docs/zh/sql-reference/sql-functions/dict-functions/dictionary_get.md
  docs/zh/sql-reference/sql-statements/dictionary/CANCEL_REFRESH_DICTIONARY.md
  docs/zh/sql-reference/sql-statements/dictionary/CREATE_DICTIONARY.md
  docs/zh/sql-reference/sql-statements/dictionary/DROP_DICTIONARY.md
  docs/zh/sql-reference/sql-statements/dictionary/REFRESH_DICTIONARY.md
  docs/zh/sql-reference/sql-statements/dictionary/SHOW_DICTIONARY.md
Labels: documentation, 3.3

#50737 [BugFix] Add GlobalConstraintManager to manage foreign key constraints parent and children relation
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/Constraint.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/ForeignKeyConstraint.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/GlobalConstraintManager.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/TableWithFKConstraint.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/UniqueConstraint.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/UKFKConstraintsCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/UKFKConstraints.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/pruner/CPBiRel.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ForeignKeyConstraintTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/UniqueConstraintTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/constraint/GlobalConstraintManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  test/sql/test_ddl/R/test_alter_swap_table
  test/sql/test_ddl/T/test_alter_swap_table
Labels: 3.2, 3.3

#50786 [BugFix] fix storage volume validation rule
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 3.1, 3.2, 3.3

#50398 [Enhancement] Support Generated Column rewrite in complex Query
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeState.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/Relation.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SelectRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceScalarOperatorRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/ExpressionMapping.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/OptExprBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GeneratedColumnTest.java
  test/sql/test_materialized_column/R/test_generated_column_rewrite
  test/sql/test_materialized_column/T/test_generated_column_rewrite
Labels: behavior_changed, 3.3

#50823 [BugFix] improve csv parser when handle empty enclose and escape
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/LoadStmtTest.java
Labels: 3.1, 3.2, 3.3

#50277 [Feature]Use jprotobuf-precompile-plugin for starrocks
  bin/start_fe.sh
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/rpc/BrpcProxy.java
  fe/pom.xml
Labels: behavior_changed

#50799 [BugFix] Fix datacache auto-populate bug in delta lake
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/DataCachePopulateRewriteRule.java
  test/sql/test_datacache/R/test_datacache_auto_populate
  test/sql/test_datacache/T/test_datacache_auto_populate
Labels: 3.3

#50828 [BugFix] Fix REPLACE constant fold
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConstantExpressionTest.java
Labels: 3.2, 3.3

#50734 [Enhancement] support constant folding in translating scalarOperator phase
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistinctAggTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  test/sql/test_agg_function/R/test_percentile_approx
  test/sql/test_agg_function/T/test_percentile_approx
Labels: 3.2, 3.3

#50842 [Doc] 3.2.11 Release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#50820 [BugFix] Fix image v2 garbled code problem when decoding
  fe/fe-core/src/main/java/com/starrocks/persist/ImageLoader.java
Labels: 3.3

#50287 [Enhancement] Partial update support const expr
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.h
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/pk_tablet_writer.h
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/rowset_update_state.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/rowset/rowset_writer_context.h
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/src/storage/rowset_update_state.cpp
  be/src/storage/rowset_update_state.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  gensrc/proto/descriptors.proto
  gensrc/proto/olap_file.proto
  gensrc/thrift/Descriptors.thrift
  test/sql/test_partial_update_column_mode/R/test_partial_update
  test/sql/test_partial_update_column_mode/T/test_partial_update
Labels: 3.2, PROTO-REVIEW, 3.3

#50526 [Enhancement] add DiskRootPath as part of show tablet statement
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SHOW_TABLET.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SHOW_TABLET.md
  fe/fe-core/src/main/java/com/starrocks/common/proc/LocalTabletsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/system/Backend.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/LocalTabletsProcDirTest.java
Labels: documentation, 3.3

#50854 [BugFix] RangePredicateExtractor discard predicates mistakenly
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarRangePredicateExtractor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorRewriterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneUKFKJoinRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#50797 [BugFix] Fix bug in serialization of EncryptionKeyPB and dcg handling
  be/src/fs/encrypt_file.h
  be/src/fs/key_cache.cpp
  be/src/io/seekable_input_stream.h
  be/src/script/script.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/rowset/page_io.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/test/fs/key_cache_test.cpp
  be/test/io/seekable_input_stream_test.cpp
  fe/fe-core/src/main/java/com/starrocks/encryption/EncryptionKeyPBAdapter.java
Labels: 3.3

#50477 [Doc]Update STRUCT.md
  docs/en/sql-reference/data-types/semi_structured/STRUCT.md
Labels: documentation, 3.1, 3.2, 3.3

#50476 [Doc]Update STRUCT.md
  docs/zh/sql-reference/data-types/semi_structured/STRUCT.md
Labels: documentation, 3.1, 3.2, 3.3

#50841 [BugFix] fix pipe deadlock in case of error
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
Labels: 3.2, 3.3

#50527 [Enhancement] Support describe files()
  fe/fe-core/src/main/java/com/starrocks/common/SchemaConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndexSchemaProcNode.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/OracleSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DescribeStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  test/sql/test_files/R/csv_format
  test/sql/test_files/T/csv_format
Labels: 3.2, 3.3

#50910 [OnlyForTest] [Enhancement] Support to pushdown compound predicates in orc (backpor…
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/test/exec/hdfs_scanner_test.cpp
Labels: title needs [type]

#50337 [Enhancement] Push down target table schema to files() in insert
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/FileTableFunctionRelation.java
  test/sql/test_files/R/test_insert_properties
  test/sql/test_files/T/test_insert_properties
  test/sql/test_files/csv_format/invalid_int.csv
Labels: behavior_changed

#48516 [Doc]Update userPrivilegeCase.md
  docs/zh/_assets/commonMarkdown/userPrivilegeCase.md
Labels: documentation

#50920 [Doc] Clarify Feature support for Loading
  docs/en/loading/loading_introduction/feature-support-loading-and-unloading.md
  docs/zh/loading/loading_introduction/feature-support-loading-and-unloading.md
Labels: documentation, 3.1, 3.2, 3.3

#50746 [Enhancement] Delete the calculation memory size of Iceberg Table
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
Labels: 3.3

#50283 [Enhancement] Adding exclusions for libraries to fix CVEs
  contrib/trino-connector/pom.xml
  fs_brokers/apache_hdfs_broker/src/hadoop-cos-shaded/pom.xml
Labels: 3.3

#50932 [UT] Fix unstable testRefreshPriority
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
Labels: 3.3

#50628 [BugFix] Fix null exception when insert overwrite job run concurrecy
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJob.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/persist/InsertOverwriteStateChangeInfo.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/InsertOverwriteJobRunnerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/InsertOverwriteStateChangeInfoTest.java
Labels: 3.1, 3.2, META-REVIEW, 3.3

#50996 [Doc] Fix Duplicate HDFS entries
  docs/docusaurus/sidebars.json
Labels: documentation, 3.2, 3.3

#51011 [Doc] set resource management to auto gen
  docs/docusaurus/sidebars.json
  docs/en/administration/management/resource_management/resource_management.mdx
  docs/zh/administration/management/resource_management/resource_management.mdx
Labels: documentation

#50971 [BugFix] Fix EncryptionKeyPBAdapter not serialize key_desc
  fe/fe-core/src/main/java/com/starrocks/encryption/EncryptionKeyPBAdapter.java
  fe/fe-core/src/test/java/com/starrocks/encryption/NormalKeyTest.java
  gensrc/proto/encryption.proto
Labels: PROTO-REVIEW, 3.3

#51012 [Doc] Fix typo
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
Labels: documentation, 3.1, 3.2, 3.3

#50917 [UT] Fix lock modes long running ut
  fe/fe-core/src/test/java/com/starrocks/common/lock/LockManagerAllLockModesRandomTest.java
Labels: 3.3

#50844 [Enhancement] List Partition For AMV(Part 4): Support more patterns for list partition materialized views
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessListPartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessRangePartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshListPartitioner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ListPartitionDiffResult.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/ListPartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PartitionDiffResult.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiffResult.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  test/sql/test_materialized_view_refresh/R/test_mv_with_list_partitions_hive
  test/sql/test_materialized_view_refresh/R/test_mv_with_list_partitions_iceberg
  test/sql/test_materialized_view_refresh/R/test_mv_with_list_partitions_olap
  test/sql/test_materialized_view_refresh/T/test_mv_with_list_partitions_hive
  test/sql/test_materialized_view_refresh/T/test_mv_with_list_partitions_iceberg
  test/sql/test_materialized_view_refresh/T/test_mv_with_list_partitions_olap
Labels: 3.3

#50382 [BugFix] In a concurrency scenario, after a tablet is deleted, its corresponding data directory still exists.
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
Labels: 3.1, behavior_changed, 3.2, 3.3

#51020 [Doc] Update SELECT.md add pivot version
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
Labels: documentation, 3.3

#50973 [Doc]Update hive_catalog.md
  docs/en/data_source/catalog/hive_catalog.md
  docs/en/data_source/catalog/hudi_catalog.md
  docs/zh/data_source/External_table.md
  docs/zh/data_source/catalog/hive_catalog.md
  docs/zh/data_source/catalog/hudi_catalog.md
Labels: documentation, 2.5, 3.1, 3.2, 3.3

#51042 [Doc] Add CN scaling doc
  docs/en/administration/management/Scale_up_down.md
  docs/zh/administration/management/Scale_up_down.md
Labels: documentation, 3.1, 3.2, 3.3

#51047 [Doc] Delete troubleshooting MV doc from 2.5
  docs/docusaurus/sidebars.json
  docs/en/using_starrocks/troubleshooting_asynchronous_materialized_views.md
  docs/zh/using_starrocks/troubleshooting_asynchronous_materialized_views.md
Labels: documentation

#51005 [BugFix] Make cpu_weight always store positive default value
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroup.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateResourceGroupStmt.java
Labels: 3.3-merged, 3.3

#50855 [Enhancement] Use the same TColumn list in AlterReplicaTask
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java
Labels: 3.2, 3.3

#51002 [Enhancement] Checkpoint outputs misleading logs when loading materialized views.
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.1, 3.2, 3.3

#50594 [Enhancement](log) add config to control compression of fe log & fe audit log
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
Labels: 3.2, 3.3

#51070 [Enhancement] Trace profile records inaccurate expression transform information.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/RewriteTreeTask.java
Labels: 3.2, 3.3

#51010 [Enhancement] Check table intersection early before rewriting PushDown Agg when mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewPushDownRewriter.java
Labels: 3.3

#50919 [BugFix] Fix filter ratio for insert into external catalog table
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DmlStmt.java
Labels: 3.3

#50878 [BugFix] Fix show proc replications
  fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicationsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJobState.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowProcStmt.java
Labels: 3.1, 3.2, 3.3

#51044 [Enhancement] Prune mv that not contains all columns used in sub query when mv is SPG
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewPushDownRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateJoinPushDownRule.java
Labels: 3.3

#51017 [BugFix] Fix the stack overflow of array_distinct
  be/src/exprs/array_functions.cpp
  test/sql/test_array_fn/R/test_array_distinct
  test/sql/test_array_fn/T/test_array_distinct
Labels: 3.1, 3.2, 3.3

#50991 [Enhancement] release request memory after serialization
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
Labels: 3.2, 3.3

#50869 [BugFix] Add enable_active_materialized_view_schema_strict_check config to decide whether to check schema strictlly in activing mv
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVRewriteWithSchemaChangeTest.java
  test/sql/test_alter_mv/R/test_alter_mv
  test/sql/test_alter_mv/T/test_alter_mv
Labels: 3.3

#50899 [BugFix] Fix thread local variable initialization problem
  be/src/runtime/current_thread.h
  be/src/service/mem_hook.cpp
Labels: 3.1, 3.2, 3.3

#51072 [BugFix] fix broker load job hang when meet resource group pending timeout
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: 3.2, 3.3

#51077 [BugFix] fix BE crash when http api request for pprof/cmdline
  be/src/http/action/pprof_actions.cpp
Labels: 3.3

#50963 [BugFix] Fix the npe of show routine load
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: 3.1, 3.2, 3.3

#50925 [Enhancement] adapt to rest catalog list views interface when user side has not implemented it.
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
Labels: 3.3

#50987 [BugFix] avoid hudi context npe when cache reload in background
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileScanContext.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemotePathKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiRemoteFileIO.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteFileOperationsTest.java
Labels: 3.2, 3.3

#50924 [BugFix] Fix session variable load image bug
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UserProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java
  fe/fe-core/src/main/java/com/starrocks/http/action/VariableAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/GlobalVarPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PipeAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/test/java/com/starrocks/authentication/UserPropertyTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BackendsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ComputeNodeProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/LocalTabletsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/odps/MockedBase.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/DeleteTest.java
  fe/fe-core/src/test/java/com/starrocks/load/DeleteHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/ExportMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/GlobalVarPersistInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTestBase.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: META-REVIEW, 3.3

#45851 [BugFix] multiple sys_log_to_console=true entry in fe.conf every time…
  bin/start_fe.sh
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.2, 3.3

#51075 [BugFix] fix BE crash during startup when its started from deep nested directory path
  be/src/util/bfd_parser.cpp
Labels: 3.3

#50471 [Enhancement] Support Gson subtype rollback
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/ForwardCompatibleAlterJobV2Object.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ForwardCompatibleRecyclePartitionInfoV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/GlobalFunctionMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/SmallFileMgr.java
  fe/fe-core/src/main/java/com/starrocks/encryption/KeyMgr.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeRepo.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/RuntimeTypeAdapterFactory.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/SubtypeNotFoundException.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/CollectionConsumer.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/MapEntryConsumer.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/PrimitiveObject.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockReader.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockReaderV1.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockReaderV2.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockWriter.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockWriterV1.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockWriterV2.java
  fe/fe-core/src/main/java/com/starrocks/plugin/PluginMgr.java
  fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/VariableMgr.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MaterializedViewMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2ForwardCompatibilityTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/RecyclePartitionInfoForwardCompatibilityTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/metablock/SRMetaBlockV1Test.java
  fe/fe-core/src/test/java/com/starrocks/persist/metablock/SRMetaBlockV2Test.java
  fe/fe-core/src/test/java/com/starrocks/plugin/PluginMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/GsonReflectUtils.java
Labels: META-REVIEW, 3.3

#50901 [BugFix] fix mysql external table clause
  be/src/exec/mysql_scanner.cpp
  test/sql/test_external_mysql/R/test_external_mysql_clause
  test/sql/test_external_mysql/T/test_external_mysql_clause
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#50302 [Enhancement] limit tablet write request size
  be/src/common/config.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
Labels: 3.2, 3.3

#50254 [Enhancement] support incremental scan ranges deployment at BE side
  be/src/connector/connector.cpp
  be/src/exec/capture_version_node.cpp
  be/src/exec/connector_scan_node.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/fragment_executor.h
  be/src/exec/pipeline/scan/connector_scan_operator.cpp
  be/src/exec/pipeline/scan/connector_scan_operator.h
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/scan_node.cpp
  be/src/service/internal_service.cpp
  be/src/storage/lake/tablet_reader.cpp
  fe/fe-core/src/main/java/com/starrocks/common/profile/Tracer.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/TracerImpl.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/Tracers.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/Var.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/VarTracer.java
  fe/fe-core/src/main/java/com/starrocks/connector/AsyncTaskQueue.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/IncrementalDeployHiveTest.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_hive/R/test_hive_scan_ranges
  test/sql/test_hive/T/test_hive_scan_ranges
Labels: PROTO-REVIEW

#51038 [Enhancement]explicit specific arrow use avx2 as default
  thirdparty/build-thirdparty.sh
Labels: 3.3

#51095 [Doc] Adding detail for data length field
  CONTRIBUTING.md
  docs/en/sql-reference/information_schema/tables.md
Labels: documentation, 3.3

#51045 [BugFix] Fix sync publish failed after BE restart
  be/src/agent/publish_version.cpp
  be/test/storage/publish_version_task_test.cpp
Labels: 3.2, 3.3

#50911 [BugFix] default current_timestamp broken after update to 3.3.2 from 3.2.10
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
Labels: 3.2, 3.3

#51121 [BugFix] Capture resource group for scan task
  be/src/exec/pipeline/exchange/mem_limited_chunk_queue.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/scan/scan_operator.cpp
  be/src/exec/spill/executor.h
  be/src/exec/spill/spiller.hpp
  be/src/exec/workgroup/scan_task_queue.cpp
  be/src/exec/workgroup/scan_task_queue.h
  be/src/udf/java/utils.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#51028 [BugFix] Fix partition ttl loss after FE restart
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TablePropertyTest.java
Labels: 3.1, 3.2, 3.3

#51152 [BugFix] fix tablet writer add chunk when larger than 2GB
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/service/service_be/internal_service.cpp
  be/src/util/brpc_stub_cache.h
  be/src/util/internal_service_recoverable_stub.cpp
  be/src/util/internal_service_recoverable_stub.h
Labels: 3.2, 3.3

#51150 [BugFix] Cached fragment misuses exogenous runtime filter
  fe/fe-core/src/main/java/com/starrocks/planner/FragmentNormalizer.java
  fe/fe-core/src/main/java/com/starrocks/planner/PlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/query_cache_misuse_exogenous_runtime_filter.json
Labels: 3.0, 3.1, 3.2, 3.3

#51148 [BugFix] Fix CTE lowcardinality array couldn't found DictExpr
  fe/fe-core/src/main/java/com/starrocks/planner/MultiCastPlanFragment.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
Labels: 3.3

#51063 [BugFix] fix DataDir invalid access, refactor DataDir management
  be/src/storage/olap_server.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/storage_engine.h
Labels: 3.2, 3.3

#51191 [BugFix] fix thread pool size adjustment exception
  fe/fe-core/src/main/java/com/starrocks/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java
  fe/fe-core/src/main/java/com/starrocks/task/LeaderTaskExecutor.java
  fe/fe-core/src/main/java/com/starrocks/task/PriorityLeaderTaskExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/common/ThreadPoolManagerTest.java
Labels: 3.2, 3.3

#50931 [Enhancement] change default_replication_num of MV
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: behavior_changed, 3.2, 3.3

#50696 [Enhancement][FlatJson] Improve flat json performace and extract strategy
  be/src/column/column_access_path.cpp
  be/src/column/json_column.cpp
  be/src/column/json_column.h
  be/src/common/config.h
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_scan_prepare.cpp
  be/src/exprs/json_functions.cpp
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/storage/meta_reader.cpp
  be/src/storage/olap_meta_reader.cpp
  be/src/storage/rowset/array_column_writer.cpp
  be/src/storage/rowset/bloom_filter.h
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/src/storage/rowset/json_column_compactor.cpp
  be/src/storage/rowset/json_column_iterator.cpp
  be/src/storage/rowset/json_column_writer.cpp
  be/src/storage/rowset/json_column_writer.h
  be/src/storage/rowset/map_column_writer.cpp
  be/src/storage/rowset/struct_column_writer.cpp
  be/src/types/logical_type.h
  be/src/util/json_flattener.cpp
  be/src/util/json_flattener.h
  be/test/exprs/flat_json_functions_test.cpp
  be/test/storage/rowset/flat_json_column_compact_test.cpp
  be/test/storage/rowset/flat_json_column_rw_test.cpp
  be/test/util/json_flattener_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  gensrc/proto/segment.proto
Labels: PROTO-REVIEW, 3.3

#51161 [Doc] Update data_migration_tool.md
  docs/en/_assets/data_migration_tool-2.png
  docs/en/administration/data_migration_tool.md
  docs/zh/_assets/data_migration_tool-2.png
  docs/zh/administration/data_migration_tool.md
Labels: documentation, 3.1, 3.2, 3.3

#51039 [BugFix] Fix stream load with no-2pc mistake write prepare edit log bug
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 3.3

#51105 [Refactor] Remove column pool
  be/src/column/column_pool.h
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/tablet_scanner.cpp
  be/src/http/action/memory_metrics_action.cpp
  be/src/http/default_path_handlers.cpp
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/script/script.cpp
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  be/src/testutil/init_test_env.h
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/test/CMakeLists.txt
  be/test/column/column_pool_test.cpp
  be/test/storage/aggregate_iterator_test.cpp
  be/test/storage/projection_iterator_test.cpp
  be/test/storage/publish_version_manager_test.cpp
  be/test/storage/publish_version_task_test.cpp
  be/test/storage/task/engine_storage_migration_task_test.cpp
  be/test/storage/union_iterator_test.cpp
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#51232 [BugFix] Fix UDTF wrong result when miss multibyte UTF-8
  be/src/udf/java/java_udf.cpp
  be/src/udf/java/java_udf.h
  test/sql/test_udf/R/test_jvm_udf
  test/sql/test_udf/T/test_jvm_udf
Labels: 3.0, 3.1, 3.2, 3.3

#51065 [BugFix] fix incorrect result of yearweek
  be/src/exprs/time_functions.cpp
  test/sql/test_datetime/R/test_yearweek
  test/sql/test_datetime/T/test_yearweek
Labels: 3.3

#51219 [Doc] Add JIT and Table Prune Doc
  docs/docusaurus/sidebars.json
  docs/en/administration/management/BE_configuration.md
  docs/en/sql-reference/System_variable.md
  docs/en/using_starrocks/accelerate-cardinality-preserving-joins.md
  docs/en/using_starrocks/jit.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/using_starrocks/accelerate-cardinality-preserving-joins.md
  docs/zh/using_starrocks/jit.md
Labels: documentation, 3.1, 3.2, 3.3

#51216 [Doc] Cloud-native PK index persistence supports object storage
  docs/en/table_design/table_types/primary_key_table.md
  docs/zh/table_design/table_types/primary_key_table.md
Labels: documentation, 3.3

#51230 [BugFix] Reset schema id when restore
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 3.2, 3.3

#50583 [BugFix] fix analyzing error in prepare stmt with HAVING clause
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AggregationAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
Labels: 3.3

#51027 [Enhancement] Fix Profile collect bug when log dir is removed
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.1, 3.2, 3.3

#50995 [Enhancement] optimize ignore nulls
  be/src/column/column_helper.h
  be/src/exprs/agg/window.h
  test/sql/test_window_function/R/test_ignore_nulls
  test/sql/test_window_function/T/test_ignore_nulls
Labels: 3.2, 3.3

#51174 [BugFix] Fix stream load load_finish_time updated unexpected after transaction committed
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: 3.1, 3.2, META-REVIEW, 3.3

#51000 [Refactor] Remove unused OperationType Code
  fe/fe-core/src/main/java/com/starrocks/authentication/UserPropertyInfo.java
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/ha/LeaderInfo.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/Timestamp.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java
  fe/fe-core/src/main/java/com/starrocks/persist/BackendTabletsInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/DatabaseInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ModifyPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/RecoverInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserIdentity.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetPassVarTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BrokerMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/EditLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariableMgrTest.java
Labels: META-REVIEW

#50685 [Enhancement] support query lake compaction profile in FE
  be/src/exec/schema_scanner/schema_be_cloud_native_compactions_scanner.cpp
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/vertical_compaction_task.cpp
  be/test/storage/lake/compaction_scheduler_test.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/BeCloudNativeCompactionsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/CompactionsProcNode.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionProfile.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionRecord.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionTask.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionProfileTest.java
  gensrc/proto/lake_service.proto
Labels: 3.2, META-REVIEW, PROTO-REVIEW, 3.3
