Repository StarRocks/starrocks, pull requests merged in 2024-06, with the labels that each got.

#46326 [BugFix] Make agg push down with mv rewrite support more cases
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewPushDownRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/AggRewriteInfo.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewAggPushDownRewriteTest.java
  test/sql/test_materialized_view/R/test_materialized_view_agg_pushdown_rewrite
  test/sql/test_materialized_view/T/test_materialized_view_agg_pushdown_rewrite
Labels: 3.3

#46470 [Enhancement] add meta analzye log
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
Labels: 3.1, 3.2, 3.3

#46382 [Enhancement] refine profile for short-cricuit point query
  be/src/exec/short_circuit.cpp
  be/src/exec/short_circuit_hybrid.cpp
  be/src/exec/short_circuit_hybrid.h
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitHybridExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/FeExecuteCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryRuntimeProfileTest.java
  test/sql/test_short_circuit/R/test_short_circuit
  test/sql/test_short_circuit/T/test_short_circuit
Labels: 3.2, 3.3

#45595 [Enhancement] Enable shared scan for cloud native data source
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/connector/lake_connector.cpp
  be/src/connector/lake_connector.h
  be/src/exec/pipeline/scan/morsel.h
  be/test/CMakeLists.txt
  be/test/exec/connector_scan_node_test.cpp
  be/test/storage/lake/lake_data_source_test.cpp
Labels: 3.3

#46377 [BugFix] Use correct warehouse in information_schema.task when mv is created
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskBuilderTest.java
Labels: 3.3

#46494 [BugFix] Add cast type for mv union rewrite to avoid type not match
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategyTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  test/sql/test_materialized_view/R/test_materialized_view_union_rewrite
  test/sql/test_materialized_view/R/test_mv_reasoning
  test/sql/test_materialized_view/T/test_materialized_view_union_rewrite
Labels: 3.3

#46549 [Enhancement] Upgrade gin for speeding up index write
  thirdparty/vars.sh
Labels: 3.3

#46364 [Doc] add col mode partial updates
  docs/en/loading/Flink-connector-starrocks.md
  docs/en/loading/Kafka-connector-starrocks.md
  docs/en/loading/Load_to_Primary_Key_tables.md
  docs/en/loading/Spark-connector-starrocks.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/UPDATE.md
  docs/zh/loading/Flink-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Load_to_Primary_Key_tables.md
  docs/zh/loading/Spark-connector-starrocks.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/STREAM_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/UPDATE.md
Labels: documentation, 3.1, 3.2, 3.3

#46411 [BugFix] Fix an issue when the privilege is merged,casue root privilge dropped.
  fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeCollectionV2.java
Labels: 2.5, 3.0, 3.1, behavior_changed, 3.2, 3.3

#46041 [Enhancement] Make the user in FE & BE as a variable
  docker/dockerfiles/be/be-ubuntu.Dockerfile
  docker/dockerfiles/fe/fe-ubuntu.Dockerfile
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3

#46580 [BugFix] remove unused DCHECK
  be/src/exec/pipeline/query_context.h
Labels: 3.1, 3.2, 3.3

#46571 [BugFix] Fix arm compile for gin lib
  thirdparty/vars.sh
Labels: 3.3

#46521 [Enhancement] Bump BE thrift to 0.20.0
  be/src/exec/aggregator.h
  be/src/exprs/time_functions.cpp
  be/src/gen_cpp/CMakeLists.txt
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: 3.3

#46432 [BugFix] fix kudu timstamp type conversion
  fe/fe-core/src/main/java/com/starrocks/connector/kudu/KuduPredicateConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/kudu/KuduPredicateConverterTest.java
Labels: 3.3

#46592 [BugFix] add an id argument to mark non-deterministic functions
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorsReuseRuleTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46595 [BugFix] tiny typo fix
  be/src/common/configbase.cpp
Labels: 3.2, 3.3

#46593 [BugFix] Add failure handle and warning log for delta writer not exist
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46546 [Enhancement] upgrade staros version to v3.3-rc2
  be/src/block_cache/starcache_wrapper.cpp
  be/test/block_cache/block_cache_test.cpp
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.3

#46491 [BugFix] Support to use session variable to set warehouse for submit task
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.3

#46617 [UT] fix unstable ut
  test/lib/sr_sql_lib.py
  test/sql/test_refresh_statistics/R/test_clear_stats
  test/sql/test_refresh_statistics/T/test_clear_stats
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46631 [Doc] Add 3.3 rc02 Release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#46618 [Doc] Add new property to files()
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/unloading/unload_using_insert_into_files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/unloading/unload_using_insert_into_files.md
Labels: documentation, 3.2, 3.3

#46560 [BugFix] Fix partition prune for transparent union rewrite
  fe/fe-core/src/main/java/com/starrocks/common/util/DebugUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Operator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ExternalScanPartitionPruneRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PartitionPruneRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateJoinPushDownRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteHiveTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteOlapTest.java
  test/sql/test_transparent_mv/R/test_transparent_mv_hive
  test/sql/test_transparent_mv/R/test_transparent_mv_iceberg_part1
  test/sql/test_transparent_mv/R/test_transparent_mv_olap
  test/sql/test_transparent_mv/T/test_transparent_mv_hive
  test/sql/test_transparent_mv/T/test_transparent_mv_iceberg_part1
  test/sql/test_transparent_mv/T/test_transparent_mv_olap
Labels: 3.3

#46508 [Enhancement] support the CREATE EXTERNAL CATALOG xx（IF NOT EXISTS) syntax
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateCatalogStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/CatalogStmtTest.java
Labels: 3.3

#46350 [BugFix] Fix BE crash in ASAN mode
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.1, 3.2, 3.3

#46634 [BugFix] fix rand(x) losing parameter
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
Labels: 3.3

#46633 [BugFix] Fix result of MATCH empty string with Gin is not empty set
  be/src/storage/column_expr_predicate.cpp
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: 3.3

#46661 [Doc] Change BE sys_log_level to mutable
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#46659 [Doc] change a default para value
  docs/en/administration/management/FE_configuration.md
Labels: documentation, 3.3

#46578 [Enhancement] change cloud native pk index's major compact function to static
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/lake_primary_index.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/lake_persistent_index_test.cpp
Labels: 3.3

#46613 [Enhancement] Modify the default parameters of the profile
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.1, 3.2, 3.3

#46650 [BugFix] no incremental data for hudi mor table
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
Labels: 3.2, 3.3

#44971 [Enhancement] reduce read io requests during spill restore phase
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_build_operator.cpp
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/block_reader.cpp
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/options.h
  be/src/exec/spill/serde.cpp
  be/src/exec/spill/serde.h
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW, 3.3

#46681 [Enhancement] Modify the default value of hive_meta_cache_refresh_interval_s
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.3

#46663 [Enhancement] Optimize concurrent partition creation cross transaction
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: 3.1, 3.2, 3.3

#46173 [BugFix] fix refresh interval 1 second
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.1, 3.2, 3.3

#46590 [Doc] Update CREATE FUNCTION docs to explain OR REPLACE feature
  docs/en/sql-reference/sql-statements/data-definition/CREATE_FUNCTION.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_FUNCTION.md
Labels: documentation

#46673 [Enhancement] Use half alter timeout as optimize table rewrite task timeout
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
Labels: 3.2, 3.3

#46706 [Doc] Update external catalog support info
  docs/en/using_starrocks/query_rewrite_with_materialized_views.md
  docs/zh/using_starrocks/query_rewrite_with_materialized_views.md
Labels: documentation, 3.1, 3.2, 3.3

#46709 [Docs] fix params name in example
  docs/en/data_source/catalog/kudu_catalog.md
  docs/zh/data_source/catalog/kudu_catalog.md
Labels: documentation, title needs [type], 3.3

#46675 [BugFix] fix concurrency issue between pk tablet migrate and pk index major compaction
  be/src/storage/persistent_index_compaction_manager.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 3.1, 3.2, 3.3

#46704 [Enhancement] Release the restrictions of DeltaLake analyze
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java
  test/sql/test_deltalake/R/test_deltalake_analyze
  test/sql/test_deltalake/R/test_deltalake_catalog
  test/sql/test_deltalake/T/test_deltalake_analyze
  test/sql/test_deltalake/T/test_deltalake_catalog
Labels: 3.3

#46668 [BugFix] Use session var for warehouse in EsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/EsScanNode.java
Labels: 3.3

#46710 [Doc]change the supported version for be lables
  docs/en/administration/management/resource_management/be_label.md
  docs/zh/administration/management/resource_management/be_label.md
Labels: documentation, 3.2, 3.3

#46677 [Doc] Fix bugs in CBO doc
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.2, 3.3

#46256 [Enhancement] skip dead be when short circuit read
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitHybridExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/DefaultWorkerProvider.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ShortCircuitTest.java
Labels: 3.3

#46599 [BugFix] use two phase agg to process distinct constant
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitMultiPhaseAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitTwoPhaseAggRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistinctAggTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/distinct_constant.json
  test/sql/test_agg/R/test_distinct_agg
  test/sql/test_agg/T/test_distinct_agg
Labels: 3.1, 3.2, 3.3

#46684 [Enhancement] Support READ Lock upgrade to WRITE Lock and add More LockManager UT
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/DeadlockException.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/MultiUserLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/DeadLockTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/LockManagerAllLockModesRandomTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/LockTestUtils.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/SysLockTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestIntendLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLightWeightLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockConflict.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockException.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockInterface.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockManagerReentrantLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockReentrant.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockUpAndDownUpgrade.java
Labels: 3.3

#46732 [BugFix] Fix aws class not found after bump hadoop to 3.4.0
  fe/fe-core/src/main/java/com/starrocks/credential/aws/AWSCloudCredential.java
  fe/fe-core/src/test/java/com/starrocks/credential/AWSCloudConfigurationTest.java
Labels: 3.3

#46579 [Enhancement] Optimize the procedure to update datacache quota and turn on the datacache switch by default.
  be/src/block_cache/block_cache.cpp
  be/src/block_cache/block_cache.h
  be/src/block_cache/cachelib_wrapper.cpp
  be/src/block_cache/cachelib_wrapper.h
  be/src/block_cache/disk_space_monitor.cpp
  be/src/block_cache/disk_space_monitor.h
  be/src/block_cache/kv_cache.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/block_cache/starcache_wrapper.h
  be/src/common/config.h
  be/src/common/status.h
  be/src/connector/hive_connector.cpp
  be/src/http/action/update_config_action.cpp
  be/src/io/cache_input_stream.cpp
  be/src/service/service_be/starrocks_be.cpp
  be/test/block_cache/block_cache_test.cpp
  be/test/block_cache/disk_space_monitor_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: behavior_changed, 3.3

#46731 [Enhancement] modify string with the IF NOT EXISTS clause moved to a better position
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateCatalogStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/CatalogStmtTest.java
Labels: 3.3

#46648 [Enhancement] add xx_hash3_128 function
  be/src/exprs/hash_functions.h
  be/test/exprs/hash_functions_test.cpp
  docs/en/sql-reference/sql-functions/hash-functions/xx_hash3_128.md
  docs/zh/sql-reference/sql-functions/hash-functions/xx_hash3_128.md
  gensrc/script/functions.py
  test/sql/test_function/R/test_hash
  test/sql/test_function/T/test_hash
Labels: documentation, 3.2, 3.3

#46737 [BugFix] Make aws_sdk_enable_compliant_rfc3986_encoding immutable
  be/src/common/config.h
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.1, 3.2, 3.3

#46656 [BugFix] Fix auto partition fail make routine load paused
  be/src/exec/tablet_sink.cpp
  test/sql/test_automatic_partition/R/test_automatic_partition_fail
  test/sql/test_automatic_partition/T/test_automatic_partition_fail
Labels: 3.1, 3.2, 3.3

#46743 [Doc] Add v3.2.8 release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#46757 [BugFix] fix compiling errors from clang15
  be/CMakeLists.txt
  be/src/geo/CMakeLists.txt
  be/src/storage/lake/compaction_scheduler.cpp
  be/test/storage/persistent_index_test.cpp
Labels: 3.2, 3.3

#46758 [BugFix] Fix wrong display for cache select in profile
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DataCacheSelectStatement.java
Labels: 3.3

#46759 [Doc] add bitmap index en
  docs/en/table_design/indexes/Bitmap_index.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#46733 [Enhancement] remove partition version check in plan validation
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/OptimisticVersion.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlanLockFreeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/OptimisticVersionTest.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46782 [BugFix] Add broker dependency hadoop-aliyun/hadoop-ks3 (backport #46162)
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: 3.3

#46492 [BugFix] Fix JniScanner crash due to struct null indicator
  java-extensions/hive-reader/src/test/java/com/starrocks/hive/reader/TestHiveScanner.java
  java-extensions/hive-reader/src/test/resources/test_complex_type/struct_test.avro
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapColumnVector.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/OffHeapTable.java
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46793 [BugFix] Fixed missing break statement while handling Disk migration task in TabletScheduler
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
Labels: 3.2, 3.3

#46500 [BugFix] In order to pass warehouse information, use context to pass it
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/CatalogConnectorMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/AlterTest.java
Labels: 3.3

#43875 [BugFix] Make Parquet writer compatible with hive reader
  be/src/connector/hive_chunk_sink.cpp
  be/src/formats/orc/orc_file_writer.cpp
  be/src/formats/parquet/chunk_writer.cpp
  be/src/formats/parquet/chunk_writer.h
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/level_builder.h
  be/src/formats/parquet/parquet_file_writer.cpp
  be/src/formats/parquet/parquet_file_writer.h
  be/src/formats/parquet/utils.cpp
  be/src/formats/parquet/utils.h
  be/src/runtime/table_function_table_sink.cpp
  be/src/runtime/time_types.h
  be/test/formats/parquet/file_writer_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  gensrc/thrift/Descriptors.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.3

#46816 [Doc] add document for percentile_disc_lc
  docs/en/sql-reference/sql-functions/aggregate-functions/percentile_disc_lc.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/percentile_disc_lc.md
Labels: documentation

#46817 [Doc] add doc for Python UDF
  docs/en/sql-reference/sql-functions/Python_UDF.md
  docs/zh/sql-reference/sql-functions/Python_UDF.md
Labels: documentation

#46815 [BugFix] Make Parquet writer compatible with hive reader (backport #43875)
  be/src/connector/hive_chunk_sink.cpp
  be/src/formats/orc/orc_file_writer.cpp
  be/src/formats/parquet/chunk_writer.cpp
  be/src/formats/parquet/chunk_writer.h
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/level_builder.h
  be/src/formats/parquet/parquet_file_writer.cpp
  be/src/formats/parquet/parquet_file_writer.h
  be/src/formats/parquet/utils.cpp
  be/src/formats/parquet/utils.h
  be/src/runtime/table_function_table_sink.cpp
  be/src/runtime/time_types.h
  be/test/formats/parquet/file_writer_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  gensrc/thrift/Descriptors.thrift
Labels: behavior_changed

#46783 [BugFix] Fix error when refreshing Paimon MV with null partition keys
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonPartitionKey.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PaimonPartitionKeyTest.java
Labels: 3.2, 3.3

#46837 [Doc] Update Loading_intro.md
  docs/en/loading/loading_introduction/Loading_intro.md
  docs/zh/loading/loading_introduction/Loading_intro.md
Labels: documentation, 3.1, 3.2, 3.3

#46735 [BugFix] Fixed the issue with the path gc thread constantly sleeping
  be/src/storage/data_dir.cpp
  be/src/storage/data_dir.h
  be/src/storage/olap_server.cpp
Labels: 3.1, 3.2, 3.3

#46832 [BugFix] Fix inconsistent dictionary in replace partition
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  test/sql/test_global_dict/R/temporary_partition
  test/sql/test_global_dict/T/temporary_partition
Labels: 2.5, 3.0, 3.1, 3.2, 3.3

#46749 [Doc] update doc for CREATE_EXTERNAL_CATALOG
  docs/en/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
Labels: documentation, 3.3

#46760 [Doc] Support SET_VAR for INSERT, DELETE, and UPDATE
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.1, 3.2, 3.3

#46822 [BugFix] Fix case when rewrite bug for synchronized materialized view
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManualTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
  test/sql/test_materialized_view/R/test_sync_materialized_view_rewrite_with_case_when
  test/sql/test_materialized_view/T/test_sync_materialized_view_rewrite_with_case_when
Labels: 3.1, 3.2, 3.3

#46444 [Feature] jdbc sql server draft
  be/src/exec/jdbc_scanner.cpp
  docs/en/data_source/catalog/jdbc_catalog.md
  docs/zh/data_source/catalog/jdbc_catalog.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/SqlServerSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/SqlServerSchemaResolverTest.java
  fe/pom.xml
Labels: documentation

#46830 [BugFix] Fix text reader crashed in compressed file
  be/src/exec/hdfs_scanner_text.cpp
  be/test/exec/hdfs_scanner_test.cpp
Labels: 3.2, 3.3

#46484 [BugFix] Fix query a view with MATCH got exception
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/LowCardinalityRewriteRule.java
  test/sql/test_inverted_index/R/test_inverted_index
  test/sql/test_inverted_index/T/test_inverted_index
Labels: 3.3

#46866 [BugFix] RemoveAggregationFromAggTable should not remove aggregation for random distribution
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RemoveAggregationFromAggTable.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
  test/sql/test_materialized_view/R/test_sync_materialized_view3
  test/sql/test_materialized_view/T/test_sync_materialized_view3
Labels: 3.1, 3.2, 3.3

#46875 [BugFix] Disable union rewrite for synchronized materialized view
  fe/fe-core/src/main/java/com/starrocks/sql/common/DebugOperatorTracer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
Labels: 3.1, 3.2, 3.3

#46827 [BugFix] Fix the issue that external olap table does not support cn
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
Labels: 3.1, 3.2, 3.3

#46829 [BugFix] Abort transaction when plan insert failed
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DmlStmt.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
Labels: 3.2, 3.3

#46886 [BugFix] Fix NoSuchMethodError in hudi connector
  fe/checkstyle.xml
  fe/fe-core/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java
Labels: 3.3

#46890 [BugFix] fix NaN result in expression statistics calculating
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PredicateReorderRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/PredicateReorderRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticsCalculatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/split_order_by.json
Labels: 3.1, 3.2, 3.3

#46794 [BugFix] CN crashed after enable parallel scan in some cases
  be/src/connector/lake_connector.cpp
Labels: 3.3

#46833 [UT] fix be crash when iceberg v2 read empty chuck after probe
  be/src/connector/binlog_connector.cpp
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/connector/jdbc_connector.cpp
  be/src/connector/mysql_connector.cpp
  be/src/exec/mor_processor.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  test/sql/test_iceberg/R/test_iceberg_v2_filter_all_rows
  test/sql/test_iceberg/T/test_iceberg_v2_filter_all_rows
Labels: 3.1, 3.2, 3.3

#46845 [Enhancement] use hashset instead of list to fix the performance bottleneck
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
Labels: 3.1, 3.2, 3.3

#46784 [Enhancement] Analyze table avoids obtaining statistics from external metadata
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
Labels: 3.3

#46896 [BugFix] Update the starcache library to fix the incorrect cache usage after adjusting datacache quota online.
  be/CMakeLists.txt
  be/src/service/service_be/starrocks_be.cpp
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.3

#46932 [Doc] Update CREATE DATABASE with new property
  docs/en/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
Labels: documentation, 3.1, 3.2, 3.3

#46908 [Doc] Update information_schema.materialized_views
  docs/en/reference/information_schema/materialized_views.md
  docs/zh/reference/information_schema/materialized_views.md
Labels: documentation, 3.1, 3.2, doc-feedback, 3.3

#46922 [BugFix] fix list partition pruning for NE expression
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  test/lib/sr_sql_lib.py
  test/sql/test_list_partition/R/test_list_partition_prune
  test/sql/test_list_partition/T/test_list_partition_prune
Labels: 3.1, 3.2, 3.3

#46942 [UT] remove hint in test sql
  test/sql/test_hint/T/test_hint
Labels: 3.3

#46910 [BugFix] fix ngram_search related issue
  be/src/exprs/ngram.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeExprTest.java
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: 3.3

#46921 [Doc] Routine load to shared-data quickstart
  docs/docusaurus/sidebars.json
  docs/en/quick_start/routine-load.md
  docs/zh/quick_start/routine-load.md
Labels: documentation, 3.1, 3.2, 3.3

#46874 [BugFix] Fix error msg about not supported compression type
  be/src/formats/csv/csv_file_writer.cpp
  be/src/formats/orc/orc_file_writer.cpp
  be/src/formats/parquet/parquet_file_writer.cpp
  be/test/formats/csv/csv_file_writer_test.cpp
  be/test/formats/orc/orc_file_writer_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
Labels: 3.3

#46915 [UT] fix npe when enable iceberg column stats cache
  fe/fe-core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestReader.java
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
Labels: 3.3

#46869 [BugFix] fix none data throw no alive be nodes
  fe/fe-core/src/main/java/com/starrocks/qe/ShortCircuitHybridExecutor.java
Labels: 3.3

#46799 [BugFix] Fix write crash when automatic partition open fail
  be/src/exec/tablet_sink.cpp
  test/sql/test_automatic_partition/R/test_automatic_partition_fail
Labels: 3.1, 3.2, 3.3

#46959 [BugFix] Fix report task timeout cancel long running alter job
  be/src/agent/agent_task.cpp
Labels: 3.2, 3.3

#46965 [Enhancement] Simplify be log, especially for too many tablets
  be/src/runtime/local_tablets_channel.cpp
Labels: 3.1, 3.2, 3.3

#46771 [BugFix] Fix hudi jni can not read timestamp type when upgrade hudi to 0.14
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiColumnValue.java
Labels: 3.3

#46867 [Doc] bugfix in rand()
  docs/en/sql-reference/sql-functions/math-functions/rand.md
  docs/zh/sql-reference/sql-functions/math-functions/rand.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#46356 [Enhancement] Speed up Gin writing
  be/src/storage/inverted/clucene/clucene_inverted_writer.cpp
  be/src/storage/inverted/clucene/clucene_inverted_writer.h
  thirdparty/build-thirdparty.sh
Labels: 3.3

#46980 [Doc] Remove the incorrect comma in job properties in CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3

#46920 [Doc] Update CREATE_ROUTINE_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3

#44810 [Feature] Support evicting old cache items with a given probability option to avoid frequent cache replacement.
  be/src/block_cache/cache_options.h
  be/src/block_cache/starcache_wrapper.cpp
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/formats/parquet/file_reader.cpp
  be/src/io/cache_input_stream.cpp
  be/src/io/cache_input_stream.h
  fe/fe-core/src/main/java/com/starrocks/datacache/DataCacheSelectExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#46986 [UT] don't use iceberg manifest cache when session var `enable_iceberg_column_statistics` is true and catalog properties `iceberg_manifest_cache_with_column_statistics` is false
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
Labels: 3.3

#47007 [Enhancement] Optimize multiple like predicates (backport #46914)
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperatorUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ConsolidateLikesRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/SimplifyCaseWhenPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithMultiLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
  test/sql/test_consolidate_multi_likes/R/test_consolidate_multi_likes
  test/sql/test_consolidate_multi_likes/T/test_consolidate_multi_likes
Labels: automerge, version:3.1.13

#46806 [Enhancement] support the drop CATALOG xx IF EXISTS syntax
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropCatalogStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/persist/DropCatalogTest.java
Labels: 3.3

#47016 [Doc]Update Cost_based_optimizer.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#47018 [Doc]Update Cost_based_optimizer.md
  docs/en/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.0, 3.1, 3.2, 3.3

#47032 [Enhancement] enable pindex compression by default (backport #46582)
  be/src/common/config.h
Labels: behavior_changed

#47033 [BugFix] Fix usage of LOG.warn to ensure stack trace is printed when an error occurs
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/binlog/BinlogManager.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java
  fe/fe-core/src/main/java/com/starrocks/common/GenericPool.java
  fe/fe-core/src/main/java/com/starrocks/common/io/Text.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/CachingHiveMetastore.java
  fe/fe-core/src/main/java/com/starrocks/http/action/HaAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBTool.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MaterializedViewMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/task/ExportExportingTask.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/etl/SparkEtlJob.java
Labels: 3.3

#46761 [Enhancement] compatible with lower version kudu-client api
  fe/fe-core/src/main/java/com/starrocks/catalog/KuduTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/kudu/KuduMetadata.java
  fe/fe-core/src/test/java/com/starrocks/catalog/KuduTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/kudu/KuduMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/KuduScanNodeTest.java
Labels: 3.3

#47000 [BugFix] Check the BE service exit status code before launching the be process
  docker/dockerfiles/be/be_entrypoint.sh
Labels: 3.2, 3.3

#47043 [Docs] Update Features.md
  docs/zh/introduction/Features.md
Labels: documentation, title needs [type], 2.5, 3.0, 3.1, 3.2, 3.3

#47058 [Enhancement] Bump paimon to 0.8.1 to resolve cve problems
  fe/fe-core/pom.xml
  java-extensions/paimon-reader/pom.xml
Labels: 3.3

#47056 [Doc] Update SHOW_ANALYZE_STATUS.md
  docs/zh/sql-reference/sql-statements/data-definition/SHOW_ANALYZE_STATUS.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2, 3.3

#47019 [BugFix] Use RandomAccessFile::get_size to get cloud native file size rather than StarletFS::get_file_size which is not implemented now
  be/src/storage/rowset/segment_iterator.cpp
Labels: 3.3

#47030 [BugFix] Fix missing setttings for warehouse in MetadataCollectJob and DictionaryMgr
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataCollectJob.java
Labels: 3.3

#47057 [BugFix] Disable header validation in netty
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
Labels: 3.3

#46897 [Enhancement] Parquet writer support writing datetime with timezone and microseconds precision
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/parquet_file_writer.cpp
  be/src/types/timestamp_value.h
  be/test/formats/parquet/file_writer_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
Labels: 3.3

#47001 [Enhancement] Support to recognize skip.header.line.count in hive's textfile
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_text.cpp
  be/src/exec/hdfs_scanner_text.h
  be/test/exec/hdfs_scanner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/TextFileFormatDesc.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveMetaClientTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/TextFileFormatDescTest.java
  gensrc/thrift/Descriptors.thrift
Labels: 3.1, 3.2, PROTO-REVIEW, 3.3

#47047 [Enhancement] Reduce the memory usage during data ingestion
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
Labels: 3.2, 3.3

#47017 [Doc] Add Doc for MV Agg Pushdown
  docs/en/reference/System_variable.md
  docs/en/using_starrocks/query_rewrite_with_materialized_views.md
  docs/zh/reference/System_variable.md
  docs/zh/using_starrocks/query_rewrite_with_materialized_views.md
Labels: documentation, 3.3

#46911 [BugFix] Fix routine load csv enclose/escape/trimspace not serialize
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
Labels: 3.1, 3.2, 3.3

#46998 [BugFix] Fix wrong delimiter in show routine load
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnSeparator.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RowDelimiter.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ColumnSeparatorTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RowDelimiterTest.java
Labels: 3.1, 3.2, 3.3

#47084 [BugFix] Fix usage of LOG.warn and LOG.error to ensure stack trace is printed when an error occurs
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/analysis/CastExpr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DomainResolver.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/CurrentQueryInfoProvider.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PulsarUtil.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/http/action/LogAction.java
  fe/fe-core/src/main/java/com/starrocks/http/action/WebBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/QueryDumpAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowMetaInfoAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowProcAction.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeBackupJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeRestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadScheduler.java
  fe/fe-core/src/main/java/com/starrocks/planner/PartitionColumnFilter.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateRoutineLoadAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CsvFileStatisticsStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  fe/fe-core/src/main/java/org/apache/iceberg/MetadataParser.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkRDDAggregator.java
Labels: 3.3

#47095 [Doc] Add connector_sink_target_max_file_size
  docs/en/reference/System_variable.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.3

#47005 [Enhancement] Make default bucket num at least 16 when table is unpartitioned
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CTASAutoTabletTest.java
Labels: 3.1, behavior_changed, 3.2, 3.3

#46738 [BugFix] Add missing logic for warehouse
  fe/fe-core/src/main/java/com/starrocks/plugin/AuditEvent.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetail.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/plugin/AuditEventTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/LeaderOpExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailQueueTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.3

#46691 [Enhancement] Support mv refresh in descending order
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
Labels: 3.3

#47111 [UT] Fix unstable sql test test_load_channel_profile
  test/sql/test_profile/R/test_load_channel_profile
  test/sql/test_profile/T/test_load_channel_profile
  test/sql/test_profile/T/test_load_channel_profile_analysis.sh
Labels: 3.3

#47101 [Enhancement] avoid too many log
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
Labels: 3.2, 3.3

#46967 [Doc] Add transparent rewrite mode doc
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
Labels: documentation, 3.3

#47081 [Doc] update doc for DROP_CATALOG
  docs/en/sql-reference/sql-statements/data-definition/DROP_CATALOG.md
  docs/zh/sql-reference/sql-statements/data-definition/DROP_CATALOG.md
Labels: documentation, 3.3

#47120 [Doc] add Pinyin keywords
  docs/zh/cover_pages/query_acceleration.mdx
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/DROP_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/BACKUP.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/CANCEL_BACKUP.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/CANCEL_RESTORE.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/CREATE_REPOSITORY.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/DROP_REPOSITORY.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/RECOVER.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/RESTORE.md
  docs/zh/sql-reference/sql-statements/data-definition/backup_restore/backup_restore.mdx
Labels: documentation, 2.5, 3.0, 3.1, 3.2, doc-feedback, 3.3

#47013 [Enhancement] Show accurate error message of connector exception
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
Labels: 3.2, 3.3

#47134 [BugFix] Fix rewrite json expr error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
Labels: 3.3

#47139 [UT] Fix unstable ut
  be/test/storage/publish_version_task_test.cpp
Labels: 3.2, 3.3

#47150 [UT] fix unstable be ut vertical_compaction_with_rows_mapper
  be/test/storage/tablet_updates_test.cpp
Labels: 3.1, 3.2, 3.3

#47143 [UT] Fix ut TableReaderRemoteTest.test_multi_get_4_tablet
  be/test/storage/table_reader_remote_test.cpp
Labels: 3.2, 3.3

#47116 [BugFix] fix schedule persistent index compact potential crash
  be/src/storage/persistent_index_compaction_manager.cpp
Labels: 3.3

#47152 [Enhancement] Use timezone in select into outfile
  be/src/exec/parquet_builder.cpp
  be/src/exec/parquet_builder.h
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/file_writer.h
  be/src/runtime/file_result_writer.cpp
  be/test/formats/parquet/file_writer_test.cpp
Labels: 3.3

#47044 [Enhancement] Optimize the logic of adding partitions to List Partition
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.2, 3.3

#47106 [Enhancement] Move some add/drop partition analysis logic to AlterTableClauseAnalyzer
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterMVClauseAnalyzerVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionDescAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddPartitionClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropPartitionClause.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AlterTableClauseVisitorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  test/sql/test_automatic_partition/R/test_automatic_partition_list
  test/sql/test_partition_by_expr/R/test_add_partition_to_auto_partition_table
Labels: 3.2, 3.3

#47162 [BugFix] Respect meta_dir conf in fe_entrypoint.sh
  docker/dockerfiles/fe/fe_entrypoint.sh
Labels: 3.3

#47159 [BugFix] fix query profile issue of SUBMIT TASK
  fe/fe-core/src/main/java/com/starrocks/http/HttpConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectProcessorTest.java
Labels: 3.2, 3.3

#47148 [Enhancement] Optimize performance of get physical partition from temp partition
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 3.2, 3.3

#46957 [Enhancement] optimize performance in cast large string to array
  be/src/exprs/array_functions.cpp
  be/src/exprs/cast_expr.h
  be/src/exprs/cast_expr_array.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/LargeStringLiteral.java
  fe/fe-core/src/main/java/com/starrocks/analysis/StringLiteral.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/PipeManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithMultiLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/AstToSqlTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ConstantExpressionTest.java
  test/sql/test_array/R/test_cast_array
  test/sql/test_array/T/test_cast_array
Labels: 3.3
