Repository StarRocks/starrocks, pull requests merged in 2024-02, with the labels that each got.

#40454 [Doc] Add links to hive files to ranger
  docs/en/administration/ranger_plugin.md
  docs/zh/administration/ranger_plugin.md
Labels: documentation, 3.2

#40455 [Doc] Add en doc of smt
  docs/en/integrations/loading_tools/SMT.md
  docs/en/loading/loading_tools.md
  docs/zh/integrations/loading_tools/SMT.md
Labels: documentation, 3.2

#40483 [Doc] Fix default of task_runs_concurrency
  docs/en/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#39265 [Feature] add partition system table
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.h
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PartitionsMetaSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_information_schema/R/test_partitions_meta
  test/sql/test_information_schema/T/test_partitions_meta
Labels: PROTO-REVIEW

#40449 [Enhancement] Refine the syntax of show tablet
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/ShowTabletTest.java
Labels: 3.1, 3.2

#40374 [BugFix] Fix sync mv aggregate column's name not equal to base column
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/BestIndexRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PreAggregateTurnOnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/FilterUnusedColumnTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mv_rewrite_with_dict_opt1.json
  test/sql/test_materialized_view/R/test_sync_materialized_view_rewrite
  test/sql/test_materialized_view/T/test_sync_materialized_view_rewrite
Labels: 3.1, 3.2

#40447 [BugFix] Fix the problem of partial update in cross cluster replication
  be/src/common/config.h
  be/src/storage/lake/replication_txn_manager.cpp
  be/src/storage/replication_txn_manager.cpp
  be/src/storage/replication_txn_manager.h
  be/src/storage/replication_utils.cpp
  be/src/storage/replication_utils.h
  be/src/storage/rowset/rowset_meta.h
  be/src/storage/segment_stream_converter.cpp
  be/src/storage/segment_stream_converter.h
Labels: 3.1, 3.2

#40502 [BugFix] Accumulator uses bytes_size instead of mem_usage to count incremental memory
  be/src/storage/chunk_helper.cpp
  be/test/storage/chunk_helper_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40501 [Doc]correctify the name of flink-connector-starrocks
  docs/en/loading/Flink-connector-starrocks.md
  docs/en/loading/Flink_cdc_load.md
  docs/zh/loading/Flink_cdc_load.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40108 [Doc] Add doc for hive bitmap udf
  docs/docusaurus/sidebars.json
  docs/en/integrations/hive_bitmap_udf.md
  docs/zh/integrations/hive_bitmap_udf.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40448 [Doc] Add link to naming conventions for CREATE xx SQL
  docs/en/reference/System_limit.md
  docs/en/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
  docs/en/sql-reference/sql-statements/account-management/CREATE_ROLE.md
  docs/en/sql-reference/sql-statements/account-management/CREATE_USER.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_INDEX.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_REPOSITORY.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_VIEW.md
  docs/en/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/en/sql-reference/sql-statements/data-manipulation/CREATE_PIPE.md
  docs/en/sql-reference/sql-statements/data-manipulation/INSERT.md
  docs/en/table_design/indexes/Bitmap_index.md
  docs/zh/reference/System_limit.md
  docs/zh/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/account-management/CREATE_ROLE.md
  docs/zh/sql-reference/sql-statements/account-management/CREATE_USER.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_DATABASE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_INDEX.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_REPOSITORY.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_RESOURCE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_VIEW.md
  docs/zh/sql-reference/sql-statements/data-manipulation/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CREATE_PIPE.md
  docs/zh/sql-reference/sql-statements/data-manipulation/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/data-manipulation/INSERT.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SUBMIT_TASK.md
  docs/zh/table_design/indexes/Bitmap_index.md
  docs/zh/table_design/indexes/indexes_overview.md
Labels: documentation, 3.2

#40541 [Doc]Update Load_to_Primary_Key_tables.md broker load sql
  docs/zh/loading/Load_to_Primary_Key_tables.md
Labels: documentation

#40551 [Doc] Fix data management image
  docs/en/assets/data_manage.png
  docs/zh/assets/data_manage.png
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40537 [Doc] Remake Build on Ubuntu
  docs/en/developers/build-starrocks/build_starrocks_on_ubuntu.md
  docs/zh/developers/build-starrocks/Build_on_ubuntu.md
  docs/zh/developers/build-starrocks/build_starrocks_on_ubuntu.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40341 [Enhancement] Support to add random interval even if mv has defined start time
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
Labels: 3.2

#40521 [BugFix] remove queries_not_in_workgroup for /api/pipeline_blocking_drivers
  be/src/http/action/pipeline_blocking_drivers_action.cpp
  be/src/http/action/pipeline_blocking_drivers_action.h
Labels: 3.1, 3.2

#40550 [BugFix] Fix NPE when cte forced inlined
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/plan/UnionTest.java
Labels: 3.1, 3.2

#40479 [Enhancement] Call unload before remove primary index to make sure clean the error pk index before retry
  be/src/storage/lake/lake_primary_key_recover.cpp
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/primary_key_recover.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.1, 3.2

#40574 [Doc] Update sr_operator.md
  docs/en/deployment/sr_operator.md
Labels: documentation, 3.0, 3.1, 3.2

#40495 [BugFix] Fix partition prune error after truncate list partition
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  test/sql/test_list_partition/R/test_select_after_truncate_list_partition
  test/sql/test_list_partition/T/test_select_after_truncate_list_partition
Labels: 3.0, 3.1, 3.2

#40545 [Enhancement] Support a fake BINARY in where clause syntax for BI
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
Labels: 3.1, behavior_changed, 3.2

#40561 [UT] Optimise BDBEnvironmentTest.testRollbackExceptionOnSetupCluster to run faster
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBEnvironmentTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40567 [UT] use parameterized test to split ut
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MockQueryDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.1, 3.2

#40286 [Enhancement] Support wild cards in the file paths for external tables.
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileDesc.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveRemoteFileIO.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileTableScanNode.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveRemoteFileIOTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedRemoteFileSystem.java
Labels: 3.1, 3.2

#40581 [Enhancement] Set agg stage to 1 to make ut stable
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteOnTpcdsTest.java
Labels: 3.0, 3.1, 3.2

#40508 [BugFix] Fix nested mv rewrite bugs
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewSSBTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/ViewBaseMvRewriteTest.java
Labels: 3.2

#39878 [Enhancement] Check meta before executing load task
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40609 [BugFix] check partial update segment file exist before rewrite
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/rowset_update_state.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/test/storage/lake/partial_update_test.cpp
Labels: 3.1, 3.2

#40636 [UT] remove time cost ut
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.1, 3.2

#40509 [BugFix] Fix sync mv aggregate column's name not equal to base column (backport #40374)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/BestIndexRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PreAggregateTurnOnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/FilterUnusedColumnTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/mv_rewrite_with_dict_opt1.json
  test/sql/test_materialized_view/R/test_sync_materialized_view_rewrite
  test/sql/test_materialized_view/T/test_sync_materialized_view_rewrite
Labels: automerge

#40462 [Feature] Support math function cbrt
  be/src/exprs/math_functions.cpp
  be/src/exprs/math_functions.h
  be/test/exprs/math_functions_test.cpp
  docs/en/sql-reference/sql-functions/math-functions/cbrt.md
  docs/zh/sql-reference/sql-functions/math-functions/cbrt.md
  gensrc/script/functions.py
  test/sql/test_function/R/test_cbrt
  test/sql/test_function/T/test_cbrt
Labels: documentation

#40572 [Enhancement] Improve kerberos tmp keytab file permission
  fs_brokers/apache_hdfs_broker/src/main/java/com/starrocks/broker/hdfs/FileSystemManager.java
Labels: 3.1, 3.2

#40602 [BugFix] Fix min-readable-version lost in follower FE
  fe/fe-core/src/main/java/com/starrocks/persist/ReplicaPersistInfo.java
Labels: 3.0, 3.1, 3.2, META-REVIEW

#40649 [BugFix] fix cancel refresh mv command cannot stop task
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunContext.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40094 [Feature] support spill to remote storage
  be/src/exec/CMakeLists.txt
  be/src/exec/aggregate/aggregate_blocking_node.cpp
  be/src/exec/aggregate/distinct_blocking_node.cpp
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/chunks_sorter.h
  be/src/exec/cross_join_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_source_operator.cpp
  be/src/exec/pipeline/aggregate/spillable_aggregate_distinct_blocking_operator.cpp
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.h
  be/src/exec/pipeline/nljoin/nljoin_context.cpp
  be/src/exec/pipeline/nljoin/nljoin_context.h
  be/src/exec/pipeline/nljoin/spillable_nljoin_build_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.h
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/pipeline/sort/spillable_partition_sort_sink_operator.cpp
  be/src/exec/pipeline/spill_process_channel.h
  be/src/exec/pipeline/spill_process_operator.cpp
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/dir_manager.cpp
  be/src/exec/spill/dir_manager.h
  be/src/exec/spill/executor.h
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/file_block_manager.h
  be/src/exec/spill/hybird_block_manager.cpp
  be/src/exec/spill/input_stream.cpp
  be/src/exec/spill/input_stream.h
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/log_block_manager.h
  be/src/exec/spill/options.h
  be/src/exec/spill/query_spill_manager.cpp
  be/src/exec/spill/query_spill_manager.h
  be/src/exec/spill/serde.cpp
  be/src/exec/spill/spill_components.cpp
  be/src/exec/spill/spill_components.h
  be/src/exec/spill/spiller.cpp
  be/src/exec/spill/spiller.h
  be/src/exec/spill/spiller.hpp
  be/src/exec/spillable_chunks_sorter_full_sort.cpp
  be/src/exec/topn_node.cpp
  be/src/exec/workgroup/scan_executor.cpp
  be/src/exec/workgroup/scan_executor.h
  be/src/exec/workgroup/scan_task_queue.h
  be/test/io/spill_block_manager_test.cpp
  be/test/io/spill_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_spill/R/test_spill_to_remote_storage
  test/sql/test_spill/T/test_spill_to_remote_storage
Labels: PROTO-REVIEW

#40637 [BugFix] Fix minor mv backup/restore bugs
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/backup/mv/MVRestoreUpdater.java
  fe/fe-core/src/main/java/com/starrocks/backup/mv/MvRestoreContext.java
Labels: 3.2

#40453 [Enhancement] support internal-sql log
  fe/fe-core/src/main/java/com/starrocks/common/AuditLog.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/http/action/LogAction.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
Labels: 3.1, behavior_changed, 3.2

#40664 [Enhancement] Add force rule based mv rewrite
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/Pattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSetType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/BestMvSelector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/OnlyScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/SingleTableMvRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
  fe/fe-core/src/test/resources/sql/query_dump/force_rule_based_mv_rewrite.json
  fe/fe-core/src/test/resources/sql/query_dump/force_rule_based_mv_rewrite_month.json
  fe/fe-core/src/test/resources/sql/query_dump/force_rule_based_mv_rewrite_year.json
Labels: 3.2

#40670 [Enhancement] change the task execution user to current_user when creating
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SubmitTaskStmtTest.java
Labels: 3.1, behavior_changed, 3.2

#40693 [BugFix] Fix or preddicates use different short key indexes bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitScanORToUnionRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalcUtils.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_sync_materialized_view_rewrite
  test/sql/test_materialized_view/T/test_sync_materialized_view_rewrite
Labels: 3.2

#40039 [Enhancement] Add digest into QueryDetail
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetail.java
Labels: 2.5, 3.0, 3.1, 3.2

#40674 [BugFix] Fix the bug of SinkIOBuffer user-after-free
  be/src/exec/pipeline/sink/export_sink_operator.cpp
  be/src/exec/pipeline/sink/file_sink_operator.cpp
  be/src/exec/pipeline/sink/mysql_table_sink_operator.cpp
  be/src/exec/pipeline/sink/sink_io_buffer.h
  be/test/exec/sink/sink_io_buffer_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40700 [Doc] Update locate function doc in zh
  docs/zh/sql-reference/sql-functions/string-functions/locate.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40713 [BugFix] use db lock in follower or cbo_use_db_lock is true
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlanLockFreeTest.java
Labels: 2.5, 3.0, 3.1

#40694 [Enhancement] IcebergHiveCatalog set list-all-tables property to true
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
Labels: 3.1, 3.2

#40465 [BugFix] Renewed Pulsar routine load task timeout
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarTaskInfo.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/PulsarTaskInfoTest.java
Labels: 3.2

#40378 [BugFix] Fix NPE in trino mode
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: behavior_changed, 3.2

#40031 [Enhancement] Return exception error content when cancel channel
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/exec/tablet_sink_sender.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40451 [Refactor] Delete the written code in EditLog that is smaller than Version 4
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
Labels: META-REVIEW

#40723 [Enhancement] Improve URL downloading mechanism
  be/src/runtime/jdbc_driver_manager.cpp
  be/src/runtime/user_function_cache.cpp
  be/src/util/download_util.cpp
  be/src/util/download_util.h
  be/test/CMakeLists.txt
  be/test/util/download_util_test.cpp
Labels: 3.1, 3.2

#40725 [BugFix] use db lock in follower or cbo_use_db_lock is true
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlanLockFreeTest.java
Labels: 2.5, 3.0, 3.1

#40745 [BugFix] Fix pk index gc which will clear pk index dir improperly
  be/src/storage/lake/local_pk_index_manager.cpp
Labels: 3.1, 3.2

#40353 [BugFix] make the AggregationType.NONE equals to null
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/AggregateType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVRewriteWithSchemaChangeTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40748 [Doc] Add lake_pk_compaction_max_input_rowsets
  docs/en/administration/BE_configuration.md
  docs/zh/administration/BE_configuration.md
Labels: documentation, 3.1, 3.2

#40715 [BugFix] use mv partition range to refresh when active mv
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  test/sql/test_materialized_view/R/test_materialized_view_status
  test/sql/test_materialized_view/T/test_materialized_view_status
Labels: 2.5, 3.0, 3.1, 3.2

#40634 [Doc] create table like supports specifying properties
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE_LIKE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE_LIKE.md
Labels: documentation, 3.2

#40747 [BugFix] Fix array_difference<largint> error
  be/src/exprs/vectorized/array_functions.tpp
Labels: 3.0

#40771 [Doc] support where in sync mv for 3.1.8
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
Labels: documentation, 3.1, 3.2

#40781 [Doc] add CTAS keyword to enhance search for 2.5
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE_AS_SELECT.md
Labels: documentation, 3.0

#39683 [Enhancement] Skip to write Hive table/column comment if comment is empty
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
Labels: 3.2

#40712 [Enhancement] Fixed an error message for a failed decimal validation
  fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ColumnDef.java
Labels: 3.1, 3.2

#40714 [Refactor] Remove database writeLock and readLock
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeLocks.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/Locker.java
  fe/fe-core/src/main/java/com/starrocks/consistency/LockChecker.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AccessTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CTASAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/MaterializedViewAutoTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowDbStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowDeleteTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DatabaseTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/InfoSchemaDbTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeLocksTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/cluster/SystemInfoServiceTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/TestLockInterface.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoCluster.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: META-REVIEW

#39590 [Enhancement] Support configuring HMS timeout param when creating hive/iceberg connector
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
Labels: 3.2

#39338 [BugFix] Fix unexpected memory copy in pipeline builder
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
Labels: 2.5, 3.0, 3.1, 3.2

#40732 [Doc] Add Trace Profile
  docs/en/assets/query_trace_profile.png
  docs/en/developers/trace-tools/query_trace_profile.md
  docs/en/reference/System_variable.md
  docs/zh/assets/query_trace_profile.png
  docs/zh/developers/trace-tools/query_trace_profile.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.2

#40795 [BugFix] Fix mistake use commit time and prepared time when check txn timeout
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
Labels: META-REVIEW

#40802 [BugFix] Fix keys_type not showed up in TabletSchema::debug_string
  be/src/storage/tablet_schema.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#38276 [Enhancement] Add MetadataMgr#getTableBasicInfo to avoid network interaction for external table
  fe/fe-core/src/main/java/com/starrocks/catalog/BasicTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalogTableBasicInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/ElasticsearchMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/odps/OdpsMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/unified/UnifiedMetadata.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/MockIcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MockedJDBCMetadata.java
  test/sql/test_information_schema/R/test_external_catalog_information_schema
  test/sql/test_information_schema/T/test_external_catalog_information_schema
Labels: behavior_changed, 3.2

#40798 [Enhancement] using stream to get iceberg scantask in list_partition_names
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
Labels: 3.1, 3.2

#40328 [BugFix] Fix bug dynamic partition date type does not support hour (backport #40256)
  fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/DynamicPartitionSchedulerTest.java
Labels: behavior_changed

#40710 [Enhancement] Optimize the lock contention of consistency checker
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/consistency/CheckConsistencyJob.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalTask.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/JournalWriterTest.java
Labels: 2.5, 3.0, 3.1, 3.2, META-REVIEW

#40828 [Doc] Update version info of array_unique_agg
  docs/en/sql-reference/sql-functions/array-functions/array_unique_agg.md
  docs/zh/sql-reference/sql-functions/array-functions/array_unique_agg.md
Labels: documentation, 3.1, 3.2

#40035 [Enhancement]Use union_iterator to get data from non-overlapping rowset during pk compaction
  be/src/storage/rowset_merger.cpp
Labels: 3.0, 3.1, 3.2

#40656 [BugFix]Fix tablet delete by mistake because of the outdate report version
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/system/SystemInfoServiceTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40756 [Enhancement] check chunk_size value before query execution
  be/src/common/constexpr.h
  be/src/runtime/fragment_mgr.cpp
  be/src/service/internal_service.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40792 [Enhancement] Enable chunk_size session variable for pipeline engine
  be/src/exec/pipeline/chunk_accumulate_operator.cpp
  be/src/exec/pipeline/chunk_accumulate_operator.h
  be/src/runtime/runtime_state.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/TFragmentInstanceFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
Labels: 3.2

#40854 [Doc] Add storage_volume to CREATE TABLE etc
  docs/en/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_TABLE.md
Labels: documentation, 3.1, 3.2

#40836 [BugFix] Fix _index_length not show up in debug_string
  be/src/storage/tablet_schema.cpp
  be/test/storage/tablet_schema_map_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40864 [Enhancement] Add MetadataMgr#getTableBasicInfo to avoid network interaction for external table (backport #38276)
  fe/fe-core/src/main/java/com/starrocks/catalog/BasicTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalog.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalogTableBasicInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaLakeMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/ElasticsearchMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/hudi/HudiMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/JDBCMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/privilege/DbPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/privilege/TablePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Authorizer.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/MockIcebergMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MockedJDBCMetadata.java
Labels: behavior_changed

#40880 [Doc] update syntax of impersonate
  docs/en/sql-reference/sql-statements/account-management/GRANT.md
  docs/en/sql-reference/sql-statements/account-management/SHOW_GRANTS.md
  docs/zh/sql-reference/sql-statements/account-management/GRANT.md
  docs/zh/sql-reference/sql-statements/account-management/SHOW_GRANTS.md
Labels: documentation, 3.0, 3.1, 3.2

#40672 [BugFix] Get rid of overwriting JobState after create an image
  fe/fe-core/src/main/java/com/starrocks/load/EtlStatus.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: 3.0, 3.1, 3.2

#40909 [UT] Fix timeout fe ut
  fe/fe-core/src/test/java/com/starrocks/alter/BatchRollupJobTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#40885 [BugFix] remove invalid `quantile="avg"` prometheus metric output
  be/src/http/action/metrics_action.cpp
Labels: 3.0, 3.1, 3.2

#40908 [BugFix] Fix possible NPE when mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCDSTest.java
Labels: 3.1, 3.2

#40874 [BugFix] Fix the problem of SinkIOBuffer getting stuck
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/sink/export_sink_operator.cpp
  be/src/exec/pipeline/sink/file_sink_operator.cpp
  be/src/exec/pipeline/sink/mysql_table_sink_operator.cpp
  be/src/exec/pipeline/sink/sink_io_buffer.cpp
  be/src/exec/pipeline/sink/sink_io_buffer.h
  be/src/runtime/runtime_state.h
  be/test/exec/sink/sink_io_buffer_test.cpp
Labels: 2.5, 3.0, 3.1, 3.2

#40701 Revert "[BugFix] Print create tablet log "
  be/src/agent/task_worker_pool.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
Labels: title needs [type]

#40923 [BugFix] The column unique ID may be incorrectly updated when upgrading to version 3.2.3
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/task/UpdateSchemaTask.java
Labels: 3.2

#40692 [BugFix] Fix the problem of column mode partial update in cross cluster replication
  be/src/agent/publish_version.cpp
  be/src/storage/delta_column_group.h
  be/src/storage/lake/replication_txn_manager.cpp
  be/src/storage/replication_txn_manager.cpp
  be/src/storage/replication_utils.cpp
  be/src/storage/replication_utils.h
  be/test/CMakeLists.txt
  be/test/storage/replication_utils_test.cpp
Labels: 3.1, 3.2

#40935 [Doc]fix the incorrect download url of kafka connector and incorrect syntax
  docs/en/sql-reference/sql-statements/data-manipulation/SHOW_ROUTINE_LOAD_TASK.md
  docs/zh/loading/Kafka-connector-starrocks.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SHOW_ROUTINE_LOAD_TASK.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40905 [Doc] add 3.1.8 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#40878 [Enhancement] Reduce iceberg job planning consumer time
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
Labels: 3.1, 3.2

#40464 [Feature] add sys.fe_memory_usage table
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/sys_fe_memory_usage.cpp
  be/src/exec/schema_scanner/sys_fe_memory_usage.h
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeMemoryUsage.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryStat.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeMemoryUsageTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_sys/R/test_fe_memory_usage
  test/sql/test_sys/T/test_fe_memory_usage
Labels: behavior_changed, PROTO-REVIEW

#40950 [Doc] Add SR Data Migration Tool doc
  docs/docusaurus/sidebars.json
  docs/en/administration/data_migration_tool.md
  docs/en/assets/data_migration_tool-1.png
  docs/zh/administration/data_migration_tool.md
  docs/zh/assets/data_migration_tool-1.png
Labels: documentation, 3.1, 3.2

#40955 [Doc] Fix materialized_views fields
  docs/en/administration/information_schema.md
  docs/zh/administration/information_schema.md
Labels: documentation

#40948 [BugFix] Should not send extra eof packet for COM_STMT_PREPARE
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.2

#40947 [Enhancement] Refine string metric merge algorithm
  be/src/exec/chunks_sorter_full_sort.cpp
  be/src/exec/query_cache/cache_operator.cpp
  be/src/exec/sorting/merge_path.cpp
  be/src/util/runtime_profile.cpp
  be/test/util/runtime_profile_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: 3.1, 3.2

#40957 [Doc] timestampadd/diff supports millisecond interval and add para desc
  docs/en/sql-reference/sql-functions/date-time-functions/timestampadd.md
  docs/en/sql-reference/sql-functions/date-time-functions/timestampdiff.md
  docs/zh/sql-reference/sql-functions/date-time-functions/timestampadd.md
  docs/zh/sql-reference/sql-functions/date-time-functions/timestampdiff.md
Labels: documentation, 3.2

#40910 [Enhancement] Change hive file split logic
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteScanRangeLocations.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/connector/RemoteScanRangeLocationsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: 3.0, 3.1, 3.2

#38957 [Enhancement] Make maximal varchar string length configurable in fe.conf and be.conf.
  be/src/common/config.h
  be/src/exprs/string_functions.cpp
  be/src/storage/CMakeLists.txt
  be/src/storage/olap_define.cpp
  be/src/storage/olap_define.h
  be/src/storage/tablet_schema.cpp
  be/src/storage/types.cpp
  be/test/exprs/string_fn_concat_test.cpp
  be/test/exprs/string_fn_pad_test.cpp
  be/test/exprs/string_fn_repeat_test.cpp
  be/test/exprs/string_fn_space_test.cpp
  be/test/storage/tablet_meta_test.cpp
  fe/fe-core/src/main/java/com/starrocks/analysis/TypeDef.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ScalarType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateFunctionStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ColumnDefTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/ColumnTypeConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzerUtilsTest.java
Labels: 3.1, 3.2

#40993 [Doc] add 2.5.19 release notes
  docs/en/release_notes/release-2.5.md
  docs/zh/release_notes/release-2.5.md
Labels: documentation

#40981 [BugFix] MERGE_LIMIT rule should be applied after PruneGroupByKeysRule's application
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
Labels: 3.1, 3.2

#40996 [Doc] Minor updates from 3.2.3
  docs/en/administration/Backup_and_restore.md
  docs/en/administration/FE_configuration.md
  docs/en/reference/System_variable.md
  docs/zh/administration/Backup_and_restore.md
  docs/zh/administration/FE_configuration.md
  docs/zh/reference/System_variable.md
Labels: documentation, 3.2

#40995 [Doc] Add 3.2.3 rn
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#39920 [Doc] Hudi quick start
  docs/docusaurus/sidebars.json
  docs/en/assets/1.1-8-dla.png
  docs/en/assets/3.8.1.png
  docs/en/assets/4.2-1.png
  docs/en/assets/commonMarkdown/datalakeIntro.md
  docs/en/assets/quick-start/hudi-test-bucket.png
  docs/en/quick_start/hudi.md
  docs/en/quick_start/iceberg.md
  docs/zh/quick_start/hudi.md
Labels: documentation, 3.2

#41010 [Doc] Remove tables
  docs/en/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
  docs/zh/using_starrocks/data_lake_query_acceleration_with_materialized_views.md
Labels: documentation, 3.2

#41018 [Doc] add info missing from Hudi quick start
  docs/en/quick_start/hudi.md
Labels: documentation, 3.2

#41021 [Doc] Edit hudi quickstart
  docs/en/quick_start/hudi.md
Labels: documentation, 3.2

#41029 [Enhancement] Use more specific license description for lz4
  licenses-binary/LICENSE-lz4.txt
Labels: 2.5, 3.0, 3.1, 3.2

#41038 [Doc] add license link
  docs/en/introduction/what_is_starrocks.md
  docs/zh/introduction/what_is_starrocks.md
Labels: documentation, 3.0, 3.1, 3.2

#41051 [BugFix] remove useless dcheck
  be/src/exec/scan_node.cpp
Labels: 3.2

#41039 [BugFix] Install en_US.UTF-8 locale in BE and Allin1 Dockerfile
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
  docker/dockerfiles/be/be-ubuntu.Dockerfile
Labels: 3.1, behavior_changed, 3.2

#41055 [Doc] Fix CN Char in migration tool
  docs/en/administration/data_migration_tool.md
Labels: documentation, 3.1, 3.2

#41061 [Doc] remove insert+files from hdfs load doc (backport #41061)
  docs/en/loading/hdfs_load.md
  docs/zh/loading/hdfs_load.md
Labels: documentation

#41054 [BugFix] Fix crash when using sort key in column with row store
  be/src/exec/short_circuit_hybrid.cpp
Labels: 3.2

#40613 [Enhancement] Make PosixFileSystem::iterate_dir2 more robust
  be/src/fs/fs_posix.cpp
  be/src/storage/lake/vacuum.cpp
Labels: 3.1, 3.2

#41079 [Feature] add sys.fe_memory_usage table (backport #40464)
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/sys_fe_memory_usage.cpp
  be/src/exec/schema_scanner/sys_fe_memory_usage.h
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeMemoryUsage.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryStat.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeMemoryUsageTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_sys/R/test_fe_memory_usage
  test/sql/test_sys/T/test_fe_memory_usage
Labels: behavior_changed

#41083 [Feature] add sys.fe_memory_usage table (backport #40464)
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/sys_fe_memory_usage.cpp
  be/src/exec/schema_scanner/sys_fe_memory_usage.h
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeMemoryUsage.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryStat.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeMemoryUsageTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_sys/R/test_fe_memory_usage
  test/sql/test_sys/T/test_fe_memory_usage
Labels: behavior_changed

#41092 [Feature] add sys.fe_memory_usage table (backport #40464)
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/sys_fe_memory_usage.cpp
  be/src/exec/schema_scanner/sys_fe_memory_usage.h
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysFeMemoryUsage.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryStat.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysFeMemoryUsageTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_sys/R/test_fe_memory_usage
  test/sql/test_sys/T/test_fe_memory_usage
Labels: behavior_changed

#41089 [Enhancement] when ddl input is invalid, set error type as ANALYSIS_ERR
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  test/sql/test_alter_table/R/test_alter_table_abnormal
  test/sql/test_auto_increment/R/test_auto_increment
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_partition/R/test_automatic_partition_list
  test/sql/test_column_rename/R/test_column_rename
  test/sql/test_column_rename/R/test_column_rename2
  test/sql/test_ddl/R/test_alter_pk_reorder
  test/sql/test_dictionary/R/test_dictionary
  test/sql/test_fast_schema_evolution/R/test_fast_schema_evolution
  test/sql/test_function/R/test_substr
  test/sql/test_iceberg/R/test_iceberg_alter_table
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_view/R/test_mv_on_view
  test/sql/test_materialized_view/R/test_mv_swap
  test/sql/test_primary_index_cache_expire/R/test_primary_index_cache_expire
  test/sql/test_random_distribution/R/test_random_distribution
  test/sql/test_sort_key/R/test_sort_key_agg_tbl
  test/sql/test_sort_key/R/test_sort_key_uni_tbl
  test/sql/test_storage_volume/R/create_storage_volume
  test/sql/test_storage_volume/R/drop_storage_volume
  test/sql/test_storage_volume/R/set_as_default
  test/sql/test_task/R/test_drop
Labels: behavior_changed

#37875 [Feature] `files()` supports CSV format
  be/src/exec/csv_scanner.cpp
  be/src/exec/csv_scanner.h
  be/src/exec/file_scanner.cpp
  be/src/exec/file_scanner.h
  be/test/exec/csv_scanner_test.cpp
  be/test/exec/test_data/csv_scanner/csv_file23
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
  fe/fe-core/src/test/java/com/starrocks/load/LoadTest.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_files/R/csv_format
  test/sql/test_files/T/csv_format
  test/sql/test_files/csv_format/basic1.csv
  test/sql/test_files/csv_format/basic2.csv
Labels: behavior_changed, PROTO-REVIEW

#40682 [Enhancement] support internal-sql log (backport #40453)
  fe/fe-core/src/main/java/com/starrocks/common/AuditLog.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java
  fe/fe-core/src/main/java/com/starrocks/http/action/LogAction.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
Labels: behavior_changed

#41112 [Doc] delete unsupported loading method from Branch 3.0
  docs/en/integrations/hive_bitmap_udf.md
  docs/zh/integrations/hive_bitmap_udf.md
Labels: documentation

#41105 [Doc] Http sql API supports querying lake tables
  docs/en/reference/HTTP_API/SQL.md
  docs/zh/reference/HTTP_API/SQL.md
Labels: documentation, 3.2

#41107 [BugFix] split limit directly in some rules (backport #36051)
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/NestLoopJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: automerge

#41111 [Doc] Optimize syntax of alias in unnest
  docs/en/sql-reference/sql-functions/array-functions/unnest.md
  docs/en/using_starrocks/Lateral_join.md
  docs/zh/sql-reference/sql-functions/array-functions/unnest.md
  docs/zh/using_starrocks/Lateral_join.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40921 [BugFix] Fix hive view query table/view/alias name are not case-insensitive
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/View.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/QueryAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveViewTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/MockedHiveMetadata.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: 3.1, 3.2

#39482 [Feature] support probe side subscribe pipeline finish event
  be/src/exec/pipeline/adaptive/event.cpp
  be/src/exec/pipeline/adaptive/event.h
  be/src/exec/pipeline/pipeline_builder.cpp
  be/src/exec/pipeline/pipeline_builder.h
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_multi_ops/R/test_depends_ops
  test/sql/test_multi_ops/T/test_depends_ops
Labels: PROTO-REVIEW

#41134 [Doc]delete unsupported syntax ”with rollup, with cude“ in GROUP BY
  docs/en/sql-reference/sql-statements/data-manipulation/GROUP_BY.md
  docs/en/sql-reference/sql-statements/data-manipulation/SELECT.md
  docs/zh/sql-reference/sql-statements/data-manipulation/SELECT.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#41115 [Enhancement] Evaluate time functions with constant arguments
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 3.2

#41144 [Doc] add keywords to stream load and broker load docs
  docs/en/loading/StreamLoad.md
  docs/en/loading/Stream_Load_transaction_interface.md
  docs/en/loading/azure.md
  docs/en/loading/gcs.md
  docs/en/loading/hdfs_load.md
  docs/en/loading/s3.md
  docs/zh/loading/StreamLoad.md
  docs/zh/loading/Stream_Load_transaction_interface.md
  docs/zh/loading/azure.md
  docs/zh/loading/gcs.md
  docs/zh/loading/hdfs_load.md
  docs/zh/loading/s3.md
Labels: documentation, 3.2

#41169 [Doc] update stream load doc
  docs/en/loading/StreamLoad.md
  docs/zh/loading/StreamLoad.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#41135 [Enhancement] Add shared buffer align size stat
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/io/shared_buffered_input_stream.cpp
  be/src/io/shared_buffered_input_stream.h
Labels: 3.1, 3.2

#41159 [Doc] Update Stream_Load_transaction_interface.md (backport #41144)
  docs/en/loading/Stream_Load_transaction_interface.md
Labels: documentation

#41160 [Doc] Update StreamLoad.md (backport #41144)
  docs/en/loading/StreamLoad.md
Labels: documentation

#41165 [Doc] Update StreamLoad.md (backport #41144)
  docs/zh/loading/StreamLoad.md
Labels: documentation

#41161 [Doc] Update Stream_Load_transaction_interface.md (backport #41144)
  docs/zh/loading/Stream_Load_transaction_interface.md
Labels: documentation

#41164 [Doc] Update BrokerLoad.md (backport #41144)
  docs/zh/loading/BrokerLoad.md
Labels: documentation

#41082 [BugFix] Fix spark load load start timestamp not set
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadJobTest.java
Labels: 2.5, 3.0, 3.1, 3.2

#41162 [Doc] Update BrokerLoad.md (backport #41144)
  docs/en/loading/BrokerLoad.md
Labels: documentation

#41150 [BugFix] Fixed the mem statistics problem of manual compaction
  be/src/storage/task/engine_manual_compaction_task.cpp
  be/src/storage/task/engine_manual_compaction_task.h
Labels: 3.1, 3.2

#39883 [Enhancement] Improve data cleanup performance for dropped tables in shared data mode
  be/src/fs/fs_posix.cpp
  be/src/service/service_be/lake_service.cpp
  be/test/service/lake_service_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/SysDb.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/persist/DisableTableRecoveryInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableCleanerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableTest.java
  gensrc/proto/lake_service.proto
  test/sql/test_drop_table/R/test_drop_table
  test/sql/test_drop_table/T/test_drop_table
Labels: 3.1, 3.2, META-REVIEW, PROTO-REVIEW

#40679 [BugFix] Fix stuck when transform from batch to single publish
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.2

#40853 [Enhancement] Add storage volume in tables_config
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  fe/fe-core/src/test/java/com/starrocks/service/LakeInformationSchemaDataSourceTest.java
Labels: 3.1, 3.2

#40355 [Feature] concurrently jit and put compiled func into LRU cache
  be/CMakeLists.txt
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/exec/aggregator.cpp
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_operation.h
  be/src/exprs/binary_predicate.cpp
  be/src/exprs/case_expr.cpp
  be/src/exprs/cast_expr.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/jit/ir_helper.cpp
  be/src/exprs/jit/ir_helper.h
  be/src/exprs/jit/jit_engine.cpp
  be/src/exprs/jit/jit_engine.h
  be/src/exprs/jit/jit_expr.cpp
  be/src/exprs/jit/jit_expr.h
  be/src/exprs/literal.cpp
  be/src/exprs/literal.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/script/script.cpp
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/test/CMakeLists.txt
  be/test/exprs/cast_expr_test.cpp
  be/test/exprs/jit_func_cache_test.cpp
  docs/en/administration/metrics.md
  docs/zh/administration/Memory_management.md
  docs/zh/administration/metrics.md
  test/sql/test_jit/R/test_jit_cast
  test/sql/test_jit/T/test_jit_cast
  thirdparty/build-thirdparty.sh
Labels: documentation

#41207 [Doc] add note to stream load transaction interface doc
  docs/en/loading/Stream_Load_transaction_interface.md
  docs/zh/loading/Stream_Load_transaction_interface.md
Labels: documentation, 2.5, 3.0, 3.1, 3.2

#40638 [BugFix] Fix data ingestion stuck when the new automatic partition and the old partition are distributed on different backends
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/exec/tablet_sink_sender.cpp
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
Labels: 3.0, 3.1, 3.2

#41049 [Enhancement] use static link for latest datadog ddprof download link
  docker/dockerfiles/artifacts/artifact.Dockerfile
Labels: 3.1, 3.2

#41080 [BugFix] fix resultset metadata of prepare protocol
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/analysis/Parameter.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlCapability.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PrepareAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/analysis/PreparedStmtTest.java
Labels: 3.2

#41216 [Doc] update catalog overview doc
  docs/en/data_source/catalog/catalog_overview.md
  docs/en/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
  docs/zh/data_source/catalog/catalog_overview.md
  docs/zh/sql-reference/sql-statements/data-definition/CREATE_EXTERNAL_CATALOG.md
Labels: documentation, 3.1, 3.2

#41235 [Doc] Optimize info in parameters and SQL according to feedback
  docs/en/administration/BE_configuration.md
  docs/en/administration/FE_configuration.md
  docs/en/administration/Query_management.md
  docs/en/reference/System_limit.md
  docs/en/reference/System_variable.md
  docs/en/sql-reference/sql-statements/data-definition/ALTER_DATABASE.md
  docs/zh/administration/BE_configuration.md
  docs/zh/administration/FE_configuration.md
  docs/zh/reference/System_limit.md
  docs/zh/reference/System_variable.md
  docs/zh/sql-reference/sql-statements/data-definition/ALTER_DATABASE.md
Labels: documentation, 3.2
