Repository StarRocks/starrocks, pull requests merged in 2025-09, with the labels that each got.

#62457 [BugFix] fix the http_workers_num metric
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
Labels: 3.4, 3.5, 4.0

#62465 [BugFix] Fix colocate group execution not found exec group
  fe/fe-core/src/main/java/com/starrocks/planner/ExecGroupSets.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterPushDownContext.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupExecutionPlanTest.java
Labels: 3.5, 4.0

#62300 [BugFix] Fix optimize table task submit reject
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
Labels: 3.3, 3.4, 3.5, 4.0

#62533 [BugFix] fix statistics collection error message
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
Labels: 3.5, 4.0

#62518 [Enhancement] Add config to disable statistics cache lazy refresh by default
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
Labels: 3.3, 3.4, 3.5, 4.0

#62510 [BugFix] Fix int256_t negation undefined behavior causing memory allocation failure
  be/src/types/int256.cpp
  be/src/types/int256.h
Labels: 4.0

#62476 [Enhancement] Change transform type prefer string for fixed length varchar
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java
  fe/fe-core/src/test/java/com/starrocks/catalog/combinator/AggStateCombinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVRewriteWithSchemaChangeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  test/sql/test_automatic_partition/R/test_multi_expr
  test/sql/test_files/R/test_orc_struct
Labels: documentation, 4.0

#62596 [Doc] 3.4.7 Release Notes
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#62019 [Enhancement] Support multi statements transaction (part2)
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/filenames.h
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/txn_log.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/txn_log_applier.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/CMakeLists.txt
  be/test/storage/lake/async_delta_writer_test.cpp
  be/test/storage/lake/delta_writer_test.cpp
  be/test/storage/lake/meta_file_test.cpp
  be/test/storage/lake/transactions_test.cpp
  be/test/storage/lake/txn_log_applier_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/TxnInfoHelper.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/DeletePlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java
  fe/fe-core/src/main/java/com/starrocks/transaction/ExplicitTxnState.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/lake/TxnInfoHelperTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionStateTest.java
  fe/fe-spi/src/main/java/com/starrocks/common/ErrorCode.java
  gensrc/proto/internal_service.proto
  gensrc/proto/lake_types.proto
  gensrc/thrift/DataSinks.thrift
Labels: PROTO-REVIEW, 4.0

#62479 [Enhancement] Add clone metrics in backend
  be/src/agent/agent_task.cpp
  be/src/fs/fs_util.h
  be/src/storage/lake/transactions.cpp
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
  be/src/storage/task/engine_storage_migration_task.h
  be/src/util/starrocks_metrics.cpp
  be/src/util/starrocks_metrics.h
  be/test/storage/task/engine_storage_migration_task_test.cpp
  be/test/util/starrocks_metrics_test.cpp
Labels: 3.5, 4.0

#62598 [BugFix] Fix case-sensitive partition column validation in materialized view analyzer
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzerTest.java
Labels: 3.3, 3.4, 3.5, 4.0

#62618 [Doc] Doc for pipeline_sink_dop
  docs/en/sql-reference/System_variable.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62661 [Enhancement] turn on tablet balance between workers by default in shared-data mode
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: documentation, behavior_changed, 3.5, 4.0

#62586 [Enhancement] disable low card on lake by default because of potential bugs
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: behavior_changed, 4.0

#62670 [Enhancement] Disable ARRAY function for DECIMAL256 type
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
  test/sql/test_decimal/R/test_decimal256_complex_types
  test/sql/test_decimal/T/test_decimal256_complex_types.sql
Labels: 4.0

#62664 [UT] add more decimal256 sql test cases
  test/sql/test_decimal/R/test_decimal256_partitioned_tables
  test/sql/test_decimal/R/test_decimal256_string_functions
  test/sql/test_decimal/R/test_decimal256_subquery_cte
  test/sql/test_decimal/R/test_decimal256_window_functions
  test/sql/test_decimal/T/test_decimal256_partitioned_tables.sql
  test/sql/test_decimal/T/test_decimal256_string_functions.sql
  test/sql/test_decimal/T/test_decimal256_subquery_cte.sql
  test/sql/test_decimal/T/test_decimal256_window_functions.sql
Labels: 4.0

#62697 [BugFix] fix iceberg transform compact bug
  be/src/runtime/descriptors.cpp
  be/src/runtime/iceberg_table_sink.cpp
Labels: 4.0

#62729 [Doc] fix typo
  docs/zh/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
Labels: documentation, 3.5, 4.0

#62744 [Doc] Separator and Delimiter with Multiple Non-printable Characters
  docs/en/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
  docs/ja/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62490 [Enhancement] Health Action need to be handled synchronously
  fe/fe-core/src/main/java/com/starrocks/http/rest/HealthAction.java
  fe/fe-core/src/test/java/com/starrocks/http/HealthActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/HttpServerHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/http/HttpServerTestUtils.java
Labels: 3.5, 4.0

#51007 [Enhancement] add command to show the dropped meta information that can be recovered
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_recyclebin_catalogs.cpp
  be/src/exec/schema_scanner/schema_recyclebin_catalogs.h
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/SystemId.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/InfoSchemaDb.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/RecycleBinCatalogsTable.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  test/sql/test_information_schema/R/test_recyclebin_catalogs
  test/sql/test_information_schema/T/test_recyclebin_catalogs
Labels: PROTO-REVIEW

#62759 [Doc] Update Partitioned Materialized View
  docs/en/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/ja/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/zh/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62246 [BugFix] storage volume delete should not be allowed if active snapshot present
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: 4.0

#62719 [BugFix] Fix csv header skip causing data loss in files()
  be/src/exec/file_scanner/csv_scanner.cpp
  be/test/exec/file_scanner/csv_scanner_test.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#62771 [UT] fix sql test for low card on lake
  test/sql/test_global_dict/R/dict_lake_period_version
  test/sql/test_global_dict/R/global_dict_on_lake
  test/sql/test_global_dict/T/dict_lake_period_version
  test/sql/test_global_dict/T/global_dict_on_lake
Labels: 3.5, 4.0

#62801 [BugFix][CVE-2025-58056] bump io.netty version to 4.1.125.Final
  fe/build.gradle.kts
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/src/pom.xml
  java-extensions/pom.xml
Labels: 3.3, 3.4, 3.5, 4.0

#62796 [BugFix] fix NPE of information_schema.analyze_status when db is dropped
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/AnalyzeStatusSystemTable.java
  fe/fe-core/src/test/java/com/starrocks/statistic/AnalyzeMgrTest.java
Labels: 3.5, 4.0

#62815 [Doc] JA version Tag for 3.5 and 3.4
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
Labels: documentation, 3.4

#62835 [Doc] Format setting names in README as inline code
  docs/README.md
Labels: documentation

#61889 [Doc] Rebuild Data Distribution
  docs/en/best_practices/table_clustering.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/en/table_design/data_distribution/Data_distribution.md
  docs/en/table_design/data_distribution/dynamic_partitioning.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/best_practices/table_clustering.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/ja/table_design/data_distribution/Data_distribution.md
  docs/ja/table_design/data_distribution/dynamic_partitioning.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/best_practices/table_clustering.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/table_design/data_distribution/Data_distribution.md
  docs/zh/table_design/data_distribution/dynamic_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation, 3.4, 3.5, 4.0

#61364 [Enhancement] Add transaction error message to loads internal table
  fe/fe-core/src/main/java/com/starrocks/load/LoadConstants.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: 3.3, 3.4, 3.5

#61417 [Enhancement] Add a cleaner for BrpcStubCache to cleanup unused connections
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/util/brpc_stub_cache.cpp
  be/src/util/brpc_stub_cache.h
  be/test/http/stream_load_test.cpp
  be/test/http/transaction_stream_load_test.cpp
  be/test/util/brpc_stub_cache_test.cpp
  docs/en/administration/management/BE_configuration.md
Labels: documentation

#62158 [Doc] Optimized Function Docs for v4.0
  docs/en/sql-reference/sql-functions/aggregate-functions/bool_or.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_hash64.md
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  docs/en/sql-reference/sql-functions/string-functions/strpos.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
  docs/ja/sql-reference/sql-functions/aggregate-functions/bool_or.md
  docs/ja/sql-reference/sql-functions/bitmap-functions/bitmap_hash64.md
  docs/ja/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  docs/ja/sql-reference/sql-functions/string-functions/strpos.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/bool_or.md
  docs/zh/sql-reference/sql-functions/bitmap-functions/bitmap_hash64.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  docs/zh/sql-reference/sql-functions/string-functions/strpos.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SELECT.md
Labels: documentation, 4.0

#62641 [Doc] V4.0 Iceberg Compaction
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 4.0

#62822 [Doc] 4.0.0-RC Release Notes
  docs/en/release_notes/release-4.0.md
  docs/ja/release_notes/release-4.0.md
  docs/zh/release_notes/release-4.0.md
Labels: documentation

#62042 [Doc] Doc Update for Indexes
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_INDEX.md
  docs/en/table_design/indexes/indexes.md
  docs/en/table_design/indexes/inverted_index.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_INDEX.md
  docs/ja/table_design/indexes/indexes.md
  docs/ja/table_design/indexes/inverted_index.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_INDEX.md
  docs/zh/table_design/indexes/indexes.md
  docs/zh/table_design/indexes/inverted_index.md
Labels: documentation, 4.0

#62576 [Doc] Iceberg REST Catalog supports Vended Credentials
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 4.0

#62767 [Enhancement] provide alter table xxx set auto_increment
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterOpType.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterTableAutoIncrementClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitorExtendInterface.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTableAutoIncrementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTestUtil.java
  fe/fe-grammar/src/main/antlr/com/starrocks/grammar/StarRocks.g4
  test/sql/test_auto_increment/R/test_auto_increment
  test/sql/test_auto_increment/T/test_auto_increment
Labels: 3.5, 4.0

#62638 [BugFix] fix missing compaction profile when file bundling is on
  be/src/service/service_be/lake_service.cpp
  be/test/service/lake_service_test.cpp
Labels: 4.0

#62842 [BugFix] fix kill analyze command
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/HyperQueryJob.java
Labels: 3.3-merged, 3.4-merged, 3.5, 4.0

#62861 [BugFix] fix nullptr delta writer in local tablet channel
  be/src/runtime/local_tablets_channel.cpp
  be/test/runtime/local_tablets_channel_test.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#62711 [Enhancement] Support use DN to match group in group provider
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationHandler.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/FileGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/GroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UnixGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorReport.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteAsExecutor.java
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/ExecuteAsExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/FileGroupProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/LDAPAuthProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
  fe/fe-core/src/test/resources/auth/file_group
  fe/fe-spi/src/main/java/com/starrocks/authentication/AuthenticationContext.java
Labels: 3.5, 4.0

#62460 [Feature] Add the way to set AUTO_INCREMENT column when PRIMARY_KEY is on other column for Starrocks python client
  contrib/starrocks-python-client/starrocks/__init__.py
  contrib/starrocks-python-client/starrocks/dialect.py
Labels: behavior_changed

#62858 [Doc] fixed hardcoded outdated JDBC link to general Tableau JDBC marketplace link
  docs/en/integrations/BI_integrations/Tableau_Desktop.md
  docs/ja/integrations/BI_integrations/Tableau_Desktop.md
  docs/zh/integrations/BI_integrations/Tableau_Desktop.md
Labels: documentation, 3.5, 4.0

#62542 [BugFix] Fix redundant replica handling after clone
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
Labels: 3.3, 3.4, 3.5, 4.0

#62802 [BugFix] Fix collecting stream load profile failed
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfileManager.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  test/lib/sr_sql_lib.py
  test/sql/test_profile/R/test_load_channel_profile
  test/sql/test_profile/T/test_load_channel_profile
Labels: 3.4, 3.5, 4.0

#62878 [Doc] Add recyclebin_catalogs system table doc
  docs/en/sql-reference/information_schema/recyclebin_catalogs.md
  docs/ja/sql-reference/information_schema/recyclebin_catalogs.md
  docs/zh/sql-reference/information_schema/recyclebin_catalogs.md
Labels: documentation, 4.0

#62928 [BugFix] Revert Add transaction error message to loads internal table (#61364)
  fe/fe-core/src/main/java/com/starrocks/load/LoadConstants.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: 3.5, 4.0

#62946 [Doc] Fix DROP ROLE Description
  docs/en/sql-reference/sql-statements/account-management/DROP_ROLE.md
  docs/ja/sql-reference/sql-statements/account-management/DROP_ROLE.md
  docs/zh/sql-reference/sql-statements/account-management/DROP_ROLE.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#63096 [UT] Fix optimize job test
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
Labels: 4.0

#63073 [Doc] Add clone metrics doc
  docs/en/administration/management/monitoring/metrics.md
  docs/ja/administration/management/monitoring/metrics.md
  docs/zh/administration/management/monitoring/metrics.md
Labels: documentation, 3.5, 4.0

#62781 [Enhancement] Force drop decommissioned backend if all the tablets in recycle bin
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletInvertedIndex.java
  fe/fe-core/src/test/java/com/starrocks/alter/SystemHandlerCanForceDropTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletInvertedIndexTest.java
Labels: 3.5, 4.0

#63115 [Doc] Add DN matching mechanism for LDAP Group Provider and update documentation
  docs/en/administration/user_privs/authentication/ldap_authentication.md
  docs/en/administration/user_privs/authentication/security_integration.md
  docs/en/administration/user_privs/group_provider.md
  docs/ja/administration/user_privs/authentication/ldap_authentication.md
  docs/ja/administration/user_privs/authentication/security_integration.md
  docs/ja/administration/user_privs/group_provider.md
  docs/zh/administration/user_privs/authentication/ldap_authentication.md
  docs/zh/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/group_provider.md
Labels: documentation, 3.5, 4.0

#63114 [Enhancement] Loose check mv's schema for better compatibilities
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: behavior_changed, 4.0

#63132 [Enhancement] Improve fragment instance exec state report
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
Labels: 3.5, 4.0

#61589 [BugFix] fix corner case failing to clean expired stream load tasks
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
Labels: 3.3, 3.4

#62961 [BugFix] Fix transaction write deadlock due to set error message
  fe/fe-core/src/main/java/com/starrocks/load/LoadConstants.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: 3.5, 4.0

#63204 [Doc] Add keywords for query tuning introduction
  docs/zh/best_practices/query_tuning/query_plan_intro.md
Labels: documentation, 3.4, 3.5, 4.0

#63183 [Doc] Add references for sys.policy_references
  docs/en/_assets/commonMarkdown/_feature_availability.mdx
  docs/en/sql-reference/sys/policy_references.md
  docs/en/sql-reference/sys/sys.md
  docs/ja/_assets/commonMarkdown/_feature_availability.mdx
  docs/ja/sql-reference/sys/policy_references.md
  docs/ja/sql-reference/sys/sys.md
  docs/zh/_assets/commonMarkdown/_feature_availability.mdx
  docs/zh/sql-reference/sys/policy_references.md
  docs/zh/sql-reference/sys/sys.md
Labels: documentation, 3.4, 3.5, 4.0

#63173 [BugFix] Fix the bug where UserProperty priority is lower than Session Variable
  fe/build.gradle.kts
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteAsExecutor.java
  fe/fe-core/src/test/java/com/starrocks/authentication/UserPropertyTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ForwardTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/VariablePriorityTest.java
  fe/fe-parser/src/main/java/com/starrocks/sql/ast/UserRef.java
Labels: 3.3, 3.4, 3.5, 4.0

#62663 [BugFix] Fix version check failed while appling replication txn with compaction enabled
  be/src/storage/lake/txn_log_applier.cpp
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.3, 3.4, 3.5, 4.0

#62048 [Enhancement] Emit routine load lag time
  docs/en/administration/management/monitoring/metrics.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricCalculator.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/metric/RoutineLoadLagTimeMetricMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/RoutineLoadLagTimeMetricMgrTest.java
Labels: documentation, 3.5, 4.0

#63239 [Enhancement] Emit routine load lag time (backport #62048)
  docs/en/administration/management/monitoring/metrics.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricCalculator.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/metric/RoutineLoadLagTimeMetricMgr.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/RoutineLoadLagTimeMetricMgrTest.java
Labels: documentation

#63168 [Enhancement] Update default bucket size of random distribution
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  test/sql/test_alter_table/R/test_alter_column_comment
  test/sql/test_automatic_bucket/R/test_automatic_partition
  test/sql/test_automatic_partition/R/test_automatic_partition_concurrent
  test/sql/test_compaction_cron/R/test_compaction_cron
  test/sql/test_ddl/R/test_alter_swap_table
  test/sql/test_http_sql/R/test_http_output
  test/sql/test_load/R/test_load_profile
  test/sql/test_partition_by_expr/R/test_expr_from_unixtime
  test/sql/test_partition_by_expr/R/test_expr_from_unixtime_add_partition
  test/sql/test_partition_by_expr/R/test_expr_str2date
  test/sql/test_random_distribution/R/test_random_distribution
  test/sql/test_temporary_table/R/temporary_table
Labels: behavior_changed, 4.0

#63246 [UT] Fix timeout SQL Test
  test/sql/test_agg_function/R/test_approx_top_k
  test/sql/test_agg_function/T/test_approx_top_k
  test/sql/test_low_cardinality/R/test_low_cardinality_parquet_cancel
  test/sql/test_low_cardinality/T/test_low_cardinality_parquet_cancel
Labels: 3.3, 3.4, 3.5, 4.0

#63257 [BugFix] Fix BE crash in tracer when jaeger_endpoint is invalid
  be/src/common/config.h
  be/src/common/tracer.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#63143 [BugFix] Fix incompatible zonemap reuse for fast schema evolution in shared-data
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/main/java/com/starrocks/catalog/SchemaChangeTypeCompatibility.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/SchemaChangeTypeCompatibilityTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TypeTest.java
Labels: 3.3, 3.4, 3.5, 4.0

#63242 [Enhancement] Make BE reject multi-statement transaction stream load
  be/src/http/action/transaction_stream_load.cpp
  be/src/http/http_common.h
  test/sql/test_stream_load/R/test_be_reject_transaction_type
  test/sql/test_stream_load/T/test_be_reject_transaction_type
Labels: 4.0

#63330 [Doc] add video
  docs/en/quick_start/shared-nothing.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#63297 [Enhancement] remove the adaptive zonemap creation
  be/src/common/config.h
  be/src/storage/rowset/column_writer.cpp
  be/src/storage/rowset/column_writer.h
  be/test/storage/rowset/zone_map_index_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 4.0

#63348 [Doc] 3.5.6 Release Notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#63296 [BugFix] fix duplicate key table delete issue in shared-data mode
  fe/fe-core/src/main/java/com/starrocks/lake/delete/LakeDeleteJob.java
  fe/fe-core/src/test/java/com/starrocks/lake/delete/LakeDeleteJobTest.java
  test/sql/test_delete/R/test_delete_dupkey_rename
  test/sql/test_delete/T/test_delete_dupkey_rename
Labels: 3.3, 3.4, 3.5, 4.0

#63277 [BugFix] Fix pk index cumulative compaction strategy when max_rss_rowid is same
  be/src/storage/lake/lake_persistent_index.cpp
  be/test/storage/lake/lake_persistent_index_test.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#63243 [BugFix] Fix bug where reserved words in iceberg partitions break toThrift
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  test/sql/test_iceberg/R/test_iceberg_show_stmt
Labels: 4.0

#63373 [Enhancement] revise iceberg cache paramters
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalogProperties.java
Labels: behavior_changed, 3.5, 4.0

#63377 [BugFix] Fix zone map incorrect filtering after CHAR to VARCHAR fast schema evolution in shared-data
  be/src/storage/rowset/column_reader.cpp
  be/src/storage/rowset/column_reader.h
  be/test/storage/rowset/segment_iterator_test.cpp
Labels: 4.0

#63392 [Doc] Add document for iceberg table sorting function.
  docs/en/administration/management/BE_configuration.md
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/administration/management/BE_configuration.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 4.0

#63317 [Doc]Update iceberg_catalog.md
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 4.0

#63457 [Doc] Update SQL Blacklist Doc
  docs/en/administration/management/resource_management/Blacklist.md
  docs/en/sql-reference/sql-statements/cluster-management/sql_blacklist/ADD_SQLBLACKLIST.md
  docs/ja/administration/management/resource_management/Blacklist.md
  docs/ja/sql-reference/sql-statements/cluster-management/sql_blacklist/ADD_SQLBLACKLIST.md
  docs/zh/administration/management/resource_management/Blacklist.md
  docs/zh/sql-reference/sql-statements/cluster-management/sql_blacklist/ADD_SQLBLACKLIST.md
Labels: documentation, 3.4, 3.5, 4.0

#63502 [UT] fix unstable distance function cases because of precision
  test/sql/test_function/R/test_math
  test/sql/test_function/T/test_math
Labels: 3.3, 3.4, 3.5, 4.0

#63520 [UT] Fix unstability security test case
  fe/fe-core/src/test/java/com/starrocks/authentication/GroupProviderPermissionTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationPermissionTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/SecurityIntegrationTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/GroupProviderAstBuilderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/parser/SecurityIntegrationAstBuilderTest.java
  fe/fe-grammar/src/main/antlr/com/starrocks/grammar/StarRocks.g4
  test/sql/test_execute_as/R/test_execute_as_internal_user
  test/sql/test_execute_as/T/test_execute_as_internal_user
  test/sql/test_security_integration/R/test_group_provider
  test/sql/test_security_integration/R/test_security_integration
  test/sql/test_security_integration/T/test_group_provider
  test/sql/test_security_integration/T/test_security_integration
Labels: 3.5, 4.0

#63548 [Doc] Fix CN shared-data quick start
  docs/zh/_assets/quick-start/MinIO-view-key.png
  docs/zh/quick_start/shared-data.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#63480 [Enhancement] add querySource in the QueryDetail & AuditEvent
  fe/fe-core/src/main/java/com/starrocks/plugin/AuditEvent.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryDetail.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MVTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTBasedRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/ivm/MVIVMBasedMVRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailQueueTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryDetailTest.java
Labels: 3.4, 3.5, 4.0

#63543 [BugFix] disable shared_scan
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
Labels: behavior_changed, 3.5, 4.0

#63521 [Enhancement] Split sumcount and distinct registration files
  be/src/exprs/CMakeLists.txt
  be/src/exprs/agg/factory/aggregate_resolver_distinct.cpp
  be/src/exprs/agg/factory/aggregate_resolver_sumcount.cpp
Labels: 4.0

#63608 [UT] Fix mv unstable test cases
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithHiveTableTest.java
Labels: 4.0

#63595 [BugFix] Fix shutdown tablet can not gc
  be/src/storage/tablet_manager.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#63615 [UT] Avoid partition ttl scheduler affecting tests
  test/test_sql_cases.py
Labels: 4.0

#63384 [Enhancement] Improve delvec file cleanup logic to properly handle pk index references
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/lake_delvec_loader.cpp
  be/src/storage/lake/lake_delvec_loader.h
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/lake_primary_index.cpp
  be/src/storage/lake/lake_primary_index.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/persistent_index_sstable.cpp
  be/src/storage/lake/persistent_index_sstable.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/lake/meta_file_test.cpp
  be/test/storage/lake/persistent_index_sstable_test.cpp
  gensrc/proto/lake_types.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#63590 [Doc] sys.fe_locks
  docs/en/sql-reference/information_schema/fe_locks.md
  docs/ja/sql-reference/information_schema/fe_locks.md
  docs/zh/sql-reference/information_schema/fe_locks.md
Labels: documentation, 3.4, 3.5, 4.0

#63627 [Doc] Rephrase Temporary Table Limitation and Minimize QR image
  docs/en/table_design/StarRocks_table_design.md
  docs/ja/table_design/StarRocks_table_design.md
  docs/zh/_assets/wechat_scan.png
  docs/zh/table_design/StarRocks_table_design.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#63643 [Doc] Fix fe_locks Location
  docs/en/sql-reference/sys/fe_locks.md
  docs/en/sql-reference/sys/sys.md
  docs/ja/sql-reference/sys/fe_locks.md
  docs/ja/sql-reference/sys/sys.md
  docs/zh/sql-reference/sys/fe_locks.md
  docs/zh/sql-reference/sys/sys.md
Labels: documentation, 3.4, 3.5, 4.0

#63665 [Doc] column_size and column_compressed_size functions
  docs/en/sql-reference/sql-functions/utility-functions/column_size_functions.md
  docs/ja/sql-reference/sql-functions/utility-functions/column_size_functions.md
  docs/zh/sql-reference/sql-functions/utility-functions/column_size_functions.md
Labels: documentation, 4.0

#63667 [Enhancement] Bump Iceberg version to 1.10.0
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestReader.java
  fe/pom.xml
  java-extensions/pom.xml
Labels: 4.0

#63686 [BugFix] fix allin1 health check cmd
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
Labels: 4.0

#63629 [BugFix] lz4 encode/decode
  be/src/serde/column_array_serde.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#63696 [Doc] Revise StarRocks Operator deployment documentation
  docs/en/deployment/sr_operator.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#63732 [BugFix] Disable simplifying case-when with complex funtions to avoid time-consuming and tedious predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/SimplifyCaseWhenPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithCaseWhenTest.java
Labels: 3.3, 3.4, 3.5, 4.0
