Repository StarRocks/starrocks, pull requests merged in 2025-08, with the labels that each got.

#61501 [Doc] Revert Documenting configurations for FE nodes' HTTPS server
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation

#61505 [UT] Avoid timeout for some sql tests (backport #61082)
  test/sql/test_scan/test_pushdown_or_predicate/R/test_parse_and_rewrite_or_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_parse_and_rewrite_or_predicate
Labels: automerge

#60708 [Enhancement] Add config option to skip removing giant core dump and check actual disk usage
  docker/dockerfiles/be/upload_coredump.sh
Labels: 3.5

#61508 [UT] Add @slow @sequential to test_max_min_by_not_filter_nulls_with_nulls
  test/sql/test_max_min_by_not_filter_nulls_with_nulls/R/test_max_min_by_not_filter_nulls_with_nulls
  test/sql/test_max_min_by_not_filter_nulls_with_nulls/T/test_max_min_by_not_filter_nulls_with_nulls
Labels: 3.3, 3.4, 3.5

#61520 [Doc]Update deployment_prerequisites.md
  docs/en/deployment/deployment_prerequisites.md
  docs/ja/deployment/deployment_prerequisites.md
  docs/zh/deployment/deployment_prerequisites.md
Labels: documentation, 3.3, 3.4, 3.5

#61526 [Doc] JDK Notes in 3.3 Release Notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#61424 [Enhancement]scan range schedule for bucket-aware execution
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/ScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/BucketAwareBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/ColocatedBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionFragment.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergConnectorScanRangeSourceTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TableTestBase.java
  fe/fe-core/src/test/java/com/starrocks/lake/qe/scheduler/DefaultSharedDataWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/BucketAwareBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ColocatedBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/CoordinatorTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW

#61524 [BugFix] Fix UAF in local-partition preagg
  be/src/exec/pipeline/sort/local_partition_topn_context.h
Labels: 3.4, 3.5

#61475 [Enhancement] Update balance statistic during balancing
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndex.java
  fe/fe-core/src/main/java/com/starrocks/clone/BackendLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/ClusterLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/Rebalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ClusterLoadStatisticProcDir.java
  fe/fe-core/src/test/java/com/starrocks/clone/DiskAndTabletLoadReBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
Labels: 3.5

#61532 [BugFix] don't try to build MFV versions for the instructions turned off
  be/src/simd/multi_version.h
Labels: 3.4, 3.5

#61540 [BugFix] fix file-prefix-map, remove the build_XXX part
  be/CMakeLists.txt
Labels: 3.3, 3.4, 3.5

#61542 [BugFix] Fix python client type reflection error
  contrib/starrocks-python-client/starrocks/dialect.py
Labels: 3.3, 3.4, 3.5

#61553 [UT] Add label(slow) to test case: test_array_distinct
  test/sql/test_array_fn/R/test_array_distinct
  test/sql/test_array_fn/T/test_array_distinct
Labels: 3.4, 3.5

#60944 [Feature] Implement cross publish version in FE for tablet splitting and merging
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/DynamicTablet.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/DynamicTabletJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/IdenticalTablet.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/MergingTablet.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/PublishTabletsInfo.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/SplittingTablet.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/test/java/com/starrocks/alter/dynamictablet/PublishTabletsInfoTest.java
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#61563 [BugFix] Fix case when simplification causing outer-join or grouping set results to be incorrect
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/SimplifyCaseWhenPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
Labels: 3.3, 3.4, 3.5

#61513 [Doc] Add doc for adaptive materialized view refresh
  docs/en/sql-reference/sql-statements/materialized_view/ALTER_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/en/using_starrocks/async_mv/use_cases/data_modeling_with_materialized_views.md
  docs/ja/sql-reference/sql-statements/materialized_view/ALTER_MATERIALIZED_VIEW.md
  docs/ja/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/ja/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/ja/using_starrocks/async_mv/use_cases/data_modeling_with_materialized_views.md
  docs/zh/sql-reference/sql-statements/materialized_view/ALTER_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/zh/using_starrocks/async_mv/use_cases/data_modeling_with_materialized_views.md
Labels: documentation

#61535 [Feature] Add format_bytes function for human-readable byte formatting
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/CMakeLists.txt
  be/test/exprs/string_fn_format_bytes_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  gensrc/script/functions.py
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: behavior_changed

#60667 [BugFix] Fix ldap not catch PartialResultException bug
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPGroupProvider.java
Labels: 3.5

#61600 [UT] Fix unstable case for dict_mapping in JIT sql-test
  test/sql/test_jit/R/test_jit_expr
  test/sql/test_jit/T/test_jit_expr
Labels: 3.3, 3.4, 3.5

#61562 [BugFix] fix query hang because of incorrect scan range delivery
  be/src/exec/pipeline/fragment_executor.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/AllAtOnceExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
Labels: 3.3, 3.4, 3.5

#61593 [BugFix] Fix the error in calculating the memory size of the low cardinality dictionary.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  test/sql/test_low_cardinality/R/test_low_cardinality_size_threshold
  test/sql/test_low_cardinality/T/test_low_cardinality_size_threshold
Labels: 3.5

#61580 [BugFix] Fix maxmin_by window function primitive type output cause unmatched length chunk
  be/src/exprs/agg/maxmin_by.h
  test/sql/test_max_min_by_not_filter_nulls_without_nulls/R/test_max_min_by_not_filter_nulls_without_nulls
  test/sql/test_window_function/R/test_minmax_by_window_function
  test/sql/test_window_function/T/test_minmax_by_window_function
Labels: 3.4, 3.5

#61601 [BugFix] avoid two-stage distinct aggregation when no grouping key in the query
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
Labels: 3.5

#61488 [Enhancement] Sort while constructing the mapping from source file rowids to update file rowids when partial update
  be/src/storage/lake/column_mode_partial_update_handler.cpp
  be/src/storage/rowset_column_update_state.cpp
  be/src/storage/rowset_column_update_state.h
  be/test/storage/rowset_column_update_state_test.cpp
  test/common/data/stream_load/sr_partial_update_6.csv
  test/common/data/stream_load/sr_partial_update_7.csv
  test/sql/test_partial_update_column_mode/R/test_partial_update_verify_order
  test/sql/test_partial_update_column_mode/T/test_partial_update_verify_order
Labels: 3.3, 3.4, 3.5

#61570 [Enhancement] Show disk balance statistic
  fe/fe-core/src/main/java/com/starrocks/clone/BackendLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/BalanceStat.java
  fe/fe-core/src/main/java/com/starrocks/clone/ClusterLoadStatistic.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ClusterBalanceProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ClusterLoadStatByMedium.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ClusterLoadStatisticProcDir.java
  fe/fe-core/src/test/java/com/starrocks/clone/ClusterLoadStatisticsTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ClusterLoadStatByMediumTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ClusterLoadStatisticProcDirTest.java
Labels: behavior_changed, 3.5

#61633 [Doc]Update CREATE_ANALYZE.md
  docs/en/sql-reference/sql-statements/cbo_stats/CREATE_ANALYZE.md
  docs/ja/sql-reference/sql-statements/cbo_stats/CREATE_ANALYZE.md
  docs/zh/sql-reference/sql-statements/cbo_stats/CREATE_ANALYZE.md
Labels: documentation

#61623 [Doc] Update best practice overview
  docs/en/best_practices/overview.md
  docs/ja/best_practices/overview.md
  docs/zh/best_practices/overview.md
Labels: documentation, 3.3, 3.4, 3.5

#61573 [Doc] add parameter "enable_get_stats_from_external_metadata" doc
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/en/sql-reference/System_variable.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.4, 3.5

#61394 [Feature] implement json_remove
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/exprs/jsonpath.cpp
  be/src/exprs/jsonpath.h
  be/test/exprs/json_functions_test.cpp
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_remove.md
  docs/en/sql-reference/sql-functions/json-functions/overview-of-json-functions-and-operators.md
  docs/ja/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_remove.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_remove.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  gensrc/script/functions.py
  test/sql/test_json/R/test_json_remove
  test/sql/test_json/T/test_json_remove
Labels: documentation, SKIP CASE

#61685 [Enhancement] upgrade staros to v3.5-rc3
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/pom.xml
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.5

#61694 [UT] add @slow to sql test test_parameterized
  test/sql/test_feedback/R/test_parameterized
  test/sql/test_feedback/T/test_parameterized
Labels: 3.5

#61671 [BugFix] Add warning logs for statistic table state check failures
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticAutoCollector.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.3, 3.4, 3.5

#61539 [Enhancement] Add prepared_timeout configuration for transaction stream load
  be/src/http/http_common.h
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/runtime/stream_load/transaction_mgr.cpp
  be/test/http/transaction_stream_load_test.cpp
  docs/en/administration/management/FE_configuration.md
  docs/en/loading/Stream_Load_transaction_interface.md
  docs/en/sql-reference/sql-statements/loading_unloading/SHOW_TRANSACTION.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/loading/Stream_Load_transaction_interface.md
  docs/ja/sql-reference/sql-statements/loading_unloading/SHOW_TRANSACTION.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/loading/Stream_Load_transaction_interface.md
  docs/zh/sql-reference/sql-statements/loading_unloading/SHOW_TRANSACTION.md
  fe/fe-core/src/main/java/com/starrocks/common/proc/TransProcDir.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/BypassWriteTransactionHandler.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionOperationParams.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowTransactionStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionStateTest.java
  gensrc/thrift/FrontendService.thrift
  test/lib/sr_sql_lib.py
  test/sql/test_stream_load/R/test_prepared_timeout
  test/sql/test_stream_load/T/test_prepared_timeout
Labels: documentation, META-REVIEW, PROTO-REVIEW, 3.5

#61684 [BugFix]Fix java.time.LocalDate type check.
  be/src/types/checker/type_checker.cpp
  be/src/types/checker/type_checker.h
  be/src/types/type_checker_manager.cpp
  be/test/types/type_checker_test.cpp
Labels: 3.4, 3.5

#61578 [Enhancement] Add show balance statistic proc
  fe/fe-core/src/main/java/com/starrocks/clone/BalanceStat.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BalanceStatProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ClusterBalanceProcDir.java
  fe/fe-core/src/test/java/com/starrocks/clone/BalanceStatTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BalanceStatProcNodeTest.java
Labels: behavior_changed, 3.5

#61732 [Doc]Update ranger_plugin.md
  docs/en/administration/user_privs/authorization/ranger_plugin.md
  docs/ja/administration/user_privs/authorization/ranger_plugin.md
  docs/zh/administration/user_privs/authorization/ranger_plugin.md
Labels: documentation, 3.3, 3.4, 3.5

#61750 [UT] skip caching mv plan in the background
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
Labels: 3.5

#61579 [Doc] Docs for DECIMAL256
  docs/en/sql-reference/data-types/numeric/DECIMAL.md
  docs/en/sql-reference/data-types/semi_structured/Array.md
  docs/ja/sql-reference/data-types/numeric/DECIMAL.md
  docs/ja/sql-reference/data-types/semi_structured/Array.md
  docs/zh/sql-reference/data-types/numeric/DECIMAL.md
  docs/zh/sql-reference/data-types/semi_structured/Array.md
Labels: documentation

#61724 [BugFix] support configure starcache inline cache count limit
  be/src/cache/local_cache_engine.h
  be/src/cache/lrucache_engine.cpp
  be/src/cache/lrucache_engine.h
  be/src/cache/starcache_engine.cpp
  be/src/cache/starcache_engine.h
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/test/cache/block_cache/test_cache_utils.h
  be/test/cache/lrucache_engine_test.cpp
  be/test/cache/starcache_engine_test.cpp
  be/test/http/action/update_config_action_test.cpp
Labels: 3.4, 3.5

#61446 [Doc] Table-level Flat JSON
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/en/using_starrocks/Flat_json.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/ja/using_starrocks/Flat_json.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/using_starrocks/Flat_json.md
Labels: documentation

#61326 [Feature] support creating iceberg table with sort order.
  fe/fe-core/src/main/java/com/starrocks/analysis/OrderByElement.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/glue/IcebergGlueCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hadoop/IcebergHadoopCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/hive/IcebergHiveCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/jdbc/IcebergJdbcCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateTemporaryTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/OptimizeClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergJdbcCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergRESTCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AlterTableClauseVisitorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/CreateTableStmtTest.java
Labels: SKIP CASE

#61605 [Enhancement] support write starlet file with tag
  be/src/common/config.h
  be/src/fs/fs_starlet.cpp
  be/test/fs/fs_starlet_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.5, 4.0

#61782 [BugFix] Fix NPE in TaskRunScheduler.getAllRunnableTaskCount
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunFIFOQueue.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: 3.4, 3.5

#61499 [Doc] Logging detail
  docs/docusaurus/sidebars.json
  docs/en/administration/management/logs.md
  docs/ja/administration/management/logs.md
  docs/zh/administration/management/logs.md
Labels: documentation, 3.5

#61796 [BugFix] starrocks-python-client: Correct DDL generation for ARRAY type in SQLAlchemy dialect
  contrib/starrocks-python-client/starrocks/datatype.py
  contrib/starrocks-python-client/starrocks/dialect.py
Labels: 3.4, 3.5, 4.0

#61403 [Enhancement] Implement function json_contains
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/util/json.cpp
  be/src/util/json.h
  be/test/exprs/json_functions_test.cpp
  docs/en/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_contains.md
  docs/ja/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_contains.md
  docs/zh/sql-reference/sql-functions/json-functions/json-query-and-processing-functions/json_contains.md
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  gensrc/script/functions.py
  test/sql/test_json/R/test_json_contains
  test/sql/test_json/T/test_json_contains
Labels: documentation, SKIP CASE, 4.0

#61736 [Enhancement] Add colocate group balance statistic
  fe/fe-core/src/main/java/com/starrocks/clone/BalanceStat.java
  fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/test/java/com/starrocks/clone/BalanceStatTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BalanceStatProcNodeTest.java
Labels: 3.5, 4.0

#61858 [BugFix] fix min/max optimization on iceberg on partition columns
  be/src/exec/hdfs_scanner.cpp
  test/sql/test_iceberg/R/test_iceberg_min_max_opt
  test/sql/test_iceberg/T/test_iceberg_min_max_opt
Labels: 3.5, 4.0

#61859 [BugFix] Fix the problem with the number of rebuild file counted.
  be/src/storage/lake/lake_persistent_index.cpp
Labels: 3.4, 3.5, 4.0

#61880 [UT] Fix ShowDataDistributionStmtTest
  fe/fe-core/src/main/java/com/starrocks/catalog/MetadataViewer.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ShowDataDistributionStmtTest.java
Labels: 3.5, 4.0

#61881 [BugFix] CBO Table Pruning misses other predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/pruner/CboTablePruneRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/TablePruningTest.java
Labels: 3.4, 3.5, 4.0

#61851 [Enhancement] revise iceberg rewrite data
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergAlterTableExecutor.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRewriteDataJob.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergTableOperation.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/IcebergRewriteStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
Labels: 4.0

#61899 [BugFix] avoid hold tablet shard lock to get compaction score
  be/src/storage/tablet_manager.cpp
Labels: 3.4, 3.5, 4.0

#61787 [Enhancement] enhance drop partition log information
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: 3.5, 4.0

#61959 [Enhancement] Add logs for the reason why tablet cannot be repaired
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
Labels: 3.5, 4.0

#61923 [Doc] add table name insensitive doc
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/System_limit.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/sql-reference/System_limit.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/System_limit.md
Labels: documentation, 4.0

#61781 [Enhancement] support encode_sort_key function
  be/src/column/datum_convert.cpp
  be/src/exprs/utility_functions.cpp
  be/src/exprs/utility_functions.h
  be/src/storage/key_coder.cpp
  be/src/storage/key_coder.h
  be/src/storage/primary_key_encoder.cpp
  be/src/storage/primary_key_encoder.h
  be/src/storage/row_store_encoder_simple.cpp
  be/src/storage/row_store_encoder_util.h
  be/src/storage/rowset/zone_map_index.cpp
  be/test/exprs/utility_functions_test.cpp
  be/test/storage/rowset/zone_map_index_test.cpp
  be/test/storage/tablet_schema_helper.h
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Type.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  gensrc/script/functions.py
  test/sql/test_make_sort_key/R/test_make_sort_key_json
  test/sql/test_make_sort_key/T/test_make_sort_key_json
Labels: 4.0

#61921 [Doc] add new fe config for controlling array ndv colleciton to cbo section
  docs/en/administration/management/FE_configuration.md
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/using_starrocks/Cost_based_optimizer.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 4.0

#61898 [Doc] Add Mapping for Packages
  docs/en/integrations/loading_tools/SMT.md
  docs/ja/integrations/loading_tools/SMT.md
  docs/zh/integrations/loading_tools/SMT.md
Labels: documentation, 3.4, 3.5, 4.0

#61971 [UT] move test_groupby_array_agg to another test file
  test/sql/test_agg/R/test_groupby_array
  test/sql/test_agg/R/test_serialize_key_agg
  test/sql/test_agg/T/test_groupby_array
  test/sql/test_agg/T/test_serialize_key_agg
Labels: 3.5, 4.0

#62041 [BugFix][CVE] CVE-2025-55163 fix, bump io.netty version
  fe/build.gradle.kts
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/src/broker-core/pom.xml
  fs_brokers/apache_hdfs_broker/src/pom.xml
  java-extensions/pom.xml
Labels: 3.3, 3.4, 3.5, 4.0

#61963 [Enhancement] Introduce a connector partition chunk writer to support spilling chunk data for iceberg table sink.
  be/src/common/config.h
  be/src/connector/CMakeLists.txt
  be/src/connector/async_flush_stream_poller.cpp
  be/src/connector/async_flush_stream_poller.h
  be/src/connector/connector_chunk_sink.cpp
  be/src/connector/connector_chunk_sink.h
  be/src/connector/connector_sink_executor.cpp
  be/src/connector/connector_sink_executor.h
  be/src/connector/file_chunk_sink.cpp
  be/src/connector/file_chunk_sink.h
  be/src/connector/hive_chunk_sink.cpp
  be/src/connector/hive_chunk_sink.h
  be/src/connector/iceberg_chunk_sink.cpp
  be/src/connector/iceberg_chunk_sink.h
  be/src/connector/partition_chunk_writer.cpp
  be/src/connector/partition_chunk_writer.h
  be/src/connector/sink_memory_manager.cpp
  be/src/connector/sink_memory_manager.h
  be/src/connector/utils.h
  be/src/exec/pipeline/sink/connector_sink_operator.cpp
  be/src/formats/csv/csv_file_writer.cpp
  be/src/formats/csv/csv_file_writer.h
  be/src/formats/file_writer.h
  be/src/formats/orc/orc_file_writer.cpp
  be/src/formats/orc/orc_file_writer.h
  be/src/formats/parquet/parquet_file_writer.cpp
  be/src/formats/parquet/parquet_file_writer.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/iceberg_table_sink.cpp
  be/test/CMakeLists.txt
  be/test/connector_sink/file_chunk_sink_test.cpp
  be/test/connector_sink/hive_chunk_sink_test.cpp
  be/test/connector_sink/iceberg_chunk_sink_test.cpp
  be/test/connector_sink/partition_chunk_writer_test.cpp
  gensrc/thrift/DataSinks.thrift
  test/sql/test_iceberg/R/test_iceberg_remove_orphan_files
Labels: PROTO-REVIEW, 4.0

#62084 [Doc] Update the default value of cbo_eq_base_type.
  docs/en/sql-reference/System_variable.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 4.0

#62046 [BugFix] Fix error base version in schema change job with lake rollup
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  test/sql/test_rollup/R/test_lake_rollup
  test/sql/test_rollup/T/test_lake_rollup
Labels: 3.4, 3.5, 4.0

#61381 [BugFix] fix insert into select's audit log
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.3, 3.4, 3.5

#62074 [BugFix] Fix missing clone copy size and duration
  be/src/agent/agent_task.cpp
  be/src/storage/task/engine_clone_task.cpp
  be/src/storage/task/engine_clone_task.h
Labels: 3.4, 3.5, 4.0

#62001 [BugFix] fix json global dict with heterogeneous schema
  be/src/storage/meta_reader.cpp
  test/sql/test_semi/R/test_flat_json_dict
Labels: 4.0

#62113 [Doc] Move downgrade notes to top
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#62128 [BugFix][CVE-2025-52999] upgrade jackson version to 2.15.2
  fs_brokers/apache_hdfs_broker/src/pom.xml
Labels: 3.3, 3.4

#62138 [UT] Fix the test case: test_files_sink
  test/sql/test_sink/R/test_files_sink
Labels: 4.0

#62157 [UT] fix unstable case
  test/sql/test_iceberg/R/test_iceberg_bucket_aware_execution
  test/sql/test_iceberg/T/test_iceberg_bucket_aware_execution
Labels: 4.0

#62161 [BugFix] Fix FE restart problem when enable query queue v2
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotTracker.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/DefaultSlotSelectionStrategyTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2Test.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/SlotTrackerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/warehouse/WarehouseMetricEntityTest.java
  fe/fe-core/src/test/java/com/starrocks/service/InformationSchemaDataSourceTest.java
Labels: 3.5, 4.0

#62135 [Enhancement]support config bucket assign mode for bucket-aware execution
  fe/fe-core/src/main/java/com/starrocks/qe/BucketAwareBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariableConstants.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java
  fe/fe-core/src/test/java/com/starrocks/qe/BucketAwareBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/SessionVariableTest.java
Labels: 4.0

#62163 [Enhancement] Refactor balance type
  fe/fe-core/src/main/java/com/starrocks/clone/BalanceStat.java
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/test/java/com/starrocks/clone/BalanceStatTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/DiskAndTabletLoadReBalancerTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/BalanceStatProcNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ClusterLoadStatByMediumTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/ClusterLoadStatisticProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/IndicesProcDirTest.java
Labels: 3.5, 4.0

#62123 [Enhancement] Improve the iceberg table sink memory and small file problems by implementing a partition based global shuffle
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
Labels: 4.0

#62195 [Enhancement] update persistent index size statistic when do major compaction
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/storage/primary_index.cpp
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
Labels: 3.4, 3.5, 4.0

#62211 [Doc] 3.5.4 Release Notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#62198 [BugFix] Fix view based mv rewrite bug
  docs/en/sql-reference/System_variable.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalViewScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayWithMVFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/view_based_rewrite1.json
  fe/fe-core/src/test/resources/sql/query_dump/materialized-view/view_based_rewrite2.json
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62096 [Enhancement] Optimize the iceberg sink local sorting based on the spill partition writer
  be/src/column/schema.cpp
  be/src/column/schema.h
  be/src/connector/partition_chunk_writer.cpp
  be/src/connector/sink_memory_manager.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/iceberg_table_sink.cpp
  be/src/storage/merge_iterator.cpp
  be/test/CMakeLists.txt
  be/test/connector_sink/iceberg_table_sink_test.cpp
  be/test/connector_sink/partition_chunk_writer_test.cpp
  be/test/connector_sink/sink_memory_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/IcebergScanNodeTest.java
  gensrc/thrift/Descriptors.thrift
  test/sql/test_iceberg/T/test_iceberg_remove_orphan_files
Labels: PROTO-REVIEW

#61930 [BugFix] support lazy delta column compact for size tiered compaction in pk table to reduce cost
  be/src/storage/tablet_updates.cpp
  be/test/storage/rowset_column_partial_update_test.cpp
Labels: 3.5, 4.0

#62165 [Enhancement] Optimize append_selective for binary column
  be/src/column/binary_column.cpp
  be/src/column/chunk.cpp
  be/src/column/fixed_length_column_base.cpp
  be/src/gutil/strings/fastmem.h
  be/src/util/runtime_profile.h
  be/test/column/binary_column_test.cpp
Labels: 4.0

#62223 [Enhancement] fix profile when deploying scan ranges in background
  fe/fe-core/src/main/java/com/starrocks/common/profile/TimeWatcher.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/TracerImpl.java
  fe/fe-core/src/main/java/com/starrocks/connector/delta/DeltaConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/AllAtOnceExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionSchedule.java
Labels: 4.0

#62170 [Doc] Add balance statistics doc
  docs/en/administration/management/resource_management/Replica.md
  docs/en/sql-reference/information_schema/partitions_meta.md
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/ja/administration/management/resource_management/Replica.md
  docs/ja/sql-reference/information_schema/partitions_meta.md
  docs/ja/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/zh/administration/management/resource_management/Replica.md
  docs/zh/sql-reference/information_schema/partitions_meta.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
Labels: documentation, 3.5, 4.0

#62180 [Doc] Update fe tablet schdules system table doc
  docs/en/sql-reference/information_schema/fe_tablet_schedules.md
  docs/ja/sql-reference/information_schema/fe_tablet_schedules.md
  docs/zh/sql-reference/information_schema/fe_tablet_schedules.md
Labels: documentation, 4.0

#62269 [Doc] Fix snippet in deployment
  docs/ja/_assets/commonMarkdown/sharedDataUse.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62238 [BugFix] Add lock when get max version from tablet in replication txn manager
  be/src/storage/replication_txn_manager.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#62275 [BugFix]Fix the error of using GTID to handle dirty tablet metadata
  be/src/storage/lake/transactions.cpp
Labels: 3.4, 3.5, 4.0

#62279 [BugFix] avoid BE crash when LakePersistentIndex init fail
  be/src/storage/lake/lake_persistent_index.cpp
Labels: 3.3, 3.4, 3.5, 4.0

#62299 [Doc] add pinyin term
  docs/zh/administration/management/monitoring/Monitor_and_Alert.md
  docs/zh/sql-reference/sql-functions/array-functions/array_contains.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62242 [Doc] correct parameter for enabling JWT auth
  docs/en/administration/user_privs/authentication/security_integration.md
  docs/ja/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/authentication/security_integration.md
Labels: documentation, 3.5, 4.0

#62225 [Enhancement] Rewrite MIN(f(col)) to f(MIN(col)) for Monotonic Functions
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMinMaxByMonotonicFunctionRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnMinMaxMgr.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/MinMaxMonotonicRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
Labels: 4.0

#62298 [UT] Fix join test timeout
  be/test/column/binary_column_test.cpp
  test/sql/test_join/R/test_join_linear_chained
  test/sql/test_join/R/test_join_one_key
  test/sql/test_join/R/test_join_range_direct_mapping
  test/sql/test_join/T/test_join_linear_chained
  test/sql/test_join/T/test_join_one_key
  test/sql/test_join/T/test_join_range_direct_mapping
Labels: 4.0

#62291 [Enhancement] add a session variable to deploy scan ranges back/foreground
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Coordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/AllAtOnceExecutionSchedule.java
Labels: 4.0

#62323 [Doc] enable_ssl Property in Storage Volume
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
  docs/ja/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
  docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62308 [Refactor] Replace OriginStatement with OriginStatementInfo across multiple files
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/Tracers.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/http/action/SystemAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ShowProcAction.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/FilePipeSource.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/persist/AlterRoutineLoadJobOperationLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OriginStatementInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/DataCacheSelectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/service/arrow/flight/sql/ArrowFlightSqlServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DataCacheSelectStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/OriginStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/QueryStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/StatementBase.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/SqlParser.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HyperStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/MultiColumnHyperStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/load/RoutineLoadDescTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/LeaderOpExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/service/arrow/flight/sql/ArrowFlightSqlServiceImplTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteMetricsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TracerMVTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TracerTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/TestWithFeService.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: META-REVIEW

#62321 [BugFix] Fix possible NPE in alter table
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeHandlerWithMVTest.java
  test/sql/test_alter_table/R/test_alter_table_with_mv
  test/sql/test_alter_table/T/test_alter_table_with_mv
Labels: 3.3, 3.4, 3.5, 4.0

#62097 [Enhancement] enable flat json by default
  be/src/common/config.h
  be/src/connector/lake_connector.cpp
  be/src/exec/olap_meta_scanner.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/tablet_schema.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: behavior_changed, 4.0

#61966 [Enhancement] revise cache mem size limit for iceberg
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalogProperties.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/StarRocksIcebergTableScanContext.java
  fe/fe-core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestGroup.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestReader.java
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
Labels: 3.5, 4.0

#61965 [Enhancement] create adaptive zonemap index for strings
  be/src/common/config.h
  be/src/storage/rowset/column_writer.cpp
  be/src/storage/rowset/column_writer.h
  be/src/storage/rowset/zone_map_index.cpp
  be/src/storage/rowset/zone_map_index.h
  be/test/connector_sink/partition_chunk_writer_test.cpp
  be/test/storage/rowset/zone_map_index_test.cpp
Labels: 4.0

#62293 [Enhancement] Add more failure reasons for tablet clone
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
Labels: 3.5, 4.0

#62376 [BugFix] fix the execState of multiple fe
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryStatisticsInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryStatisticsItem.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotManager.java
Labels: 4.0

#62292 [BugFix] fix table function use lowcarditinay error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeRewriter.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
Labels: 3.3, 3.4, 3.5, 4.0

#62363 [BugFix] fix combine txnlog vacuum issue when delete tablets
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
Labels: 4.0

#62378 [BugFix] use fe id instead to replace the fe name
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/PredicateColumnsStorage.java
  fe/fe-core/src/test/java/com/starrocks/statistic/columns/PredicateColumnsStorageTest.java
Labels: 3.5, 4.0

#62367 [Doc] Document session variables and update Flat_json.md
  docs/en/sql-reference/System_variable.md
  docs/en/using_starrocks/Flat_json.md
  docs/ja/sql-reference/System_variable.md
  docs/ja/using_starrocks/Flat_json.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/using_starrocks/Flat_json.md
Labels: documentation, 4.0

#62369 [BugFix] fix the overlap check of zonemap
  be/src/storage/rowset/zone_map_index.cpp
Labels: 4.0

#62413 [UT] Fix ut append_chunk_safe
  be/test/column/chunk_test.cpp
Labels: 4.0

#61650 [Feature] Support automatic creating split tablet job
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/DynamicTabletUtils.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SplitTabletClause.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTableTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/dynamictablet/AutomaticDynamicTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/dynamictablet/DynamicTabletJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/dynamictablet/SplitTabletJobFactoryTest.java
Labels: SKIP CASE

#61664 [BugFix]Fix publishTask may blocked by TransactionState of REPLICATION
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.3, 3.4, 3.5

#62404 [Enhancement] improve lake information schema performance
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.4, 3.5, 4.0

#62419 [Doc] Updated documentation to align with Auditloader 5.0
  docs/en/administration/management/audit_loader.md
  docs/ja/administration/management/audit_loader.md
  docs/zh/administration/management/audit_loader.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62410 [BugFix] Fix UAF for BinaryColumn::append_selective
  be/src/column/binary_column.cpp
Labels: 4.0

#62396 [BugFix] fix the privilege issue of refresh mv
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_create_mv_with_user
  test/sql/test_materialized_view/T/test_create_mv_with_user
Labels: 3.3, 3.4, 3.5, 4.0

#62121 [Enhancement] reduce unnecessary storage related logs
  be/src/agent/agent_server.cpp
  be/src/agent/agent_task.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/runtime/lake_snapshot_loader.cpp
  be/src/runtime/snapshot_loader.cpp
  be/src/storage/compaction_manager.cpp
  be/src/storage/delete_handler.cpp
  be/src/storage/lake/spark_load.cpp
  be/src/storage/push_handler.cpp
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_meta.cpp
  be/src/storage/task/engine_alter_tablet_task.cpp
  be/src/storage/task/engine_batch_load_task.cpp
  fe/fe-core/src/main/java/com/starrocks/consistency/CheckConsistencyJob.java
  fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/task/PushTask.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TxnStateCallbackFactory.java
Labels: 3.5, 4.0

#62339 [Refactor] Replace logEdit with logJsonObject for improved logging consistency
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/io/Writable.java
  fe/fe-core/src/main/java/com/starrocks/consistency/CheckConsistencyJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMultiStmtTask.java
  fe/fe-core/src/main/java/com/starrocks/persist/ConsistencyCheckInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/DropBrokerLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/DropRepositoryLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogFileInputStream.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogFileOutputStream.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogInputStream.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogOutputStream.java
  fe/fe-core/src/main/java/com/starrocks/persist/EraseDbLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/ErasePartitionLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/NextIdLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/bdb/BDBToolTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/ChangeMaterializedViewRefreshSchemeLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/EditLogDeserializerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/FsBrokerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/UpdateHistoricalNodeLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/WarehouseInternalOpLogTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/mv/MVEpochTest.java
  fe/fe-core/src/test/java/com/starrocks/system/BackendHbResponseTest.java
Labels: META-REVIEW

#62480 [BugFix] Fix table with gin index use replicated_storage
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
Labels: 4.0

#62253 [Enhancement] Fast schema evolution supports adding key columns for shared-data
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeData.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJobTest.java
Labels: 4.0

#62478 [BugFix] Fix compile memcpy_inlined_overflow16 on ARM
  be/src/gutil/strings/fastmem.h
  be/src/util/crc32c_sse_simd.cpp
Labels: 4.0

#62139 [Enhancement] support expr reuse in outer join where predicates
  be/src/exec/cross_join_node.cpp
  be/src/exec/cross_join_node.h
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/pipeline/hashjoin/hash_joiner_factory.cpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.h
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/spillable_nljoin_probe_operator.h
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/storage/chunk_helper.cpp
  be/src/storage/chunk_helper.h
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/JoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/NestLoopJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/DictMappingOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/exprreuse/ScalarOperatorsReuseRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/planner/PushDownSubfieldHashJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/JoinPredicateExprReuseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_join/R/test_predicate_expr_reuse
  test/sql/test_join/T/test_predicate_expr_reuse
Labels: PROTO-REVIEW

#62207 [Enhancement] fix null_or_empty can support array type
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  be/test/exprs/array_functions_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/null_or_empty.md
  docs/ja/sql-reference/sql-functions/string-functions/null_or_empty.md
  docs/zh/sql-reference/sql-functions/string-functions/null_or_empty.md
  fe/fe-core/src/test/java/com/starrocks/catalog/FunctionSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeArrayTest.java
  gensrc/script/functions.py
  test/sql/test_array/R/test_array
  test/sql/test_array/T/test_array
Labels: documentation, 3.5, 4.0

#62507 [Enhancement] revise cache mem size limit for iceberg (backport #61966)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/CachingIcebergCatalog.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalogProperties.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/StarRocksIcebergTableScanContext.java
  fe/fe-core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestGroup.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestReader.java
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
Labels: automerge

#62421 [Enhancement] Add clone metrics in frontend
  fe/fe-core/src/main/java/com/starrocks/clone/BalanceStat.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerStatTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricsTest.java
Labels: 3.5, 4.0

#62517 [Doc] Categorize enable_auth_check
  docs/en/_assets/commonMarkdown/Edition_Specific_FE_Item.md
  docs/en/administration/management/FE_configuration.md
  docs/ja/_assets/commonMarkdown/Edition_Specific_FE_Item.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/_assets/commonMarkdown/Edition_Specific_FE_Item.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5, 4.0

#62512 [BugFix] Fix two minus signs when the result is INT256_MIN
  be/src/runtime/decimalv3.h
  test/sql/test_decimal/R/test_decimal256_arithmetic_overflow
Labels: 4.0
