Repository StarRocks/starrocks, pull requests merged in 2025-05, with the labels that each got.

#58650 [Doc] broken link
  docs/ja/table_design/data_distribution/expression_partitioning.md
Labels: documentation

#58649 [BugFix] Fix show_be_version command not work
  bin/show_be_version.sh
  bin/start_backend.sh
Labels: 3.4, 3.5

#58656 [Doc] Sidebars for Japanese
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58653 [UT] eliminate NPE in UT MockCluster
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
Labels: 3.3, 3.4, 3.5

#58664 [Doc] Update current.json
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58666 [Doc] Update current.json
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
  docs/ja/_assets.old/commonMarkdown/BE_config_method.md
  docs/ja/_assets.old/commonMarkdown/BE_dynamic_note.md
  docs/ja/_assets.old/commonMarkdown/FE_config_method.md
  docs/ja/_assets.old/commonMarkdown/FE_config_note.md
  docs/ja/_assets.old/commonMarkdown/RoutineLoadPrivNote.md
  docs/ja/_assets.old/commonMarkdown/StaticBE_config_note.md
  docs/ja/_assets.old/commonMarkdown/StaticFE_config_note.md
  docs/ja/_assets.old/commonMarkdown/brokerDataFlow.md
  docs/ja/_assets.old/commonMarkdown/datalakeIntro.md
  docs/ja/_assets.old/commonMarkdown/dateTimeTip.mdx
  docs/ja/_assets.old/commonMarkdown/insertPrivNote.md
  docs/ja/_assets.old/commonMarkdown/loadMethodIntro.md
  docs/ja/_assets.old/commonMarkdown/multi-service-access.mdx
  docs/ja/_assets.old/commonMarkdown/pipeAdvantages.md
  docs/ja/_assets.old/commonMarkdown/quickstart-iceberg-tip.mdx
  docs/ja/_assets.old/commonMarkdown/quickstart-overview-tip.mdx
  docs/ja/_assets.old/commonMarkdown/quickstart-routine-load-tip.mdx
  docs/ja/_assets.old/commonMarkdown/quickstart-shared-data.mdx
  docs/ja/_assets.old/commonMarkdown/quickstart-shared-nothing-tip.mdx
  docs/ja/_assets.old/commonMarkdown/replicanum.md
  docs/ja/_assets.old/commonMarkdown/sharedDataCNconf.md
  docs/ja/_assets.old/commonMarkdown/sharedDataIntro.md
  docs/ja/_assets.old/commonMarkdown/sharedDataUse.md
  docs/ja/_assets.old/commonMarkdown/sharedDataUseIntro.md
  docs/ja/_assets.old/commonMarkdown/userManagementPriv.md
  docs/ja/_assets.old/commonMarkdown/userPrivilegeCase.md
  docs/ja/_assets.old/deployment/_OperatorPrereqs.mdx
  docs/ja/_assets.old/quick-start/_DDL.mdx
  docs/ja/_assets.old/quick-start/_SQL.mdx
  docs/ja/_assets.old/quick-start/_clientsAllin1.mdx
  docs/ja/_assets.old/quick-start/_clientsCompose.mdx
  docs/ja/_assets.old/quick-start/_curl.mdx
  docs/translation/README.md
Labels: documentation

#58665 [Doc] Update current.json
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58667 [Doc] Update current.json
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58668 [Doc] Update current.json
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
  docs/translation/README.md
Labels: documentation

#58593 [BugFix] Fix inconsistent delvector/dcg cache for migration
  be/src/storage/tablet_updates.cpp
  be/src/storage/task/engine_storage_migration_task.cpp
  be/src/storage/update_manager.cpp
  be/src/storage/update_manager.h
  be/test/storage/update_manager_test.cpp
Labels: 3.2, 3.3, 3.4, 3.5

#58690 [Doc]Update feature-support-data-lake-analytics.md
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/ja/data_source/feature-support-data-lake-analytics.md
  docs/zh/data_source/feature-support-data-lake-analytics.md
Labels: documentation, 3.4, 3.5

#58289 [Feature] Support aggregate publish for shared data
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/lake/metacache.cpp
  be/src/storage/lake/metacache.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/transactions.h
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/txn_log_applier.h
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  be/test/storage/lake/replication_txn_manager_test.cpp
  be/test/storage/lake/schema_change_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeAggregator.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceWithMetrics.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakeAggregatePublishTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW

#58697 [BugFix] Fix ValueWindowFunction bug for object types
  be/src/exprs/agg/window.h
  test/sql/test_window_function/R/test_window_functions_with_complex_types
  test/sql/test_window_function/T/test_window_functions_with_complex_types
Labels: 3.3, 3.4, 3.5

#58706 [Doc] Revamp Iceberg quick start guide
  docs/en/_assets/quick-start/MinIO-Iceberg-data.png
  docs/en/quick_start/iceberg.md
Labels: documentation, 3.5

#58623 [Enhancement] add more stats for lake compaction profile (backport #56769)
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/pk_tablet_writer.cpp
  be/src/storage/lake/vertical_compaction_task.cpp
  be/src/storage/olap_common.h
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionProfile.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionJobTest.java
  gensrc/proto/lake_service.proto
Labels: META-REVIEW

#58716 [Doc] Change WeChat QR Code img
  docs/zh/_assets/wechat_scan.png
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#55772 [Enhancement] Routine load records kafka partition/offset of dirty json data to the error log
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/runtime/routine_load/data_consumer_group.cpp
  be/src/runtime/routine_load/kafka_consumer_pipe.h
  be/src/runtime/stream_load/stream_load_pipe.cpp
  be/src/util/CMakeLists.txt
  be/src/util/byte_buffer.cpp
  be/src/util/byte_buffer.h
  be/test/CMakeLists.txt
  be/test/runtime/kafka_consumer_pipe_test.cpp
  be/test/runtime/stream_load_pipe_test.cpp
  be/test/util/byte_buffer_test.cpp
  be/test/util/byte_buffer_test2.cpp
Labels: 3.4

#58654 [Doc] Add description for `iceberg.catalog.view-endpoints-supported`
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4, 3.5

#58722 [Enhancement] Optimize the log "skip update replicas to visible version"
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
Labels: 3.3, 3.4, 3.5

#58732 [BugFix] Fix negative sleep time in sleepAtLeastIgnoreInterrupts
  fe/fe-core/src/main/java/com/starrocks/common/util/ThreadUtil.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/alter/OnlineOptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/RollupJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CommitRateLimiterTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVTestUtils.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.4, 3.5

#58740 [Doc] Revert "Change WeChat QR Code img"
  docs/zh/_assets/wechat_scan.png
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#56996 [BugFix] Fix partial update for auto increment column can not triggered by insert stmt
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/FileListTableRepo.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoAccessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  test/sql/test_auto_increment/R/test_auto_increment
  test/sql/test_auto_increment/T/test_auto_increment
  test/sql/test_dml/R/test_update
  test/sql/test_dml/T/test_update
Labels: behavior_changed, 3.3, 3.4, 3.5

#58745 [Doc] Update description for Expression Partition and Dynamic Overwrite
  docs/en/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation, 3.4, 3.5

#58750 [Enhancement] fix CVE error for parquet and httpclient5
  .trivyignore
  fe/pom.xml
  java-extensions/pom.xml
Labels: 3.5

#58678 [Enhancement] Add more merge commit metrics
  be/src/runtime/batch_write/batch_write_mgr.cpp
  be/src/runtime/batch_write/isomorphic_batch_write.cpp
  be/src/runtime/batch_write/isomorphic_batch_write.h
  be/src/runtime/batch_write/txn_state_cache.cpp
  be/src/runtime/batch_write/txn_state_cache.h
  be/src/runtime/stream_load/time_bounded_stream_load_pipe.cpp
  be/src/util/starrocks_metrics.h
  be/test/util/starrocks_metrics_test.cpp
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/BatchWriteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/CoordinatorBackendAssignerImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/MergeCommitJob.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/MergeCommitMetricRegistry.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/MergeCommitTask.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/MergeCommitTaskCallback.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/TxnStateDispatcher.java
  fe/fe-core/src/main/java/com/starrocks/metric/GaugeMetricImpl.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/BatchWriteMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/MergeCommitJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/MergeCommitTaskTest.java
Labels: 3.4, 3.5

#58600 [Enhancement] upgrade staros to v3.5-rc1
  be/CMakeLists.txt
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/runtime/exec_env.cpp
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  be/test/fs/fs_starlet_test.cpp
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/pom.xml
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.5

#58774 [BugFix]fix typo in log
  be/src/cache/block_cache/datacache_utils.cpp
Labels: 3.4, 3.5

#58752 [Enhancement] excluded_refresh_tables support different databases
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvRefreshArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessArbiter.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPartitioner.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: 3.3, 3.4, 3.5

#58778 [Enhancement] Add GrantType class to mini refactor Grant Stmt
  fe/fe-core/src/main/java/com/starrocks/authorization/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authorization/GrantType.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizationAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/BaseGrantRevokeRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/GrantRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RevokeRoleStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowGrantsStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/authorization/AuthorizationMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/RBACExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
Labels: 3.5

#58712 [Enhancement] Bump Iceberg version to 1.9.0
  fe/fe-core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestGroup.java
  fe/fe-core/src/main/java/org/apache/iceberg/ManifestReader.java
  fe/fe-core/src/main/java/org/apache/iceberg/MetadataParser.java
  fe/fe-core/src/main/java/org/apache/iceberg/StarRocksIcebergTableScan.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergAwsClientFactoryTest.java
  fe/pom.xml
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/iceberg/IcebergAwsClientFactory.java
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/pom.xml
Labels: behavior_changed, 3.5

#58788 [BugFix] fix touch_cache api in stream does not override correctly
  be/src/io/seekable_input_stream.h
  be/test/io/seekable_input_stream_test.cpp
Labels: 3.3, 3.4, 3.5

#58469 [Enhancement] support vacuum for shared tablet meta
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW

#58753 [BugFix] Fix possible duplicate finishInstance calls
  be/src/common/config.h
  be/src/exec/pipeline/exec_state_reporter.cpp
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/profile_report_worker.cpp
  be/src/util/thrift_rpc_helper.cpp
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/JoinTest.java
  test/sql/test_insert_overwrite/R/test_insert_with_profile
  test/sql/test_insert_overwrite/T/test_insert_with_profile
Labels: documentation, 3.3, 3.4, 3.5

#58838 [Doc] Update ALTER_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation

#58749 [Doc] Change compaction_mem_limit to compaction_memory_limit_per_worker in doc
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.5

#58841 [Doc] stop script doesn't have the `--daemon` option
  docs/en/deployment/deploy_manually.md
  docs/ja/deployment/deploy_manually.md
  docs/zh/deployment/deploy_manually.md
Labels: documentation, 3.2, 3.3, 3.4, 3.5

#58840 [UT] clean clang compiler warnings
  be/src/agent/agent_server.cpp
  be/src/exprs/jit/jit_engine.cpp
  be/test/exec/es/es_scan_reader_test.cpp
  be/test/exec/es/es_scroll_parser_test.cpp
  be/test/exec/file_scan_node_test.cpp
  be/test/exec/parquet_scanner_test.cpp
  be/test/exec/pipeline/pipeline_file_scan_node_test.cpp
  be/test/exec/stream/stream_pipeline_test.cpp
  be/test/exprs/bitmap_functions_test.cpp
  be/test/runtime/sorted_chunks_merger_test.cpp
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/rowset/bitshuffle_page_test.cpp
  be/test/storage/rowset/column_reader_writer_test.cpp
  be/test/storage/rowset/plain_page_test.cpp
  be/test/util/arrow/starrocks_column_to_arrow_test.cpp
  be/test/util/bthreads/future_test.cpp
  be/test/util/bthreads/shared_future_test.cpp
Labels: 3.5

#58853 [Doc] Sync build from prod
  docs/docusaurus/Dockerfile
  docs/docusaurus/babel.config.js
  docs/docusaurus/docusaurus.config.js
  docs/docusaurus/package.json
  docs/docusaurus/scripts/docker-run.sh
  docs/docusaurus/yarn.lock
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#58843 [BugFix] remove CVE-2025-27820 from .trivyignore
  .trivyignore
Labels: 3.5

#58737 [BugFix] fix partial compaction's segment deleted by abort transaction
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/transactions.cpp
  be/src/storage/lake/transactions.h
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/rowset_test.cpp
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW, 3.3, 3.4, 3.5

#58117 [Feature] Skeleton implementation for cngroup management
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/WarehouseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/warehouse/cngroup/AlterCnGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/warehouse/cngroup/CreateCnGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/warehouse/cngroup/DropCnGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/warehouse/cngroup/EnableDisableCnGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/DefaultWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Warehouse.java
  fe/fe-core/src/test/java/com/starrocks/alter/SystemHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/FakeEditLog.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/qe/CNGroupStatementExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/WarehouseAnalyzerTest.java
  fe/fe-core/src/test/java/com/starrocks/system/SystemInfoServiceTest.java
Labels: behavior_changed

#58773 [Enhancement] Support equal partition prune for non-monotonic function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  test/sql/test_automatic_partition/R/test_partition_prune
  test/sql/test_automatic_partition/T/test_partition_prune
Labels: 3.5

#58832 [BugFix] Fix multi partition column mv related bugs
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/MaterializedViewExceptions.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/HudiPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ListPartitionInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksTestBase.java
  test/sql/test_materialized_view/R/test_mv_with_multi_partition_columns_active
  test/sql/test_materialized_view/R/test_mv_with_multi_partition_columns_basic
  test/sql/test_materialized_view/R/test_mv_with_multi_partition_columns_optimize
  test/sql/test_materialized_view/R/test_mv_with_multi_partition_columns_rename
  test/sql/test_materialized_view/R/test_mv_with_multi_partition_columns_swap
  test/sql/test_materialized_view/T/test_mv_with_multi_partition_columns_active
  test/sql/test_materialized_view/T/test_mv_with_multi_partition_columns_basic
  test/sql/test_materialized_view/T/test_mv_with_multi_partition_columns_optimize
  test/sql/test_materialized_view/T/test_mv_with_multi_partition_columns_rename
  test/sql/test_materialized_view/T/test_mv_with_multi_partition_columns_swap
Labels: 3.5

#58441 [Feature] support combine txnlog for compaction transaction
  be/src/service/service_be/lake_service.cpp
  be/src/service/service_be/lake_service.h
  be/src/service/service_be/starrocks_be.cpp
  be/src/storage/lake/cloud_native_index_compaction_task.cpp
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/vertical_compaction_task.cpp
  be/test/service/lake_service_test.cpp
  be/test/storage/lake/compaction_scheduler_test.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/AggregateCompactionTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionTask.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeService.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceWithMetrics.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableHelperTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/AggregateCompactionTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/rpc/LakeServiceWithMetricsTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW

#58867 [BugFix] Fix bugs with partition_condition_retention
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/PartitionTTLScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/partition/PartitionSelector.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateTableWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionWithExprListTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/DynamicPartitionSchedulerTest.java
Labels: 3.5

#58897 [Doc] translation of cards on intro page
  docs/docusaurus/src/components/Features/index.js
  docs/ja/introduction/StarRocks_intro.md
Labels: documentation, 3.4, 3.5

#58876 [Enhancement] support fe total tablet count metric
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: 3.3, 3.4, 3.5

#58751 [Enhancement][SPM] spm support subquery & table function
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SubqueryRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SPMOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/BaselinePlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SPMAst2SQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SPMPlaceholderBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SPMPlan2SQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SPMPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SQLPlanGlobalStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/spm/SQLPlanStorage.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMPlan2SQLTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMPlanBindTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMPlanRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMTPCDSBindTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMTPCDSUseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMTPCHBindTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/spm/SPMTPCHUseTest.java
Labels: META-REVIEW

#58884 [BugFix] Use list partitioned mv for iceberg table with partition transforms
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryCacheAndMVTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
  test/sql/test_transparent_mv/R/test_mv_with_iceberg_partition_transform
  test/sql/test_transparent_mv/R/test_mv_with_iceberg_transforms
  test/sql/test_transparent_mv/T/test_mv_with_iceberg_partition_transform
  test/sql/test_transparent_mv/T/test_mv_with_iceberg_transforms
Labels: 3.5

#58871 [Enhancement] Persistent index support fix length size greater than 128 bytes
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
Labels: 3.4, 3.5

#58907 [Refactor] Modify the default semantics of the configuration related to the index cache.
  be/src/common/config.h
  be/src/storage/rowset/scalar_column_iterator.cpp
  be/src/storage/rowset/segment_iterator.cpp
Labels: behavior_changed

#58831 [BugFix] Fix push down aggregate to rollup lose predicate rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggregateGroupingSetsRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetsTest.java
Labels: 3.3, 3.4, 3.5

#58910 [Doc] Modify the default value of the configuration related to the index cache
  be/src/common/config.h
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation

#58938 [Doc] Use expression partition in the starrocks_audit_tbl__
  docs/en/administration/management/audit_loader.md
  docs/ja/administration/management/audit_loader.md
  docs/zh/administration/management/audit_loader.md
Labels: documentation, 3.4, 3.5

#58895 [BugFix] Fix the OAuth2.0 where arbitrary parameter from redirect_uri is removed.
  fe/fe-core/src/main/java/com/starrocks/http/rest/OAuth2Action.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
Labels: 3.5

#58770 [Doc] Fix Param Name
  docs/en/administration/user_privs/ranger_plugin.md
  docs/ja/administration/user_privs/ranger_plugin.md
  docs/zh/administration/user_privs/ranger_plugin.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#58944 [Doc] Fix wording
  docs/zh/introduction/Features.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#58709 [Enhancement] Improve tablet delta writer thread number
  be/src/common/config.h
  be/src/http/action/update_config_action.cpp
  be/src/storage/storage_engine.cpp
  be/src/storage/utils.cpp
  be/src/storage/utils.h
  be/test/http/action/update_config_action_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation

#58777 [Enhancement] add query progress into /current_queries command result
  fe/fe-core/src/main/java/com/starrocks/common/proc/CurrentQueryStatisticsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/qe/QueryStatisticsInfo.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/CurrentGlobalQueryStatisticsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/CurrentQueryStatisticsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/QueryStatisticsInfoTest.java
  gensrc/thrift/FrontendService.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.5

#58966 [Doc] move intro to snippet
  docs/en/_assets/catalog/_databricks_params.mdx
  docs/en/_assets/catalog/_deltalake_intro.mdx
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/ja/_assets/catalog/_databricks_params.mdx
  docs/ja/_assets/catalog/_deltalake_intro.mdx
  docs/ja/data_source/catalog/deltalake_catalog.md
  docs/zh/_assets/catalog/_databricks_params.mdx
  docs/zh/_assets/catalog/_deltalake_intro.mdx
  docs/zh/data_source/catalog/deltalake_catalog.md
Labels: documentation, 3.3, 3.4, 3.5

#58971 [Doc] fix column
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/ja/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/deltalake_catalog.md
Labels: documentation, 3.3, 3.4, 3.5

#58836 [Enhancement] Support materialized view concurrent prepare
  docs/en/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/profile/Tracers.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
Labels: documentation, 3.4, 3.5

#56783 [Doc][SPM] add spm docs
  docs/en/using_starrocks/SQL_plan_manager.md
  docs/ja/using_starrocks/SQL_plan_manager.md
  docs/zh/using_starrocks/SQL_plan_manager.md
Labels: documentation

#58957 [Enhancement] Add expiration config for cached starlet filesystem instances
  be/src/common/config.h
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#58943 [Enhancement] Rename oidc to jwt
  fe/fe-core/src/main/java/com/starrocks/authentication/JWTAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/JWTSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegrationFactory.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthPlugin.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/test/java/com/starrocks/authentication/OpenIdConnectAuthenticationTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlAuthPacketTest.java
  test/sql/test_security_integration/R/test_security_integration
  test/sql/test_security_integration/T/test_security_integration
Labels: 3.5

#58489 [Enhancement] load support filter black list node
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/test/java/com/starrocks/catalog/LocalTabletTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: 3.4, 3.5

#58976 [Doc] 3.3.14 release notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#58790 [BugFix] Fix race condition in BucketSequenceMorselQueue
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
Labels: 3.5

#58995 [Doc] Spark Connector Release notes 1.1.3
  docs/en/ecosystem_release/spark_connector.md
  docs/ja/ecosystem_release/spark_connector.md
  docs/zh/ecosystem_release/spark_connector.md
Labels: documentation

#58990 [BugFix] Fail to build MaterializedView relationship when do reload after FE image loaded
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java
Labels: 3.5

#59006 [BugFix] Fix the issue of frequent version loss during imports
  fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java
Labels: 3.2, 3.3, 3.4, 3.5

#59005 [Enhancement] Change proc_profile collect time to 2min
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.3, 3.4, 3.5

#58996 [Enhancement] MV support self-union-join
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshPlanBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java
Labels: 3.3, 3.4, 3.5

#59007 [BugFix] Fix show processlist miss warehouse param bug
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowProcesslistStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowProcesslistStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.5

#59016 [Enhancement] Add azure cpp sdk
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/azure-storage-files-shares_12.12.0.patch
  thirdparty/vars.sh
Labels: 3.5

#59030 [BugFix] Fix incorrect union plan causing fe oom
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/UnionToValuesRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/OptExpressionValidator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
  fe/fe-core/src/test/resources/sql/query_dump/union_with_empty_input.json
Labels: 3.2, 3.3, 3.4, 3.5

#59033 [BugFix] better compatibility for coverage build
  be/CMakeLists.txt
Labels: 3.4, 3.5

#59031 [BugFix] do not ignore error when starmgr's meta file is corrupted
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
Labels: 3.4, 3.5

#58621 [BugFix] Check multi_column_statistics table status before access
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.5

#59065 [Doc] Fix issues in Expression Partitions
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation, 3.4, 3.5

#58852 [BugFix] NodeChannel should check the error of eos rpc asap
  be/src/exec/tablet_sink_colocate_sender.cpp
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/exec/tablet_sink_sender.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel_mgr.cpp
  be/test/exec/tablet_sink_index_channel_test.cpp
Labels: 3.5

#59056 [BugFix] Fix miss update job state when replaying restore log may cause restored table lost after FE restart
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.4, 3.5

#58710 [Enhancement] support adaptive RocksDB write buffer configuration
  be/src/common/config.h
  be/src/storage/kv_store.cpp
  be/src/storage/kv_store.h
  be/test/storage/kv_store_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#58933 [BugFix] Deletion task failed when using datetime as a deletion predicate
  be/src/storage/utils.cpp
  be/test/storage/utils_test.cpp
  test/sql/test_datetime/R/test_datetime
  test/sql/test_datetime/T/test_datetime
Labels: 3.3, 3.4, 3.5

#59091 [Doc] Remove enable_pipeline_load in guide
  docs/en/administration/management/resource_management/resource_group.md
  docs/ja/administration/management/resource_management/resource_group.md
  docs/zh/administration/management/resource_management/resource_group.md
Labels: documentation

#59078 [UT] reduce debug info size for unit test under gcov mode
  be/test/CMakeLists.txt
Labels: 3.5

#59090 [Doc] Configs for Bloom Filter in Parquet
  docs/en/administration/management/BE_configuration.md
  docs/en/sql-reference/System_variable.md
  docs/ja/administration/management/BE_configuration.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.5

#58854 [BugFix] Primary replica should cancel secondary replica if rpc failed
  be/src/runtime/local_tablets_channel.cpp
  be/src/storage/segment_replicate_executor.h
  be/test/runtime/local_tablets_channel_test.cpp
Labels: 3.5

#58387 [Enhancement] Support customize warehouse parameter for _query_plan http action
  fe/fe-core/src/main/java/com/starrocks/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/test/java/com/starrocks/http/TableQueryPlanActionTest.java
Labels: 3.4, 3.5

#59066 [Enhancement] Add azure blob credential in backend
  be/src/fs/CMakeLists.txt
  be/src/fs/credential/cloud_configuration.h
  be/src/fs/credential/cloud_configuration_factory.cpp
  be/src/fs/credential/cloud_configuration_factory.h
  be/test/CMakeLists.txt
  be/test/fs/credential/cloud_configuration_factory_test.cpp
Labels: 3.5

#59105 [BugFix] Fix pipe source poll exception causes pipe error state
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/PipeManagerTest.java
Labels: 3.4, 3.5

#59097 [Enhancement] Add azure blob uri class in frontend
  fe/fe-core/src/main/java/com/starrocks/fs/azure/AzBlobURI.java
  fe/fe-core/src/test/java/com/starrocks/fs/azure/AzBlobURITest.java
Labels: 3.5

#59034 [Enhancement] Fix CVE-2024-13009
  fe/pom.xml
  trivy.yaml
Labels: 3.4, 3.5

#59062 [Enhancement] Add azure blob uri class in backend
  be/src/fs/CMakeLists.txt
  be/src/fs/azure/azblob_uri.cpp
  be/src/fs/azure/azblob_uri.h
  be/src/fs/azure/utils.h
  be/test/CMakeLists.txt
  be/test/fs/azure/azblob_uri_test.cpp
Labels: 3.5

#59127 [Refactor] Modify some configuration names related to adaptive adjustment of disk cache and memory cache.
  be/src/cache/datacache.cpp
  be/src/cache/disk_space_monitor.cpp
  be/src/cache/mem_space_monitor.cpp
  be/src/common/config.h
  be/test/cache/block_cache/block_cache_test.cpp
  be/test/cache/disk_space_monitor_test.cpp
  be/test/http/action/update_config_action_test.cpp
  be/test/io/cache_input_stream_test.cpp
Labels: behavior_changed

#59138 [Doc] Update the default value of `datacache_mem_size` in the document. (backport #59064)
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation

#59032 [BugFix] fix getting hive partition bug when using escaped string
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetaClient.java
  test/sql/test_dml/R/test_escape
  test/sql/test_dml/T/test_escape
Labels: 3.5

#59089 [BugFix] Stream load failed because duplicate begin txn request
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
Labels: 3.3, 3.4, 3.5

#59063 [Doc] Update MV FE Configuration docs
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.5

#58219 [Doc] Merge Expression Partitions
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation, 3.5

#58620 [Doc] SQL Transaction
  docs/docusaurus/sidebars.json
  docs/en/loading/SQL_transaction.md
  docs/ja/loading/SQL_transaction.md
  docs/zh/loading/SQL_transaction.md
Labels: documentation, 3.5

#58391 [Doc] JDK 17 doc
  docs/en/deployment/deployment_prerequisites.md
  docs/en/sql-reference/sql-functions/JAVA_UDF.md
  docs/ja/deployment/deployment_prerequisites.md
  docs/ja/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/deployment/deployment_prerequisites.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
Labels: documentation, 3.5

#59161 [Enhancement] apply the task_runs_max_history_number to task_runs
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
Labels: behavior_changed, 3.3, 3.4, 3.5

#59166 [Doc] Add 3.5 RC Release Notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#58579 [Doc] Generated columns in shared-data
  docs/en/deployment/shared_data/feature-support-shared-data.md
  docs/en/sql-reference/sql-statements/generated_columns.md
  docs/ja/deployment/shared_data/feature-support-shared-data.md
  docs/ja/sql-reference/sql-statements/generated_columns.md
  docs/zh/deployment/shared_data/feature-support-shared-data.md
  docs/zh/sql-reference/sql-statements/generated_columns.md
Labels: documentation, 3.5

#57875 [Doc] New variables for 3.5
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/System_variable.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.5

#59159 [Doc] update doc with correct deployment steps
  docs/en/developers/development-environment/ide-setup.md
Labels: documentation

#59184 [Doc] Release 3.5 as RC
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#59185 [UT] Fix unstable test_agg_state_with_sync_mv.sql
  test/sql/test_agg_state/R/test_agg_state_with_sync_mv.sql
  test/sql/test_agg_state/T/test_agg_state_with_sync_mv.sql
Labels: 3.5

#59181 [BugFix] Stream load failed because receive duplicate stream load put request
  fe/fe-core/src/main/java/com/starrocks/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.3, 3.4, 3.5

#59164 [Doc] Fix docs about partition_refresh_number
  docs/en/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/ja/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/zh/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
Labels: documentation, 3.3, 3.4, 3.5

#59212 [UT] Fix unstable test
  test/sql/test_partial_update_column_mode/R/test_partial_update
  test/sql/test_partial_update_column_mode/T/test_partial_update
Labels: 3.3, 3.4, 3.5

#59210 [Doc] Add links to 3.5 Release notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#59160 [Enhancement] Add azure blob file system in frontend
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureCloudConfigurationProvider.java
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureStorageCloudCredential.java
  fe/fe-core/src/main/java/com/starrocks/fs/FileSystem.java
  fe/fe-core/src/main/java/com/starrocks/fs/azure/AzBlobFileSystem.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFileSystemWrap.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
  fe/fe-core/src/test/java/com/starrocks/fs/FileSystemTest.java
  fe/fe-core/src/test/java/com/starrocks/fs/azure/AzBlobFileSystemTest.java
  fe/pom.xml
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/credential/CloudConfigurationConstants.java
Labels: 3.5

#59178 [BugFix] Fix query fail after rename column name if scan node contain unused output column name
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  test/sql/test_column_rename/R/test_column_rename
  test/sql/test_column_rename/T/test_column_rename
Labels: 3.3, 3.4, 3.5

#59216 [BugFix]fix crash when a subfield of struct appearw in two predicates
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  test/sql/test_external_file/R/test_parquet_struct_in_struct
  test/sql/test_external_file/T/test_parquet_struct_in_struct
Labels: 3.3, 3.4, 3.5

#59227 [BugFix] Disable release data cache before BE core dump
  be/src/common/config.h
Labels: 3.3, 3.4, 3.5

#59239 [Doc] Minor fix for 3.5 Doc
  docs/docusaurus/i18n/ja/docusaurus-plugin-content-docs/current.json
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/en/using_starrocks/SQL_plan_manager.md
  docs/ja/administration/user_privs/authentication/_category_.yml
  docs/ja/administration/user_privs/authentication/native_authentication.md
  docs/ja/administration/user_privs/authentication/security_integration.md
  docs/ja/administration/user_privs/authorization/_category_.yml
  docs/ja/administration/user_privs/group_provider.md
  docs/ja/using_starrocks/SQL_plan_manager.md
  docs/zh/administration/user_privs/authentication/_category_.yml
  docs/zh/administration/user_privs/authentication/native_authentication.md
  docs/zh/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/authorization/_category_.yml
  docs/zh/administration/user_privs/group_provider.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
  docs/zh/using_starrocks/SQL_plan_manager.md
Labels: documentation, 3.5

#58576 [Enhancement] add athena partition projection table error msg for glue
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/metastore/GlueMetastoreClientDelegate.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/HiveTableValidator.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/glue/util/MetastoreClientUtils.java
  fe/fe-core/src/test/java/com/starrocks/connector/hive/glue/util/MetastoreClientUtilsTest.java
Labels: 3.5

#59238 [UT] Fix unstable ut
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
Labels: 3.3, 3.4, 3.5

#58079 [Doc] Add percentile_approx_weight doc
  docs/en/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/en/sql-reference/sql-functions/aggregate-functions/percentile_approx_weight.md
  docs/ja/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/ja/sql-reference/sql-functions/aggregate-functions/percentile_approx_weight.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/percentile_approx.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/percentile_approx_weight.md
Labels: documentation, 3.3, 3.4, 3.5

#58080 [Doc] Add ds_theta_count_distinct doc
  docs/en/sql-reference/sql-functions/aggregate-functions/ds_theta_count_distinct.md
  docs/ja/sql-reference/sql-functions/aggregate-functions/ds_theta_count_distinct.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/ds_theta_count_distinct.md
Labels: documentation, 3.5

#59253 [Doc] Update Dashboard download links
  docs/en/administration/management/monitoring/Monitor_and_Alert.md
  docs/ja/administration/management/monitoring/Monitor_and_Alert.md
  docs/zh/administration/management/monitoring/Monitor_and_Alert.md
Labels: documentation, 3.5

#59153 [BugFix] Fix result queue capacity of result sink
  be/src/exec/data_sink.cpp
  be/src/exec/pipeline/result_sink_operator.cpp
  be/src/exec/pipeline/result_sink_operator.h
Labels: 3.3, 3.4, 3.5

#59194 [BugFix] Fix query version not found error
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/transaction/TransactionStateTest.java
Labels: META-REVIEW, 3.4, 3.5

#59024 [Feature] implement insert into iceberg partition transform table
  be/src/connector/async_flush_stream_poller.h
  be/src/connector/connector_chunk_sink.cpp
  be/src/connector/connector_chunk_sink.h
  be/src/connector/hive_connector.cpp
  be/src/connector/iceberg_chunk_sink.cpp
  be/src/connector/iceberg_chunk_sink.h
  be/src/connector/sink_memory_manager.cpp
  be/src/connector/sink_memory_manager.h
  be/src/connector/utils.cpp
  be/src/connector/utils.h
  be/src/exec/pipeline/exchange/local_exchange.cpp
  be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp
  be/src/exec/pipeline/exchange/local_exchange_source_operator.h
  be/src/exec/pipeline/sink/table_function_table_sink_operator.cpp
  be/src/formats/file_writer.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/iceberg_table_sink.cpp
  be/test/connector_sink/iceberg_chunk_sink_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/IcebergTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergApiConverter.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/ScalarOperatorToIcebergExpr.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/IcebergPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/TypeManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java
  fe/fe-core/src/test/java/com/starrocks/catalog/IcebergTableTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorPartitionTraitsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/TableTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeInsertTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/InsertPlanTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/Types.thrift
Labels: PROTO-REVIEW

#59247 [BugFix] persistent index will lost data when load snapshot fail
  be/src/storage/persistent_index.cpp
  be/src/util/phmap/phmap_dump.h
  be/test/storage/persistent_index_test.cpp
Labels: 3.3, 3.4, 3.5

#59248 [BugFix] Fix check runtime filter version for compatibility
  be/src/exec/pipeline/runtime_filter_types.cpp
Labels: 3.5

#59209 [Enhancement] Add some load metrics for cloud-native
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/delta_writer.cpp
Labels: 3.3, 3.4, 3.5

#59052 [BugFix] Avoid polluting task run properties in multi task runs
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/history/TaskRunHistoryTable.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunManagerTest.java
Labels: 3.3, 3.4, 3.5

#58932 [BugFix] Fix auto increment partial update triggered by error if auto increment column is key when it miss in target columns in insert stmt
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/FileListTableRepo.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/filelist/RepoAccessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  test/sql/test_auto_increment/R/test_auto_increment
  test/sql/test_auto_increment/T/test_auto_increment
Labels: 3.4, 3.5

#59252 [BugFix] Fix query concurrency limit in SlotSelectionStrategyV2
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2Test.java
Labels: 3.5

#59273 [BugFix] Fix compilation errors in centos7
  thirdparty/build-thirdparty.sh
Labels: 3.5

#59059 [Enhancement] Support using native sdk to access azure blob storage in files() table function
  be/src/fs/fs.cpp
  be/src/fs/fs.h
  be/src/fs/fs_util.h
  be/test/fs/fs_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/fs/FileSystem.java
  fe/fe-core/src/main/java/com/starrocks/fs/azure/AzBlobFileSystem.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFileSystemWrap.java
  fe/fe-core/src/main/java/com/starrocks/planner/FileScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/TableFunctionTableSink.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
  fe/fe-core/src/test/java/com/starrocks/fs/azure/AzBlobFileSystemTest.java
  gensrc/thrift/CloudConfiguration.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.5

#59293 [Doc] Add missing notes
  docs/en/sql-reference/sql-statements/table_bucket_part_index/REFRESH_EXTERNAL_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/REFRESH_EXTERNAL_TABLE.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#59162 [Doc] Cherry-picking information for developers.
  docs/en/developers/versions.md
Labels: documentation

#59304 [UT] Fix flaky ThreadPool tests
  be/test/util/threadpool_test.cpp
Labels: 3.3, 3.4, 3.5

#59311 [Doc] Update page ranking
  docs/en/loading/Flink_cdc_load.md
  docs/en/loading/Loading_intro.md
  docs/en/sql-reference/sql-statements/loading_unloading/BROKER_LOAD.md
Labels: documentation, 3.3, 3.4, 3.5

#59319 [Doc] translation of files related to versioning and backporting
  docs/ja/developers/versions.md
  docs/ja/introduction/versioning.md
  docs/zh/developers/versions.md
  docs/zh/introduction/versioning.md
Labels: documentation

#59328 [Doc] adjust doc for lake_compaction_disable_ids
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.4, 3.5

#59038 [Refactor] Mini Refactor to BrokerMgr
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/BrokerMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/BrokerProcNode.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/ProcService.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/ModifyBrokerInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowBrokerStmt.java
  fe/fe-core/src/test/java/com/starrocks/catalog/BrokerMgrTest.java
Labels: META-REVIEW

#59266 [BugFix] add escape character in column comment in SHOW CREATE TABLE …
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableLikeTest.java
Labels: 3.5

#59342 [BugFix]Don't return error when decoding min/max is not suppoted
  be/src/formats/parquet/scalar_column_reader.cpp
  be/src/formats/parquet/statistics_helper.cpp
Labels: 3.3

#59009 [Enhancement] Report tablet version in advance if publish cost too much time
  be/src/common/config.h
  be/src/storage/publish_version_manager.cpp
  be/src/storage/publish_version_manager.h
  be/test/storage/publish_version_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/leader/LeaderImplTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.4, 3.5

#59325 [Doc] Bash fix in doc
  docs/en/developers/development-environment/ide-setup.md
Labels: documentation

#59353 [Doc]Update jwt_authentication.md
  docs/zh/administration/user_privs/authentication/jwt_authentication.md
Labels: documentation, 3.5

#59308 [Enhancement] Support service principal authentication in azure blob file system
  be/src/fs/azure/fs_azblob.cpp
  be/src/fs/credential/cloud_configuration.h
  be/src/fs/credential/cloud_configuration_factory.cpp
  be/src/fs/credential/cloud_configuration_factory.h
  be/test/CMakeLists.txt
  be/test/fs/azure/fs_azblob_test.cpp
  be/test/fs/credential/cloud_configuration_factory_test.cpp
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureCloudConfigurationProvider.java
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureStorageCloudCredential.java
  fe/fe-core/src/main/java/com/starrocks/fs/azure/AzBlobFileSystem.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
  fe/fe-core/src/test/java/com/starrocks/fs/azure/AzBlobFileSystemTest.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/credential/CloudConfigurationConstants.java
Labels: 3.5

#59219 [BugFix] fix persistent index compatibility issue when migrate between different cpu arch
  be/src/exprs/agg/distinct.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/src/util/phmap/phmap.h
  be/src/util/phmap/phmap_dump.h
  be/test/CMakeLists.txt
  be/test/storage/persistent_index_snapshot_load_test.cpp
Labels: 3.4, 3.5

#59368 [BugFix]Fix table_type
  contrib/trino-connector/src/main/java/io/trino/plugin/starrocks/StarRocksClient.java
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalCatalogTableBasicInfo.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowTablesTest.java
  test/sql/test_temporary_table/R/temporary_table
Labels: 3.4, 3.5

#59369 [BugFix] Fix mv refresh external table error
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: 3.5
