Repository StarRocks/starrocks, pull requests merged in 2025-06, with the labels that each got.

#59525 [Doc] show sql blacklist typo fix
  docs/en/administration/management/resource_management/Blacklist.md
  docs/ja/administration/management/resource_management/Blacklist.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#59510 [BugFix] fix LambdaFunction's isConst always return false
  be/src/exprs/lambda_function.h
  test/sql/test_array/R/test_array_map
  test/sql/test_array/T/test_array_map
Labels: 3.3, 3.4, 3.5

#59378 [Feature] Introduce virtual buckets metadata for dynamic tablet splitting and merging
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndex.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/IndicesProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcDir.java
Labels: META-REVIEW

#59536 [BugFix] Fix invalid connections are fetched in the thrift connection pools
  be/src/common/config.h
  be/src/runtime/client_cache.cpp
  be/src/runtime/client_cache.h
  be/src/util/thrift_client.cpp
  be/src/util/thrift_client.h
  be/test/CMakeLists.txt
  be/test/util/thrift_client_test.cpp
Labels: 3.3, 3.4, 3.5

#59554 [BugFix] fix shard group id lost when replay DDL from 3.3
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartition.java
Labels: 3.4, 3.5

#59580 [BugFix] Fix potential race condition
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
Labels: 3.4, 3.5

#59577 [BugFix] keep lambdaFunction's isConst as before, array_contains fall back to non-const process when state is nullptr
  be/src/exprs/array_functions.tpp
  be/src/exprs/lambda_function.h
Labels: 3.3, 3.4, 3.5

#58923 [Feature] support data file bundling
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/fs/CMakeLists.txt
  be/src/fs/bundle_file.cpp
  be/src/fs/bundle_file.h
  be/src/fs/encrypt_file.h
  be/src/fs/fs.cpp
  be/src/fs/fs.h
  be/src/runtime/lake_tablets_channel.cpp
  be/src/storage/lake/async_delta_writer.cpp
  be/src/storage/lake/async_delta_writer.h
  be/src/storage/lake/column_mode_partial_update_handler.cpp
  be/src/storage/lake/delta_writer.cpp
  be/src/storage/lake/delta_writer.h
  be/src/storage/lake/general_tablet_writer.cpp
  be/src/storage/lake/general_tablet_writer.h
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/pk_tablet_writer.cpp
  be/src/storage/lake/pk_tablet_writer.h
  be/src/storage/lake/rowset.cpp
  be/src/storage/lake/rowset_update_state.cpp
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/src/storage/lake/tablet_writer.h
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/vacuum.cpp
  be/src/storage/rowset/segment.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_writer.cpp
  be/src/storage/rowset/segment_writer.h
  be/test/CMakeLists.txt
  be/test/fs/bundle_file_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  gensrc/proto/internal_service.proto
  gensrc/proto/lake_types.proto
  gensrc/thrift/DataSinks.thrift
Labels: PROTO-REVIEW

#59487 [Enhancement] Enable low cardinality optimization on PRIMARY KEY tables.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
Labels: behavior_changed, 3.3, 3.4, 3.5

#59500 [Doc] Add a troubleshooting part for datacache document to help users quickly troubleshoot some common issues during cache usage.
  docs/docusaurus/sidebars.json
  docs/en/_assets/data_cache_be_web_console.png
  docs/en/data_source/data_cache_troubleshooting.md
  docs/ja/_assets/data_cache_be_web_console.png
  docs/ja/data_source/data_cache_troubleshooting.md
  docs/zh/_assets/data_cache_be_web_console.png
  docs/zh/data_source/data_cache_troubleshooting.md
Labels: documentation, 3.3, 3.4, 3.5

#59555 [Doc] Details for SHOW PARTITION, SHOW TABLET, and SHOW PROC
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SHOW_PARTITIONS.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SHOW_TABLET.md
  docs/ja/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/SHOW_PARTITIONS.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/SHOW_TABLET.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SHOW_PARTITIONS.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/SHOW_TABLET.md
Labels: documentation, 3.3, 3.4, 3.5

#59557 [Doc] Workflow for Cluster Snapshot
  docs/en/_assets/cluster_snapshot_workflow.png
  docs/en/administration/cluster_snapshot.md
  docs/ja/_assets/cluster_snapshot_workflow.png
  docs/ja/administration/cluster_snapshot.md
  docs/zh/_assets/cluster_snapshot_workflow.png
  docs/zh/administration/cluster_snapshot.md
Labels: documentation, 3.4, 3.5

#59559 [Doc] Fix Iceberg Catalog Heading
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4, 3.5

#59562 [Refactor] Rename enable_partiton_aggregate to file_bundling
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/Utils.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeRollupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableHelperTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakeAggregatePublishTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
  gensrc/proto/lake_service.proto
  gensrc/thrift/AgentService.thrift
Labels: META-REVIEW, PROTO-REVIEW

#59640 [BugFix] Revert Reduce the size of data written to edit log when schema changes in shared-data clusters with fast schema evolution enabled. (#55282)
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java
Labels: 3.4, 3.5

#59637 [Doc] An example of interacting with Cloudflare R2 Data Catalog
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/_assets/commonMarkdown/quickstart-iceberg-tip.mdx
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.3, 3.4, 3.5

#59647 [BugFix] Fix UnionToValuesRule bug with unligned constant values
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/UnionToValuesRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SelectConstTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SetTest.java
  test/sql/test_execute_in_fe/R/test_execute_in_fe
  test/sql/test_execute_in_fe/T/test_execute_in_fe
Labels: 3.5

#58764 [Enhancement] Support partition_retention_condition for multi level partition
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/PartitionTTLScheduler.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TriggerAction.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/partition/PartitionSelector.java
  test/sql/test_automatic_partition/R/test_partition_ttl
  test/sql/test_automatic_partition/T/test_partition_ttl
Labels: 3.5

#59657 [Enhancement] Add azure use managed identity property
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureCloudConfigurationProvider.java
  fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureStorageCloudCredential.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
  fe/fe-core/src/test/java/com/starrocks/fs/azure/AzBlobFileSystemTest.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/credential/CloudConfigurationConstants.java
Labels: 3.5

#59587 [BugFix] disable ASAN build when gcov is enabled to avoid link failure
  build.sh
  run-be-ut.sh
Labels: 3.3, 3.4, 3.5

#59561 [Feature] CNGroup skeleton, error codes, interfaces and persist
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/WarehouseInternalOpLog.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FeNameFormat.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/WarehouseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/warehouse/ShowClustersStmt.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/DefaultWarehouse.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/Warehouse.java
  fe/fe-core/src/test/java/com/starrocks/alter/SystemHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/EditLogDeserializerTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/WarehouseInternalOpLogTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/CNGroupStatementExecutorTest.java
Labels: behavior_changed, META-REVIEW

#59658 [Doc] Fix Iceberg Headings - part 2
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4, 3.5

#59655 [Doc] Add Jemalloc Heap Profiling Doc
  docs/en/_assets/visualized_heap_profile.png
  docs/en/developers/jemalloc_heap_profile.md
  docs/ja/_assets/visualized_heap_profile.png
  docs/ja/developers/jemalloc_heap_profile.md
  docs/zh/_assets/visualized_heap_profile.png
  docs/zh/developers/jemalloc_heap_profile.md
Labels: documentation, 3.3, 3.4, 3.5

#59679 [Doc] Translate HTTP Interface Doc
  docs/docusaurus/sidebars.json
  docs/en/administration/http_interface.md
  docs/ja/administration/http_interface.md
Labels: documentation, 3.3, 3.4, 3.5

#59442 [BugFix] Redact credentials in audit log when SQL parsing fails
  fe/fe-core/src/main/java/com/starrocks/common/util/SqlCredentialRedactor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/com/starrocks/common/util/SqlCredentialRedactorTest.java
Labels: 3.3, 3.4, 3.5

#59517 [Enhancement] add metrics for sql black list intercepts
  docs/en/administration/management/monitoring/metrics.md
  docs/ja/administration/management/monitoring/metrics.md
  docs/zh/administration/management/monitoring/metrics.md
  fe/fe-core/src/main/java/com/starrocks/meta/SqlBlackList.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: documentation

#19239 [BugFix] fix rpc closure unexpected delete (#19235)
  be/src/storage/table_reader.cpp
Labels: be-build

#34722 [BugFix] Use correct parameter for pulsar_consumer.seek()
  be/src/runtime/routine_load/data_consumer.cpp
Labels: 2.5, 3.0

#59713 [BugFix] Add apostrophes in insert external statistics query
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
Labels: 3.3, 3.4, 3.5

#59771 [BugFix] Transform all exception for some operation in HdfsFsMgr into StarRocksException to prevent Exception leak for the caller
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/test/java/com/starrocks/fs/HdfsUtilTest.java
Labels: 3.4, 3.5

#59786 [Doc] 3.4.4 release notes
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#59689 [Enhancement] Fix CVE-2022-41404
  fe/pom.xml
  fs_brokers/apache_hdfs_broker/src/pom.xml
  java-extensions/odps-reader/pom.xml
Labels: 3.5

#59772 [Enhancement] support minimal docker image for FE/BE
  docker/dockerfiles/be/be-ubuntu.Dockerfile
  docker/dockerfiles/fe/fe-ubuntu.Dockerfile
Labels: 3.5

#59576 [Feature] Support ssl connection for LDAP access
  docs/zh/administration/user_privs/authentication/ldap_authentication.md
  docs/zh/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/group_provider.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProviderForNative.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LdapSslSocketFactory.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SimpleLDAPSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SslUtils.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthPlugin.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/LdapSecurityTest.java
  fe/pom.xml
Labels: documentation

#59797 [BugFix] suppression __cxa_thread_atexit
  conf/asan_suppressions.conf
Labels: 3.4, 3.5

#59804 [BugFix] fix invalid json string when parsing PipeFileRecord
  fe/fe-core/src/main/java/com/starrocks/common/InvalidOlapTableStateException.java
  fe/fe-core/src/main/java/com/starrocks/load/pipe/PipeFileRecord.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
Labels: 3.5

#59809 [BugFix] Fix race condition in merge_isomorphic_profiles
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/test/util/runtime_profile_test.cpp
Labels: 3.3, 3.4, 3.5

#59815 [BugFix] Revert PR #59009
  be/src/common/config.h
  be/src/storage/publish_version_manager.cpp
  be/src/storage/publish_version_manager.h
  be/test/storage/publish_version_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/leader/LeaderImplTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.4, 3.5

#59732 [BugFix] Fix bug of BrokerDesc can not restore from metadb
  fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadMgrTest.java
Labels: 3.3, 3.4, 3.5

#59001 [BugFix] Fix cancel stream load api is not registered correctly
  docs/en/administration/http_interface.md
  docs/zh/administration/http_interface.md
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/CancelStreamLoadAction.java
  fe/fe-core/src/test/java/com/starrocks/http/CancelStreamLoadActionTest.java
Labels: documentation, 3.4, 3.5

#59792 [Doc] Fix Image Directory in Hybrid Table
  docs/en/table_design/hybrid_table.md
  docs/ja/table_design/hybrid_table.md
  docs/zh/table_design/hybrid_table.md
Labels: documentation, 3.3, 3.4, 3.5

#59787 [Enhancement] Support changing kafka_broker_list in ALTER ROUTINE LOAD
  fe/fe-core/src/main/java/com/starrocks/analysis/RoutineLoadDataSourceProperties.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: META-REVIEW, 3.4, 3.5

#59834 [Enhancement] Support minute granularity of date_trunc
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/T/test_automatic_partition
Labels: 3.4, 3.5

#52908 [BugFix] fix alter load label error check
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterLoadAnalyzer.java
Labels: 2.5, 3.0, 3.1, 3.2

#52459 [Doc] update primary Key index persistence on remote storage
  docs/en/deployment/shared_data/feature-support-shared-data.md
  docs/zh/deployment/shared_data/feature-support-shared-data.md
Labels: documentation

#45912 [Enhancement] support drop resource group if exists
  fe/fe-core/src/main/java/com/starrocks/catalog/ResourceGroupMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DropResourceGroupStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ResourceGroupStmtTest.java
Labels: 2.5, 3.0

#59876 [Doc] Revise Release Notes for 3.5.0
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#59912 [Doc] Release 3.5.0 as Latest - Part -3
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#59910 [Doc]Update feature-support-data-lake-analytics.md
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/ja/data_source/feature-support-data-lake-analytics.md
  docs/zh/data_source/feature-support-data-lake-analytics.md
Labels: documentation, 3.3, 3.4, 3.5

#59907 [BugFix] Avoid printing auth info in log
  fe/fe-core/src/main/java/com/starrocks/http/BaseAction.java
Labels: 3.3, 3.4, 3.5

#59916 [Doc] Fix RC tag
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#59941 [BugFix] fix modify column wrongly handled for older version table
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
Labels: 3.3, 3.4, 3.5

#59883 [Enhancement] change a few metrics fe leader awareness
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/metric/JsonMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/LeaderAwareGaugeMetric.java
  fe/fe-core/src/main/java/com/starrocks/metric/LeaderAwareGaugeMetricLong.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/test/java/com/starrocks/metric/LeaderAwareGaugeMetricTest.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricRepoTest.java
Labels: behavior_changed, 3.4, 3.5

#59919 [BugFix] Fix the `disk_device_id` function to aquire the device_id of an non-existent entry by its ancestor entries.
  be/src/cache/datacache_utils.cpp
  be/test/cache/datacache_utils_test.cpp
Labels: 3.4, 3.5

#59904 [BugFix] Fix third-party build failure for pulsar-client-cpp-3.3.0 mo…
  docs/en/developers/development-environment/ide-setup.md
  docs/ja/developers/development-environment/ide-setup.md
  thirdparty/build-thirdparty.sh
Labels: documentation

#59963 [UT] Fix unstable ut
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
Labels: 3.5

#59924 [BugFix] Fix starrocks_fe_routine_load_max_lag_of_partition metric in multi-warehouse case
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
Labels: 3.3, 3.4, 3.5

#59954 [BugFix] Fix partition creation failure during multi-table write with in a single transaction
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  test/sql/test_automatic_partition/R/test_multi_insert
  test/sql/test_automatic_partition/T/test_multi_insert
Labels: 3.3, 3.4, 3.5

#60003 [BugFix] fix window pre-aggregation for count(*)
  be/src/exec/pipeline/sort/local_partition_topn_context.cpp
  test/sql/test_window_function/R/test_window_pre_agg_with_rank
  test/sql/test_window_function/T/test_window_pre_agg_with_rank
Labels: 3.4, 3.5

#59845 [Enhancement] Introduce ClusterSnapshotInfo for cluster snapshot
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/DatabaseSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/MaterializedIndexSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/PartitionSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/PhysicalPartitionSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/SnapshotInfoHelper.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/TableSnapshotInfo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/lake/snapshot/ClusterSnapshotInfoTest.java
Labels: META-REVIEW

#59920 [Enhancement] Add SKIPPED State for task run
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/WarehouseMetricsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/metric/IMaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsBlackHoleEntity.java
  fe/fe-core/src/main/java/com/starrocks/metric/MaterializedViewMetricsEntity.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/warehouse/WarehouseMetrics.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/BaseTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/Constants.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/DataCacheSelectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/SqlTaskRunProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunExecutor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunProcessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/MockTaskRunProcessor.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_materialized_view/R/test_show_materialized_view
Labels: 3.4, 3.5

#59972 [BugFix] Fix case-when return collection type bugs
  be/src/exprs/case_expr.cpp
  be/test/exprs/case_expr_test.cpp
Labels: 3.3, 3.4, 3.5

#59998 [Enhancement] avoid lake compaction might be delayed even all sub tasks success
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/PartitionStatistics.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/PartitionStatisticsTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakeTableTestHelper.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakeTableTxnLogApplierTest.java
Labels: 3.4, 3.5

#60053 [BugFix] Filesystem cache failure in concurrent scenarios.
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  be/test/service/staros_worker_test.cpp
Labels: 3.3, 3.4, 3.5

#60027 [Enhancement] Add a force refresh strategy and add meta functions for better debug
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/function/MetaFunctions.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/MetaFunctionsTest.java
  test/sql/test_materialized_view/R/test_mv_meta_functions
  test/sql/test_materialized_view/R/test_mv_refresh_strategy_with_force
  test/sql/test_materialized_view/T/test_mv_meta_functions
  test/sql/test_materialized_view/T/test_mv_refresh_strategy_with_force
Labels: META-REVIEW, 3.4, 3.5

#59790 [Doc] Update AuditLoader table structure
  docs/en/administration/management/audit_loader.md
Labels: documentation, 3.5

#60052 [BugFix] Fix assertion failure for insert stmt planning of shuffle for primary key table
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  test/sql/test_insert_empty/R/test_insert_partial_update
  test/sql/test_insert_empty/T/test_insert_partial_update
Labels: 3.3, 3.4, 3.5

#60057 [Refactor] rename aggregate/shared prefix to bundle
  be/src/service/service_be/lake_service.cpp
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/lake/tablet_metadata.h
  be/src/storage/lake/txn_log_applier.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  be/test/storage/lake/test_util.h
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  gensrc/proto/lake_types.proto
  gensrc/thrift/AgentService.thrift
Labels: PROTO-REVIEW

#60092 [UT] Fix timeout CreateMaterializedViewTest test
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
Labels: 3.5

#60026 [BugFix] extend the DEFER LOCK optimization to SUBMIT TASK
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/StatementPlannerTest.java
Labels: 3.3, 3.4, 3.5

#60022 [Enhancement] optimize count(1) for iceberg table
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnectorScanRangeSource.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW, 3.4, 3.5

#60014 [BugFix] Create temporary partitions bugfix + fix comparisons on Type.Date and Type.Datetime
  fe/fe-core/src/main/java/com/starrocks/analysis/DateLiteral.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PartitionDescAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/MultiRangePartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/PartitionValue.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
Labels: 3.3, 3.4, 3.5

#60076 [Enhancement] optimize log warning for table exist when create hive table
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: 3.3, 3.4, 3.5

#59886 [BugFix] fix PRangeCell compareTo.
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCellPlus.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/RangePartitionDiffer.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/SyncPartitionUtils.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PartitionKeyTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/PRangeCellPlusTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/PRangeCellTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/common/SyncPartitionBench.java
Labels: 3.3, 3.4, 3.5

#60111 [UT] Fix the unstable sql test case related to delta lake cache.
  test/sql/test_deltalake/R/test_deltalake_trace
  test/sql/test_deltalake/T/test_deltalake_trace
Labels: 3.3, 3.4, 3.5

#60005 [Enhancement] bump up breakpad to 2024.02.16 to fix crash in dump_syms
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/minidump/gen_minidump_symbols.sh
  thirdparty/patches/breakpad-2024.02.16.patch
  thirdparty/vars.sh
Labels: 3.5

#60132 [BugFix] fix initial tablet meta read when only provide full path
  be/src/storage/lake/filenames.h
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/starlet_location_provider_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
Labels: 3.5

#60141 [Doc] Doc for parquet.use_legacy_encoding
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/ja/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.3, 3.4, 3.5

#60173 [Doc] Fix doc typo for iceberg catalog
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4, 3.5

#60119 [BugFix] Fix unsupported nestloop null-aware left anti join
  be/src/column/column_helper.cpp
  be/src/column/column_helper.h
  be/src/exec/cross_join_node.cpp
  be/src/exec/join_hash_map.h
  be/src/exec/join_hash_map.tpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp
  be/src/exec/pipeline/nljoin/nljoin_probe_operator.h
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PushDownPredicateJoinTypeTest.java
  fe/fe-core/src/test/resources/sql/subquery/in-subquery.sql
  test/sql/test_join/R/test_null_aware_anti_join
  test/sql/test_join/T/test_null_aware_anti_join
Labels: 3.3, 3.4, 3.5

#60201 [Doc] add some description for some config
  docs/en/administration/management/BE_configuration.md
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-functions/JAVA_UDF.md
  docs/ja/administration/management/BE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
Labels: documentation, 3.4, 3.5

#60188 [BugFix] Fix mv is not inactive after column rename
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FileTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/MVActiveChecker.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  test/sql/test_mv/R/basic
Labels: 3.3, 3.4, 3.5

#60163 [BugFix] Fix child class loader of jni readers
  java-extensions/common-runtime/pom.xml
  java-extensions/hive-reader/pom.xml
  java-extensions/hive-reader/src/main/java/com/starrocks/hive/reader/HiveScannerFactory.java
  java-extensions/hudi-reader/pom.xml
  java-extensions/hudi-reader/src/main/java/com/starrocks/hudi/reader/HudiSliceScannerFactory.java
  java-extensions/iceberg-metadata-reader/pom.xml
  java-extensions/iceberg-metadata-reader/src/main/java/com/starrocks/connector/iceberg/IcebergMetadataScannerFactory.java
  java-extensions/java-utils/src/main/java/com/starrocks/utils/loader/ChildFirstClassLoader.java
  java-extensions/jni-connector/src/main/java/com/starrocks/jni/connector/ScannerHelper.java
  java-extensions/kudu-reader/pom.xml
  java-extensions/kudu-reader/src/main/java/com/starrocks/kudu/reader/KuduSplitScannerFactory.java
  java-extensions/paimon-reader/pom.xml
  java-extensions/pom.xml
Labels: 3.4, 3.5

#60222 [Doc] Fix the incorrect default value of enable_scan_datacache
  docs/en/sql-reference/System_variable.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.3, 3.4, 3.5

#60212 [BugFix] Fix incorect usage of jline.internal.Log as LOG
  fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/partition/PartitionSelector.java
Labels: 3.5

#60224 [BugFix] allow DECOMMISSION replica while loading to prevent publish failure
  fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/LocalTabletTest.java
Labels: 3.3, 3.4, 3.5

#60164 [BugFix] fix default_warehouse initialization in multiple scenarios
  fe/fe-core/src/main/java/com/starrocks/journal/GlobalStateCheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
Labels: 3.4, 3.5

#53060 [BugFix] Return error asap while executing ShortCircuitHybridScanNode.
  be/src/exec/short_circuit_hybrid.cpp
Labels: 3.2, 3.3, 3.4

#60262 [BugFix] Exclude mysql-connector-j from distribution
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: 3.5

#60190 [BugFix] Fix null pointer on transaction commit.
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 3.4, 3.5

#60291 [BugFix] Fix alter mv active bugs
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  test/lib/sr_sql_lib.py
  test/sql/test_mv/R/test_mv_with_schema_change_column_rename
  test/sql/test_mv/T/test_mv_with_schema_change_column_rename
Labels: 3.4, 3.5

#58909 [Enhancement] Introduce GC control by cluster snapshot info
  be/src/storage/lake/tablet_retain_info.cpp
  be/src/storage/lake/tablet_retain_info.h
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/tablet_retain_info_test.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW

#60292 [Doc] update FE configuration doc with a few shared-data items
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#60301 [UT] adding missing StorageVolumeProcNode test
  fe/fe-core/src/test/java/com/starrocks/common/proc/StorageVolumeProcNodeTest.java
Labels: 3.3, 3.4, 3.5

#60237 [Doc] New Benchmark Docs
  docs/docusaurus/sidebars.json
  docs/en/_assets/benchmark/SSB-SR.png
  docs/en/_assets/benchmark/TPC-DS-SR.png
  docs/en/benchmarking/SSB_Benchmarking.md
  docs/en/benchmarking/TPC_DS_Benchmark.md
  docs/ja/_assets/benchmark/SSB-SR.png
  docs/ja/_assets/benchmark/TPC-DS-SR.png
  docs/ja/benchmarking/SSB_Benchmarking.md
  docs/ja/benchmarking/TPC_DS_Benchmark.md
  docs/zh/_assets/benchmark/SSB-SR.png
  docs/zh/_assets/benchmark/TPC-DS-SR.png
  docs/zh/benchmarking/SSB_Benchmarking.md
  docs/zh/benchmarking/TPC_DS_Benchmark.md
Labels: documentation, 3.5

#60333 [Doc]Update feature-support-data-lake-analytics.md
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/ja/data_source/feature-support-data-lake-analytics.md
  docs/zh/data_source/feature-support-data-lake-analytics.md
Labels: documentation, 3.5

#60208 [BugFix] Fix prune unused predicate column bug
  be/src/exec/olap_common.cpp
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_prepare.cpp
  be/test/storage/conjunctive_predicates_test.cpp
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  test/sql/test_scan/test_pushdown_or_predicate/R/test_pushdown_and_rewrite_predicate
  test/sql/test_scan/test_pushdown_or_predicate/T/test_pushdown_and_rewrite_predicate
Labels: 3.3, 3.4, 3.5

#60332 [BugFix] Fixed the issue where the cache sharing function does not work in some cases due to incorrect node information acquisition.
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/CandidateWorkerProvider.java
Labels: 3.5

#60339 [BugFix] fix incorrect message shown from spill dir configuration
  be/src/exec/spill/dir_manager.cpp
  be/src/storage/options.cpp
  be/src/storage/options.h
  be/test/storage/options_test.cpp
Labels: 3.4, 3.5

#57287 [Feature] Add strpos function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/strpos.md
  docs/ja/sql-reference/sql-functions/string-functions/strpos.md
  docs/zh/sql-reference/sql-functions/string-functions/strpos.md
  gensrc/script/functions.py
  test/sql/test_string_functions/R/test_string_functions
  test/sql/test_string_functions/T/test_string_functions
Labels: documentation

#60341 [Enhancement] Plan advisor supports blacklist strategy
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanAdvisorExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/PlanTuningAdvisor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ApplyTuningGuideRule.java
  test/sql/test_feedback/R/test_agg_feedback
  test/sql/test_feedback/R/test_external_table_join_feedback
  test/sql/test_feedback/R/test_join_feedback
  test/sql/test_feedback/R/test_parameterized
  test/sql/test_feedback/T/test_agg_feedback
  test/sql/test_feedback/T/test_external_table_join_feedback
  test/sql/test_feedback/T/test_join_feedback
  test/sql/test_feedback/T/test_parameterized
Labels: 3.5

#60306 [BugFix] Mask credentials for iceberg REST catalog
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/credential/CredentialUtil.java
  fe/fe-core/src/test/java/com/starrocks/credential/CredentialUtilTest.java
Labels: 3.4, 3.5

#60228 [BugFix] Clean the stale datacache data to free disk spaces immediately.
  be/src/cache/block_cache/datacache_utils.cpp
  be/src/cache/block_cache/datacache_utils.h
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/test/cache/block_cache/block_cache_test.cpp
  be/test/cache/block_cache/datacache_utils_test.cpp
Labels: 3.5

#60335 [BugFix] group execution should not support bucket shuffle full-join
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupExecutionPlanTest.java
Labels: 3.3, 3.4, 3.5

#60365 [BugFix] merge project operator after rewriting `count(1)`
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveScanTest.java
Labels: 3.4, 3.5

#60386 [Doc] Remove conflicted desc
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE_AS_SELECT.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE_AS_SELECT.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE_AS_SELECT.md
Labels: documentation, 3.3, 3.4, 3.5

#60395 [Doc] Remove arrow flight from 3.4 RN
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.0.md
  docs/ja/release_notes/release-3.1.md
  docs/ja/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#60042 [Enhancement]Set the hive table owner to the qualified user
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetastoreApiConverter.java
Labels: behavior_changed, 3.3, 3.4, 3.5

#60368 [Refactor] enable skip pk preload by default
  be/src/common/config.h
  be/test/storage/lake/auto_increment_partial_update_test.cpp
  be/test/storage/lake/partial_update_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: behavior_changed

#60358 [Enhancement] adding -j syntax support to run-fe-ut.sh
  run-fe-ut.sh
Labels: 3.5

#60297 [BugFix] Prevent approx_cosine_similarity from Returning NaN When Input Vector Norm is Zero
  be/src/exprs/math_functions.cpp
Labels: 3.4, 3.5

#59993 [Feature] Introduce Column Hash Predicate as a Record Predicate for data filtering
  be/src/storage/CMakeLists.txt
  be/src/storage/record_predicate/column_hash_is_congruent.cpp
  be/src/storage/record_predicate/column_hash_is_congruent.h
  be/src/storage/record_predicate/record_predicate.h
  be/src/storage/record_predicate/record_predicate_helper.cpp
  be/src/storage/record_predicate/record_predicate_helper.h
  be/test/CMakeLists.txt
  be/test/storage/record_predicate/column_hash_is_congruent_test.cpp
  be/test/storage/record_predicate/record_predicate_helper_test.cpp
  gensrc/proto/lake_types.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#60352 [BugFix]Fix memory leaks due to PolicyRefresher thread leaks.
  fe/fe-core/src/main/java/com/starrocks/authorization/ranger/RangerAccessController.java
Labels: 3.3, 3.4, 3.5

#60425 [Doc] Add Doc for Compile Python
  docs/en/sql-reference/sql-functions/Python_UDF.md
  docs/ja/sql-reference/sql-functions/Python_UDF.md
  docs/zh/sql-reference/sql-functions/Python_UDF.md
Labels: documentation, 3.4, 3.5

#44033 [Enhancement] Support sqlblacklist for ctas
  docs/en/administration/management/resource_management/Blacklist.md
  docs/zh/administration/management/resource_management/Blacklist.md
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
Labels: documentation, feature

#60436 [Doc] Add missing comma in AuditLoader statement
  docs/en/administration/management/audit_loader.md
  docs/zh/administration/management/audit_loader.md
Labels: documentation, 3.5
