Repository StarRocks/starrocks, pull requests merged in 2025-07, with the labels that each got.

#60452 [Doc] Update release-3.3.md
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#60427 [Enhancement] remove the compatibility of backend HbResponse without reboot time
  fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java
Labels: 3.5

#60302 [Doc] reformat the CREATE TABLE doc
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
Labels: documentation, 3.3, 3.4, 3.5

#60448 [Doc] Update System_limit.md
  docs/zh/sql-reference/System_limit.md
Labels: documentation, 3.4, 3.5

#60442 [BugFix] Fix not predicate pushdown check
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
Labels: 3.3, 3.4, 3.5

#60348 [Feature] Add splitting and merging tablets info in the publish version rpc request for dynamic tablet splitting and merging
  gensrc/proto/lake_service.proto
  gensrc/proto/lake_types.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#60441 [BugFix] honor warehouse session variable for ANALYZE
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorAnalyzeTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalAnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/NativeAnalyzeJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectionTrigger.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsExecutorTest.java
Labels: behavior_changed

#60385 [Enhancement] use lower_bound/upper_bound to optimize min/max
  be/src/connector/hive_connector.cpp
  be/src/connector/hive_connector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/types/date_value.h
  fe/fe-core/src/main/java/com/starrocks/connector/GetRemoteFilesParams.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergConnectorScanRangeSource.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergUtil.java
  fe/fe-core/src/main/java/com/starrocks/planner/HdfsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergMetadataScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/OdpsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FeNameFormat.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ScanOptimizeOption.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MinMaxOptOnScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneScanColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveScanTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
  gensrc/thrift/Exprs.thrift
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_iceberg/R/test_iceberg_min_max_opt
  test/sql/test_iceberg/T/test_iceberg_min_max_opt
Labels: PROTO-REVIEW, 3.4, 3.5

#60481 [BugFix] Update stop script for CN
  bin/stop_cn.sh
Labels: 3.4, 3.5

#60497 [BugFix] Fix arrow flight crash when fetch from a not exist query_id
  be/src/exec/arrow_flight_batch_reader.cpp
  be/src/exec/arrow_flight_batch_reader.h
  be/src/service/service_be/arrow_flight_sql_service.cpp
  be/test/service/service_be/arrow_flight_call_header_utils_test.cpp
Labels: 3.4, 3.5

#60488 [Doc] v3.5.1 Release notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#60544 [Doc] Fix security integration type mistake in doc
  docs/en/administration/user_privs/authentication/oauth2_authentication.md
  docs/en/administration/user_privs/authentication/security_integration.md
  docs/ja/administration/user_privs/authentication/oauth2_authentication.md
  docs/ja/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/authentication/oauth2_authentication.md
  docs/zh/administration/user_privs/authentication/security_integration.md
Labels: documentation, 3.5

#60560 [Doc] Fix version Date
  docs/en/benchmarking/TPC_DS_Benchmark.md
  docs/ja/benchmarking/TPC_DS_Benchmark.md
  docs/zh/benchmarking/TPC_DS_Benchmark.md
Labels: documentation, 3.5

#60344 [BugFix] Fix window output partition propery
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ChildOutputPropertyGuarantor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/RequiredPropertyDeriver.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/SortProperty.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java
Labels: 3.3, 3.4, 3.5

#60574 [Doc] Align Docs for Updates in User Priv
  docs/en/administration/user_privs/authentication/ldap_authentication.md
  docs/en/administration/user_privs/authentication/security_integration.md
  docs/en/administration/user_privs/group_provider.md
  docs/ja/administration/user_privs/authentication/ldap_authentication.md
  docs/ja/administration/user_privs/authentication/security_integration.md
  docs/ja/administration/user_privs/group_provider.md
  docs/zh/administration/user_privs/authentication/ldap_authentication.md
  docs/zh/administration/user_privs/authentication/security_integration.md
  docs/zh/administration/user_privs/group_provider.md
Labels: documentation, 3.5

#60390 [BugFix] GC inverted index path after segment data deleted
  be/src/storage/data_dir.cpp
Labels: 3.3, 3.4, 3.5

#60514 [Doc] Add Arrow Flight SQL Doc
  docs/docusaurus/sidebars.json
  docs/en/_assets/arrow_flight.png
  docs/en/_assets/arrow_flight_example.png
  docs/en/unloading/arrow_flight.md
  docs/ja/_assets/arrow_flight.png
  docs/ja/_assets/arrow_flight_example.png
  docs/ja/unloading/arrow_flight.md
  docs/zh/_assets/arrow_flight.png
  docs/zh/_assets/arrow_flight_example.png
  docs/zh/unloading/arrow_flight.md
Labels: documentation, 3.5

#60449 [Feature] Introduce dynamic tablet job framework for dynamic tablet splitting and merging
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/DynamicTabletJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/dynamictablet/DynamicTabletJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/RemoveDynamicTabletJobLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockID.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/alter/dynamictablet/DynamicTabletJobMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
Labels: META-REVIEW

#60585 [UT] Fix missing invocation xxx for restore job test
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.4, 3.5

#60601 [BugFix] fix min/max bug on sql like 'select distinct x'
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MinMaxOptOnScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneScanColumnRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveScanTest.java
Labels: 3.5

#60584 [BugFix] Fix submit task with properties bugs
  docs/en/sql-reference/sql-statements/loading_unloading/ETL/SUBMIT_TASK.md
  docs/ja/sql-reference/sql-statements/loading_unloading/ETL/SUBMIT_TASK.md
  docs/zh/sql-reference/sql-statements/loading_unloading/ETL/SUBMIT_TASK.md
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SubmitTaskStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVTestBase.java
  test/sql/test_task/R/test_submit_task_with_properties
  test/sql/test_task/T/test_submit_task_with_properties
Labels: documentation, 3.3, 3.4, 3.5

#60621 [UT] Disable metric calculator in restore job test
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.4, 3.5

#60635 [UT] fix StarOSAgent unit test
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
Labels: 3.5

#60641 [Doc] correcting split_part function markdowns
  docs/en/sql-reference/sql-functions/string-functions/split_part.md
  docs/ja/sql-reference/sql-functions/string-functions/split_part.md
  docs/zh/sql-reference/sql-functions/string-functions/split_part.md
Labels: documentation

#60566 [BugFix] fix cloud native pk index memory statistic leak
  be/src/storage/lake/persistent_index_memtable.cpp
  be/src/storage/lake/persistent_index_memtable.h
  be/src/util/string_util.cpp
  be/src/util/string_util.h
  be/test/util/string_util_test.cpp
Labels: 3.3, 3.4, 3.5

#60602 [Enhancement] update staros to v3.5-rc2
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/pom.xml
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.5

#60614 [Enhancement]make access controller lazily
  fe/fe-core/src/main/java/com/starrocks/connector/LazyConnector.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CatalogStmtTest.java
Labels: 3.5

#60360 [Doc] Add best practice section to the docs
  docs/docusaurus/sidebars.json
  docs/en/_assets/best_practices/primary_key-1.png
  docs/en/_assets/best_practices/table_clustering-1.png
  docs/en/_assets/best_practices/table_clustering-2.png
  docs/en/best_practices/bucketing.md
  docs/en/best_practices/overview.md
  docs/en/best_practices/partitioning.md
  docs/en/best_practices/primarykey_table.md
  docs/en/best_practices/table_clustering.md
  docs/ja/_assets/best_practices/primary_key-1.png
  docs/ja/_assets/best_practices/table_clustering-1.png
  docs/ja/_assets/best_practices/table_clustering-2.png
  docs/ja/best_practices/bucketing.md
  docs/ja/best_practices/overview.md
  docs/ja/best_practices/partitioning.md
  docs/ja/best_practices/primarykey_table.md
  docs/ja/best_practices/table_clustering.md
  docs/zh/_assets/best_practices/primary_key-1.png
  docs/zh/_assets/best_practices/table_clustering-1.png
  docs/zh/_assets/best_practices/table_clustering-2.png
  docs/zh/best_practices/bucketing.md
  docs/zh/best_practices/overview.md
  docs/zh/best_practices/partitioning.md
  docs/zh/best_practices/primarykey_table.md
  docs/zh/best_practices/table_clustering.md
Labels: documentation, 3.3, 3.4, 3.5

#60673 [BugFix] fix compaction new segments does not clean by abort txn
  be/src/storage/lake/compaction_task.cpp
  be/test/storage/lake/rowset_test.cpp
Labels: 3.3, 3.4, 3.5

#60537 [BugFix] Fixed unchecked cast leading to CCE
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
Labels: 3.5

#60645 [Feature] Introduce predicate for sstable
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/key_to_chunk_converter.cpp
  be/src/storage/lake/key_to_chunk_converter.h
  be/src/storage/lake/sstable_predicate.cpp
  be/src/storage/lake/sstable_predicate.h
  be/test/CMakeLists.txt
  be/test/storage/lake/sstable_predicate_test.cpp
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#60174 [Enhancement] faster from_unixtime
  thirdparty/download-thirdparty.sh
  thirdparty/patches/cctz_civil_cache.patch
Labels: 3.5

#60730 [BugFix] make generated column replacement greedy, the larger wins
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/InPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReplaceScalarOperatorRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/GreedyGeneralizedColumnReplacementTest.java
Labels: 3.5

#60718 [Doc] Adjust prep for DMT
  docs/en/administration/data_migration_tool.md
  docs/ja/administration/data_migration_tool.md
  docs/zh/administration/data_migration_tool.md
Labels: documentation, 3.3, 3.4, 3.5

#60737 [Enhancement] disable colocate balancer and tablet scheduler in shared-data
  fe/fe-core/src/main/java/com/starrocks/clone/TabletChecker.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: 3.5

#60755 [BugFix] fix scheduler is null when stream load
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/JobSpecTest.java
Labels: 3.4, 3.5

#60757 [Doc] Update warehouse related documents
  docs/en/administration/management/audit_loader.md
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROCESSLIST.md
  docs/ja/administration/management/audit_loader.md
  docs/ja/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROCESSLIST.md
  docs/zh/administration/management/audit_loader.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROCESSLIST.md
Labels: documentation

#60772 [Doc] Delete Vector Index limits
  docs/en/table_design/indexes/vector_index.md
  docs/ja/table_design/indexes/vector_index.md
  docs/zh/table_design/indexes/vector_index.md
Labels: documentation, 3.4, 3.5

#60550 [BugFix] Fix incorrect matching when multiple global UDFs with the same name exist
  fe/fe-core/src/main/java/com/starrocks/catalog/GlobalFunctionMgr.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalFunctionMgrTest.java
Labels: 3.3, 3.4, 3.5

#60691 [Refactor] Refactor historical node manager by the compute node resource.
  fe/fe-core/src/main/java/com/starrocks/common/proc/HistoricalNodeProcNode.java
  fe/fe-core/src/main/java/com/starrocks/persist/UpdateHistoricalNodeLog.java
  fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/CandidateWorkerProvider.java
  fe/fe-core/src/main/java/com/starrocks/system/HistoricalNodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/HistoricalNodeProcNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/UpdateHistoricalNodeLogTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/HDFSBackendSelectorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/CandidateWorkerProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/system/HistoricalNodeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/system/SystemInfoServiceTest.java
Labels: META-REVIEW

#60787 [BugFix] remove trailing back slash in build script
  build.sh
Labels: 3.3, 3.4, 3.5

#60796 [UT] fix unstable ColocateTableBalancerTest
  fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
Labels: 3.3, 3.4, 3.5

#60664 [BugFix] fix multi_distinct_count crash caused by low_cardinality rewrite
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
  test/sql/test_low_cardinality/R/test_low_cardinality2
  test/sql/test_low_cardinality/T/test_low_cardinality2
Labels: 3.3, 3.4, 3.5

#60366 [Enhancement] Support different compaction strategy for different table in shared-data mode
  be/src/common/config.h
  be/src/storage/lake/compaction_policy.cpp
  be/src/storage/lake/compaction_policy.h
  be/src/storage/lake/primary_key_compaction_policy.cpp
  be/src/storage/lake/primary_key_compaction_policy.h
  be/src/storage/lake/schema_change.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/tablet_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/common/PropertyAnalyzerTest.java
  gensrc/proto/lake_types.proto
  gensrc/thrift/AgentService.thrift
Labels: META-REVIEW, PROTO-REVIEW

#60151 [Tool] Docker-Based Development Environment to build local code from any host environment
  Makefile.docker
  build-in-docker.sh
  docker-compose.dev.yml
  docker-dev.sh
  docs/en/developers/development-environment/dev-env-setup.md
Labels: documentation

#60741 [BugFix] Fix JVM crash bug caused by async-profiler
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.4, 3.5

#60823 [Doc] Fix Link to Code
  docs/en/developers/development-environment/dev-env-setup.md
Labels: documentation, 2.5, 3.1, 3.3, 3.4, 3.5

#60813 [UT] Fix UT java.lang.ClassCircularityError
  fe/fe-core/src/main/java/com/starrocks/common/util/UDFInternalClassLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateFunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CreateFunctionStmtAnalyzerTest.java
Labels: 3.4, 3.5

#60821 [Doc] Align Feature Support Doc for Data Lake
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/ja/data_source/feature-support-data-lake-analytics.md
Labels: documentation, 3.3, 3.4, 3.5

#60702 [BugFix] Fix aggregate key use random distribution
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateTableTest.java
  test/sql/test_random_distribution/R/test_random_distribution
  test/sql/test_random_distribution/T/test_random_distribution
Labels: behavior_changed, 3.3, 3.4, 3.5

#60726 [BugFix] fix stream load does not use correct CN group
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/ShowStreamLoadTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest2.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadTaskTest.java
Labels: META-REVIEW

#59759 [Enhancement] Implement missing HDFS filesystem operations for spilling support
  be/src/fs/hdfs/fs_hdfs.cpp
  be/src/util/hdfs_util.cpp
  be/src/util/hdfs_util.h
  be/test/fs/fs_hdfs_test.cpp
Labels: behavior_changed, 3.5

#60846 [Doc] update SQL
  docs/en/sql-reference/sql-statements/dictionary/CREATE_DICTIONARY.md
  docs/ja/sql-reference/sql-statements/dictionary/CREATE_DICTIONARY.md
  docs/zh/sql-reference/sql-statements/dictionary/CREATE_DICTIONARY.md
Labels: documentation, doc-feedback, 3.3, 3.4, 3.5

#60845 [BugFix] incorrect expression in zonemap filters
  be/src/formats/parquet/complex_column_reader.cpp
Labels: 3.4, 3.5

#60029 [Enhancement] prefer two-phase plan for distinct aggregation in single node env
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestBase.java
Labels: 3.5

#57574 [BugFix] Fix concurrent publish the same txn when enable batch publish in shared data
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.2, 3.3, 3.4, 3.5

#60266 [Enhancement] Avoid selecting dead backend or compute node when picking up backend
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/v2/vo/TabletView.java
  fe/fe-core/src/main/java/com/starrocks/lake/backup/LakeRestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/http/rest/v2/TablePartitionActionTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  fe/fe-core/src/test/java/com/starrocks/server/WarehouseManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplCreatePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedWarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseTest.java
Labels: 3.5

#60885 [Doc] Fix Jit Doc Bug
  docs/en/administration/management/BE_configuration.md
  docs/en/using_starrocks/jit.md
  docs/ja/administration/management/BE_configuration.md
  docs/ja/using_starrocks/jit.md
  docs/zh/administration/management/BE_configuration.md
  docs/zh/using_starrocks/jit.md
Labels: documentation, 3.3, 3.4, 3.5

#60886 [Doc] Update Table Types in Information Schema
  docs/en/sql-reference/information_schema/tables.md
  docs/ja/sql-reference/information_schema/tables.md
  docs/zh/sql-reference/information_schema/tables.md
Labels: documentation, 3.4, 3.5

#60873 [BugFix] Fix inconsistent implementations in url_extract_parameter
  be/src/util/url_parser.cpp
  test/sql/test_url_extract_parameter/R/test_url_extract_parameter
  test/sql/test_url_extract_parameter/T/test_url_extract_parameter
Labels: 3.3, 3.4, 3.5

#60843 [Enhancement] Support parquet version in files unload
  be/src/formats/parquet/parquet_file_writer.cpp
  be/src/formats/parquet/parquet_file_writer.h
  be/src/runtime/table_function_table_sink.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/Types.thrift
  test/sql/test_sink/R/test_files_sink_parquet_version
  test/sql/test_sink/T/test_files_sink_parquet_version
Labels: PROTO-REVIEW, 3.3, 3.4, 3.5

#60910 [BugFix] CVE fix, bump quartz version to 2.5.0
  fe/fe-core/pom.xml
Labels: 3.5

#60863 [BugFix] Change KEYWORD to WORD to comply with MySQL's standard definition
  be/src/exec/schema_scanner/schema_keywords_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/KeywordsSystemTable.java
  test/sql/test_information_schema/R/test_keywords
  test/sql/test_information_schema/T/test_keywords
Labels: behavior_changed, 3.4, 3.5

#60884 [Doc] Storage Volume supports Google Storage
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.5

#60830 [Feature] support manual compute node blacklist
  fe/fe-core/src/main/java/com/starrocks/qe/HostBlacklist.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddComputeNodeBlackListStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DelComputeNodeBlackListStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowComputeNodeBlackListStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/ComputeNodeBlacklistTest.java
Labels: behavior_changed

#60928 [Doc]Update oauth2_authentication.md
  docs/en/administration/management/FE_configuration.md
  docs/en/administration/user_privs/authentication/jwt_authentication.md
  docs/en/administration/user_privs/authentication/oauth2_authentication.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/administration/user_privs/authentication/jwt_authentication.md
  docs/ja/administration/user_privs/authentication/oauth2_authentication.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/administration/user_privs/authentication/jwt_authentication.md
  docs/zh/administration/user_privs/authentication/oauth2_authentication.md
Labels: documentation, 3.5

#59422 [Enhancement] Add version check in shared data
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.4, 3.5

#60801 [BugFix] Fix the isInternalStmt flag is missing bug when stmt is forward to leader
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/LeaderOpExecutorTest.java
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW, 3.4, 3.5

#60949 [BugFix] Fix txn log not exist when batch publish for shared-data arch
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
Labels: 3.3-merged, 3.3, 3.4, 3.5, 3.5-merged

#60974 [Doc] New Grafana Dashboard
  docs/en/administration/management/monitoring/Monitor_and_Alert.md
  docs/ja/administration/management/monitoring/Monitor_and_Alert.md
  docs/zh/administration/management/monitoring/Monitor_and_Alert.md
Labels: documentation, 3.3, 3.4, 3.5

#61017 [Doc] Config for JSON-formatted Profile
  docs/en/administration/management/FE_configuration.md
  docs/en/administration/query_profile_overview.md
  docs/ja/administration/management/FE_configuration.md
  docs/ja/administration/query_profile_overview.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/administration/query_profile_overview.md
Labels: documentation, 3.3, 3.4, 3.5

#61025 [Doc] 3.5 Downgrade Warning
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#61015 [BugFix] Make Python UDF error reporting clearer
  be/src/udf/python/env.cpp
  docs/en/sql-reference/sql-functions/Python_UDF.md
  docs/ja/sql-reference/sql-functions/Python_UDF.md
  docs/zh/sql-reference/sql-functions/Python_UDF.md
Labels: documentation, 3.4, 3.5

#60976 [Enhancement] Enable enable_materialized_view_agg_pushdown_rewrite by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTPCDSTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRefreshAndRewriteIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PushDownAggregationWithMVTest.java
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q10.sql
  fe/fe-core/src/test/resources/sql/materialized-view/tpch-hive/q3.sql
Labels: behavior_changed

#61033 [UT] Fix LakePublishBatchTest failure
  fe/fe-core/src/test/java/com/starrocks/transaction/LakePublishBatchTest.java
Labels: 3.3, 3.4, 3.5

#60840 [Enhancement] support map type in UDAF
  be/src/exprs/agg/java_udaf_function.h
  contrib/java-udf/pom.xml
  contrib/java-udf/src/main/java/com/starrocks/udf/NormalCdf.java
  contrib/java-udf/src/main/java/com/starrocks/udf/SumMap.java
  contrib/java-udf/src/main/java/com/starrocks/udf/SumMapInt64.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateFunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/CreateFunctionStmtAnalyzerTest.java
  test/sql/test_udf/R/test_jvm_udf
  test/sql/test_udf/T/test_jvm_udf
Labels: 3.5

#61021 [Enhancement] support uuid type in postgres
  be/src/types/checker/type_checker.h
  be/src/types/type_checker_manager.cpp
  java-extensions/jdbc-bridge/src/main/java/com/starrocks/jdbcbridge/JDBCScanner.java
  java-extensions/udf-extensions/src/main/java/com/starrocks/udf/UDFHelper.java
Labels: 3.5

#61016 [BugFix] fix starmgr's leader address
  fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java
Labels: 3.3, 3.4, 3.5

#61052 [Enhancement] FE supports to handle http request asynchronously (backport #59935)
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpServerHandler.java
  fe/fe-core/src/main/java/com/starrocks/http/IAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/test/java/com/starrocks/common/ThreadPoolManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/http/HttpServerHandlerTest.java
Labels: documentation

#60967 [Enhancement] Add future timeout for MVPrepareRelatedMVs
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MvRefreshArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessListPartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVTimelinessRangePartitionArbiter.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManyJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.5

#60743 [Enhancement] Filter out keys using SstablePredicate for sstable after compaction
  be/src/storage/CMakeLists.txt
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/persistent_index_sstable.cpp
  be/src/storage/record_predicate/column_hash_is_congruent.h
  be/src/storage/record_predicate/record_predicate.h
  be/src/storage/sstable/iterator.h
  be/src/storage/sstable/iterator_wrapper.h
  be/src/storage/sstable/merger.cpp
  be/src/storage/sstable/options.h
  be/src/storage/sstable/sstable_predicate.cpp
  be/src/storage/sstable/sstable_predicate.h
  be/src/storage/sstable/sstable_predicate_fwd.h
  be/src/storage/sstable/sstable_predicate_utils.cpp
  be/src/storage/sstable/sstable_predicate_utils.h
  be/src/storage/sstable/two_level_iterator.cpp
  be/test/CMakeLists.txt
  be/test/storage/lake/lake_persistent_index_test.cpp
  be/test/storage/sstable/sstable_predicate_test.cpp
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#61089 [BugFix] Executable segments generated by JIT are not released when it is evicted from JIT cache (backport #61027)
  be/src/common/config.h
  be/src/exprs/jit/jit_engine.cpp
  be/src/exprs/jit/jit_engine.h
  be/src/exprs/jit/jit_expr.cpp
  be/src/exprs/jit/jit_expr.h
  be/src/http/CMakeLists.txt
  be/src/http/action/jit_cache_action.cpp
  be/src/http/action/jit_cache_action.h
  be/src/service/service_be/http_service.cpp
  be/test/CMakeLists.txt
  be/test/exprs/jit_cache_test.cpp
Labels: automerge

#61096 [Doc] 3.5.2 Release Notes
  docs/en/release_notes/release-3.5.md
  docs/ja/release_notes/release-3.5.md
  docs/zh/release_notes/release-3.5.md
Labels: documentation

#61078 [BugFix] handle invalid column of ColumnUsage
  fe/fe-core/src/main/java/com/starrocks/catalog/Table.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ColumnStatsUsageSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/ColumnFullId.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/ColumnUsage.java
  fe/fe-core/src/main/java/com/starrocks/statistic/columns/PredicateColumnsStorage.java
  fe/fe-core/src/test/java/com/starrocks/statistic/columns/ColumnUsageTest.java
Labels: META-REVIEW, 3.5

#61080 [Doc] Add document for cache sharing ability.
  docs/en/_assets/cache_sharing_workflow.png
  docs/en/administration/management/FE_configuration.md
  docs/en/data_source/data_cache.md
  docs/en/sql-reference/System_variable.md
  docs/ja/_assets/cache_sharing_workflow.png
  docs/ja/administration/management/FE_configuration.md
  docs/ja/data_source/data_cache.md
  docs/ja/sql-reference/System_variable.md
  docs/zh/_assets/cache_sharing_workflow.png
  docs/zh/administration/management/FE_configuration.md
  docs/zh/data_source/data_cache.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation

#61112 [BugFix]Fix transaction stream load can not find the coordinator node.(backport #60154)
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/HttpMetricRegistry.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadCoordinatorMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/http/StarRocksHttpTestCase.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadCoordinatorMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/ShowStreamLoadTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: documentation

#61081 [Enhancement] Add balance type in cluster balance proc result
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
  fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedCtxTest.java
Labels: behavior_changed, 3.5

#57688 [Doc]Update CREATE_MATERIALIZED_VIEW.md
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/ja/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
Labels: documentation, 3.4, 3.5

#61102 [BugFix] set hit_count in vector index metrics
  be/src/util/system_metrics.cpp
Labels: behavior_changed, 3.4, 3.5

#60880 [BugFix] Fix NPE while missing setting globalStateMgr in `ConnectContext`
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ExecuteAsStmtTest.java
Labels: 3.3, 3.4, 3.5

#61124 [Enhancement] Use RangeDirectMapping to optimize hash join
  be/src/exec/hash_join_components.cpp
  be/src/exec/hash_join_components.h
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/join/join_hash_map.cpp
  be/src/exec/join/join_hash_map.h
  be/src/exec/join/join_hash_map.tpp
  be/src/exec/join/join_hash_map_method.h
  be/src/exec/join/join_hash_map_method.hpp
  be/src/exec/join/join_hash_table_descriptor.h
  be/src/exec/join/join_type_traits.h
  be/src/runtime/runtime_state.h
  be/src/util/bit_util.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/test/exec/join_hash_map_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_join/R/test_join_range_direct_mapping
  test/sql/test_join/T/test_join_range_direct_mapping
Labels: PROTO-REVIEW

#61153 [Doc] Fix jdbc catalog configuration description
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#60890 [BugFix] Fix alter job conflicts with partition creation.
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogUtilsTest.java
Labels: 3.3, 3.4, 3.5

#60970 [Enhancement] Optimize the select worker logic for CheckpointController
  fe/fe-core/src/main/java/com/starrocks/journal/CheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/leader/CheckpointController.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/Frontend.java
  fe/fe-core/src/test/java/com/starrocks/leader/CheckpointControllerTest.java
Labels: 3.5

#61159 [Doc] add upgrade notes regarding JRE and behavior change
  docs/en/deployment/upgrade.md
  docs/ja/deployment/upgrade.md
  docs/zh/deployment/upgrade.md
Labels: documentation, 3.3, 3.4, 3.5

#60985 [Refactor] Add WALApplier interface to apply in-memory change after WAL
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/WALApplier.java
Labels: META-REVIEW

#61183 [Doc] Best Practices for Authentication and Authorization
  docs/en/_assets/best_practices/_auth_comparison.mdx
  docs/en/_assets/best_practices/_auth_group_provider_example.mdx
  docs/en/_assets/best_practices/_auth_solution_3.mdx
  docs/en/_assets/best_practices/auth_feature.png
  docs/en/_assets/best_practices/auth_solution_1.png
  docs/en/best_practices/authentication_authorization.md
  docs/ja/_assets/best_practices/_auth_comparison.mdx
  docs/ja/_assets/best_practices/_auth_group_provider_example.mdx
  docs/ja/_assets/best_practices/_auth_solution_3.mdx
  docs/ja/_assets/best_practices/auth_feature.png
  docs/ja/_assets/best_practices/auth_solution_1.png
  docs/ja/best_practices/authentication_authorization.md
  docs/zh/_assets/best_practices/_auth_comparison.mdx
  docs/zh/_assets/best_practices/_auth_group_provider_example.mdx
  docs/zh/_assets/best_practices/_auth_solution_3.mdx
  docs/zh/_assets/best_practices/auth_feature.png
  docs/zh/_assets/best_practices/auth_solution_1.png
  docs/zh/best_practices/authentication_authorization.md
Labels: documentation, 3.5

#61205 [UT] Make sql test test_pipeline_level_runtime_filter stable
  test/sql/test_pipeline_level_runtime_filter/R/test_pipeline_level_runtime_filter
  test/sql/test_pipeline_level_runtime_filter/T/test_pipeline_level_runtime_filter
Labels: 3.3, 3.4, 3.5

#60746 [BugFix] Fix do schema change with partial MaterializedIndex
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  test/sql/test_rollup/R/test_lake_rollup
  test/sql/test_rollup/T/test_lake_rollup
Labels: 3.4, 3.5

#61212 [Doc] Default Resource Groups use cpu_weight
  docs/en/administration/management/resource_management/resource_group.md
  docs/ja/administration/management/resource_management/resource_group.md
  docs/zh/administration/management/resource_management/resource_group.md
Labels: documentation, 3.3, 3.4, 3.5

#60400 [Enhancement] Outer-Join Elimination for duplicate-insensitive aggreg…
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/OuterJoinEliminationRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/OuterJoinEliminationRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExplainTest.java
Labels: 3.3, 3.4, 3.5

#61218 [BugFix] fix TableMetricsMgrTest
  be/src/util/metrics.cpp
  be/src/util/table_metrics.h
Labels: 3.5

#61206 [BugFix] fix hour_from_unixtime
  be/src/exprs/time_functions.cpp
  be/test/exprs/time_functions_test.cpp
Labels: 3.5

#61150 [BugFix] fix deploy serialize pool block
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Deployer.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
Labels: 3.3, 3.4, 3.5

#61036 [BugFix] Fix array column cloning durign array comparison
  be/src/exec/sorting/compare_column.cpp
  be/test/exec/sorting_test.cpp
Labels: 3.4, 3.5

#61203 [BugFix] using ip address as the cache map key in FQDN mode
  fe/fe-core/src/main/java/com/starrocks/rpc/BrpcProxy.java
  fe/fe-core/src/test/java/com/starrocks/rpc/BrpcProxyTest.java
Labels: 3.3, 3.4, 3.5

#61083 [Enhancement] Improve error handling in TabletStatMgr and WarehouseManager
  fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
Labels: 3.5

#61285 [UT] fix array stats collection
  test/sql/test_collect_statistics/R/test_array_stats
  test/sql/test_collect_statistics/T/test_array_stats
Labels: 3.5

#61291 [Doc]Update authentication_authorization.md
  docs/en/best_practices/authentication_authorization.md
  docs/ja/best_practices/authentication_authorization.md
  docs/zh/best_practices/authentication_authorization.md
Labels: documentation, 3.5

#61281 [UT] fix unstable sql test
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  test/sql/test_refresh_statistics/R/test_refresh_statistics
  test/sql/test_refresh_statistics/T/test_refresh_statistics
Labels: 3.5

#61084 [BugFix] Fix a bug that agg_state_if will not handle the streaming aggregation cases
  be/src/exprs/agg/agg_state_if.h
  test/sql/test_agg_state/R/test_agg_filter.sql
  test/sql/test_agg_state/T/test_agg_filter.sql
Labels: 3.4, 3.5

#61286 [Doc] Doc Modifications for Cluster Snapshot
  docs/en/_assets/commonMarkdown/cluster_snapshot_term.mdx
  docs/en/_assets/commonMarkdown/cluster_snapshot_warning.mdx
  docs/en/_assets/commonMarkdown/manual_cluster_snapshot.mdx
  docs/en/administration/cluster_snapshot.md
  docs/ja/_assets/commonMarkdown/cluster_snapshot_term.mdx
  docs/ja/_assets/commonMarkdown/cluster_snapshot_warning.mdx
  docs/ja/_assets/commonMarkdown/manual_cluster_snapshot.mdx
  docs/ja/administration/cluster_snapshot.md
  docs/zh/_assets/commonMarkdown/cluster_snapshot_term.mdx
  docs/zh/_assets/commonMarkdown/cluster_snapshot_warning.mdx
  docs/zh/_assets/commonMarkdown/manual_cluster_snapshot.mdx
  docs/zh/administration/cluster_snapshot.md
Labels: documentation

#61309 [BugFix] Fix array_map crash when capture const array columns
  be/src/exprs/array_map_expr.cpp
  test/sql/test_array_fn/R/test_array_map_2
  test/sql/test_array_fn/T/test_array_map_2
Labels: 3.3, 3.4, 3.5

#61300 [BugFix] partition-statistics: load it fully async
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  test/sql/test_list_partition/R/test_list_partition_cardinality
  test/sql/test_list_partition/R/test_list_partition_selectivity
  test/sql/test_list_partition/T/test_list_partition_cardinality
  test/sql/test_list_partition/T/test_list_partition_selectivity
Labels: 3.3, 3.4, 3.5

#61271 [BugFix] fix the pruned column size to be same with the unpruned one
  be/src/storage/rowset/segment_iterator.cpp
Labels: 3.5

#61334 [UT] disable parquet asan long running ut
  be/test/formats/parquet/parquet_cli_reader_test.cpp
Labels: 3.5

#61356 [Doc]Update group_provider.md
  docs/en/administration/user_privs/group_provider.md
  docs/ja/administration/user_privs/group_provider.md
  docs/zh/administration/user_privs/group_provider.md
Labels: documentation, 3.5

#61347 [UT] fix compilation and be-ut
  be/src/common/status.h
  be/test/formats/parquet/parquet_cli_reader_test.cpp
Labels: 3.5

#61207 [BugFix] fix missing partition id in combine txnlog
  be/src/service/service_be/lake_service.cpp
  be/test/service/lake_service_test.cpp
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW

#61373 [BugFix] Fix global dictionary update error under shared-data
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnStateListener.java
Labels: 3.3, 3.4, 3.5

#61414 [Doc] Clarify Parameter Group
  docs/en/administration/user_privs/group_provider.md
  docs/ja/administration/user_privs/group_provider.md
  docs/zh/administration/user_privs/group_provider.md
Labels: documentation, 3.5

#61412 [UT] Fix test_merge_commit
  test/lib/sr_sql_lib.py
  test/sql/test_stream_load/R/test_merge_commit
  test/sql/test_stream_load/T/test_merge_commit
Labels: 3.4, 3.5

#61432 [UT] Fix some unstable mv tests
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
Labels: 3.5

#61427 [BugFix] Fix local-passthrough cause rpc to get stuck
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/sink_buffer.cpp
  be/src/exec/pipeline/exchange/sink_buffer.h
  be/test/exec/pipeline/exchange_pass_through_test.cpp
Labels: 3.5

#61371 [BugFix] Show Pipes by equal or like name.
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/pipe/ShowPipeStmt.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/PipeManagerTest.java
Labels: 3.3, 3.4, 3.5

#61465 [Enhancement] remove unnecessary compaction control log in shared-data
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionControlScheduler.java
Labels: 3.4, 3.5

#61476 [Doc] 3.3.17 Release Notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#61457 [Doc] Add a note to Dynamic Partition
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/en/table_design/data_distribution/dynamic_partitioning.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/ja/table_design/data_distribution/dynamic_partitioning.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/table_design/data_distribution/dynamic_partitioning.md
Labels: documentation, 3.3, 3.4, 3.5

#61241 [Doc] add iceberg transform doc
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/en/data_source/feature-support-data-lake-analytics.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/feature-support-data-lake-analytics.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/feature-support-data-lake-analytics.md
Labels: documentation

#56302 [Enhancement] ugprade zstd to v1.5.7
  thirdparty/download-thirdparty.sh
  thirdparty/patches/arrow-16.1.0-use-zstd-1.5.7.patch
  thirdparty/vars.sh
Labels: 3.5
