Repository StarRocks/starrocks, pull requests merged in 2025-02, with the labels that each got.

#55517 [Doc] correct dir
  docs/docusaurus/sidebars.json
Labels: documentation, 3.2, 3.3, 3.4

#54796 [Enhancement] Upgrade paimon sdk to 1.0 version
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/connector/CatalogConnectorMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/PaimonScanNodeTest.java
  java-extensions/paimon-reader/pom.xml
  trivy.yaml
Labels: 3.4

#55451 [Refactor]delete old way to deal with metadata in parquet reader
  be/src/common/config.h
  be/src/exec/hdfs_scanner.cpp
  be/src/formats/CMakeLists.txt
  be/src/formats/parquet/column_reader.cpp
  be/src/formats/parquet/column_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/file_reader.h
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/page_index_reader.cpp
  be/src/formats/parquet/page_index_reader.h
  be/src/formats/parquet/scalar_column_reader.cpp
  be/src/formats/parquet/scalar_column_reader.h
  be/src/formats/parquet/stored_column_reader_with_index.h
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/page_index_test.cpp
  be/test/formats/parquet/parquet_ut_base.cpp
  be/test/formats/parquet/parquet_ut_base.h
Labels: behavior_changed

#55240 [Doc] Modify the fe protocol description in this document
  docs/en/deployment/plan_cluster.md
  docs/en/introduction/Architecture.md
  docs/en/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
  docs/zh/deployment/plan_cluster.md
  docs/zh/introduction/Architecture.md
  docs/zh/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55226 [Doc] SHOW RESOURCE GROUP docfix
  docs/en/sql-reference/sql-statements/cluster-management/resource_group/SHOW_RESOURCE_GROUP.md
  docs/zh/sql-reference/sql-statements/cluster-management/resource_group/SHOW_RESOURCE_GROUP.md
Labels: documentation, 3.3, 3.4

#54889 [Doc]completed_task_count is a cumulative value and should not be used as the Excessive FE Thread Count Alert.
  docs/en/administration/management/monitoring/alert.md
  docs/zh/administration/management/monitoring/alert.md
Labels: documentation, 3.3, 3.4

#55235 [Enhancement] Disable load storage volume from fe.conf by default
  docker/dockerfiles/allin1/fe.conf
  docs/en/administration/management/FE_configuration.md
  docs/en/deployment/shared_data/azure.md
  docs/en/deployment/shared_data/gcs.md
  docs/en/deployment/shared_data/hdfs.md
  docs/en/deployment/shared_data/minio.md
  docs/en/deployment/shared_data/s3.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/deployment/shared_data/azure.md
  docs/zh/deployment/shared_data/gcs.md
  docs/zh/deployment/shared_data/hdfs.md
  docs/zh/deployment/shared_data/minio.md
  docs/zh/deployment/shared_data/other.md
  docs/zh/deployment/shared_data/s3.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java
Labels: documentation, 3.4

#55136 [Enhancement] Make lake compaction schedule interval configurable
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
Labels: 3.4

#55051 [Doc] Update sr_operator.md
  docs/en/deployment/sr_operator.md
  docs/zh/deployment/sr_operator.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53601 [Doc] Update Flink_connector.md
  docs/zh/unloading/Flink_connector.md
Labels: documentation, 3.3, 3.4

#53202 [Doc] Fix `SHOW USAGE RESOURCE GROUPS` document link
  docs/zh/administration/management/resource_management/resource_group.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55549 [BugFix] Fix drop partition miss lock bug
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
Labels: 3.3, 3.4

#55584 [Doc] Remove unnecessary Desc
  docs/en/integrations/data_lakes.mdx
  docs/zh/integrations/data_lakes.mdx
Labels: documentation, 3.2, 3.3, 3.4

#55563 [UT] Refactor shared-data ut code for warehouse related cases
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableAlterMetaJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeTableSchemaChangeJobTest.java
  fe/fe-core/src/test/java/com/starrocks/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ReplaceLakePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TabletStatMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/common/util/KafkaUtilTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeTableCleanerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgent2ndTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/pipe/filelist/FileListRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/SchemaScanNodeTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/StreamLoadPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoClusterTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskBuilderTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedWarehouseManager.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.2, 3.3, 3.4

#55353 [BugFix] fix the issue that TemporaryTableCleaner incorrectly cleaned up sessions
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableCleaner.java
  fe/fe-core/src/main/java/com/starrocks/server/TemporaryTableMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/com/starrocks/server/TemporaryTableCleanerTest.java
Labels: 3.3, 3.4

#55041 [Doc] fix case
  docs/en/quick_start/iceberg.md
  docs/en/quick_start/routine-load.md
  docs/en/quick_start/shared-data.md
  docs/en/quick_start/shared-nothing.md
Labels: documentation, 3.3, 3.4

#55548 [BugFix] Fix crash in RowsetUpdateStateTest.with_deletes
  be/src/storage/rowset/rowset_writer.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/rowset_update_state_test.cpp
Labels: 3.3, 3.4

#54832 [Enhancement] Refactor lake compaction task cancel checker in BE to ensure it can stop asap
  be/src/common/config.h
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/compaction_task_context.h
  be/test/storage/lake/compaction_scheduler_test.cpp
  be/test/storage/lake/compaction_task_context_test.cpp
  be/test/storage/lake/compaction_task_test.cpp
  be/test/storage/lake/lake_primary_key_consistency_test.cpp
  be/test/storage/lake/primary_key_compaction_task_test.cpp
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.2, 3.3, 3.4

#55630 [Doc] update post-deploy doc
  docs/en/deployment/post_deployment_setup.md
  docs/zh/deployment/post_deployment_setup.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55023 [Enhancement] make LIKE operations' statistics consistent
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticsCalculatorTest.java
Labels: 3.3, 3.4

#54787 [Enhancement] Support replication from another cluster with compaction enabled in shared-data mode
  be/src/agent/agent_task.cpp
  be/src/storage/lake/replication_txn_manager.cpp
  be/src/storage/lake/txn_log_applier.cpp
  be/test/storage/lake/replication_txn_manager_test.cpp
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationJob.java
  fe/fe-core/src/main/java/com/starrocks/replication/ReplicationTxnCommitAttachment.java
  fe/fe-core/src/main/java/com/starrocks/task/RemoteSnapshotTask.java
  fe/fe-core/src/main/java/com/starrocks/task/ReplicateSnapshotTask.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/replication/ReplicationJobTest.java
  fe/fe-core/src/test/java/com/starrocks/replication/ReplicationMgrTest.java
  gensrc/proto/types.proto
  gensrc/thrift/AgentService.thrift
Labels: META-REVIEW, PROTO-REVIEW, 3.3, 3.4

#53490 [Enhancement] add more metrics to help locate hotspot issues
  be/src/common/daemon.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/pipeline/pipeline_driver.cpp
  be/src/exec/pipeline/pipeline_driver.h
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/pipeline/pipeline_driver_executor.h
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/exec/pipeline/pipeline_driver_poller.h
  be/src/exec/pipeline/pipeline_driver_queue.cpp
  be/src/exec/pipeline/pipeline_driver_queue.h
  be/src/exec/pipeline/pipeline_metrics.cpp
  be/src/exec/pipeline/pipeline_metrics.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.h
  be/src/exec/spill/log_block_manager.cpp
  be/src/exec/spill/serde.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/exec/workgroup/pipeline_executor_set.cpp
  be/src/exec/workgroup/pipeline_executor_set.h
  be/src/exec/workgroup/scan_executor.cpp
  be/src/exec/workgroup/scan_executor.h
  be/src/exec/workgroup/work_group.cpp
  be/src/io/io_profiler.cpp
  be/src/io/io_profiler.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/service/staros_worker.cpp
  be/src/service/staros_worker.h
  be/src/storage/tablet.cpp
  be/src/util/CMakeLists.txt
  be/src/util/metrics.h
  be/src/util/starrocks_metrics.cpp
  be/src/util/starrocks_metrics.h
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/src/util/table_metrics.cpp
  be/src/util/table_metrics.h
  be/test/exec/pipeline/pipeline_driver_queue_test.cpp
  be/test/exec/pipeline/schedule/observer_test.cpp
  be/test/exec/workgroup/pipeline_executor_set_test.cpp
  be/test/exec/workgroup/scan_task_queue_test.cpp
Labels: 3.4

#55212 [BugFix] Fix transaction commit failed due to replica not found
  fe/fe-core/src/main/java/com/starrocks/transaction/OlapTableTxnStateListener.java
Labels: 3.1, 3.2, 3.3, 3.4

#55560 [Doc] Revise Python UDF doc
  docs/en/sql-reference/sql-functions/JAVA_UDF.md
  docs/en/sql-reference/sql-functions/Python_UDF.md
  docs/zh/sql-reference/sql-functions/Python_UDF.md
Labels: documentation, 3.4

#55592 [BugFix] Fix show create table with fk error
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/ForeignKeyConstraint.java
  fe/fe-core/src/main/java/com/starrocks/catalog/constraint/UniqueConstraint.java
  fe/fe-core/src/test/java/com/starrocks/catalog/ForeignKeyConstraintTest.java
Labels: 3.3, 3.4

#55656 [Enhancement] Lake compaction scheduler optimize in fe restart scenarios (backport #54881)
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateSnapshot.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: automerge, behavior_changed

#55388 [Enhancement] Lake compaction scheduler optimize in fe restart scenarios (backport #54881)
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: automerge, behavior_changed

#55605 [BugFix] Fix AlterTable operator not protected by meta lock
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PlannerMetaLocker.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstTraverser.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/RefreshTableStmt.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/UpdateDbUsedDataQuotaDaemon.java
Labels: 3.3, 3.4

#55667 [Enhancement] Add get_cluster_snapshot_restore_state rest api
  fe/fe-core/src/main/java/com/starrocks/http/HttpServer.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/GetClusterSnapshotRestoreStateAction.java
  fe/fe-core/src/test/java/com/starrocks/http/GetClusterSnapshotRestoreStateActionTest.java
Labels: 3.4

#55409 [BugFix] Fix string format in HyperLogLog::to_string
  be/src/types/hll.cpp
Labels: 3.4

#55164 [UT] Fix the problem that jmockit jar was not found in run-fe-ut.sh execution.
  fe/plugin-common/pom.xml
Labels: 3.2, 3.3, 3.4

#55331 [Feature] Support Mysql Field function
  be/src/exprs/string_functions.h
  be/test/CMakeLists.txt
  be/test/exprs/string_fn_field.cpp
  docs/en/sql-reference/sql-functions/string-functions/field.md
  docs/zh/sql-reference/sql-functions/string-functions/field.md
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java
  gensrc/script/functions.py
  test/sql/test_function/R/test_field
  test/sql/test_function/T/test_field
Labels: documentation

#55627 [Enhancement]generate new range faster
  be/src/storage/range.h
Labels: 3.3, 3.4

#55696 [Doc] fix the doc of parse_json function
  docs/en/sql-reference/data-types/semi_structured/JSON.md
  docs/zh/sql-reference/data-types/semi_structured/JSON.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55425 [Enhancement] subfield pushdown through table function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/SubfieldPushDownThroughTableFunctionTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/VectorIndexTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityArrayTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PruneComplexSubfieldTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55661 [BugFix] flatjson read notObject json crash
  be/src/util/json_flattener.cpp
  test/sql/test_json/R/test_string_json
  test/sql/test_json/T/test_string_json
Labels: 3.3, 3.4

#55682 [BugFix] correct repeatnode's output property
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OutputPropertyDeriver.java
Labels: 3.1, 3.2, 3.3, 3.4

#55703 [BugFix] fix incorrect statistics of spill dir capacity
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/log_block_manager.cpp
  be/test/io/spill_block_manager_test.cpp
Labels: 3.3, 3.4

#54959 [BugFix] Fix transaction stream load TXN_IN_PROCESSING error
  be/src/http/action/transaction_stream_load.cpp
  be/src/http/action/transaction_stream_load.h
  be/src/runtime/stream_load/stream_load_context.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/transaction_mgr.cpp
  be/test/http/transaction_stream_load_test.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#55698 [Enhancement] Add metrics to monitor unstable routine load jobs
  docs/en/administration/management/monitoring/alert.md
  docs/en/administration/management/monitoring/metrics.md
  docs/zh/administration/management/monitoring/alert.md
  docs/zh/administration/management/monitoring/metrics.md
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
Labels: documentation, 3.2, 3.3, 3.4

#55719 [Doc] Fix MV Refresh Desc
  docs/en/using_starrocks/async_mv/Materialized_view.md
  docs/zh/using_starrocks/async_mv/Materialized_view.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55695 [BugFix] fix the privilege issue DROP STATS command
  fe/fe-core/src/main/java/com/starrocks/load/DeleteMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/PhasedExecutionSchedule.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
Labels: 3.2, 3.3, 3.4

#55760 [Enhancement] Upgrade paimon version to 1.0.1
  fe/fe-core/pom.xml
  java-extensions/paimon-reader/pom.xml
Labels: 3.4

#55773 [BugFix] Fix stream load crash during schema change since open different schema in load job
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/test/java/com/starrocks/planner/OlapTableSinkTest.java
Labels: 3.3, 3.4

#55768 [BugFix] CTE pushdown limit&predicate error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushLimitAndFilterToCTEProduceRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55489 [UT] Fix unstable optimize sql test
  test/lib/sr_sql_lib.py
Labels: 3.3, 3.4

#55628 [Enhancement] Skip load primary index for empty rowset
  be/src/storage/lake/txn_log_applier.cpp
  be/src/storage/lake/update_manager.cpp
  be/src/storage/lake/update_manager.h
  be/test/storage/lake/alter_tablet_meta_test.cpp
Labels: 3.3, 3.4

#55662 [BugFix] Support non deterministic functions in transparent mv
  fe/fe-core/src/main/java/com/starrocks/catalog/MvPlanContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializedViewOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptConstFoldRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/NonDeterministicVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionWithExprListTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/DropPartitionWithExprRangeTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PCTRefreshListPartitionOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/OptConstFoldRewriterTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  test/sql/test_transparent_mv/R/test_transparent_mv_olap_part3
  test/sql/test_transparent_mv/T/test_transparent_mv_olap_part3
Labels: 3.4

#55756 [BugFix] Fix insert overwrite loss data since dynamic open partition
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
  fe/fe-core/src/main/java/com/starrocks/sql/InsertPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/InsertStmt.java
  test/sql/test_insert_overwrite/R/test_insert
  test/sql/test_insert_overwrite/T/test_insert
Labels: 3.3, 3.4

#55720 [Enhancement] Compatible with mariadb client for ldap user login
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
  fe/fe-core/src/main/java/com/starrocks/mysql/NegotiateState.java
Labels: 3.3, 3.4

#55495 [Doc] Add Generic Aggregate State Doc
  docs/en/table_design/table_types/aggregate_table.md
  docs/zh/table_design/table_types/aggregate_table.md
Labels: documentation, 3.4

#55490 [Enhancement] Stream load/routine support load channel profile
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/test/CMakeLists.txt
  be/test/exec/tablet_sink_index_channel_test.cpp
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryRuntimeProfileTest.java
  test/sql/test_profile/R/test_load_channel_profile
  test/sql/test_profile/T/test_load_channel_profile
  test/sql/test_profile/T/test_load_channel_profile_analysis.sh
Labels: 3.4

#55821 [Doc] Fix Desc in Iceberg Catalog
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4

#55825 [BugFix] missing ONCE_RESET in reset_state of agg streaming operator
  be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_sink_operator.cpp
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55835 [Doc] Fix latest version - part-2
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#55833 [Doc] Fix latest version - part-1
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#55838 [Enhancement] Set the default value of datacache_tiered_cache_enable to false
  be/src/block_cache/datacache_utils.cpp
  be/src/block_cache/datacache_utils.h
  be/src/common/config.h
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation

#55841 [Doc] Fix insert unload desc
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/unloading/unload_using_insert_into_files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/unloading/unload_using_insert_into_files.md
Labels: documentation, 3.2, 3.3, 3.4

#55868 [Doc] Fix datacache_enable default
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3, 3.4

#54941 [Enhancement] Support persistent configuration
  fe/fe-core/src/main/java/com/starrocks/common/ConfigBase.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AdminSetConfigStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/AdminSetConfigStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/com/starrocks/common/ConfigTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/AdaptiveChooseNodesTest.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/resources/conf/config_test.properties
  gensrc/thrift/FrontendService.thrift
Labels: behavior_changed, PROTO-REVIEW

#55883 [BugFix]Drop inexistent table silently(recover 50195)
  fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveMetadata.java
Labels: 3.3

#55859 [BugFix] Fix fail to do fast schema change on tables with sync mv in shared data
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletMetadataUpdateAgentTaskFactory.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.4

#55904 [Doc] Fix INSERT example
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55895 [UT]avoid bug on dropping hive table
  test/sql/test_hive/R/test_hive_catalog
  test/sql/test_hive/T/test_hive_catalog
Labels: 3.2, 3.3, 3.4

#55923 [UT] Fix ASAN compile error and unstable UT
  be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.h
  test/sql/test_topn_filter_throttle_scan/R/test_topn_filter_throttle_scan
  test/sql/test_topn_filter_throttle_scan/T/test_topn_filter_throttle_scan
Labels: 3.3, 3.4

#55909 [Doc] Fix INSERT example
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation

#55920 [Doc] 3.2.15 Release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#55787 [BugFix] Use PredicateSearchKey instead of PaimonFilter to avoid cache coherency problem
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonFilter.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
Labels: 3.4

#55902 [BugFix] Fix sort key being incorrectly set on rollup index meta in schema change
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: 3.2, 3.3, 3.4

#55947 [Doc] Fix admonitions syntax
  docs/en/sql-reference/sql-statements/loading_unloading/routine_load/STOP_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/routine_load/STOP_ROUTINE_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55358 [BugFix] Fix broker load profile credential leak
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
Labels: 3.3, 3.4

#55921 [UT] fix unstable mv tests
  fe/fe-core/src/test/java/com/starrocks/planner/ViewBaseMvRewriteOnTpcdsTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/OptimizerTaskTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTimeSeriesRewriteWithOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpForSharedDataTest.java
Labels: 3.4

#55980 [BugFix] Fix table state may not correct caused by LakeRollupJob
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
Labels: 3.4

#55248 [Enhancement] support lake table cache select in physical way
  be/src/common/config.h
  be/src/connector/lake_connector.cpp
  be/src/storage/options.h
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
Labels: 3.3, 3.4

#55965 [UT] Fix fe ut failed in shared-data mode
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedFrontend.java
Labels: 3.3, 3.4

#55968 [UT] [BugFix] Fix possible NPE querying task_runs schema table
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
Labels: 3.4

#55966 [BugFix] Fix array map over flow
  be/src/exprs/array_map_expr.cpp
Labels: 3.3, 3.4

#53099 [BugFix] Fix repeated migration of colocate tablets
  fe/fe-core/src/main/java/com/starrocks/clone/DiskAndTabletLoadReBalancer.java
Labels: 3.2, 3.3, 3.4

#55983 [BugFix] fix parquet column chunk reader when n is zero
  be/src/formats/parquet/stored_column_reader.cpp
Labels: 3.4

#56008 [BugFix] Fix the bug of jdbc catalog processing json type
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  test/sql/test_jdbc_catalog/R/test_json_type
  test/sql/test_jdbc_catalog/T/test_json_type
Labels: 3.3, 3.4

#55973 [BugFix] Fixed the bug that getWarhouse returns null and throws an exception and is used in a confusing way
  fe/fe-core/src/main/java/com/starrocks/authorization/WarehouseFCPEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/authorization/WarehousePEntryObject.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/sys/GrantsTo.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskInfo.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadInfo.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/server/WarehouseManager.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseProcDir.java
Labels: 3.3, 3.4

#55935 [BugFix] Fix iceberg result error when query multi identical tables which have equality delete file
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergGetRemoteFilesParams.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRemoteFileInfoSourceKey.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergRemoteSourceTrigger.java
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergTableMORParams.java
  fe/fe-core/src/main/java/com/starrocks/planner/IcebergScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalIcebergEqualityDeleteScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalIcebergEqualityDeleteScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalIcebergScanOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/IcebergEqualityDeleteRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/IcebergEqualityDeletePlanTest.java
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: 3.4

#55862 [Enhancement] Simplify the exception log
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java
Labels: 3.3, 3.4

#55951 [BugFix] Fix skew join mcv predicate doesn't cast
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SkewJoinOptimizeRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/MockHistogramStatisticStorage.java
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/histogram-stats/c_nationkey.json
Labels: 3.3, 3.4

#55882 [BugFix] Fix ConnectContext startTime not reset when retry broker load job
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: 3.2, 3.3, 3.4

#55808 [Enhancement] Optimize shard lock acquisition to reduce the holding time
  be/src/storage/tablet.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_manager.h
  be/test/storage/tablet_mgr_test.cpp
Labels: 3.2, 3.3, 3.4

#56047 [UT] Fix unstable test_mv_with_multi_partition_columns_iceberg1
  test/sql/test_transparent_mv/R/test_mv_with_multi_partition_columns_iceberg1
  test/sql/test_transparent_mv/T/test_mv_with_multi_partition_columns_iceberg1
Labels: 3.4

#55848 [BugFix] Fix sync mv can not be cancelled in shared data
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/MVTestUtils.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.4

#56029 [Doc] Fix broken links in 3.3 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#56005 [Refactor] Remove mysql block io code
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/quick_start/shared-data.md
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlChannel.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlServer.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlChannel.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/NMysqlServer.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/ReadListener.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/QeService.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlChannelTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlServerTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoFrontend.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/KillQueryHandleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: documentation

#55992 [Enhancement] support str_to_date/str2date partition prune
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
  test/sql/test_automatic_partition/R/test_automatic_partition
  test/sql/test_automatic_partition/R/test_partition_prune
  test/sql/test_automatic_partition/T/test_partition_prune
  test/sql/test_drop_partition/R/test_drop_partition_range_table_with_where
  test/sql/test_drop_partition/T/test_drop_partition_range_table_with_where
Labels: 3.4

#56053 [Enhancement] Estimate numWorkers of connector scan nodes for query queue
  fe/fe-core/src/main/java/com/starrocks/planner/ScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotEstimatorFactory.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/SlotEstimatorTest.java
Labels: 3.4

#56030 [BugFix] Index entry reference not decrease
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.2, 3.3, 3.4

#55993 [BugFix] Fx a JDBC metadata compatible bug
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/MysqlSchemaResolver.java
  fe/fe-core/src/main/java/com/starrocks/connector/jdbc/OracleSchemaResolver.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/MysqlSchemaResolverTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/jdbc/OracleSchemaResolverTest.java
Labels: 3.3, 3.4

#56001 [BugFix] Support text base mv rewrite for different dbs
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTestBase.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTextBasedRewriteTPCDSTest.java
Labels: 3.3, 3.4

#56065 [BugFix] fix rewrite `RewriteSimpleAggToHDFSScanRule` apply infinitely
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteSimpleAggToHDFSScanRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/HiveScanTest.java
Labels: 3.2, 3.3, 3.4

#55998 [UT] [BugFix] Fix mv unstable test cases
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvPlanContextBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTimeSeriesRewriteWithOlapTest.java
Labels: 3.3, 3.4

#55995 [BugFix] Fix show materialized view NPE bug
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
Labels: 3.3, 3.4

#56083 [UT] Fix unstable UT
  test/sql/test_iceberg/R/test_iceberg_view
  test/sql/test_iceberg/T/test_iceberg_view
Labels: 3.4

#55867 [BugFix] Use correct TabletReader::parse_seek_range for clould native table when tablet_internal_parallel is enabled
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/storage/base_tablet.h
  be/src/storage/lake/tablet.h
  be/src/storage/lake/tablet_reader.h
  be/src/storage/tablet.h
Labels: 3.3, 3.4

#56113 Revert "[BugFix] Index entry reference not decrease (backport #56030)"
  be/src/storage/primary_index.h
  be/src/storage/tablet_updates.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: title needs [type]

#56094 [BugFix] table fucntion's result used by common subexpression should not be eliminated
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TableFunctionTest.java
Labels: 3.3, 3.4

#56096 [BugFix] fix window function first_value/last_value with Shrinking Frame cause result error
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
Labels: 3.3, 3.4

#55933 [Enhancement] support configure show proc '/transactions' max entry count
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/TransProcDir.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/TransactionsProcTest.java
Labels: 3.2, 3.3, 3.4

#56114 [BugFix] skip the statistics database when decommission
  fe/fe-core/src/main/java/com/starrocks/alter/SystemHandler.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/DecommissionTest.java
Labels: 3.2, 3.3, 3.4

#56138 [Doc] 3.3.10 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#56125 [Feature] Support OIDC Security Integration
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/OIDCSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegrationFactory.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/GenericNameWithPropsPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/SecurityIntegrationPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SecurityIntegrationStatementAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/SecurityIntegrationTest.java
  test/sql/test_security_integration/R/test_security_integration
  test/sql/test_security_integration/T/test_security_integration
Labels: META-REVIEW

#55982 [Enhancement] Make exec_plan_fragment rpc timeout configable and add more metrics
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/com/starrocks/rpc/BrpcProxy.java
  fe/fe-core/src/main/java/com/starrocks/rpc/LakeServiceWithMetrics.java
  fe/fe-core/src/main/java/com/starrocks/rpc/PBackendServiceWithMetrics.java
  fe/fe-core/src/test/java/com/starrocks/metric/MetricRepoTest.java
  fe/fe-core/src/test/java/com/starrocks/rpc/LakeServiceWithMetricsTest.java
  fe/fe-core/src/test/java/com/starrocks/rpc/PBackendServiceWithMetricsTest.java
Labels: 3.3, 3.4

#44991 [BugFix] Fix table load metrics missing for transaction load
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/com/starrocks/transaction/GlobalTransactionMgrTest.java
Labels: 3.3

#55854 [BugFix]disable chunked upload in aws sdk while we have support it in poco
  thirdparty/download-thirdparty.sh
  thirdparty/patches/aws-cpp-sdk-1.11.267-disable-chunked-upload.patch
Labels: 3.4

#56165 [Enhancement] Support dynamic modification of automated_cluster_snapshot_interval_seconds and max_historical_automated_cluster_snapshot_jobs
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Daemon.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotCheckpointScheduler.java
Labels: 3.4

#56181 [Enhancement] staros worker build fs under no lock
  be/src/service/staros_worker.cpp
Labels: 3.2, 3.3, 3.4

#55899 [BugFix] Fix hive catalog parquet table daylight saving time issue caused by Int96ToDateTimeConverter use fixed offset to convert utc time to local time
  be/src/formats/parquet/column_converter.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/level_builder.h
  be/src/runtime/time_types.h
  be/test/column/date_value_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
Labels: behavior_changed, 3.3, 3.4

#56098 [BugFix] Fix snapshot was deleted by mistake after restore from it
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotCheckpointScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoredSnapshotInfo.java
  fe/fe-core/src/test/java/com/starrocks/lake/ClusterSnapshotTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgrTest.java
  fe/fe-core/src/test/resources/conf/cluster_snapshot2.yaml
Labels: META-REVIEW, 3.4

#56171 [BugFix] Fix can not modify column with sync mv in shared data
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
Labels: 3.4

#55764 [Enhancement] Optimize vacuum logic by adding vacuum version.
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartition.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW, 3.3, 3.4

#56206 [Enhancement] set page size to 25 for memtracker items
  be/src/http/default_path_handlers.cpp
Labels: behavior_changed, 3.3, 3.4

#55494 [Enhancement] Report load profile if brpc reaches timeout
  be/src/common/config.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/local_tablets_channel.cpp
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/service/service_be/internal_service.cpp
  be/src/service/service_be/internal_service.h
  be/src/util/internal_service_recoverable_stub.cpp
  be/src/util/internal_service_recoverable_stub.h
  be/test/exec/tablet_sink_index_channel_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/service/service_be/internal_service_test.cpp
  be/test/util/internal_service_recoverable_stub_test.cpp
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadErrorUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/QueryRuntimeProfile.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/JobSpec.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadErrorUtilsTest.java
  gensrc/proto/internal_service.proto
  test/sql/test_profile/R/test_load_brpc_reached_timeout
  test/sql/test_profile/R/test_load_channel_profile
  test/sql/test_profile/T/test_load_brpc_reached_timeout
  test/sql/test_profile/T/test_load_channel_profile
  test/sql/test_profile/T/test_load_profile_analysis.sh
  test/sql/test_profile/data/brpc_reached_timeout.csv
Labels: PROTO-REVIEW, 3.4

#56226 [UT] fix unstable mv tests
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
Labels: 3.4

#56216 [BugFix] fix io.netty CVE-2025-24970
  .trivyignore
  build.sh
  fe/fe-core/pom.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
  java-extensions/pom.xml
Labels: 3.2, 3.3, 3.4

#56153 [BugFix] fix inconsistent transaction process if exception thrown
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
Labels: 3.3, 3.4

#56217 [BugFix] fix rpc error for partitions_meta when partitions are too many
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp
  be/src/exec/schema_scanner/schema_partitions_meta_scanner.h
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_information_schema/R/test_partitions_meta
  test/sql/test_information_schema/T/test_partitions_meta
Labels: PROTO-REVIEW, 3.3, 3.4

#56168 [BugFix] do not forbid pushdown agg in 11MV
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PushDownAggregationWithMVTest.java
Labels: 3.4

#56195 [Enhancement] upgrade staros to version v3.4-rc4
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  thirdparty/starlet-artifacts-version.sh
  thirdparty/vars-aarch64.sh
  thirdparty/vars-ubuntu22-aarch64.sh
  thirdparty/vars-ubuntu22-x86_64.sh
  thirdparty/vars-x86_64.sh
Labels: 3.4

#56143 [BugFix] Fix complex expression partition prune
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/OperatorFunctionChecker.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ListPartitionPruner.java
  test/sql/test_automatic_partition/R/test_partition_prune
  test/sql/test_automatic_partition/T/test_partition_prune
Labels: 3.4

#55573 [Enhancement] Convert Trino function from_iso8601_timestamp -> timestamp
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: behavior_changed, 3.3, 3.4

#56257 [Enhancement] record audit stats for all statements
  fe/fe-core/src/main/java/com/starrocks/plugin/AuditEvent.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: 3.3, 3.4

#56291 [Doc] Update expression_partitioning.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation

#56263 [BugFix] Lake compaction scheduler might trigger redundant transaction which can cause CN crash
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
Labels: 3.2, 3.3, 3.4

#56305 [Doc] Yank v3.3.10
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#56319 [Doc] fix broken links
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation, 3.3, 3.4

#55917 [Doc] Detailed Syntax for adding fields to STRUCT
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation, 3.2, 3.3, 3.4

#56273 [BugFix] Fix the bug of incorrect updates in the vacuum version.
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
Labels: 3.3, 3.4

#55124 [Enhancement] pushdown join runtime filter into storage layer
  be/src/column/binary_column.cpp
  be/src/column/binary_column.h
  be/src/column/chunk.h
  be/src/column/column.h
  be/src/column/fixed_length_column_base.cpp
  be/src/column/fixed_length_column_base.h
  be/src/column/nullable_column.cpp
  be/src/column/nullable_column.h
  be/src/common/config.h
  be/src/exec/olap_scan_prepare.cpp
  be/src/exec/olap_scan_prepare.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.h
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/exprs/runtime_filter_layout.h
  be/src/formats/parquet/group_reader.cpp
  be/src/runtime/runtime_state.h
  be/src/storage/CMakeLists.txt
  be/src/storage/column_placeholder_predicate.h
  be/src/storage/column_predicate.h
  be/src/storage/column_predicate_cmp.cpp
  be/src/storage/column_predicate_rewriter.cpp
  be/src/storage/olap_common.h
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/rowset_options.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  be/src/storage/runtime_filter_predicate.cpp
  be/src/storage/runtime_filter_predicate.h
  be/src/storage/tablet_reader.cpp
  be/src/storage/tablet_reader_params.h
  be/test/exprs/runtime_filter_test.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
  test/sql/test_colocate/R/test_colocate
  test/sql/test_colocate/T/test_colocate
Labels: PROTO-REVIEW

#55804 [BugFix] Support cast constant time type to DateTime
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/operator/operator/ConstantOperatorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
Labels: 3.3, 3.4

#56256 [BugFix]get endpoint from vended credential to be compatible with minio
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
Labels: 3.4

#56330 [UT] give a try to fix FE RoutineLoadTaskSchedulerTest flaky test
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadTaskSchedulerTest.java
Labels: 3.4

#56266 [Enhancement] Wait apply finish out of tablet meta lock when set tablet state as SHUTDOWN
  be/src/storage/tablet.cpp
  be/src/storage/tablet_manager.cpp
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
Labels: 3.2, 3.3, 3.4

#56163 [Feature] Support Group Provider
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/FileGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/GroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/GroupProviderFactory.java
  fe/fe-core/src/main/java/com/starrocks/authentication/JwkMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/OpenIdConnectAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SecurityIntegrationFactory.java
  fe/fe-core/src/main/java/com/starrocks/authentication/UnixGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/GroupProviderLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/DDLStmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Analyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/GroupProviderStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/group/CreateGroupProviderStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/group/DropGroupProviderStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/group/ShowCreateGroupProviderStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/group/ShowGroupProvidersStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  test/sql/test_security_integration/R/test_group_provider
  test/sql/test_security_integration/T/test_group_provider
Labels: META-REVIEW

#56333 [BugFix] Fix security view miss SECURITY msg in `show create view`
  fe/fe-core/src/main/java/com/starrocks/authorization/ColumnPrivilege.java
  fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowCreateViewStmtTest.java
  test/sql/test_view/R/test_security_view
  test/sql/test_view/T/test_security_view
Labels: 3.4

#56318 [Enhancement] Reduce varchar cast inside date/datetime cast
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRuleTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ExpressionTest.java
Labels: 3.3, 3.4

#55886 [Enhancement] optimize the performace for topn with large offset
  be/src/bench/chunks_sorter_bench.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/chunks_sorter.cpp
  be/src/exec/chunks_sorter.h
  be/src/exec/chunks_sorter_heap_sort.h
  be/src/exec/chunks_sorter_topn.cpp
  be/src/exec/chunks_sorter_topn.h
  be/src/exec/pipeline/sort/local_partition_topn_context.cpp
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exec/sorting/merge.cpp
  be/src/exec/sorting/merge.h
  be/src/exec/sorting/merge_cascade.cpp
  be/src/exec/sorting/merge_column.cpp
  be/src/exec/topn_node.cpp
  be/test/exec/chunks_sorter_test.cpp
  be/test/runtime/merge_cascade_test.cpp
Labels: 3.3, 3.4

#56372 [UT] Fix unstable mv sql tests
  test/sql/test_transparent_mv/R/test_mv_with_multi_partition_columns_iceberg1
  test/sql/test_transparent_mv/R/test_mv_with_multi_partition_columns_iceberg2
  test/sql/test_transparent_mv/T/test_mv_with_multi_partition_columns_iceberg1
  test/sql/test_transparent_mv/T/test_mv_with_multi_partition_columns_iceberg2
Labels: 3.4

#56311 [Enhancement] Support at time zone expression for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoParserNotSupportTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoQueryTest.java
Labels: 3.2, 3.3, 3.4

#56324 [Doc] Fix code-style-guides' titles for protobuf and thrift.
  docs/en/developers/code-style-guides/protobuf-guides.md
  docs/en/developers/code-style-guides/thrift-guides.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#56166 [Enhancement] Support partial refresh in text based mv rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteOlapTest.java
Labels: 3.4

#56396 [Doc] adjust compaction doc for shared-data
  docs/en/administration/management/compaction.md
  docs/zh/administration/management/compaction.md
Labels: documentation, 3.3, 3.4

#56190 [Enhancement] support touch cache for CACHE SELECT
  be/src/fs/fs_starlet.cpp
  be/src/io/seekable_input_stream.h
  be/src/storage/rowset/segment_iterator.cpp
  be/test/fs/fs_starlet_test.cpp
Labels: 3.3, 3.4

#56406 [Enhancement] Support writing parquet json type when unloading data using FILES()
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/level_builder.h
  be/src/formats/parquet/parquet_file_writer.cpp
  be/test/formats/parquet/file_writer_test.cpp
  be/test/formats/parquet/parquet_file_writer_test.cpp
  test/sql/test_sink/R/test_files_sink_parquet_json
  test/sql/test_sink/T/test_files_sink_parquet_json
Labels: 3.3, 3.4

#56338 [BugFix] Fix files deleted incorrectly under cluster snapshot
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/ClusterSnapshotTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: META-REVIEW, 3.4
