Repository StarRocks/starrocks, pull requests merged in 2025-03, with the labels that each got.

#56429 [BugFix] fix connection leak of cost predictor
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/feature/CostPredictor.java
Labels: 3.4

#56262 [BugFix]json_query multi-dimension array flatten
  be/src/exprs/jsonpath.cpp
Labels: 3.3, 3.4

#56057 [BugFix] Fix getRemoteFiles error for paimon system table.
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.4

#55781 [Enhancement] Paimon partition pruning support cast predicate
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonPredicateConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonPredicateConverterTest.java
Labels: 3.3, 3.4

#55769 [Enhancement] Enhance observability in profile for paimon queries
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetricRegistry.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonRemoteFileDesc.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.3, 3.4

#55922 [Enhancement] Use input column statistics for computing IF min/max statistics
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/ExpressionStatisticsCalculatorTest.java
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q12.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q14.sql
  fe/fe-core/src/test/resources/sql/external/hive/tpch/q8.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q12.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q14.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q8.sql
Labels: 3.3, 3.4

#56443 [Enhancement] provide a faster but potentially wrong way to do timezone conversion
  be/src/common/config.h
  be/src/formats/parquet/column_converter.cpp
Labels: 3.4

#56430 [Enhancement] Mask sensitive information for azure adls2 storage volume
  fe/fe-core/src/main/java/com/starrocks/sql/common/AuditEncryptionChecker.java
Labels: 3.4

#56442 [BugFix] fix complex type subfield pruning on lambda function
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java
  test/sql/test_iceberg/R/test_iceberg_catalog_complex_type
  test/sql/test_iceberg/T/test_iceberg_catalog_complex_type
Labels: 3.1, 3.2, 3.3, 3.4

#55860 [BugFix] Introduce tablet_schema into MorselQueue for tablet_internal_parallel in clould native table
  be/src/exec/pipeline/scan/morsel.cpp
  be/src/exec/pipeline/scan/morsel.h
  be/src/exec/pipeline/scan/olap_scan_prepare_operator.cpp
  be/src/storage/lake/tablet_reader.cpp
Labels: 3.3, 3.4

#56354 [Enhancement]add Parse "20250225112345" to DateTime(#56339)
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DateUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/PartitionUtilTest.java
  test/sql/test_function/R/test_cast_string_to_datetime
Labels: 3.4

#56433 [UT] Refactor long time ut
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
Labels: 3.3, 3.4

#56493 [BugFix] Fix missing alter routine load job replay
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
Labels: META-REVIEW, 3.4

#56172 [BugFix] Fix materialized view originalViewDefineSql error
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: 3.4

#56515 [Doc] update prompt
  docs/ja/table_design/data_distribution/expression_partitioning.md
  docs/translation/en-to-ja-configs/system_prompt.txt
Labels: documentation, 3.4

#56462 [BugFix] fix complex type subfield pruning on lambda function for olap table
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldExpressionCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
Labels: 3.3, 3.4

#56467 [BugFix] "first_value" with "ignore nulls" and "rows between unbounded preceding and unbounded following result is wrong
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/WindowTest.java
  test/sql/test_window_function/R/test_basic_window_function
Labels: 3.3, 3.4

#56002 [Enhancement] turn on graceful exit loop by default
  be/src/common/config.h
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, behavior_changed, 3.4

#56356 [BugFix] Set timeout in TCreateTabletReq
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/com/starrocks/task/AgentTaskTest.java
Labels: 3.4

#56417 [BugFix] Fix insert overwrite job ConcurrentModificationException issue
  fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java
Labels: 3.2, 3.3, 3.4

#55802 [BugFix] Fix some odps bug
  fe/fe-core/src/main/java/com/starrocks/connector/odps/EntityConvertUtils.java
  fe/fe-core/src/main/java/com/starrocks/connector/odps/OdpsMetadata.java
  fe/fe-core/src/main/java/com/starrocks/planner/OdpsScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/MultiOpPattern.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsColumnValue.java
Labels: 3.4

#56512 [BugFix] Fix broker load set connection context
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadLoadingTaskTest.java
Labels: 3.1, 3.2, 3.3, 3.4

#56511 [BugFix] Fix online optimize table fail due to physical partition id changed
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/insert.sh
  test/sql/test_optimize_table/T/test_optimize_table
Labels: 3.4

#56062 [Enhancement] Support to pause routine load job on json parse error
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/src/exec/json_scanner.cpp
  be/test/exec/json_parser_test.cpp
  be/test/exec/json_scanner_test.cpp
  docs/en/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/ja/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/ErrorReason.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/TxnStatusChangeReason.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_routine_load/R/test_pause_on_fatal_parse_error
  test/sql/test_routine_load/R/test_show_create_routine_load
  test/sql/test_routine_load/T/test_pause_on_fatal_parse_error
Labels: documentation, 3.3, 3.4

#56502 [Doc]Correct some incorrect docker urls in ARM deployment.
  docs/en/deployment/prepare_deployment_files.md
  docs/zh/deployment/prepare_deployment_files.md
Labels: documentation, 3.3, 3.4

#56547 [BugFix] Fix MaterializedView's getQueryRewriteStatus cost too much time
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/mv/MVPlanValidationResult.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
Labels: 3.3, 3.4

#56244 [Enhancement] Use min_version of tablet to avoid vacuum throwing file not found exception
  be/src/storage/lake/vacuum.cpp
  be/test/storage/lake/vacuum_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/proc/LakeTabletsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTablet.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
  gensrc/proto/lake_service.proto
Labels: 3.2, PROTO-REVIEW, 3.3, 3.4

#56202 [Enhancement]add a config for low cardinality threshold
  be/src/exec/lake_meta_scanner.cpp
  be/src/exec/olap_meta_scanner.cpp
  be/src/exprs/agg/distinct.h
  be/src/exprs/agg/factory/aggregate_resolver_others.cpp
  be/src/formats/parquet/column_reader_factory.cpp
  be/src/formats/parquet/scalar_column_reader.cpp
  be/src/runtime/global_dict/parser.cpp
  be/src/runtime/global_dict/parser.h
  be/src/storage/column_predicate_rewriter.cpp
  be/src/storage/lake_meta_reader.cpp
  be/src/storage/meta_reader.cpp
  be/src/storage/meta_reader.h
  be/src/storage/olap_meta_reader.cpp
  be/src/storage/rowset/column_decoder.h
  be/src/storage/rowset/dictcode_column_iterator.cpp
  be/src/storage/rowset/dictcode_column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAggToMetaScanRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CacheDictManager.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/planner/TablePruningTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LowCardinalityTest2.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ScanTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/CacheRelaxDictManagerTest.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_agg_function/R/test_dict_merge
  test/sql/test_agg_function/T/test_dict_merge
  test/sql/test_external_file/R/test_parquet_dict_null_predicate
  test/sql/test_external_file/T/test_parquet_dict_null_predicate
  test/sql/test_fast_schema_evolution/R/test_fast_schema_evolution
  test/sql/test_fast_schema_evolution/T/test_fast_schema_evolution
Labels: PROTO-REVIEW

#55757 [Enhancement] Support paimon cbo and analyzer
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/Partition.java
  fe/fe-core/src/main/java/com/starrocks/connector/partitiontraits/PaimonPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: 3.4

#56415 [Enhancement] Optimize Database Quota statistics to reduce lock usage time
  fe/fe-core/src/main/java/com/starrocks/catalog/Database.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/AutoCloseableLock.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/server/DatabaseQuotaRefresher.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/UpdateDbUsedDataQuotaDaemon.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/AutoCloseableLockerTest.java
  fe/fe-core/src/test/java/com/starrocks/server/DatabaseQuotaRefresherTest.java
Labels: 3.3, 3.4

#56594 [BugFix] Fix warehouse not set when creating cloud native sync mv
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableRollupBuilder.java
  fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeRollupJobTest.java
Labels: 3.4

#56558 [BugFix] Fix mv refresh with warehouse
  fe/fe-core/src/main/java/com/starrocks/load/pipe/Pipe.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/ExecuteOption.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRun.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunBuilder.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/persist/MVTaskRunExtraMessage.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/benchmark/TaskSchedulerBench.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunFIFOQueueTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/TaskRunSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/history/TaskRunHistoryTest.java
Labels: 3.4

#55785 [Enhancement] Support paimon show partitions
  fe/fe-core/src/main/java/com/starrocks/common/proc/ExternalTableProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PaimonTablePartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/Partition.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowPartitionsStmt.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/PaimonPartitionsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/ConnectorPartitionTraitsTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.4

#56606 [BugFix] Fix files() view lost credential
  fe/fe-core/src/main/java/com/starrocks/catalog/View.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewAnalyzer.java
  test/sql/test_view/R/test_files_view
  test/sql/test_view/T/test_files_view
Labels: 3.2, 3.3, 3.4

#55559 [Enhancement]Add partition offset lag column in show routine load and information_schema.routine_load_jobs
  be/src/exec/schema_scanner/schema_routine_load_jobs_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/RoutineLoadJobsSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowRoutineLoadStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/ShowRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/PulsarRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  gensrc/thrift/FrontendService.thrift
  test/sql/test_routine_load/R/test_offset_lag
  test/sql/test_routine_load/T/test_offset_lag
Labels: 3.2, PROTO-REVIEW, 3.3, 3.4

#56616 [BugFix] fix min/max profile counter
  be/src/util/runtime_profile.cpp
  fe/fe-core/src/main/java/com/starrocks/common/util/Counter.java
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/common/util/RuntimeProfileTest.java
Labels: 3.3, 3.4

#56628 [BugFix] Avoid potential coordinator leak for query (backport #56596)
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
Labels: automerge

#56653 [BugFix] Reset index information when creating tablet in rollup job (backport #56553)
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/test/java/com/starrocks/catalog/OlapTableTest.java
Labels: META-REVIEW

#56607 [Doc] Add Doc for iceberg jdbc catalog
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation

#56577 [Enhancement] Support to pause routine load job on json parse error (backport #56062)
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/src/exec/json_scanner.cpp
  be/test/exec/json_parser_test.cpp
  be/test/exec/json_scanner_test.cpp
  docs/en/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/ja/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/ErrorReason.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/TxnStatusChangeReason.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_routine_load/R/test_pause_on_fatal_parse_error
  test/sql/test_routine_load/R/test_show_create_routine_load
  test/sql/test_routine_load/T/test_pause_on_fatal_parse_error
Labels: documentation

#56578 [Enhancement] Support to pause routine load job on json parse error (backport #56062)
  be/src/exec/json_parser.cpp
  be/src/exec/json_parser.h
  be/src/exec/json_scanner.cpp
  be/test/exec/json_parser_test.cpp
  be/test/exec/json_scanner_test.cpp
  docs/en/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/ja/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/routine_load/CREATE_ROUTINE_LOAD.md
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/ErrorReason.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/PulsarRoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/TxnStatusChangeReason.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/routineload/RoutineLoadJobTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_routine_load/R/test_pause_on_fatal_parse_error
  test/sql/test_routine_load/R/test_show_create_routine_load
  test/sql/test_routine_load/T/test_pause_on_fatal_parse_error
Labels: documentation

#56431 [BugFix] Fix the issue of cache select for JNI scanner
  be/src/exec/cache_select_scanner.cpp
  be/test/CMakeLists.txt
  be/test/exec/cache_select_scanner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/planner/PaimonScanNodeTest.java
Labels: 3.3, 3.4

#56613 [BugFix] Fix recycle bin missing to delete lake mv's expired partitions after mv refreshed
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/test/java/com/starrocks/lake/LakeMaterializedViewTest.java
Labels: 3.3, 3.4

#56671 [BugFix] fix partition stats healthy
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/statistic/BasicStatsMetaTest.java
Labels: 3.3, 3.4

#56696 [UT] Fix sql tester test_materialized_view_refresh_with_many_to_many case
  test/sql/test_materialized_view/R/test_materialized_view_refresh_with_many_to_many
  test/sql/test_materialized_view/T/test_materialized_view_refresh_with_many_to_many
Labels: 3.4

#56672 [Enhancement] Fix some mv related noisy logs
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/TaskRunScheduler.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java
Labels: 3.3, 3.4

#56702 [Doc] 3.3.11 Release notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#56649 [Enhancement] add random compaction strategy for chaos test
  be/src/common/config.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
  be/test/storage/tablet_updates_test.h
Labels: 3.3, 3.4

#56703 [Enhancement] Improve query timeout message
  be/src/exec/pipeline/pipeline_driver_poller.cpp
  be/src/exec/pipeline/schedule/timeout_tasks.cpp
  test/sql/test_insert_empty/R/test_insert_timeout
Labels: 3.4

#56426 [Enhancement] support short-job-first query schedule strategy
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/LogicalSlot.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/QueryQueueOptions.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/ShortJobFirstAlgo.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotScheduleAlgorithm.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/ShortJobFirstAlgoTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/slot/SlotSelectionStrategyV2Test.java
Labels: 3.4

#56684 [Enhancement] mask credentials in FILES
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/FileTableFunctionRelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/AuditEncryptionChecker.java
  fe/fe-core/src/test/java/com/starrocks/sql/ast/DescribeStmtTest.java
Labels: 3.3, 3.4

#56712 [UT] Fix lake tablet manager UT
  be/test/storage/lake/tablet_manager_test.cpp
Labels: 3.4

#56722 [Enhancement] cache hive metastore client in kudu connector
  fe/fe-core/src/main/java/com/starrocks/connector/kudu/KuduConnector.java
Labels: 3.2, 3.3, 3.4

#56693 [Enhancement] add metrics for statistics collect jobs
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalFullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalHistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/ExternalSampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/FullStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HyperStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/SampleStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJob.java
Labels: 3.4

#56726 [Enhancement] Resolve absl conflicts between staros and opentelemetry
  be/src/common/tracer.h
  be/src/common/tracer_fwd.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/storage/delta_writer.cpp
  be/src/storage/delta_writer.h
Labels: 3.4

#56638 [Doc] Add more swap table docs
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation, 3.4

#56362 [BugFix] Table name should always use default catalog when showing mv
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowMaterializedViewsStmt.java
Labels: 3.3, 3.4

#56745 [BugFix] Fix replay external table stats meta takes long time
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
Labels: 3.2, 3.3, 3.4

#56694 [Enhancement] remove redundant star client init
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
Labels: 3.3, 3.4

#56715 [Enhancement] use multi-column stats to estimate agg node cardinality
  be/src/runtime/statistic_result_writer.cpp
  be/src/runtime/statistic_result_writer.h
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/StatisticsUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/MultiColumnCombinedStatistics.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/MultiColumnCombinedStats.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/MultiColumnCombinedStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalcUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/MultiColumnStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregatePushDownWithCostTest.java
  test/sql/test_analyze_statistics/R/test_multi_column_stats
  test/sql/test_analyze_statistics/T/test_multi_column_stats
Labels: META-REVIEW

#56544 [Doc]rename configuartion to take charge of all query-trigger tasks
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorTableTriggerAnalyzeMgr.java
Labels: documentation, 3.4

#56761 [BugFix] Only check users' defined uk/fk constraints to be compatible with old versions
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  test/sql/test_ddl/R/test_alter_swap_table
  test/sql/test_ddl/T/test_alter_swap_table
Labels: 3.3, 3.4

#56762 [UT] Fix unstable sql test
  test/sql/test_automatic_partition/R/test_partition_prune
  test/sql/test_automatic_partition/T/test_partition_prune
  test/sql/test_optimize_table/R/test_optimize_table
  test/sql/test_optimize_table/T/test_optimize_table
Labels: 3.4

#56565 [Enhancement] Convert sql function parse_datetime(...) to str_to_jodatime(...) with accepting 'T' and 'Z' in format for Trino transformer when sql_dialect='trino'
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/ComplexFunctionCallTransformer.java
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: behavior_changed, 3.3, 3.4

#56678 [Doc] add document for running queries
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/en/using_starrocks/running_queries.md
  docs/ja/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/ja/using_starrocks/running_queries.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_PROC.md
  docs/zh/using_starrocks/running_queries.md
Labels: documentation, 3.2, 3.3, 3.4

#56776 [Doc]rename configuartion to take charge of all query-trigger tasks (backport #56544)
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorTableTriggerAnalyzeMgr.java
Labels: documentation

#56767 [BugFix] Fix partition_retention_condition ttl scheduler bug
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/clone/PartitionTTLScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/test/java/com/starrocks/clone/DynamicPartitionSchedulerTest.java
Labels: 3.4

#56677 [BugFix] set defaultTableLocation to null when create iceberg view for rest catalog
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergRESTCatalogTest.java
Labels: 3.4

#56787 [BugFix] fix rowset verify
  be/src/storage/rowset/rowset.cpp
Labels: 3.3, 3.4

#55788 [Enhancement] Support Paimon manifest cache
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/connector/hive/ConnectorTableMetadataProcessor.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonConnector.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.4

#56106 [Feature] Support graceful exit for FE
  bin/stop_be.sh
  bin/stop_fe.sh
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/ha/StateChangeExecutor.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/ExecuteSqlAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/HealthAction.java
  fe/fe-core/src/main/java/com/starrocks/journal/DrainingJournalTask.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalTask.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java
  fe/fe-core/src/main/java/com/starrocks/journal/LeaderTransferException.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/ReadListener.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/LeaderOpExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ProxyContextManager.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/GracefulExitFlag.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentTaskQueue.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectProcessorTest.java
Labels: META-REVIEW

#56585 [Enhancement]DateUtil probeFormat parse Unsigned second-level date
  fe/fe-core/src/main/java/com/starrocks/common/util/DateUtils.java
  fe/fe-core/src/test/java/com/starrocks/common/util/DateUtilsTest.java
Labels: 3.4

#56822 [Enhancement] add stack trace when thread pool create thread failed
  be/src/util/threadpool.cpp
Labels: 3.3, 3.4

#56799 [Enhancement] try to only use lhs/rhs for select_if
  be/src/exprs/condition_expr.cpp
  be/src/simd/selector.h
Labels: 3.3, 3.4

#56810 [BugFix] Fix array contains reuse null column
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.tpp
  test/sql/test_array_fn/R/test_array_contains
  test/sql/test_array_fn/T/test_array_contains
Labels: 3.3, 3.4

#56695 [BugFix] Fix data unconsistent if add a new generated column which ref a normal column which contains cols file for pk table
  be/src/storage/rowset/rowset.cpp
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: 3.3, 3.4

#56732 [Enhancement] fix jprotobuf-precompile-plugin not work with scope provided
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: 3.4

#56212 [Enhancement] support alter hive/hudi catalog's properties
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/catalog/AlterCatalogTest.java
Labels: behavior_changed, 3.3, 3.4

#56848 [Doc] 3.4.1 release notes
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#56546 [Enhancement] Support automatically choosing the latest automated cluster snapshot to restore
  conf/cluster_snapshot.yaml
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgr.java
Labels: 3.4

#56850 [Doc] Files supports list_recursively
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/ja/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.4

#56665 [Doc] Not support modify multiple table properties
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#56857 [Doc] Expression Partition FAQ
  docs/en/faq/Others.md
  docs/ja/faq/Others.md
  docs/zh/faq/Others.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#56465 [Doc] Add FE memory FAQ
  docs/en/_assets/fe_mem_faq_1.png
  docs/en/_assets/fe_mem_faq_2.png
  docs/en/faq/fe_mem_faq.md
  docs/ja/_assets/fe_mem_faq_1.png
  docs/ja/_assets/fe_mem_faq_2.png
  docs/ja/faq/fe_mem_faq.md
  docs/zh/_assets/fe_mem_faq_1.png
  docs/zh/_assets/fe_mem_faq_2.png
  docs/zh/faq/fe_mem_faq.md
Labels: documentation, 3.3, 3.4

#56668 [Doc] Fix inverted index example
  docs/en/table_design/indexes/inverted_index.md
  docs/ja/table_design/indexes/inverted_index.md
  docs/zh/table_design/indexes/inverted_index.md
Labels: documentation, 3.3, 3.4

#56870 [Enhancement] support alter hive/hudi catalog's properties (backport #56212)
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java
  fe/fe-core/src/test/java/com/starrocks/catalog/AlterCatalogTest.java
Labels: behavior_changed

#56879 [BugFix] Fix Paimon TimeStamp timezone converter problem
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonPredicateConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonPredicateConverterTest.java
Labels: 3.3, 3.4

#56878 [Enhancement] Add jni and dv metrics for paimon queries
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
Labels: 3.3, 3.4

#56860 [BugFix] Fix vector index not found
  be/src/storage/snapshot_manager.cpp
  be/src/storage/tablet_schema.cpp
Labels: 3.4

#56805 [Enhancement] Enable enable_materialized_view_multi_stages_rewrite by default
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerTraceUtil.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryMaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MVCorrelation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewWrapper.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteStrategy.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewHiveTPCHTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewWithPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePreprocessorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/PushDownAggregationWithMVTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPushAggTest.java
  test/sql/test_materialized_view/R/test_mv_reasoning
  test/sql/test_materialized_view_rewrite/R/test_mv_rewrite_with_time_series_multi_mvs
  test/sql/test_materialized_view_rewrite/T/test_mv_rewrite_with_time_series_multi_mvs
Labels: 3.3, 3.4

#56929 [BugFix] Remove deprecated annotation in proto to avoid compiler warning
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW, 3.3, 3.4

#56927 [BugFix] TableFunction output empty after elimination
  be/src/exec/pipeline/table_function_operator.cpp
  test/sql/test_table_function_elimination/R/test_table_function_elimination
  test/sql/test_table_function_elimination/T/test_table_function_elimination
Labels: 3.2, 3.3, 3.4

#56912 [Enhancement] MV support partition compensation for paimon table.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
Labels: 3.3, 3.4

#56922 [Enhancement] upgrade to spark 3.5 to fix CVE
  fe/pom.xml
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
  trivy.yaml
Labels: 3.3, 3.4

#56949 [BugFix] Disable collect stats/profile in mv refresh by default
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapTest.java
Labels: behavior_changed, 3.3, 3.4

#56970 [Doc] Add JA Secure View
  docs/ja/sql-reference/sql-statements/View/CREATE_VIEW.md
Labels: documentation, 3.4

#56874 [Enhancement] FE sends node type along with heartbeat to BE/CN
  be/src/agent/heartbeat_server.cpp
  be/test/agent/heartbeat_server_test.cpp
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  gensrc/thrift/HeartbeatService.thrift
  gensrc/thrift/Types.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.4

#56886 [BugFix] Fix the issue the JDBC tables which contains `$` character in table name are treated as iceberg metadata tables.
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataTableName.java
  fe/fe-core/src/test/java/com/starrocks/server/MetadataMgrTest.java
Labels: 3.3, 3.4

#56856 [BugFix]no sensitive info exposed when show create jdbc table
  fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java
  fe/fe-core/src/main/java/com/starrocks/planner/JDBCScanNode.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorJdbcTest.java
  test/sql/test_jdbc_catalog/R/test_json_type
  test/sql/test_jdbc_catalog/T/test_json_type
Labels: 3.4

#56997 [UT] Fix unstable test_materialized_view_refresh_with_many_to_many test case
  test/sql/test_materialized_view/R/test_materialized_view_refresh_with_many_to_many
  test/sql/test_materialized_view/T/test_materialized_view_refresh_with_many_to_many
Labels: 3.3, 3.4

#56813 [Enhancement] add probe memory limit before building partition hash table
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_probe_operator.h
  be/src/exec/spill/options.h
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#56788 [Enhancement] Add groovy unix socket debug server
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteScriptExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/GroovyUDSServer.java
  fe/fe-core/src/test/java/com/starrocks/service/GroovyUDSServerTest.java
Labels: 3.4

#50073 [Feature] Support Skew join Plan Rewrite
  fe/fe-core/src/main/java/com/starrocks/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java
  fe/fe-core/src/main/java/com/starrocks/common/LocalExchangerType.java
  fe/fe-core/src/main/java/com/starrocks/common/util/ProfilingExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/planner/DataPartition.java
  fe/fe-core/src/main/java/com/starrocks/planner/ExchangeNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/HashJoinNode.java
  fe/fe-core/src/main/java/com/starrocks/planner/RuntimeFilterDescription.java
  fe/fe-core/src/main/java/com/starrocks/planner/SplitCastDataSink.java
  fe/fe-core/src/main/java/com/starrocks/planner/SplitCastPlanFragment.java
  fe/fe-core/src/main/java/com/starrocks/planner/UnionNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/guide/JoinTuningGuide.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/ExecutionDAG.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/LogicalPlanPrinter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptExpressionVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OperatorType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Projection.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalCTEAnchorOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalConcatenateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalHashJoinOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSplitConsumeOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalSplitProduceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/implementation/HashJoinImplementationRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/SkewShuffleJoinEliminationRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/com/starrocks/catalog/combinator/AggStateCombinatorTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/ExecutionDAGTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithCaseWhenTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/SelectStmtWithMultiLikeTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/cost/PlanFeaturesTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/PlanTestNoneDBBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SkewJoinV2Test.java
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/Partitions.thrift
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_http_sql/R/test_http_output
Labels: PROTO-REVIEW

#57031 [BugFix] fix cardinality estimation on boolean constant value using mcv
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/IntersectAddDistinctRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ReorderIntersectRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
Labels: 3.3, 3.4

#57004 [BugFix] fix spark-launcher jar missing
  fe/pom.xml
Labels: 3.3, 3.4

#57010 [Enhancement] upgrade jetty to 10.0.24 to fix CVE-2024-22201
  fe/pom.xml
  java-extensions/jni-connector/pom.xml
  java-extensions/kudu-reader/pom.xml
Labels: 3.3, 3.4

#57045 [BugFix] fix parse ES properties
  fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/EsUtil.java
  fe/fe-core/src/test/java/com/starrocks/connector/elasticsearch/EsUtilTest.java
Labels: 3.2, 3.3, 3.4

#57054 [Enhancement] Update error message of alter job conflicts with partition creation
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.2, 3.3, 3.4

#56796 [BugFix] Support paimon schema change
  be/src/connector/hive_connector.cpp
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/formats/parquet/column_converter.cpp
  be/src/formats/parquet/column_reader_factory.cpp
  be/src/formats/parquet/column_reader_factory.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/src/formats/parquet/meta_helper.cpp
  be/src/formats/parquet/meta_helper.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/test/exec/hdfs_scanner_test.cpp
  be/test/formats/parquet/column_converter_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/iceberg_schema_evolution_file_reader_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  gensrc/thrift/Descriptors.thrift
  java-extensions/paimon-reader/src/main/java/com/starrocks/paimon/reader/PaimonSplitScanner.java
Labels: PROTO-REVIEW, 3.3, 3.4

#56914 [Enhancement] Fix CNVD-C-2024-1042082
  fe/fe-core/src/main/java/com/starrocks/http/rest/ProfileAction.java
Labels: behavior_changed, 3.3, 3.4

#56264 [Enhancement] Capture stack trace if load meets brpc timeout
  be/src/common/config.h
  be/src/exec/tablet_sink_index_channel.cpp
  be/src/exec/tablet_sink_index_channel.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/diagnose_daemon.cpp
  be/src/runtime/diagnose_daemon.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.h
  be/src/util/stack_util.cpp
  be/src/util/stack_util.h
  be/test/CMakeLists.txt
  be/test/exec/tablet_sink_index_channel_test.cpp
  be/test/runtime/diagnose_daemon_test.cpp
  be/test/runtime/load_channel_test.cpp
  be/test/runtime/local_tablets_channel_test.cpp
  be/test/service/service_be/internal_service_test.cpp
  be/test/util/stack_util_test.cpp
  gensrc/proto/internal_service.proto
  test/sql/test_profile/R/test_load_brpc_reached_timeout
  test/sql/test_profile/T/test_load_brpc_reached_timeout
Labels: PROTO-REVIEW

#57000 [BugFix] Fix NPE when CREATE TABLE LIKE AS from a table with generated column
  fe/fe-core/src/main/java/com/starrocks/catalog/Column.java
  test/sql/test_automatic_partition/R/test_multi_expr
  test/sql/test_materialized_column/R/test_materialized_column
  test/sql/test_materialized_column/T/test_materialized_column
Labels: 3.3, 3.4

#56936 [Doc] Fix Fast Schema Evolution Note
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
Labels: documentation, 3.3, 3.4

#57032 [Doc] 3.4.0 Behavior Change
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#57015 [Doc] add doc for json array processing
  docs/en/sql-reference/data-types/semi_structured/JSON.md
  docs/ja/sql-reference/data-types/semi_structured/JSON.md
  docs/zh/sql-reference/data-types/semi_structured/JSON.md
Labels: documentation, 3.3, 3.4

#57073 [UT]end-to-end test case for iceberg schema evolution
  test/sql/test_iceberg/R/test_iceberg_schema_evolution
  test/sql/test_iceberg/T/test_iceberg_schema_evolution
Labels: 3.4

#57056 [BugFix] Support list mv refresh with null partition value
  fe/fe-core/src/main/java/com/starrocks/sql/common/PListCell.java
  test/sql/test_transparent_mv/R/test_mv_with_multi_partition_columns_iceberg1_nulls
  test/sql/test_transparent_mv/T/test_mv_with_multi_partition_columns_iceberg1_nulls
Labels: 3.4

#55282 [Enhancement] Reduce the size of data written to edit log when schema changes in shared-data clusters with fast schema evolution enabled.
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAlterMetaJobBase.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java
Labels: 3.4

#56899 [Enhancement] Catch bad alloc to avoid OOM
  be/src/common/config.h
  be/src/runtime/current_thread.h
  be/src/storage/persistent_index.cpp
  be/src/storage/persistent_index.h
  be/test/storage/persistent_index_test.cpp
Labels: 3.3, 3.4

#56942 [BugFix] Fix several bugs when restore table with random distribution
  fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/test/java/com/starrocks/backup/CatalogMocker.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
Labels: 3.3, 3.4

#57095 [Doc] Add doc for unified catalog using Paimon
  docs/en/data_source/catalog/unified_catalog.md
  docs/ja/data_source/catalog/unified_catalog.md
  docs/zh/data_source/catalog/unified_catalog.md
Labels: documentation, 3.3, 3.4

#57108 [Doc] Add doc for unified catalog using Paimon (backport #57095)
  docs/en/data_source/catalog/unified_catalog.md
  docs/ja/data_source/catalog/unified_catalog.md
  docs/zh/data_source/catalog/unified_catalog.md
Labels: documentation

#56910 [Doc] Remove Deprecated Param
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/ja/using_starrocks/Cost_based_optimizer.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.3, 3.4

#56862 [Doc] Add SSL Authentication
  docs/en/administration/user_privs/ssl_authentication.md
  docs/ja/administration/user_privs/ssl_authentication.md
  docs/zh/administration/user_privs/ssl_authentication.md
Labels: documentation, 3.4

#56987 [Enhancement] Improve broker load job retry
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadErrorUtils.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadTask.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/BrokerLoadJobTest.java
Labels: behavior_changed, 3.3, 3.4

#57047 [Enhancement] introduce more NDV estimators
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/NDVEstimator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/PrimitiveTypeColumnStats.java
  fe/fe-core/src/test/java/com/starrocks/statistic/sample/PrimitiveTypeColumnStatsTest.java
Labels: 3.3, 3.4

#57098 [BugFix] fix lake table's bad message when query error
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTablet.java
Labels: 3.3

#57055 [Enhancement] Improve create table failed message when BE has no available disk space
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java
Labels: 3.3, 3.4

#57006 [Enhancement] Paimon limit push down when only has partition predicate.
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.3, 3.4

#56840 [Feature] Support alter table merge partitions
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/MergePartitionJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/OptimizeJobV2Builder.java
  fe/fe-core/src/main/java/com/starrocks/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ExpressionPartitionDesc.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/OptimizeClause.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/OptimizeRange.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/alter/OptimizeJobV2BuilderTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AlterTableClauseVisitorTest.java
  test/sql/test_optimize_table/R/test_merge_partitions
  test/sql/test_optimize_table/T/test_merge_partitions
Labels: META-REVIEW

#56655 [BugFix] Fix checkpoint base compaction forbiden ranges fail
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionControlScheduler.java
Labels: 3.2, 3.3, 3.4

#57152 [Doc] Update Tableau Doc
  docs/en/integrations/BI_integrations/Tableau_Desktop.md
  docs/ja/integrations/BI_integrations/Tableau_Desktop.md
  docs/zh/integrations/BI_integrations/Tableau_Desktop.md
Labels: documentation, 3.2, 3.3, 3.4

#57159 [Doc] Doc for Iceberg Meta Tables
  docs/en/data_source/catalog/iceberg/iceberg_meta_table.md
  docs/ja/data_source/catalog/iceberg/iceberg_meta_table.md
  docs/zh/data_source/catalog/iceberg/iceberg_meta_table.md
Labels: documentation, 3.4

#57021 [Doc] Doc for Automated Cluster Snapshot
  docs/en/administration/cluster_snapshot.md
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/cluster_snapshot.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/cluster_snapshot.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.4

#56270 [Doc] Enhancement for MV on Data Lake
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/async_mv/use_cases/create_partitioned_materialized_view.md
Labels: documentation

#56230 [Doc] Common Partition Expression Doc
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
Labels: documentation

#57155 [BugFix] Fix materialized view originalViewDefineSql error (backport #56172)
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
Labels: automerge

#57174 [Doc] Fix incorrect anchor
  docs/en/sql-reference/data-types/semi_structured/JSON.md
  docs/ja/sql-reference/data-types/semi_structured/JSON.md
  docs/zh/sql-reference/data-types/semi_structured/JSON.md
Labels: documentation, 3.3, 3.4

#57119 [Doc] Remove the drop frontend part for meta recovery
  docs/en/administration/Meta_recovery.md
  docs/ja/administration/Meta_recovery.md
  docs/zh/administration/Meta_recovery.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#57192 [Enhancement] fix hadoop-hdfs cve in hudi-common
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: 3.3, 3.4

#57191 [BugFix] fix upgrade to spark 3.5.x compatibility
  fe/spark-dpp/src/main/java/com/starrocks/load/loadv2/dpp/SparkDpp.java
Labels: 3.3, 3.4

#57153 [BugFix] Fix view rewrite bug if non-rewritten view plan contains extra predicates
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteJoinTest.java
Labels: 3.3, 3.4

#57154 [BugFix] support boolean type predicate cardinality estimation
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
Labels: 3.3, 3.4

#57110 [Enhancement] Support modification of storage volume type and location in cluster snapshot restoration
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/StorageInfo.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableStorageInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/TableStorageInfos.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/SharedNothingStorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
Labels: META-REVIEW, 3.4

#57194 [Enhancement] remove broker from allin1 image
  docker/dockerfiles/allin1/allin1-ubi.Dockerfile
  docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile
  docker/dockerfiles/allin1/entrypoint.sh
  docker/dockerfiles/allin1/services/director/run.sh
  docker/dockerfiles/allin1/services/supervisor/supervisord.conf
Labels: behavior_changed, 3.4

#57101 [Refactor] establish abstract base for bloom filter hierarchy
  be/src/connector/connector.cpp
  be/src/connector/connector.h
  be/src/connector/hive_connector.cpp
  be/src/connector/lake_connector.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_joiner.cpp
  be/src/exec/hash_joiner.h
  be/src/exec/olap_scan_prepare.cpp
  be/src/exec/pipeline/hashjoin/hash_join_build_operator.cpp
  be/src/exec/pipeline/hashjoin/spillable_hash_join_build_operator.cpp
  be/src/exec/pipeline/nljoin/nljoin_context.cpp
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/runtime_filter_types.cpp
  be/src/exec/pipeline/runtime_filter_types.h
  be/src/exec/pipeline/scan/scan_operator.h
  be/src/exec/pipeline/sort/partition_sort_sink_operator.cpp
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_bank.cpp
  be/src/exprs/runtime_filter_bank.h
  be/src/runtime/runtime_filter_worker.cpp
  be/src/storage/runtime_range_pruner.h
  be/test/exec/hdfs_scanner_test.cpp
  be/test/exec/olap_scan_prepare_test.cpp
  be/test/exprs/min_max_predicate_test.cpp
  be/test/exprs/runtime_filter_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/storage/olap_runtime_range_pruner_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/combinator/AggStateDesc.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/TFragmentInstanceFactory.java
  gensrc/thrift/InternalService.thrift
Labels: PROTO-REVIEW

#57080 [Enhancement] Optimize graceful-exit for jdbc driver
  be/src/agent/finish_task.cpp
  be/src/common/status.cpp
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/common/util/SqlUtils.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/mysql/nio/ReadListener.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/task/AgentTaskQueue.java
  fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/com/starrocks/task/TabletTaskExecutor.java
  fe/fe-core/src/test/java/com/starrocks/common/util/SqlUtilsTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java
  gensrc/thrift/StatusCode.thrift
Labels: PROTO-REVIEW, 3.4

#57126 [BugFix] Fix `insert into files` statement not support delimiter convert
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java
Labels: 3.3, 3.4

#57170 [Enhancement] use partition level null fraction to estimate list partition cardinality
  be/src/runtime/statistic_result_writer.cpp
  be/src/runtime/statistic_result_writer.h
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PartitionStats.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PartitionStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticSQLBuilder.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatsConstants.java
  test/sql/test_list_partition/R/test_list_partition_selectivity
  test/sql/test_list_partition/T/test_list_partition_selectivity
Labels: 3.3, 3.4

#57227 [Doc] Fix user identity example
  docs/en/administration/user_privs/privilege_overview.md
  docs/ja/administration/user_privs/privilege_overview.md
  docs/zh/administration/user_privs/privilege_overview.md
Labels: documentation, 3.3, 3.4
