Repository StarRocks/starrocks, pull requests merged in 2025-01, with the labels that each got.

#54576 [Enhancement] remove gcc14 detect in build-thirdparty script
  thirdparty/build-thirdparty.sh
Labels: 3.4

#54571 [Enhancement] Improve files() parquet orc column mismatch error message
  be/src/exec/csv_scanner.cpp
  be/src/exec/orc_scanner.cpp
  be/src/exec/parquet_reader.cpp
  be/src/exec/parquet_scanner.cpp
  test/sql/test_files/R/test_csv_files_merge
  test/sql/test_files/R/test_orc_files_merge
  test/sql/test_files/R/test_parquet_files_merge
  test/sql/test_files/T/test_orc_files_merge
  test/sql/test_files/T/test_parquet_files_merge
Labels: behavior_changed, 3.4

#54579 [Enhancement] patching flatbuffers CMakeLists.txt
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/flat-buffers-1.10.0-no-stringop-overread.patch
Labels: 3.4

#54591 [UT] Fix Compilation error with clang
  be/test/formats/parquet/file_reader_test.cpp
Labels: 3.4

#54593 [Enhancement] add sv cbo_max_reorder_node_use_greedy and skip DP and greedy reorder without unknown stats
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderFactory.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/ReorderJoinRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java
Labels: 3.4

#54592 [BugFix] Fix UAF in shared UDF
  be/src/exprs/java_function_call_expr.cpp
  be/src/exprs/java_function_call_expr.h
  be/src/udf/java/java_udf.cpp
  be/src/udf/java/java_udf.h
  test/sql/test_udf/R/test_jvm_udf
  test/sql/test_udf/T/test_jvm_udf
Labels: 3.1, 3.2, 3.3, 3.4

#54595 [BugFix] Fix sequence of selection and input_chunk for streaming_agg_with_selection
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#54620 [Doc] fix descriptions, add guide link
  docs/en/sql-reference/sql-statements/backup_restore/BACKUP.md
  docs/en/sql-reference/sql-statements/backup_restore/CANCEL_BACKUP.md
  docs/en/sql-reference/sql-statements/backup_restore/CANCEL_RESTORE.md
  docs/en/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
  docs/en/sql-reference/sql-statements/backup_restore/DROP_REPOSITORY.md
  docs/en/sql-reference/sql-statements/backup_restore/RECOVER.md
  docs/en/sql-reference/sql-statements/backup_restore/RESTORE.md
  docs/en/sql-reference/sql-statements/backup_restore/SHOW_BACKUP.md
  docs/en/sql-reference/sql-statements/backup_restore/SHOW_REPOSITORIES.md
  docs/en/sql-reference/sql-statements/backup_restore/SHOW_RESTORE.md
  docs/en/sql-reference/sql-statements/backup_restore/SHOW_SNAPSHOT.md
  docs/en/sql-reference/sql-statements/backup_restore/backup_restore.mdx
  docs/zh/sql-reference/sql-statements/backup_restore/BACKUP.md
  docs/zh/sql-reference/sql-statements/backup_restore/CANCEL_BACKUP.md
  docs/zh/sql-reference/sql-statements/backup_restore/CANCEL_RESTORE.md
  docs/zh/sql-reference/sql-statements/backup_restore/CREATE_REPOSITORY.md
  docs/zh/sql-reference/sql-statements/backup_restore/DROP_REPOSITORY.md
  docs/zh/sql-reference/sql-statements/backup_restore/RECOVER.md
  docs/zh/sql-reference/sql-statements/backup_restore/RESTORE.md
  docs/zh/sql-reference/sql-statements/backup_restore/SHOW_BACKUP.md
  docs/zh/sql-reference/sql-statements/backup_restore/SHOW_REPOSITORIES.md
  docs/zh/sql-reference/sql-statements/backup_restore/SHOW_RESTORE.md
  docs/zh/sql-reference/sql-statements/backup_restore/backup_restore.mdx
Labels: documentation, 3.0, 3.1, 3.2, 3.3, 3.4

#54300 [Doc] add doc for time_format
  docs/en/sql-reference/sql-functions/date-time-functions/time_format.md
  docs/zh/sql-reference/sql-functions/date-time-functions/time_format.md
Labels: documentation, 3.2, 3.3, 3.4

#54606 [Doc] update doc about shared-data mode ingestion rate limit
  docs/en/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3, 3.4

#54575 [Enhancement] Use bthread lock in merge commit rpc
  be/src/runtime/batch_write/batch_write_mgr.cpp
  be/src/runtime/batch_write/batch_write_mgr.h
  be/src/runtime/batch_write/isomorphic_batch_write.cpp
  be/src/runtime/batch_write/isomorphic_batch_write.h
Labels: 3.4

#54585 [BugFix] Fix warehouse exists check after modify system info meta bug
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
Labels: 3.3, 3.4

#53824 [Enhancement] Add skip_page_cache and skip_disk_cache options in session variables
  be/src/connector/lake_connector.cpp
  be/src/fs/fs.h
  be/src/fs/fs_starlet.cpp
  be/src/storage/lake/horizontal_compaction_task.cpp
  be/src/storage/lake/vertical_compaction_task.cpp
  be/src/storage/options.h
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/segment_options.h
  be/src/storage/rowset/segment_rewriter.cpp
  be/src/storage/tablet_reader_params.h
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW, 3.3, 3.4

#54572 [Enhancement] adjust agg pushdown strategy for broadcast
  be/src/exec/aggregator.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/pdagg/PushDownAggregateCollector.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsEstimateCoefficient.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TPCDSPushAggTest.java
Labels: 3.4

#54604 [Enhancement] Remove unnecessary frequent memory alloc and release requests
  be/src/storage/persistent_index.cpp
Labels: 3.2, 3.3, 3.4

#54645 [BugFix] Fix exception not clear in env
  be/src/udf/java/java_udf.h
Labels: 3.2, 3.3, 3.4

#54626 [Enhancement] Support read compressed csv in files()
  be/src/exec/file_scanner.cpp
  test/sql/test_files/R/test_csv_compress
  test/sql/test_files/T/test_csv_compress
  test/sql/test_files/csv_format/basic1.csv.bz2
  test/sql/test_files/csv_format/basic1.csv.deflate
  test/sql/test_files/csv_format/basic1.csv.gz
  test/sql/test_files/csv_format/basic1.csv.lz4
  test/sql/test_files/csv_format/basic1.csv.zst
Labels: 3.3, 3.4

#54627 [BugFix] Only enable query context cache when there are more than one related mvs
  fe/fe-core/src/main/java/com/starrocks/connector/ConnectorPartitionTraits.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryMaterializationContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorIcebergTest.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessorOlapPart2Test.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.3, 3.4

#54590 [BugFix] fix HttpResultWriter ill-formatted json string
  be/src/runtime/http_result_writer.cpp
  be/test/CMakeLists.txt
  be/test/runtime/http_result_writer_test.cpp
Labels: 3.2, 3.3, 3.4

#54564 [Enhancement] Remove thrift_types_customize_impl.cpp from gitignore
  .gitignore
Labels: 3.1, 3.2, 3.3, 3.4

#54684 [Doc] 3.1.17 release notes
  docs/en/release_notes/release-3.1.md
  docs/zh/release_notes/release-3.1.md
Labels: documentation

#54700 [Doc] 3.3.8 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#54697 [Enhancement] support `cache select` set var hint
  fe/fe-core/src/main/java/com/starrocks/sql/parser/HintCollector.java
  fe/fe-core/src/test/java/com/starrocks/analysis/DataCacheStmtAnalyzerTest.java
Labels: 3.3, 3.4

#54677 [BugFix] Remove sensitive messages in be log
  be/src/storage/replication_utils.cpp
  be/src/storage/task/engine_clone_task.cpp
Labels: 3.3, 3.4

#54696 [BugFix] avoid tte is null in `openInternal` in HiveMetaStoreClient
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: 3.2, 3.3, 3.4

#54671 [Enhancement] statistics query error message retargeting from fe.out to fe.log
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorColumnStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/connector/statistics/ConnectorHistogramColumnStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PartitionStatsCacheLoader.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/TableStatsCacheLoader.java
Labels: 3.4

#54686 [UT] Fix unstable ut
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
Labels: 3.2, 3.3, 3.4

#54458 [Feature] Support security view
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/authorization/ColumnPrivilege.java
  fe/fe-core/src/main/java/com/starrocks/catalog/View.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AlterViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergMetadataTest.java
  test/sql/test_view/R/test_alter_view
  test/sql/test_view/R/test_security_view
  test/sql/test_view/T/test_alter_view
  test/sql/test_view/T/test_security_view
Labels: META-REVIEW

#54679 [BugFix] don't remove partition predicate from predicate when bucket column includes partition column
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java
  fe/fe-core/src/test/java/com/starrocks/planner/HashDistributionPrunerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartialPartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewritePartitionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteUnionTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentUnionRewriteOlapTest.java
Labels: 3.4

#54728 [BugFix] Fix wrong decimal32 type when converted from thrift
  fe/fe-core/src/main/java/com/starrocks/catalog/PrimitiveType.java
Labels: 3.3, 3.4

#54713 [Enhancement]reserve size before reading strings
  be/src/formats/parquet/encoding_plain.h
Labels: 3.4

#54690 [Refactor] Refactor edit log deserialize logical and add Writable default implementation
  fe/fe-core/src/main/java/com/starrocks/common/io/Writable.java
  fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBTool.java
  fe/fe-core/src/main/java/com/starrocks/persist/AlterUserInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/CreateUserInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/bdb/BDBToolTest.java
  fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJournalCursorTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/CreateInsertOverwriteJobLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/EditLogTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/InsertOverwriteStateChangeInfoTest.java
  fe/fe-core/src/test/java/com/starrocks/statistic/AnalyzeMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/system/BackendHbResponseTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockJournal.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: META-REVIEW

#54750 [Enhancement] improve error message of killed sql (backport #53708)
  fe/fe-core/src/main/java/com/starrocks/common/util/SqlUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/com/starrocks/qe/DefaultCoordinator.java
Labels: automerge

#54678 [BugFix] fix incorrect part of compaction profile
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/test/storage/lake/compaction_task_context_test.cpp
Labels: 3.2, 3.3, 3.4

#54654 [BugFix] Fix wrong plan when apply offset limit in PushDown Project limit
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectLimitRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/LimitTest.java
Labels: 3.2, 3.3, 3.4

#54737 [BugFix] Build a ConnectContext for inner query which is used for StarRocks internal query
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobExecutor.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobMgr.java
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/OnlineOptimizeJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/backup/mv/MVRestoreUpdater.java
  fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/main/java/com/starrocks/connector/metadata/MetadataCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticUtils.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/CatalogConnectorMetadataTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/AlterTest.java
Labels: 3.2, 3.3, 3.4

#54754 [Doc] update Metabase connect docs
  docs/en/_assets/Metabase/Metabase_3.png
  docs/en/integrations/BI_integrations/Metabase.md
  docs/zh/_assets/Metabase/Metabase_3.png
  docs/zh/integrations/BI_integrations/Metabase.md
Labels: documentation, 3.2, 3.3, 3.4

#54774 [Doc]Fix wrong pr url in release notes.
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation, 3.2, 3.3, 3.4

#54766 [BugFix] reset delta rows of basic meta after collecting statistics
  fe/fe-core/src/main/java/com/starrocks/statistic/BasicStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/test/java/com/starrocks/statistic/BasicStatsMetaTest.java
Labels: 3.3, 3.4

#54797 [Doc] load props are comma separated
  docs/en/loading/Etl_in_loading.md
  docs/zh/loading/Etl_in_loading.md
Labels: documentation

#54480 [Doc] doc for `scan_olap_partition_num_limit` session variable
  docs/en/sql-reference/System_variable.md
  docs/zh/sql-reference/System_variable.md
Labels: documentation, 3.3, 3.4

#54482 [Doc] add doc for `starlet_fslib_s3client_request_timeout_ms`
  docs/en/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3, 3.4

#54324 [Doc] fix wrong link for 'ANALYZE PROFILE' in EXPLAIN_ANALYZE.md
  docs/en/sql-reference/sql-statements/cluster-management/plan_profile/EXPLAIN_ANALYZE.md
Labels: documentation, 3.3, 3.4

#53703 [Enhancement][Doc] add warehouse parameter to audit log table
  docs/en/administration/management/audit_loader.md
  docs/zh/administration/management/audit_loader.md
Labels: documentation

#53699 [Doc] update show dynamic partition tables startof filed
  docs/en/sql-reference/sql-statements/table_bucket_part_index/SHOW_DYNAMIC_PARTITION_TABLES.md
Labels: documentation

#54806 [Doc] update PDF gen
  docs/docusaurus/Dockerfile
  docs/docusaurus/PDF/README.md
  docs/docusaurus/PDF/docker-compose.yaml
  docs/docusaurus/PDF/generatePdf.js
  docs/docusaurus/src/css/custom.css
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#53553 [Doc] Query-triggered ANALYZE
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/System_variable.md
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.4

#54789 [BugFix] Change sort key may not work correctly
  be/src/column/schema.cpp
  be/src/storage/schema_change.cpp
  test/sql/test_schema/R/test_order_keys
  test/sql/test_sort_key/R/test_sort_key_agg_tbl
  test/sql/test_sort_key/R/test_sort_key_uni_tbl
  test/sql/test_sort_key/T/test_sort_key_agg_tbl
  test/sql/test_sort_key/T/test_sort_key_uni_tbl
Labels: 3.2, 3.3, 3.4

#54790 [BugFix] Fix snapshot versions in cross-cluster replication
  be/src/storage/replication_txn_manager.cpp
Labels: 3.1, 3.2, 3.3, 3.4

#54749 [Enhancement] Fixing CVEs
  java-extensions/hive-reader/pom.xml
  java-extensions/hudi-reader/pom.xml
  java-extensions/iceberg-metadata-reader/pom.xml
Labels: 3.3, 3.4

#54830 [Enhancement] adjust translate function syntax structure to prevent parser performance rollback
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/parser/ParserTest.java
  test/sql/test_agg/R/test_distinct_agg
  test/sql/test_agg/T/test_distinct_agg
Labels: 3.4

#54837 [BugFix] Fix thrift RuntimeProfile child node number not consistent
  be/src/util/runtime_profile.cpp
Labels: 3.2, 3.3, 3.4

#54804 [BugFix] Materialized view rewrite fails because PartitionKey type is DATE.
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtilsTest.java
Labels: 3.3, 3.4

#53934 [Enhancement] use table sample to collect column statistics
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/statistic/HistogramStatisticsCollectJob.java
  fe/fe-core/src/main/java/com/starrocks/statistic/hyper/HyperStatisticSQLs.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/SampleInfo.java
  fe/fe-core/src/test/java/com/starrocks/statistic/StatisticsCollectJobTest.java
Labels: behavior_changed

#54873 [Enhancement] Fixing vulns
  docs/docusaurus/package.json
Labels: documentation, 3.3, 3.4

#54829 [Refactor] Remove cancel disable disk code
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
Labels: META-REVIEW

#54849 [Enhancement] support cumulative algorithm for max/min
  be/src/column/nullable_column.h
  be/src/common/config.h
  be/src/exec/analytor.cpp
  be/src/exprs/agg/aggregate.h
  be/src/exprs/agg/aggregate_traits.h
  be/src/exprs/agg/avg.h
  be/src/exprs/agg/count.h
  be/src/exprs/agg/maxmin.h
  be/src/exprs/agg/nullable_aggregate.h
  be/src/exprs/agg/sum.h
Labels: 3.3, 3.4

#54892 [UT] fix ut stop, add lake::tablet_manager stop
  be/src/testutil/init_test_env.h
  be/test/storage/task/engine_storage_migration_task_test.cpp
Labels: 3.3, 3.4

#54854 [BugFix] Fix date_format function error when input with microsecond
  be/src/exprs/time_functions.cpp
  be/src/runtime/time_types.h
  be/src/types/timestamp_value.cpp
  be/src/types/timestamp_value.h
  be/test/exprs/time_functions_test.cpp
Labels: 3.0, 3.1, behavior_changed, 3.2, 3.3, 3.4

#54859 [BugFix] ensure the latch can be counted down
  be/src/service/service_be/lake_service.cpp
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
  be/test/service/lake_service_test.cpp
  be/test/util/threadpool_test.cpp
Labels: 3.2, 3.3, 3.4

#54918 [UT] fix test_list_partition_minmax
  test/sql/test_list_partition/R/test_list_partition_minmax
  test/sql/test_list_partition/T/test_list_partition_minmax
Labels: 3.3, 3.4

#54110 [Doc] v3.4 INSERT from FILES Enhancement
  docs/en/loading/InsertInto.md
  docs/en/loading/load_concept/strict_mode.md
  docs/en/sql-reference/System_variable.md
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/en/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/zh/loading/InsertInto.md
  docs/zh/loading/load_concept/strict_mode.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation, 3.4

#53785 [Doc] V3.4 Query feedback doc
  docs/en/administration/management/FE_configuration.md
  docs/en/sql-reference/System_variable.md
  docs/en/using_starrocks/query_feedback.md
  docs/zh/administration/management/FE_configuration.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/using_starrocks/query_feedback.md
Labels: documentation

#54279 [Doc] V3.4 Doc - Merge Commit
  docs/en/loading/StreamLoad.md
  docs/en/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
  docs/zh/loading/StreamLoad.md
  docs/zh/sql-reference/sql-statements/loading_unloading/STREAM_LOAD.md
Labels: documentation, 3.4

#54460 [Doc] Add status code to show be/cn
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_BACKENDS.md
  docs/en/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_COMPUTE_NODES.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_BACKENDS.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/SHOW_COMPUTE_NODES.md
Labels: documentation, 3.4

#54329 [Doc] V3.4 - Dynamic Overwrite
  docs/en/loading/InsertInto.md
  docs/en/sql-reference/System_variable.md
  docs/en/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/zh/loading/InsertInto.md
  docs/zh/sql-reference/System_variable.md
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation, 3.4

#54509 [Doc] v3.4 Multi-level Expression Partitioning
  docs/en/table_design/data_distribution/Data_distribution.md
  docs/en/table_design/data_distribution/dynamic_partitioning.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/en/table_design/data_distribution/list_partitioning.md
  docs/zh/table_design/data_distribution/Data_distribution.md
  docs/zh/table_design/data_distribution/dynamic_partitioning.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/list_partitioning.md
Labels: documentation, 3.4

#54907 [Doc] v3.4 - Delta Lake features
  docs/en/data_source/catalog/deltalake_catalog.md
  docs/zh/data_source/catalog/deltalake_catalog.md
Labels: documentation, 3.3, 3.4

#54911 [Doc] V3.4 - Miscellaneous Support info
  docs/en/_assets/commonMarkdown/sharedDataUse.md
  docs/en/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/en/using_starrocks/Materialized_view-single_table.md
  docs/en/using_starrocks/caching/query_cache.md
  docs/zh/_assets/commonMarkdown/sharedDataUse.md
  docs/zh/sql-reference/sql-statements/materialized_view/CREATE_MATERIALIZED_VIEW.md
  docs/zh/using_starrocks/Materialized_view-single_table.md
  docs/zh/using_starrocks/caching/query_cache.md
Labels: documentation, 3.4

#54917 [BugFix] Add exhausted check for MultiJoinBinder
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/GroupExpression.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewManyJoinTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/BinderTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/UtFrameUtils.java
Labels: 3.2, 3.3, 3.4

#53979 [Doc] Doc update for v3.4 BACKUP RESTORE
  docs/en/administration/management/Backup_and_restore.md
  docs/en/sql-reference/sql-statements/backup_restore/BACKUP.md
  docs/en/sql-reference/sql-statements/backup_restore/CANCEL_BACKUP.md
  docs/en/sql-reference/sql-statements/backup_restore/CANCEL_RESTORE.md
  docs/en/sql-reference/sql-statements/backup_restore/RESTORE.md
  docs/en/table_design/data_distribution/expression_partitioning.md
  docs/en/table_design/data_distribution/list_partitioning.md
  docs/zh/administration/management/Backup_and_restore.md
  docs/zh/sql-reference/sql-statements/backup_restore/BACKUP.md
  docs/zh/sql-reference/sql-statements/backup_restore/CANCEL_BACKUP.md
  docs/zh/sql-reference/sql-statements/backup_restore/CANCEL_RESTORE.md
  docs/zh/sql-reference/sql-statements/backup_restore/RESTORE.md
  docs/zh/table_design/data_distribution/expression_partitioning.md
  docs/zh/table_design/data_distribution/list_partitioning.md
Labels: documentation, 3.4

#54922 [BugFix] Fix LockManager release not notify all waiters that meet the conditions
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/LockManager.java
  fe/fe-core/src/main/java/com/starrocks/common/util/concurrent/lock/MultiUserLock.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/LockManagerAllLockModesRandomTest.java
  fe/fe-core/src/test/java/com/starrocks/common/lock/ReleaseTest.java
Labels: 3.3, 3.4

#54847 [Enhancement] Improve deletion vector performance using roaring bitmap instead of set
  be/src/connector/CMakeLists.txt
  be/src/connector/deletion_vector/deletion_bitmap.cpp
  be/src/connector/deletion_vector/deletion_bitmap.h
  be/src/connector/deletion_vector/deletion_vector.cpp
  be/src/connector/deletion_vector/deletion_vector.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_orc.cpp
  be/src/exec/hdfs_scanner_orc.h
  be/src/exec/hdfs_scanner_parquet.cpp
  be/src/exec/iceberg/iceberg_delete_builder.cpp
  be/src/exec/iceberg/iceberg_delete_builder.h
  be/src/exec/paimon/paimon_delete_file_builder.cpp
  be/src/exec/paimon/paimon_delete_file_builder.h
  be/src/formats/orc/orc_chunk_reader.cpp
  be/src/formats/orc/orc_chunk_reader.h
  be/src/formats/parquet/file_reader.cpp
  be/src/formats/parquet/group_reader.cpp
  be/src/formats/parquet/group_reader.h
  be/test/connector/deletion_vector/deletion_vector_test.cpp
  be/test/exec/paimon/paimon_delete_file_builder_test.cpp
  be/test/formats/orc/orc_chunk_reader_test.cpp
  be/test/formats/parquet/file_reader_test.cpp
  be/test/formats/parquet/group_reader_test.cpp
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: 3.4

#54921 [Doc] SQL Digest Minor fix
  docs/en/administration/sql_digest.md
  docs/zh/administration/sql_digest.md
Labels: documentation, 3.3, 3.4

#54895 [Doc] Remove cloud ingest
  docs/docusaurus/docusaurus.config.js
  docs/docusaurus/sidebars.json
  docs/en/loading/Etl_in_loading.md
  docs/en/loading/Load_to_Primary_Key_tables.md
  docs/en/loading/alibaba.md
  docs/en/loading/cloud_storage_load.md
  docs/en/loading/huawei.md
  docs/en/loading/s3_compatible.md
  docs/en/loading/tencent.md
  docs/zh/loading/Etl_in_loading.md
  docs/zh/loading/Load_to_Primary_Key_tables.md
  docs/zh/loading/Loading_intro.md
  docs/zh/loading/alibaba.md
  docs/zh/loading/cloud_storage_load.md
  docs/zh/loading/huawei.md
  docs/zh/loading/s3_compatible.md
  docs/zh/loading/tencent.md
  docs/zh/sql-reference/sql-statements/cluster-management/nodes_processes/ALTER_SYSTEM.md
  docs/zh/sql-reference/sql-statements/loading_unloading/BROKER_LOAD.md
  docs/zh/sql-reference/sql-statements/loading_unloading/SHOW_LOAD.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#54818 [Enhancement] Support some math function for trino parser
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: behavior_changed

#54755 [Doc] 3.2.14 Release notes
  docs/en/release_notes/release-3.2.md
  docs/zh/release_notes/release-3.2.md
Labels: documentation

#54695 [Feature] Support Cluster Snapshot Backup: checkpoint and image backup (part3)
  be/src/exec/schema_scanner/schema_cluster_snapshot_jobs_scanner.cpp
  be/src/exec/schema_scanner/schema_cluster_snapshots_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ClusterSnapshotJobsTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ClusterSnapshotsTable.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/fs/HdfsUtil.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java
  fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsService.java
  fe/fe-core/src/main/java/com/starrocks/journal/CheckpointWorker.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshot.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotCheckpointScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotUtils.java
  fe/fe-core/src/main/java/com/starrocks/leader/CheckpointController.java
  fe/fe-core/src/main/java/com/starrocks/persist/ClusterSnapshotLog.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ClusterSnapshotAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java
  fe/fe-core/src/test/java/com/starrocks/lake/ClusterSnapshotTest.java
Labels: META-REVIEW

#54857 [BugFix] Fix unlimit delete_txn_log request from FE side
  fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java
Labels: 3.3, 3.4

#54949 [Enhancement] Make generated column error msg more clear
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
Labels: 3.2, 3.3

#54942 [Doc] 3.4 RC release notes
  docs/en/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#54975 [Doc] 3.3.9 release notes
  docs/en/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#54978 [BugFix]uuid in iceberg should be binary
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
Labels: behavior_changed, 3.2, 3.3, 3.4

#55008 [Doc] 3.4 Release notes update
  docs/en/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#54956 [Enhancement] adaptive enable the exchange compression
  be/src/common/config.h
  be/src/exec/pipeline/exchange/exchange_sink_operator.cpp
  be/src/exec/pipeline/exchange/exchange_sink_operator.h
  be/src/serde/CMakeLists.txt
  be/src/serde/compress_strategy.cpp
  be/src/serde/compress_strategy.h
  be/src/serde/encode_context.cpp
  be/src/util/compression/block_compression.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/com/starrocks/common/util/CompressionUtils.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  gensrc/thrift/Types.thrift
Labels: behavior_changed, PROTO-REVIEW, 3.4

#54972 [BugFix] flush memtable when too many files need rebuilt in cloud native pk index
  be/src/common/config.h
  be/src/storage/lake/lake_persistent_index.cpp
  be/src/storage/lake/lake_persistent_index.h
  be/src/storage/lake/meta_file.h
  be/src/storage/lake/persistent_index_memtable.h
  be/test/storage/lake/primary_key_publish_test.cpp
Labels: 3.3, 3.4

#55005 [BugFix]uuid in iceberg should be binary (backport #54978)
  fe/fe-core/src/main/java/com/starrocks/connector/ColumnTypeConverter.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergApiConverterTest.java
Labels: behavior_changed

#55027 [Doc] use safe package.json yarn.lock
  .github/workflows/ci-doc-checker.yml
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55025 [Doc] Fix typo
  docs/en/sql-reference/sql-functions/array-functions/array_contains_seq.md
  docs/zh/sql-reference/sql-functions/array-functions/array_contains_seq.md
Labels: documentation, 3.3, 3.4

#54974 [Enhancement] update staros 3.4-rc3
  docker/dockerfiles/dev-env/dev-env.Dockerfile
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgentTest.java
  thirdparty/starlet-artifacts-version.sh
Labels: 3.4

#55012 [BugFix] Fix cancel external catalog backup/restore failed and refactor some error msg
  fe/fe-core/src/main/java/com/starrocks/backup/BackupHandler.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
Labels: 3.4

#54945 [Enhancement]define GlobalDictNotMatch Status and extract info to feedback
  be/src/common/status.cpp
  be/src/common/status.h
  be/test/common/status_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Status.java
  fe/fe-core/src/main/java/com/starrocks/connector/exception/GlobalDictNotMatchException.java
  fe/fe-core/src/test/java/com/starrocks/connector/exception/GlobalDictNotMatchExceptionTest.java
  gensrc/thrift/StatusCode.thrift
Labels: PROTO-REVIEW

#55020 [BugFix] Fix a bug that the fe_entrypoint.sh will always use the default EDIT_LOG_PORT
  docker/dockerfiles/fe/fe_entrypoint.sh
Labels: 3.1, 3.2, 3.3, 3.4

#55074 Revert "[Doc] use safe package.json yarn.lock"
  .github/workflows/ci-doc-checker.yml
Labels: title needs [type]

#55053 [UT] Fix unstable CoordinatorBackendAssignerTest
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/CoordinatorBackendAssignerImpl.java
Labels: 3.4

#55078 [Doc] Files() with Regex
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.2, 3.3, 3.4

#55062 [Doc] Remove incorrect description
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.4

#55083 [Doc] use package.json from main
  .github/workflows/ci-doc-checker.yml
Labels: 3.3, 3.4

#55050 [Doc] Add links to release notes
  docs/en/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#55022 [Enhancement] deletion bitmap fill skip rows filter in batches
  be/src/connector/deletion_vector/deletion_bitmap.cpp
  be/src/connector/deletion_vector/deletion_bitmap.h
  be/src/exec/hdfs_scanner.cpp
  be/src/exec/hdfs_scanner.h
  be/src/exec/hdfs_scanner_parquet.cpp
Labels: 3.4

#55095 [BugFix] Fix MemTracker::release_without_root
  be/src/runtime/mem_tracker.h
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55071 [Enhancement] Introduce TxnStateDispatcher for merge commit sync mode #55001
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/BatchWriteMgr.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/CoordinatorBackendAssignerImpl.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/IsomorphicBatchWrite.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/LoadExecuteCallback.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/LoadExecutor.java
  fe/fe-core/src/main/java/com/starrocks/load/batchwrite/TxnStateDispatcher.java
  fe/fe-core/src/main/java/com/starrocks/rpc/PBackendService.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStatus.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/CoordinatorBackendAssignerTest.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/IsomorphicBatchWriteTest.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/LoadExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/load/batchwrite/TxnStateDispatcherTest.java
  fe/fe-core/src/test/java/com/starrocks/pseudocluster/PseudoBackend.java
  fe/fe-core/src/test/java/com/starrocks/utframe/MockedBackend.java
  gensrc/proto/internal_service.proto
  gensrc/proto/types.proto
Labels: PROTO-REVIEW

#55107 [Doc] Add Trino Translate doc
  docs/en/sql-reference/sql-statements/TRANSLATE_TRINO.md
  docs/zh/sql-reference/sql-statements/TRANSLATE_TRINO.md
Labels: documentation, 3.3, 3.4

#55024 [BugFix] Fix set the gtid of null rowset when publish
  be/src/agent/publish_version.cpp
Labels: 3.4

#55116 [BugFix] make max_by/min_by's output result column always nullable
  be/src/exec/aggregator.cpp
  test/sql/test_max_min_by_not_filter_nulls_with_nulls/R/test_max_min_by_with_empty_table
  test/sql/test_max_min_by_not_filter_nulls_with_nulls/T/test_max_min_by_with_empty_table
Labels: 3.1, 3.2, 3.3, 3.4

#55138 [Doc] Remove CN deployment from shared-nothing
  docs/en/deployment/deploy_manually.md
  docs/zh/deployment/deploy_manually.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#54997 [BugFix] Fix NPE in HeartbeatMgr when FE node is not available
  fe/fe-core/src/main/java/com/starrocks/common/util/Util.java
  fe/fe-core/src/test/java/com/starrocks/common/util/UtilTest.java
Labels: 3.4

#55134 [BugFix] destruct workgroup's MemTracker prematurely
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/exec/workgroup/work_group.h
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55014 [Feature] Make blacklist persistent
  fe/fe-core/src/main/java/com/starrocks/meta/SqlBlackList.java
  fe/fe-core/src/main/java/com/starrocks/persist/DeleteSqlBlackLists.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java
  fe/fe-core/src/main/java/com/starrocks/persist/SqlBlackListPersistInfo.java
  fe/fe-core/src/main/java/com/starrocks/persist/metablock/SRMetaBlockID.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AddSqlBlackListStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/DelSqlBlackListStmt.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SqlBlacklistAndWhitelistTest.java
  fe/fe-core/src/test/java/com/starrocks/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/com/starrocks/persist/OperationTypeTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/QueryPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/server/SqlBlacklistTest.java
Labels: behavior_changed, META-REVIEW

#49684 [BugFix] Fix warehouse property might not take effect when executing load stmts
  fe/fe-core/src/main/java/com/starrocks/http/rest/transaction/TransactionWithChannelHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadJob.java
  fe/fe-core/src/test/java/com/starrocks/http/StarRocksHttpTestCase.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/LoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/com/starrocks/load/streamload/StreamLoadManagerTest.java
Labels: 3.3, 3.4

#55127 [Doc] Update Match Column By Name
  docs/en/loading/InsertInto.md
  docs/en/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/zh/loading/InsertInto.md
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation, 3.4

#55174 [BugFix] fix fragment instance state transition in incremental scan ranges case
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java
Labels: 3.4

#55137 [Enhancement] Optimize the performance of reading dictionary pages
  be/src/common/config.h
  be/src/storage/rowset/binary_dict_page.cpp
  be/src/storage/rowset/binary_plain_page.cpp
  be/src/storage/rowset/binary_plain_page.h
Labels: 3.4

#55147 [Enhancement] Use cluster_snapshot_path to specify the cluster snapshot to be restored
  conf/cluster_snapshot.yaml
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotConfig.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/snapshot/ClusterSnapshotConfigTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/snapshot/RestoreClusterSnapshotMgrTest.java
  fe/fe-core/src/test/resources/conf/cluster_snapshot.yaml
  fe/fe-core/src/test/resources/conf/cluster_snapshot2.yaml
Labels: 3.4

#55145 [Enhancement] Support mysql_clear_password pulgin for native user
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
Labels: 3.4

#55173 [BugFix] Fix promote ip string as double type in csv files()
  be/src/util/string_parser.hpp
  be/test/util/string_parser_test.cpp
  test/sql/test_files/R/test_csv_ip
  test/sql/test_files/T/test_csv_ip
  test/sql/test_files/csv_format/ip.csv
Labels: 3.3, 3.4

#55168 [BugFix] Fix RewriteUnnestBitmapRule rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteUnnestBitmapRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/TableFunctionTest.java
  test/sql/test_bitmap_functions/R/test_unnest_bitmap
  test/sql/test_bitmap_functions/T/test_unnest_bitmap
Labels: 3.4

#54980 [Feature] Support Cluster Snapshot Backup: deletion control (part4)
  fe/fe-core/src/main/java/com/starrocks/alter/AlterHandler.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshot.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/test/java/com/starrocks/catalog/CatalogRecycleBinTest.java
  fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/ClusterSnapshotTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: META-REVIEW

#55163 [BugFix] Fix TopN RuntimeFilter with nulls first crash with lowcardinality optimize
  be/src/exec/olap_scan_prepare.cpp
  be/src/exec/olap_scan_prepare.h
  test/sql/test_sort/R/test_topn
  test/sql/test_sort/T/test_topn
Labels: 3.4

#55214 [BugFix] fix thrift compatibility issue with v3.3
  gensrc/thrift/PlanNodes.thrift
Labels: PROTO-REVIEW, 3.4

#54745 [Doc] Add ds_hll_count_distinct doc
  docs/en/sql-reference/sql-functions/aggregate-functions/approx_count_distinct_hll_sketch.md
  docs/en/sql-reference/sql-functions/aggregate-functions/ds_hll_count_distinct.md
  docs/zh/sql-reference/sql-functions/aggregate-functions/ds_hll_count_distinct.md
Labels: documentation, 3.4

#54047 [BugFix] Call StarOsAgent.prepare wherever serviceId is required
  fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java
Labels: 3.3, 3.4

#54779 [BugFix] Fix shared UDF concurrent load issue
  be/src/runtime/user_function_cache.cpp
Labels: 3.4

#55207 [BugFix] fix ingestion hang because of alter job timeout
  fe/fe-core/src/main/java/com/starrocks/alter/AlterJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
Labels: 3.2, 3.3, 3.4

#55123 [BugFix] Fix bugs of vector index
  be/src/common/config.h
  be/src/exec/pipeline/scan/olap_chunk_source.cpp
  be/src/exec/pipeline/scan/olap_chunk_source.h
  be/src/storage/index/vector/tenann/del_id_filter.h
  be/src/storage/index/vector/tenann/tenann_index_builder.cpp
  be/src/storage/index/vector/tenann/tenann_index_builder.h
  be/src/storage/index/vector/tenann/tenann_index_utils.cpp
  be/src/storage/index/vector/vector_index_builder.h
  be/src/storage/index/vector/vector_index_builder_factory.cpp
  be/src/storage/index/vector/vector_index_builder_factory.h
  be/src/storage/index/vector/vector_index_writer.cpp
  be/src/storage/index/vector/vector_index_writer.h
  be/src/storage/rowset/array_column_writer.cpp
  be/src/storage/rowset/segment_iterator.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/com/starrocks/analysis/VectorIndexUtil.java
  fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java
  fe/fe-core/src/main/java/com/starrocks/catalog/IndexParams.java
  fe/fe-core/src/main/java/com/starrocks/common/VectorIndexParams.java
  fe/fe-core/src/main/java/com/starrocks/common/VectorSearchOptions.java
  fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Projection.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteToVectorPlanRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/VectorIndexTest.java
  fe/fe-core/src/test/java/com/starrocks/planner/VectorIndexTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeAlterTableStatementTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeVectorIndexDMLTest.java
  gensrc/thrift/PlanNodes.thrift
  test/sql/test_vector_index/R/test_vector_index
  test/sql/test_vector_index/R/test_vector_index_hnsw
  test/sql/test_vector_index/R/test_vector_index_insert
  test/sql/test_vector_index/R/test_vector_index_ivfpq
  test/sql/test_vector_index/T/test_vector_index
  test/sql/test_vector_index/T/test_vector_index_hnsw
  test/sql/test_vector_index/T/test_vector_index_insert
  test/sql/test_vector_index/T/test_vector_index_ivfpq
Labels: META-REVIEW, PROTO-REVIEW, 3.4

#55199 [BugFix] Support more patterns for mv union rewrite by default
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  test/sql/test_transparent_mv/R/test_transparent_mv_union_hive2
  test/sql/test_transparent_mv/T/test_transparent_mv_union_hive2
Labels: 3.3, 3.4

#55241 [BugFix] Fix reserve error with a large limit
  be/src/exec/chunks_sorter_topn.cpp
  test/sql/test_sort/R/test_topn_with_large_limit
  test/sql/test_sort/T/test_topn_with_large_limit
Labels: 3.0, 3.1, 3.2, 3.3, 3.4

#55219 [BugFix] should acquire db lock out of createLoadTask to avoid dead lock
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java
Labels: 3.3, 3.4

#55194 [BugFix] parquet writer do not perform time zone adjustments when writing timestamp types.
  be/src/formats/parquet/file_writer.cpp
  be/src/formats/parquet/level_builder.cpp
  be/src/formats/parquet/parquet_file_writer.cpp
  test/sql/test_iceberg/R/test_iceberg_catalog_timestamp
  test/sql/test_iceberg/T/test_iceberg_catalog_timestamp
Labels: 3.3, 3.4

#54218 [Feature] Add Transaction Commit/Rollback logical and state
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/common/LoadException.java
  fe/fe-core/src/main/java/com/starrocks/common/NoAliveBackendException.java
  fe/fe-core/src/main/java/com/starrocks/common/TimeoutException.java
  fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadMgr.java
  fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/StatementPlanner.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DMLStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/ExplicitTxnState.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateBatch.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStmtExecutor.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: META-REVIEW

#55271 [Enhancement] upgrade iceberg version to 1.7.1
  fe/fe-core/pom.xml
  java-extensions/pom.xml
Labels: 3.4

#55284 [UT] fix GlobalStateMgrTest.testReloadTables
  fe/fe-core/src/test/java/com/starrocks/server/GlobalStateMgrTest.java
Labels: 3.2, 3.3, 3.4

#55298 [Doc] Fix links
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#54850 [Enhancement] Implement trino function year_of_week
  fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/Trino2SRFunctionCallTransformer.java
  fe/fe-core/src/test/java/com/starrocks/connector/parser/trino/TrinoFunctionTransformTest.java
Labels: behavior_changed

#55283 [Enhancement] Update limitation of M_IVFPQ and is_input_normalized for vector index
  be/src/storage/index/vector/tenann/tenann_index_builder.cpp
  be/test/storage/index/vector_index_test.cpp
  be/test/storage/index/vector_search_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/VectorIndexParams.java
Labels: 3.4

#54881 [Enhancement] Lake compaction scheduler optimize in fe restart scenarios
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionStateSnapshot.java
  fe/fe-core/src/test/java/com/starrocks/catalog/GlobalStateMgrTestUtil.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionMgrTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionSchedulerTest.java
  fe/fe-core/src/test/java/com/starrocks/transaction/DatabaseTransactionMgrTest.java
Labels: behavior_changed, 3.3, 3.4

#55287 [BugFix] Fix wrong result when query cache work with select node
  fe/fe-core/src/main/java/com/starrocks/planner/SelectNode.java
  gensrc/thrift/Normalization.thrift
  test/sql/test_query_cache/R/test_query_cache_select_node
  test/sql/test_query_cache/T/test_query_cache_select_node
Labels: 3.0, 3.1, 3.2, PROTO-REVIEW, 3.3, 3.4

#55042 [BugFix] Fix BE crash if disk is failed
  be/src/storage/tablet_manager.cpp
Labels: 3.2, 3.3, 3.4

#55316 [BugFix] Fix valid normalized null vector for vector index
  be/src/storage/index/vector/tenann/tenann_index_builder.cpp
Labels: 3.4

#55310 [Doc] Add back CN deployment
  docs/en/deployment/deploy_manually.md
  docs/zh/deployment/deploy_manually.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4

#55177 [BugFix] Fix several problem for cluster snapshot backup
  be/src/exec/schema_scanner/schema_cluster_snapshot_jobs_scanner.cpp
  be/src/exec/schema_scanner/schema_cluster_snapshots_scanner.cpp
  fe/fe-core/src/main/java/com/starrocks/alter/AlterHandler.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/ClusterSnapshotsTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshot.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotCheckpointScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotMgr.java
  fe/fe-core/src/main/java/com/starrocks/lake/snapshot/ClusterSnapshotUtils.java
  fe/fe-core/src/main/java/com/starrocks/leader/CheckpointController.java
  fe/fe-core/src/main/java/com/starrocks/persist/ClusterSnapshotLog.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/test/java/com/starrocks/lake/ClusterSnapshotTest.java
  gensrc/thrift/FrontendService.thrift
Labels: META-REVIEW, PROTO-REVIEW, 3.4

#55286 [BugFix] Prune aggregate non-required columns after mv transparent rewrite
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/OpRuleBit.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVTestBase.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
Labels: 3.3, 3.4

#54937 [Enhancement] simd count_zero in arm
  be/src/simd/simd.h
Labels: 3.3, 3.4

#55327 [Enhancement] translate sql use right position when throw exception
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeTranslateTest.java
Labels: 3.3, 3.4

#55056 [BugFix] fix error parameters when replaying drop temp table
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
  fe/fe-core/src/test/java/com/starrocks/catalog/TemporaryTableTest.java
  fe/fe-core/src/test/java/com/starrocks/server/LocalMetaStoreTest.java
Labels: 3.3, 3.4

#55255 [BugFix] Fix error l0 memory usage for cloud native pindex
  be/src/storage/lake/lake_persistent_index.cpp
  be/test/storage/lake/lake_persistent_index_test.cpp
Labels: 3.3, 3.4

#54848 [Enhancement] Optimize Tablet Report
  be/src/agent/heartbeat_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/service/service_be/backend_service.cpp
  be/src/service/service_be/backend_service.h
  be/test/agent/heartbeat_server_test.cpp
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/leader/TabletCollector.java
  fe/fe-core/src/main/java/com/starrocks/memory/MemoryUsageTracker.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
  fe/fe-core/src/main/java/com/starrocks/system/HeartbeatMgr.java
  fe/fe-core/src/test/java/com/starrocks/common/GenericPoolTest.java
  fe/fe-core/src/test/java/com/starrocks/leader/ReportHandlerTest.java
  fe/fe-core/src/test/java/com/starrocks/leader/TabletCollectorTest.java
  gensrc/thrift/BackendService.thrift
  gensrc/thrift/HeartbeatService.thrift
Labels: PROTO-REVIEW

#55355 [BugFix] Ensure transparent mv's output columns with order
  fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/MaterializedViewTransparentRewriteRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/TextMatchBasedRewriteRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvTransparentRewriteWithOlapTableTest.java
  fe/fe-core/src/test/java/com/starrocks/utframe/StarRocksAssert.java
Labels: 3.3, 3.4

#55347 [BugFix] Fix mv partition compensation for iceberg table with transform partition in range materialized view (backport #55151)
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvPartitionCompensator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/compensation/ExternalTableCompensation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/compensation/MVCompensationBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/compensation/OptCompensator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTestBase.java
  test/sql/test_transparent_mv/R/test_mv_with_iceberg_partition_transform
  test/sql/test_transparent_mv/T/test_mv_with_iceberg_partition_transform
Labels: automerge

#55367 [BugFix] PushDownSubfieldRule shouldn't pushdown expr with lambda
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/prunesubfield/SubfieldExpressionCollector.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/ArrayTypeTest.java
Labels: 3.3, 3.4
