Repository StarRocks/starrocks, pull requests merged in 2025-04, with the labels that each got.

#57433 [BugFix] default close flat-json
  be/src/common/config.h
  docs/en/using_starrocks/Flat_json.md
  docs/zh/using_starrocks/Flat_json.md
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/ScanPredicateExprReuseTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/JsonTypeTest.java
Labels: documentation, 3.4, 3.5

#57471 [BugFix] Constant group-by column in grouping-sets should not propagate upwards
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/QueryTransformer.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/GroupingSetsTest.java
Labels: 3.3, 3.4, 3.5

#57483 [BugFix] Disable enable_backup_materialized_view by default since it's experimental
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/management/FE_configuration.md
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: documentation, 3.3, 3.4, 3.5

#57493 [Doc] Update CREATE_STORAGE_VOLUME.md
  docs/en/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md
Labels: documentation, 3.4, 3.5

#57469 [Doc] Fix link in `zh/docs/deployment/shared_data/minio`
  docs/zh/_assets/commonMarkdown/sharedDataUse.md
Labels: documentation

#57145 [Doc] update kafka-connector-starrocks.md
  docs/en/loading/Kafka-connector-starrocks.md
  docs/zh/loading/Kafka-connector-starrocks.md
Labels: documentation, 3.3, 3.4

#57448 [BugFix] fix cache select crash for struct/json/map/array column
  be/src/storage/rowset/array_column_iterator.cpp
  be/src/storage/rowset/array_column_iterator.h
  be/src/storage/rowset/column_iterator.h
  be/src/storage/rowset/json_column_iterator.cpp
  be/src/storage/rowset/map_column_iterator.cpp
  be/src/storage/rowset/map_column_iterator.h
  be/src/storage/rowset/scalar_column_iterator.cpp
  be/src/storage/rowset/scalar_column_iterator.h
  be/src/storage/rowset/segment_iterator.cpp
  be/src/storage/rowset/struct_column_iterator.cpp
Labels: 3.3, 3.4, 3.5

#57454 [BugFix]skip nullable struct for orc
  be/src/formats/orc/apache-orc/c++/src/ColumnReader.cc
  be/test/formats/test_data/orc/nullable_struct.orc
  test/sql/test_external_file/R/test_orc_nullabe_struct
  test/sql/test_external_file/T/test_orc_nullabe_struct
Labels: 3.1, 3.2, 3.3, 3.4, 3.5

#57487 [BugFix] Fix alter column bug for str2date partition table
  fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/com/starrocks/alter/AlterJobV2Test.java
  test/sql/test_schema_change/R/test_schema_change_with_partition_table
  test/sql/test_schema_change/T/test_schema_change_with_partition_table
Labels: 3.3, 3.4, 3.5

#57522 [BugFix] concat(col) should return cloned column instead of original column to avoid abusing sharing column
  be/src/exprs/string_functions.cpp
Labels: 3.1, 3.2, 3.3, 3.4, 3.5

#57311 [BugFix] Fix UAF when spill yield
  be/src/exec/pipeline/pipeline_driver_executor.cpp
  be/src/exec/spill/spill_components.h
  be/src/exec/spill/spiller.hpp
  be/test/io/spill_test.cpp
  test/sql/test_exception/R/test_pipeline_operator_failed
  test/sql/test_exception/T/test_pipeline_operator_failed
Labels: 3.3, 3.4

#57229 [BugFix] Fix broker load ssl_enable does not take effect
  be/src/fs/fs_s3.cpp
Labels: behavior_changed, 3.4

#57468 [Enhancement] turn on avro_ignore_union_type_tag by default
  be/src/common/config.h
  be/test/exec/avro_scanner_test.cpp
  be/test/formats/avro/binary_column_test.cpp
  docs/en/administration/management/BE_configuration.md
  docs/ja/administration/management/BE_configuration.md
  docs/zh/administration/management/BE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#57544 [BugFix] Ensure clear all visible map for all schema changes
  fe/fe-core/src/main/java/com/starrocks/alter/AlterMVJobExecutor.java
  test/sql/test_materialized_view/R/test_mv_inactive
  test/sql/test_materialized_view/T/test_mv_inactive
Labels: 3.4, 3.5

#57470 [BugFix] Fix FE may get incorrect version when enable batch publish in shared data
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 3.3, 3.4, 3.5

#57550 [BugFix] skip shadow partition when auto collect statistics in the background
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsCollectJobFactory.java
  fe/fe-core/src/main/java/com/starrocks/statistic/base/PartitionSampler.java
  fe/fe-core/src/main/java/com/starrocks/statistic/sample/TabletSampleManager.java
Labels: 3.5

#57581 [UT] fix unstable fe ut
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculatorTest.java
Labels: 3.3, 3.4, 3.5

#57430 [BugFix] Fix deadLock when routineLoad task abortTxn
  fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java
Labels: 3.3, 3.4, 3.5

#56849 [BugFix] Fix parallel fail when deploy large plan
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Deployer.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/PhasedScheduleTest.java
Labels: 3.3, 3.4, 3.5

#57610 [BugFix] Only push down join runtime filter to storage only it's root builder
  be/src/exec/olap_scan_prepare.cpp
Labels: 3.5

#57618 [UT] fix sql test
  test/lib/skip.py
  test/sql/test_aa_statistic_behavior/R/test_aa_statistic_behavior
  test/sql/test_aa_statistic_behavior/T/test_aa_statistic_behavior
Labels: 3.5

#57418 [BugFix]Fix Grant CaseSensibility
  fe/fe-core/src/main/java/com/starrocks/authorization/TablePEntryObject.java
Labels: behavior_changed, 3.4, 3.5

#57354 [Enhancement] support retry apply for primary key table
  be/src/common/config.h
  be/src/storage/tablet_updates.cpp
  be/src/storage/tablet_updates.h
  be/test/storage/tablet_updates_test.cpp
Labels: 3.3, 3.4, 3.5

#57579 [BugFix] Exclude all join on-predicate columns in lowcardinality optimization
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/compensation/PartitionRetentionTableCompensation.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
Labels: 3.3, 3.4, 3.5

#57486 [BugFix] fix BE crash because of runtime profile missing when do load spill
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/src/storage/lake/spill_mem_table_sink.h
  be/test/storage/lake/async_delta_writer_test.cpp
Labels: 3.5

#57638 [UT] fix error sql test case
  test/sql/test_analyze_statistics/R/test_analyze_column
  test/sql/test_analyze_statistics/T/test_analyze_column
Labels: 3.5

#56595 [BugFix] should not clean data when commited iceberg snapshot
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: 3.3, 3.4

#57643 [Doc] Update shared-data.md
  docs/en/quick_start/shared-data.md
Labels: documentation, 3.2, 3.3, 3.4, 3.5

#57644 [BugFix] Fix ASAN link with mem_hook
  be/src/common/daemon.cpp
Labels: 3.4, 3.5

#57442 [BugFix] fix jersey conflict behind ranger integration
  fe/pom.xml
Labels: 3.4, 3.5

#57562 [Doc] fix mismatch result in Spark connector doc
  docs/en/unloading/Spark_connector.md
  docs/zh/unloading/Spark_connector.md
Labels: documentation, 3.4, 3.5

#57366 [Enhancement] Add OIDC token expiry validation
  fe/fe-core/src/main/java/com/starrocks/authentication/OpenIdConnectVerifier.java
  fe/fe-core/src/test/java/com/starrocks/authentication/MockTokenUtils.java
  fe/fe-core/src/test/java/com/starrocks/authentication/OpenIdConnectAuthenticationTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
  fe/fe-core/src/test/resources/auth/jwks-private-key.pem
  fe/fe-core/src/test/resources/auth/jwks.json
  fe/fe-core/src/test/resources/auth/signer-jwks.json
Labels: behavior_changed

#57537 [Enhancement] Remove unused function from LogUtils
  fe/fe-core/src/main/java/com/starrocks/common/util/LogUtil.java
Labels: 3.4, 3.5

#57521 [Enhancement] Optimize warehouse idle check
  fe/fe-core/src/main/java/com/starrocks/http/rest/IdleAction.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/IdleStatus.java
  fe/fe-core/src/main/java/com/starrocks/warehouse/WarehouseIdleChecker.java
  fe/fe-core/src/test/java/com/starrocks/qe/ShowExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/warehouse/WarehouseIdleCheckerTest.java
Labels: META-REVIEW, 3.3, 3.4, 3.5

#57674 [BugFix] Remove zero-width space in method call
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
Labels: 3.5

#57686 [BugFix] Fix delta lake un-partitioned mv can not query rewrite
  fe/fe-core/src/main/java/com/starrocks/catalog/DeltaLakeTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/pattern/MultiOpPattern.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateMaterializedViewTest.java
  test/sql/test_materialized_view/R/test_mv_deltalake_rewrite
  test/sql/test_materialized_view/T/test_mv_deltalake_rewrite
Labels: 3.3, 3.4, 3.5

#57655 [BugFix] fix query profile min/max correctness for long-running queries
  fe/fe-core/src/main/java/com/starrocks/common/util/RuntimeProfile.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryRuntimeProfileTest.java
Labels: 3.3, 3.4, 3.5

#57705 [Enhancement] upgrade parquet to 1.15.1 to fix CVE-2025-30065
  fe/pom.xml
  java-extensions/hudi-reader/pom.xml
  java-extensions/pom.xml
Labels: 3.3, 3.4, 3.5

#57706 [UT]Fix unstable statistics sql test
  test/lib/sr_sql_lib.py
  test/sql/test_aa_statistic_behavior/R/test_aa_statistic_behavior
  test/sql/test_aa_statistic_behavior/T/test_aa_statistic_behavior
Labels: 3.5

#57684 [Doc]Update External_table.md
  docs/en/data_source/External_table.md
  docs/ja/data_source/External_table.md
  docs/zh/data_source/External_table.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#57719 [BugFix] avoid checking query_queue_pending_timeout_second when disabled
  fe/fe-core/src/main/java/com/starrocks/qe/QueryQueueManager.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java
Labels: 3.3, 3.4, 3.5

#57717 [Doc] Update sidebar for cluster snapshot
  docs/docusaurus/sidebars.json
Labels: documentation, 3.4, 3.5

#57721 [Doc] 3.3.12 Release Notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#57729 [BugFix]ban low-card optimization for array column with predicate on lake
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/lowcardinality/DecodeCollector.java
  test/sql/test_global_dict/R/global_dict_on_lake
  test/sql/test_global_dict/T/global_dict_on_lake
Labels: 3.5

#57736 [BugFix] Fix log block container causing disk space statistics issues
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/data_stream.cpp
  be/src/exec/spill/dir_manager.h
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/log_block_manager.cpp
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/test/io/spill_block_manager_test.cpp
Labels: 3.3, 3.4, 3.5

#57752 [Doc] A wrong description of the date_diff function
  docs/zh/sql-reference/sql-functions/date-time-functions/date_diff.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#55512 [Doc] Update Flink_connector.md
  docs/en/unloading/Flink_connector.md
Labels: documentation, 3.4

#57704 [UT] Add missing routine load proc UT
  fe/fe-core/src/test/java/com/starrocks/common/proc/RoutineLoadsProcDirTest.java
Labels: 3.1, 3.2, 3.3, 3.4, 3.5

#57190 [Enhancement] add profile metric: output chunk bytes of every operator
  be/src/exec/pipeline/operator.cpp
  be/src/exec/pipeline/operator.h
  be/src/exec/pipeline/pipeline_driver.cpp
Labels: 3.3, 3.4

#57695 [BugFix] Use operator id not node id for feedback
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/OperatorTuningGuides.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/analyzer/JoinTuningAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/analyzer/StreamingAggTuningAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/skeleton/SkeletonBuilder.java
  fe/fe-core/src/main/java/com/starrocks/qe/feedback/skeleton/SkeletonNode.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/Operator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ApplyTuningGuideRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/ExecPlan.java
  fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java
  fe/fe-core/src/test/java/com/starrocks/qe/feedback/analyzer/PlanTuningAnalyzerTest.java
  test/sql/test_feedback/R/test_agg_feedback
  test/sql/test_feedback/T/test_agg_feedback
Labels: 3.5

#57690 [BugFix] fix multi distinct agg function with same distinct col and group by one column with one Tablet property
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithDecimalTypesNewPlannerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java
Labels: 3.2, 3.3, 3.4, 3.5

#57635 [BugFix] Avoid ScalarOperatorsReuse stack overflow
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ArrayOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ArraySliceOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BetweenPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CloneOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CollectionElementOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/MapOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/MatchExprOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/PredicateOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuse.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorsReuseTest.java
Labels: 3.3, 3.4, 3.5

#57651 [BugFix] Fix the bug of the runtime filter cannot be pushed down for iceberg table with equality delete
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/IcebergEqualityDeleteRewriteRule.java
  test/sql/test_iceberg/R/test_iceberg_v2
  test/sql/test_iceberg/T/test_iceberg_v2
Labels: 3.4, 3.5

#57753 [Enhancement] Ldap Group Provider support Cache group
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPGroupProvider.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
Labels: 3.5

#57756 [BugFix] fix slot conflicts in array_map
  be/src/exprs/array_map_expr.cpp
  be/src/exprs/array_map_expr.h
  be/src/exprs/lambda_function.cpp
  be/src/exprs/lambda_function.h
  test/sql/test_array/R/test_array_map
  test/sql/test_array/T/test_array_map
Labels: 3.3, 3.4, 3.5

#57685 [BugFix] Fix the problem of inconsistent that the same Java enumeration class may have different hash values in different JVM instance
  fe/fe-core/src/main/java/com/starrocks/analysis/Expr.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PartitionKey.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PrimitiveType.java
Labels: 3.1, 3.2, 3.3, 3.4, 3.5

#57466 [Doc] Update spill_to_disk.md, Fix grammatical errors
  docs/zh/administration/management/resource_management/spill_to_disk.md
Labels: documentation, 3.3, 3.4, 3.5

#56968 [Doc] list_recursively option was missing in Syntax sequence
  docs/en/sql-reference/sql-functions/table-functions/files.md
  docs/ja/sql-reference/sql-functions/table-functions/files.md
  docs/zh/sql-reference/sql-functions/table-functions/files.md
Labels: documentation, 3.3, 3.4, 3.5

#57786 [Doc]A spelling mistake for value in the bit_shift_left function
  docs/zh/sql-reference/sql-functions/bit-functions/bit_shift_left.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#57596 [Doc] add docs for array/map java UDF
  docs/en/sql-reference/sql-functions/JAVA_UDF.md
  docs/zh/sql-reference/sql-functions/JAVA_UDF.md
Labels: documentation, 3.5

#57573 [Doc] Append a note on TRUNCATE TABLE ... PARTITION to make it much clearer
  docs/en/sql-reference/sql-statements/table_bucket_part_index/TRUNCATE_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/TRUNCATE_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/TRUNCATE_TABLE.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#57270 [Doc] dynamic_overwrite parameter setting for insert overwrite
  docs/en/loading/InsertInto.md
  docs/en/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/ja/loading/InsertInto.md
  docs/ja/sql-reference/sql-statements/loading_unloading/INSERT.md
  docs/zh/loading/InsertInto.md
  docs/zh/sql-reference/sql-statements/loading_unloading/INSERT.md
Labels: documentation, 3.1, 3.2, 3.3, 3.5

#57798 [BugFix] Avoid to copy descTable for each AlterReplicaTask
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java
  test/lib/sr_sql_lib.py
  test/sql/test_rollup/R/test_lake_rollup
  test/sql/test_rollup/R/test_rollup_basic
  test/sql/test_rollup/T/test_lake_rollup
  test/sql/test_rollup/T/test_rollup_basic
Labels: 3.3, 3.4, 3.5

#57580 [Enhancement] Add properties in show create paimon table stmt
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.4, 3.5

#57578 [Enhancement] Use uuid instead of table create time when selecting paimon
  fe/fe-core/src/main/java/com/starrocks/catalog/PaimonTable.java
  fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonMetadata.java
  fe/fe-core/src/test/java/com/starrocks/catalog/PaimonTableTest.java
  fe/fe-core/src/test/java/com/starrocks/common/proc/PaimonPartitionsProcDirTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/paimon/PaimonMetadataTest.java
Labels: 3.3, 3.4, 3.5

#57782 [Enhancement] add try acquire size for load spill
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/file_block_manager.cpp
  be/src/exec/spill/log_block_manager.cpp
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/test/io/spill_block_manager_test.cpp
Labels: 3.5

#57855 [BugFix] [FollowUp] Avoid to copy descTable for each AlterReplicaTask
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java
  fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java
Labels: 3.4, 3.5

#57789 [BugFix] Fix count scalar-subquery rewrite bug
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/QueryOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SPMOptimizer.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleSet.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/RuleType.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/ScalarApplyNormalizeCountRule.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/SubqueryTest.java
Labels: 3.1, 3.2, 3.3, 3.4, 3.5

#57866 [Enhancement] Change ProcProfileCollector Daemon interval to 1s
  fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java
Labels: 3.3, 3.4, 3.5

#57874 [Enhancement] use histogram to estimate in_predicate cardinality
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsUtils.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsEstimateCoefficient.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculatorTest.java
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q16.sql
Labels: 3.5

#57819 [Enhancement] introduce show data distribution command to display data distribution
  fe/fe-core/src/main/java/com/starrocks/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowDataDistributionStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/sql/ast/ShowDataDistributionStmtTest.java
Labels: behavior_changed, 3.4, 3.5

#57639 [Enhancement] Use histograms for join selectivity estimation
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Bucket.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  test/lib/sr_sql_lib.py
  test/sql/test_analyze_statistics/R/test_histogram
  test/sql/test_analyze_statistics/T/test_histogram
Labels: 3.3, 3.4, 3.5

#57857 [Enhancement] Add FE node alive count in metrics
  fe/fe-core/src/main/java/com/starrocks/metric/JsonMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java
Labels: 3.3, 3.4, 3.5

#57745 [Enhancement] support batch put back in pipeline driver queue
  be/src/exec/pipeline/pipeline_driver_queue.cpp
  be/src/exec/pipeline/pipeline_driver_queue.h
  be/src/exec/workgroup/work_group.h
Labels: 3.5

#57899 [Enhancement] Optimize concurrent create partition fail by expression partition
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java
  fe/fe-core/src/test/java/com/starrocks/service/FrontendServiceImplTest.java
Labels: 3.3, 3.4, 3.5

#57851 [Doc] Fix Nav Bar
  docs/docusaurus/sidebars.json
Labels: documentation, 3.3, 3.4, 3.5

#57924 [Doc] Add 3.4.2 Release Notes
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#57939 [UT] Fix testSetResourceGroupID
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
Labels: 3.3, 3.4, 3.5

#57941 [Enhancement] modify analyze multiple columns combined stats syntax
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocksLex.g4
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
  test/sql/test_analyze_statistics/R/test_multi_column_stats
  test/sql/test_analyze_statistics/T/test_multi_column_stats
Labels: 3.5

#57947 [UT] Split test_iceberg_parse_predicates into multiple cases
  test/sql/test_iceberg/R/test_iceberg_parse_predicates_1
  test/sql/test_iceberg/R/test_iceberg_parse_predicates_2
  test/sql/test_iceberg/R/test_iceberg_parse_predicates_3
  test/sql/test_iceberg/T/test_iceberg_parse_predicates_1
  test/sql/test_iceberg/T/test_iceberg_parse_predicates_2
  test/sql/test_iceberg/T/test_iceberg_parse_predicates_3
Labels: 3.5

#57452 [Enhancement] Optimize the disk cache space monitor to simplify the logic of automatic capacity adjustment for datacache.
  be/src/cache/block_cache/datacache_utils.cpp
  be/src/cache/block_cache/datacache_utils.h
  be/src/cache/block_cache/disk_space_monitor.cpp
  be/src/cache/block_cache/disk_space_monitor.h
  be/src/cache/block_cache/starcache_wrapper.cpp
Labels: 3.5

#57910 [Enhancement] add extra AWS properties for iceberg rest catalog with vended credentials
  fe/fe-core/src/main/java/com/starrocks/credential/CloudConfigurationFactory.java
  fe/fe-core/src/test/java/com/starrocks/credential/CloudConfigurationFactoryTest.java
Labels: 3.4, 3.5

#57884 [Doc] Fix a compression format typo
  be/CMakeLists.txt
  be/src/formats/orc/apache-orc/c++/src/Compression.cc
  docs/en/loading/loading_introduction/feature-support-loading-and-unloading.md
  docs/ja/loading/loading_introduction/feature-support-loading-and-unloading.md
  docs/zh/loading/loading_introduction/feature-support-loading-and-unloading.md
Labels: documentation, 3.2, 3.3, 3.4, 3.5

#57755 [BugFix] fix StarMgrMetaSync incorrectly preserving new created shardGroups
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/lake/StarMgrMetaSyncer.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarMgrMetaSyncerTest.java
Labels: 3.2, 3.3, 3.4, 3.5

#57953 [Enhancement] support show multi column stats meta
  fe/fe-core/src/main/java/com/starrocks/persist/EditLogDeserializer.java
  fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ShowStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/AstVisitor.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/ShowMultiColumnStatsMetaStmt.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/main/java/com/starrocks/statistic/AnalyzeMgr.java
  fe/fe-core/src/main/java/com/starrocks/statistic/MultiColumnStatsMeta.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticExecutor.java
  fe/fe-core/src/main/java/com/starrocks/statistic/StatisticsMetaManager.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeStmtTest.java
Labels: META-REVIEW, 3.5

#57615 [Enhancement] Unified test code
  fe/fe-core/src/test/java/com/starrocks/alter/LakeSyncMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/AlterMaterializedViewTest.java
  fe/fe-core/src/test/java/com/starrocks/analysis/CreateSyncMaterializedViewTest.java
Labels: 3.3, 3.4, 3.5

#57984 [Enhancement] Bump avro to 1.12.0 and add avro cpp library
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/avro-1.10.2.c.gcc14.patch
  thirdparty/patches/avro-1.12.0.c.findjansson.patch
  thirdparty/patches/avro-1.12.0.c.patch
  thirdparty/patches/avro-1.12.0.cpp.patch
  thirdparty/vars.sh
Labels: 3.4, 3.5

#57919 [Enhancement] Use query blacklist for stream load BE/CN selection
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java
  fe/fe-core/src/test/java/com/starrocks/http/LoadActionTest.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionOnSharedDataClusterTest.java
Labels: 3.2, 3.3, 3.4, 3.5

#57923 [BugFix] Fix invalid mutable bucket num
  fe/fe-core/src/main/java/com/starrocks/catalog/ExternalOlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/catalog/Partition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/TableProperty.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
Labels: META-REVIEW, 3.3, 3.4, 3.5

#57768 [Enhancement] support current_timestamp(6)
  docs/en/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/ja/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  docs/zh/sql-reference/sql-functions/date-time-functions/current_timestamp.md
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtTest.java
  gensrc/script/functions.py
Labels: documentation, 3.4, 3.5

#58027 [BugFix] fix heap-use-after-free when pk tablet apply retry
  be/src/storage/olap_server.cpp
  be/test/storage/tablet_updates_test.cpp
Labels: 3.3, 3.4, 3.5

#58049 [Doc] Page boost
  docs/en/administration/cluster_snapshot.md
Labels: documentation, 3.4, 3.5

#58052 [Doc] adjust pageBoost placement
  docs/en/administration/cluster_snapshot.md
Labels: documentation, 3.4, 3.5

#58044 [BugFix] fix getTableProperty npe
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/TimeDriftConstraint.java
Labels: 3.5

#58056 [Doc] setup for pageRanking with pageBoost metadata
  docs/en/administration/cluster_snapshot.md
Labels: documentation, 3.4, 3.5

#58032 [BugFix] Fix set_index_filter_only when parsing predicates from runtime filters
  be/src/exec/olap_scan_prepare.cpp
Labels: 3.5

#58022 [BugFix] fix crash caused by spill preagg strategy
  be/src/exec/aggregator.cpp
  be/src/exec/aggregator.h
  be/src/exec/pipeline/aggregate/spillable_aggregate_blocking_sink_operator.cpp
  be/src/exec/sorted_streaming_aggregator.cpp
  test/sql/test_spill/R/test_spill_agg_streaming_strategy
  test/sql/test_spill/T/test_spill_agg_streaming_strategy
Labels: 3.2, 3.3, 3.4, 3.5

#57970 [Enhancement] Support for dynamic linking to support switching jemalloc with debug option
  be/CMakeLists.txt
  bin/start_backend.sh
  build.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/patches/jemalloc_nallocx.patch
Labels: 3.4, 3.5

#58047 [Enhancement] Remove duplicates during join selectivity estimation with histograms
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Bucket.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticRangeValues.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  test/sql/test_analyze_statistics/R/test_histogram
  test/sql/test_analyze_statistics/T/test_histogram
Labels: 3.3, 3.4, 3.5

#58081 [Enhancement][Revert] Remove duplicates during join selectivity estimation with histograms
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Bucket.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Histogram.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/StatisticRangeValues.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  test/sql/test_analyze_statistics/R/test_histogram
  test/sql/test_analyze_statistics/T/test_histogram
Labels: 3.5

#57377 [BugFix] Fix dependency conflict issue in MaxCompute Catalog
  docs/en/data_source/catalog/maxcompute_catalog.md
  docs/zh/data_source/catalog/maxcompute_catalog.md
  fe/fe-core/src/main/java/com/starrocks/connector/odps/OdpsMetadata.java
  fe/fe-core/src/main/java/com/starrocks/connector/odps/OdpsProperties.java
  fe/fe-core/src/test/java/com/starrocks/connector/odps/MockedBase.java
  fe/fe-core/src/test/java/com/starrocks/connector/odps/OdpsMetadataTest.java
  java-extensions/odps-reader/pom.xml
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsSplitScanner.java
  java-extensions/odps-reader/src/main/java/com/starrocks/odps/reader/OdpsSplitScannerFactory.java
  java-extensions/pom.xml
Labels: documentation, 3.3, 3.4, 3.5

#57788 [Enhancement] Support from_unixtime with timezone for table partition
  be/src/exprs/time_functions.cpp
  be/src/exprs/time_functions.h
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctionsTest.java
  gensrc/script/functions.py
  test/sql/test_automatic_partition/R/test_timezone
  test/sql/test_automatic_partition/T/test_timezone
Labels: 3.4, 3.5

#58072 [BugFix] Fix show authentication display password cleartext bug
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
Labels: 3.3, 3.4, 3.5

#58009 [Enhancement] support check large column in pipeline executor
  be/src/column/chunk.h
  be/src/common/config.h
  be/src/exec/pipeline/pipeline_driver.cpp
  test/sql/test_exception/R/test_gen_large_column
  test/sql/test_exception/T/test_gen_large_column
Labels: 3.3, 3.4, 3.5

#58016 [Enhancement] Support nested namespaces for iceberg rest catalog
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateDbAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FeNameFormat.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/fe-core/src/test/java/com/starrocks/common/FeNameFormatTest.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergRESTCatalogTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeCreateDbTest.java
Labels: 3.4, 3.5

#57900 [Doc] versioning info
  docs/docusaurus/sidebars.json
  docs/en/introduction/versioning.md
Labels: documentation, 3.3, 3.4, 3.5

#58030 [BugFix] fix No space left on device error when do load spill
  be/src/exec/spill/block_manager.h
  be/src/exec/spill/hybird_block_manager.cpp
  be/src/storage/lake/load_spill_block_manager.cpp
  be/src/storage/lake/load_spill_block_manager.h
  be/src/storage/lake/spill_mem_table_sink.cpp
  be/src/storage/lake/spill_mem_table_sink.h
  be/test/storage/lake/spill_mem_table_sink_test.cpp
Labels: 3.5

#58102 [Enhancement] Add avro schema builder
  be/CMakeLists.txt
  be/src/formats/CMakeLists.txt
  be/src/formats/avro/cpp/avro_reader.cpp
  be/src/formats/avro/cpp/avro_reader.h
  be/src/formats/avro/cpp/avro_schema_builder.cpp
  be/src/formats/avro/cpp/avro_schema_builder.h
  be/test/CMakeLists.txt
  be/test/formats/avro/cpp/avro_reader_test.cpp
  be/test/formats/test_data/avro/cpp/complex.avro
  be/test/formats/test_data/avro/cpp/complex_nest.avro
  be/test/formats/test_data/avro/cpp/logical.avro
  be/test/formats/test_data/avro/cpp/primitive.avro
Labels: 3.4, 3.5

#58132 [Doc] Change ignore_unknown_log_id to metadata_ignore_unknown_operation_type
  docs/en/administration/Meta_recovery.md
  docs/en/administration/management/FE_configuration.md
  docs/ja/administration/Meta_recovery.md
  docs/ja/administration/management/FE_configuration.md
  docs/zh/administration/Meta_recovery.md
  docs/zh/administration/management/FE_configuration.md
Labels: documentation, 3.3, 3.4, 3.5

#58140 [Doc] add property iceberg.catalog.rest.nested-namespace-enabled doc
  docs/en/data_source/catalog/iceberg/iceberg_catalog.md
  docs/ja/data_source/catalog/iceberg/iceberg_catalog.md
  docs/zh/data_source/catalog/iceberg/iceberg_catalog.md
Labels: documentation, 3.4, 3.5

#58093 [Enhancement] Unify the logic of set password and alter user
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToStringBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/SetPassVar.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UserAuthOption.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/analysis/SetPassVarTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/OpenIdConnectAuthenticationTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/PlainPasswordAuthenticationProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/qe/SetExecutorTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeSetVariableTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerTest.java
  fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2Test.java
Labels: 3.5

#58005 [BugFix] use log4j2 as implementation of slf4j
  java-extensions/hadoop-lib/pom.xml
  java-extensions/java-utils/src/main/java/com/starrocks/utils/loader/ChildFirstClassLoader.java
  java-extensions/pom.xml
Labels: 3.3, 3.4, 3.5

#58115 [BugFix] prune and update histogram after cardinality estimation
  fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/BinaryPredicateStatisticCalculator.java
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsUtils.java
  fe/fe-core/src/test/java/com/starrocks/sql/optimizer/statistics/HistogramStatisticsTest.java
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/histogram-stats/p_type.json
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q10.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q14.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q16.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q17.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q19.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q2.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q20.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q21.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q22.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q3.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q5.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q6.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q7.sql
  fe/fe-core/src/test/resources/sql/tpch-histogram-cost/q8.sql
  test/sql/test_analyze_statistics/R/test_histogram
  test/sql/test_analyze_statistics/T/test_histogram
Labels: 3.5

#57969 [BugFix] Fix the issue of MV refresh failure
  fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitioner.java
  fe/fe-core/src/test/java/com/starrocks/scheduler/mv/MVPCTRefreshRangePartitionerTest.java
Labels: 3.4, 3.5

#58152 [UT] Fix some incorrect load profile counters
  be/src/runtime/lake_tablets_channel.cpp
  be/src/runtime/local_tablets_channel.cpp
  be/test/runtime/local_tablets_channel_test.cpp
Labels: 3.4, 3.5

#58108 [BugFix] Fix flat json config bugs
  fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java
  fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java
Labels: META-REVIEW

#58163 [BugFix] Remove useless fe config enable_block_list_for_stream_load
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/http/rest/LoadAction.java
  fe/fe-core/src/test/java/com/starrocks/http/TransactionLoadActionTest.java
Labels: 3.4, 3.5

#58169 [BugFix] filter non-existent table when querying predicate columns
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
Labels: 3.5

#58096 [Doc] add table-level flat json config doc
  docs/en/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/en/using_starrocks/Flat_json.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/CREATE_TABLE.md
  docs/zh/using_starrocks/Flat_json.md
Labels: documentation

#58189 [Doc] zh 3.3 stable - part 2
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58188 [Doc] zh 3.3 stable - part 1
  docs/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: documentation

#58183 [UT] Fix unstable time zone sql test
  test/sql/test_automatic_partition/R/test_timezone
  test/sql/test_automatic_partition/T/test_timezone
Labels: 3.4, 3.5

#58191 [BugFix]fix compile in arm arch
  be/src/simd/simd.h
Labels: 3.5

#57940 [Doc] update cbo statistics doc
  docs/en/using_starrocks/Cost_based_optimizer.md
  docs/ja/using_starrocks/Cost_based_optimizer.md
  docs/zh/using_starrocks/Cost_based_optimizer.md
Labels: documentation, 3.5

#58212 [Doc] Yank 3.4.1
  docs/en/release_notes/release-3.4.md
  docs/ja/release_notes/release-3.4.md
  docs/zh/release_notes/release-3.4.md
Labels: documentation

#57182 [Feature] Add regexp_count function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_fn_test.cpp
  docs/en/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  docs/ja/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  docs/zh/sql-reference/sql-functions/like-predicate-functions/regexp_count.md
  gensrc/script/functions.py
  test/sql/test_function/R/test_regex
  test/sql/test_function/T/test_regex
Labels: documentation

#56234 [Enhancement] Add storage size property for cloud native partition
  be/src/storage/lake/compaction_scheduler.cpp
  be/src/storage/lake/compaction_scheduler.h
  be/src/storage/lake/compaction_task.cpp
  be/src/storage/lake/compaction_task_context.cpp
  be/src/storage/lake/compaction_task_context.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/vacuum.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/PhysicalPartition.java
  fe/fe-core/src/main/java/com/starrocks/catalog/system/information/PartitionsMetaSystemTable.java
  fe/fe-core/src/main/java/com/starrocks/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionJob.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionScheduler.java
  fe/fe-core/src/main/java/com/starrocks/lake/compaction/CompactionTask.java
  fe/fe-core/src/main/java/com/starrocks/lake/vacuum/AutovacuumDaemon.java
  fe/fe-core/src/main/java/com/starrocks/metric/MetricRepo.java
  fe/fe-core/src/test/java/com/starrocks/lake/VacuumTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/compaction/CompactionTaskTest.java
  gensrc/proto/lake_service.proto
Labels: PROTO-REVIEW, 3.3, 3.4

#58190 [BugFix] fix ngram_search generate invalid plan
  fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/AddIndexOnlyPredicateRule.java
  fe/fe-core/src/test/java/com/starrocks/sql/plan/AddIndexOnlyFilterTest.java
Labels: 3.3, 3.4, 3.5

#57979 [BugFix] store exception at TransactionResult.
  fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionResult.java
  fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  test/sql/test_stream_load/R/test_stream_load_label_already_exist
  test/sql/test_stream_load/T/test_stream_load_label_already_exist
Labels: 3.3, 3.4, 3.5

#58187 [BugFix] Fix ClassCastException caused by alter mv
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJobBase.java
Labels: 3.4, 3.5

#58184 [Enhancement] Display authentication error msg to user client
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationHandler.java
  fe/fe-core/src/main/java/com/starrocks/authentication/AuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProviderForNative.java
  fe/fe-core/src/main/java/com/starrocks/authentication/OAuth2AuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/OIDCSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/authentication/OpenIdConnectAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authentication/SimpleLDAPSecurityIntegration.java
  fe/fe-core/src/main/java/com/starrocks/common/Config.java
  fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java
  fe/fe-core/src/main/java/com/starrocks/mysql/privilege/AuthPlugin.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthenticationAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SetStmtAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UserAuthOptionAnalyzer.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationManagerTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/OpenIdConnectAuthenticationTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/PlainPasswordAuthenticationProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/SecurityIntegrationTest.java
Labels: 3.5

#58153 [Feature] Add avro column reader
  be/src/formats/CMakeLists.txt
  be/src/formats/avro/cpp/avro_reader.cpp
  be/src/formats/avro/cpp/avro_reader.h
  be/src/formats/avro/cpp/binary_column_reader.cpp
  be/src/formats/avro/cpp/binary_column_reader.h
  be/src/formats/avro/cpp/column_reader.cpp
  be/src/formats/avro/cpp/column_reader.h
  be/src/formats/avro/cpp/complex_column_reader.cpp
  be/src/formats/avro/cpp/complex_column_reader.h
  be/src/formats/avro/cpp/date_column_reader.cpp
  be/src/formats/avro/cpp/date_column_reader.h
  be/src/formats/avro/cpp/nullable_column_reader.cpp
  be/src/formats/avro/cpp/nullable_column_reader.h
  be/src/formats/avro/cpp/numeric_column_reader.cpp
  be/src/formats/avro/cpp/numeric_column_reader.h
  be/src/formats/avro/cpp/utils.cpp
  be/src/formats/avro/cpp/utils.h
  be/test/CMakeLists.txt
  be/test/formats/avro/cpp/avro_reader_test.cpp
  be/test/formats/avro/cpp/binary_column_reader_test.cpp
  be/test/formats/avro/cpp/date_column_reader_test.cpp
  be/test/formats/avro/cpp/numeric_column_reader_test.cpp
  be/test/formats/avro/cpp/utils_test.cpp
Labels: 3.4, 3.5

#58196 [UT] test AggregateJoinPushDownRule can apply to subquery
  fe/fe-core/src/test/java/com/starrocks/planner/MaterializedViewAggPushDownRewriteTest.java
Labels: 3.3, 3.4, 3.5

#58238 [Doc] simplified boosting
  docs/en/loading/Loading_intro.md
Labels: documentation, 3.2, 3.3, 3.4, 3.5

#58253 [Doc] upgrade to Docusaurus 3.7
  docs/docusaurus/Dockerfile
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
  docs/en/administration/cluster_snapshot.md
Labels: documentation, 3.1, 3.2, 3.3, 3.4, 3.5

#58182 [BugFix] Fix expression partition fail with month/year granularity
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
Labels: 3.3, 3.4, 3.5

#58265 [Doc] Batch Drop Partition ver
  docs/en/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/ja/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
  docs/zh/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE.md
Labels: documentation, 3.4, 3.5

#58164 [BugFix] Fix uniqueness checking for column unique id in schema change
  fe/fe-core/src/main/java/com/starrocks/alter/LakeRollupJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJob.java
  fe/fe-core/src/main/java/com/starrocks/alter/LakeTableSchemaChangeJobBase.java
  fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeMaterializedView.java
  fe/fe-core/src/main/java/com/starrocks/lake/LakeTable.java
  fe/fe-core/src/test/java/com/starrocks/alter/LakeRollupJobTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/CreateLakeTableTest.java
Labels: 3.3, 3.4, 3.5

#58267 [Doc] 3.3.13 Release Notes
  docs/en/release_notes/release-3.3.md
  docs/ja/release_notes/release-3.3.md
  docs/zh/release_notes/release-3.3.md
Labels: documentation

#58237 [Enhancement] Support security privilege access type
  fe/fe-core/src/main/java/com/starrocks/authorization/AuthorizationMgr.java
  fe/fe-core/src/main/java/com/starrocks/authorization/DefaultAuthorizationProvider.java
  fe/fe-core/src/main/java/com/starrocks/authorization/PrivilegeBuiltinConstants.java
  fe/fe-core/src/main/java/com/starrocks/authorization/PrivilegeType.java
  fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AuthorizerStmtVisitor.java
  test/sql/test_security_integration/R/test_group_provider
  test/sql/test_security_integration/R/test_security_integration
  test/sql/test_security_integration/T/test_group_provider
  test/sql/test_security_integration/T/test_security_integration
Labels: 3.5

#57889 [Enhancement] Support aggregate_tablet_meta read/write
  be/src/storage/lake/location_provider.h
  be/src/storage/lake/tablet_manager.cpp
  be/src/storage/lake/tablet_manager.h
  be/src/storage/protobuf_file.cpp
  be/src/storage/protobuf_file.h
  be/test/storage/lake/tablet_manager_test.cpp
  gensrc/proto/lake_types.proto
Labels: PROTO-REVIEW

#58186 [BugFix] fix partial column update loss under fast schema evolution in cloud native table
  be/src/storage/lake/meta_file.cpp
  be/src/storage/lake/tablet_manager.cpp
  be/test/storage/lake/alter_tablet_meta_test.cpp
Labels: 3.4, 3.5

#58234 [Enhancement] Support display ldap error msg to client
  fe/fe-core/src/main/java/com/starrocks/authentication/LDAPAuthProviderForNative.java
  fe/fe-core/src/main/java/com/starrocks/authentication/PlainPasswordAuthenticationProvider.java
  fe/fe-core/src/main/java/com/starrocks/common/StarRocksException.java
  fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadScheduler.java
  fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/main/java/com/starrocks/mysql/MysqlProto.java
  fe/fe-core/src/main/java/com/starrocks/mysql/security/LdapSecurity.java
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteExceptionHandler.java
  fe/fe-core/src/test/java/com/starrocks/authentication/AuthenticationProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/authentication/PlainPasswordAuthenticationProviderTest.java
  fe/fe-core/src/test/java/com/starrocks/lake/StarOSAgent2ndTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/MysqlAuthPacketTest.java
  fe/fe-core/src/test/java/com/starrocks/mysql/privilege/LdapSecurityTest.java
Labels: 3.5

#58311 [UT] Fix test_percentile_approx_weighted test case
  test/sql/test_agg_function/R/test_percentile_approx_weighted
  test/sql/test_agg_function/T/test_percentile_approx_weighted
Labels: 3.5

#58324 [Doc] Fix some issues with the chinese translation of doc "Window Function".
  docs/en/sql-reference/sql-functions/Window_function.md
  docs/ja/sql-reference/sql-functions/Window_function.md
  docs/zh/sql-reference/sql-functions/Window_function.md
Labels: documentation

#58296 [Enhancement] use IcebergAwsClientFactory to create aws client for iceberg REST catalog with vended credentials
  fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java
  fe/fe-core/src/test/java/com/starrocks/connector/iceberg/IcebergAwsClientFactoryTest.java
  java-extensions/hadoop-ext/src/main/java/com/starrocks/connector/share/iceberg/IcebergAwsClientFactory.java
Labels: 3.4, 3.5

#58278 [BugFix] Fix cancel query for external low cardinality
  be/src/exec/pipeline/fragment_context.cpp
  be/src/exec/pipeline/fragment_context.h
  be/src/exec/pipeline/fragment_executor.cpp
  be/src/exec/pipeline/query_context.cpp
  be/src/exec/pipeline/query_context.h
  be/src/formats/parquet/column_reader_factory.cpp
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/com/starrocks/qe/ExecuteExceptionHandler.java
  fe/fe-core/src/main/java/com/starrocks/qe/scheduler/Deployer.java
  fe/fe-core/src/test/java/com/starrocks/qe/scheduler/StartSchedulingTest.java
  test/sql/test_low_cardinality/R/test_low_cardinality_parquet_cancel
  test/sql/test_low_cardinality/T/test_low_cardinality_parquet_cancel
Labels: 3.5

#58302 [BugFix] Fix admin execute ExecEnv.get_stack_trace_for_all_threads() failed
  be/src/runtime/diagnose_daemon.cpp
  be/src/util/stack_util.cpp
  be/src/util/stack_util.h
  be/test/util/stack_util_test.cpp
Labels: 3.5

#58107 [Feature] Support avro format in files() table function
  be/src/common/config.h
  be/src/connector/file_connector.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/avro_cpp_scanner.cpp
  be/src/exec/avro_cpp_scanner.h
  be/src/exec/file_scanner.cpp
  be/src/formats/avro/cpp/avro_reader.cpp
  be/src/formats/avro/cpp/avro_reader.h
  be/src/formats/avro/cpp/binary_column_reader.cpp
  be/test/CMakeLists.txt
  be/test/exec/avro_cpp_scanner_test.cpp
  be/test/formats/avro/cpp/avro_reader_test.cpp
  fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java
  fe/fe-core/src/main/java/com/starrocks/load/Load.java
  test/sql/test_files/R/test_avro_columns_from_path
  test/sql/test_files/R/test_avro_complex_nest_type
  test/sql/test_files/R/test_avro_complex_type
  test/sql/test_files/R/test_avro_compression
  test/sql/test_files/R/test_avro_data_quality_error
  test/sql/test_files/R/test_avro_files_merge
  test/sql/test_files/R/test_avro_logical_type
  test/sql/test_files/R/test_avro_primitive_type
  test/sql/test_files/T/test_avro_columns_from_path
  test/sql/test_files/T/test_avro_complex_nest_type
  test/sql/test_files/T/test_avro_complex_type
  test/sql/test_files/T/test_avro_compression
  test/sql/test_files/T/test_avro_data_quality_error
  test/sql/test_files/T/test_avro_files_merge
  test/sql/test_files/T/test_avro_logical_type
  test/sql/test_files/T/test_avro_primitive_type
  test/sql/test_files/avro_format/complex.avro
  test/sql/test_files/avro_format/complex_nest.avro
  test/sql/test_files/avro_format/logical.avro
  test/sql/test_files/avro_format/primitive.avro
  test/sql/test_files/avro_format/primitive.deflate.avro
  test/sql/test_files/avro_format/primitive.snappy.avro
  test/sql/test_files/avro_format/user.avro
  test/sql/test_files/avro_format/user1.avro
  test/sql/test_files/avro_format/user2.avro
Labels: 3.4, 3.5

#58174 [Enhancement] Introducing the failpoint injection framework into FE
  bin/start_fe.sh
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java
  fe/fe-core/src/main/java/com/starrocks/common/CommandLineOptions.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/FailPoint.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/FailPointExecutor.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/FailPointHelper.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/README.md
  fe/fe-core/src/main/java/com/starrocks/failpoint/TriggerMode.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/TriggerPolicy.java
  fe/fe-core/src/main/java/com/starrocks/failpoint/failpoint.btm
  fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java
  fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/com/starrocks/sql/ast/UpdateFailPointStatusStatement.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
  fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4
  fe/pom.xml
  gensrc/thrift/FrontendService.thrift
Labels: PROTO-REVIEW
